# Role-separated direct allocation

慢速hazard、相对alpha和快速recovery分别cross-fit，再由直接仓位模型输出SOXL/SOXX/cash。

In [1]:
from pathlib import Path
import sys
import qlib
from qlib.data import D
from qlib.workflow import R
repo_root = Path.cwd().parents[1]
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))
qlib.init(provider_uri=str(repo_root / 'data/qlib/soxl'), region='us', kernels=1, skip_if_reg=False)
calendar = D.calendar(start_time='2011-01-03', end_time='2026-07-02', freq='day')
from src.workflow.role_separated_direct_allocation import run_role_separated_direct_allocation_card
summary = run_role_separated_direct_allocation_card(root=repo_root)
summary['promotion_decision']

[49035:MainThread](2026-07-23 23:12:29,649) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[49035:MainThread](2026-07-23 23:12:29,650) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[49035:MainThread](2026-07-23 23:12:29,650) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[49035:MainThread](2026-07-23 23:12:30,923) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[49035:MainThread](2026-07-23 23:12:30,924) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[49035:MainThread](2026-07-23 23:12:30,924) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[49035:MainThread](2026-07-23 23:12:30,947) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[49035:MainThread](2026-07-23 23:12:30,948) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[49035:MainThread](2026-07-23 23:12:30,949) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[49035:MainThread](2026-07-23 23:12:31,205) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[49035:MainThread](2026-07-23 23:12:31,206) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[49035:MainThread](2026-07-23 23:12:31,207) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

[49035:MainThread](2026-07-23 23:12:31,332) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[49035:MainThread](2026-07-23 23:12:31,333) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[49035:MainThread](2026-07-23 23:12:31,333) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[49035:MainThread](2026-07-23 23:12:31,693) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[49035:MainThread](2026-07-23 23:12:31,694) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[49035:MainThread](2026-07-23 23:12:31,694) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/taleb_fragility_v1')}

[49035:MainThread](2026-07-23 23:12:31,701) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[49035:MainThread](2026-07-23 23:12:31,701) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[49035:MainThread](2026-07-23 23:12:31,702) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/taleb_fragility_v1')}

[49035:MainThread](2026-07-23 23:12:31,705) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[49035:MainThread](2026-07-23 23:12:31,706) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[49035:MainThread](2026-07-23 23:12:31,706) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/taleb_fragility_v1')}

[49035:MainThread](2026-07-23 23:12:31,736) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[49035:MainThread](2026-07-23 23:12:31,737) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[49035:MainThread](2026-07-23 23:12:31,737) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/taleb_fragility_v1')}

[49035:MainThread](2026-07-23 23:12:31,777) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[49035:MainThread](2026-07-23 23:12:31,777) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[49035:MainThread](2026-07-23 23:12:31,777) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[49035:MainThread](2026-07-23 23:13:47,296) INFO - qlib.workflow - [exp.py:258] - Experiment 535417237255137576 starts running ...

[49035:MainThread](2026-07-23 23:13:47,364) INFO - qlib.workflow - [recorder.py:345] - Recorder 3020e2ceb0274c35ad205835862c89cf starts running under Experiment 535417237255137576 ...

[49035:MainThread](2026-07-23 23:13:47,532) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

'not_promoted_role_or_risk_gates_failed'

In [2]:
import pandas as pd
card = Path.cwd()
pd.read_csv(card / 'head_summary.csv')

,role,folds,mean_mae_skill,positive_skill_years,mean_spearman,same_sign_spearman_years,mean_roc_auc,auc_above_060_years
0,alpha,7,-0.024761,3.0,0.191163,7.0,NaN,NaN
1,hazard,7,-0.035210,3.0,-0.020058,3.0,NaN,NaN
2,recovery,7,NaN,NaN,NaN,NaN,0.641208,5.0

In [3]:
pd.read_csv(card / 'model_selection.csv')

,candidate,router,objective,segment,cost_bps,selection_uses_outer_test,return_pct,cagr_pct,annualized_vol_pct,max_drawdown_pct,...,cash_gate,capture_gate,hazard_gate,alpha_gate,recovery_gate,gate_count,all_gate,selection_score,diagnostic_selected,selection_policy
0,crossfit_heads_direct_mse,False,oracle_weight_mse,development_walk_forward,10,False,335.516662,23.421271,35.470600,-54.111197,...,True,False,False,True,True,7,False,-0.418228,False,development_only_all_gates_else_gate_count_the...
1,crossfit_alpha_recovery_direct_mse,False,oracle_weight_mse,development_walk_forward,10,False,344.343315,23.775949,35.646217,-53.765565,...,True,False,False,True,True,8,False,-0.384687,True,development_only_all_gates_else_gate_count_the...
2,crossfit_heads_router_mse,True,oracle_weight_mse,development_walk_forward,10,False,326.156817,23.038373,35.330112,-53.892499,...,True,False,False,True,True,6,False,-0.441184,False,development_only_all_gates_else_gate_count_the...
3,crossfit_alpha_recovery_router_mse,True,oracle_weight_mse,development_walk_forward,10,False,337.169830,23.488165,35.589482,-53.696865,...,False,False,False,True,True,6,False,-0.403915,False,development_only_all_gates_else_gate_count_the...
4,crossfit_alpha_recovery_router_utility,True,relative_wealth_cvar,development_walk_forward,10,False,107.893702,11.034373,42.693748,-67.040431,...,True,False,False,True,True,4,False,-1.827745,False,development_only_all_gates_else_gate_count_the...

In [4]:
pd.read_csv(card / 'window_metrics.csv')

,window,start,end,rows,terminal_wealth_ratio_vs_soxx,avg_cash_weight_pct,avg_soxl_weight_pct,turnover
0,2020_pre_crash,2020-01-02,2020-02-19,33,1.006451,13.952309,14.251819,0.302448
1,2020_crash,2020-02-20,2020-03-23,23,0.912745,13.843312,16.935666,0.083609
2,2020_recovery_early,2020-03-24,2020-05-29,47,1.028185,13.874134,16.669881,0.344144
3,2020_recovery_late,2020-06-01,2020-08-31,65,1.040567,13.517647,16.595789,0.462826
4,2022_bear,2022-01-03,2022-12-30,251,0.905284,16.363452,16.599493,2.429578

In [5]:
pd.read_csv(card / 'objective_gate_audit.csv')

,gate,required,passed,detail
0,no_base_or_prior,True,True,all candidates emit full SOXL/SOXX/cash weights
1,cross_fitted_heads,True,True,allocator training only receives expanding-win...
2,outer_not_used_for_selection,True,True,2023-2026 is selected-candidate validation only
3,development_all_gates,True,False,gate_count=8/12
4,outer_year_robustness,True,False,passing_outer_years=2/4
5,outer_drawdown,True,False,outer_maxdd=-47.01%
6,seed_stability_10bps,True,True,seed_ratio_range=1.0297-1.0439
7,alpha_learnability,True,True,"positive_skill_years=3, same_sign_spearman_yea..."
8,hazard_learnability,True,False,"positive_skill_years=3, same_sign_spearman_yea..."
9,recovery_learnability,True,True,auc_above_060_years=5

# 结论

- 已执行三头cross-fit与直接仓位分配；选择完全不使用outer。
- 开发期诊断候选：`crossfit_alpha_recovery_direct_mse`；10bp相对SOXX=1.0405，25bp=1.0039，MaxDD=-53.77%。
- Outer仅报告：相对SOXX=1.0346，MaxDD=-47.01%。
- 晋升：`not_promoted_role_or_risk_gates_failed`。
- 主要失败门：development_all_gates, outer_year_robustness, outer_drawdown, hazard_learnability。
- 风险：头部可学性不足时，router不能创造新信息；outer不得反向影响模型选择。
- 下一步：根据head_summary判断继续改目标，还是停止网络搜索并补充长期PIT期权/高频数据。
- Qlib recorder：`ca40bd3d6feb4d5eb99015049e026aed`。