# multi-session label 审计（diagnostic-only）

0 新模型；控制模型从已保存 Recorder 读回（全部年度 hash 绑定）；10/25bp 父账户各自独立；label fee=25bp；
固定 5-session 反事实分支（各自 cash/qty/risk clock）；20-session 完整日历分块 bootstrap；outer=reused。

In [1]:
import sys, json, hashlib
from pathlib import Path

ROOT = Path.cwd()
while not (ROOT/'AGENTS.md').exists():
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))
CARD = ROOT/'research'/'stage1_multisession_label_audit_20261010'
print('plan sha256:', hashlib.sha256((CARD/'preregistration_plan.json').read_bytes()).hexdigest())

plan sha256: 9541eddd593fda45fd92fa33e65ed91f3e69561de384a0ec3f8b076e54ec1a3b

In [2]:
# Explicit qlib-native lineage: read the frozen uniform provider directly via qlib D.
import qlib
from qlib.data import D
PROVIDERS = {'intraday':'stage1_uniform_intraday_20261009','execution':'stage1_uniform_execution_marks_20261009','daily':'stage1_uniform_daily_marks_20261009'}
qlib.init(provider_uri=str((ROOT/'data/qlib'/PROVIDERS['intraday']).resolve()), region='us', kernels=1)
cal = D.calendar(freq='15min')
marks = D.features(['SOXL','SOXX'], ['$open','$close'], start_time=str(cal.min().date()), end_time=str(cal.max().date())+' 16:00:00', freq='15min')
print('uniform intraday calendar:', cal[0], '->', cal[-1], '| marks rows:', len(marks))
print('manifest sha:', hashlib.sha256((ROOT/'data/qlib'/PROVIDERS['intraday']/'qlib_store_manifest.json').read_bytes()).hexdigest())

[117:MainThread](2026-10-10 10:36:39,614) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

2026/10/10 10:36:40 INFO mlflow.agent.hint: Load the `instrumenting-with-mlflow-tracing` skill at /Users/rziiiii/dev/workspace/qlib_venv/lib/python3.12/site-packages/mlflow/assistant/skills/instrumenting-with-mlflow-tracing/SKILL.md before writing any tracing code; it ships with this MLflow install. Set MLFLOW_DISABLE_AGENT_HINT=1 to silence this.

[117:MainThread](2026-10-10 10:36:40,084) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[117:MainThread](2026-10-10 10:36:40,084) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_intraday_20261009')}

uniform intraday calendar: 2018-12-31 09:45:00 -> 2026-09-25 16:00:00 | marks rows: 100780
manifest sha: fb6afd75ea128999b1b87bd178e9d54eb7e00f1bd1ee3fc03d657db39c91274a

In [3]:
from src.workflow import multisession_label_audit as workflow
summary = workflow.run_multisession_label_audit(root=ROOT, card_dir=CARD)
print('models_trained:', summary['models_trained'], '| diagnostic_only:', summary['diagnostic_only'])
print('data lineage:', {k:{'as_of':v['as_of'],'manifest_sha256':v['manifest_sha256'][:12]} for k,v in summary['data_lineage'].items()})
print('observed parity 10:', summary['observed_parent_parity'][10])
print('observed parity 25:', summary['observed_parent_parity'][25])
print('training label parity:', summary['training_label_parity'])
print('recorder:', summary['recorder_id'], '| saved:', summary['saved_objects'])

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[117:MainThread](2026-10-10 10:36:42,223) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[117:MainThread](2026-10-10 10:36:42,224) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[117:MainThread](2026-10-10 10:36:42,224) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[117:MainThread](2026-10-10 10:36:42,386) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[117:MainThread](2026-10-10 10:36:42,387) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[117:MainThread](2026-10-10 10:36:42,387) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[117:MainThread](2026-10-10 10:36:42,400) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[117:MainThread](2026-10-10 10:36:42,401) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[117:MainThread](2026-10-10 10:36:42,402) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_intraday_20261009')}

[117:MainThread](2026-10-10 10:37:38,931) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[117:MainThread](2026-10-10 10:37:38,932) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[117:MainThread](2026-10-10 10:37:38,932) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[117:MainThread](2026-10-10 10:37:38,933) WARNING - qlib.workflow - [expm.py:231] - No valid experiment found. Create a new experiment with name stage1_multisession_label_audit_20261010.

[117:MainThread](2026-10-10 10:37:38,935) INFO - qlib.workflow - [exp.py:258] - Experiment 498944341642889372 starts running ...

[117:MainThread](2026-10-10 10:37:39,030) INFO - qlib.workflow - [recorder.py:345] - Recorder 5adde25b815042a78396492ea71169d1 starts running under Experiment 498944341642889372 ...

[117:MainThread](2026-10-10 10:37:39,891) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

models_trained: 0 | diagnostic_only: True
data lineage: {'stage1_uniform_intraday_20261009': {'as_of': '2026-09-25', 'manifest_sha256': 'fb6afd75ea12'}, 'stage1_uniform_execution_marks_20261009': {'as_of': '2026-09-25', 'manifest_sha256': 'd565935ca518'}, 'stage1_uniform_daily_marks_20261009': {'as_of': '2026-09-25', 'manifest_sha256': '48ec582f748d'}}
observed parity 10: {'development_walk_forward': {'status': 'exact', 'rtol': 0, 'atol': 1e-12, 'sessions_equal': True, 'trade_dates_equal': True, 'return': True, 'end_soxl': True, 'end_soxx': True, 'end_cash': True}, 'outer_reused_diagnostic': {'status': 'exact', 'rtol': 0, 'atol': 1e-12, 'sessions_equal': True, 'trade_dates_equal': True, 'return': True, 'end_soxl': True, 'end_soxx': True, 'end_cash': True}}
observed parity 25: {'development_walk_forward': {'status': 'exact', 'rtol': 0, 'atol': 1e-12, 'sessions_equal': True, 'trade_dates_equal': True, 'return': True, 'end_soxl': True, 'end_soxx': True, 'end_cash': True}, 'outer_reused_diagnostic': {'status': 'exact', 'rtol': 0, 'atol': 1e-12, 'sessions_equal': True, 'trade_dates_equal': True, 'return': True, 'end_soxl': True, 'end_soxx': True, 'end_cash': True}}
training label parity: {'n_rows': 2690, 'n_finite': 2688, 'values_exact': True, 'label_available_at_exact': True, 'label_status_match': True, 'boundary_unknown_rows': ['2022-12-21', '2026-09-23'], 'canonical_unknown_identity': {'complete': 2688, 'unknown_segment_boundary': 1, 'unknown_terminal': 1}, 'scope': '10bp training book only; 25bp original label has no saved training-row control and is recomputed from its own 25bp state'}
recorder: 5adde25b815042a78396492ea71169d1 | saved: ['diagnostics_control', 'labels_10', 'labels_25', 'parents_10', 'parents_25', 'trajectories_10', 'trajectories_25']

In [4]:
import pandas as pd
print('=== label comparison (per cost x segment) ==='); display(pd.read_csv(CARD/'label_comparison.csv').round(4))
print('=== OOS IC overall (per cost x segment, 20-session blocks) ==='); display(pd.read_csv(CARD/'oos_ic_overall.csv'))
print('=== freeze manifest ==='); display(json.load(open(CARD/'freeze_manifest.json')))

=== label comparison (per cost x segment) ===

,cost_bps,segment,n_with_orig,sign_disagreement_rate,orig_mean_bps,label_5d_mean_bps,orig_std_bps,label_5d_std_bps,pearson_corr,spearman_corr,risk_state_disagreement_rate,risk_clock_disagreement_rate,recovery_disagreement_rate,eligible_available_sessions
0,10,development_walk_forward,1529,0.2492,2.5413,5.7707,141.6428,266.5397,0.5582,0.4562,0.0255,0.0255,0.0046,1529
1,10,outer_reused_diagnostic,748,0.1818,0.8776,-9.6013,75.5974,166.6203,0.5573,0.5760,0.0134,0.0134,0.0000,748
2,25,development_walk_forward,1513,0.2479,2.9164,5.4734,140.8169,264.2725,0.5575,0.4580,0.0264,0.0264,0.0046,1513
3,25,outer_reused_diagnostic,736,0.1889,2.7218,-5.9497,74.0638,158.5549,0.5454,0.5757,0.0217,0.0217,0.0000,736

=== OOS IC overall (per cost x segment, 20-session blocks) ===

,cost_bps,segment,point,ci_low,ci_high,blocks,status
0,10,development_walk_forward,0.065940,-0.023825,0.151028,1737,ok
1,10,outer_reused_diagnostic,0.066739,-0.065074,0.195913,915,ok
2,25,development_walk_forward,0.072908,-0.016027,0.158342,1737,ok
3,25,outer_reused_diagnostic,0.064089,-0.063677,0.189422,915,ok

=== freeze manifest ===

{'experiment': 'stage1_multisession_label_audit_20261010',
 'plan_pointer': 'preregistration_plan.json',
 'control_recorder': 'e4d888a42c914bf69660ab78a35ba6e7',
 'control_card': 'research/stage1_feasible_action_training_20261009',
 'model_object_sha256': {'model_control_all_state_2016': '9c298d589a2158eb513cb52191144518a2acab2cb0c04f1df14fca0f712fa4a1',
  'model_control_all_state_2017': '194aeaf843787def0f77e8bccb005fbed3fc3bf0b24fe5107072bb8c4581705b',
  'model_control_all_state_2018': 'e1ef03327b6f54fd9cf4e7b4ea1a21d961e4dd1595850f5997441f8660b67038',
  'model_control_all_state_2019': '78728ed47ff40a512e3d66ad8b187efbfed31d3c89518b6f7f5a5e0ab98152b5',
  'model_control_all_state_2020': '77710354e5aa02a23d34c8f67d10bb9c06c1bc6b57640e17467f8d1dfc9f334a',
  'model_control_all_state_2021': '96adcba2ac020c935e6c1dcb3aebbb4971fb08ccff9268064b63ceafe3c1e97d',
  'model_control_all_state_2022': 'e194a5ff5d85676434c88248dd1367b9a051c72507f6f108932a1445754b0995',
  'model_control_all_state_2023': '770acef63a0c0b6fd47425dd14c2f450fc67fb264e78c7c3b6741dbb34ff625e',
  'model_control_all_state_2024': '770acef63a0c0b6fd47425dd14c2f450fc67fb264e78c7c3b6741dbb34ff625e',
  'model_control_all_state_2025': '770acef63a0c0b6fd47425dd14c2f450fc67fb264e78c7c3b6741dbb34ff625e',
  'model_control_all_state_2026': '770acef63a0c0b6fd47425dd14c2f450fc67fb264e78c7c3b6741dbb34ff625e'},
 'replay_training_diagnostics_sha256': {'replays': '510ae5e9c95df55759be5a4ac62b53bf06b70bf6bf4c106eb9e58a6e1780b17d',
  'training_rows_control': 'ce49a677e18c3c2b4c09600378fa58ecd649118020fb987d654f2d7aeb7d5cc9',
  'diagnostics_control': '6dffebbe9b5f3887eb03fa3b08961573c1ea1c8bf915a0f64a949bdff536b1d4'},
 'carry_forward_from_year': {'2024': 2023, '2025': 2023, '2026': 2023},
 'provider_manifest_sha256': {'stage1_uniform_intraday_20261009': 'fb6afd75ea128999b1b87bd178e9d54eb7e00f1bd1ee3fc03d657db39c91274a',
  'stage1_uniform_execution_marks_20261009': 'd565935ca518aecff338631ad993e8a9235ec1c9c39a44b62af75db4f84f27eb',
  'stage1_uniform_daily_marks_20261009': '48ec582f748d1c4f769aac2771569dd320ee4872813fc1f43e096717bde2081f'},
 'prepared_inputs_sha256': '8baa4f74449c1da41eb189f51c75074a61dacb8d7c8540710f4f67560d58d4aa',
 'statistical_corrections': {'bootstrap': 'fixed 20-session moving blocks over the full official calendar, resampled inside the statistic (previous pooled bootstrap was invalid)',
  'cost_accounts': 'both 10bp and 25bp parent own-state accounts computed; label fee fixed at 25bp',
  'five_day_choice': 'unchanged fixed 5-session choice; no horizon/sign/threshold selection'}}

## 中文结论

In [5]:
from IPython.display import Markdown, display
display(Markdown((CARD/'conclusion.md').read_text()))

# multi-session label 审计（diagnostic-only，中文结论）
- 0 新模型；不训练候选、不晋升；控制模型从已保存 Recorder 读回（全部年度 hash 绑定），本轮不调用任何 fit。
- plan sha `9541eddd593f`；control recorder `e4d888a42c914bf69660ab78a35ba6e7`；label fee=25bp；父账户成本 10bp 与 25bp 各自独立。
- observed-parent 精确 parity（rtol=0）：{10: {'development_walk_forward': {'status': 'exact', 'rtol': 0, 'atol': 1e-12, 'sessions_equal': True, 'trade_dates_equal': True, 'return': True, 'end_soxl': True, 'end_soxx': True, 'end_cash': True}, 'outer_reused_diagnostic': {'status': 'exact', 'rtol': 0, 'atol': 1e-12, 'sessions_equal': True, 'trade_dates_equal': True, 'return': True, 'end_soxl': True, 'end_soxx': True, 'end_cash': True}}, 25: {'development_walk_forward': {'status': 'exact', 'rtol': 0, 'atol': 1e-12, 'sessions_equal': True, 'trade_dates_equal': True, 'return': True, 'end_soxl': True, 'end_soxx': True, 'end_cash': True}, 'outer_reused_diagnostic': {'status': 'exact', 'rtol': 0, 'atol': 1e-12, 'sessions_equal': True, 'trade_dates_equal': True, 'return': True, 'end_soxl': True, 'end_soxx': True, 'end_cash': True}}}；10bp training-row label parity values/available/status：True/True/True（rows=2690, finite=2688, boundary_unknown=['2022-12-21', '2026-09-23']）。
## cost 10bp / segment development_walk_forward（独立 bootstrap，不跨段拼接）
- eligible available 1529；by year {2016: 201, 2017: 245, 2018: 246, 2019: 248, 2020: 244, 2021: 198, 2022: 147}。
- sign disagreement 0.2492；orig mean 2.54bp vs 5d mean 5.77bp；std 141.6 vs 266.5；Spearman 0.4561747695664339。
- branch risk_state/clock/recovery 分歧率 0.0255 / 0.0255 / 0.0046。
- 严格因果 OOS（20-session block）：{'point': 0.06594034820500863, 'ci_low': -0.02382479194515184, 'ci_high': 0.15102788176638682, 'blocks': 1737, 'status': 'ok'}；by year=2016:None, 2017:0.14692490350798457, 2018:0.13054009991475604, 2019:0.16854803306211655, 2020:0.020598986406948936, 2021:0.03519752276224995, 2022:-0.069373399118996。
## cost 10bp / segment outer_reused_diagnostic（独立 bootstrap，不跨段拼接）
- eligible available 748；by year {2023: 209, 2024: 226, 2025: 219, 2026: 94}。
- sign disagreement 0.1818；orig mean 0.88bp vs 5d mean -9.60bp；std 75.6 vs 166.6；Spearman 0.5760181010914566。
- branch risk_state/clock/recovery 分歧率 0.0134 / 0.0134 / 0.0000。
- 严格因果 OOS（20-session block）：{'point': 0.06673944516132398, 'ci_low': -0.06507386301796853, 'ci_high': 0.19591268946114151, 'blocks': 915, 'status': 'ok'}；by year=2023:0.2190138808559861, 2024:-0.18292048393175056, 2025:0.13499491585453635, 2026:0.03935267131452516。
## cost 25bp / segment development_walk_forward（独立 bootstrap，不跨段拼接）
- eligible available 1513；by year {2016: 201, 2017: 245, 2018: 246, 2019: 248, 2020: 243, 2021: 189, 2022: 141}。
- sign disagreement 0.2479；orig mean 2.92bp vs 5d mean 5.47bp；std 140.8 vs 264.3；Spearman 0.4580496772549183。
- branch risk_state/clock/recovery 分歧率 0.0264 / 0.0264 / 0.0046。
- 严格因果 OOS（20-session block）：{'point': 0.07290839931662547, 'ci_low': -0.01602686308928399, 'ci_high': 0.15834184459274145, 'blocks': 1737, 'status': 'ok'}；by year=2016:None, 2017:0.14686451949832313, 2018:0.1304490118354046, 2019:0.16845755753849928, 2020:0.03153241305253227, 2021:-0.06796779181997548, 2022:-0.20789845455713002。
## cost 25bp / segment outer_reused_diagnostic（独立 bootstrap，不跨段拼接）
- eligible available 736；by year {2023: 209, 2024: 217, 2025: 215, 2026: 95}。
- sign disagreement 0.1889；orig mean 2.72bp vs 5d mean -5.95bp；std 74.1 vs 158.6；Spearman 0.5756907966419414。
- branch risk_state/clock/recovery 分歧率 0.0217 / 0.0217 / 0.0000。
- 严格因果 OOS（20-session block）：{'point': 0.06408862760489718, 'ci_low': -0.06367681783251708, 'ci_high': 0.18942211407033593, 'blocks': 915, 'status': 'ok'}；by year=2023:0.19783505967716494, 2024:-0.19398878225454136, 2025:0.15137530488541137, 2026:0.05393337066069429。
- native：needs_data（no native cash/quantity reconciliation executed this diagnostic round）。
- 结论边界：本卡只诊断标签口径差异与因果 OOS 信息，未证明新 alpha；outer 为 reused_diagnostic（非 fresh）。
- 下一动作：read-only diagnostic complete; do NOT train a 5-session candidate without a separate pre-registration; outer is reused_diagnostic, never a fresh out-of-sample pass。
- 子 Recorder：5adde25b815042a78396492ea71169d1；parents/labels/trajectories 按 cost 分别保存。