# Drawdown-targeted PIT allocation

成分股与2x标签只参与训练；推理仍只依赖SOXL/SOXX。

In [1]:
from pathlib import Path
import sys
import qlib
from qlib.data import D
from qlib.data.dataset import DatasetH
from qlib.workflow import R
repo_root = Path.cwd().parents[1]
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))
qlib.init(provider_uri=str(repo_root / 'data/qlib/soxl'), region='us', kernels=1, skip_if_reg=False)
calendar = D.calendar(start_time='2011-01-03', end_time='2026-07-02', freq='day')
from src.workflow import run_drawdown_targeted_pit_allocation_card
summary = run_drawdown_targeted_pit_allocation_card(root=repo_root)
summary['promotion_decision']

[5108:MainThread](2026-07-24 11:59:13,523) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[5108:MainThread](2026-07-24 11:59:13,524) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[5108:MainThread](2026-07-24 11:59:13,524) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[5108:MainThread](2026-07-24 11:59:14,828) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[5108:MainThread](2026-07-24 11:59:14,829) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[5108:MainThread](2026-07-24 11:59:14,829) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[5108:MainThread](2026-07-24 11:59:14,851) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[5108:MainThread](2026-07-24 11:59:14,852) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[5108:MainThread](2026-07-24 11:59:14,852) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[5108:MainThread](2026-07-24 11:59:15,105) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[5108:MainThread](2026-07-24 11:59:15,106) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[5108:MainThread](2026-07-24 11:59:15,106) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

[5108:MainThread](2026-07-24 11:59:15,201) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[5108:MainThread](2026-07-24 11:59:15,201) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[5108:MainThread](2026-07-24 11:59:15,202) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[5108:MainThread](2026-07-24 11:59:15,207) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[5108:MainThread](2026-07-24 11:59:15,208) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[5108:MainThread](2026-07-24 11:59:15,208) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[5108:MainThread](2026-07-24 11:59:15,226) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[5108:MainThread](2026-07-24 11:59:15,227) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[5108:MainThread](2026-07-24 11:59:15,228) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxx_pit_leveraged_training_v1')}

[5108:MainThread](2026-07-24 11:59:15,915) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[5108:MainThread](2026-07-24 11:59:15,916) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[5108:MainThread](2026-07-24 11:59:15,916) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[5108:MainThread](2026-07-24 12:00:00,666) INFO - qlib.workflow - [exp.py:258] - Experiment 500529444791250497 starts running ...

[5108:MainThread](2026-07-24 12:00:00,734) INFO - qlib.workflow - [recorder.py:345] - Recorder 4fd1fba883ee49d298e1c6e2d38e8b29 starts running under Experiment 500529444791250497 ...

[5108:MainThread](2026-07-24 12:00:00,848) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

'research_target_30pct_met_not_promoted'

In [2]:
import pandas as pd
card = Path.cwd()
pd.read_csv(card / 'model_selection.csv')

,segment,candidate,cost_bps,selection_uses_outer_test,return_pct,cagr_pct,annualized_vol_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,...,relative_objective_pass,all_gate,research_maxdd_gate,research_worst_5d_gate,research_relative_preservation_gate,research_gate_count,research_target_pass,selection_score,selected,selection_policy
0,development_walk_forward,primary_only,10,False,391.477056,25.573589,37.129835,-48.554616,-12.395221,-5.338706,...,False,False,False,False,True,1,False,0.391811,False,diagnostic_fallback_drawdown_closeness_then_re...
1,development_walk_forward,pit_only_aux_005,10,False,446.497300,27.493875,36.468944,-48.370613,-12.424681,-5.224798,...,True,False,False,False,True,1,False,0.536500,False,diagnostic_fallback_drawdown_closeness_then_re...
2,development_walk_forward,pit_mdd_003,10,False,373.878724,24.920424,37.016438,-52.402500,-12.703816,-5.349941,...,False,False,False,False,True,1,False,0.302324,False,diagnostic_fallback_drawdown_closeness_then_re...
3,development_walk_forward,pit_mdd_ced_008,10,False,384.449790,25.315213,36.490002,-50.342509,-12.518625,-5.242357,...,False,False,False,False,True,1,False,0.295455,False,diagnostic_fallback_drawdown_closeness_then_re...
4,development_walk_forward,pit_cdar_cash_005,10,False,395.181714,25.708529,36.126981,-49.579235,-12.440219,-5.140718,...,False,False,False,False,True,1,False,0.369932,False,diagnostic_fallback_drawdown_closeness_then_re...
5,development_walk_forward,pit_cdar_cash_fast_010,10,False,388.908855,25.479532,37.259166,-50.640556,-13.047125,-5.330500,...,False,False,False,False,True,1,False,0.323684,False,diagnostic_fallback_drawdown_closeness_then_re...
6,development_walk_forward,pit_budget_risky_250,10,False,167.044391,15.082600,22.661992,-29.317278,-7.845988,-3.574100,...,False,False,True,True,True,3,True,-0.582584,True,development_drawdown_target_then_relative_pres...
7,development_walk_forward,pit_budget_beta_400,10,False,158.840523,14.570177,21.908083,-29.142613,-7.219359,-3.437253,...,False,False,True,True,True,3,True,-0.623226,False,development_drawdown_target_then_relative_pres...
8,development_walk_forward,pit_budget_risky_200,10,False,146.287870,13.758513,20.116594,-28.161658,-6.351565,-3.116944,...,False,False,True,True,True,3,True,-0.683890,False,development_drawdown_target_then_relative_pres...

In [3]:
pd.read_csv(card / 'actual_2x_calibration.csv')

,product,underlying,observations,start_date,end_date,daily_rank_correlation,tracking_residual_mean_bps,tracking_residual_rmse_bps
0,NVDL,NVDA,614,2024-01-22,2026-07-02,0.999408,-5.087769,19.299169
1,AMDL,AMD,574,2024-03-19,2026-07-02,0.999563,-4.575493,18.814573
2,MULL,MU,408,2024-11-13,2026-07-02,0.998917,-6.334652,30.954779
3,INTW,INTC,346,2025-02-14,2026-07-02,0.999302,-4.486147,25.434938
4,MVLL,MRVL,331,2025-03-10,2026-07-02,0.998614,-6.593127,32.215322

In [4]:
pd.read_csv(card / 'backtest_walk_forward_metrics.csv')

,fold_year,segment,candidate,cost_bps,selection_uses_outer_test,return_pct,cagr_pct,annualized_vol_pct,max_drawdown_pct,worst_day_pct,...,terminal_wealth,terminal_wealth_ratio_vs_soxx,soxx_terminal_wealth,soxx_return_pct,avg_cash_weight_pct,min_cash_weight_pct,max_cash_weight_pct,zero_cash_days,avg_soxl_weight_pct,avg_soxx_weight_pct
0,2016,development_walk_forward,primary_only,10,False,46.077544,46.077544,23.946900,-14.602559,-4.708363,...,1.460775,1.041581,1.402460,40.246030,46.144384,19.875743,90.751251,0,21.177438,32.678177
1,2017,development_walk_forward,primary_only,10,False,33.208544,33.360810,20.099908,-13.810387,-7.845988,...,1.332085,0.927318,1.436492,43.649187,50.028198,16.037642,97.597320,0,19.462823,30.508979
2,2018,development_walk_forward,primary_only,10,False,-8.683203,-8.716245,31.827566,-27.017078,-7.058978,...,0.913168,1.025431,0.890521,-10.947863,34.897142,15.742432,92.701359,0,21.672917,43.429942
3,2019,development_walk_forward,primary_only,10,False,71.005145,71.005145,30.272548,-21.208793,-4.923678,...,1.710051,1.030408,1.659586,65.958602,26.275641,16.947384,90.442846,0,24.909535,48.814824
4,2020,development_walk_forward,primary_only,10,False,60.529360,60.229326,49.577542,-45.378711,-12.395221,...,1.605294,1.061637,1.512093,51.209284,28.783092,17.945771,79.123077,0,23.717371,47.499537
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,2026,outer_diagnostic,pit_budget_risky_250,10,False,63.983415,180.125030,45.297069,-13.398598,-9.385771,...,1.639834,0.852587,1.923363,92.336260,53.321322,25.000000,78.897011,0,17.689760,28.988918
130,2023,outer_diagnostic,pit_budget_risky_250,25,False,47.917157,48.381139,32.483147,-19.485972,-5.193429,...,1.479172,0.945593,1.564280,56.427971,38.560831,25.000000,66.736600,0,22.591098,38.848071
131,2024,outer_diagnostic,pit_budget_risky_250,25,False,13.032539,13.032539,28.027964,-24.340399,-7.210426,...,1.130325,0.935857,1.207797,20.779705,53.227498,25.000000,91.675095,0,16.871506,29.900996
132,2025,outer_diagnostic,pit_budget_risky_250,25,False,1.081237,1.089934,10.010469,-10.820849,-3.593501,...,1.010812,0.683082,1.479783,47.978263,84.712389,70.314478,97.027223,0,5.519969,9.767642
133,2026,outer_diagnostic,pit_budget_risky_250,25,False,62.969254,176.529043,45.290347,-13.432844,-9.390733,...,1.629693,0.847314,1.923363,92.336260,53.321322,25.000000,78.897011,0,17.689760,28.988918

In [5]:
pd.read_csv(card / 'objective_gate_audit.csv')

,gate,required,passed,evidence
0,development_20pct_excess_10bps,True,False,0.6252987070221045
1,development_25bps_cost_stress,True,False,0.5700535092418672
2,development_positive_relative_years,True,False,2
3,outer_20pct_excess_10bps,True,False,0.5276078994019492
4,outer_25bps_cost_stress,True,False,0.5121896432761677
5,outer_three_of_four_positive_years,True,False,0
6,max_drawdown_minus_20pct,True,False,-29.15760550759061
7,worst_day_minus_12pct,True,True,-9.38577057478538
8,cvar5_minus_8pct,True,True,-4.320431167050476
9,worst_rolling_5d_minus_12pct,True,False,-13.398597822197045
10,average_cash_15pct,True,True,58.05671755930513
11,upside_capture_60pct,True,False,23.77589088214368
12,outer_not_used_for_selection,True,True,development_2016_2022_only
13,development_research_maxdrawdown_target,False,True,-29.317278226133926
14,outer_research_maxdrawdown_target,False,True,-29.15760550759061
15,outer_research_worst_5d_target,False,True,-13.398597822197045
16,outer_research_relative_preservation,False,True,0.5276078994019492

# 结论

- what_ran: 成分股与合成2x标签只进入训练辅助头；开发期和outer推理均只使用原有SOXL/SOXX数据，网络直接输出完整仓位，路径预算候选仅根据此前已实现净值与峰值因果缩放风险仓位。
- key_metrics: 开发期选择 `pit_budget_risky_250`，10bp相对SOXX=0.6253，25bp=0.5701，正超额年份=2/7；outer 10bp=0.5276，MaxDD=-29.16%。
- regime_window: SEC filing_date 后使用PIT成员；更早历史并非PIT，只在单独候选中以0.25权重作为预训练样本。
- promotion_decision: `research_target_30pct_met_not_promoted`；相对目标通过=False，完整风险门=False，30%研究目标=True。
- risks: 失败门为 development_20pct_excess_10bps, development_25bps_cost_stress, development_positive_relative_years, outer_20pct_excess_10bps, outer_25bps_cost_stress, outer_three_of_four_positive_years, max_drawdown_minus_20pct, worst_rolling_5d_minus_12pct, upside_capture_60pct；实际单股2x历史太短，只用于校准合成标签，不伪造早期可交易历史。
- next_action: 30%路径风险目标与跑赢SOXX目标分开判定；只有开发期先达到目标后才解释outer诊断，不用outer反选。
- recorder: `50c560823f6d4eb787969100d3a96b4f`。