# 固定 5-session label 动作消融（候选）

仅换目标为 fixed 5-session label；1 候选 + 7 年度 fit（2017-2023），2016 fallback，2024-2026 carry 2023；
训练用冻结父状态（fixed_parent_state_label_ablation）；原 1 日控制复用 e4 冻结模型/回放不解封；
dev/outer 各自重置；outer=reused_diagnostic。

In [1]:
import sys, json, hashlib
from pathlib import Path

ROOT = Path.cwd()
while not (ROOT/'AGENTS.md').exists():
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))
CARD = ROOT/'research'/'stage1_multisession_action_ablation_20261010'
print('plan sha256:', hashlib.sha256((CARD/'plan.json').read_bytes()).hexdigest())

plan sha256: d16ea7c6be4e0b83654ef1b3e31a3c5b361ce91c624b373ae0db548e03d6808f

In [2]:
# Explicit qlib-native lineage via D on the uniform provider.
import qlib
from qlib.data import D
qlib.init(provider_uri=str((ROOT/'data/qlib/stage1_uniform_intraday_20261009').resolve()), region='us', kernels=1)
cal = D.calendar(freq='15min')
marks = D.features(['SOXL','SOXX'], ['$open','$close'], start_time=str(cal.min().date()), end_time=str(cal.max().date())+' 16:00:00', freq='15min')
print('uniform intraday calendar:', cal[0], '->', cal[-1], '| marks rows:', len(marks))
print('manifest sha:', hashlib.sha256((ROOT/'data/qlib/stage1_uniform_intraday_20261009'/'qlib_store_manifest.json').read_bytes()).hexdigest())

[1555:MainThread](2026-10-10 10:56:59,164) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

2026/10/10 10:56:59 INFO mlflow.agent.hint: Load the `instrumenting-with-mlflow-tracing` skill at /Users/rziiiii/dev/workspace/qlib_venv/lib/python3.12/site-packages/mlflow/assistant/skills/instrumenting-with-mlflow-tracing/SKILL.md before writing any tracing code; it ships with this MLflow install. Set MLFLOW_DISABLE_AGENT_HINT=1 to silence this.

[1555:MainThread](2026-10-10 10:56:59,660) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[1555:MainThread](2026-10-10 10:56:59,660) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_intraday_20261009')}

uniform intraday calendar: 2018-12-31 09:45:00 -> 2026-09-25 16:00:00 | marks rows: 100780
manifest sha: fb6afd75ea128999b1b87bd178e9d54eb7e00f1bd1ee3fc03d657db39c91274a

In [3]:
from src.workflow import multisession_action_ablation as workflow
summary = workflow.run_multisession_action_ablation(root=ROOT, card_dir=CARD)
print('decision:', summary['decision'], '| reasons:', summary['decision_reasons'])
print('candidate_audit:', summary['candidate_audit'])
print('fits:', [(d['model_year'], d['training_rows'], d['model_available'], d['information_cutoff_exclusive']) for d in summary['fit_diagnostics']])
print('native:', summary['native'].get('status'))
print('recorder:', summary['recorder_id'], '| saved:', len(summary['saved_objects']))

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[1555:MainThread](2026-10-10 10:57:01,295) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[1555:MainThread](2026-10-10 10:57:01,296) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[1555:MainThread](2026-10-10 10:57:01,296) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[1555:MainThread](2026-10-10 10:57:01,437) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[1555:MainThread](2026-10-10 10:57:01,438) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[1555:MainThread](2026-10-10 10:57:01,438) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[1555:MainThread](2026-10-10 10:57:01,448) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[1555:MainThread](2026-10-10 10:57:01,449) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[1555:MainThread](2026-10-10 10:57:01,449) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_intraday_20261009')}

[1555:MainThread](2026-10-10 10:57:01,729) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[1555:MainThread](2026-10-10 10:57:01,730) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[1555:MainThread](2026-10-10 10:57:01,731) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[1555:MainThread](2026-10-10 10:57:01,785) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[1555:MainThread](2026-10-10 10:57:01,786) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[1555:MainThread](2026-10-10 10:57:01,786) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[1555:MainThread](2026-10-10 10:57:11,271) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[1555:MainThread](2026-10-10 10:57:11,272) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[1555:MainThread](2026-10-10 10:57:11,272) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[1555:MainThread](2026-10-10 10:57:11,285) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[1555:MainThread](2026-10-10 10:57:11,286) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[1555:MainThread](2026-10-10 10:57:11,286) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[1555:MainThread](2026-10-10 10:57:11,293) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[1555:MainThread](2026-10-10 10:57:11,294) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[1555:MainThread](2026-10-10 10:57:11,294) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[1555:MainThread](2026-10-10 10:57:11,298) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[1555:MainThread](2026-10-10 10:57:11,302) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[1555:MainThread](2026-10-10 10:57:11,305) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[1555:MainThread](2026-10-10 10:57:11,305) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[1555:MainThread](2026-10-10 10:57:11,307) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x122831b50>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[1555:MainThread](2026-10-10 10:57:11,870) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[1555:MainThread](2026-10-10 10:57:11,871) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[1555:MainThread](2026-10-10 10:57:11,871) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[1555:MainThread](2026-10-10 10:57:11,947) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[1555:MainThread](2026-10-10 10:57:11,948) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[1555:MainThread](2026-10-10 10:57:11,948) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[1555:MainThread](2026-10-10 10:57:11,991) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[1555:MainThread](2026-10-10 10:57:12,026) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[1555:MainThread](2026-10-10 10:57:12,115) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[1555:MainThread](2026-10-10 10:57:12,115) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[1555:MainThread](2026-10-10 10:57:12,144) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x122262030>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[1555:MainThread](2026-10-10 10:57:22,037) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[1555:MainThread](2026-10-10 10:57:22,038) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[1555:MainThread](2026-10-10 10:57:22,038) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[1555:MainThread](2026-10-10 10:57:22,049) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[1555:MainThread](2026-10-10 10:57:22,050) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[1555:MainThread](2026-10-10 10:57:22,050) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[1555:MainThread](2026-10-10 10:57:22,054) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[1555:MainThread](2026-10-10 10:57:22,060) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[1555:MainThread](2026-10-10 10:57:22,065) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[1555:MainThread](2026-10-10 10:57:22,065) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[1555:MainThread](2026-10-10 10:57:22,067) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x13c22a5d0>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[1555:MainThread](2026-10-10 10:57:22,546) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[1555:MainThread](2026-10-10 10:57:22,547) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[1555:MainThread](2026-10-10 10:57:22,547) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[1555:MainThread](2026-10-10 10:57:22,624) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[1555:MainThread](2026-10-10 10:57:22,625) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[1555:MainThread](2026-10-10 10:57:22,625) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[1555:MainThread](2026-10-10 10:57:22,668) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[1555:MainThread](2026-10-10 10:57:22,700) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[1555:MainThread](2026-10-10 10:57:22,789) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[1555:MainThread](2026-10-10 10:57:22,790) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[1555:MainThread](2026-10-10 10:57:23,059) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x12d2b83e0>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[1555:MainThread](2026-10-10 10:57:32,899) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[1555:MainThread](2026-10-10 10:57:32,900) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[1555:MainThread](2026-10-10 10:57:32,900) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[1555:MainThread](2026-10-10 10:57:32,980) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[1555:MainThread](2026-10-10 10:57:32,981) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[1555:MainThread](2026-10-10 10:57:32,982) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[1555:MainThread](2026-10-10 10:57:33,026) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[1555:MainThread](2026-10-10 10:57:33,058) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[1555:MainThread](2026-10-10 10:57:33,144) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[1555:MainThread](2026-10-10 10:57:33,144) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[1555:MainThread](2026-10-10 10:57:33,175) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x14599da30>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[1555:MainThread](2026-10-10 10:57:42,507) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[1555:MainThread](2026-10-10 10:57:42,508) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[1555:MainThread](2026-10-10 10:57:42,508) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[1555:MainThread](2026-10-10 10:57:42,587) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[1555:MainThread](2026-10-10 10:57:42,588) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[1555:MainThread](2026-10-10 10:57:42,588) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[1555:MainThread](2026-10-10 10:57:42,633) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[1555:MainThread](2026-10-10 10:57:42,663) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[1555:MainThread](2026-10-10 10:57:42,746) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[1555:MainThread](2026-10-10 10:57:42,746) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[1555:MainThread](2026-10-10 10:57:42,777) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x123f2a5d0>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[1555:MainThread](2026-10-10 10:57:51,627) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[1555:MainThread](2026-10-10 10:57:51,628) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[1555:MainThread](2026-10-10 10:57:51,628) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[1555:MainThread](2026-10-10 10:57:51,630) WARNING - qlib.workflow - [expm.py:231] - No valid experiment found. Create a new experiment with name stage1_multisession_action_ablation_20261010.

[1555:MainThread](2026-10-10 10:57:51,632) INFO - qlib.workflow - [exp.py:258] - Experiment 260193606592673876 starts running ...

[1555:MainThread](2026-10-10 10:57:51,730) INFO - qlib.workflow - [recorder.py:345] - Recorder 8a5ecfdade5c4f20a9786617b3350254 starts running under Experiment 260193606592673876 ...

[1555:MainThread](2026-10-10 10:57:53,038) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

decision: not_promoted | reasons: ['nine_gates_failed', 'dev_paired_ci_vs_control_not_positive', 'dev_paired_ci_vs_soxx_not_positive']
candidate_audit: {'parent_rows': 2690, 'candidate_rows_with_finite_5d_label': 2646, 'excluded_unknown_or_crossyear': 44, 'null_label_filled_with_zero': 0, 'unknown_rows_retained': 44, 'missing_filled_count': 0, 'window_status_counts': {'available': 2646, 'unavailable_cross_year_upstream_identity': 36, 'unavailable_segment_or_gap': 4, 'unavailable_terminal_short': 4}, 'illegal_hold_counterfactual_rows': 374, 'note': 'source identity features are not filtered by routing_eligible; illegal-HOLD rows are counted as a limitation'}
fits: [(2017, 246, True, '2017-01-01T05:00:00+00:00'), (2018, 493, True, '2018-01-01T05:00:00+00:00'), (2019, 740, True, '2019-01-01T05:00:00+00:00'), (2020, 988, True, '2020-01-01T05:00:00+00:00'), (2021, 1237, True, '2021-01-01T05:00:00+00:00'), (2022, 1485, True, '2022-01-01T05:00:00+00:00'), (2023, 1728, True, '2023-01-01T05:00:00+00:00')]
native: passed
recorder: 8a5ecfdade5c4f20a9786617b3350254 | saved: 49

In [4]:
import pandas as pd
print('=== four cost x window ==='); display(pd.read_csv(CARD/'ablation_comparison.csv').round(2))
print('=== nine gates (dev 2017-2022) ==='); display(pd.read_csv(CARD/'gate_results.csv'))
print('=== SOXX matched-cost (relative wealth vs SOXX) ==='); display(pd.read_csv(CARD/'soxx_comparison.csv').round(3))
print('=== paired 20-session block CI ==='); display(pd.read_csv(CARD/'paired_uncertainty.csv').round(2))
print('=== qlib risk_analysis (native-confirmed daily returns) ==='); display(pd.read_csv(CARD/'risk_analysis.csv').round(4))

=== four cost x window ===

,variant,segment,cost_bps,terminal_wealth,return_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,worst_rolling_5d_pct,total_turnover,open_trade_days,recovery_action_count,avg_cash_weight_pct,sharpe
0,candidate_label_5d,development_walk_forward,10.0,3.43,243.30,-29.92,-8.23,-3.81,-10.82,75.84,981,0,48.56,0.86
1,control_all_state,development_walk_forward,10.0,3.00,200.46,-29.03,-7.46,-3.06,-10.82,46.65,638,0,57.84,0.93
2,active_hold_baseline,development_walk_forward,10.0,2.15,114.59,-30.08,-7.11,-3.49,-10.82,102.87,1457,3,54.66,0.62
3,no_hold_reference,development_walk_forward,10.0,2.18,118.19,-29.93,-7.11,-3.47,-10.82,107.62,1721,3,54.09,0.63
4,cash_reference,development_walk_forward,10.0,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0,0,100.00,NaN
5,candidate_label_5d,development_walk_forward,25.0,2.54,153.88,-33.64,-8.23,-3.56,-10.99,65.72,997,0,52.74,0.73
6,control_all_state,development_walk_forward,25.0,2.61,160.83,-30.18,-8.26,-3.08,-10.99,49.02,650,0,58.68,0.83
7,active_hold_baseline,development_walk_forward,25.0,1.97,96.72,-30.09,-7.12,-3.59,-11.89,114.42,1478,3,53.12,0.55
8,no_hold_reference,development_walk_forward,25.0,2.02,102.23,-30.13,-7.12,-3.58,-11.89,112.03,1724,3,53.36,0.57
9,cash_reference,development_walk_forward,25.0,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0,0,100.00,NaN
10,candidate_label_5d,outer_reused_diagnostic,10.0,2.88,188.10,-20.70,-9.27,-4.32,-9.61,33.79,379,0,55.73,1.17
11,control_all_state,outer_reused_diagnostic,10.0,4.63,362.93,-26.48,-8.73,-4.77,-14.55,44.80,558,0,51.71,1.44
12,active_hold_baseline,outer_reused_diagnostic,10.0,3.19,219.49,-26.92,-8.70,-4.80,-14.55,57.43,796,0,48.40,1.13
13,no_hold_reference,outer_reused_diagnostic,10.0,3.20,220.43,-26.92,-8.70,-4.81,-14.55,59.54,918,0,48.22,1.13
14,cash_reference,outer_reused_diagnostic,10.0,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0,0,100.00,NaN
15,candidate_label_5d,outer_reused_diagnostic,25.0,1.83,82.72,-27.24,-9.27,-4.12,-9.67,29.93,326,0,61.39,0.77
16,control_all_state,outer_reused_diagnostic,25.0,4.25,324.74,-26.85,-8.78,-4.69,-14.63,41.69,537,0,53.04,1.38
17,active_hold_baseline,outer_reused_diagnostic,25.0,1.75,75.14,-32.38,-11.20,-4.42,-14.64,50.61,751,0,58.55,0.69
18,no_hold_reference,outer_reused_diagnostic,25.0,1.66,66.12,-36.44,-11.20,-4.40,-14.64,46.93,923,0,59.25,0.64
19,cash_reference,outer_reused_diagnostic,25.0,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0,0,100.00,NaN

=== nine gates (dev 2017-2022) ===

,candidate,reference,status,gate_scope,minimum_annual_wealth_ratio,development_return_above_baseline,stress_25bps_return_above_baseline,max_drawdown_not_worse,worst_day_not_worse,cvar5_not_worse,worst_5d_not_worse,open_trade_days_reduced_8pct,turnover_not_increased,annual_wealth_floor_pass,all_pass
0,candidate_label_5d,no_hold_reference,ok,development_2017_2022,0.808129,True,True,True,False,False,True,True,True,False,False
1,candidate_label_5d,active_hold_baseline,ok,development_2017_2022,0.807251,True,True,True,False,False,True,True,True,False,False

=== SOXX matched-cost (relative wealth vs SOXX) ===

,segment,cost_bps,candidate_return_pct,soxx_return_pct,return_delta_pct_points,relative_wealth_pct,candidate_sharpe,soxx_sharpe,candidate_max_drawdown_pct,soxx_max_drawdown_pct,annual_win_rate,common_years
0,development_walk_forward,10.0,243.305,320.003,-76.698,-18.261,0.864,0.828,-29.923,-47.374,0.286,"[2016, 2017, 2018, 2019, 2020, 2021, 2022]"
1,development_walk_forward,25.0,153.878,319.374,-165.497,-39.463,0.726,0.827,-33.636,-47.374,0.286,"[2016, 2017, 2018, 2019, 2020, 2021, 2022]"
2,outer_reused_diagnostic,10.0,188.098,398.088,-209.990,-42.159,1.169,1.348,-20.699,-42.790,0.250,"[2023, 2024, 2025, 2026]"
3,outer_reused_diagnostic,25.0,82.725,397.343,-314.618,-63.260,0.775,1.347,-27.238,-42.790,0.000,"[2023, 2024, 2025, 2026]"

=== paired 20-session block CI ===

,segment,cost_bps,reference,mean_log_relative_bps,ci_low_bps,ci_high_bps,terminal_wealth_ratio,blocks,block,bootstrap,seed,status
0,development_walk_forward,10.0,control_all_state,0.76,-3.48,5.12,1.14,1737,20,2000,20261010,ok
1,development_walk_forward,10.0,soxx_buy_hold,-1.15,-6.09,3.88,0.82,1737,20,2000,20261010,ok
2,development_walk_forward,25.0,control_all_state,-0.15,-4.02,3.88,0.97,1737,20,2000,20261010,ok
3,development_walk_forward,25.0,soxx_buy_hold,-2.86,-8.19,2.56,0.61,1737,20,2000,20261010,ok
4,outer_reused_diagnostic,10.0,control_all_state,-5.08,-11.72,2.53,0.62,915,20,2000,20261010,ok
5,outer_reused_diagnostic,10.0,soxx_buy_hold,-5.86,-11.11,2.34,0.58,915,20,2000,20261010,ok
6,outer_reused_diagnostic,25.0,control_all_state,-9.03,-16.23,-1.03,0.43,915,20,2000,20261010,ok
7,outer_reused_diagnostic,25.0,soxx_buy_hold,-10.72,-16.54,-1.74,0.37,915,20,2000,20261010,ok

=== qlib risk_analysis (native-confirmed daily returns) ===

,book,segment,cost_bps,mean,std,annualized_return,information_ratio,max_drawdown
0,candidate_label_5d,development_walk_forward,10.0,0.0007,0.0150,0.1820,0.7239,-0.2992
1,candidate_label_5d,development_walk_forward,25.0,0.0005,0.0137,0.1346,0.5992,-0.3364
2,candidate_label_5d,outer_reused_diagnostic,10.0,0.0011,0.0175,0.3095,0.9993,-0.2070
3,candidate_label_5d,outer_reused_diagnostic,25.0,0.0006,0.0158,0.1660,0.6294,-0.2724
4,soxx_buy_hold,development_walk_forward,10.0,0.0008,0.0193,0.2147,0.6549,-0.4737
5,soxx_buy_hold,outer_reused_diagnostic,10.0,0.0017,0.0235,0.5055,1.1284,-0.4279
6,soxx_buy_hold,development_walk_forward,25.0,0.0008,0.0193,0.2145,0.6542,-0.4737
7,soxx_buy_hold,outer_reused_diagnostic,25.0,0.0017,0.0235,0.5049,1.1273,-0.4279

## 中文结论

In [5]:
from IPython.display import Markdown, display
display(Markdown((CARD/'conclusion.md').read_text()))

# 固定 5-session label 动作消融（候选，中文结论）
- 仅把目标换成 fixed 5-session label；1 候选 + 7 年度 fit（2017-2023），2016 fallback，2024-2026 carry 2023；0 调参/选符号/挑窗口。
- training_state=`fixed_parent_state_label_ablation`；continuation=original frozen net_value router；训练用冻结父状态，**不是**候选自身 on-policy 多日标签（off-policy 偏移为限制）。
- 源绑定：diag recorder `5adde25b815042a78396492ea71169d1` labels_10 sha `6f1582fd490e`；control recorder `e4d888a42c914bf69660ab78a35ba6e7`。
- candidate rows：{'parent_rows': 2690, 'candidate_rows_with_finite_5d_label': 2646, 'excluded_unknown_or_crossyear': 44, 'null_label_filled_with_zero': 0, 'unknown_rows_retained': 44, 'missing_filled_count': 0, 'window_status_counts': {'available': 2646, 'unavailable_cross_year_upstream_identity': 36, 'unavailable_segment_or_gap': 4, 'unavailable_terminal_short': 4}, 'illegal_hold_counterfactual_rows': 374, 'note': 'source identity features are not filtered by routing_eligible; illegal-HOLD rows are counted as a limitation'}。
- 决定：`not_promoted`；reasons=['nine_gates_failed', 'dev_paired_ci_vs_control_not_positive', 'dev_paired_ci_vs_soxx_not_positive']；stop_route=end_fixed_label_route_no_parameter_search。
### 原九项门（仅 development 2017-2022，outer 不入 annual 门）
- ref no_hold_reference：status=ok all_pass=False {'development_return_above_baseline': True, 'stress_25bps_return_above_baseline': True, 'max_drawdown_not_worse': True, 'worst_day_not_worse': False, 'cvar5_not_worse': False, 'worst_5d_not_worse': True, 'open_trade_days_reduced_8pct': True, 'turnover_not_increased': True, 'annual_wealth_floor_pass': False, 'all_pass': False}
- ref active_hold_baseline：status=ok all_pass=False {'development_return_above_baseline': True, 'stress_25bps_return_above_baseline': True, 'max_drawdown_not_worse': True, 'worst_day_not_worse': False, 'cvar5_not_worse': False, 'worst_5d_not_worse': True, 'open_trade_days_reduced_8pct': True, 'turnover_not_increased': True, 'annual_wealth_floor_pass': False, 'all_pass': False}
### SOXX 同费用比较（relative wealth = candidate 相对 SOXX 的比值；非相对 control）
- development_walk_forward @10bp：cand 243.30% vs SOXX 320.00%；relative_wealth(vs SOXX) -18.26%；return_delta -76.70pp；annual win rate 0.2857142857142857。
- development_walk_forward @25bp：cand 153.88% vs SOXX 319.37%；relative_wealth(vs SOXX) -39.46%；return_delta -165.50pp；annual win rate 0.2857142857142857。
- outer_reused_diagnostic @10bp：cand 188.10% vs SOXX 398.09%；relative_wealth(vs SOXX) -42.16%；return_delta -209.99pp；annual win rate 0.25。
- outer_reused_diagnostic @25bp：cand 82.72% vs SOXX 397.34%；relative_wealth(vs SOXX) -63.26%；return_delta -314.62pp；annual win rate 0.0。
### paired 20-session block uncertainty（cost×segment 独立）
- development_walk_forward @10bp vs control_all_state：mean log rel 0.7591610230077076 CI [-3.4751773049469783,5.118994371916654] blocks=1737 status=ok。
- development_walk_forward @10bp vs soxx_buy_hold：mean log rel -1.1483054657248597 CI [-6.091697341927533,3.8786254136290736] blocks=1737 status=ok。
- development_walk_forward @25bp vs control_all_state：mean log rel -0.15374526384879753 CI [-4.015693198838716,3.882141612769863] blocks=1737 status=ok。
- development_walk_forward @25bp vs soxx_buy_hold：mean log rel -2.8582629596646165 CI [-8.18806676844673,2.5565201845051155] blocks=1737 status=ok。
- outer_reused_diagnostic @10bp vs control_all_state：mean log rel -5.077915812120868 CI [-11.717828213665308,2.5299297396204965] blocks=915 status=ok。
- outer_reused_diagnostic @10bp vs soxx_buy_hold：mean log rel -5.8616244209897115 CI [-11.106207762047015,2.336803691659608] blocks=915 status=ok。
- outer_reused_diagnostic @25bp vs control_all_state：mean log rel -9.031009497883245 CI [-16.22957612078406,-1.0327603758259134] blocks=915 status=ok。
- outer_reused_diagnostic @25bp vs soxx_buy_hold：mean log rel -10.72054859424792 CI [-16.540205563703005,-1.74474833266595] blocks=915 status=ok。
- native：passed。
- 边界：outer=reused_diagnostic（非 fresh）；历史看似通过仍需独立前向，不替换现役；诊断 CI 不明确只是探索，不预称 predictive gate 通过。
- 子 Recorder：8a5ecfdade5c4f20a9786617b3350254。