# Stateful direct SOXL/SOXX/cash allocation

单个模型直接输出最终合法仓位；outer 不参与选择。

In [1]:
from pathlib import Path
import sys
import qlib
from qlib.data import D
from qlib.data.dataset import DatasetH
from qlib.workflow import R
repo_root = Path.cwd().parents[1]
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))
qlib.init(provider_uri=str(repo_root / 'data/qlib/soxl'), region='us', kernels=1, skip_if_reg=False)
calendar = D.calendar(start_time='2016-01-01', end_time='2026-12-31', freq='day')
from src.workflow.stateful_direct_allocation import run_stateful_direct_allocation_card
summary = run_stateful_direct_allocation_card(root=repo_root)
summary['decision']

[38750:MainThread](2026-07-25 00:16:40,463) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[38750:MainThread](2026-07-25 00:16:40,464) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[38750:MainThread](2026-07-25 00:16:40,464) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[38750:MainThread](2026-07-25 00:16:42,262) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[38750:MainThread](2026-07-25 00:16:42,263) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[38750:MainThread](2026-07-25 00:16:42,264) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[38750:MainThread](2026-07-25 00:16:42,292) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[38750:MainThread](2026-07-25 00:16:42,293) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[38750:MainThread](2026-07-25 00:16:42,294) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[38750:MainThread](2026-07-25 00:16:42,572) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[38750:MainThread](2026-07-25 00:16:42,573) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[38750:MainThread](2026-07-25 00:16:42,573) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

[38750:MainThread](2026-07-25 00:16:42,701) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[38750:MainThread](2026-07-25 00:16:42,702) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[38750:MainThread](2026-07-25 00:16:42,702) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[38750:MainThread](2026-07-25 00:16:42,748) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[38750:MainThread](2026-07-25 00:16:42,749) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[38750:MainThread](2026-07-25 00:16:42,749) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

[38750:MainThread](2026-07-25 00:16:43,621) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[38750:MainThread](2026-07-25 00:16:43,622) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[38750:MainThread](2026-07-25 00:16:43,622) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[38750:MainThread](2026-07-25 00:16:43,642) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[38750:MainThread](2026-07-25 00:16:43,643) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[38750:MainThread](2026-07-25 00:16:43,644) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[38750:MainThread](2026-07-25 00:16:43,919) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[38750:MainThread](2026-07-25 00:16:43,920) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[38750:MainThread](2026-07-25 00:16:43,920) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

[38750:MainThread](2026-07-25 00:16:44,021) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[38750:MainThread](2026-07-25 00:16:44,022) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[38750:MainThread](2026-07-25 00:16:44,023) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[38750:MainThread](2026-07-25 00:16:44,045) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[38750:MainThread](2026-07-25 00:16:44,046) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[38750:MainThread](2026-07-25 00:16:44,046) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[38750:MainThread](2026-07-25 00:20:33,948) INFO - qlib.workflow - [exp.py:258] - Experiment 466222303248987930 starts running ...

[38750:MainThread](2026-07-25 00:20:34,028) INFO - qlib.workflow - [recorder.py:345] - Recorder 7943709a719f4ca9b82513476e7c92df starts running under Experiment 466222303248987930 ...

[38750:MainThread](2026-07-25 00:20:34,124) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | waiting `async_log` Done

'retain_current_stage1_stateful_direct_model_not_promoted'

In [2]:
import pandas as pd
card = Path.cwd()
pd.read_csv(card / 'model_selection.csv')

,candidate,segment,selection_uses_outer_test,name,recurrent_units,teacher_loss_weight,risk_loss_weight,turnover_loss_weight,trade_loss_weight,trade_threshold,...,risk_window_pass_count,positive_relative_window_count,relative_ratio_min,relative_ratio_p25,relative_ratio_median,open_turnover,open_active_day_count,open_material_day_count,avg_cash_weight_pct,development_gate_pass
0,gru8_imitation_gate,development_walk_forward,False,gru8_imitation_gate,8,20.0,5.0,0.02,1.0,0.6,...,0,6,0.995007,1.054300,1.091587,70.472204,889,655,35.288610,False
1,gru16_imitation_gate,development_walk_forward,False,gru16_imitation_gate,16,20.0,10.0,0.03,1.0,0.6,...,0,3,0.888444,0.931573,0.987105,93.702811,894,761,37.684549,False
2,gru16_tail_gate,development_walk_forward,False,gru16_tail_gate,16,10.0,20.0,0.04,1.5,0.7,...,0,4,0.938908,0.969952,1.001749,59.886818,515,448,39.501872,False

In [3]:
pd.read_csv(card / 'risk_analysis.csv')

,scenario,terminal_wealth,return_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,worst_rolling_5d_pct
0,stateful_outer_10bps,5.251761,425.176143,-39.242191,-9.789360,-5.775415,-16.127359
1,stateful_dynamic_25bps,4.557096,355.709645,-40.263556,-9.744258,-5.782446,-16.110766
2,stateful_fixed_25bps,4.888218,388.821815,-40.363521,-9.789360,-5.783410,-16.158592
3,stage1_outer_10bps,6.433420,543.342018,-28.105110,-9.383715,-5.233616,-11.602809
4,stage1_dynamic_25_open_10_intraday,4.835582,383.558196,-29.073039,-9.383715,-5.193444,-11.725467

In [4]:
pd.read_csv(card / 'turnover_analysis.csv')

,model,open_turnover,active_days,material_days,avg_cash_weight_pct
0,stateful_direct,47.861361,810,562,38.588899
1,current_stage1,61.873906,404,403,36.099520

In [5]:
pd.read_csv(card / 'annual_metrics.csv')

,year,terminal_wealth,return_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,worst_rolling_5d_pct,terminal_wealth_ratio_vs_soxx,avg_cash_weight_pct,recovery_action_count
0,2023,1.505482,50.548151,-22.772209,-6.220075,-4.382049,-8.592562,0.959999,34.266256,0
1,2024,1.219807,21.980739,-27.924485,-9.789360,-4.929256,-16.127359,1.009945,45.030938,0
2,2025,1.557641,55.764126,-26.394353,-9.652312,-5.677633,-14.047672,1.052615,41.567658,0
3,2026,1.835992,83.599232,-28.928794,-8.912285,-7.585282,-15.019469,1.078205,29.191654,0

# 结论

- what_ran: 保留冻结 qlib walk-forward 特征编码作为初始化，在同一个最终仓位头中加入因果 GRU 账户状态；模型直接输出 SOXL/SOXX/cash，已删除推理时 cap/wait/ramp 和底仓加 overlay。
- key_metrics: development 25bp return=217.2719%，MaxDD=-43.0651%，worst 5d=-26.9498%；outer 10bp return=425.1761%，MaxDD=-39.2422%，worst 5d=-16.1274%。
- regime_window: 候选只由 2019-2022 年度与两年 development 窗口选择；2023-至今 outer 只在选择冻结后诊断。
- turnover: outer 开盘换手由 61.8739 降至 47.8614，变化 22.65%；活跃日 810 对 404。
- promotion_decision: `retain_current_stage1_stateful_direct_model_not_promoted`；development gate=False，完整替换门=False。
- risks: outer 已被此前多轮研究重复观察，不是全新未见测试；教师来自当前 Stage1，只用于 development 行为压缩，outer 标签不参与训练或选择；尚未验证真实 bid/ask、延迟和排队。
- next_action: 若 development 风险门失败，停止扩大网络或使用 outer 调参；只保留该结构证据并继续使用当前 Stage1。
- recorder: `d015df77b5814988bba1f76ab65fdd21`。
- 不构成买卖建议。