# Direct continuous SOXL/SOXX/cash allocation

模型直接输出完整连续权重；没有底仓、规则先验或候选仓位表。

In [1]:
from pathlib import Path
import sys
import qlib
from qlib.data import D
from qlib.workflow import R
repo_root = Path.cwd().parents[1]
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))
qlib.init(provider_uri=str(repo_root / 'data/qlib/soxl'), region='us', kernels=1, skip_if_reg=False)
calendar = D.calendar(start_time='2011-01-03', end_time='2026-12-31', freq='day')
from src.workflow.direct_continuous_soxx_allocation import run_direct_continuous_soxx_allocation_card
summary = run_direct_continuous_soxx_allocation_card(root=repo_root)
summary['promotion_decision']

[4418:MainThread](2026-07-23 17:34:08,225) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[4418:MainThread](2026-07-23 17:34:08,226) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[4418:MainThread](2026-07-23 17:34:08,226) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[4418:MainThread](2026-07-23 17:34:09,571) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[4418:MainThread](2026-07-23 17:34:09,572) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[4418:MainThread](2026-07-23 17:34:09,573) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[4418:MainThread](2026-07-23 17:34:09,599) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[4418:MainThread](2026-07-23 17:34:09,600) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[4418:MainThread](2026-07-23 17:34:09,600) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[4418:MainThread](2026-07-23 17:34:09,876) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[4418:MainThread](2026-07-23 17:34:09,877) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[4418:MainThread](2026-07-23 17:34:09,877) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

[4418:MainThread](2026-07-23 17:34:10,010) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[4418:MainThread](2026-07-23 17:34:10,010) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[4418:MainThread](2026-07-23 17:34:10,010) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[4418:MainThread](2026-07-23 17:34:35,557) INFO - qlib.workflow - [exp.py:258] - Experiment 742080559585064672 starts running ...

[4418:MainThread](2026-07-23 17:34:35,634) INFO - qlib.workflow - [recorder.py:345] - Recorder ac3d6a35da02423aa369aa95fc76b9fa starts running under Experiment 742080559585064672 ...

[4418:MainThread](2026-07-23 17:34:35,780) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

'needs_iteration_direct_continuous_allocation'

In [2]:
import pandas as pd
card = Path.cwd()
pd.read_csv(card / 'model_selection.csv')

,profile,selection_uses_outer_test,return_pct,cagr_pct,annualized_vol_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,worst_rolling_5d_pct,avg_soxl_position_pct,...,cost_stress_gate,year_gate,drawdown_gate,recovery_gate,cash_gate,gate_count,all_gate,selection_score,selected,selection_policy
0,return_stability,False,449.221773,27.584584,42.647355,-52.997180,-14.773092,-6.488598,-31.121403,23.241362,...,False,False,False,False,False,1,False,0.280169,False,diagnostic_fallback_maximum_gate_count_then_score
1,turnover_stability,False,1079.800812,42.327665,44.806412,-51.540994,-14.770475,-6.456569,-31.126391,26.616908,...,True,True,False,False,True,4,False,1.431756,True,diagnostic_fallback_maximum_gate_count_then_score
2,tail_supervised,False,584.169525,31.657174,43.574377,-52.031614,-14.655225,-6.301924,-30.829643,26.169823,...,True,True,False,False,True,4,False,0.701188,False,diagnostic_fallback_maximum_gate_count_then_score
3,low_leverage,False,270.542079,20.602065,36.978231,-45.824137,-12.955359,-5.600260,-26.699662,14.737069,...,False,False,True,False,False,1,False,-0.076745,False,diagnostic_fallback_maximum_gate_count_then_score

In [3]:
pd.read_csv(card / 'backtest_benchmark_comparison.csv')

,segment,profile,cost_bps,selection_uses_outer_test,return_pct,cagr_pct,annualized_vol_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,...,avg_soxl_weight_pct,avg_soxx_weight_pct,longest_underwater_days,max_drawdown_recovery_days,soxx_max_drawdown_pct,soxx_longest_underwater_days,soxx_max_drawdown_recovery_days,downside_avg_cash_weight_pct,downside_min_cash_weight_pct,turnover
0,development_walk_forward,turnover_stability,10,False,1079.800812,42.327665,44.806412,-51.540994,-14.770475,-6.456569,...,26.616908,62.317284,272,54,-47.374011,257,56,17.224356,0.000145,147.741615
1,development_walk_forward,turnover_stability,25,False,844.947931,37.880277,44.826079,-51.672827,-14.770475,-6.467484,...,26.616908,62.317284,276,54,-47.374011,257,56,17.224356,0.000145,147.741615
2,outer_diagnostic,turnover_stability,10,False,723.496050,83.786948,50.876609,-60.763552,-13.137449,-7.190336,...,24.408609,58.400922,377,193,-42.790391,297,113,40.351102,0.001671,74.785830
3,outer_diagnostic,turnover_stability,25,False,635.946957,77.919576,50.902913,-63.047819,-13.182406,-7.197550,...,24.408609,58.400922,383,199,-42.790391,297,113,40.351102,0.001671,74.785830

In [4]:
pd.read_csv(card / 'objective_gate_audit.csv')

,gate,required,passed,evidence
0,no_base_or_prior,True,True,base_constrained_ref_role=none
1,no_candidate_weight_grid,True,True,network emits three continuous logits and soft...
2,outer_not_used_for_selection,True,True,2016_2022_development_only
3,development_20pct_excess_10bps,True,True,2.7625666258664983
4,development_25bps_stress,True,True,2.2160857449041003
5,development_year_stability,True,True,6
6,development_maxdd_better_than_soxx,True,False,-51.540994 vs -47.374011
7,development_recovery_better_than_soxx,True,False,underwater 272 vs 257; recovery 54 vs 56
8,development_model_uses_cash_in_downside,True,True,17.224356 vs 11.065809
9,outer_20pct_excess_10bps,True,True,1.5291118875789838
10,outer_maxdd_better_than_soxx,True,False,-60.763552 vs -42.790391
11,outer_recovery_better_than_soxx,True,False,underwater 377 vs 297; recovery 193 vs 113
12,outer_model_uses_cash_in_downside,True,True,40.351102 vs 17.190471
13,legacy_absolute_worst_5d_minus_12pct,False,False,-22.50204918841101

In [5]:
pd.read_csv(card / 'regime_metrics.csv')

,regime,rows,terminal_wealth_ratio_vs_soxx,avg_soxl_weight_pct,avg_soxx_weight_pct,avg_cash_weight_pct
0,all,873,1.527579,24.408609,58.400922,17.190471
1,uptrend,625,1.699053,27.388346,64.611324,8.000332
2,downtrend,248,0.899076,16.899193,42.749706,40.351102
3,high_volatility,437,1.416350,22.024764,54.171487,23.803750

# 纯模型连续 SOXL/SOXX/cash 配置结论

- 跑了什么：模型直接输出三资产连续权重；没有SOXX底仓、规则先验或合法仓位表。
- 开发期：10bp财富/SOXX=2.7626，25bp=2.2161，MaxDD=-51.54% vs SOXX -47.37%。
- 年份稳定性：6/7 个开发年份相对收益为正。
- Outer仅诊断：10bp财富/SOXX=1.5291，MaxDD=-60.76% vs SOXX -42.79%。
- 现金行为：开发期总体平均 11.07%，下跌期 17.22%；outer总体 17.19%，下跌期 40.35%。
- 晋升决定：needs_iteration_direct_continuous_allocation。
- 风险：直接日频权重模型可能以高换手换取样本内相对收益；MaxDD、恢复期和25bp结果必须同时通过，不能只看终值。
- 下一步：若失败，只调整模型的时序状态和训练目标；不恢复底仓、先验或外层参数选择。