# SOXL 高位耗竭、内部结构与杠杆脆弱性因子实验

## tl;dr

本实验不用预测模型。开发期筛选与 2023–2026 SOXL 外层完全分离，并要求新增因子对 price-only 基线有条件增量。

## Context & Methods

### Key Assumptions

- 日线数据通过 `qlib.data.D.features` 读取，DatasetH 只用于可复现分段证据。
- 所有因子滞后一完整交易日，方向统一为数值越高、未来 breakdown 压力越高。
- 固定 NVDA/AVGO/AMD/TSM/ASML 只是 bellwether proxy，不代表历史 SOXX 成分股。
- SOXL/SOXX 15 分钟数据可用于 2019 起的路径诊断；外部五龙头 15 分钟完整覆盖只从 2025 起，因此阻断长期筛选。

In [1]:
from pathlib import Path
import json
import sys
import pandas as pd
from IPython.display import display, Markdown

ROOT = Path.cwd().resolve()
while ROOT != ROOT.parent and not (ROOT / 'AGENTS.md').exists():
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))
from src.workflow.soxl_exhaustion_structure_fragility import run_soxl_exhaustion_structure_fragility_card
CARD = ROOT / 'research' / 'soxl_exhaustion_structure_fragility_v1'
ROOT

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1')

## Data

重新执行 qlib 原始 provider 读取、点时因子构造、派生 store 回读、DatasetH 分段和 Recorder 留痕。

In [2]:
summary = run_soxl_exhaustion_structure_fragility_card(root=ROOT)
{
    'status': summary['status'],
    'as_of': summary['as_of'],
    'promotion_decision': summary['promotion_decision'],
    'dataset': summary['qlib_contract']['dataset_evidence'],
    'intraday_coverage': summary['data_quality']['intraday_coverage'],
}

[16503:MainThread](2026-07-19 17:41:43,034) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:43,518) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:43,518) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/soxl')}

[16503:MainThread](2026-07-19 17:41:43,544) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:43,545) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:43,546) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/tqqq')}

[16503:MainThread](2026-07-19 17:41:43,568) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:43,570) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:43,570) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/upro')}

[16503:MainThread](2026-07-19 17:41:43,592) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:43,594) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:43,595) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/spxl')}

[16503:MainThread](2026-07-19 17:41:43,616) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:43,618) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:43,618) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/tecl')}

[16503:MainThread](2026-07-19 17:41:43,639) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:43,641) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:43,642) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/udow')}

[16503:MainThread](2026-07-19 17:41:43,664) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:43,666) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:43,666) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/tna')}

[16503:MainThread](2026-07-19 17:41:43,687) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:43,689) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:43,690) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/midu')}

[16503:MainThread](2026-07-19 17:41:43,712) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:43,714) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:43,715) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/fas')}

[16503:MainThread](2026-07-19 17:41:43,741) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:43,743) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:43,743) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/labu')}

[16503:MainThread](2026-07-19 17:41:43,760) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:43,762) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:43,763) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/cure')}

[16503:MainThread](2026-07-19 17:41:43,851) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:43,853) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:43,854) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/nail')}

[16503:MainThread](2026-07-19 17:41:43,872) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:43,874) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:43,874) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/retl')}

[16503:MainThread](2026-07-19 17:41:43,894) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:43,895) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:43,896) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/erx')}

[16503:MainThread](2026-07-19 17:41:43,920) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:43,922) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:43,923) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/drn')}

[16503:MainThread](2026-07-19 17:41:43,940) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:43,941) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:43,942) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/want')}

[16503:MainThread](2026-07-19 17:41:48,851) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:48,853) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:48,853) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/soxx_constituents')}

[16503:MainThread](2026-07-19 17:41:48,875) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:48,877) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:48,877) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/soxl')}

[16503:MainThread](2026-07-19 17:41:48,964) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:48,966) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:48,967) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/soxl_intraday_15min')}

[16503:MainThread](2026-07-19 17:41:51,342) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:51,344) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:51,345) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/soxl_exhaustion_structure_fragility_v1')}

[16503:MainThread](2026-07-19 17:41:51,506) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:51,508) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:51,509) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/soxl_exhaustion_structure_fragility_v1')}

[16503:MainThread](2026-07-19 17:41:51,514) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:51,515) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:51,516) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/soxl_exhaustion_structure_fragility_v1')}

[16503:MainThread](2026-07-19 17:41:51,716) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:51,719) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:51,719) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/soxl_exhaustion_structure_fragility_v1')}

[16503:MainThread](2026-07-19 17:41:52,657) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[16503:MainThread](2026-07-19 17:41:52,660) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[16503:MainThread](2026-07-19 17:41:52,661) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/.worktrees/multi-3x-high-chop-risk-control-v1/data/qlib/soxl_exhaustion_structure_fragility_v1')}

[16503:MainThread](2026-07-19 17:41:52,847) INFO - qlib.timer - [log.py:127] - Time cost: 0.182s | Loading data Done

[16503:MainThread](2026-07-19 17:41:52,848) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[16503:MainThread](2026-07-19 17:41:52,848) INFO - qlib.timer - [log.py:127] - Time cost: 0.183s | Init data Done

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[16503:MainThread](2026-07-19 17:41:53,252) INFO - qlib.workflow - [exp.py:258] - Experiment 703105948188725631 starts running ...

[16503:MainThread](2026-07-19 17:41:53,336) INFO - qlib.workflow - [recorder.py:345] - Recorder 4e18504a172f41d1809348278679f251 starts running under Experiment 703105948188725631 ...

[16503:MainThread](2026-07-19 17:41:53,644) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

{'status': 'completed',
 'as_of': '2026-07-02',
 'promotion_decision': 'not_retained_no_incremental_factor_evidence',
 'dataset': {'api': ['DatasetH', 'DataHandlerLP', 'QlibDataLoader'],
  'segments': {'train': ['2011-01-03', '2020-12-31'],
   'test': ['2023-01-01', '2026-07-02'],
   'valid': ['2021-01-01', '2022-12-31']},
  'prepared_rows': {'train': 40272, 'valid': 8048, 'test': 14032}},
 'intraday_coverage': {'soxl_soxx_intraday': {'status': 'eligible',
   'start': '2018-12-31',
   'included_in_selection': True},
  'external_bellwether_intraday': {'status': 'blocked_insufficient_history',
   'complete_start': '2025-01-02',
   'required_development_end': '2022-12-31',
   'outer_start': '2023-01-01',
   'included_in_selection': False}}}

## Results

In [3]:
family_metrics = pd.read_csv(CARD / 'outer_family_metrics.csv')
factor_metrics = pd.read_csv(CARD / 'outer_factor_metrics.csv')
factor_summary = pd.read_csv(CARD / 'factor_summary.csv')
display(family_metrics)
display(factor_metrics.sort_values(['auc', 'conditional_event_rate_lift'], ascending=False).head(10))
display(factor_summary.loc[factor_summary['development_gate_passed']])

,window,family,selected_factors,observations,breakdown_events,auc,average_precision,prevalence,average_precision_lift,quintile_1_rate,quintile_5_rate,quintile_lift,quintile_monotonicity,conditional_event_rate_lift,eligible_price_bins
0,overall,price_only,NaN,461,33,0.704758,0.125492,0.071584,1.753083,0.010753,0.141304,0.130552,1.0,NaN,NaN
1,overall,soxl_soxx_intraday_path,intraday_range_ratio_pressure,461,33,0.400630,0.065727,0.071584,0.918182,0.096774,0.032609,-0.064165,-0.7,-0.039028,5.0

,family,factor,development_selected,observations,breakdown_events,auc,average_precision,prevalence,average_precision_lift,quintile_1_rate,quintile_5_rate,quintile_lift,quintile_monotonicity,conditional_event_rate_lift,eligible_price_bins
8,leverage_fragility,asymmetric_beta_pressure_60,False,450,33,0.659182,0.113119,0.073333,1.542527,0.022222,0.133333,0.111111,0.900000,0.084444,5
9,leverage_fragility,volatility_drag_pressure_20,False,461,33,0.656861,0.115074,0.071584,1.607556,0.032258,0.119565,0.087307,0.900000,0.041125,5
2,price_path_exhaustion,efficiency_collapse_20,False,461,33,0.629106,0.098188,0.071584,1.371658,0.021505,0.086957,0.065451,0.900000,-0.020162,5
3,price_path_exhaustion,upside_progress_per_range_pressure_20,False,461,33,0.617920,0.091708,0.071584,1.281127,0.021505,0.086957,0.065451,0.600000,0.022763,5
7,leverage_fragility,up_day_leverage_shortfall_20,False,449,33,0.570950,0.107703,0.073497,1.465409,0.066667,0.144444,0.077778,0.051299,-0.004167,5
6,leverage_fragility,cumulative_leverage_residual_pressure_20,False,461,33,0.556004,0.106650,0.071584,1.489870,0.086022,0.097826,0.011805,0.400000,0.039301,5
11,fixed_bellwether_structure,fixed_bellwether_residual_dispersion_20,False,461,33,0.555084,0.115244,0.071584,1.609922,0.075269,0.152174,0.076905,0.100000,-0.004348,5
4,price_path_exhaustion,downside_range_skew_20,False,461,33,0.529560,0.071282,0.071584,0.995783,0.010753,0.032609,0.021856,0.359092,-0.010173,5
12,fixed_bellwether_structure,fixed_bellwether_leadership_concentration_20,False,461,33,0.529383,0.072802,0.071584,1.017028,0.021505,0.000000,-0.021505,0.000000,0.040230,5
18,soxl_soxx_intraday_path,intraday_leverage_residual_pressure,False,461,33,0.528285,0.080024,0.071584,1.117907,0.053763,0.076087,0.022324,0.666886,-0.003639,5

,factor,eligible_group_count,direction_consistency,median_group_auc,median_group_quintile_lift,development_gate_passed,selection_status,family,selection_uses_soxl
19,intraday_range_ratio_pressure,3,1.0,0.564103,0.133333,True,selected,soxl_soxx_intraday_path,True

## Takeaways

### 中文结论

- 做了什么：检验价格路径耗竭、杠杆脆弱性、固定五龙头结构代理和 SOXL/SOXX 盘中路径，共 21 个透明因子，不使用预测模型。
- 关键指标：2023–2026 SOXL 高位样本 461 条、33 次 breakdown；price-only AUC 0.705、AP lift 1.75x、Q5-Q1 13.1%。
- regime/window：2023 和 2024 是可用的年度事件窗口；2025/2026 只有 3/2 次事件，年度结果只作诊断。
- 晋升决定：`not_retained_no_incremental_factor_evidence`。开发期唯一入选的 15 分钟 range-ratio 因子在外层反转为 AUC 0.401、Q5-Q1 -6.4%、price-only 条件增量 -3.9%。其余三族没有因子通过开发门槛。
- 风险：固定五龙头存在生存偏差；外部龙头 15 分钟历史不足；单因子外层排名属于诊断，不能反向用于重选。
- 下一步：保留 price-only 作为风险状态基线；若继续优化，应改标签为近端路径失速/回撤深度并做多尺度事件定义，而不是继续给这些失败因子调权重。