# SOXL 复利状态、波动预算与稀疏执行实验

假设：在冻结 Stage1 confidence-veto 基线上，使用 SOXX 的点时可得趋势/震荡/危机状态、波动率预算和事件式调仓，可能减少 SOXL 交易而不损失收益风险表现。结构只在 2016–2022 开发期判断；2023–2026 是已复用诊断，不参与选择。

In [1]:
from pathlib import Path
import sys
root = Path.cwd().resolve()
while root != root.parent and not (root / 'AGENTS.md').exists():
    root = root.parent
if not (root / 'AGENTS.md').exists():
    raise RuntimeError('blocked: repository root not found')
sys.path.insert(0, root.as_posix())
import pandas as pd
import qlib
from qlib.config import REG_US
from qlib.data import D
from qlib.data.dataset import DatasetH
from qlib.data.dataset.handler import DataHandlerLP
from qlib.data.dataset.loader import StaticDataLoader
from qlib.workflow import R
from src.workflow.soxl_compounding_regime_sparse_execution import run_soxl_compounding_regime_sparse_execution_card

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

In [2]:
provider_uri = root / 'data' / 'qlib' / 'soxl_soxx_soxs'
qlib.init(provider_uri=provider_uri.as_posix(), region=REG_US, kernels=1)
calendar = D.calendar(start_time='2016-01-01', end_time='2026-12-31', freq='day')
close_audit = D.features(['SOXX'], ['$close'], start_time='2016-01-01', end_time='2026-12-31', freq='day')
{'provider_uri': provider_uri.as_posix(), 'calendar_rows': len(calendar), 'feature_rows': len(close_audit), 'qlib_api': ['qlib.init', 'D.calendar', 'D.features', 'DatasetH', 'DataHandlerLP', 'StaticDataLoader', 'R.start']}

[36022:MainThread](2026-08-10 16:02:39,924) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[36022:MainThread](2026-08-10 16:02:39,927) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[36022:MainThread](2026-08-10 16:02:39,928) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

{'provider_uri': '/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs',
 'calendar_rows': 2664,
 'feature_rows': 2664,
 'qlib_api': ['qlib.init',
  'D.calendar',
  'D.features',
  'DatasetH',
  'DataHandlerLP',
  'StaticDataLoader',
  'R.start']}

In [3]:
summary = run_soxl_compounding_regime_sparse_execution_card(root=root)
{'decision': summary['decision'], 'selected_challenger': summary['selected_challenger'], 'retained_model': summary['retained_model'], 'recorder_id': summary['recorder_id']}

[36022:MainThread](2026-08-10 16:02:39,977) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[36022:MainThread](2026-08-10 16:02:39,979) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[36022:MainThread](2026-08-10 16:02:39,980) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[36022:MainThread](2026-08-10 16:02:40,017) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[36022:MainThread](2026-08-10 16:02:40,019) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[36022:MainThread](2026-08-10 16:02:40,020) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[36022:MainThread](2026-08-10 16:02:40,340) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[36022:MainThread](2026-08-10 16:02:40,342) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[36022:MainThread](2026-08-10 16:02:40,343) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

[36022:MainThread](2026-08-10 16:02:40,543) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[36022:MainThread](2026-08-10 16:02:40,547) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[36022:MainThread](2026-08-10 16:02:40,548) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[36022:MainThread](2026-08-10 16:02:40,599) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[36022:MainThread](2026-08-10 16:02:40,601) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[36022:MainThread](2026-08-10 16:02:40,602) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

[36022:MainThread](2026-08-10 16:02:40,851) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[36022:MainThread](2026-08-10 16:02:40,853) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[36022:MainThread](2026-08-10 16:02:40,853) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[36022:MainThread](2026-08-10 16:02:40,877) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[36022:MainThread](2026-08-10 16:02:40,878) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[36022:MainThread](2026-08-10 16:02:40,878) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[36022:MainThread](2026-08-10 16:02:42,515) WARNING - qlib.workflow - [expm.py:231] - No valid experiment found. Create a new experiment with name soxl_compounding_regime_sparse_execution_v1.

[36022:MainThread](2026-08-10 16:02:42,520) INFO - qlib.workflow - [exp.py:258] - Experiment 781107184629592212 starts running ...

[36022:MainThread](2026-08-10 16:02:42,634) INFO - qlib.workflow - [recorder.py:345] - Recorder 6b7ad80a749640d79daa0654234592e2 starts running under Experiment 781107184629592212 ...

[36022:MainThread](2026-08-10 16:02:43,848) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

{'decision': 'research_reject_no_structural_profile_passed_all_gates',
 'selected_challenger': None,
 'retained_model': 'confidence_veto_baseline',
 'recorder_id': '6b7ad80a749640d79daa0654234592e2'}

In [4]:
card = root / 'research' / 'soxl_compounding_regime_sparse_execution_v1'
comparison = pd.read_csv(card / 'backtest_benchmark_comparison.csv')
selection = pd.read_csv(card / 'model_selection.csv')
display(selection[['profile', 'return_pct', 'max_drawdown_pct', 'worst_rolling_5d_pct', 'total_turnover', 'open_trade_days', 'recovery_action_count', 'all_gates_pass']])
display(comparison[comparison['segment'].eq('outer_reused_diagnostic') & comparison['cost_bps'].eq(10.0)])

,profile,return_pct,max_drawdown_pct,worst_rolling_5d_pct,total_turnover,open_trade_days,recovery_action_count,all_gates_pass
0,confidence_veto_baseline,424.956036,-26.728104,-10.701044,129.062863,1762,19,False
1,recovery_trend_only,395.568445,-26.683796,-10.701044,118.825723,1762,0,False
2,volatility_budget,119.023825,-26.827613,-10.625297,130.262503,1762,16,False
3,compounding_regime_cap,83.356476,-30.529078,-10.431441,156.125759,1762,26,False
4,regime_sparse_execution,112.418322,-27.172114,-9.206553,102.001986,455,15,False

,profile,segment,cost_bps,terminal_wealth,return_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,worst_rolling_5d_pct,total_turnover,open_trade_days,recovery_action_count,avg_cash_weight_pct
10,confidence_veto_baseline,outer_reused_diagnostic,10.0,4.802061,380.206146,-27.494922,-8.667006,-5.072032,-14.408875,58.611506,900,0,39.043288
12,recovery_trend_only,outer_reused_diagnostic,10.0,4.802061,380.206146,-27.494922,-8.667006,-5.072032,-14.408875,58.611506,900,0,39.043288
14,volatility_budget,outer_reused_diagnostic,10.0,1.640941,64.094113,-33.849898,-5.825790,-3.384218,-9.098357,41.961366,899,0,58.030283
16,compounding_regime_cap,outer_reused_diagnostic,10.0,4.742155,374.215519,-28.194107,-7.447902,-3.862421,-10.812725,65.113814,900,0,37.135659
18,regime_sparse_execution,outer_reused_diagnostic,10.0,2.840858,184.085832,-25.690150,-5.733387,-3.343765,-8.113759,35.188395,191,0,41.036418

## 中文结论

最终结论以执行后同步生成的 `conclusion.md`、`summary.json` 和 qlib recorder 为准。结论必须说明：运行内容、关键收益与风险、状态差异、是否晋升、剩余风险和下一步。

In [5]:
print((card / 'conclusion.md').read_text(encoding='utf-8'))

# 中文结论

- 做了什么：以冻结的 Stage1 confidence-veto 为直接基线，固定测试论文启发的四个结构消融：恢复动作只限趋势、35% SOXX 波动率预算、趋势/震荡/危机 beta cap，以及状态 cap + 2%/5% no-trade band + 3日最短持有。没有用 2023-2026 选结构或参数。
- 基线：开发期 10bp return=424.9560%、MaxDD=-26.7281%、open trade days=1762、10:31 actions=19。
- 恢复状态反证：趋势限定把 10:31 actions 从 19 降到 0，但 return 降到 395.5684%。原19次动作实际位于危机/震荡后的恢复阶段，不能按普通趋势追随信号删除。
- 波动率预算：return=119.0238%、MaxDD=-26.8276%；固定35%预算与现有 controller 重复去风险，收益损失过大。
- 状态限仓：return=83.3565%、MaxDD=-30.5291%；简单把震荡 beta 限到0.8、危机限到0.25并不适合当前模型。
- 稀疏执行：open trade days 从 1762 降到 455，turnover 从 129.0629 降到 102.0020，但 return 仅 112.4183%、MaxDD=-27.1721%。这证明每日目标变化包含有价值的信息，粗暴3日冻结并不是免费降频。
- outer 复用诊断：基线 return=380.2061%，稀疏方案=184.0858%；该窗口已反复查看，只用于确认失败没有反转，不能作为选择证据。
- 决策：research_reject_no_structural_profile_passed_all_gates。没有结构候选同时超过基线收益、守住风险、通过25bp并减少20%开盘交易日；保留 confidence-veto baseline，不修改生产模拟盘。
- 下一步：若继续降频，应把目标改成“未来3-5日累计调仓价值/交易成本”的监督式 action-value objective，而不是继续调固定波动率、MA或no-trade阈值。
- qlib：SOXX状态特征通过 D.features 读取，DatasetH 对齐开发/outer 段，完整 replay 和模型比较保存在 recorder 6b7ad80a749640d79daa0654234592e2；卡根只保留小型审计 sidecar。
- 不构成买卖建议。