# Stage1 费用一致动作训练（增量 2）

在冻结 own-state 面板训练两本书（10bp 书=自身 state+label10bp；25bp 书=自身 state+label25bp），
先控制 parity，再各 cost 候选 + 冻结参照，**分组比较 + 真实门**，不合并胜出。

In [1]:
import sys, json, hashlib
from pathlib import Path

ROOT = Path.cwd()
while not (ROOT/'AGENTS.md').exists():
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))
CARD = ROOT/'research'/'stage1_cost_consistent_action_20261009'
print('plan sha256:', hashlib.sha256((CARD/'plan.json').read_bytes()).hexdigest())

plan sha256: 4bc91c1a4ef72c760ffa5ac5be9939fe3fec830417536794a6ea7bb52f8285c7

In [2]:
from src.workflow import cost_matched_action_experiment as workflow
summary = workflow.run_cost_matched_action(root=ROOT, card_dir=CARD)
print('parity:', summary['control_parity']['status'])
print('recorder:', summary['recorder_id'])
print('saved objects:', summary['saved_objects'])

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

2026/10/09 22:29:41 INFO mlflow.agent.hint: Load the `instrumenting-with-mlflow-tracing` skill at /Users/rziiiii/dev/workspace/qlib_venv/lib/python3.12/site-packages/mlflow/assistant/skills/instrumenting-with-mlflow-tracing/SKILL.md before writing any tracing code; it ships with this MLflow install. Set MLFLOW_DISABLE_AGENT_HINT=1 to silence this.

[68832:MainThread](2026-10-09 22:29:41,299) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[68832:MainThread](2026-10-09 22:29:41,300) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[68832:MainThread](2026-10-09 22:29:41,300) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[68832:MainThread](2026-10-09 22:29:41,571) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[68832:MainThread](2026-10-09 22:29:41,571) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[68832:MainThread](2026-10-09 22:29:41,571) INFO - qlib.timer - [log.py:127] - Time cost: 0.002s | Init data Done

[68832:MainThread](2026-10-09 22:29:42,005) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[68832:MainThread](2026-10-09 22:29:42,006) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[68832:MainThread](2026-10-09 22:29:42,006) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[68832:MainThread](2026-10-09 22:29:42,434) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[68832:MainThread](2026-10-09 22:29:42,435) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[68832:MainThread](2026-10-09 22:29:42,435) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[68832:MainThread](2026-10-09 22:29:42,863) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[68832:MainThread](2026-10-09 22:29:42,863) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[68832:MainThread](2026-10-09 22:29:42,863) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[68832:MainThread](2026-10-09 22:29:43,296) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[68832:MainThread](2026-10-09 22:29:43,297) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[68832:MainThread](2026-10-09 22:29:43,297) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[68832:MainThread](2026-10-09 22:29:43,775) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[68832:MainThread](2026-10-09 22:29:43,776) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[68832:MainThread](2026-10-09 22:29:43,776) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[68832:MainThread](2026-10-09 22:29:44,543) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[68832:MainThread](2026-10-09 22:29:44,544) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[68832:MainThread](2026-10-09 22:29:44,544) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[68832:MainThread](2026-10-09 22:29:50,616) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[68832:MainThread](2026-10-09 22:29:50,617) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[68832:MainThread](2026-10-09 22:29:50,617) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[68832:MainThread](2026-10-09 22:29:51,043) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[68832:MainThread](2026-10-09 22:29:51,043) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[68832:MainThread](2026-10-09 22:29:51,043) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[68832:MainThread](2026-10-09 22:29:51,465) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[68832:MainThread](2026-10-09 22:29:51,465) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[68832:MainThread](2026-10-09 22:29:51,465) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[68832:MainThread](2026-10-09 22:29:51,893) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[68832:MainThread](2026-10-09 22:29:51,894) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[68832:MainThread](2026-10-09 22:29:51,894) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[68832:MainThread](2026-10-09 22:29:52,363) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[68832:MainThread](2026-10-09 22:29:52,363) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[68832:MainThread](2026-10-09 22:29:52,363) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[68832:MainThread](2026-10-09 22:29:52,916) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[68832:MainThread](2026-10-09 22:29:52,917) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[68832:MainThread](2026-10-09 22:29:52,917) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[68832:MainThread](2026-10-09 22:29:53,705) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[68832:MainThread](2026-10-09 22:29:53,705) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[68832:MainThread](2026-10-09 22:29:53,705) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[68832:MainThread](2026-10-09 22:29:56,382) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[68832:MainThread](2026-10-09 22:29:56,382) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[68832:MainThread](2026-10-09 22:29:56,383) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[68832:MainThread](2026-10-09 22:29:56,798) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[68832:MainThread](2026-10-09 22:29:56,798) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[68832:MainThread](2026-10-09 22:29:56,799) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[68832:MainThread](2026-10-09 22:29:57,233) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[68832:MainThread](2026-10-09 22:29:57,233) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[68832:MainThread](2026-10-09 22:29:57,233) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[68832:MainThread](2026-10-09 22:29:57,663) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[68832:MainThread](2026-10-09 22:29:57,664) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[68832:MainThread](2026-10-09 22:29:57,664) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[68832:MainThread](2026-10-09 22:29:58,122) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[68832:MainThread](2026-10-09 22:29:58,122) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[68832:MainThread](2026-10-09 22:29:58,122) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[68832:MainThread](2026-10-09 22:29:58,698) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[68832:MainThread](2026-10-09 22:29:58,698) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[68832:MainThread](2026-10-09 22:29:58,698) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[68832:MainThread](2026-10-09 22:29:59,490) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[68832:MainThread](2026-10-09 22:29:59,491) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[68832:MainThread](2026-10-09 22:29:59,491) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[68832:MainThread](2026-10-09 22:30:06,497) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[68832:MainThread](2026-10-09 22:30:06,498) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[68832:MainThread](2026-10-09 22:30:06,498) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[68832:MainThread](2026-10-09 22:30:06,499) WARNING - qlib.workflow - [expm.py:231] - No valid experiment found. Create a new experiment with name stage1_cost_consistent_action_20261009.

[68832:MainThread](2026-10-09 22:30:06,501) INFO - qlib.workflow - [exp.py:258] - Experiment 179067074231437245 starts running ...

[68832:MainThread](2026-10-09 22:30:06,571) INFO - qlib.workflow - [recorder.py:345] - Recorder a100fa4745f4421c9dface98c2921ae9 starts running under Experiment 179067074231437245 ...

[68832:MainThread](2026-10-09 22:30:06,664) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

parity: passed
recorder: a100fa4745f4421c9dface98c2921ae9
saved objects: ['annual_records', 'candidate_comparison', 'candidate_replays', 'dataset_audit_10', 'dataset_audit_25', 'diagnostics_10', 'diagnostics_25', 'models_10', 'models_25', 'reference_comparison', 'training_rows_10', 'training_rows_25']

In [3]:
import pandas as pd
t = pd.read_csv(CARD/'cost_matched_comparison.csv')
cols=['segment','family','variant','cost_bps','label_cost_bps','return_pct','max_drawdown_pct','cvar5_pct','worst_day_pct','worst_rolling_5d_pct','total_turnover','open_trade_days']
display(t[cols].sort_values(['segment','cost_bps','family']).round(2))

,segment,family,variant,cost_bps,label_cost_bps,return_pct,max_drawdown_pct,cvar5_pct,worst_day_pct,worst_rolling_5d_pct,total_turnover,open_trade_days
16,development_walk_forward,cost_matched,cost_matched_book_10,10.0,10.0,110.30,-32.33,-3.52,-9.50,-14.42,57.67,699
0,development_walk_forward,frozen_reference,active_hold_baseline,10.0,NaN,170.74,-30.08,-3.54,-7.11,-10.82,103.43,1457
1,development_walk_forward,frozen_reference,no_hold_reference,10.0,NaN,115.04,-29.93,-3.48,-7.11,-10.82,106.92,1713
2,development_walk_forward,frozen_reference,own_state_net_value_frozen_2022,10.0,NaN,200.49,-29.03,-3.06,-7.46,-10.82,46.65,597
3,development_walk_forward,frozen_reference,rules_only,10.0,NaN,171.49,-29.67,-3.52,-7.11,-10.82,97.24,1259
17,development_walk_forward,cost_matched,cost_matched_book_25,25.0,25.0,154.33,-30.03,-3.25,-8.23,-10.99,52.56,582
4,development_walk_forward,frozen_reference,active_hold_baseline,25.0,NaN,96.76,-30.08,-3.59,-7.12,-11.89,114.42,1478
5,development_walk_forward,frozen_reference,no_hold_reference,25.0,NaN,151.27,-30.00,-3.64,-7.12,-11.89,111.51,1721
6,development_walk_forward,frozen_reference,own_state_net_value_frozen_2022,25.0,NaN,160.85,-30.18,-3.08,-8.26,-10.99,49.02,614
7,development_walk_forward,frozen_reference,rules_only,25.0,NaN,98.98,-30.10,-3.56,-7.12,-11.88,107.23,1284
18,outer_reused_diagnostic,cost_matched,cost_matched_book_10,10.0,10.0,84.24,-32.62,-4.31,-11.02,-14.13,43.53,611
8,outer_reused_diagnostic,frozen_reference,active_hold_baseline,10.0,NaN,219.43,-26.92,-4.80,-8.70,-14.55,57.44,791
9,outer_reused_diagnostic,frozen_reference,no_hold_reference,10.0,NaN,220.37,-26.92,-4.81,-8.70,-14.55,59.54,906
10,outer_reused_diagnostic,frozen_reference,own_state_net_value_frozen_2022,10.0,NaN,362.84,-26.48,-4.77,-8.73,-14.55,44.81,491
11,outer_reused_diagnostic,frozen_reference,rules_only,10.0,NaN,220.82,-26.92,-4.80,-8.70,-14.55,56.59,652
19,outer_reused_diagnostic,cost_matched,cost_matched_book_25,25.0,25.0,109.32,-33.04,-4.43,-11.20,-14.20,32.73,347
12,outer_reused_diagnostic,frozen_reference,active_hold_baseline,25.0,NaN,75.11,-32.38,-4.42,-11.20,-14.64,50.62,746
13,outer_reused_diagnostic,frozen_reference,no_hold_reference,25.0,NaN,66.09,-36.44,-4.40,-11.20,-14.64,46.93,916
14,outer_reused_diagnostic,frozen_reference,own_state_net_value_frozen_2022,25.0,NaN,324.65,-26.85,-4.69,-8.78,-14.63,41.69,475
15,outer_reused_diagnostic,frozen_reference,rules_only,25.0,NaN,74.80,-32.89,-4.43,-11.20,-14.63,50.57,654

In [4]:
print('=== 真实门 ===')
display(pd.read_csv(CARD/'gate_results.csv'))
print('=== SOXX 基准 ===')
display(pd.read_csv(CARD/'soxx_benchmark.csv').round(2))

=== 真实门 ===

,candidate,segment,cost_bps,reference,minimum_annual_wealth_ratio,return_above_baseline,max_drawdown_not_worse,worst_day_not_worse,cvar5_not_worse,worst_5d_not_worse,open_trade_days_reduced_8pct,turnover_not_increased,annual_wealth_floor_pass,all_pass
0,cost_matched_book_10,development_walk_forward,10.0,no_hold_reference,0.816755,False,False,False,False,False,True,True,False,False
1,cost_matched_book_10,development_walk_forward,10.0,active_hold_baseline,0.761726,False,False,False,True,False,True,True,False,False
2,cost_matched_book_25,development_walk_forward,25.0,no_hold_reference,0.743838,True,False,False,True,True,True,True,False,False
3,cost_matched_book_25,development_walk_forward,25.0,active_hold_baseline,0.742733,True,True,False,True,True,True,True,False,False
4,cost_matched_book_10,outer_reused_diagnostic,10.0,no_hold_reference,0.798306,False,False,False,True,True,True,True,False,False
5,cost_matched_book_10,outer_reused_diagnostic,10.0,active_hold_baseline,0.798988,False,False,False,True,True,True,True,False,False
6,cost_matched_book_25,outer_reused_diagnostic,25.0,no_hold_reference,0.851672,True,True,True,False,True,True,True,False,False
7,cost_matched_book_25,outer_reused_diagnostic,25.0,active_hold_baseline,0.848327,True,False,True,False,True,True,True,False,False

=== SOXX 基准 ===

,benchmark,segment,sessions,terminal_wealth,return_pct,max_drawdown_pct,cvar5_pct,worst_day_pct,worst_rolling_5d_pct,sharpe,total_turnover,open_trade_days,recovery_action_count
0,SOXX_buy_hold_open_to_open,development_walk_forward,1756,4.21,320.70,-47.37,-4.42,-9.33,-17.25,0.83,0.0,0,0
1,SOXX_buy_hold_open_to_open,outer_reused_diagnostic,934,4.98,398.25,-42.79,-5.29,-9.65,-17.69,1.35,0.0,0,0

## 中文结论

In [5]:
from IPython.display import Markdown, display
display(Markdown((CARD/'conclusion.md').read_text()))

# Stage1 费用一致动作训练（增量 2，中文结论）
- 做了什么：冻结 own-state 面板训练两本书（10bp 书=自身 state+label10bp；25bp 书=自身 state+label25bp），与冻结参照 active/no_hold/own_state_frozen/rules_only 分组比较。plan sha `4bc91c1a4ef7`。
- 控制 parity（新 wrapper label25/eval10 全路径复现源 control，含 returns/endweights/decisions）：passed。
- 结果按 **segment × cost** 分组，不合并；真实门与年度/财富下限门按原阈值计算，失败如实列出。
- 本执行**不依赖价格一致性接口**；增量 1（价格口径）留待原生接口就绪后单独跑并单独报告。
- 门阈值（复用原卡）：{'annual_wealth_floor': 0.985, 'open_trade_days_reduction': 0.92}。
- 候选 not_promoted：缺完整 native intraday 对账，历史门不自动授权晋升。
- 子 Recorder：a100fa4745f4421c9dface98c2921ae9；保存 models/scaler/training/maturity/predictions/replays，源只读不改。