# SOXL 长周期超额与超跌特征

比较 SOXL、SOXX 与理想每日重置 3x SOXX，分析固定持有期超额、持续超额状态、绝对/相对水下周期，以及 VIX 与 SOXL 自身路径波动的差异。

In [1]:
from pathlib import Path
import sys
import pandas as pd
import qlib
from qlib.config import REG_US
from qlib.data import D
from qlib.data.dataset import DatasetH
from qlib.workflow import R
from IPython.display import Markdown, display

repo_root = Path.cwd().resolve().parents[1]
sys.path.insert(0, str(repo_root))
from src.workflow.soxl_long_horizon_excess_drawdown import run_soxl_long_horizon_card

provider_uri = repo_root / 'data' / 'qlib' / 'soxl'
qlib.init(provider_uri=str(provider_uri), region=REG_US, kernels=1)
calendar = D.calendar(freq='day')
instruments = D.instruments('all')
source_check = D.features(['SOXL', 'SOXX'], ['$close', '$vix'], start_time='2010-03-11', end_time=str(pd.Timestamp(calendar[-1]).date()), freq='day')
{'calendar_rows': len(calendar), 'feature_rows': len(source_check), 'instruments': instruments}

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[80914:MainThread](2026-07-29 20:08:52,475) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[80914:MainThread](2026-07-29 20:08:52,477) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[80914:MainThread](2026-07-29 20:08:52,477) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

{'calendar_rows': 4120,
 'feature_rows': 8240,
 'instruments': {'market': 'all', 'filter_pipe': []}}

In [2]:
summary = run_soxl_long_horizon_card(root=repo_root)
card = repo_root / 'research' / summary['experiment']
display(pd.read_csv(card / 'horizon_metrics.csv'))
display(pd.read_csv(card / 'persistent_regimes.csv').query("lookback_horizon_days == 252 and rank_within_state == 1"))
display(pd.read_csv(card / 'underwater_episodes.csv').query("duration_rank == 1"))
{'decision': summary['decision'], 'recorder_id': summary['recorder_id']}

[80914:MainThread](2026-07-29 20:08:52,495) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[80914:MainThread](2026-07-29 20:08:52,496) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[80914:MainThread](2026-07-29 20:08:52,496) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[80914:MainThread](2026-07-29 20:08:52,501) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[80914:MainThread](2026-07-29 20:08:52,502) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[80914:MainThread](2026-07-29 20:08:52,502) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[80914:MainThread](2026-07-29 20:08:52,817) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[80914:MainThread](2026-07-29 20:08:52,818) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[80914:MainThread](2026-07-29 20:08:52,818) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[80914:MainThread](2026-07-29 20:08:53,051) INFO - qlib.workflow - [exp.py:258] - Experiment 186638595000434944 starts running ...

[80914:MainThread](2026-07-29 20:08:53,118) INFO - qlib.workflow - [recorder.py:345] - Recorder 6acbc2fa9b7245a9b9176013ac5e9ddb starts running under Experiment 186638595000434944 ...

[80914:MainThread](2026-07-29 20:08:53,206) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

,horizon_days,rows,positive_excess_share,median_raw_excess_return,p05_raw_excess_return,p95_raw_excess_return,median_tracking_gap_vs_ideal,median_soxx_realized_volatility,median_path_efficiency
0,1,4119,0.539209,0.002783,-0.059578,0.060735,-0.000168,0.158147,1.000000
1,5,4115,0.558688,0.009864,-0.120882,0.135290,-0.000789,0.227572,0.431200
2,21,4099,0.581117,0.027812,-0.208853,0.309093,-0.002333,0.245623,0.196536
3,63,4057,0.617698,0.087475,-0.319814,0.626438,-0.002131,0.260456,0.120408
4,126,3994,0.614422,0.153906,-0.394185,1.064137,-0.005477,0.264483,0.090491
5,252,3868,0.589969,0.219885,-0.491260,1.825438,-0.021387,0.279137,0.073200
6,504,3616,0.662058,0.393855,-0.585087,3.535667,-0.059197,0.270304,0.058096
7,756,3364,0.728002,1.213037,-0.766204,4.506340,-0.144790,0.253707,0.066621
8,1260,2860,0.722378,2.200611,-0.960512,17.346317,-0.302262,0.294321,0.060580

,lookback_horizon_days,state,state_start_date,state_end_date,state_trading_days,state_calendar_days,median_trailing_excess,worst_trailing_excess,best_trailing_excess,median_trailing_soxx_return,...,state_interval_relative_wealth_change_vs_soxx,state_interval_relative_wealth_change_vs_ideal,state_interval_soxx_realized_volatility,state_interval_path_efficiency,state_interval_positive_soxx_day_share,state_interval_vix_mean,state_interval_vix_max,state_interval_vix_start,state_interval_vix_end,rank_within_state
12,252,negative_excess,2022-03-30,2023-06-12,302,439,-0.475591,-0.525292,-0.060066,-0.115081,...,-0.426672,-0.082981,0.391941,0.006393,0.48505,23.256656,34.75,19.33,15.01,1
15,252,positive_excess,2016-07-18,2018-10-08,562,812,0.901952,0.003090,2.686576,0.377967,...,1.257177,-0.046902,0.202844,0.106634,0.57041,13.008025,37.32,12.44,15.69,1

,basis,peak_date,trough_date,recovery_or_end_date,duration_trading_days,depth,recovered,start_date,end_date,trading_days,...,relative_wealth_change_vs_ideal,soxx_realized_volatility,path_efficiency,positive_soxx_day_share,vix_mean,vix_max,vix_start,vix_end,duration_rank,depth_rank
0,absolute_soxl,2021-12-27,2022-10-14,2026-04-10,1075,-0.905055,True,2021-12-27,2026-04-10,1075,...,-0.334007,0.370728,0.039498,0.525581,19.346599,52.330002,17.680000,19.230000,1,1
6,relative_vs_ideal_daily_reset_3x,2020-03-16,2026-07-28,2026-07-28,1599,-0.455404,False,2020-03-16,2026-07-28,1599,...,-0.455404,0.377492,0.075494,0.534084,20.781113,82.690002,82.690002,18.209999,1,1
13,relative_vs_soxx,2021-12-27,2025-04-21,2026-05-26,1106,-0.864939,True,2021-12-27,2026-05-26,1106,...,-0.337093,0.373663,0.057975,0.532550,19.307055,52.330002,17.680000,17.010000,1,1

{'decision': 'descriptive_path_dependence_confirmed_not_entry_signal',
 'recorder_id': '6acbc2fa9b7245a9b9176013ac5e9ddb'}

## 中文结论

In [3]:
display(Markdown((card / 'conclusion.md').read_text(encoding='utf-8')))

# 中文结论

- 做了什么：使用 qlib `D.features` 读取 2010-03-11 至 2026-07-28 的 SOXL、SOXX 与 VIX，共 4120 个交易日；比较实际 SOXL、SOXX 和理想每日重置 3x SOXX，并区分固定持有期、持续状态与水下周期。
- 全历史：SOXL 财富变为 165.84 倍，SOXX 30.56 倍，理想每日重置 3x 为 259.07 倍；实际 SOXL 财富比理想 3x 低 35.98%，说明长期有显著产品/复利跟踪缺口。
- 最长一年期正超额状态：2016-07-18 至 2018-10-08，连续 562 个观察日；状态区间 SOXX 77.09%、SOXL 299.73%，SOXX 年化波动 20.28%，VIX 均值 13.01。特征是底层持续上涨、波动较低、正收益日占比更高。
- 最长一年期负超额状态：2022-03-30 至 2023-06-12，连续 302 个观察日；状态区间 SOXX 3.77%、SOXL -40.51%，SOXX 年化波动 39.19%，路径效率 0.64%，VIX 均值 23.26。特征是底层横盘/弱势且高波动，日复利损耗主导结果。
- 最长绝对水下期：2021-12-27 至 2026-04-10，1075 个交易日，最深 -90.51%；最长相对 SOXX 水下期为 1106 个交易日，最深 -86.49%。这说明回本与重新跑赢 1x 都可能需要多年。
- 相对理想 3x 的最长水下期从 2020-03-16 开始，截至 2026-07-28 仍未恢复，深度 -45.54%。绝对上涨不等于有效捕获理论 3x。
- 当前绝对水下期始于 2026-06-22，截至 2026-07-28 深度 -63.58%；期间 VIX 均值 17.32、最高 19.49。当前样本再次说明半导体集中风险可以在 VIX 不高时发生，不能把 VIX 当成 SOXL 自身波动的替代品。
- 窗口差异：持有期越长，正超额概率总体提高，但负尾部并未消失；5年窗口仍可出现SOXL 上涨但落后 SOXX 的起点敏感结果。
- 决策：descriptive_path_dependence_confirmed_not_entry_signal。该研究解释杠杆复利机制，不是可直接交易的择时信号，也不改变生产 Stage1 配置。
- qlib recorder：6acbc2fa9b7245a9b9176013ac5e9ddb。
- 风险：滚动窗口高度重叠；最长区间对起止点敏感；VIX 是大盘隐含波动率；理想 3x 未计费用、融资与再平衡摩擦。
- 下一步：若要用于模型，应单独加入 SOXL/SOXX 实现波动、路径效率和相对跟踪缺口，并做前向验证，而不是仅依赖 VIX。
- 不构成买卖建议。