# TSMC YoY 加速度 5-session 信息初筛（0 model，0 strategy）

单一固定机制 + 固定 horizon=5 session + 固定正方向；primary=时序 Spearman(score, spread5d)。
raw association 初筛，未证明 alpha/超额，不可上线。

In [1]:
import sys, json, hashlib
from pathlib import Path

ROOT = Path.cwd()
while not (ROOT/'AGENTS.md').exists():
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))
CARD = ROOT/'research'/'tsmc_yoy_acceleration_5session_information_20261010'
print('plan sha256:', hashlib.sha256((CARD/'preregister_plan.json').read_bytes()).hexdigest())

plan sha256: 11df7ed38ef350291dfaaafff4a39600c008957d31fd51f923155b767ff31985

In [2]:
# Explicit Qlib SourceDataAPI + DataAPI readback.
import qlib
from qlib.data import D
import src.analysis.tsmc_yoy_acceleration_information as A
qlib.init(provider_uri=str((ROOT/A.SOURCE_PROVIDER).resolve()), region='us', kernels=1)
src = D.features([A.INSTRUMENT], ['$acceleration_pct_points','$event_available'], freq='day')
qlib.init(provider_uri=str((ROOT/A.PRICE_PROVIDER).resolve()), region='us', kernels=1)
px = D.features(['SOXL','SOXX'], ['$open'], freq='day')
cal = D.calendar(freq='day')
print('source info rows:', len(src), '| price rows:', len(px), '| calendar', cal[0], '->', cal[-1])
print('source manifest sha:', A._sha(ROOT/A.SOURCE_PROVIDER/'qlib_store_manifest.json')[:16])

[6117:MainThread](2026-10-10 12:48:35,017) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

2026/10/10 12:48:35 INFO mlflow.agent.hint: Load the `instrumenting-with-mlflow-tracing` skill at /Users/rziiiii/dev/workspace/qlib_venv/lib/python3.12/site-packages/mlflow/assistant/skills/instrumenting-with-mlflow-tracing/SKILL.md before writing any tracing code; it ships with this MLflow install. Set MLFLOW_DISABLE_AGENT_HINT=1 to silence this.

[6117:MainThread](2026-10-10 12:48:35,433) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[6117:MainThread](2026-10-10 12:48:35,434) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/tsmc_monthly_revenue_20261010_v1')}

[6117:MainThread](2026-10-10 12:48:35,441) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[6117:MainThread](2026-10-10 12:48:35,441) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[6117:MainThread](2026-10-10 12:48:35,441) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

source info rows: 2712 | price rows: 5396 | calendar 2016-01-04 00:00:00 -> 2026-09-25 00:00:00
source manifest sha: 329811ed6fa96ff9

In [3]:
from src.workflow import tsmc_yoy_acceleration_information as workflow
summary = workflow.run_tsmc_yoy_acceleration_information(root=ROOT, card_dir=CARD)
print('decision:', summary['decision'])
print('primary_gate:', summary['primary_gate'])
print('models_trained:', summary['models_trained'], '| strategy:', summary['strategy'], '| orders:', summary['orders'])
print('recorder:', summary['recorder_id'])

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[6117:MainThread](2026-10-10 12:48:36,122) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[6117:MainThread](2026-10-10 12:48:36,123) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[6117:MainThread](2026-10-10 12:48:36,123) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/tsmc_monthly_revenue_20261010_v1')}

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[6117:MainThread](2026-10-10 12:48:36,147) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[6117:MainThread](2026-10-10 12:48:36,148) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[6117:MainThread](2026-10-10 12:48:36,148) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/tsmc_monthly_revenue_20261010_v1')}

[6117:MainThread](2026-10-10 12:48:36,156) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[6117:MainThread](2026-10-10 12:48:36,157) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[6117:MainThread](2026-10-10 12:48:36,157) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[6117:MainThread](2026-10-10 12:48:37,205) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[6117:MainThread](2026-10-10 12:48:37,206) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[6117:MainThread](2026-10-10 12:48:37,206) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[6117:MainThread](2026-10-10 12:48:37,208) WARNING - qlib.workflow - [expm.py:231] - No valid experiment found. Create a new experiment with name tsmc_yoy_acceleration_5session_information_20261010.

[6117:MainThread](2026-10-10 12:48:37,210) INFO - qlib.workflow - [exp.py:258] - Experiment 938822120988822900 starts running ...

[6117:MainThread](2026-10-10 12:48:37,286) INFO - qlib.workflow - [recorder.py:345] - Recorder 62851a0ab548440aa4961627c8b897b4 starts running under Experiment 938822120988822900 ...

[6117:MainThread](2026-10-10 12:48:38,177) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

decision: end_fixed_monthly_information_route_no_parameter_search
primary_gate: {'scope': 'development', 'min_valid_n': 40, 'pass': False, 'valid_n': 84, 'primary_ic': -0.09476945515335523, 'ci95_lower': -0.3267771733589285}
models_trained: 0 | strategy: False | orders: False
recorder: 62851a0ab548440aa4961627c8b897b4

In [4]:
import pandas as pd
print('=== window IC ==='); display(pd.read_csv(CARD/'window_ic.csv').round(4))
print('=== year IC ==='); display(pd.read_csv(CARD/'year_ic.csv').round(4))
print('=== coverage ==='); display(pd.read_csv(CARD/'coverage.csv'))

=== window IC ===

,window,valid_n,primary_ic,pearson,ci_low,ci_high,valid_replicates
0,development,84,-0.0948,-0.1284,-0.3268,0.1172,2000
1,outer_reused_diagnostic,45,0.0900,0.0615,-0.1881,0.3870,2000

=== year IC ===

                     window  year   n  valid_n      ic
0               development  2016  12       12  0.2378
1               development  2017  12       12  0.3217
2               development  2018  12       12  0.0909
3               development  2019  12       12 -0.5245
4               development  2020  12       12 -0.4126
5               development  2021  12       12 -0.3217
6               development  2022  12       12  0.0490
7   outer_reused_diagnostic  2023  12       12  0.1259
8   outer_reused_diagnostic  2024  12       12 -0.1678
9   outer_reused_diagnostic  2025  12       12  0.2727
10  outer_reused_diagnostic  2026   9        9  0.0167

=== coverage ===

                    window  events_in_window  valid_n unknown
0              development                84       84      {}
1  outer_reused_diagnostic                45       45      {}

## 中文结论

In [5]:
from IPython.display import Markdown, display
display(Markdown((CARD/'conclusion.md').read_text()))

# TSMC YoY 加速度 5-session 信息初筛（0 model，中文结论）
- 固定机制：`TSMC reported YoY acceleration (current yoy - previous consecutive yoy), fixed positive expected sign`；固定 horizon=5 session；固定正方向；无 threshold/year/horizon/sign 搜索。
- primary stat=`signed_time_series_spearman`（时序 Spearman(score, spread5d)，非两资产横截面 IC）；secondary 仅 SOXL/SOXX label IC/Pearson。
- 决定：`end_fixed_monthly_information_route_no_parameter_search`；gate：{'scope': 'development', 'min_valid_n': 40, 'pass': False, 'valid_n': 84, 'primary_ic': -0.09476945515335523, 'ci95_lower': -0.3267771733589285}。
### 分窗口
- development：valid_n=84；primaryIC=-0.09476945515335523；CI=[-0.3267771733589285,0.11720173354532991]；secondary SOXL/SOXX IC=-0.10028754842884441/-0.10351740485981879；unknown={}。
- outer_reused_diagnostic：valid_n=45；primaryIC=0.08999571806636376；CI=[-0.18806876633289557,0.3870118414702069]；secondary SOXL/SOXX IC=0.08887571279028161/0.09388279520100172；unknown={}。
- 源/价格 SHA：source 329811ed6fa9 / price 48ec582f748d（frozen_verified=True）。
- 边界：raw association 初筛；未证明超越 price/vol、无经济 alpha、不可上线；CI 跨 0 表示证据不足，而非证明不存在信息；后续仍需 priced-vol control 与 10/25bp economic/native 及独立前向。
- 本 fixed route 因证据不足而停止；next action=end_fixed_monthly_information_route_no_parameter_search（不调 sign/horizon/threshold）。
- outer=reused_diagnostic，不作资格/选择；unknown 全保留不填0；每 period 仅 1 独立观察。
- 子 Recorder：62851a0ab548440aa4961627c8b897b4。