# Hierarchical SOXX excess walk-forward

收益头只决定 SOXL/SOXX，风险头只授权防守，现金头只在 hazard 与净现金收益同时满足时加 cash。

In [1]:
from pathlib import Path
import sys
repo_root = Path.cwd().parents[1]
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))
from src.workflow.hierarchical_soxx_excess_walk_forward import run_hierarchical_soxx_excess_walk_forward_card
summary = run_hierarchical_soxx_excess_walk_forward_card(root=repo_root)
summary['promotion_decision']

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[82244:MainThread](2026-07-23 16:00:20,608) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[82244:MainThread](2026-07-23 16:00:21,021) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[82244:MainThread](2026-07-23 16:00:21,021) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[82244:MainThread](2026-07-23 16:00:21,042) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[82244:MainThread](2026-07-23 16:00:21,043) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[82244:MainThread](2026-07-23 16:00:21,043) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[82244:MainThread](2026-07-23 16:00:21,307) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[82244:MainThread](2026-07-23 16:00:21,308) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[82244:MainThread](2026-07-23 16:00:21,308) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

[82244:MainThread](2026-07-23 16:00:21,411) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[82244:MainThread](2026-07-23 16:00:21,412) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[82244:MainThread](2026-07-23 16:00:21,412) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[82244:MainThread](2026-07-23 16:00:21,688) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[82244:MainThread](2026-07-23 16:00:21,689) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[82244:MainThread](2026-07-23 16:00:21,689) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[82244:MainThread](2026-07-23 16:00:38,949) INFO - qlib.workflow - [exp.py:258] - Experiment 554021619276614264 starts running ...

[82244:MainThread](2026-07-23 16:00:39,007) INFO - qlib.workflow - [recorder.py:345] - Recorder 20f4f86ed2254700ba30fd3e999ad392 starts running under Experiment 554021619276614264 ...

[82244:MainThread](2026-07-23 16:00:39,146) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

'needs_iteration_hierarchical_soxx_excess_transfer'

In [2]:
import pandas as pd
card = Path.cwd()
pd.read_csv(card / 'backtest_benchmark_comparison.csv')

,candidate,feature_bundle,model_family,policy_profile,cost_bps,selection_uses_outer_test,return_pct,cagr_pct,annualized_vol_pct,max_drawdown_pct,...,soxx_max_drawdown_pct,soxx_longest_underwater_days,soxx_max_drawdown_recovery_days,cash_entry_days,cash_action_days,hazard_days,downside_avg_cash_weight_pct,downside_min_cash_weight_pct,turnover,segment
0,reintegrated__extra_trees__balanced_half_defen...,reintegrated,extra_trees,balanced_half_defense_hold3,10,False,387.020748,25.410112,34.971512,-36.271440,...,-47.374011,257,56,223,355,514,23.277228,10.0,117.09,development_walk_forward
1,reintegrated__extra_trees__balanced_half_defen...,reintegrated,extra_trees,balanced_half_defense_hold3,25,False,308.610193,22.300719,34.972171,-36.464356,...,-47.374011,257,56,223,355,514,23.277228,10.0,117.09,development_walk_forward
2,reintegrated__extra_trees__balanced_half_defen...,reintegrated,extra_trees,balanced_half_defense_hold3,10,False,395.313314,58.702555,34.137067,-41.579810,...,-42.790391,297,113,233,330,353,26.693548,10.0,57.24,outer_diagnostic
3,reintegrated__extra_trees__balanced_half_defen...,reintegrated,extra_trees,balanced_half_defense_hold3,25,False,354.593534,54.820831,34.141509,-42.522837,...,-42.790391,297,113,233,330,353,26.693548,10.0,57.24,outer_diagnostic

In [3]:
pd.read_csv(card / 'head_oos_audit.csv')

,feature_bundle,model_family,head,evaluation_scope,metric_name,pooled_metric,median_fold_metric,positive_fold_count,fold_count,selection_uses_outer_test
0,current,extra_trees,soxl_relative_alpha_5d,all_rows,spearman_ic,-0.004473,0.030341,5,7,False
1,current,extra_trees,crash_hazard_5d,all_rows,roc_auc,0.721634,0.569110,6,7,False
2,current,extra_trees,cash_action_5d,actual_crash_hazard_rows,roc_auc,0.636844,0.605357,5,7,False
3,current,linear,soxl_relative_alpha_5d,all_rows,spearman_ic,0.040701,0.115595,6,7,False
4,current,linear,crash_hazard_5d,all_rows,roc_auc,0.679257,0.580827,5,7,False
5,current,linear,cash_action_5d,actual_crash_hazard_rows,roc_auc,0.595481,0.623604,4,7,False
6,full,extra_trees,soxl_relative_alpha_5d,all_rows,spearman_ic,-0.019839,0.083666,6,7,False
7,full,extra_trees,crash_hazard_5d,all_rows,roc_auc,0.737956,0.625506,6,7,False
8,full,extra_trees,cash_action_5d,actual_crash_hazard_rows,roc_auc,0.628007,0.502995,3,7,False
9,full,linear,soxl_relative_alpha_5d,all_rows,spearman_ic,0.030148,0.084320,6,7,False
10,full,linear,crash_hazard_5d,all_rows,roc_auc,0.611052,0.558904,4,7,False
11,full,linear,cash_action_5d,actual_crash_hazard_rows,roc_auc,0.535441,0.489631,2,7,False
12,reintegrated,extra_trees,soxl_relative_alpha_5d,all_rows,spearman_ic,0.044138,0.113576,6,7,False
13,reintegrated,extra_trees,crash_hazard_5d,all_rows,roc_auc,0.730170,0.639303,6,7,False
14,reintegrated,extra_trees,cash_action_5d,actual_crash_hazard_rows,roc_auc,0.614067,0.565303,4,7,False
15,reintegrated,linear,soxl_relative_alpha_5d,all_rows,spearman_ic,0.057966,0.053799,6,7,False
16,reintegrated,linear,crash_hazard_5d,all_rows,roc_auc,0.721031,0.594973,6,7,False
17,reintegrated,linear,cash_action_5d,actual_crash_hazard_rows,roc_auc,0.619898,0.468606,3,7,False

In [4]:
pd.read_csv(card / 'regime_metrics.csv')

,regime,rows,return_pct,soxx_return_pct,terminal_wealth_ratio_vs_soxx,avg_cash_weight_pct,avg_soxl_weight_pct,positive_soxx_capture
0,all,2635,2.312279e+03,2.204641e+03,1.046705,21.698292,12.033017,1.007475
1,downtrend,753,4.717560e+02,2.734985e+02,1.530812,24.402390,12.203187,1.047203
2,high_vol,1318,7.075190e+02,6.495265e+02,1.077372,29.768589,10.884674,0.939065
3,positive_soxx,1463,2.102414e+11,1.883002e+11,1.116523,21.719070,12.408066,1.007475

# 分层 SOXL/SOXX/cash walk-forward 结论

- 跑了什么：2016–2022 年度 expanding walk-forward，三类特征包、两类模型、三个独立预测头；2023–2026-07-02 仅作 outer 诊断。
- 开发期：10bp 终值比 SOXX=1.1404，25bp=0.9583；MaxDD=-36.27% vs SOXX -47.37%。
- Outer：10bp 终值比 SOXX=0.9197；MaxDD=-41.58% vs SOXX -42.79%。
- Regime/窗口：开发期最长水下 205 天 vs SOXX 257 天；downside 平均现金 23.28%。
- 晋升决定：needs_iteration_hierarchical_soxx_excess_transfer。
- 风险：策略超额依赖收益头对少数上行窗口的识别；现金动作样本稀疏，outer 若未转移则不能因历史开发期通过而晋升。
- 下一步：若未通过 outer，按 head_oos_audit、outer_head_transfer_diagnostic、action_attribution 和 policy_ablation 区分收益头失效、hazard 误杀或 cash gate 召回不足，不再扩大无约束参数网格。