# 半导体广度与相关性的增量信息检验

固定 BASE5 与 BASE5+4 连续特征，2024/2025/2026 年度前推、H5 现金优势目标、6 次 Ridge 拟合。完整上一交易日已公开持仓篮子；不分类市场状态，不搜索参数，不构造投组。训练起点和 2026 年部分评价范围由完整数据合同预先固定。

In [1]:
from pathlib import Path
import json
import sys
ROOT = Path.cwd().resolve()
while not (ROOT / 'SPEC.md').exists():
    if ROOT == ROOT.parent:
        raise RuntimeError('repository root not found')
    ROOT = ROOT.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
CARD = ROOT / 'research' / 'semiconductor_breadth_20261005'
plan = json.loads((CARD / 'plan.json').read_text())
import qlib
from qlib.data import D
from qlib.data.dataset import DatasetH
from qlib.workflow import R
qlib.init(provider_uri=str(ROOT / plan['source']['provider_uri']), region='us', kernels=1)
calendar = D.calendar(freq='day')
print({'canonical_calendar_start': str(calendar[0]), 'canonical_calendar_end': str(calendar[-1]), 'calendar_rows': len(calendar)})

[79014:MainThread](2026-10-05 12:20:17,917) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[79014:MainThread](2026-10-05 12:20:17,918) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[79014:MainThread](2026-10-05 12:20:17,918) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/semis-breadth-20261005/data/qlib/published_futu_affine_20260925_v1')}

{'canonical_calendar_start': '2010-03-11 00:00:00', 'canonical_calendar_end': '2026-09-25 00:00:00', 'calendar_rows': 4162}

每个标签先在完整 Qlib 日历上用 `-log(SOXX_open[t+6]/SOXX_open[t+1])` 计算，再与完整广度特征日期配对。特征决策时点为纽约 17:00；年度训练除去最后 20 个既有信号行，并独立检查标签在下一年 1 月 1 日前成熟。所有模型输入由 `DatasetH.prepare` 提供。

实现和来源须经独立审阅并有哈希绑定的 root GO；缺少授权、来源或完整配对行时 fail closed。

In [2]:
from src.workflow.semiconductor_breadth import run_experiment
summary = run_experiment(root=ROOT)
with R.uri_context(Path(summary['recorder_uri']).as_uri()):
    recorder = R.get_recorder(recorder_id=summary['recorder_id'], experiment_name=summary['experiment'])
assert recorder.status == 'FINISHED'
print({'status': summary['status'], 'fit_count': summary['fit_count'], 'recorder_id': recorder.id, 'promotion_decision': summary['promotion_decision']})

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[79014:MainThread](2026-10-05 12:20:19,244) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[79014:MainThread](2026-10-05 12:20:19,245) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[79014:MainThread](2026-10-05 12:20:19,245) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/semis-breadth-20261005/data/qlib/published_futu_affine_20260925_v1')}

[79014:MainThread](2026-10-05 12:20:19,282) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[79014:MainThread](2026-10-05 12:20:19,283) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[79014:MainThread](2026-10-05 12:20:19,283) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/semis-breadth-20261005/data/qlib/soxx_pit_leveraged_training_v1')}

[79014:MainThread](2026-10-05 12:20:19,537) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[79014:MainThread](2026-10-05 12:20:19,538) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[79014:MainThread](2026-10-05 12:20:19,539) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/semis-breadth-20261005/data/qlib/semis_wolf_recovery_20241126_v1')}

[79014:MainThread](2026-10-05 12:20:19,781) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[79014:MainThread](2026-10-05 12:20:19,782) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[79014:MainThread](2026-10-05 12:20:19,782) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/semis-breadth-20261005/data/qlib/published_futu_affine_20260925_v1')}

[79014:MainThread](2026-10-05 12:20:19,785) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[79014:MainThread](2026-10-05 12:20:19,785) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[79014:MainThread](2026-10-05 12:20:19,785) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[79014:MainThread](2026-10-05 12:20:19,796) WARNING - qlib.workflow - [expm.py:231] - No valid experiment found. Create a new experiment with name semiconductor_breadth_20261005.

[79014:MainThread](2026-10-05 12:20:19,799) INFO - qlib.workflow - [exp.py:258] - Experiment 464436947409504031 starts running ...

[79014:MainThread](2026-10-05 12:20:19,882) INFO - qlib.workflow - [recorder.py:345] - Recorder e1dd830dcabf4042a75f491747457157 starts running under Experiment 464436947409504031 ...

[79014:MainThread](2026-10-05 12:20:20,520) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

{'status': 'finished', 'fit_count': 6, 'recorder_id': 'e1dd830dcabf4042a75f491747457157', 'promotion_decision': 'not_promoted'}

In [3]:
import pandas as pd
if summary['status'] == 'finished':
    display(pd.read_csv(CARD / 'point_metrics.csv'))
    display(pd.read_csv(CARD / 'bootstrap_summary.csv'))
    display(pd.read_csv(CARD / 'event_metrics.csv'))
from IPython.display import Markdown, display
display(Markdown((CARD / 'conclusion.md').read_text()))

,slice,rows,signal_start,signal_end,trade_start,label_mature_end,base_ic,base_plus_breadth_ic,delta_ic_full_minus_base,base_mse,base_plus_breadth_mse,delta_mse_full_minus_base,mse_reduction_base_minus_full,prior_mean_mse,mse_reduction_prior_mean_minus_full
0,pooled_2024_2026_partial,627,2024-01-02,2026-07-02,2024-01-03,2026-07-13,-0.012878,-0.111686,-0.098808,0.002702,0.002814,0.000112,-0.000112,0.002585,-0.000229
1,year_2024,252,2024-01-02,2024-12-31,2024-01-03,2025-01-10,-0.049413,-0.164426,-0.115014,0.002056,0.002261,0.000206,-0.000206,0.001989,-0.000272
2,year_2025,250,2025-01-02,2025-12-31,2025-01-03,2026-01-09,-0.108653,-0.141794,-0.033140,0.002717,0.002790,0.000074,-0.000074,0.002467,-0.000323
3,year_2026,125,2026-01-02,2026-07-02,2026-01-05,2026-07-13,0.276903,0.280823,0.003920,0.003974,0.003975,0.000002,-0.000002,0.004020,0.000045

,slice,block_length,paths,seed,rows,paired_same_indices,indices_sha256,indices_shape,degenerate_draws,base_ic_official_interval_defined,...,full_conditional_net_event_mean_bp10_q0.5,full_conditional_net_event_mean_bp10_q0.95,full_conditional_net_event_mean_bp10_q0.975,full_conditional_net_event_mean_bp25_official_interval_defined,full_conditional_net_event_mean_bp25_undefined_draws,full_conditional_net_event_mean_bp25_q0.025,full_conditional_net_event_mean_bp25_q0.05,full_conditional_net_event_mean_bp25_q0.5,full_conditional_net_event_mean_bp25_q0.95,full_conditional_net_event_mean_bp25_q0.975
0,pooled_2024_2026_partial,20,2000,20261005,627,True,3248edee29e7142b1d40f0e9335aaa0aebd8f57944dd28...,"[2000, 627]",0,True,...,-193.691006,-99.842458,-84.160422,True,0,-342.208201,-324.736717,-222.008909,-59.528504,-9.355380
1,pooled_2024_2026_partial,60,2000,20261005,627,True,6c5507753e95dcc0da652c638811714b8bed0b7b6c2a9d...,"[2000, 627]",0,True,...,-189.104015,-105.124404,-89.408725,True,0,-327.594044,-314.467609,-219.336269,-38.658085,11.895428

,slice,family,cost_bps,log_hurdle,event_count,coverage,mean_event_gross_log_bp,mean_event_net_log_bp,positive_net_event_fraction,mean_masked_net_log_bp_per_observation,conditional_mean_undefined_reason,event_scope
0,pooled_2024_2026_partial,base,10.0,0.002,175,0.279107,-116.279515,-136.279522,0.342857,-38.036549,NaN,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...
1,pooled_2024_2026_partial,base,25.0,0.005,123,0.196172,-123.632831,-173.632935,0.300813,-34.061963,NaN,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...
2,pooled_2024_2026_partial,base_plus_breadth,10.0,0.002,123,0.196172,-172.782555,-192.782562,0.260163,-37.818589,NaN,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...
3,pooled_2024_2026_partial,base_plus_breadth,25.0,0.005,82,0.130781,-174.650592,-224.650696,0.231707,-29.380155,NaN,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...
4,pooled_2024_2026_partial,prior_mean,10.0,0.002,0,0.000000,NaN,NaN,NaN,0.000000,no_events,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...
5,pooled_2024_2026_partial,prior_mean,25.0,0.005,0,0.000000,NaN,NaN,NaN,0.000000,no_events,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...
6,year_2024,base,10.0,0.002,65,0.257937,-57.506201,-77.506207,0.369231,-19.991680,NaN,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...
7,year_2024,base,25.0,0.005,44,0.174603,30.638622,-19.361482,0.409091,-3.380576,NaN,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...
8,year_2024,base_plus_breadth,10.0,0.002,37,0.146825,-178.967543,-198.967550,0.243243,-29.213489,NaN,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...
9,year_2024,base_plus_breadth,25.0,0.005,17,0.067460,-39.356162,-89.356266,0.352941,-6.028002,NaN,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...
10,year_2024,prior_mean,10.0,0.002,0,0.000000,NaN,NaN,NaN,0.000000,no_events,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...
11,year_2024,prior_mean,25.0,0.005,0,0.000000,NaN,NaN,NaN,0.000000,no_events,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...
12,year_2025,base,10.0,0.002,83,0.332000,-177.057956,-197.057963,0.301205,-65.423244,NaN,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...
13,year_2025,base,25.0,0.005,63,0.252000,-250.280700,-300.280804,0.190476,-75.670763,NaN,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...
14,year_2025,base_plus_breadth,10.0,0.002,61,0.244000,-245.367950,-265.367956,0.180328,-64.749781,NaN,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...
15,year_2025,base_plus_breadth,25.0,0.005,48,0.192000,-254.814519,-304.814624,0.125000,-58.524408,NaN,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...
16,year_2025,prior_mean,10.0,0.002,0,0.000000,NaN,NaN,NaN,0.000000,no_events,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...
17,year_2025,prior_mean,25.0,0.005,0,0.000000,NaN,NaN,NaN,0.000000,no_events,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...
18,year_2026,base,10.0,0.002,27,0.216000,-70.933398,-90.933405,0.407407,-19.641615,NaN,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...
19,year_2026,base,25.0,0.005,16,0.128000,-49.203339,-99.203443,0.437500,-12.698041,NaN,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...
20,year_2026,base_plus_breadth,10.0,0.002,25,0.200000,13.479591,-6.520416,0.480000,-1.304083,NaN,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...
21,year_2026,base_plus_breadth,25.0,0.005,17,0.136000,-83.599816,-133.599920,0.411765,-18.169589,NaN,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...
22,year_2026,prior_mean,10.0,0.002,0,0.000000,NaN,NaN,NaN,0.000000,no_events,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...
23,year_2026,prior_mean,25.0,0.005,0,0.000000,NaN,NaN,NaN,0.000000,no_events,isolated_SOXX_to_CASH_to_SOXX; not a portfolio...

# 最终中文结论

本轮使用固定 BASE5 ETF 特征，对比增加四个连续半导体特征：上涨比例、等权减已披露持仓权重收益、横截面收益标准差与 60 日平均绝对成对相关性。篮子由上一交易日以前已公开 SEC 持仓构成，每日要求完整 30 个成员及 61 个收盘价；不把它称为官方每日指数成分。训练起于 2022-05-27，2024/2025/2026 各年仅拟合两个 StandardScaler + Ridge(alpha=10)，共 6 次，均经 Qlib D → DatasetH.prepare → Recorder；20 行剔除并要求 H5 标签在年界以前成熟。

评价期为 2024—2025 全年与 2026 截至 2026-07-02，共 627 行。BASE5 / 加广度的 Spearman IC 为 -0.012878 / -0.111686，ΔIC=-0.098808，MSE 改善（base-full）=-0.000112。2024年 ΔIC=-0.115014、MSE改善=-0.000206；2025年 ΔIC=-0.033140、MSE改善=-0.000074；2026年 ΔIC=0.003920、MSE改善=-0.000002。未做事后 regime 分组；年间差异见 `point_metrics.csv`。

两个块长 20/60、各 2,000 次相同索引配对自助法结果见 `bootstrap_summary.csv`。信息门 / 增量门 / 经济门为 False / False / False；加广度 IC 为正 1/3 年，IC 增量为正 1/3 年、MSE 改善 0/3 年，结论 `end_route_no_further_search`。10/25bp 仅是重叠独立 H5 现金事件诊断，使用 log((1+c)/(1-c)) 资金门槛，不复利、不年化，不是投组收益或稳定超额验证。

不晋升。全部评价历史已被使用过，样本范围较短，2026 年不完整且没有 8 月窗口；价格复权是回溯版本，不是归档的历史时点复权价。定期披露篮子存在披露滞后与持仓变动风险，旧 WOLF 补充来源及身份限制见 `source_audit.json`。本轮没有 HMM、人工状态配置、参数搜索、投资组合或真实订单。Qlib Recorder：`e1dd830dcabf4042a75f491747457157`。

下一步：结束该路线并保留失败证据，本轮不增加特征或修改门槛。

# 最终中文结论

本轮使用固定 BASE5 ETF 特征，对比增加四个连续半导体特征：上涨比例、等权减已披露持仓权重收益、横截面收益标准差与 60 日平均绝对成对相关性。篮子由上一交易日以前已公开 SEC 持仓构成，每日要求完整 30 个成员及 61 个收盘价；不把它称为官方每日指数成分。训练起于 2022-05-27，2024/2025/2026 各年仅拟合两个 StandardScaler + Ridge(alpha=10)，共 6 次，均经 Qlib D → DatasetH.prepare → Recorder；20 行剔除并要求 H5 标签在年界以前成熟。

评价期为 2024—2025 全年与 2026 截至 2026-07-02，共 627 行。BASE5 / 加广度的 Spearman IC 为 -0.012878 / -0.111686，ΔIC=-0.098808，MSE 改善（base-full）=-0.000112。2024年 ΔIC=-0.115014、MSE改善=-0.000206；2025年 ΔIC=-0.033140、MSE改善=-0.000074；2026年 ΔIC=0.003920、MSE改善=-0.000002。未做事后 regime 分组；年间差异见 `point_metrics.csv`。

两个块长 20/60、各 2,000 次相同索引配对自助法结果见 `bootstrap_summary.csv`。信息门 / 增量门 / 经济门为 False / False / False；加广度 IC 为正 1/3 年，IC 增量为正 1/3 年、MSE 改善 0/3 年，结论 `end_route_no_further_search`。10/25bp 仅是重叠独立 H5 现金事件诊断，使用 log((1+c)/(1-c)) 资金门槛，不复利、不年化，不是投组收益或稳定超额验证。

不晋升。全部评价历史已被使用过，样本范围较短，2026 年不完整且没有 8 月窗口；价格复权是回溯版本，不是归档的历史时点复权价。定期披露篮子存在披露滞后与持仓变动风险，旧 WOLF 补充来源及身份限制见 `source_audit.json`。本轮没有 HMM、人工状态配置、参数搜索、投资组合或真实订单。Qlib Recorder：`e1dd830dcabf4042a75f491747457157`。

下一步：结束该路线并保留失败证据，本轮不增加特征或修改门槛。