# Intraday staged recovery direct SOXL/SOXX/cash allocation

假设：10:30 第一段恢复只解决全天现金过多；第二个模型使用 10:30 后新增路径做二次确认，把额外 beta 限定在 11:00 到收盘，收盘恢复第一段仓位以隔离隔夜尾部风险。

In [1]:
from pathlib import Path
import sys
import pandas as pd
from IPython.display import Markdown, display

ROOT = Path.cwd().resolve()
while not (ROOT / 'AGENTS.md').exists():
    ROOT = ROOT.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from src.workflow.intraday_staged_recovery_direct_allocation import run_intraday_staged_recovery_direct_allocation_card

summary = run_intraday_staged_recovery_direct_allocation_card(root=ROOT)
summary['decision']

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[62063:MainThread](2026-07-24 16:37:31,934) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[62063:MainThread](2026-07-24 16:37:32,293) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[62063:MainThread](2026-07-24 16:37:32,293) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

[62063:MainThread](2026-07-24 16:37:32,483) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[62063:MainThread](2026-07-24 16:37:32,484) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[62063:MainThread](2026-07-24 16:37:32,485) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

[62063:MainThread](2026-07-24 16:37:41,695) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[62063:MainThread](2026-07-24 16:37:41,696) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[62063:MainThread](2026-07-24 16:37:41,697) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[62063:MainThread](2026-07-24 16:37:51,040) INFO - qlib.workflow - [exp.py:258] - Experiment 754044726175152829 starts running ...

[62063:MainThread](2026-07-24 16:37:51,089) INFO - qlib.workflow - [recorder.py:345] - Recorder 3e921b1f2d844fd88541e9c2309a9f03 starts running under Experiment 754044726175152829 ...

[62063:MainThread](2026-07-24 16:37:51,173) INFO - qlib.timer - [log.py:127] - Time cost: 0.004s | waiting `async_log` Done

'promoted_research_candidate_staged_intraday_recovery'

In [2]:
CARD = ROOT / 'research' / 'intraday_staged_recovery_direct_allocation_v1'
display(pd.read_csv(CARD / 'risk_analysis.csv'))
display(pd.read_csv(CARD / 'annual_metrics.csv'))
display(pd.read_csv(CARD / 'stage2_action_attribution.csv'))
display(pd.read_csv(CARD / 'cost_sensitivity.csv'))

,variant,segment,cost_bps,terminal_wealth,return_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,worst_rolling_5d_pct,avg_cash_weight_pct
0,daily_risk_controller,outer_diagnostic_reused,10.0,6.405320,540.531969,-27.445163,-9.382462,-5.202018,-11.301752,37.759811
1,stage1_10_30_recovery,outer_diagnostic_reused,10.0,7.296689,629.668873,-28.105120,-9.382462,-5.253781,-11.301752,35.828892
2,selected_staged_intraday_recovery,outer_diagnostic_reused,10.0,8.127392,712.739209,-28.105120,-9.382462,-5.253781,-11.301752,35.737686
3,selected_staged_intraday_recovery_fixed_decisions,outer_diagnostic_reused,25.0,7.267773,626.777341,-29.088729,-9.382462,-5.262269,-11.485839,35.737686

,year,terminal_wealth,return_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,worst_rolling_5d_pct,terminal_wealth_ratio_vs_soxx,avg_cash_weight_pct,recovery_action_count,stage2_action_count
0,2023,1.417019,41.701863,-21.654721,-5.401278,-4.267412,-8.145401,0.903588,33.607852,3,0
1,2024,1.400497,40.049699,-18.027346,-7.390744,-4.679965,-10.092335,1.159547,41.863090,8,1
2,2025,1.794365,79.436480,-22.933970,-7.185349,-4.954945,-11.075419,1.212587,36.451671,16,6
3,2026,2.282353,128.235256,-21.362152,-9.382462,-7.132735,-11.301752,1.186647,25.905950,5,0

,signal_date,trade_date,soxx_return,recovery_probability,stage2_probability,strategy_return,turnover,stage1_only_return,incremental_return
0,2024-08-02,2024-08-05,0.061992,0.738852,0.711644,0.037826,1.003221,0.032435,0.005391
1,2025-04-08,2025-04-09,0.118258,0.718690,0.886535,0.169308,1.407214,0.064562,0.104746
2,2025-04-10,2025-04-11,0.063333,0.580977,0.712366,0.062821,1.150030,0.041519,0.021301
3,2025-04-14,2025-04-15,-0.045835,0.559159,0.813757,-0.028317,1.083131,-0.009167,-0.019150
4,2025-04-15,2025-04-16,0.013467,0.683398,0.788881,-0.002508,1.536116,0.001635,-0.004143
5,2025-04-21,2025-04-22,0.060643,0.574776,0.774308,0.035446,0.655705,0.018193,0.017253
6,2025-11-13,2025-11-14,0.019421,0.722467,0.782252,-0.006129,1.433366,-0.000094,-0.006035

,variant,segment,cost_bps,terminal_wealth,return_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,worst_rolling_5d_pct,avg_cash_weight_pct
0,selected_staged_intraday_recovery,outer_diagnostic_reused,10.0,8.127392,712.739209,-28.105120,-9.382462,-5.253781,-11.301752,35.737686
1,selected_staged_intraday_recovery_fixed_decisions,outer_diagnostic_reused,25.0,7.267773,626.777341,-29.088729,-9.382462,-5.262269,-11.485839,35.737686

## 中文结论

In [3]:
display(Markdown((CARD / 'conclusion.md').read_text(encoding='utf-8')))

# 中文结论

- 做了什么：保留上一张 10:30 第一段恢复模型；只有第一段已经触发时，第二个模型才使用新增的 10:30-11:00 路径确认是否把有效 beta 临时提高到 1.2。
- 风险结构：第二段仓位只持有到当日常规收盘，收盘确定性退回第一段 0.6 beta，第二段杠杆不隔夜。每次 10:30、第二切点和收盘退回都计算换手成本；未触发时不允许隐含免费再平衡。
- 选择规则：第二切点、Logistic C、阈值和 beta 只使用 2019-2022 开发期年度/两年窗口；2023-2026 不参与选择。由于这些 outer 年份已被前序实验反复诊断，本卡只把它们标记为 reused diagnostic，不能声称是全新未见测试。
- 开发期 10bp：return=481.8952%，MaxDD=-26.1749%，worst 5d=-11.9658%。
- 外层诊断 10bp：return=712.7392%，MaxDD=-28.1051%，worst day=-9.3825%，CVaR5=-5.2538%，worst 5d=-11.3018%。
- 相对第一段：第一段 return=629.6689%，第二段提高 83.0703 个百分点；终值倍率=1.1138。outer 只有 7 次二段动作，其中正增量 4 次、负增量 3 次。
- 现金解释：收盘/隔夜平均现金仅由 35.8289% 降到 35.7377%；收益改善来自少数反弹日的日内现金时点，不是长期取消现金。
- 25bp 冻结决策压力：return=626.7773%，MaxDD=-29.0887%，worst 5d=-11.4858%。
- 原模型差距：原模型 return=707.5934%，新模型仍少 -5.1458 个百分点，但原模型 MaxDD=-48.2641%。
- 是否晋升：promoted_research_candidate_staged_intraday_recovery。这是研究候选，不是生产或实盘成交证明；仍缺 bid/ask、排队、延迟、11:00 与收盘成交 replay。
- qlib recorder：3e921b1f2d844fd88541e9c2309a9f03
- 不构成买卖建议。