# Cross-pair auxiliary training

检验 TQQQ 数据能否改善 SOXL 训练，以及 SOXL 数据能否改善 TQQQ 训练。Outer 不参与候选选择。

In [1]:
from pathlib import Path
import sys
import qlib
from qlib.data import D
from qlib.data.dataset import DatasetH
from qlib.workflow import R
repo_root = Path.cwd().parents[1]
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))
qlib.init(provider_uri=str(repo_root / 'data/qlib/tqqq'), region='us', kernels=1, skip_if_reg=False)
calendar = D.calendar(start_time='2011-01-03', end_time='2026-07-24', freq='day')
from src.workflow.cross_pair_auxiliary_training import run_cross_pair_auxiliary_training_card
summary = run_cross_pair_auxiliary_training_card(root=repo_root)
summary['promotion_decision']

[26651:MainThread](2026-07-25 12:58:05,853) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[26651:MainThread](2026-07-25 12:58:05,855) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[26651:MainThread](2026-07-25 12:58:05,855) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/tqqq')}

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[26651:MainThread](2026-07-25 12:58:07,514) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[26651:MainThread](2026-07-25 12:58:07,514) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[26651:MainThread](2026-07-25 12:58:07,515) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[26651:MainThread](2026-07-25 12:58:07,520) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[26651:MainThread](2026-07-25 12:58:07,521) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[26651:MainThread](2026-07-25 12:58:07,522) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[26651:MainThread](2026-07-25 12:58:07,542) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[26651:MainThread](2026-07-25 12:58:07,543) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[26651:MainThread](2026-07-25 12:58:07,543) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/tqqq')}

[26651:MainThread](2026-07-25 12:58:07,547) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[26651:MainThread](2026-07-25 12:58:07,548) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[26651:MainThread](2026-07-25 12:58:07,548) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/tqqq')}

[26651:MainThread](2026-07-25 12:58:07,566) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[26651:MainThread](2026-07-25 12:58:07,567) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[26651:MainThread](2026-07-25 12:58:07,567) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/upro')}

[26651:MainThread](2026-07-25 12:58:07,572) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[26651:MainThread](2026-07-25 12:58:07,573) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[26651:MainThread](2026-07-25 12:58:07,573) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/upro')}

[26651:MainThread](2026-07-25 12:58:07,592) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[26651:MainThread](2026-07-25 12:58:07,593) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[26651:MainThread](2026-07-25 12:58:07,593) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/spxl')}

[26651:MainThread](2026-07-25 12:58:07,597) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[26651:MainThread](2026-07-25 12:58:07,598) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[26651:MainThread](2026-07-25 12:58:07,598) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/spxl')}

[26651:MainThread](2026-07-25 12:58:07,619) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[26651:MainThread](2026-07-25 12:58:07,620) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[26651:MainThread](2026-07-25 12:58:07,620) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/tecl')}

[26651:MainThread](2026-07-25 12:58:07,625) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[26651:MainThread](2026-07-25 12:58:07,626) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[26651:MainThread](2026-07-25 12:58:07,626) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/tecl')}

[26651:MainThread](2026-07-25 12:58:18,062) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[26651:MainThread](2026-07-25 12:58:18,063) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[26651:MainThread](2026-07-25 12:58:18,063) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[26651:MainThread](2026-07-25 12:58:38,370) INFO - qlib.workflow - [exp.py:258] - Experiment 320943303230068262 starts running ...

[26651:MainThread](2026-07-25 12:58:38,466) INFO - qlib.workflow - [recorder.py:345] - Recorder 6df600b4529d4688a3a674bca0a45d94 starts running under Experiment 320943303230068262 ...

[26651:MainThread](2026-07-25 12:58:38,748) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

'not_promoted_cross_pair_training_gates_failed'

In [2]:
import pandas as pd
card = Path.cwd()
pd.read_csv(card / 'model_selection.csv')

,pair,candidate,auxiliary_weight,turnover_penalty,ratio_10bps,ratio_25bps,dynamic_vs_matched_static,return_pct,max_drawdown_pct,worst_day_pct,...,cvar_gate,worst_5d_gate,cash_gate,capture_gate,year_gate,gate_count,all_gate,selection_score,selected,selection_policy
0,SOXL_SOXX_CASH,own_only_mse,0.00,0.00,0.922238,0.826560,0.971020,263.616655,-49.517400,-9.893677,...,True,False,True,False,False,3,False,-0.123277,False,development_only_gate_count_then_relative_weal...
1,SOXL_SOXX_CASH,own_only_turnover,0.00,0.02,0.903950,0.824058,0.943861,256.406303,-49.827956,-9.873161,...,True,False,True,False,False,3,False,-0.158248,False,development_only_gate_count_then_relative_weal...
2,SOXL_SOXX_CASH,cross_aux25_turnover,0.25,0.02,0.940014,0.874679,0.967646,270.625333,-49.637918,-9.932449,...,True,False,True,False,False,3,False,-0.071780,False,development_only_gate_count_then_relative_weal...
3,SOXL_SOXX_CASH,cross_aux50_turnover,0.50,0.02,0.936969,0.878387,0.959047,269.424878,-49.824220,-9.908625,...,True,False,True,False,False,3,False,-0.098429,False,development_only_gate_count_then_relative_weal...
4,SOXL_SOXX_CASH,cross_equal_turnover,1.00,0.02,0.959995,0.907055,0.978047,278.503260,-49.706904,-9.839439,...,True,False,True,False,False,3,False,-0.016315,True,development_only_gate_count_then_relative_weal...
5,TQQQ_QQQ_CASH,own_only_mse,0.00,0.00,0.905450,0.845130,0.927580,131.475877,-39.184244,-8.695394,...,True,False,True,False,False,3,False,-0.118977,False,development_only_gate_count_then_relative_weal...
6,TQQQ_QQQ_CASH,own_only_turnover,0.00,0.02,0.919396,0.870391,0.939973,135.041138,-39.242376,-8.816796,...,True,False,True,False,False,3,False,-0.089693,False,development_only_gate_count_then_relative_weal...
7,TQQQ_QQQ_CASH,cross_aux25_turnover,0.25,0.02,0.931403,0.887833,0.948702,138.110526,-38.990133,-8.993263,...,True,False,True,False,False,3,False,-0.067137,False,development_only_gate_count_then_relative_weal...
8,TQQQ_QQQ_CASH,cross_aux50_turnover,0.50,0.02,0.935254,0.891273,0.951753,139.095003,-39.115441,-9.072762,...,True,False,True,False,False,3,False,-0.060438,False,development_only_gate_count_then_relative_weal...
9,TQQQ_QQQ_CASH,cross_equal_turnover,1.00,0.02,0.941381,0.895382,0.958973,140.661389,-39.274494,-9.156573,...,True,False,True,False,False,3,False,-0.048980,True,development_only_gate_count_then_relative_weal...

In [3]:
pd.read_csv(card / 'backtest_benchmark_comparison.csv').query("segment == 'outer_diagnostic' and strategy == 'model' and cost_bps == 10")

,pair,leveraged_symbol,underlying_symbol,segment,strategy,cost_bps,selection_uses_outer_test,return_pct,cagr_pct,annualized_vol_pct,...,soxx_return_pct,avg_cash_weight_pct,min_cash_weight_pct,max_cash_weight_pct,zero_cash_days,avg_soxl_weight_pct,avg_soxx_weight_pct,candidate,auxiliary_weight,turnover_penalty
8,SOXL_SOXX_CASH,SOXL,SOXX,outer_diagnostic,model,10,False,306.190828,48.716631,35.260248,...,364.598965,24.680613,15.621559,60.476959,0,11.412399,63.906989,own_only_mse,0.00,0.00
24,SOXL_SOXX_CASH,SOXL,SOXX,outer_diagnostic,model,10,False,309.695798,49.078862,35.524560,...,364.598965,24.423845,15.677853,63.092494,0,11.579931,63.996224,own_only_turnover,0.00,0.02
40,SOXL_SOXX_CASH,SOXL,SOXX,outer_diagnostic,model,10,False,341.916662,52.309008,36.572696,...,364.598965,22.295306,15.771931,59.654665,0,11.797425,65.907269,cross_aux25_turnover,0.25,0.02
56,SOXL_SOXX_CASH,SOXL,SOXX,outer_diagnostic,model,10,False,353.369464,53.416432,36.837756,...,364.598965,21.511386,15.679109,56.281877,0,11.787490,66.701123,cross_aux50_turnover,0.50,0.02
72,SOXL_SOXX_CASH,SOXL,SOXX,outer_diagnostic,model,10,False,367.852168,54.788477,36.975855,...,364.598965,20.796231,15.643682,42.145747,0,11.755023,67.448746,cross_equal_turnover,1.00,0.02
88,TQQQ_QQQ_CASH,TQQQ,QQQ,outer_diagnostic,model,10,False,158.217770,30.813405,20.546871,...,163.602651,19.154811,15.185511,51.279777,0,10.979402,69.865787,own_only_mse,0.00,0.00
104,TQQQ_QQQ_CASH,TQQQ,QQQ,outer_diagnostic,model,10,False,159.299118,30.968284,20.621005,...,163.602651,18.945958,15.252896,46.020728,0,11.017523,70.036519,own_only_turnover,0.00,0.02
120,TQQQ_QQQ_CASH,TQQQ,QQQ,outer_diagnostic,model,10,False,164.101005,31.650506,20.709268,...,163.602651,19.108036,15.426333,37.442958,0,11.356359,69.535605,cross_aux25_turnover,0.25,0.02
136,TQQQ_QQQ_CASH,TQQQ,QQQ,outer_diagnostic,model,10,False,163.533511,31.570346,20.688494,...,163.602651,19.424200,15.518761,43.661872,0,11.523076,69.052724,cross_aux50_turnover,0.50,0.02
152,TQQQ_QQQ_CASH,TQQQ,QQQ,outer_diagnostic,model,10,False,160.532055,31.144310,20.654391,...,163.602651,19.939713,15.618716,48.600337,0,11.681916,68.378371,cross_equal_turnover,1.00,0.02

In [4]:
pd.read_csv(card / 'objective_gate_audit.csv')

,pair,selected_candidate,gate,required,passed,outer_ratio_10bps,outer_ratio_25bps,dynamic_vs_matched_static,selected_vs_own_only_turnover,max_drawdown_pct,worst_rolling_5d_pct,avg_cash_weight_pct,positive_relative_years,risk_passing_years,selection_uses_outer_test
0,SOXL_SOXX_CASH,cross_equal_turnover,selected_uses_auxiliary_data,True,True,1.007002,0.979981,1.025427,1.141950,-44.099426,-17.475112,20.796231,1,2,False
1,SOXL_SOXX_CASH,cross_equal_turnover,return_10bps_vs_underlying,True,True,1.007002,0.979981,1.025427,1.141950,-44.099426,-17.475112,20.796231,1,2,False
2,SOXL_SOXX_CASH,cross_equal_turnover,return_25bps_vs_underlying,True,False,1.007002,0.979981,1.025427,1.141950,-44.099426,-17.475112,20.796231,1,2,False
3,SOXL_SOXX_CASH,cross_equal_turnover,dynamic_vs_matched_static,True,True,1.007002,0.979981,1.025427,1.141950,-44.099426,-17.475112,20.796231,1,2,False
4,SOXL_SOXX_CASH,cross_equal_turnover,selected_vs_own_only_turnover,True,True,1.007002,0.979981,1.025427,1.141950,-44.099426,-17.475112,20.796231,1,2,False
5,SOXL_SOXX_CASH,cross_equal_turnover,maxdd,True,False,1.007002,0.979981,1.025427,1.141950,-44.099426,-17.475112,20.796231,1,2,False
6,SOXL_SOXX_CASH,cross_equal_turnover,worst_day,True,True,1.007002,0.979981,1.025427,1.141950,-44.099426,-17.475112,20.796231,1,2,False
7,SOXL_SOXX_CASH,cross_equal_turnover,cvar5,True,True,1.007002,0.979981,1.025427,1.141950,-44.099426,-17.475112,20.796231,1,2,False
8,SOXL_SOXX_CASH,cross_equal_turnover,worst_rolling_5d,True,False,1.007002,0.979981,1.025427,1.141950,-44.099426,-17.475112,20.796231,1,2,False
9,SOXL_SOXX_CASH,cross_equal_turnover,average_cash,True,True,1.007002,0.979981,1.025427,1.141950,-44.099426,-17.475112,20.796231,1,2,False
10,SOXL_SOXX_CASH,cross_equal_turnover,annual_relative_stability,True,False,1.007002,0.979981,1.025427,1.141950,-44.099426,-17.475112,20.796231,1,2,False
11,SOXL_SOXX_CASH,cross_equal_turnover,annual_risk_stability,True,False,1.007002,0.979981,1.025427,1.141950,-44.099426,-17.475112,20.796231,1,2,False
12,TQQQ_QQQ_CASH,cross_equal_turnover,selected_uses_auxiliary_data,True,True,0.988351,0.966451,1.004777,1.004755,-24.171933,-10.836724,19.939713,1,4,False
13,TQQQ_QQQ_CASH,cross_equal_turnover,return_10bps_vs_underlying,True,False,0.988351,0.966451,1.004777,1.004755,-24.171933,-10.836724,19.939713,1,4,False
14,TQQQ_QQQ_CASH,cross_equal_turnover,return_25bps_vs_underlying,True,False,0.988351,0.966451,1.004777,1.004755,-24.171933,-10.836724,19.939713,1,4,False
15,TQQQ_QQQ_CASH,cross_equal_turnover,dynamic_vs_matched_static,True,True,0.988351,0.966451,1.004777,1.004755,-24.171933,-10.836724,19.939713,1,4,False
16,TQQQ_QQQ_CASH,cross_equal_turnover,selected_vs_own_only_turnover,True,True,0.988351,0.966451,1.004777,1.004755,-24.171933,-10.836724,19.939713,1,4,False
17,TQQQ_QQQ_CASH,cross_equal_turnover,maxdd,True,True,0.988351,0.966451,1.004777,1.004755,-24.171933,-10.836724,19.939713,1,4,False
18,TQQQ_QQQ_CASH,cross_equal_turnover,worst_day,True,True,0.988351,0.966451,1.004777,1.004755,-24.171933,-10.836724,19.939713,1,4,False
19,TQQQ_QQQ_CASH,cross_equal_turnover,cvar5,True,True,0.988351,0.966451,1.004777,1.004755,-24.171933,-10.836724,19.939713,1,4,False
20,TQQQ_QQQ_CASH,cross_equal_turnover,worst_rolling_5d,True,True,0.988351,0.966451,1.004777,1.004755,-24.171933,-10.836724,19.939713,1,4,False
21,TQQQ_QQQ_CASH,cross_equal_turnover,average_cash,True,True,0.988351,0.966451,1.004777,1.004755,-24.171933,-10.836724,19.939713,1,4,False
22,TQQQ_QQQ_CASH,cross_equal_turnover,annual_relative_stability,True,False,0.988351,0.966451,1.004777,1.004755,-24.171933,-10.836724,19.939713,1,4,False
23,TQQQ_QQQ_CASH,cross_equal_turnover,annual_risk_stability,True,True,0.988351,0.966451,1.004777,1.004755,-24.171933,-10.836724,19.939713,1,4,False

## 中文结论

# 结论

- 已比较自身训练、换手正则，以及25%/50%/100%双向辅助样本；所有候选都由网络直接输出合法三资产权重，现金每日不低于15%。
- SOXL/SOXX/cash 开发期选择 `cross_equal_turnover`；outer 10bp收益 367.85%，SOXX 364.60%，财富比 1.0070，25bp财富比 0.9800，MaxDD -44.10%，换手 19.15，平均现金 20.80%；相对自身训练财富比 1.1420。
- TQQQ/QQQ/cash 开发期选择 `cross_equal_turnover`；outer 10bp收益 160.53%，QQQ 163.60%，财富比 0.9884，25bp财富比 0.9665，MaxDD -24.17%，换手 15.95，平均现金 19.94%；相对自身训练财富比 1.0048。
- 两组开发期所有候选都未通过完整门槛，因此这里的选择只是开发期最优诊断候选，不是可晋升模型。
- 晋升：`not_promoted_cross_pair_training_gates_failed`。
- 选择仅使用2016–2022 walk-forward；2023–2026 outer 只报告，不参与候选或参数选择。
- 下一步只保留开发期与outer均证明有增益的辅助方式；若动态模型仍输给同平均仓位静态组合，则停止增加网络复杂度。
- Qlib recorder：`cf4f0295bd4748cdb9a7f8a30ffacc1e`。