# SOXL 区间感知调仓与部署验证

假设：以决策前可知的 SOXX 趋势/震荡/下行信息改善调仓净价值，在保留硬风险限制的同时降低无效换手。首轮四个候选、历史门禁和部署边界预先登记于 selection_plan.json；第二轮三个单一差异对照登记于 followup_plan.json。2023–2026 已被查看，不能作为新的未见测试。

In [1]:
import os
from pathlib import Path
os.environ["MLFLOW_ALLOW_FILE_STORE"]="true"
os.environ["MLFLOW_DISABLE_AGENT_HINT"]="1"
root = Path.cwd().resolve()
while not (root / "AGENTS.md").exists():
    root = root.parent
import sys
sys.path.insert(0, str(root))
import qlib
from qlib.data import D
from qlib.workflow import R
qlib.init(provider_uri=str(root / "data/qlib/soxl_soxx_soxs"), region="us", kernels=1)
calendar = D.calendar(start_time="2011-01-01", end_time="2026-09-25", freq="day")
print("Qlib calendar sessions:", len(calendar))

[42821:MainThread](2026-10-01 13:22:11,042) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[42821:MainThread](2026-10-01 13:22:11,044) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[42821:MainThread](2026-10-01 13:22:11,044) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/data/qlib/soxl_soxx_soxs')}

Qlib calendar sessions: 3956

In [2]:
from src.workflow.stage1_regime_experiment import run_regime_experiment
summary = run_regime_experiment(root=root)
summary

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[42821:MainThread](2026-10-01 13:22:12,364) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[42821:MainThread](2026-10-01 13:22:12,364) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[42821:MainThread](2026-10-01 13:22:12,365) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/data/qlib/soxl_soxx_soxs')}

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[42821:MainThread](2026-10-01 13:22:12,398) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[42821:MainThread](2026-10-01 13:22:12,399) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[42821:MainThread](2026-10-01 13:22:12,399) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/data/qlib/soxl_intraday_15min')}

[42821:MainThread](2026-10-01 13:22:14,746) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[42821:MainThread](2026-10-01 13:22:14,747) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[42821:MainThread](2026-10-01 13:22:14,747) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/data/qlib/soxl_soxx_soxs')}

Reference active_hold_baseline at 10bps

Reference no_hold_reference at 10bps

Reference active_hold_baseline at 25bps

Reference no_hold_reference at 25bps

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[42829:MainThread](2026-10-01 13:22:21,756) INFO - qlib.Initialization - [config.py:452] - default_conf: client.
[42828:MainThread](2026-10-01 13:22:21,772) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[42829:MainThread](2026-10-01 13:22:22,271) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.
[42829:MainThread](2026-10-01 13:22:22,271) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/data/qlib/soxl_soxx_soxs')}
[42828:MainThread](2026-10-01 13:22:22,283) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.
[42828:MainThread](2026-10-01 13:22:22,283) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/data/qlib/soxl_soxx_soxs')}

Training preregistered regime_ridge100_soft
Training preregistered regime_ridge10_soft

[42829:MainThread](2026-10-01 13:22:22,845) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done
[42829:MainThread](2026-10-01 13:22:22,846) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done
[42829:MainThread](2026-10-01 13:22:22,846) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done
[42828:MainThread](2026-10-01 13:22:22,855) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done
[42828:MainThread](2026-10-01 13:22:22,855) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done
[42828:MainThread](2026-10-01 13:22:22,855) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Init data Done

[42828:MainThread](2026-10-01 13:22:23,554) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done
[42828:MainThread](2026-10-01 13:22:23,554) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done
[42828:MainThread](2026-10-01 13:22:23,554) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Init data Done
[42829:MainThread](2026-10-01 13:22:23,556) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done
[42829:MainThread](2026-10-01 13:22:23,556) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done
[42829:MainThread](2026-10-01 13:22:23,557) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Init data Done

[42829:MainThread](2026-10-01 13:22:24,234) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done
[42829:MainThread](2026-10-01 13:22:24,234) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done
[42829:MainThread](2026-10-01 13:22:24,234) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done
[42828:MainThread](2026-10-01 13:22:24,238) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done
[42828:MainThread](2026-10-01 13:22:24,238) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done
[42828:MainThread](2026-10-01 13:22:24,238) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Init data Done

[42828:MainThread](2026-10-01 13:22:24,910) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done
[42828:MainThread](2026-10-01 13:22:24,910) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done
[42828:MainThread](2026-10-01 13:22:24,910) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Init data Done
[42829:MainThread](2026-10-01 13:22:24,911) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done
[42829:MainThread](2026-10-01 13:22:24,911) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done
[42829:MainThread](2026-10-01 13:22:24,911) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Init data Done

[42828:MainThread](2026-10-01 13:22:25,644) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done
[42828:MainThread](2026-10-01 13:22:25,644) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done
[42828:MainThread](2026-10-01 13:22:25,644) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Init data Done
[42829:MainThread](2026-10-01 13:22:25,650) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done
[42829:MainThread](2026-10-01 13:22:25,650) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done
[42829:MainThread](2026-10-01 13:22:25,650) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Init data Done

[42828:MainThread](2026-10-01 13:22:26,360) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done
[42828:MainThread](2026-10-01 13:22:26,360) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done
[42828:MainThread](2026-10-01 13:22:26,360) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Init data Done
[42829:MainThread](2026-10-01 13:22:26,528) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done
[42829:MainThread](2026-10-01 13:22:26,528) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done
[42829:MainThread](2026-10-01 13:22:26,528) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Init data Done

[42828:MainThread](2026-10-01 13:22:27,231) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done
[42828:MainThread](2026-10-01 13:22:27,231) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done
[42828:MainThread](2026-10-01 13:22:27,231) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Init data Done

[42829:MainThread](2026-10-01 13:22:27,537) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done
[42829:MainThread](2026-10-01 13:22:27,537) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done
[42829:MainThread](2026-10-01 13:22:27,537) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Init data Done

Finished regime_ridge10_soft; causal replay reproduced
Training preregistered regime_hist7_soft

[42828:MainThread](2026-10-01 13:22:31,461) INFO - qlib.Initialization - [config.py:452] - default_conf: client.
[42828:MainThread](2026-10-01 13:22:31,461) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.
[42828:MainThread](2026-10-01 13:22:31,461) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/data/qlib/soxl_soxx_soxs')}

Finished regime_ridge100_soft; causal replay reproduced

[42828:MainThread](2026-10-01 13:22:32,017) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done
[42828:MainThread](2026-10-01 13:22:32,017) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done
[42828:MainThread](2026-10-01 13:22:32,017) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Init data Done

[42828:MainThread](2026-10-01 13:22:32,754) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done
[42828:MainThread](2026-10-01 13:22:32,754) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done
[42828:MainThread](2026-10-01 13:22:32,754) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Init data Done

[42828:MainThread](2026-10-01 13:22:33,492) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done
[42828:MainThread](2026-10-01 13:22:33,492) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done
[42828:MainThread](2026-10-01 13:22:33,493) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Init data Done

[42828:MainThread](2026-10-01 13:22:34,231) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done
[42828:MainThread](2026-10-01 13:22:34,231) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done
[42828:MainThread](2026-10-01 13:22:34,231) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Init data Done

[42828:MainThread](2026-10-01 13:22:35,154) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done
[42828:MainThread](2026-10-01 13:22:35,154) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done
[42828:MainThread](2026-10-01 13:22:35,154) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Init data Done

[42828:MainThread](2026-10-01 13:22:35,940) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done
[42828:MainThread](2026-10-01 13:22:35,940) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done
[42828:MainThread](2026-10-01 13:22:35,940) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Init data Done

[42828:MainThread](2026-10-01 13:22:36,915) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done
[42828:MainThread](2026-10-01 13:22:36,915) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done
[42828:MainThread](2026-10-01 13:22:36,915) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Init data Done

Finished regime_hist7_soft; causal replay reproduced

Selection sealed before diagnostic evaluation: {'variant': 'regime_ridge10_soft', 'historical_all_pass': False, 'passed_gate_count': 11, 'minimum_annual_wealth_ratio': 0.8586610602400143, 'minimum_stress_annual_wealth_ratio': 0.8556855333094006, 'stress_return_pct': 229.92507507723084}

[42821:MainThread](2026-10-01 13:22:42,722) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[42821:MainThread](2026-10-01 13:22:42,723) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[42821:MainThread](2026-10-01 13:22:42,723) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[42821:MainThread](2026-10-01 13:22:43,395) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[42821:MainThread](2026-10-01 13:22:43,395) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[42821:MainThread](2026-10-01 13:22:43,396) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[42821:MainThread](2026-10-01 13:22:44,048) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[42821:MainThread](2026-10-01 13:22:44,048) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[42821:MainThread](2026-10-01 13:22:44,048) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[42821:MainThread](2026-10-01 13:22:44,725) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[42821:MainThread](2026-10-01 13:22:44,726) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[42821:MainThread](2026-10-01 13:22:44,726) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[42821:MainThread](2026-10-01 13:22:45,434) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[42821:MainThread](2026-10-01 13:22:45,434) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[42821:MainThread](2026-10-01 13:22:45,435) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[42821:MainThread](2026-10-01 13:22:46,146) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[42821:MainThread](2026-10-01 13:22:46,146) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[42821:MainThread](2026-10-01 13:22:46,146) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[42821:MainThread](2026-10-01 13:22:47,004) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[42821:MainThread](2026-10-01 13:22:47,005) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[42821:MainThread](2026-10-01 13:22:47,005) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[42821:MainThread](2026-10-01 13:22:47,754) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[42821:MainThread](2026-10-01 13:22:47,754) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[42821:MainThread](2026-10-01 13:22:47,754) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[42821:MainThread](2026-10-01 13:22:48,519) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[42821:MainThread](2026-10-01 13:22:48,520) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[42821:MainThread](2026-10-01 13:22:48,520) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[42821:MainThread](2026-10-01 13:22:49,254) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[42821:MainThread](2026-10-01 13:22:49,254) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[42821:MainThread](2026-10-01 13:22:49,255) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[42821:MainThread](2026-10-01 13:22:56,942) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[42821:MainThread](2026-10-01 13:22:56,943) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[42821:MainThread](2026-10-01 13:22:56,944) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/data/qlib/soxl_soxx_soxs')}

[42821:MainThread](2026-10-01 13:22:56,953) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[42821:MainThread](2026-10-01 13:22:56,957) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[42821:MainThread](2026-10-01 13:22:56,961) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[42821:MainThread](2026-10-01 13:22:56,961) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[42821:MainThread](2026-10-01 13:22:56,964) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x122fca6f0>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)

[42821:MainThread](2026-10-01 13:22:57,317) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[42821:MainThread](2026-10-01 13:22:57,318) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[42821:MainThread](2026-10-01 13:22:57,318) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/data/qlib/soxl_soxx_soxs')}

[42821:MainThread](2026-10-01 13:22:57,321) INFO - qlib.workflow - [exp.py:258] - Experiment 138807958067870112 starts running ...

[42821:MainThread](2026-10-01 13:22:57,466) INFO - qlib.workflow - [recorder.py:345] - Recorder 49fdd8b009ba4487952e08b986c08376 starts running under Experiment 138807958067870112 ...

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[42821:MainThread](2026-10-01 13:22:57,639) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

{'experiment': 'stage1_regime_deployment_20261001',
 'decision': 'not_promoted_historical_gates_failed',
 'selected': {'variant': 'regime_ridge10_soft',
  'historical_all_pass': False,
  'passed_gate_count': 11,
  'minimum_annual_wealth_ratio': 0.8586610602400143,
  'minimum_stress_annual_wealth_ratio': 0.8556855333094006,
  'stress_return_pct': 229.92507507723084},
 'source_as_of': '2026-09-25',
 'provider_uri': 'data/qlib/soxl_soxx_soxs',
 'region': 'us',
 'market': 'all',
 'data_range': ['2016-01-04', '2026-09-23'],
 'plan_sha256': '3bbcc97c22719bbe781002a0dd89f685db15813e82dddf3edfe634e3ae443de0',
 'followup_plan_sha256': 'a056ab13e2626527f8073e0001f9a58ea714daecf6245fd322f8f9439c836db1',
 'previous_trial_recorder_id': 'f8aa6df6644d45909fb6d59ad41d67a6',
 'selection_uses_outer_test': False,
 'baseline_reproduction_pass': True,
 'recorder_id': '49fdd8b009ba4487952e08b986c08376',
 'recorder_uri': '/Users/rziiiii/dev/workspace/research/stage1_regime_deployment_20261001/qlib_recorder',
 'recorder_local_dir': '/Users/rziiiii/dev/workspace/research/stage1_regime_deployment_20261001/qlib_recorder/138807958067870112/49fdd8b009ba4487952e08b986c08376',
 'recorder_relative_dir': 'qlib_recorder/138807958067870112/49fdd8b009ba4487952e08b986c08376',
 'allocation_source': {'card_path': 'research/pit_constituent_auxiliary_training_allocation_retrained_20260928',
  'manifest_sha256': '44c1a375ea575f1055ff46850a9c8dbc30d121d97919231efbf9084504628112',
  'recorder_id': 'f696f656b3d44e868588e09a5d97c905'},
 'source_audit': {'path': 'qlib_recorder/517305099807006126/17f81fbf27ee46859816ec1ac52151f6/artifacts/inputs/prepared_inputs.pkl',
  'sha256': '8baa4f74449c1da41eb189f51c75074a61dacb8d7c8540710f4f67560d58d4aa',
  'source': 'frozen Qlib feature/model/recorder inputs',
  'source_allocation_recorder': 'f696f656b3d44e868588e09a5d97c905',
  'source_card': 'stage1_economic_action_20260929',
  'recorder_id': '17f81fbf27ee46859816ec1ac52151f6'},
 'feature_audit': {'provider_uri': '/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/data/qlib/soxl_soxx_soxs',
  'source_api': 'qlib.data.D.features',
  'calendar_api': 'qlib.data.D.calendar',
  'instrument': 'SOXX',
  'fields': ['$close'],
  'schema_version': 'causal_soxx_close_regime_v1',
  'feature_scope': 'price_only; canonical daily provider does not contain historical SOXX volume',
  'warmup_start': '2010-10-05',
  'signal_start': '2011-01-03',
  'signal_end': '2026-09-25',
  'future_fill': False,
  'source_sha256': '5ab763ed456927ab6ab3d546a6c12558249661079893406e742363c7a70ff7d3'},
 'first_hour_audit': {'status': 'passed',
  'provider_uri': '/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/data/qlib/soxl_intraday_15min',
  'provider_as_of': '2026-09-25',
  'provider_manifest_sha256': 'b4b024257464981a27397b4a1169d896639c8b8fbd2340a3341a356000327664',
  'source_api': ['qlib.init', 'qlib.data.D.features'],
  'rows': 2690,
  'valid_recovery_rows': 1937,
  'unavailable_recovery_rows': 753,
  'invalid_retained_recovery_rows': 0,
  'maximum_retained_feature_error': 0.0,
  'source_unchanged': True,
  'bar_count_semantics': 'full-session 15-minute bar count, not observed first-hour minute coverage; not a model feature',
  'limitation': 'Exact aggregate bar timestamps do not prove every underlying one-minute observation is present.'},
 'native_qlib_audit': {'status': 'passed',
  'sessions': 752,
  'start': '2016-01-05',
  'end': '2018-12-28',
  'provider_uri': '/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/data/qlib/soxl_soxx_soxs',
  'cost_bps': 10.0,
  'initial_cash': 100000.0,
  'maximum_session_return_error': 4.3532117910416446e-08,
  'tolerance': 1e-07,
  'native_api': 'qlib.backtest.backtest + SimulatorExecutor + Exchange + Position',
  'schedule_strategy': 'DirectTargetWeightStrategy subclass with observed-open sizing and fee-affordable targets',
  'report_mark': 'native daily same-day close; next-open reconciliation uses native positions and Qlib D.features',
  'scope': 'prescribed open-only schedule settlement; controller selection and intraday recovery not independently validated',
  'execution_limitation': 'Historical open marks, not executable 09:31 prices; continuous adjusted shares, no spread/impact/partial fills.'},
 'selected_spec': {'name': 'regime_ridge10_soft',
  'estimator': 'ridge',
  'use_regime': True,
  'ridge_alpha': 10.0,
  'min_advantage_bps': 0.0,
  'protect_derisk': False,
  'minimum_training_rows': 200,
  'max_leaf_nodes': 7,
  'max_iter': 80,
  'l2_regularization': 10.0},
 'final_model_training_end': '2025-12-31',
 'dataset_audit': {'dataset_class': 'qlib.data.dataset.DatasetH',
  'handler_class': 'qlib.data.dataset.handler.DataHandlerLP',
  'loader_class': 'qlib.data.dataset.loader.StaticDataLoader',
  'features': ['portfolio_drawdown',
   'current_beta_cap',
   'raw_effective_beta',
   'risk_state',
   'raw_soxl_weight',
   'raw_soxx_weight',
   'raw_cash_weight',
   'tail_probability',
   'alpha_probability',
   'portfolio_ret_1d',
   'portfolio_ret_3d',
   'portfolio_ret_5d',
   'target_soxl_weight',
   'target_soxx_weight',
   'target_cash_weight',
   'pretrade_soxl_weight',
   'pretrade_soxx_weight',
   'pretrade_cash_weight',
   'soxl_weight_delta',
   'soxx_weight_delta',
   'effective_beta_delta',
   'open_turnover',
   'risk_clock',
   'days_since_trade',
   'hard_beta_cap',
   'regime_momentum_20',
   'regime_momentum_60',
   'regime_efficiency_20',
   'regime_volatility_20',
   'regime_drawdown_60',
   'regime_up_probability',
   'regime_range_probability',
   'regime_down_probability',
   'regime_up_probability__effective_beta_delta',
   'regime_up_probability__open_turnover',
   'regime_up_probability__soxl_weight_delta',
   'regime_up_probability__soxx_weight_delta',
   'regime_range_probability__effective_beta_delta',
   'regime_range_probability__open_turnover',
   'regime_range_probability__soxl_weight_delta',
   'regime_range_probability__soxx_weight_delta',
   'regime_down_probability__effective_beta_delta',
   'regime_down_probability__open_turnover',
   'regime_down_probability__soxl_weight_delta',
   'regime_down_probability__soxx_weight_delta'],
  'training_state': 'causal_own_policy_path',
  'evaluation_segment_reset': True,
  'training_history_reset_on_segment': False,
  'label_cost_bps': 25.0,
  'label_proxy': 'one session execute-versus-hold net value plus common next own-policy desired-target reset cost; not a multiday policy rollout',
  'maturity': 'label_available_at strictly before both January 1 New York of fit year and first fit-year decision',
  'recovery_branches': "separately recomputed from each branch's marked holdings; same frozen open controller snapshot",
  'maximum_training_signal_year': 2025,
  'fit_year_by_decision_year': {2016: None,
   2017: 2017,
   2018: 2018,
   2019: 2019,
   2020: 2020,
   2021: 2021,
   2022: 2022,
   2023: 2023,
   2024: 2024,
   2025: 2025,
   2026: 2026},
  'regime_schema_version': 'causal_soxx_close_regime_v1',
  'regime_source': {'provider_uri': '/Users/rziiiii/dev/workspace-worktrees/regime-deployment-20261001/data/qlib/soxl_soxx_soxs',
   'source_api': 'qlib.data.D.features',
   'calendar_api': 'qlib.data.D.calendar',
   'instrument': 'SOXX',
   'fields': ['$close'],
   'schema_version': 'causal_soxx_close_regime_v1',
   'feature_scope': 'price_only; canonical daily provider does not contain historical SOXX volume',
   'warmup_start': '2010-10-05',
   'signal_start': '2011-01-03',
   'signal_end': '2026-09-25',
   'future_fill': False,
   'source_sha256': '5ab763ed456927ab6ab3d546a6c12558249661079893406e742363c7a70ff7d3'},
  'spec': {'name': 'regime_ridge10_soft',
   'estimator': 'ridge',
   'use_regime': True,
   'ridge_alpha': 10.0,
   'min_advantage_bps': 0.0,
   'protect_derisk': False,
   'minimum_training_rows': 200,
   'max_leaf_nodes': 7,
   'max_iter': 80,
   'l2_regularization': 10.0}},
 'source_sha256': {'src/workflow/stage1_regime_action.py': '6d906a3c4f7bc33d18aaea6c04884cfd36b50f5efa5bbc57d98f3fa0f55786d2',
  'src/workflow/stage1_regime_experiment.py': 'c761133c83c7de646c33ecc1f503a6ebdcaf7e3448c90202e9082e7875ab49c9',
  'src/analysis/stage1_regime_validation.py': '3184a3769127b144d57c083b59d87d5f9e2e9dea7711fc47fe067b6f2503b42f'},
 'model_artifacts': {'selected_action': {'path': 'qlib_recorder/138807958067870112/49fdd8b009ba4487952e08b986c08376/artifacts/models/selected_action.pkl',
   'sha256': '9bbe6c69e89ed5212d6f63043ae99b2cfd4eb95c8cf6785226661e9413064b1e'},
  'selected_spec': {'path': 'qlib_recorder/138807958067870112/49fdd8b009ba4487952e08b986c08376/artifacts/models/selected_spec.pkl',
   'sha256': 'e08a94ebf0fd204b70e3712c7b5229893bbf60e0ae24a7567b7e98f2ca988330'},
  'recovery_models': {'path': 'qlib_recorder/138807958067870112/49fdd8b009ba4487952e08b986c08376/artifacts/models/recovery_models.pkl',
   'sha256': 'ec8613b29fafaa7c9e57209c844b093b5fe032446de810505e77c7e694367af7'},
  'recovery_selection': {'path': 'qlib_recorder/138807958067870112/49fdd8b009ba4487952e08b986c08376/artifacts/models/recovery_selection.pkl',
   'sha256': 'ee811aab1d0ba67dfc89577503efab4dbb4e06598c73e94f8a673e736ec4c116'}},
 'sealed_source_objects': {'models/selected_action.pkl': '9bbe6c69e89ed5212d6f63043ae99b2cfd4eb95c8cf6785226661e9413064b1e',
  'models/selected_spec.pkl': 'e08a94ebf0fd204b70e3712c7b5229893bbf60e0ae24a7567b7e98f2ca988330',
  'inputs/prepared_inputs.pkl': 'e518b3c7e8f51b389afb9624503cc8897095bb65c324ed150ac2d8ed3c29c7b1',
  'training/expanded_model_training.pkl': '92531df2677314cb8209e96d112d7834246b0b9faaaf0eed7e374f5f2d56cc22'},
 'artifact_policy': {'policy': 'slim_card_recorder_first',
  'workflow_config': 'workflow.yaml',
  'recorder_only_artifacts': ['inputs/*.pkl',
   'training/*.pkl',
   'analysis/portfolio_replays.pkl',
   'portfolio_analysis/native_reconciliation.pkl',
   'models/*.pkl']},
 'promotion': {'historical_pass': False,
  'native_reconciliation_pass': True,
  'new_continuous_forward_pass': False,
  'broker_release_changed': False,
  'real_execution': False},
 'limitations': ['All2023-2026 observations were previously reviewed; reused diagnostic only.',
  'Historical replay uses session open, not actual09:31 executable quote; native reconciliation does not remove this limitation.',
  'No first-hour recovery history before2019; missing bars do not fabricate recovery.',
  'Action supervision is a one-session reset-cost proxy, not a multiday controller optimum.',
  'Regime probabilities are smooth causal state scores, not calibrated future probabilities.',
  'Continuous-weight evidence does not demonstrate integer-share broker fills.',
  'No candidate is promoted before new continuous forward evidence.'],
 'qlib_docs_reference': ['https://qlib.readthedocs.io/en/latest/component/data.html',
  'https://qlib.readthedocs.io/en/latest/component/recorder.html',
  'https://qlib.readthedocs.io/en/latest/component/strategy.html']}

In [3]:
import pandas as pd
card = root / "research/stage1_regime_deployment_20261001"
display(pd.read_csv(card / "backtest_benchmark_comparison.csv"))
display(pd.read_csv(card / "development_gates.csv"))
display(pd.read_csv(card / "regime_metrics.csv"))

,variant,segment,cost_bps,terminal_wealth,return_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,worst_rolling_5d_pct,total_turnover,open_trade_days,recovery_action_count,avg_cash_weight_pct
0,active_hold_baseline,development_walk_forward,10.0,2.707450,170.744997,-30.083233,-7.113776,-3.538537,-10.823738,103.433381,1457,3,5.355939e+01
1,no_hold_reference,development_walk_forward,10.0,2.150363,115.036339,-29.930616,-7.113776,-3.484579,-10.823738,106.920191,1713,3,5.421350e+01
2,economic_own_state_reference,development_walk_forward,10.0,3.004894,200.489432,-29.027730,-7.460937,-3.055820,-10.820572,46.647209,597,0,5.783996e+01
3,active_hold_baseline,development_walk_forward,25.0,1.967609,96.760893,-30.077734,-7.116038,-3.585222,-11.889098,114.423594,1478,3,5.311922e+01
4,no_hold_reference,development_walk_forward,25.0,2.512705,151.270490,-29.999829,-7.116038,-3.642867,-11.889098,111.512289,1721,3,5.226951e+01
5,economic_own_state_reference,development_walk_forward,25.0,2.608518,160.851809,-30.179242,-8.259297,-3.077741,-10.993481,49.020774,614,0,5.868315e+01
6,action_ridge,development_walk_forward,10.0,1.920146,92.014569,-28.111304,-9.495368,-3.652288,-14.983356,79.216759,852,1,5.818001e+01
7,action_ridge,development_walk_forward,25.0,1.722890,72.289002,-28.380680,-9.495368,-3.550348,-15.056452,80.743519,875,1,5.833965e+01
8,regime_ridge10,development_walk_forward,10.0,1.194996,19.499564,-35.114366,-9.495368,-3.504471,-14.715168,80.209683,855,2,6.271785e+01
9,regime_ridge10,development_walk_forward,25.0,1.270230,27.022959,-34.133183,-8.230222,-2.912843,-10.993481,69.375939,843,0,6.592225e+01
10,regime_ridge100,development_walk_forward,10.0,2.510127,151.012655,-27.245958,-9.979319,-3.881081,-15.173673,89.462636,900,2,5.515432e+01
11,regime_ridge100,development_walk_forward,25.0,2.081851,108.185055,-30.655464,-8.989253,-3.510375,-14.061466,83.173131,923,0,6.066573e+01
12,regime_hist7,development_walk_forward,10.0,1.660253,66.025255,-29.573713,-9.631879,-3.228788,-10.820572,78.247922,973,0,5.972499e+01
13,regime_hist7,development_walk_forward,25.0,1.550823,55.082281,-29.604288,-9.633107,-3.106622,-10.993481,70.784976,962,0,6.050967e+01
14,regime_ridge10_soft,development_walk_forward,10.0,3.624906,262.490584,-26.001748,-10.920967,-3.713144,-13.367893,75.572282,789,1,4.905464e+01
15,regime_ridge10_soft,development_walk_forward,25.0,3.299251,229.925075,-30.252979,-11.006984,-3.666978,-13.526546,73.612402,827,1,4.967685e+01
16,regime_ridge100_soft,development_walk_forward,10.0,2.733430,173.342974,-33.720677,-10.926525,-3.480181,-12.656716,66.351104,967,2,5.265012e+01
17,regime_ridge100_soft,development_walk_forward,25.0,1.833446,83.344601,-35.140402,-11.020862,-3.377234,-12.824827,66.563565,933,3,5.445073e+01
18,regime_hist7_soft,development_walk_forward,10.0,1.931574,93.157396,-29.621680,-7.117665,-3.285213,-11.246098,62.881433,798,0,5.657105e+01
19,regime_hist7_soft,development_walk_forward,25.0,2.013614,101.361448,-29.166384,-7.115768,-3.371912,-10.993481,66.829468,830,0,5.510753e+01
20,active_hold_baseline,outer_reused_diagnostic,10.0,3.194260,219.426019,-26.921781,-8.704025,-4.795462,-14.553374,57.437770,791,0,4.839832e+01
21,no_hold_reference,outer_reused_diagnostic,10.0,3.203673,220.367320,-26.921781,-8.704025,-4.811696,-14.553374,59.539806,906,0,4.822305e+01
22,regime_ridge10_soft_frozen2022,outer_reused_diagnostic,10.0,2.968369,196.836878,-26.927866,-8.702876,-4.882764,-14.552752,46.957189,544,0,4.981483e+01
23,regime_ridge10_soft_expanded2025,outer_reused_diagnostic,10.0,3.629459,262.945944,-26.920189,-8.702876,-4.791077,-14.552752,49.304341,584,0,4.930786e+01
24,active_hold_baseline,outer_reused_diagnostic,25.0,1.751089,75.108862,-32.380969,-11.199483,-4.420564,-14.635573,50.618160,746,0,5.855267e+01
25,no_hold_reference,outer_reused_diagnostic,25.0,1.660869,66.086931,-36.441787,-11.199483,-4.403429,-14.635573,46.931016,916,0,5.924826e+01
26,regime_ridge10_soft_frozen2022,outer_reused_diagnostic,25.0,1.614187,61.418682,-28.099045,-8.720969,-4.559106,-14.633923,47.734154,644,0,5.745134e+01
27,regime_ridge10_soft_expanded2025,outer_reused_diagnostic,25.0,2.710183,171.018324,-27.312343,-8.720969,-4.779865,-14.633923,51.189051,591,0,5.019777e+01
28,SOXL_buy_hold,development_walk_forward,10.0,5.906923,490.692296,-91.291416,-27.476609,-13.215909,-57.080211,0.999001,1,0,-3.600894e-15
29,SOXL_buy_hold,development_walk_forward,25.0,5.898085,489.808467,-91.291416,-27.476609,-13.215909,-57.080211,0.997506,1,0,-1.101322e-15
30,SOXX_buy_hold,development_walk_forward,10.0,4.202835,320.283513,-47.374015,-9.325033,-4.417736,-17.254916,0.999001,1,0,-6.471453e-15
31,SOXX_buy_hold,development_walk_forward,25.0,4.196547,319.654660,-47.374015,-9.325033,-4.419380,-17.254916,0.997506,1,0,-1.979273e-15
32,SOXL_buy_hold,outer_reused_diagnostic,10.0,15.421504,1442.150401,-88.657522,-27.324617,-15.530365,-47.710689,0.999001,1,0,-4.977822e-15
33,SOXL_buy_hold,outer_reused_diagnostic,25.0,15.398429,1439.842944,-88.657522,-27.324617,-15.530365,-47.710689,0.997506,1,0,-1.522451e-15
34,SOXX_buy_hold,outer_reused_diagnostic,10.0,4.977558,397.755794,-42.790376,-9.654284,-5.285490,-17.688149,0.999001,1,0,-7.623524e-15
35,SOXX_buy_hold,outer_reused_diagnostic,25.0,4.970110,397.011023,-42.790376,-9.654284,-5.285490,-17.688149,0.997506,1,0,-2.331631e-15

,variant,reference,net_return_above_reference,stress_return_above_reference,max_drawdown_not_worse,worst_day_not_worse,cvar5_not_worse,worst_5d_not_worse,open_trade_days_reduced_8pct,turnover_not_increased,annual_wealth_ratio_at_least_0.985,minimum_annual_wealth_ratio,passed_gate_count,all_pass
0,action_ridge,active_hold_baseline,False,False,True,False,False,False,True,True,False,0.645715,3,False
1,action_ridge,no_hold_reference,False,False,True,False,False,False,True,True,False,0.786164,3,False
2,regime_ridge10,active_hold_baseline,False,False,False,False,True,False,True,True,False,0.559592,3,False
3,regime_ridge10,no_hold_reference,False,False,False,False,False,False,True,True,False,0.629988,2,False
4,regime_ridge100,active_hold_baseline,False,True,True,False,False,False,True,True,False,0.703669,4,False
5,regime_ridge100,no_hold_reference,True,False,True,False,False,False,True,True,False,0.885898,4,False
6,regime_hist7,active_hold_baseline,False,False,True,False,True,True,True,True,False,0.798642,5,False
7,regime_hist7,no_hold_reference,False,False,True,False,True,True,True,True,False,0.902384,5,False
8,regime_ridge10_soft,active_hold_baseline,True,True,True,False,False,False,True,True,False,0.858661,5,False
9,regime_ridge10_soft,no_hold_reference,True,True,True,False,False,False,True,True,True,0.996960,6,False
10,regime_ridge100_soft,active_hold_baseline,True,False,False,False,True,False,True,True,False,0.613604,4,False
11,regime_ridge100_soft,no_hold_reference,True,False,False,False,True,False,True,True,False,0.614271,4,False
12,regime_hist7_soft,active_hold_baseline,False,True,True,False,True,False,True,True,False,0.742326,5,False
13,regime_hist7_soft,no_hold_reference,False,False,True,False,True,False,True,True,False,0.876094,4,False

,variant,segment,cost_bps,regime,sessions,episodes,conditional_compounded_return_pct,mean_daily_net_return_pct,turnover,open_trade_days,worst_contiguous_episode_drawdown_pct,return_is_noncontiguous_conditional_statistic
0,active_hold_baseline,development_walk_forward,10.0,down,168,20,11.375038,0.074637,11.376450,152,-9.990162,True
1,active_hold_baseline,development_walk_forward,10.0,range,834,62,72.808242,0.076813,52.543159,724,-13.530631,True
2,active_hold_baseline,development_walk_forward,10.0,up,754,41,40.672149,0.052784,39.513772,581,-9.667856,True
3,no_hold_reference,development_walk_forward,10.0,down,168,20,12.198781,0.078564,11.961465,167,-9.075454,True
4,no_hold_reference,development_walk_forward,10.0,range,834,62,35.325179,0.046748,55.119596,829,-13.520320,True
...,...,...,...,...,...,...,...,...,...,...,...,...
103,SOXX_buy_hold,outer_reused_diagnostic,10.0,range,443,34,59.527108,0.131812,0.999001,1,-20.721794,True
104,SOXX_buy_hold,outer_reused_diagnostic,10.0,up,426,21,100.394008,0.187187,0.000000,0,-10.826740,True
105,SOXX_buy_hold,outer_reused_diagnostic,25.0,down,65,12,55.703043,0.743287,0.000000,0,-18.895711,True
106,SOXX_buy_hold,outer_reused_diagnostic,25.0,range,443,34,59.288414,0.131476,0.997506,1,-20.721794,True
107,SOXX_buy_hold,outer_reused_diagnostic,25.0,up,426,21,100.394008,0.187187,0.000000,0,-10.826740,True

In [4]:
from IPython.display import Markdown, display
display(Markdown((card / "conclusion.md").read_text()))

# 区间感知调仓与部署验证

完成7个有界共享动作模型的年度滚动训练；首轮四个，后续三个仅取消普通软目标降beta的强制执行，硬风险限制不变。两轮选择均在各自 outer 诊断前封存；这是自适应开发，不是新的独立测试。选中 regime_ridge10_soft，历史门全部通过=False。

开发期2016–2022，10bp扣费后的连续持仓路径：
- active_hold_baseline：收益170.74%，MaxDD -30.08%，CVaR5 -3.54%，调仓1457日，换手103.433。
- no_hold_reference：收益115.04%，MaxDD -29.93%，CVaR5 -3.48%，调仓1713日，换手106.920。
- economic_own_state_reference：收益200.49%，MaxDD -29.03%，CVaR5 -3.06%，调仓597日，换手46.647。
- action_ridge：收益92.01%，MaxDD -28.11%，CVaR5 -3.65%，调仓852日，换手79.217。
- regime_ridge10：收益19.50%，MaxDD -35.11%，CVaR5 -3.50%，调仓855日，换手80.210。
- regime_ridge100：收益151.01%，MaxDD -27.25%，CVaR5 -3.88%，调仓900日，换手89.463。
- regime_hist7：收益66.03%，MaxDD -29.57%，CVaR5 -3.23%，调仓973日，换手78.248。
- regime_ridge10_soft：收益262.49%，MaxDD -26.00%，CVaR5 -3.71%，调仓789日，换手75.572。
- regime_ridge100_soft：收益173.34%，MaxDD -33.72%，CVaR5 -3.48%，调仓967日，换手66.351。
- regime_hist7_soft：收益93.16%，MaxDD -29.62%，CVaR5 -3.29%，调仓798日，换手62.881。
- SOXL_buy_hold：收益490.69%，MaxDD -91.29%，CVaR5 -13.22%，调仓1日，换手0.999。
- SOXX_buy_hold：收益320.28%，MaxDD -47.37%，CVaR5 -4.42%，调仓1日，换手0.999。

分上行/震荡/下行的条件收益、换手和连续区间回撤见regime_metrics.csv；不能把不连续区间收益当成可直接交易的独立策略。25bp压力从各自净持仓重新走完整路径。

2023–2026仅作复用诊断；最终动作模型信息截至2025年末。历史开盘价与09:31真实报价的差异、新候选连续前向表现和整数股执行仍须单独验证。

晋升决定：not_promoted_historical_gates_failed。保留每一项失败门；准备独立paper观察，不据此替换原SIM或下真实订单。

下一步：以冻结模型、候选自身持仓和实际观测报价累计连续前向证据。
QLib recorder：49fdd8b009ba4487952e08b986c08376。

# 区间感知调仓与部署验证

完成7个有界共享动作模型的年度滚动训练；首轮四个，后续三个仅取消普通软目标降beta的强制执行，硬风险限制不变。两轮选择均在各自 outer 诊断前封存；这是自适应开发，不是新的独立测试。选中 regime_ridge10_soft，历史门全部通过=False。

开发期2016–2022，10bp扣费后的连续持仓路径：
- active_hold_baseline：收益170.74%，MaxDD -30.08%，CVaR5 -3.54%，调仓1457日，换手103.433。
- no_hold_reference：收益115.04%，MaxDD -29.93%，CVaR5 -3.48%，调仓1713日，换手106.920。
- economic_own_state_reference：收益200.49%，MaxDD -29.03%，CVaR5 -3.06%，调仓597日，换手46.647。
- action_ridge：收益92.01%，MaxDD -28.11%，CVaR5 -3.65%，调仓852日，换手79.217。
- regime_ridge10：收益19.50%，MaxDD -35.11%，CVaR5 -3.50%，调仓855日，换手80.210。
- regime_ridge100：收益151.01%，MaxDD -27.25%，CVaR5 -3.88%，调仓900日，换手89.463。
- regime_hist7：收益66.03%，MaxDD -29.57%，CVaR5 -3.23%，调仓973日，换手78.248。
- regime_ridge10_soft：收益262.49%，MaxDD -26.00%，CVaR5 -3.71%，调仓789日，换手75.572。
- regime_ridge100_soft：收益173.34%，MaxDD -33.72%，CVaR5 -3.48%，调仓967日，换手66.351。
- regime_hist7_soft：收益93.16%，MaxDD -29.62%，CVaR5 -3.29%，调仓798日，换手62.881。
- SOXL_buy_hold：收益490.69%，MaxDD -91.29%，CVaR5 -13.22%，调仓1日，换手0.999。
- SOXX_buy_hold：收益320.28%，MaxDD -47.37%，CVaR5 -4.42%，调仓1日，换手0.999。

分上行/震荡/下行的条件收益、换手和连续区间回撤见regime_metrics.csv；不能把不连续区间收益当成可直接交易的独立策略。25bp压力从各自净持仓重新走完整路径。

2023–2026仅作复用诊断；最终动作模型信息截至2025年末。历史开盘价与09:31真实报价的差异、新候选连续前向表现和整数股执行仍须单独验证。

晋升决定：not_promoted_historical_gates_failed。保留每一项失败门；准备独立paper观察，不据此替换原SIM或下真实订单。

下一步：以冻结模型、候选自身持仓和实际观测报价累计连续前向证据。
QLib recorder：49fdd8b009ba4487952e08b986c08376。