# SOXL Intraday 5m/15m LGB/XGB Probe

Hypothesis: SOXL/SOXX minute-derived 5min and 15min qlib providers may contain same-session next-bar volatility signal. This notebook runs the qlib-backed diagnostic card and does not promote the signal unless stability gates are proven.

In [1]:
from pathlib import Path
import json
import sys
import pandas as pd
from IPython.display import display, Markdown

ROOT = Path.cwd().resolve()
if not (ROOT / "src").exists():
    for candidate in [Path.cwd().resolve(), *Path.cwd().resolve().parents]:
        if (candidate / "src").exists() and (candidate / "research").exists():
            ROOT = candidate
            break
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.workflow.intraday_bar_model import IntradayBarModelSpec, run_intraday_bar_model_card

EXPERIMENT = "agentic_alpha_intraday_5m15m_lgb_xgb_v1"
CARD = ROOT / "research" / EXPERIMENT
SPEC = IntradayBarModelSpec(
    experiment=EXPERIMENT,
    output_dir=CARD,
    recorder_uri=CARD / "qlib_recorder",
    provider_uris={
        "5min": ROOT / "data/qlib/soxl_intraday_5min",
        "15min": ROOT / "data/qlib/soxl_intraday_15min",
    },
)
result = run_intraday_bar_model_card(SPEC)
summary = result.summary
summary["recorder_id"], summary["selected_model"]

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[54760:MainThread](2026-07-04 11:39:41,458) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[54760:MainThread](2026-07-04 11:39:41,459) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[54760:MainThread](2026-07-04 11:39:41,460) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

[54760:MainThread](2026-07-04 11:39:41,493) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[54760:MainThread](2026-07-04 11:39:41,494) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[54760:MainThread](2026-07-04 11:39:41,494) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

[54760:MainThread](2026-07-04 11:39:41,693) INFO - qlib.timer - [log.py:127] - Time cost: 0.118s | Loading data Done

[54760:MainThread](2026-07-04 11:39:41,694) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[54760:MainThread](2026-07-04 11:39:41,694) INFO - qlib.timer - [log.py:127] - Time cost: 0.119s | Init data Done

[54760:MainThread](2026-07-04 11:39:41,700) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[54760:MainThread](2026-07-04 11:39:41,700) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[54760:MainThread](2026-07-04 11:39:41,701) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

[54760:MainThread](2026-07-04 11:39:46,961) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[54760:MainThread](2026-07-04 11:39:46,962) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[54760:MainThread](2026-07-04 11:39:46,963) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_5min')}

[54760:MainThread](2026-07-04 11:39:47,187) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[54760:MainThread](2026-07-04 11:39:47,188) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[54760:MainThread](2026-07-04 11:39:47,189) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_5min')}

[54760:MainThread](2026-07-04 11:39:47,688) INFO - qlib.timer - [log.py:127] - Time cost: 0.338s | Loading data Done

[54760:MainThread](2026-07-04 11:39:47,689) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[54760:MainThread](2026-07-04 11:39:47,689) INFO - qlib.timer - [log.py:127] - Time cost: 0.339s | Init data Done

[54760:MainThread](2026-07-04 11:39:47,703) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[54760:MainThread](2026-07-04 11:39:47,703) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[54760:MainThread](2026-07-04 11:39:47,704) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_5min')}

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[54760:MainThread](2026-07-04 11:39:57,490) WARNING - qlib.workflow - [expm.py:231] - No valid experiment found. Create a new experiment with name agentic_alpha_intraday_5m15m_lgb_xgb_v1.

[54760:MainThread](2026-07-04 11:39:57,491) INFO - qlib.workflow - [exp.py:258] - Experiment 213843614429864973 starts running ...

[54760:MainThread](2026-07-04 11:39:57,555) INFO - qlib.workflow - [recorder.py:345] - Recorder 6f57d668e1f44b388a6c45cbb2f3637c starts running under Experiment 213843614429864973 ...

[54760:MainThread](2026-07-04 11:39:57,640) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | waiting `async_log` Done

('6f57d668e1f44b388a6c45cbb2f3637c',
 {'freq': '15min',
  'model': 'xgb',
  'threshold': 0.5242983669042587,
  'selection_segment': 'valid',
  'selection_metric': 'valid_net_return_pct + 5*valid_daily_sharpe + 0.5*valid_max_drawdown_pct',
  'valid_net_return_pct': 42.24726104736328,
  'valid_max_drawdown_pct': -15.537637710571289,
  'test_net_return_pct': 20.412731170654297,
  'test_max_drawdown_pct': -7.314026355743408,
  'test_ic': 0.0032409104141955867})

In [2]:
model_selection = pd.read_csv(CARD / summary["sidecars"]["model_selection"])
display(model_selection[[
    "freq", "model", "threshold", "valid_ic", "test_ic",
    "valid_net_return_pct", "valid_max_drawdown_pct",
    "test_net_return_pct", "test_max_drawdown_pct", "test_daily_sharpe", "test_trades"
]])

,freq,model,threshold,valid_ic,test_ic,valid_net_return_pct,valid_max_drawdown_pct,test_net_return_pct,test_max_drawdown_pct,test_daily_sharpe,test_trades
0,15min,lgb,0.551622,0.019515,-0.001092,40.663456,-11.509633,20.199024,-14.531576,2.460817,198
1,15min,lgb_xgb_consensus,0.528072,0.019726,0.001418,40.296589,-10.809719,25.840176,-12.824178,2.823233,215
2,15min,xgb,0.524298,0.018771,0.003241,42.247261,-15.537638,20.412731,-7.314026,2.823481,135
3,5min,lgb,0.550000,0.002012,0.034958,-10.957259,-18.594582,29.179621,-3.477401,5.318316,81
4,5min,lgb_xgb_consensus,0.500000,-0.000259,0.033603,-41.025669,-48.547585,29.340231,-17.409933,2.277484,405
5,5min,xgb,0.488541,-0.002141,0.028130,-46.328419,-50.144089,26.406490,-22.599691,1.591764,661

In [3]:
display(pd.read_csv(CARD / summary["sidecars"]["cost_sensitivity"]))
display(pd.read_csv(CARD / summary["sidecars"]["monthly_stability"]))
display(pd.read_csv(CARD / summary["sidecars"]["backtest_walk_forward_metrics"]))

,freq,model,threshold_selected_at_cost_bps,threshold,cost_bps,valid_trades,valid_trade_days,valid_coverage_days,valid_net_return_pct,valid_gross_return_pct,...,test_trades,test_trade_days,test_coverage_days,test_net_return_pct,test_gross_return_pct,test_max_drawdown_pct,test_daily_sharpe,test_win_rate,test_avg_trade_bps,test_worst_trade_bps
0,15min,lgb_xgb_consensus,5.0,0.528072,0.0,322,159,250,64.771988,64.771988,...,215,100,125,40.102661,40.102661,-9.079414,4.074333,0.539535,16.235638,-345.850586
1,15min,lgb_xgb_consensus,5.0,0.528072,5.0,322,159,250,40.296589,64.771988,...,215,100,125,25.840176,40.102661,-12.824178,2.823233,0.506977,11.235638,-350.850586
2,15min,lgb_xgb_consensus,5.0,0.528072,10.0,322,159,250,19.445789,64.771988,...,215,100,125,13.022900,40.102661,-16.416491,1.556854,0.483721,6.235635,-355.850555
3,15min,lgb_xgb_consensus,5.0,0.528072,20.0,322,159,250,-13.438177,64.771988,...,215,100,125,-8.841187,40.102661,-24.410360,-0.990113,0.423256,-3.764366,-365.850586
4,5min,lgb_xgb_consensus,5.0,0.500000,0.0,518,179,250,-23.574478,-23.574478,...,405,96,125,58.345055,58.345055,-15.699429,3.991354,0.580247,11.973689,-487.213135
5,5min,lgb_xgb_consensus,5.0,0.500000,5.0,518,179,250,-41.025669,-23.574478,...,405,96,125,29.340231,58.345055,-17.409933,2.277484,0.558025,6.973688,-492.213135
6,5min,lgb_xgb_consensus,5.0,0.500000,10.0,518,179,250,-54.498447,-23.574478,...,405,96,125,5.636156,58.345055,-19.796001,0.606778,0.530864,1.973687,-497.213104
7,5min,lgb_xgb_consensus,5.0,0.500000,20.0,518,179,250,-72.923065,-23.574478,...,405,96,125,-29.554098,58.345055,-32.081898,-2.476786,0.474074,-8.026314,-507.213135

,freq,month,trades,trade_days,net_return_pct,avg_trade_bps,win_rate
0,15min,2026-01,29,15,3.458488,11.949382,0.482759
1,15min,2026-02,29,16,1.053524,4.085065,0.448276
2,15min,2026-03,42,20,-2.660602,-6.184119,0.476190
3,15min,2026-04,30,13,-3.983355,-13.246325,0.433333
4,15min,2026-05,33,17,5.248225,15.867369,0.515152
5,15min,2026-06,50,17,16.755449,32.143303,0.600000
6,15min,2026-07,2,2,4.803288,238.498672,1.000000
7,5min,2026-01,20,10,2.182579,11.046971,0.650000
8,5min,2026-02,54,15,4.917073,9.185904,0.500000
9,5min,2026-03,54,18,-1.249665,-2.028366,0.518519
10,5min,2026-04,35,14,12.384283,33.801189,0.628571
11,5min,2026-05,68,18,20.030140,27.164957,0.691176
12,5min,2026-06,150,19,-1.224089,0.223576,0.520000
13,5min,2026-07,24,2,-8.309311,-35.287376,0.458333

,freq,fold,train_start,train_end,valid_start,valid_end,test_start,test_end,purge_bars,threshold,valid_net_return_pct,valid_max_drawdown_pct,test_net_return_pct,test_max_drawdown_pct,test_daily_sharpe,test_trades,test_trade_days,test_ic,prediction_rows
0,15min,wf_2024,2019-01-02,2022-12-30,2023-01-03,2023-12-29,2024-01-02,2024-12-31,1,0.550000,-17.056978,-22.952938,-28.057020,-29.133684,-3.417053,213,133,-0.030952,19482
1,15min,wf_2025,2019-01-02,2023-12-29,2024-01-02,2024-12-31,2025-01-02,2025-12-31,1,0.550000,-17.345547,-19.008160,33.130180,-14.564217,1.378477,154,92,0.027778,22696
2,15min,wf_2026,2019-01-02,2024-12-31,2025-01-02,2025-12-31,2026-01-02,2026-07-02,1,0.528072,40.296589,-10.809719,25.840176,-12.824178,2.823233,215,100,0.001418,24321
3,5min,wf_2024,2019-01-02,2022-12-30,2023-01-03,2023-12-29,2024-01-02,2024-12-31,1,0.500000,-25.577282,-33.151161,-29.688591,-32.701485,-2.105477,667,218,0.010165,97714
4,5min,wf_2025,2019-01-02,2023-12-29,2024-01-02,2024-12-31,2025-01-02,2025-12-31,1,0.500000,15.697824,-12.322866,-58.938694,-58.947002,-3.506310,574,191,0.000898,113856
5,5min,wf_2026,2019-01-02,2024-12-31,2025-01-02,2025-12-31,2026-01-02,2026-07-02,1,0.500000,-41.025669,-48.547585,29.340231,-17.409933,2.277484,405,96,0.033603,121981

In [4]:
assert "qlib.data.D.features" in summary["qlib_native_api"]
assert "DatasetH" in summary["qlib_native_api"]
assert "qlib.workflow.R.start" in summary["qlib_native_api"]
assert summary["artifact_policy"]["policy"] == "slim_card_recorder_first"
assert Path(summary["recorder_local_dir"]).exists()
assert (Path(summary["recorder_local_dir"]) / "artifacts" / "pred.pkl").exists()
summary["promotion_decision"]

'not_promoted_intraday_stability_not_proven'

## 中文结论

以下单元读取本次执行同步写出的 `conclusion.md`，作为 notebook 的最终中文结论。

In [5]:
display(Markdown((CARD / "conclusion.md").read_text(encoding="utf-8")))

# 中文结论

- 做了什么：把 SOXL/SOXX 1m 缓存正式重采样成 qlib 5min/15min provider，并通过 qlib.init、D.features、DatasetH/DataHandlerLP、R.start、LGBMClassifier 和 XGBClassifier 重跑下一根 bar open-to-close 盘中模型。
- 核心指标：validation 选择 15min / xgb，valid return_pct=42.2473、test return_pct=20.4127、test max_drawdown_pct=-7.3140、test IC=0.0032。
- regime/window 差异：5min 与 15min 都使用 purged split（purge_bars=1）和 2024/2025/2026 walk-forward；月度稳定性与成本敏感度见 monthly_stability.csv、cost_sensitivity.csv 和 backtest_walk_forward_metrics.csv。
- 是否晋升：不晋升；15min 有弱正信号但月度集中、IC 很小，5min validation 不稳定，尚不能证明盘中实盘能力。
- 风险：执行假设是 bar 收盘出信号、下一根 bar 开盘进、下一根 bar 收盘出，未证明真实 spread、排队成交、PDT、滑点扩张和实时延迟。
- 下一步：若继续推进，应接入实时分钟 replay 和成交模拟，扩大成本压力，并把 15min xgb/consensus 作为候选而非生产信号。
- qlib recorder：6f57d668e1f44b388a6c45cbb2f3637c