# Homologous 3x / 1x / cash generalization

`SOXL/SOXX/cash` 与 `TQQQ/QQQ/cash` 分别独立训练；不迁移仓位时序，也不使用 outer 选择模型。

In [1]:
from pathlib import Path
import sys
import qlib
from qlib.data import D
from qlib.data.dataset import DatasetH
from qlib.workflow import R
repo_root = Path.cwd().parents[1]
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))
qlib.init(provider_uri=str(repo_root / 'data/qlib/tqqq'), region='us', kernels=1, skip_if_reg=False)
calendar = D.calendar(start_time='2011-01-03', end_time='2026-07-24', freq='day')
from src.workflow.homologous_3x_1x_cash_generalization import run_homologous_3x_1x_cash_generalization_card
summary = run_homologous_3x_1x_cash_generalization_card(root=repo_root)
summary['generalization_decision']

[20540:MainThread](2026-07-25 12:29:23,603) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[20540:MainThread](2026-07-25 12:29:23,604) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[20540:MainThread](2026-07-25 12:29:23,605) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/tqqq')}

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[20540:MainThread](2026-07-25 12:29:24,980) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[20540:MainThread](2026-07-25 12:29:24,981) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[20540:MainThread](2026-07-25 12:29:24,981) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[20540:MainThread](2026-07-25 12:29:24,985) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[20540:MainThread](2026-07-25 12:29:24,986) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[20540:MainThread](2026-07-25 12:29:24,986) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[20540:MainThread](2026-07-25 12:29:25,005) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[20540:MainThread](2026-07-25 12:29:25,006) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[20540:MainThread](2026-07-25 12:29:25,007) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/tqqq')}

[20540:MainThread](2026-07-25 12:29:25,011) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[20540:MainThread](2026-07-25 12:29:25,011) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[20540:MainThread](2026-07-25 12:29:25,012) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/tqqq')}

[20540:MainThread](2026-07-25 12:29:25,029) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[20540:MainThread](2026-07-25 12:29:25,030) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[20540:MainThread](2026-07-25 12:29:25,030) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/upro')}

[20540:MainThread](2026-07-25 12:29:25,034) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[20540:MainThread](2026-07-25 12:29:25,035) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[20540:MainThread](2026-07-25 12:29:25,035) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/upro')}

[20540:MainThread](2026-07-25 12:29:25,054) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[20540:MainThread](2026-07-25 12:29:25,054) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[20540:MainThread](2026-07-25 12:29:25,055) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/spxl')}

[20540:MainThread](2026-07-25 12:29:25,059) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[20540:MainThread](2026-07-25 12:29:25,059) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[20540:MainThread](2026-07-25 12:29:25,060) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/spxl')}

[20540:MainThread](2026-07-25 12:29:25,077) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[20540:MainThread](2026-07-25 12:29:25,078) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[20540:MainThread](2026-07-25 12:29:25,078) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/tecl')}

[20540:MainThread](2026-07-25 12:29:25,081) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[20540:MainThread](2026-07-25 12:29:25,082) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[20540:MainThread](2026-07-25 12:29:25,083) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/tecl')}

[20540:MainThread](2026-07-25 12:29:35,228) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[20540:MainThread](2026-07-25 12:29:35,229) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[20540:MainThread](2026-07-25 12:29:35,229) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[20540:MainThread](2026-07-25 12:29:38,798) INFO - qlib.workflow - [exp.py:258] - Experiment 360354811803247780 starts running ...

[20540:MainThread](2026-07-25 12:29:38,875) INFO - qlib.workflow - [recorder.py:345] - Recorder f2f5e90be7c94c31bf61a014c866a97e starts running under Experiment 360354811803247780 ...

[20540:MainThread](2026-07-25 12:29:38,996) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

'not_validated_on_tqqq_homologous_pair'

In [2]:
import pandas as pd
card = Path.cwd()
pd.read_csv(card / 'backtest_benchmark_comparison.csv').query("segment == 'outer_diagnostic' and cost_bps == 10")

,pair,leveraged_symbol,underlying_symbol,segment,strategy,cost_bps,selection_uses_outer_test,return_pct,cagr_pct,annualized_vol_pct,...,terminal_wealth,terminal_wealth_ratio_vs_soxx,soxx_terminal_wealth,soxx_return_pct,avg_cash_weight_pct,min_cash_weight_pct,max_cash_weight_pct,zero_cash_days,avg_soxl_weight_pct,avg_soxx_weight_pct
8,SOXL_SOXX_CASH,SOXL,SOXX,outer_diagnostic,model,10,False,302.022386,48.282902,37.688231,...,4.020224,0.865311,4.645990,364.598965,21.070403,2.050025,80.219728,0,12.975679,65.953918
9,SOXL_SOXX_CASH,SOXL,SOXX,outer_diagnostic,matched_static,10,False,366.501283,54.661797,38.379639,...,4.665013,1.004095,4.645990,364.598965,21.070403,21.070403,21.070403,0,12.975679,65.953918
10,SOXL_SOXX_CASH,SOXL,SOXX,outer_diagnostic,underlying_buyhold,10,False,364.598965,54.482959,36.688595,...,4.645990,1.000000,4.645990,364.598965,0.000000,0.000000,0.000000,890,0.000000,100.000000
11,SOXL_SOXX_CASH,SOXL,SOXX,outer_diagnostic,leveraged_buyhold,10,False,1431.350312,116.545518,109.444368,...,15.313503,3.296069,4.645990,364.598965,0.000000,0.000000,0.000000,890,100.000000,0.000000
24,TQQQ_QQQ_CASH,TQQQ,QQQ,outer_diagnostic,model,10,False,165.261505,31.814046,22.103224,...,2.652615,1.006293,2.636027,163.602651,14.212971,1.508445,62.351543,0,13.443484,72.343546
25,TQQQ_QQQ_CASH,TQQQ,QQQ,outer_diagnostic,matched_static,10,False,179.404723,33.767105,22.897220,...,2.794047,1.059947,2.636027,163.602651,14.212971,14.212971,14.212971,0,13.443484,72.343546
26,TQQQ_QQQ_CASH,TQQQ,QQQ,outer_diagnostic,underlying_buyhold,10,False,163.602651,31.580118,20.324138,...,2.636027,1.000000,2.636027,163.602651,0.000000,0.000000,0.000000,890,0.000000,100.000000
27,TQQQ_QQQ_CASH,TQQQ,QQQ,outer_diagnostic,leveraged_buyhold,10,False,689.109995,79.482028,60.973593,...,7.891100,2.993559,2.636027,163.602651,0.000000,0.000000,0.000000,890,100.000000,0.000000

In [3]:
pd.read_csv(card / 'annual_metrics.csv').query("segment == 'outer_diagnostic' and strategy == 'model' and cost_bps == 10")

,pair,leveraged_symbol,underlying_symbol,segment,strategy,cost_bps,selection_uses_outer_test,fold_year,return_pct,cagr_pct,...,terminal_wealth,terminal_wealth_ratio_vs_soxx,soxx_terminal_wealth,soxx_return_pct,avg_cash_weight_pct,min_cash_weight_pct,max_cash_weight_pct,zero_cash_days,avg_soxl_weight_pct,avg_soxx_weight_pct
56,SOXL_SOXX_CASH,SOXL,SOXX,outer_diagnostic,model,10,False,2023,62.265298,62.894888,...,1.622653,1.045529,1.551992,55.199245,16.539666,2.314337,52.468151,0,13.445812,70.014522
57,SOXL_SOXX_CASH,SOXL,SOXX,outer_diagnostic,model,10,False,2024,15.660104,15.660104,...,1.156601,0.963667,1.200209,20.020878,21.854360,2.050025,56.650823,0,13.521541,64.624098
58,SOXL_SOXX_CASH,SOXL,SOXX,outer_diagnostic,model,10,False,2025,27.146721,27.391252,...,1.271467,0.865288,1.469415,46.941506,21.916363,2.475953,72.125369,0,12.886140,65.197497
59,SOXL_SOXX_CASH,SOXL,SOXX,outer_diagnostic,model,10,False,2026,68.475147,159.223369,...,1.684751,0.992541,1.697412,69.741231,26.314151,2.490647,80.219728,0,11.289403,62.396446
144,TQQQ_QQQ_CASH,TQQQ,QQQ,outer_diagnostic,model,10,False,2023,54.424363,54.962119,...,1.544244,1.023543,1.508724,50.872391,12.553429,2.792896,45.754620,0,13.201517,74.245054
145,TQQQ_QQQ_CASH,TQQQ,QQQ,outer_diagnostic,model,10,False,2024,32.808000,32.808000,...,1.328080,1.028540,1.291228,29.122774,12.991572,2.433873,46.756610,0,13.175857,73.832572
146,TQQQ_QQQ_CASH,TQQQ,QQQ,outer_diagnostic,model,10,False,2025,16.316133,16.456860,...,1.163161,0.959271,1.212547,21.254720,16.358077,2.616174,62.351543,0,13.880028,69.761895
147,TQQQ_QQQ_CASH,TQQQ,QQQ,outer_diagnostic,model,10,False,2026,11.197293,21.386963,...,1.111973,0.996450,1.115934,11.593398,15.563704,1.508445,51.851004,0,13.579700,70.856595

In [4]:
pd.read_csv(card / 'objective_gate_audit.csv')

,pair,gate,required,passed,outer_ratio_10bps,outer_ratio_25bps,model_wealth_ratio_vs_matched_static,model_calmar,matched_static_calmar,outer_max_drawdown_pct,outer_worst_day_pct,outer_cvar5_pct,outer_worst_rolling_5d_pct,outer_avg_cash_weight_pct,positive_relative_years,risk_passing_years,selection_uses_outer_test
0,SOXL_SOXX_CASH,outer_return_10bps,True,False,0.865311,0.757117,0.861782,0.918455,1.192830,-52.569715,-11.579230,-5.364090,-21.835352,21.070403,1,2,False
1,SOXL_SOXX_CASH,outer_return_25bps,True,False,0.865311,0.757117,0.861782,0.918455,1.192830,-52.569715,-11.579230,-5.364090,-21.835352,21.070403,1,2,False
2,SOXL_SOXX_CASH,dynamic_wealth_vs_matched_static,True,False,0.865311,0.757117,0.861782,0.918455,1.192830,-52.569715,-11.579230,-5.364090,-21.835352,21.070403,1,2,False
3,SOXL_SOXX_CASH,dynamic_calmar_vs_matched_static,True,False,0.865311,0.757117,0.861782,0.918455,1.192830,-52.569715,-11.579230,-5.364090,-21.835352,21.070403,1,2,False
4,SOXL_SOXX_CASH,maxdd,True,False,0.865311,0.757117,0.861782,0.918455,1.192830,-52.569715,-11.579230,-5.364090,-21.835352,21.070403,1,2,False
5,SOXL_SOXX_CASH,worst_day,True,True,0.865311,0.757117,0.861782,0.918455,1.192830,-52.569715,-11.579230,-5.364090,-21.835352,21.070403,1,2,False
6,SOXL_SOXX_CASH,cvar5,True,True,0.865311,0.757117,0.861782,0.918455,1.192830,-52.569715,-11.579230,-5.364090,-21.835352,21.070403,1,2,False
7,SOXL_SOXX_CASH,worst_rolling_5d,True,False,0.865311,0.757117,0.861782,0.918455,1.192830,-52.569715,-11.579230,-5.364090,-21.835352,21.070403,1,2,False
8,SOXL_SOXX_CASH,average_cash,True,True,0.865311,0.757117,0.861782,0.918455,1.192830,-52.569715,-11.579230,-5.364090,-21.835352,21.070403,1,2,False
9,SOXL_SOXX_CASH,annual_relative_stability,True,False,0.865311,0.757117,0.861782,0.918455,1.192830,-52.569715,-11.579230,-5.364090,-21.835352,21.070403,1,2,False
10,SOXL_SOXX_CASH,annual_risk_stability,True,False,0.865311,0.757117,0.861782,0.918455,1.192830,-52.569715,-11.579230,-5.364090,-21.835352,21.070403,1,2,False
11,TQQQ_QQQ_CASH,outer_return_10bps,True,True,1.006293,0.932503,0.949381,1.197025,1.247261,-26.577604,-6.133077,-3.120923,-11.507689,14.212971,2,4,False
12,TQQQ_QQQ_CASH,outer_return_25bps,True,False,1.006293,0.932503,0.949381,1.197025,1.247261,-26.577604,-6.133077,-3.120923,-11.507689,14.212971,2,4,False
13,TQQQ_QQQ_CASH,dynamic_wealth_vs_matched_static,True,False,1.006293,0.932503,0.949381,1.197025,1.247261,-26.577604,-6.133077,-3.120923,-11.507689,14.212971,2,4,False
14,TQQQ_QQQ_CASH,dynamic_calmar_vs_matched_static,True,False,1.006293,0.932503,0.949381,1.197025,1.247261,-26.577604,-6.133077,-3.120923,-11.507689,14.212971,2,4,False
15,TQQQ_QQQ_CASH,maxdd,True,True,1.006293,0.932503,0.949381,1.197025,1.247261,-26.577604,-6.133077,-3.120923,-11.507689,14.212971,2,4,False
16,TQQQ_QQQ_CASH,worst_day,True,True,1.006293,0.932503,0.949381,1.197025,1.247261,-26.577604,-6.133077,-3.120923,-11.507689,14.212971,2,4,False
17,TQQQ_QQQ_CASH,cvar5,True,True,1.006293,0.932503,0.949381,1.197025,1.247261,-26.577604,-6.133077,-3.120923,-11.507689,14.212971,2,4,False
18,TQQQ_QQQ_CASH,worst_rolling_5d,True,True,1.006293,0.932503,0.949381,1.197025,1.247261,-26.577604,-6.133077,-3.120923,-11.507689,14.212971,2,4,False
19,TQQQ_QQQ_CASH,average_cash,True,False,1.006293,0.932503,0.949381,1.197025,1.247261,-26.577604,-6.133077,-3.120923,-11.507689,14.212971,2,4,False
20,TQQQ_QQQ_CASH,annual_relative_stability,True,False,1.006293,0.932503,0.949381,1.197025,1.247261,-26.577604,-6.133077,-3.120923,-11.507689,14.212971,2,4,False
21,TQQQ_QQQ_CASH,annual_risk_stability,True,True,1.006293,0.932503,0.949381,1.197025,1.247261,-26.577604,-6.133077,-3.120923,-11.507689,14.212971,2,4,False

## 中文结论

# 结论

- 已按同构口径重做：两个组合使用完全相同的过去式通用特征、网络结构、目标、约束和训练截止日，但分别只用自己的历史训练。没有把 SOXL 仓位套到 TQQQ。
- SOXL/SOXX/cash outer 10bp：收益 302.02%，SOXX 364.60%，财富比 0.8653，MaxDD -52.57%，平均现金 21.07%。
  同平均仓位静态组合收益 366.50%，动态/静态财富比 0.8618。
- TQQQ/QQQ/cash outer 10bp：收益 165.26%，QQQ 163.60%，财富比 1.0063，MaxDD -26.58%，平均现金 14.21%。
  同平均仓位静态组合收益 179.40%，动态/静态财富比 0.9494。
- 这不是只在 outer 才出现的过拟合：开发期 walk-forward 中，SOXL 通用模型/同仓位静态财富比为 0.9550，TQQQ 为 0.8856；动态择时在开发期已经没有增益。
- 同构泛化判断：`not_validated_on_tqqq_homologous_pair`；失败门：SOXL_SOXX_CASH:outer_return_10bps, SOXL_SOXX_CASH:outer_return_25bps, SOXL_SOXX_CASH:dynamic_wealth_vs_matched_static, SOXL_SOXX_CASH:dynamic_calmar_vs_matched_static, SOXL_SOXX_CASH:maxdd, SOXL_SOXX_CASH:worst_rolling_5d, SOXL_SOXX_CASH:annual_relative_stability, SOXL_SOXX_CASH:annual_risk_stability, TQQQ_QQQ_CASH:outer_return_25bps, TQQQ_QQQ_CASH:dynamic_wealth_vs_matched_static, TQQQ_QQQ_CASH:dynamic_calmar_vs_matched_static, TQQQ_QQQ_CASH:average_cash, TQQQ_QQQ_CASH:annual_relative_stability。
- 这张卡验证的是日频直接仓位核心的可迁移性；SOXL 生产模型额外使用半导体专属特征和盘中恢复模块，二者不能混为同一个模型。
- Outer 2023-2026 全程只报告，未参与模型或参数选择。
- Qlib recorder：`cc81e0c07fae405d877326a4c53ef4a4`。