# Stage1 cash-funded risk-budget overlay v1

假设：冻结现有 Stage1 后，在 SOXL 已触及 30% 但仍保留现金的日期，使用 prior-close 的非过热趋势条件，从现金增加小规模 SOXL/SOXX 风险，可以提高开发期收益，同时保留现金下限和尾部风险门。2018–2022 用于选择；2023–2026 只作冻结诊断。

In [1]:
from pathlib import Path
import sys

root = Path.cwd().resolve()
while root != root.parent and not (root / "SPEC.md").exists():
    root = root.parent
if str(root) not in sys.path:
    sys.path.insert(0, str(root))
root

PosixPath('/Users/rziiiii/dev/workspace')

In [2]:
import qlib
from qlib.data import D
from qlib.workflow import R

provider_uri = root / "data" / "qlib" / "soxl_soxx_soxs"
qlib.init(provider_uri=str(provider_uri), region="us")
calendar = D.calendar(start_time="2016-01-01", end_time="2026-12-31", freq="day")
{
    "provider_uri": str(provider_uri),
    "calendar_start": str(calendar[0]),
    "calendar_end": str(calendar[-1]),
    "calendar_sessions": len(calendar),
    "recorder_api": R.__class__.__name__,
}

[69794:MainThread](2026-07-27 20:51:00,391) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[69794:MainThread](2026-07-27 20:51:00,392) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[69794:MainThread](2026-07-27 20:51:00,392) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

{'provider_uri': '/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs',
 'calendar_start': '2016-01-04 00:00:00',
 'calendar_end': '2026-07-24 00:00:00',
 'calendar_sessions': 2654,
 'recorder_api': 'RecorderWrapper'}

In [3]:
from src.workflow.stage1_cash_funded_risk_budget_overlay import (
    run_stage1_cash_funded_risk_budget_overlay_card,
)

result = run_stage1_cash_funded_risk_budget_overlay_card(root=root)
result

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[69794:MainThread](2026-07-27 20:51:01,738) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[69794:MainThread](2026-07-27 20:51:01,739) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[69794:MainThread](2026-07-27 20:51:01,739) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[69794:MainThread](2026-07-27 20:51:01,763) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[69794:MainThread](2026-07-27 20:51:01,764) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[69794:MainThread](2026-07-27 20:51:01,764) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[69794:MainThread](2026-07-27 20:51:02,028) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[69794:MainThread](2026-07-27 20:51:02,029) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[69794:MainThread](2026-07-27 20:51:02,030) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

[69794:MainThread](2026-07-27 20:51:02,142) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[69794:MainThread](2026-07-27 20:51:02,143) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[69794:MainThread](2026-07-27 20:51:02,143) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[69794:MainThread](2026-07-27 20:51:02,182) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[69794:MainThread](2026-07-27 20:51:02,183) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[69794:MainThread](2026-07-27 20:51:02,183) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

[69794:MainThread](2026-07-27 20:51:02,594) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[69794:MainThread](2026-07-27 20:51:02,595) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[69794:MainThread](2026-07-27 20:51:02,595) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[69794:MainThread](2026-07-27 20:51:02,614) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[69794:MainThread](2026-07-27 20:51:02,615) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[69794:MainThread](2026-07-27 20:51:02,615) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[69794:MainThread](2026-07-27 20:51:02,865) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[69794:MainThread](2026-07-27 20:51:02,866) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[69794:MainThread](2026-07-27 20:51:02,866) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

[69794:MainThread](2026-07-27 20:51:02,966) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[69794:MainThread](2026-07-27 20:51:02,966) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[69794:MainThread](2026-07-27 20:51:02,967) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[69794:MainThread](2026-07-27 20:51:03,166) WARNING - qlib.workflow - [expm.py:231] - No valid experiment found. Create a new experiment with name stage1_cash_funded_risk_budget_overlay_v1.

[69794:MainThread](2026-07-27 20:51:03,169) INFO - qlib.workflow - [exp.py:258] - Experiment 816784797224074224 starts running ...

[69794:MainThread](2026-07-27 20:51:03,240) INFO - qlib.workflow - [recorder.py:345] - Recorder 84eff9da51e943958ebe1193cc07b5dc starts running under Experiment 816784797224074224 ...

[69794:MainThread](2026-07-27 20:51:03,329) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

{'experiment': 'stage1_cash_funded_risk_budget_overlay_v1',
 'card_type': 'stage1_cash_funded_risk_budget_research_card',
 'primary_notebook': 'stage1_cash_funded_risk_budget_overlay_v1.ipynb',
 'system_of_record': 'qlib',
 'provider_uri': '/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs',
 'as_of': '2026-07-24',
 'market': 'US',
 'region': 'us',
 'source_stage1': {'experiment': 'intraday_on_policy_staged_validation_v1',
  'recorder_id': 'f6b09330175e41719886d58ee2d11bec',
  'training_end': '2022-12-30',
  'stage2_enabled': False,
  'frozen': True},
 'hypothesis': 'When Stage1 is already at its 30% SOXL ceiling but retains cash, a low-frequency non-overextended trend gate can fund a small SOXL or SOXX overlay from cash without replacing SOXX.',
 'method': {'capital_source': 'cash_only',
  'holding_period': 'next_open_to_following_open',
  'base_stage1': 'frozen',
  'development': '2018-2022 expanding prior-year thresholds',
  'outer': '2023-2026 thresholds frozen using data through 2022-12-30; outer excluded from selection',
  'gate': {'required': ['Stage1 SOXL weight at 30% cap',
    'SOXX 20d trend positive',
    'relative momentum not above prior cap-event q67'],
   'quality_variant_adds': ['SOXX volatility below prior cap-event q75',
    'chop risk below prior cap-event median']},
  'hard_constraints': {'minimum_cash_weight': 0.15,
   'source_maximum_soxl_weight': 0.3,
   'overlay_maximum_soxl_weight': 0.4,
   'long_only': True,
   'weights_sum_to_one': True}},
 'candidate_count': 6,
 'candidates': [{'name': 'soxl_005_pullback',
   'asset': 'SOXL',
   'maximum_overlay_weight': 0.05,
   'gate': 'trend_positive_momentum_not_overextended'},
  {'name': 'soxl_010_pullback',
   'asset': 'SOXL',
   'maximum_overlay_weight': 0.1,
   'gate': 'trend_positive_momentum_not_overextended'},
  {'name': 'soxl_005_quality',
   'asset': 'SOXL',
   'maximum_overlay_weight': 0.05,
   'gate': 'pullback_low_vol_low_chop'},
  {'name': 'soxl_010_quality',
   'asset': 'SOXL',
   'maximum_overlay_weight': 0.1,
   'gate': 'pullback_low_vol_low_chop'},
  {'name': 'soxx_005_quality',
   'asset': 'SOXX',
   'maximum_overlay_weight': 0.05,
   'gate': 'pullback_low_vol_low_chop'},
  {'name': 'soxx_010_quality',
   'asset': 'SOXX',
   'maximum_overlay_weight': 0.1,
   'gate': 'pullback_low_vol_low_chop'}],
 'selected_model': {'name': 'soxl_010_pullback',
  'asset': 'SOXL',
  'maximum_overlay_weight': 0.1,
  'gate': 'trend_positive_momentum_not_overextended',
  'selection_uses_outer_test': False},
 'development_baseline_metrics_10bps': {'variant': 'stage1_baseline',
  'segment': 'development_walk_forward',
  'selection_uses_outer_test': False,
  'asset': 'BASELINE',
  'gate': 'none',
  'maximum_overlay_weight': 0.0,
  'terminal_wealth': 3.2141247493902614,
  'return_pct': 221.41247493902614,
  'max_drawdown_pct': -27.488582391581495,
  'worst_day_pct': -7.058978409639723,
  'cvar5_pct': -4.30628318897681,
  'worst_rolling_5d_pct': -11.858940216431579,
  'stress_25bps_return_pct': 172.38654939071046,
  'stress_25bps_max_drawdown_pct': -30.509145252993587,
  'stress_25bps_worst_rolling_5d_pct': -12.180752211372958,
  'baseline_return_pct': 221.41247493902614,
  'baseline_max_drawdown_pct': -27.488582391581495,
  'baseline_worst_rolling_5d_pct': -11.858940216431579,
  'baseline_stress_25bps_return_pct': 172.38654939071046,
  'return_delta_pct_points': 0.0,
  'max_drawdown_delta_pct_points': 0.0,
  'worst_5d_delta_pct_points': 0.0,
  'action_count': 0,
  'positive_action_rate': None,
  'positive_relative_years': 0,
  'incremental_turnover': 0.0,
  'incremental_turnover_ratio': 0.0,
  'average_overlay_weight': 0.0,
  'return_gate_pass': None,
  'action_count_gate_pass': None,
  'positive_action_gate_pass': None,
  'positive_years_gate_pass': None,
  'max_drawdown_gate_pass': None,
  'worst_5d_gate_pass': None,
  'turnover_gate_pass': None,
  'neighbor_gate_pass': None,
  'neighbor_count': None,
  'neighbor_min_wealth_ratio': None,
  'neighbor_positive_count': None,
  'gate_pass_count': None,
  'all_development_gates_pass': None,
  'selected': False},
 'development_selected_metrics_10bps': {'variant': 'soxl_010_pullback',
  'segment': 'development_walk_forward',
  'selection_uses_outer_test': False,
  'asset': 'SOXL',
  'gate': 'trend_positive_momentum_not_overextended',
  'maximum_overlay_weight': 0.1,
  'terminal_wealth': 3.2440291055369284,
  'return_pct': 224.40291055369283,
  'max_drawdown_pct': -28.25894423634896,
  'worst_day_pct': -7.058978409639723,
  'cvar5_pct': -4.328434214999518,
  'worst_rolling_5d_pct': -11.858940216431579,
  'stress_25bps_return_pct': 174.63493509346773,
  'stress_25bps_max_drawdown_pct': -31.26863210682087,
  'stress_25bps_worst_rolling_5d_pct': -12.180752211372958,
  'baseline_return_pct': 221.41247493902614,
  'baseline_max_drawdown_pct': -27.488582391581495,
  'baseline_worst_rolling_5d_pct': -11.858940216431579,
  'baseline_stress_25bps_return_pct': 172.38654939071046,
  'return_delta_pct_points': 2.990435614666694,
  'max_drawdown_delta_pct_points': -0.7703618447674643,
  'worst_5d_delta_pct_points': 0.0,
  'action_count': 12,
  'positive_action_rate': 0.6666666666666666,
  'positive_relative_years': 3,
  'incremental_turnover': 0.6934441991189375,
  'incremental_turnover_ratio': 0.006278603258080345,
  'average_overlay_weight': 0.0005140685948568696,
  'return_gate_pass': False,
  'action_count_gate_pass': True,
  'positive_action_gate_pass': True,
  'positive_years_gate_pass': True,
  'max_drawdown_gate_pass': True,
  'worst_5d_gate_pass': True,
  'turnover_gate_pass': True,
  'neighbor_gate_pass': True,
  'neighbor_count': 2.0,
  'neighbor_min_wealth_ratio': 0.9927597974308111,
  'neighbor_positive_count': 2.0,
  'gate_pass_count': 7.0,
  'all_development_gates_pass': False,
  'selected': True},
 'outer_diagnostic_selected_metrics_10bps': {'variant': 'soxl_010_pullback',
  'segment': 'outer_reused_diagnostic',
  'selection_uses_outer_test': False,
  'asset': 'SOXL',
  'gate': 'trend_positive_momentum_not_overextended',
  'maximum_overlay_weight': 0.1,
  'terminal_wealth': 6.199957032866708,
  'return_pct': 519.9957032866708,
  'max_drawdown_pct': -28.105112234782304,
  'worst_day_pct': -9.383714522840133,
  'cvar5_pct': -5.261593661382325,
  'worst_rolling_5d_pct': -12.808590791233865,
  'stress_25bps_return_pct': 451.97129265104985,
  'stress_25bps_max_drawdown_pct': -29.088721515490047,
  'stress_25bps_worst_rolling_5d_pct': -12.904457729777906,
  'baseline_return_pct': 542.653315361169,
  'baseline_max_drawdown_pct': -28.105112234782304,
  'baseline_worst_rolling_5d_pct': -11.602809404682091,
  'baseline_stress_25bps_return_pct': 473.1961785652809,
  'return_delta_pct_points': -22.65761207449816,
  'max_drawdown_delta_pct_points': 0.0,
  'worst_5d_delta_pct_points': -1.2057813865517737,
  'action_count': 42,
  'positive_action_rate': 0.5238095238095238,
  'positive_relative_years': 0,
  'incremental_turnover': 1.2121572146808863,
  'incremental_turnover_ratio': 0.015863730763561006,
  'average_overlay_weight': 0.0022175723780272242,
  'return_gate_pass': False,
  'action_count_gate_pass': True,
  'positive_action_gate_pass': True,
  'positive_years_gate_pass': True,
  'max_drawdown_gate_pass': True,
  'worst_5d_gate_pass': True,
  'turnover_gate_pass': True,
  'neighbor_gate_pass': True,
  'neighbor_count': 2.0,
  'neighbor_min_wealth_ratio': 0.9927597974308111,
  'neighbor_positive_count': 2.0,
  'gate_pass_count': 7.0,
  'all_development_gates_pass': False,
  'selected': True},
 'selection_gates': {'return_gate_pass': False,
  'action_count_gate_pass': True,
  'positive_action_gate_pass': True,
  'positive_years_gate_pass': True,
  'max_drawdown_gate_pass': True,
  'worst_5d_gate_pass': True,
  'turnover_gate_pass': True,
  'neighbor_gate_pass': True,
  'all_development_gates_pass': False,
  'gate_pass_count': 7,
  'neighbor_count': 2,
  'neighbor_min_wealth_ratio': 0.9927597974308111,
  'neighbor_positive_count': 2,
  'required_return_delta_pct_points': 20.0,
  'clean_unseen_holdout_available': False,
  'outer_used_for_selection': False},
 'cash_audit': {'development_cap_rows': 69,
  'development_mean_cash_weight': 0.19764796930534045,
  'outer_cap_rows': 176,
  'outer_mean_cash_weight': 0.21082081608981798},
 'momentum_audit': {'development_spearman_vs_soxl_minus_soxx': -0.180306905370844,
  'development_low_third_mean_spread': 0.006994045078260868,
  'development_high_third_mean_spread': -0.0034924175400000003,
  'outer_spearman_vs_soxl_minus_soxx': 0.03156724631300903},
 'selection_uses_outer_test': False,
 'outer_status': 'reused_diagnostic_not_clean_unseen_holdout',
 'decision': 'not_promoted_development_uplift_or_coverage_gates_failed',
 'promotion': 'blocked',
 'dataset_audit': {'dataset_class': 'qlib.data.dataset.DatasetH',
  'handler_class': 'qlib.data.dataset.handler.DataHandlerLP',
  'loader_class': 'qlib.data.dataset.loader.StaticDataLoader',
  'features': ['soxx_trend20',
   'relative_momentum20',
   'soxx_vol20',
   'chop_breakdown_risk'],
  'labels': ['cash_to_soxl_return',
   'cash_to_soxx_return',
   'cap_bind',
   'cash_available'],
  'segments': {'all': ['2016-01-04', '2026-07-22'],
   'development': ['2018-01-01', '2022-12-31'],
   'outer': ['2023-01-01', '2026-12-31'],
   'train_outer': ['2016-01-01', '2022-12-30'],
   'train_2018': ['2016-01-01', '2017-12-31'],
   'test_2018': ['2018-01-01', '2018-12-31'],
   'train_2019': ['2016-01-01', '2018-12-31'],
   'test_2019': ['2019-01-01', '2019-12-31'],
   'train_2020': ['2016-01-01', '2019-12-31'],
   'test_2020': ['2020-01-01', '2020-12-31'],
   'train_2021': ['2016-01-01', '2020-12-31'],
   'test_2021': ['2021-01-01', '2021-12-31'],
   'train_2022': ['2016-01-01', '2021-12-31'],
   'test_2022': ['2022-01-01', '2022-12-31'],
   'test_2023': ['2023-01-01', '2023-12-31'],
   'test_2024': ['2024-01-01', '2024-12-31'],
   'test_2025': ['2025-01-01', '2025-12-31'],
   'test_2026': ['2026-01-01', '2026-12-31']},
  'segment_rows': {'all': 2652,
   'development': 1259,
   'outer': 890,
   'train_outer': 1762,
   'train_2018': 503,
   'test_2018': 251,
   'train_2019': 754,
   'test_2019': 252,
   'train_2020': 1006,
   'test_2020': 253,
   'train_2021': 1259,
   'test_2021': 252,
   'train_2022': 1511,
   'test_2022': 251,
   'test_2023': 250,
   'test_2024': 252,
   'test_2025': 250,
   'test_2026': 138}},
 'threshold_audit': {'outer_training_end': '2022-12-30',
  'outer_unique_threshold_rows': 1},
 'qlib_api': ['qlib.init',
  'qlib.data.D.features',
  'DatasetH',
  'DataHandlerLP',
  'qlib.workflow.R',
  'qlib.contrib.evaluate.risk_analysis'],
 'qlib_docs_reference': ['https://qlib.readthedocs.io/en/latest/component/strategy.html',
  'https://qlib.readthedocs.io/en/latest/component/recorder.html',
  'https://qlib.readthedocs.io/en/latest/component/model.html'],
 'recorder_id': '84eff9da51e943958ebe1193cc07b5dc',
 'recorder_uri': '/Users/rziiiii/dev/workspace/research/stage1_cash_funded_risk_budget_overlay_v1/qlib_recorder',
 'recorder_local_dir': '/Users/rziiiii/dev/workspace/research/stage1_cash_funded_risk_budget_overlay_v1/qlib_recorder/816784797224074224/84eff9da51e943958ebe1193cc07b5dc',
 'sidecars': {'selected_model': 'selected_model.json',
  'model_selection': 'model_selection.csv',
  'backtest_benchmark_comparison': 'backtest_benchmark_comparison.csv',
  'annual_metrics': 'annual_metrics.csv',
  'risk_analysis': 'risk_analysis.csv',
  'cash_availability': 'cash_availability.csv',
  'factor_diagnostics': 'factor_diagnostics.csv',
  'momentum_failure': 'momentum_failure.csv',
  'threshold_schedule': 'threshold_schedule.csv',
  'analysis_summary': 'analysis_summary.json',
  'failure_modes': 'failure_modes.md',
  'conclusion': 'conclusion.md',
  'workflow_config': 'workflow.yaml'},
 'artifact_policy': {'policy': 'slim_card_recorder_first',
  'workflow_config': 'workflow.yaml',
  'recorder_only_artifacts': ['artifacts/stage1_cash_funded_risk_budget_overlay_v1/portfolio_report.csv',
   'artifacts/stage1_cash_funded_risk_budget_overlay_v1/model_selection_full.csv',
   'artifacts/stage1_cash_funded_risk_budget_overlay_v1/factor_label_frame.csv']}}

In [4]:
import json
import pandas as pd
from IPython.display import display

card = root / "research" / "stage1_cash_funded_risk_budget_overlay_v1"
summary = json.loads((card / "summary.json").read_text())
headline = {
    "decision": summary["decision"],
    "promotion": summary["promotion"],
    "selected_candidate": summary["selected_model"]["name"],
    "development_delta_pct_points": summary["development_selected_metrics_10bps"]["return_delta_pct_points"],
    "outer_delta_pct_points": summary["outer_diagnostic_selected_metrics_10bps"]["return_delta_pct_points"],
    "development_mean_cash_at_cap": summary["cash_audit"]["development_mean_cash_weight"],
}
display(pd.DataFrame(headline, index=[0]).T.rename(columns={0: "value"}))
display(pd.read_csv(card / "model_selection.csv"))
display(pd.read_csv(card / "factor_diagnostics.csv"))
display(pd.read_csv(card / "momentum_failure.csv"))

                                                                          value
decision                      not_promoted_development_uplift_or_coverage_ga...
promotion                                                               blocked
selected_candidate                                            soxl_010_pullback
development_delta_pct_points                                           2.990436
outer_delta_pct_points                                               -22.657612
development_mean_cash_at_cap                                           0.197648

,variant,segment,selection_uses_outer_test,asset,gate,maximum_overlay_weight,terminal_wealth,return_pct,max_drawdown_pct,worst_day_pct,...,max_drawdown_gate_pass,worst_5d_gate_pass,turnover_gate_pass,neighbor_gate_pass,neighbor_count,neighbor_min_wealth_ratio,neighbor_positive_count,gate_pass_count,all_development_gates_pass,selected
0,stage1_baseline,development_walk_forward,False,BASELINE,none,0.00,3.214125,221.412475,-27.488582,-7.058978,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1,stage1_baseline,outer_reused_diagnostic,False,BASELINE,none,0.00,6.426533,542.653315,-28.105112,-9.383715,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
2,soxl_005_pullback,development_walk_forward,False,SOXL,trend_positive_momentum_not_overextended,0.05,3.220542,222.054168,-28.255498,-7.058978,...,True,True,True,True,2.0,1.000000,2.0,7.0,False,False
3,soxl_005_pullback,outer_reused_diagnostic,False,SOXL,trend_positive_momentum_not_overextended,0.05,6.296605,529.660470,-28.105112,-9.383715,...,True,True,True,True,2.0,1.000000,2.0,7.0,False,False
4,soxl_010_pullback,development_walk_forward,False,SOXL,trend_positive_momentum_not_overextended,0.10,3.244029,224.402911,-28.258944,-7.058978,...,True,True,True,True,2.0,0.992760,2.0,7.0,False,True
5,soxl_010_pullback,outer_reused_diagnostic,False,SOXL,trend_positive_momentum_not_overextended,0.10,6.199957,519.995703,-28.105112,-9.383715,...,True,True,True,True,2.0,0.992760,2.0,7.0,False,True
6,soxl_005_quality,development_walk_forward,False,SOXL,pullback_low_vol_low_chop,0.05,3.244714,224.471446,-27.488582,-7.058978,...,True,True,True,True,2.0,1.000000,2.0,5.0,False,False
7,soxl_005_quality,outer_reused_diagnostic,False,SOXL,pullback_low_vol_low_chop,0.05,6.369207,536.920663,-28.105112,-9.383715,...,True,True,True,True,2.0,1.000000,2.0,5.0,False,False
8,soxl_010_quality,development_walk_forward,False,SOXL,pullback_low_vol_low_chop,0.10,3.268535,226.853521,-27.488582,-7.058978,...,True,True,True,True,2.0,0.992712,2.0,5.0,False,False
9,soxl_010_quality,outer_reused_diagnostic,False,SOXL,pullback_low_vol_low_chop,0.10,6.369210,536.921025,-28.105112,-9.383715,...,True,True,True,True,2.0,0.992712,2.0,5.0,False,False
10,soxx_005_quality,development_walk_forward,False,SOXX,pullback_low_vol_low_chop,0.05,3.223460,222.345999,-27.488582,-7.058978,...,True,True,True,True,2.0,1.000000,2.0,5.0,False,False
11,soxx_005_quality,outer_reused_diagnostic,False,SOXX,pullback_low_vol_low_chop,0.05,6.405513,540.551334,-28.105112,-9.383715,...,True,True,True,True,2.0,1.000000,2.0,5.0,False,False
12,soxx_010_quality,development_walk_forward,False,SOXX,pullback_low_vol_low_chop,0.10,3.230887,223.088698,-27.488582,-7.058978,...,True,True,True,True,2.0,0.997701,2.0,5.0,False,False
13,soxx_010_quality,outer_reused_diagnostic,False,SOXX,pullback_low_vol_low_chop,0.10,6.405223,540.522309,-28.105112,-9.383715,...,True,True,True,True,2.0,0.997701,2.0,5.0,False,False

,segment,factor,cap_rows,cap_vs_noncap_mean_difference_z,spearman_vs_soxl_minus_soxx,low_third_rows,low_third_positive_spread_rate,low_third_mean_spread,high_third_rows,high_third_positive_spread_rate,high_third_mean_spread
0,development_walk_forward,soxx_trend20,69,0.116589,-0.146036,23,0.652174,0.007433,23,0.565217,-0.005618
1,development_walk_forward,relative_momentum20,69,0.166625,-0.180307,23,0.652174,0.006994,23,0.478261,-0.003492
2,development_walk_forward,soxx_vol20,69,-0.341831,-0.155170,23,0.739130,0.007984,23,0.521739,-0.001680
3,development_walk_forward,chop_breakdown_risk,69,0.562748,-0.033036,43,0.604651,0.001677,26,0.538462,-0.001853
4,outer_reused_diagnostic,soxx_trend20,176,0.735919,-0.056639,59,0.627119,0.008411,59,0.508475,-0.000984
5,outer_reused_diagnostic,relative_momentum20,176,0.955559,0.031567,59,0.593220,0.005228,59,0.576271,0.005996
6,outer_reused_diagnostic,soxx_vol20,176,-0.131844,0.044453,59,0.525424,0.002589,59,0.559322,0.006895
7,outer_reused_diagnostic,chop_breakdown_risk,176,-0.271909,0.172120,154,0.564935,0.002719,176,0.579545,0.006250

,year,segment,cap_rows,positive_momentum_rows,positive_momentum_success_rate,positive_momentum_mean_spread,positive_momentum_failure_count
0,2018,development_walk_forward,11,11,0.818182,0.006989,2
1,2019,development_walk_forward,46,29,0.448276,-0.008181,16
2,2020,development_walk_forward,3,0,NaN,NaN,0
3,2021,development_walk_forward,4,4,0.750000,0.025478,1
4,2022,development_walk_forward,5,2,0.000000,-0.039242,2
5,2023,outer_reused_diagnostic,14,9,0.444444,-0.000799,5
6,2024,outer_reused_diagnostic,5,5,0.800000,0.003539,1
7,2025,outer_reused_diagnostic,77,62,0.564516,0.003259,27
8,2026,outer_reused_diagnostic,80,73,0.616438,0.010287,28

## 中文结论

以下结论由同一轮 qlib Dataset、recorder 和 slim-card sidecars 生成。

In [5]:
from IPython.display import Markdown

display(Markdown((card / "conclusion.md").read_text()))

# 中文结论

- 做了什么：冻结现有 Stage1，仅在 SOXL 已触及 30%、SOXX 20 日趋势为正且相对动量未处于 prior cap-event 最高三分之一时，测试从现金增加 5%/10% SOXL 或 SOXX；现金不得低于 15%，SOXL 临时上限 40%。
- 封顶后现金：开发期 69 次封顶，平均现金=19.76%；outer 176 次封顶，平均现金=21.08%。
- 开发期选中诊断候选：`soxl_010_pullback`，10bp return=224.4029%，相对 Stage1 增量=2.9904 个百分点，动作=12，MaxDD=-28.2589%。
- 收益门：要求至少 20.00 个百分点，实际=2.9904，gate=False。
- 动量诊断：开发期封顶样本的相对动量与下一日 SOXL-SOXX spread Spearman=-0.1803；低三分位平均 spread=0.6994%，高三分位=-0.3492%，确认高动量存在过热/反转风险。
- outer 复用诊断：相对 Stage1 增量=-22.6576 个百分点；该窗口不参与选择，也不是 clean holdout。
- 决策：`not_promoted_development_uplift_or_coverage_gates_failed`；promotion=blocked，生产 Stage1 不变。
- 失败门：['return_gate_pass']。开发期的小幅改善不足以补偿样本稀疏和outer 方向反转。
- 下一步：把本卡保留为现金出资失败边界；只有新增 PIT 广度信息或预登记 clean-forward 后才重开，不用 outer 调阈值。
- qlib recorder：`84eff9da51e943958ebe1193cc07b5dc`。
- 不构成买卖建议。