# 可达基准的凸配置研究

先解决已查明的优化缺陷：上一轮无信号网络未达到可行的 SOXX 基准。用严格成熟的年度五日收益预测、显式可行基准和全局凸求解，检验信号在费用和风险约束下是否有增量。参数在市场拟合前固定于 selection_plan.json。历史窗口均已看过，不宣称新样本外。

In [1]:
from pathlib import Path
import os, sys, json, warnings
warnings.filterwarnings("once", message="Solution may be inaccurate.*", category=UserWarning)
ROOT = Path.cwd().resolve()
while not (ROOT / 'src').is_dir():
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))
os.environ['MLFLOW_ALLOW_FILE_STORE'] = 'true'
os.environ['MLFLOW_DISABLE_AGENT_HINT'] = '1'
import qlib
qlib.init(provider_uri=str(ROOT / 'data/qlib/stable_excess_integration_20261002'), region='us', kernels=1)
from src.workflow.convex_excess import run_experiment
summary = run_experiment(root=ROOT)
summary

[72192:MainThread](2026-10-02 20:00:04,145) INFO - qlib.Initialization - [config.py:452] - default_conf: client.
[72192:MainThread](2026-10-02 20:00:04,507) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.
[72192:MainThread](2026-10-02 20:00:04,508) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/convex-excess-20261002/data/qlib/stable_excess_integration_20261002')}
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
[72192:MainThread](2026-10-02 20:00:06,032) INFO - qlib.Initialization - [config.py:452] - default_conf: client.
[共1718行运行诊断；完整执行本保留于Recorder notebooks/raw_execution/]
/Users/rziiiii/dev/workspace-worktrees/convex-excess-20261002/src/workflow/convex_excess.py:253: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  gates=pd.concat([r['gates'].assign(variant=name) for name,r in evidence.items()],ignore_index=True)
[72192:MainThread](2026-10-02 20:00:53,703) INFO - qlib.Initialization - [config.py:452] - default_conf: client.
[72192:MainThread](2026-10-02 20:00:53,704) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.
[72192:MainThread](2026-10-02 20:00:53,705) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/convex-excess-20261002/data/qlib/stable_excess_integration_20261002')}
[72192:MainThread](2026-10-02 20:00:53,706) INFO - qlib.workflow - [exp.py:258] - Experiment 333485224999987774 starts running ...
[72192:MainThread](2026-10-02 20:00:53,801) INFO - qlib.workflow - [recorder.py:345] - Recorder 53dc5870bc8741d2a939938b0f6be9df starts running under Experiment 333485224999987774 ...
[72192:MainThread](2026-10-02 20:00:54,337) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Convex development repeat=1 prior_h5 cost=10 verified=True

Convex development repeat=1 prior_h5 cost=25 verified=True

Convex development repeat=1 ridge_h5 cost=10 verified=True

Convex development repeat=1 ridge_h5 cost=25 verified=True

Convex development repeat=1 robust_ridge_h5 cost=10 verified=True

Convex development repeat=1 robust_ridge_h5 cost=25 verified=True

Convex development repeat=2 prior_h5 cost=10 verified=True

Convex development repeat=2 prior_h5 cost=25 verified=True

Convex development repeat=2 ridge_h5 cost=10 verified=True

Convex development repeat=2 ridge_h5 cost=25 verified=True

Convex development repeat=2 robust_ridge_h5 cost=10 verified=True

Convex development repeat=2 robust_ridge_h5 cost=25 verified=True

Convex development repeat=3 prior_h5 cost=10 verified=True

Convex development repeat=3 prior_h5 cost=25 verified=True

Convex development repeat=3 ridge_h5 cost=10 verified=True

Convex development repeat=3 ridge_h5 cost=25 verified=True

Convex development repeat=3 robust_ridge_h5 cost=10 verified=True

Convex development repeat=3 robust_ridge_h5 cost=25 verified=True

Convex development sealed: {'variant': 'robust_ridge_h5', 'historical_qualification_pass': False, 'passed_gates': 10, 'worst_annualized_lower_bound': -0.06800690503604515, 'worst_relative_wealth': 0.8968674994575024, 'positive_years_10bps': 3}

Convex diagnostic repeat=1 annual_refit cost=10

Convex diagnostic repeat=1 annual_refit cost=25

Convex diagnostic repeat=1 frozen2022 cost=10

Convex diagnostic repeat=1 frozen2022 cost=25

Convex diagnostic repeat=2 annual_refit cost=10

Convex diagnostic repeat=2 annual_refit cost=25

Convex diagnostic repeat=2 frozen2022 cost=10

Convex diagnostic repeat=2 frozen2022 cost=25

Convex diagnostic repeat=3 annual_refit cost=10

Convex diagnostic repeat=3 annual_refit cost=25

Convex diagnostic repeat=3 frozen2022 cost=10

Convex diagnostic repeat=3 frozen2022 cost=25

backtest loop:   0%|          | 0/1762 [00:00<?, ?it/s]

backtest loop:   0%|          | 0/1762 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

{'experiment': 'convex_excess_20261002',
 'campaign_status': 'active_research',
 'objective_achieved': False,
 'decision': 'continue_research_no_historical_qualification',
 'selected': {'variant': 'robust_ridge_h5',
  'historical_qualification_pass': False,
  'passed_gates': 10,
  'worst_annualized_lower_bound': -0.06800690503604515,
  'worst_relative_wealth': 0.8968674994575024,
  'positive_years_10bps': 3},
 'plan_sha256': '9d4cc905d44fa6b0b636748548a5043f07542f9eca0a08585cf0319fff32c8e7',
 'source_as_of': '2026-09-25',
 'source_recorder_id': 'b94059c2e0754b0ab102e4f62534eefb',
 'environment': {'python': '3.12.12',
  'platform': 'macOS-26.2-arm64-arm-64bit',
  'pyqlib': '0.9.7',
  'numpy': '2.5.3',
  'pandas': '2.3.3',
  'cvxpy': '1.9.3',
  'clarabel': '0.11.1',
  'scikit-learn': '1.9.1'},
 'provider_uri': 'data/qlib/stable_excess_integration_20261002',
 'region': 'us',
 'market': 'all',
 'data_audit': {'horizon_sessions': 5,
  'formula': 'open[t+6]/open[t+1]-1',
  'signal': 'close[t]',
  'entry': 'open[t+1]',
  'outcome_available': 'open[t+6],09:30 America/New_York',
  'feature_columns': ['soxx_ret1',
   'soxx_mom5',
   'soxx_mom20',
   'soxx_mom60',
   'soxx_reversal1',
   'soxx_vol10',
   'soxx_vol20',
   'soxx_downside_vol20',
   'soxx_skew20',
   'soxx_kurt60',
   'soxx_drawdown20',
   'soxx_drawdown60',
   'soxx_gap1',
   'soxx_intraday1',
   'soxx_volume_z20',
   'soxx_range_pct',
   'soxl_gap1',
   'soxl_intraday1',
   'soxl_volume_z20',
   'soxl_range_pct',
   'relative_log_return_1d',
   'relative_log_return_5d',
   'relative_log_return_20d',
   'relative_volatility_20',
   'soxx_efficiency_20'],
  'label_columns': ['soxl_return_h5', 'soxx_return_h5'],
  'primary_input_sha256': 'e29390b697b176f2dd6a9731cdcef34c019e000ecbf6f3c4aa494764bfd93246',
  'execution_prices_sha256': 'fe78c5dcadac986e757d8b5d30cbbf0dc3b667b1d32e1377ee313a6ae66ba12a',
  'horizon_frame_sha256': '4b855df7ffb4a809c621fcd6698cba0a2941fd328412150654df3d9fb2709a52',
  'rows': 3956,
  'complete_labels': 3950,
  'last_feature_date': '2026-09-25',
  'last_complete_label_signal': '2026-09-17',
  'last_complete_label_available_at': '2026-09-25T09:30:00-04:00',
  'daily_returns_preserved': True,
  'mean_covariance_units': 'five_session_simple_return_squared',
  'daily_risk_covariance_units': 'one_session_simple_return_squared',
  'qlib_docs_reference': 'https://qlib.readthedocs.io/en/latest/component/data.html'},
 'source_sha256': {'src/data/convex_allocation.py': '915c7eae8da16d69221d660e040b26ad5ba16e37fd607afd01ae0842e0fba82f',
  'src/model/convex_allocation.py': 'da25951193c0b28948754527e8a9990bb33eb04f8137ce7d694a28304cb34a47',
  'src/workflow/convex_excess.py': 'dee0b77983fee5268c3f76360c11b1cb145aca3cffec1e5e4e89afa28c0fa698',
  'src/data/integrated_allocation.py': '73f2495f6a9860860a76a5a8c2f679c42f5a76f089c10fb7d347ce66acc36e9c',
  'src/analysis/integrated_allocation.py': '63a04045c59e8266efc2642a4db3d080845bdefbad6c2ac914a2194d26c17fc4',
  'src/workflow/benchmark_risk_excess.py': '26fcd325ca5cd20ed37eec9e8296b477eedc907e4c815af802d448236b5cdbcd',
  'src/workflow/stable_excess_integration.py': '7753c5bc16dddda5758d6fe5609fa7be915c6484f05e1881989a67afdf17771c',
  'src/backtest/position_accounting.py': '070a42a631f4ddc5aaa251791c9c8e43b263d34e9ae70d7e0a66a486f6b4fdde',
  'src/workflow/stage1_economic_action.py': '17a580e1a0fdf1e991fdfd150d59e80f272f199a9f0bd45a99d325d155cd5fe7',
  'src/analysis/convex_qlib.py': '7bb60f7a3365cc36623785f25aa62c2f585211eb85483c0a3891caa53d7fd9e9',
  'src/backtest/qlib_continuous_position.py': 'f06bb596b6d3d3f875e9b6c59490080684d13fbe9f6763bd039d1b2afa4c5721'},
 'qlib_docs_reference': ['https://qlib.readthedocs.io/en/latest/component/data.html',
  'https://qlib.readthedocs.io/en/latest/component/workflow.html'],
 'benchmark': '100percent SOXX fee-funded buyhold; identical dates, marks and funding',
 'model_selection': {'variant': 'robust_ridge_h5',
  'historical_qualification_pass': False,
  'passed_gates': 10,
  'worst_annualized_lower_bound': -0.06800690503604515,
  'worst_relative_wealth': 0.8968674994575024,
  'positive_years_10bps': 3},
 'sidecars': ['model_selection.csv',
  'backtest_benchmark_comparison.csv',
  'annual_metrics.csv',
  'development_gates.csv',
  'bootstrap_analysis.csv',
  'repeated_metrics.csv',
  'reproduction_audit.csv',
  'risk_solver_audit.csv',
  'prior_control_comparison.csv'],
 'historical_qualification_pass': False,
 'new_forward_qualified': False,
 'selection_uses_diagnostic_signal_years': False,
 'development_last_exit': '2023-01-04',
 'deterministic_reproduction': {'fresh_fits_and_solves': 3,
  'all_match': True,
  'tolerance': 1e-08,
  'independent_statistical_observations': False},
 'recorder_id': '53dc5870bc8741d2a939938b0f6be9df',
 'recorder_uri': '/Users/rziiiii/dev/workspace/research/convex_excess_20261002/qlib_recorder',
 'recorder_local_dir': '/Users/rziiiii/dev/workspace/research/convex_excess_20261002/qlib_recorder/333485224999987774/53dc5870bc8741d2a939938b0f6be9df',
 'recorder_relative_dir': 'qlib_recorder/333485224999987774/53dc5870bc8741d2a939938b0f6be9df',
 'native_qlib_audit': {'10': {'status': 'passed',
   'sessions': 1762,
   'start': '2016-01-05',
   'end': '2023-01-03',
   'provider_uri': '/Users/rziiiii/dev/workspace-worktrees/convex-excess-20261002/data/qlib/stable_excess_integration_20261002',
   'cost_bps': 10.0,
   'initial_cash': 100000.0,
   'maximum_session_return_error': 5.9565412824369446e-08,
   'tolerance': 1e-07,
   'native_api': 'qlib.backtest.backtest + SimulatorExecutor + Exchange + Account + Position',
   'position_type': 'src.backtest.qlib_continuous_position.QlibContinuousPosition',
   'position_precision_fix': 'Every positive fractional-sale residual remains owned; no relative isclose liquidation.',
   'report_mark': 'native same-day close; next-open reconciliation marks native positions through Qlib D.features',
   'sealed_stage1_code_changed': False,
   'qlib_api_reference': 'https://qlib.readthedocs.io/en/latest/reference/api.html#qlib.backtest.backtest',
   'policy_scope': 'continuous_three_asset_targets_without_legacy_allocation_caps',
   'legacy_controller_executed': False,
   'scope': 'complete prescribed daily target/HOLD schedule; actual Qlib Exchange, Position, report and next-open accounting',
   'risk_annualization_sessions': 252,
   'native_close_anchored_max_drawdown_pct': -43.61055593877987,
   'native_open_to_open_anchored_max_drawdown_pct': -45.29486014430317,
   'risk_table_mark_convention': 'risk_analysis uses native close marks; risk_analysis_open_to_open uses native positions marked at the following open',
   'execution_limitation': 'Observed historical opens and continuous adjusted shares; no claim of spread/impact/partial-fill evidence.'},
  '25': {'status': 'passed',
   'sessions': 1762,
   'start': '2016-01-05',
   'end': '2023-01-03',
   'provider_uri': '/Users/rziiiii/dev/workspace-worktrees/convex-excess-20261002/data/qlib/stable_excess_integration_20261002',
   'cost_bps': 25.0,
   'initial_cash': 100000.0,
   'maximum_session_return_error': 5.946452930061241e-08,
   'tolerance': 1e-07,
   'native_api': 'qlib.backtest.backtest + SimulatorExecutor + Exchange + Account + Position',
   'position_type': 'src.backtest.qlib_continuous_position.QlibContinuousPosition',
   'position_precision_fix': 'Every positive fractional-sale residual remains owned; no relative isclose liquidation.',
   'report_mark': 'native same-day close; next-open reconciliation marks native positions through Qlib D.features',
   'sealed_stage1_code_changed': False,
   'qlib_api_reference': 'https://qlib.readthedocs.io/en/latest/reference/api.html#qlib.backtest.backtest',
   'policy_scope': 'continuous_three_asset_targets_without_legacy_allocation_caps',
   'legacy_controller_executed': False,
   'scope': 'complete prescribed daily target/HOLD schedule; actual Qlib Exchange, Position, report and next-open accounting',
   'risk_annualization_sessions': 252,
   'native_close_anchored_max_drawdown_pct': -43.77947132017997,
   'native_open_to_open_anchored_max_drawdown_pct': -45.458730168508964,
   'risk_table_mark_convention': 'risk_analysis uses native close marks; risk_analysis_open_to_open uses native positions marked at the following open',
   'execution_limitation': 'Observed historical opens and continuous adjusted shares; no claim of spread/impact/partial-fill evidence.'}},
 'production_change': False,
 'real_broker_orders': False,
 'artifact_policy': {'policy': 'slim_card_recorder_first',
  'workflow_config': 'workflow.yaml',
  'recorder_only_artifacts': ['inputs/*.pkl',
   'models/*.pkl',
   'predictions/*.pkl',
   'analysis/portfolio_replays.pkl',
   'analysis/daily_solver_audits.pkl',
   'portfolio_analysis/*.pkl']},
 'limitations': ['Previously inspected history is not fresh OOS; family10 correction excludes older adaptive search.',
  'H5 utility assumes no future trading but actual policy reoptimizes daily; it is a rolling planning approximation.',
  'Estimated variance bounds do not ensure realized tail-risk bounds; actual drawdown/CVaR gates remain mandatory.',
  'One SEM robust radius is not a confidence guarantee; excludes ridge bias and regime change.',
  'Frozen primary features and execution labels use different historical distribution-adjustment conventions; this round preserves those inputs, and a unified-basis audit is required before further deployment claims.',
  'A failed experimental batch does not complete the stable-excess objective.']}

## 数据和证据

沿用固定 Qlib recorder b94059c2e0754b0ab102e4f62534eefb 和截至2026-09-25的执行价格。数据进入 DatasetH；模型、逐日预测、实际持仓路径与 Qlib 原生回测存入本卡 Recorder。三次确定性复现不增加统计样本。

In [2]:
import pandas as pd
CARD = ROOT / 'research' / 'convex_excess_20261002'
display(pd.read_csv(CARD / 'backtest_benchmark_comparison.csv'))
display(pd.read_csv(CARD / 'development_gates.csv'))
print((CARD / 'conclusion.md').read_text())

,cost_bps,sessions,start_signal,last_exit,terminal_wealth,return_pct,cagr_pct,annualized_log_volatility_pct,max_drawdown_pct,qlib_max_drawdown_without_initial_mark_pct,...,annualized_log_excess,annualized_relative_return_pct,relative_max_drawdown_pct,up_day_conditional_relative_return_pct,down_day_conditional_relative_return_pct,conditional_returns_are_noncontiguous_statistics,risk_policy,annualization_sessions,variant,segment
0,10.0,1762,2016-01-04,2023-01-04,3.444115,244.411453,19.347261,30.367670,-48.728061,-48.728061,...,-0.030769,-3.030053,-19.875565,-23.446244,5.341536,True,reported against benchmark; no implicit fixed ...,252,prior_h5,development
1,25.0,1762,2016-01-04,2023-01-04,3.358022,235.802193,18.915946,30.367404,-48.944646,-48.944646,...,-0.034175,-3.359804,-21.748922,-24.503370,4.302527,True,reported against benchmark; no implicit fixed ...,252,prior_h5,development
2,10.0,1762,2016-01-04,2023-01-04,3.516928,251.692843,19.704899,28.370093,-44.408636,-44.408636,...,-0.027777,-2.739472,-38.398990,-90.516149,768.295177,True,reported against benchmark; no implicit fixed ...,252,ridge_h5,development
3,25.0,1762,2016-01-04,2023-01-04,2.793493,179.349271,15.826440,28.304888,-45.610208,-45.610208,...,-0.060499,-5.870574,-46.989649,-92.166234,736.210915,True,reported against benchmark; no implicit fixed ...,252,ridge_h5,development
4,10.0,1762,2016-01-04,2023-01-04,4.220258,322.025801,22.867082,29.826673,-45.294855,-45.294855,...,-0.001703,-0.170190,-19.260122,-52.022497,105.963340,True,reported against benchmark; no implicit fixed ...,252,robust_ridge_h5,development
5,25.0,1762,2016-01-04,2023-01-04,3.824630,282.462990,21.149473,29.854097,-45.458725,-45.458725,...,-0.015567,-1.544670,-24.626789,-55.060790,99.573489,True,reported against benchmark; no implicit fixed ...,252,robust_ridge_h5,development
6,10.0,934,2023-01-03,2026-09-25,6.142374,514.237411,63.191999,36.144320,-42.991378,-42.991378,...,0.056733,5.837308,-15.464498,-34.208335,87.563818,True,reported against benchmark; no implicit fixed ...,252,robust_ridge_h5_annual_refit,reused_diagnostic
7,25.0,934,2023-01-03,2026-09-25,4.895474,389.547406,53.501155,36.046440,-42.790376,-42.790376,...,-0.004082,-0.407411,-20.243490,-43.993072,75.868064,True,reported against benchmark; no implicit fixed ...,252,robust_ridge_h5_annual_refit,reused_diagnostic
8,10.0,934,2023-01-03,2026-09-25,5.296297,429.629669,56.795285,35.976871,-39.665402,-39.665402,...,0.016747,1.688753,-17.444066,-45.724473,96.043267,True,reported against benchmark; no implicit fixed ...,252,robust_ridge_h5_frozen2022,reused_diagnostic
9,25.0,934,2023-01-03,2026-09-25,4.367968,336.796840,48.851106,35.805314,-40.243541,-40.243541,...,-0.034844,-3.424393,-24.414549,-53.067383,87.257274,True,reported against benchmark; no implicit fixed ...,252,robust_ridge_h5_frozen2022,reused_diagnostic

,cost_bps,aggregate_positive_net_log_excess,minimum_positive_signal_years,median_annual_log_excess_positive,leave_any_one_year_out_log_excess_positive,anchored_max_drawdown_not_worse_than_soxx,cvar5_not_worse_than_soxx,all_repeats_positive_at_both_costs,stationary_block_20_lower_bound_positive,stationary_block_60_lower_bound_positive,...,years,positive_repeats_at_this_cost,repeats_positive_at_both_costs,repeat_evidence_complete,largest_positive_year_share,minimum_leave_one_year_out_log_excess,all_three_fresh_runs_match,all_convex_solutions_verified,measurable_log_excess_above_numerical_tolerance,variant
0,10.0,False,False,False,False,False,True,False,False,False,...,7,0,0,True,NaN,-0.204763,True,True,False,prior_h5
1,25.0,False,False,False,False,False,True,False,False,False,...,7,0,0,True,NaN,-0.225187,True,True,False,prior_h5
2,10.0,False,False,False,False,True,True,False,False,False,...,7,0,0,True,0.537397,-0.233097,True,True,False,ridge_h5
3,25.0,False,False,False,False,True,True,False,False,False,...,7,0,0,True,NaN,-0.416839,True,True,False,ridge_h5
4,10.0,False,False,False,False,True,True,False,False,False,...,7,0,0,True,0.640864,-0.106290,True,True,False,robust_ridge_h5
5,25.0,False,False,False,False,True,True,False,False,False,...,7,0,0,True,0.444404,-0.147927,True,True,False,robust_ridge_h5

# 可达基准的凸配置实验结论

完成3个确定性版本，每版3次真实重拟合与求解，历史资格通过=False；稳定超额目标仍在进行。

年度仅用严格成熟的五日开盘收益训练均值模型；每日在现金费用和因果SOXX方差预算下求解，纯SOXX作为显式可行基准。三次复现不增加统计样本。

开发期2016–2022信号年，10bp：
- prior_h5：收益244.41%，相对SOXX终值0.8064，MaxDD-48.73%，CVaR5-4.37%。
- ridge_h5：收益251.69%，相对SOXX终值0.8235，MaxDD-44.41%，CVaR5-4.28%。
- robust_ridge_h5：收益322.03%，相对SOXX终值0.9882，MaxDD-45.29%，CVaR5-4.35%。

年度差异见 annual_metrics.csv；2023以后已看过的诊断窗口在开发选择封存后运行，未用于排名。费用压力、留一年、区块bootstrap和尾部风险门均保留。

推广决定：continue_research_no_historical_qualification；没有修改现有SIM或发出委托。下一步检查预测误差、实际换手和相对无信号对照的增量，登记下一项独立机制检验。
风险：历史反复检视、均值估计不稳定、H5计划与每日重配差异、扩展风险估计的滞后。冻结特征与执行收益的历史分红复权口径不同，本轮保持旧输入以隔离优化修复；下一轮先统一数据口径。数学求解正确不等于真实收益可靠。
Qlib recorder：53dc5870bc8741d2a939938b0f6be9df。

# 可达基准的凸配置实验结论

完成3个确定性版本，每版3次真实重拟合与求解，历史资格通过=False；稳定超额目标仍在进行。

年度仅用严格成熟的五日开盘收益训练均值模型；每日在现金费用和因果SOXX方差预算下求解，纯SOXX作为显式可行基准。三次复现不增加统计样本。

开发期2016–2022信号年，10bp：
- prior_h5：收益244.41%，相对SOXX终值0.8064，MaxDD-48.73%，CVaR5-4.37%。
- ridge_h5：收益251.69%，相对SOXX终值0.8235，MaxDD-44.41%，CVaR5-4.28%。
- robust_ridge_h5：收益322.03%，相对SOXX终值0.9882，MaxDD-45.29%，CVaR5-4.35%。

年度差异见 annual_metrics.csv；2023以后已看过的诊断窗口在开发选择封存后运行，未用于排名。费用压力、留一年、区块bootstrap和尾部风险门均保留。

推广决定：continue_research_no_historical_qualification；没有修改现有SIM或发出委托。下一步检查预测误差、实际换手和相对无信号对照的增量，登记下一项独立机制检验。
风险：历史反复检视、均值估计不稳定、H5计划与每日重配差异、扩展风险估计的滞后。冻结特征与执行收益的历史分红复权口径不同，本轮保持旧输入以隔离优化修复；下一轮先统一数据口径。数学求解正确不等于真实收益可靠。
Qlib recorder：53dc5870bc8741d2a939938b0f6be9df。

数学与工程证据：30条复现/费用路径、42,924次决策全部验证，零回退；三次模型、预测和组合路径一致，原生Qlib两档费用均通过。55项针对性测试通过；全套797通过、139个既有失败，失败集合没有新增。

已看过的2023–2026诊断期：年度重拟合相对SOXX终值在10bp为+23.40%、25bp为−1.50%；冻结2022参数在10bp为+6.40%、25bp为−12.12%。费用敏感，不能据此宣称前向稳定超额。

初次完整Recorder 3fd837456d2f4095a4251c6c7ce0d3df包含明确标记的数值回退；本次53dc5870bc8741d2a939938b0f6be9df是已验证求解路径，两者结果分别保留，不混用。后续先完成统一数据基准，再预登记条件波动比较，整体目标继续。