# SOXL 连续区间 3x 保持度因子

使用纯文本口径评估 SOXL 在连续21/63/126日区间内能否维持3x，并检验滚动保持度对未来21/63日保持度是否具有前向增量价值。

In [1]:
from pathlib import Path
import sys
import pandas as pd
import qlib
from qlib.config import REG_US
from qlib.data import D
from qlib.data.dataset import DatasetH
from qlib.workflow import R
from IPython.display import Markdown, display

repo_root = Path.cwd().resolve().parents[1]
sys.path.insert(0, str(repo_root))
from src.workflow.soxl_rolling_3x_retention_factor import run_soxl_rolling_3x_retention_factor_card

provider_uri = repo_root / 'data' / 'qlib' / 'soxl'
qlib.init(provider_uri=str(provider_uri), region=REG_US, kernels=1)
calendar = D.calendar(freq='day')
source_check = D.features(['SOXL', 'SOXX'], ['$close', '$vix'], start_time='2010-03-11', end_time=str(pd.Timestamp(calendar[-1]).date()), freq='day')
{'calendar_rows': len(calendar), 'feature_rows': len(source_check)}

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[89512:MainThread](2026-07-29 20:59:14,516) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[89512:MainThread](2026-07-29 20:59:14,519) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[89512:MainThread](2026-07-29 20:59:14,519) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

{'calendar_rows': 4120, 'feature_rows': 8240}

In [2]:
summary = run_soxl_rolling_3x_retention_factor_card(root=repo_root)
card = repo_root / 'research' / summary['experiment']
display(pd.read_json(card / 'current_factor_snapshot.json'))
display(pd.read_csv(card / 'model_comparison.csv').query("fold == 'outer_2023_2026' and sample == 'nonoverlap'"))
{'decision': summary['decision'], 'recorder_id': summary['recorder_id']}

[89512:MainThread](2026-07-29 20:59:14,542) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[89512:MainThread](2026-07-29 20:59:14,543) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[89512:MainThread](2026-07-29 20:59:14,543) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[89512:MainThread](2026-07-29 20:59:14,548) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[89512:MainThread](2026-07-29 20:59:14,549) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[89512:MainThread](2026-07-29 20:59:14,549) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[89512:MainThread](2026-07-29 20:59:14,579) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[89512:MainThread](2026-07-29 20:59:14,580) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[89512:MainThread](2026-07-29 20:59:14,580) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[89512:MainThread](2026-07-29 20:59:14,982) WARNING - qlib.workflow - [expm.py:231] - No valid experiment found. Create a new experiment with name soxl_rolling_3x_retention_factor_v1.

[89512:MainThread](2026-07-29 20:59:14,985) INFO - qlib.workflow - [exp.py:258] - Experiment 720395977227178321 starts running ...

[89512:MainThread](2026-07-29 20:59:15,072) INFO - qlib.workflow - [recorder.py:345] - Recorder 58ee5fd74e2245afbfc10783fd6fa62a starts running under Experiment 720395977227178321 ...

[89512:MainThread](2026-07-29 20:59:15,195) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

,as_of,lookback_days,soxx_return,soxl_return,effective_multiple,endpoint_3x_gap,continuous_3x_retention_ratio,actual_3x_residual_log,ideal_path_drag_log,product_tracking_log,retention_z252,soxx_realized_volatility
0,2026-07-28,21,-0.166932,-0.491930,2.946881,0.008867,0.878786,-0.129214,-0.093539,-0.035676,-1.911914,0.591540
1,2026-07-28,63,0.079159,-0.112246,-1.417971,-0.349724,0.706376,-0.347608,-0.317928,-0.029679,-3.064860,0.642094
2,2026-07-28,126,0.432536,0.804613,1.860223,-0.492994,0.613858,-0.487992,-0.437527,-0.050465,-2.537314,0.532366

,target_horizon_days,fold,model,sample,train_rows,test_rows,pearson,spearman,r2,mae
31,21,outer_2023_2026,vix_level,nonoverlap,3226,42,0.600247,0.466980,-0.224421,0.023442
33,21,outer_2023_2026,vix_normalized,nonoverlap,3100,42,0.622801,0.582692,-0.119361,0.023770
35,21,outer_2023_2026,core_baseline,nonoverlap,3037,42,0.620589,0.583502,-0.125380,0.023809
37,21,outer_2023_2026,retention_factor,nonoverlap,3079,42,0.519857,0.428733,-0.278759,0.024467
39,21,outer_2023_2026,baseline_plus_retention,nonoverlap,3037,42,0.663188,0.568755,-0.049509,0.023625
71,63,outer_2023_2026,vix_level,nonoverlap,3226,14,0.228834,0.156044,-0.920962,0.064800
73,63,outer_2023_2026,vix_normalized,nonoverlap,3100,14,0.282048,0.252747,-0.906425,0.065435
75,63,outer_2023_2026,core_baseline,nonoverlap,3037,14,0.242051,0.002198,-0.945122,0.067925
77,63,outer_2023_2026,retention_factor,nonoverlap,3079,14,0.401801,0.437363,-1.110388,0.075539
79,63,outer_2023_2026,baseline_plus_retention,nonoverlap,3037,14,0.274456,0.142857,-1.003668,0.069896

{'decision': 'diagnostic_guardrail_value_not_incremental_alpha',
 'recorder_id': '58ee5fd74e2245afbfc10783fd6fa62a'}

## 中文结论

In [3]:
display(Markdown((card / 'conclusion.md').read_text(encoding='utf-8')))

# 中文结论

- 口径：TUI 结论全部使用纯文本。直观倍数等于“SOXL区间收益 / SOXX区间收益”；稳定因子使用“log(SOXL总收益倍数) - 3 × log(SOXX总收益倍数)”，再用此前252日均值和标准差归一化，当前日期不进入历史均值。
- 原始倍数不适合作因子：21日窗口中，SOXX区间收益绝对值低于2%的比例为 20.27%；有效倍数历史1%至99%分位为 -5.03 至 15.43，近零分母会制造极值。
- 当前21日：SOXX -16.69%，SOXL -49.19%，直观倍数 2.95；连续3x保持比 87.88%，相对自身过去252日为 -1.91 个标准差。
- 当前63日：SOXX 7.92%，SOXL -11.22%，直观倍数 -1.42；连续3x保持比 70.64%，Z分数 -3.06。底层上涨但SOXL下跌，正是震荡损耗主导的区间。
- 当前126日：SOXX 43.25%，SOXL 80.46%，直观倍数 1.86；连续3x保持比 61.39%。
- 21日因子有单变量状态价值：2023–2026重叠样本对未来21日保持度的Spearman为 0.406，非重叠样本为 0.429。
- 但不是稳定增量alpha：加入VIX、自身实现波动、趋势和路径效率后，外部期重叠样本增量Spearman为 0.094，非重叠为 -0.015；仅 1/4 个时间折增益为正，且R2为 -0.249。
- 未来63日同样未通过：非重叠增量Spearman为 0.141，仅 1/4 个时间折改善。
- 机制：纯路径损耗与SOXX实现波动几乎同义，21/63/126日Spearman绝对值接近1；剩余部分主要是产品跟踪噪声。因此它适合压缩为一个SOXL自身风险状态，不能替代方向因子。
- 决策：diagnostic_guardrail_value_not_incremental_alpha。允许作为Stage1候选风险输入做前向paper观察；禁止单独据此交易或直接调整生产权重。
- qlib recorder：58ee5fd74e2245afbfc10783fd6fa62a。
- 风险：outer已被查看，不是clean holdout；滚动标签重叠；非重叠63日样本很少；当前极端状态可能主导相关性。
- 下一步：只保留21日标准化保持度，在新的前向样本中检查它是否能改善SOXL风险上限或回撤控制，而不是继续增加更长窗口。
- 不构成买卖建议。