# Stage1 feasible-action 训练域对照（预声明合法性对照）

统一 vintage 冻结 coherent 输入上：1 候选（feasible 域）+ all-state 对照 + active/no_hold/SOXX。
超参/labelfee/minrows/硬修复全不变；不调参。前提“非法样本主导极值”实证不成立。

In [1]:
import sys, json, hashlib
from pathlib import Path

ROOT = Path.cwd()
while not (ROOT/'AGENTS.md').exists():
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))
CARD = ROOT/'research'/'stage1_feasible_action_training_20261009'
print('plan sha256:', hashlib.sha256((CARD/'plan.json').read_bytes()).hexdigest())

plan sha256: 78f053b70475cf43753d5c309edb88ebfb3516037301451e4875254b8da2411b

In [2]:
from src.workflow import feasible_action_experiment as workflow
summary = workflow.run_feasible_action_training(root=ROOT, card_dir=CARD)
print('decision:', summary['decision'], '| control_reproduction:', summary['control_reproduction'])
print('native:', summary['native_reconciliation']['status'], 'boundary:', summary['native_reconciliation'].get('boundary'))
print('recorder:', summary['recorder_id'])
print('model inventory:', {k:(v.get('annual_models') if isinstance(v,dict) else v) for k,v in summary['model_inventory'].items()})

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

2026/10/10 00:40:53 INFO mlflow.agent.hint: Load the `instrumenting-with-mlflow-tracing` skill at /Users/rziiiii/dev/workspace/qlib_venv/lib/python3.12/site-packages/mlflow/assistant/skills/instrumenting-with-mlflow-tracing/SKILL.md before writing any tracing code; it ships with this MLflow install. Set MLFLOW_DISABLE_AGENT_HINT=1 to silence this.

[75891:MainThread](2026-10-10 00:40:53,802) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:40:53,803) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:40:53,803) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:40:53,857) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:40:53,858) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:40:53,858) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:40:53,869) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:40:53,870) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:40:53,870) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_intraday_20261009')}

[75891:MainThread](2026-10-10 00:40:54,380) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[75891:MainThread](2026-10-10 00:40:54,381) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[75891:MainThread](2026-10-10 00:40:54,381) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[75891:MainThread](2026-10-10 00:40:54,845) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[75891:MainThread](2026-10-10 00:40:54,846) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[75891:MainThread](2026-10-10 00:40:54,846) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[75891:MainThread](2026-10-10 00:40:55,273) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[75891:MainThread](2026-10-10 00:40:55,273) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[75891:MainThread](2026-10-10 00:40:55,273) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[75891:MainThread](2026-10-10 00:40:55,707) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[75891:MainThread](2026-10-10 00:40:55,707) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[75891:MainThread](2026-10-10 00:40:55,707) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[75891:MainThread](2026-10-10 00:40:56,143) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[75891:MainThread](2026-10-10 00:40:56,143) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[75891:MainThread](2026-10-10 00:40:56,143) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[75891:MainThread](2026-10-10 00:40:56,631) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[75891:MainThread](2026-10-10 00:40:56,632) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[75891:MainThread](2026-10-10 00:40:56,632) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[75891:MainThread](2026-10-10 00:40:57,409) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[75891:MainThread](2026-10-10 00:40:57,410) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[75891:MainThread](2026-10-10 00:40:57,410) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[75891:MainThread](2026-10-10 00:40:59,378) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[75891:MainThread](2026-10-10 00:40:59,378) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[75891:MainThread](2026-10-10 00:40:59,379) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[75891:MainThread](2026-10-10 00:41:01,649) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[75891:MainThread](2026-10-10 00:41:01,649) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[75891:MainThread](2026-10-10 00:41:01,649) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[75891:MainThread](2026-10-10 00:41:02,069) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[75891:MainThread](2026-10-10 00:41:02,070) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[75891:MainThread](2026-10-10 00:41:02,070) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[75891:MainThread](2026-10-10 00:41:02,493) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[75891:MainThread](2026-10-10 00:41:02,493) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[75891:MainThread](2026-10-10 00:41:02,493) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[75891:MainThread](2026-10-10 00:41:02,926) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[75891:MainThread](2026-10-10 00:41:02,927) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[75891:MainThread](2026-10-10 00:41:02,927) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[75891:MainThread](2026-10-10 00:41:03,360) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[75891:MainThread](2026-10-10 00:41:03,361) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[75891:MainThread](2026-10-10 00:41:03,361) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[75891:MainThread](2026-10-10 00:41:03,849) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[75891:MainThread](2026-10-10 00:41:03,850) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[75891:MainThread](2026-10-10 00:41:03,850) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[75891:MainThread](2026-10-10 00:41:04,629) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[75891:MainThread](2026-10-10 00:41:04,629) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[75891:MainThread](2026-10-10 00:41:04,630) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[75891:MainThread](2026-10-10 00:41:06,503) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[75891:MainThread](2026-10-10 00:41:06,503) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[75891:MainThread](2026-10-10 00:41:06,503) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[75891:MainThread](2026-10-10 00:41:25,238) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:41:25,239) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:41:25,239) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:41:25,253) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:41:25,253) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:41:25,254) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:41:25,261) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:41:25,261) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:41:25,262) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:41:25,266) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:41:25,270) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:41:25,274) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:41:25,274) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:41:25,276) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x1219888c0>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:41:25,708) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:41:25,708) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:41:25,709) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:41:25,786) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:41:25,787) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:41:25,787) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:41:25,914) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:41:25,947) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:41:26,035) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:41:26,036) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:41:26,064) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x121d1d250>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:41:36,139) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:41:36,140) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:41:36,140) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:41:36,157) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:41:36,158) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:41:36,158) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:41:36,167) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:41:36,168) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:41:36,168) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:41:36,172) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:41:36,178) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:41:36,182) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:41:36,182) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:41:36,184) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x12e5ad250>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:41:36,613) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:41:36,614) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:41:36,614) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:41:36,689) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:41:36,690) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:41:36,690) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:41:36,732) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:41:36,765) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:41:36,855) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:41:36,855) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:41:36,883) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x121fcb020>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:41:47,340) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:41:47,341) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:41:47,341) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:41:47,357) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:41:47,358) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:41:47,358) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:41:47,434) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:41:47,434) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:41:47,435) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:41:47,476) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:41:47,508) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:41:47,590) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:41:47,590) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:41:47,619) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x127ab0740>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:41:57,554) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:41:57,555) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:41:57,555) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:41:57,572) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:41:57,573) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:41:57,573) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:41:57,648) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:41:57,649) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:41:57,649) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:41:57,690) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:41:57,721) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:41:57,805) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:41:57,805) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:41:57,833) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x12ceb5250>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:42:07,653) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:42:07,654) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:42:07,655) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:42:07,671) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:42:07,672) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:42:07,672) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:42:07,682) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:42:07,683) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:42:07,683) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:42:07,687) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:42:07,693) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:42:07,697) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:42:07,697) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:42:07,699) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x12dd40fb0>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:42:08,164) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:42:08,165) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:42:08,165) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:42:08,752) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:42:08,753) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:42:08,753) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:42:08,799) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:42:08,832) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:42:08,925) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:42:08,925) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:42:08,957) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x12dfb76b0>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:42:19,292) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:42:19,293) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:42:19,293) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:42:19,310) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:42:19,311) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:42:19,311) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:42:19,320) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:42:19,321) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:42:19,321) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:42:19,325) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:42:19,331) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:42:19,335) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:42:19,335) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:42:19,337) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x12c34bb90>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:42:19,798) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:42:19,799) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:42:19,799) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:42:19,879) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:42:19,880) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:42:19,880) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:42:19,928) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:42:19,963) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:42:20,056) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:42:20,056) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:42:20,084) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x129b58740>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:42:31,015) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:42:31,016) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:42:31,017) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:42:31,034) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:42:31,035) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:42:31,035) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:42:31,118) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:42:31,119) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:42:31,119) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:42:31,169) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:42:31,201) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:42:31,292) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:42:31,292) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:42:31,322) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x123b58590>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:42:41,235) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:42:41,236) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:42:41,237) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:42:41,253) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:42:41,254) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:42:41,254) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:42:41,331) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:42:41,332) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:42:41,332) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:42:41,377) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:42:41,407) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:42:41,491) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:42:41,492) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:42:41,520) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x122f22c30>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:42:52,016) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:42:52,017) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:42:52,017) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:42:52,034) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:42:52,035) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:42:52,036) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:42:52,046) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:42:52,046) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:42:52,047) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:42:52,051) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:42:52,057) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:42:52,061) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:42:52,061) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:42:52,063) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x13e9c6240>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:42:52,594) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:42:52,594) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:42:52,595) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:42:52,673) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:42:52,674) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:42:52,674) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:42:52,718) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:42:52,752) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:42:52,842) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:42:52,843) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:42:52,870) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x12a2c3620>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:43:03,209) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:03,210) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:03,211) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:03,228) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:03,229) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:03,229) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:03,238) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:03,239) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:03,239) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:03,243) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:43:03,248) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:43:03,253) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:43:03,253) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:43:03,255) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x125e88650>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:43:03,788) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:03,789) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:03,789) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:03,867) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:03,868) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:03,868) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:03,913) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:43:03,946) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:43:04,038) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:43:04,038) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:43:04,066) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x12dad18e0>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:43:14,580) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:14,582) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:14,582) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:14,599) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:14,600) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:14,600) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:14,610) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:14,611) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:14,611) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:14,615) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:43:14,621) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:43:14,625) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:43:14,625) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:43:14,627) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x13e1fe270>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:43:14,975) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:14,976) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:14,976) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:15,056) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:15,057) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:15,057) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:15,915) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:43:15,947) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:43:16,038) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:43:16,038) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:43:16,068) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x143ed18e0>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:43:23,035) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:23,036) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:23,036) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:23,052) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:23,053) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:23,054) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:23,062) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:23,063) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:23,063) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:23,067) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:43:23,072) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:43:23,077) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:43:23,077) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:43:23,079) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x12478bd70>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:43:23,610) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:23,611) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:23,611) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:24,495) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:24,496) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:24,496) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:24,543) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:43:24,576) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:43:24,666) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:43:24,667) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:43:24,697) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x144646630>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:43:35,254) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:35,255) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:35,255) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:35,272) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:35,273) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:35,273) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:35,282) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:35,283) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:35,283) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:35,288) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:43:35,294) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:43:35,298) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:43:35,299) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:43:35,301) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x129ba8740>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:43:35,836) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:35,837) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:35,837) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:35,918) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:35,919) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:35,920) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:35,968) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:43:36,001) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:43:36,090) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:43:36,091) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:43:36,120) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x143e60620>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:43:47,004) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:47,005) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:47,006) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:47,023) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:47,023) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:47,024) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:47,033) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:47,034) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:47,034) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:47,039) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:43:47,044) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:43:47,048) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:43:47,049) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:43:47,050) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x1461f8e30>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:43:47,399) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:47,400) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:47,400) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:47,482) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:47,483) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:47,483) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:47,532) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:43:47,565) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:43:47,656) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:43:47,656) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:43:47,685) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x1235f0710>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:43:55,076) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:55,077) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:55,077) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:55,094) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:55,095) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:55,095) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:55,175) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:43:55,176) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:43:55,176) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:43:56,098) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:43:56,128) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:43:56,213) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:43:56,214) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:43:56,246) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x12c96a870>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:44:05,975) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:44:05,976) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:44:05,976) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:44:05,992) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:44:05,993) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:44:05,994) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:44:06,074) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:44:06,075) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:44:06,075) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:44:06,123) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:44:06,154) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:44:06,238) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:44:06,239) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:44:06,268) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x145fd5250>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:44:17,071) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:44:17,073) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:44:17,073) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:44:17,090) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:44:17,091) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:44:17,092) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:44:17,171) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:44:17,172) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:44:17,172) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:44:17,219) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:44:17,250) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:44:17,335) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:44:17,335) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:44:17,363) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x1260a3b90>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:44:25,137) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:44:25,138) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:44:25,138) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:44:25,154) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:44:25,155) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:44:25,155) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:44:25,234) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:44:25,234) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:44:25,235) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:44:25,281) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:44:25,312) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:44:25,398) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:44:25,398) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:44:25,427) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x12a0eb6b0>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:44:35,169) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:44:35,170) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:44:35,171) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:44:35,187) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:44:35,188) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:44:35,189) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:44:35,275) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:44:35,276) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:44:35,277) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:44:35,329) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:44:35,364) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:44:35,461) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:44:35,461) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:44:35,494) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x152e1bb90>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:44:46,154) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:44:46,155) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:44:46,155) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[75891:MainThread](2026-10-10 00:44:46,173) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:44:46,174) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:44:46,174) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:44:46,255) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:44:46,255) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:44:46,256) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[75891:MainThread](2026-10-10 00:44:46,303) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[75891:MainThread](2026-10-10 00:44:46,334) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[75891:MainThread](2026-10-10 00:44:46,423) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[75891:MainThread](2026-10-10 00:44:46,423) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[75891:MainThread](2026-10-10 00:44:46,452) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x1255203b0>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[75891:MainThread](2026-10-10 00:44:54,505) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[75891:MainThread](2026-10-10 00:44:54,506) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[75891:MainThread](2026-10-10 00:44:54,506) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[75891:MainThread](2026-10-10 00:44:54,508) WARNING - qlib.workflow - [expm.py:231] - No valid experiment found. Create a new experiment with name stage1_feasible_action_training_20261009.

[75891:MainThread](2026-10-10 00:44:54,510) INFO - qlib.workflow - [exp.py:258] - Experiment 485650054674319224 starts running ...

[75891:MainThread](2026-10-10 00:44:54,606) INFO - qlib.workflow - [recorder.py:345] - Recorder e4d888a42c914bf69660ab78a35ba6e7 starts running under Experiment 485650054674319224 ...

[75891:MainThread](2026-10-10 00:44:57,244) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

decision: feasible_action_domain_contrast_reported | control_reproduction: True
native: passed boundary: 2018-12-31
recorder: e4d888a42c914bf69660ab78a35ba6e7
model inventory: {'control_all_state': 10, 'candidate_feasible': 10, 'control_reproduction': None}

In [3]:
import pandas as pd
display(pd.read_csv(CARD/'feasible_action_comparison.csv').round(2))
print('=== SOXX buy-hold (real cost) ===')
display(pd.read_csv(CARD/'soxx_benchmark.csv').round(2))
print('=== gates ===')
display(pd.read_csv(CARD/'gate_results.csv'))

,variant,segment,cost_bps,terminal_wealth,return_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,worst_rolling_5d_pct,total_turnover,open_trade_days,recovery_action_count,avg_cash_weight_pct
0,control_all_state,development_walk_forward,10.0,3.00,200.46,-29.03,-7.46,-3.06,-10.82,46.65,638,0,57.84
1,control_all_state,development_walk_forward,25.0,2.61,160.83,-30.18,-8.26,-3.08,-10.99,49.02,650,0,58.68
2,control_all_state,outer_reused_diagnostic,10.0,4.63,362.93,-26.48,-8.73,-4.77,-14.55,44.80,558,0,51.71
3,control_all_state,outer_reused_diagnostic,25.0,4.25,324.74,-26.85,-8.78,-4.69,-14.63,41.69,537,0,53.04
4,candidate_feasible,development_walk_forward,10.0,3.13,213.48,-29.79,-8.23,-3.35,-10.82,57.25,750,0,55.38
5,candidate_feasible,development_walk_forward,25.0,4.00,300.49,-29.48,-7.93,-3.51,-10.99,60.04,810,0,50.38
6,candidate_feasible,outer_reused_diagnostic,10.0,2.63,163.17,-26.26,-8.71,-4.45,-14.55,41.76,518,0,56.64
7,candidate_feasible,outer_reused_diagnostic,25.0,3.56,256.31,-26.65,-8.75,-4.67,-14.63,44.19,570,0,50.41
8,active_hold_baseline,development_walk_forward,10.0,2.15,114.59,-30.08,-7.11,-3.49,-10.82,102.87,1457,3,54.66
9,no_hold_reference,development_walk_forward,10.0,2.18,118.19,-29.93,-7.11,-3.47,-10.82,107.62,1721,3,54.09
10,cash_reference,development_walk_forward,10.0,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0,0,100.00
11,active_hold_baseline,development_walk_forward,25.0,1.97,96.72,-30.09,-7.12,-3.59,-11.89,114.42,1478,3,53.12
12,no_hold_reference,development_walk_forward,25.0,2.02,102.23,-30.13,-7.12,-3.58,-11.89,112.03,1724,3,53.36
13,cash_reference,development_walk_forward,25.0,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0,0,100.00
14,active_hold_baseline,outer_reused_diagnostic,10.0,3.19,219.49,-26.92,-8.70,-4.80,-14.55,57.43,796,0,48.40
15,no_hold_reference,outer_reused_diagnostic,10.0,3.20,220.43,-26.92,-8.70,-4.81,-14.55,59.54,918,0,48.22
16,cash_reference,outer_reused_diagnostic,10.0,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0,0,100.00
17,active_hold_baseline,outer_reused_diagnostic,25.0,1.75,75.14,-32.38,-11.20,-4.42,-14.64,50.61,751,0,58.55
18,no_hold_reference,outer_reused_diagnostic,25.0,1.66,66.12,-36.44,-11.20,-4.40,-14.64,46.93,923,0,59.25
19,cash_reference,outer_reused_diagnostic,25.0,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0,0,100.00

=== SOXX buy-hold (real cost) ===

,benchmark,segment,sessions,gross_return_pct,gross_max_drawdown_pct,cost_model,net10_return_pct,net25_return_pct
0,SOXX_buy_hold_open_to_open,development_walk_forward,1756,320.42,-47.37,"fund SOXX from cash at the first open, hold to...",320.00,319.37
1,SOXX_buy_hold_open_to_open,outer_reused_diagnostic,934,398.59,-42.79,"fund SOXX from cash at the first open, hold to...",398.09,397.34

=== gates ===

,candidate,reference,status,minimum_annual_wealth_ratio,development_return_above_baseline,stress_25bps_return_above_baseline,max_drawdown_not_worse,worst_day_not_worse,cvar5_not_worse,worst_5d_not_worse,open_trade_days_reduced_8pct,turnover_not_increased,annual_wealth_floor_pass,all_pass,gross_soxx_return_pct
0,candidate_feasible,no_hold_reference,ok,0.809349,True,True,True,False,True,True,True,True,False,False,320.42285
1,candidate_feasible,active_hold_baseline,ok,0.808470,True,True,True,False,True,True,True,True,False,False,320.42285

In [4]:
print('empirical prior:', summary['empirical_prior'])
print('provider freeze:', {k:v['manifest_sha256'][:12] for k,v in summary['provider_freeze'].items()})

empirical prior: {'feasible_share': 0.8609665427509293, 'note': "illegal rows have lower label variance and ~5% of the top decile; the strong 'illegal rows dominate the extremes' premise is NOT supported", 'framing': 'pre-declared decision-time legality contrast, not proof that filtering removes noise'}
provider freeze: {'intraday_provider': 'fb6afd75ea12', 'execution_mark_provider': 'd565935ca518', 'coherent_provider': '48ec582f748d'}

## 中文结论

In [5]:
from IPython.display import Markdown, display
display(Markdown((CARD/'conclusion.md').read_text()))

# Stage1 feasible-action 训练域对照（中文结论）
- 做了什么：同一统一 vintage 冻结 coherent 输入上，1 个预声明候选（feasible 域）与 all-state 对照；超参、label fee、minrows、硬修复规则全不变；不调参、不搜阈值。
- plan sha `78f053b70475`；控制复现（filter=all == 封存 control）：True。
- legacy identity parity（original frame + same legacy models/spec vs 源 17，逐日）：passed。若一致，则 uniform 与源 17 的 active/no_hold 差异来自**输入 vintage 敏感性**（legacy state feedback），不能笼统说“价格影响近零”：economic control 在同价路径变化小只是其特性，不等于所有策略路径不敏感。
- baseline 身份：`no_hold_reference`=禁用开盘 HOLD 动作层、始终执行合法上游目标；`active_hold_baseline`=legacy rules-only；`cash_reference`=显式全现金（**不是** no_hold）。
- 前提校正：实证 feasible 比例 0.8610，非法行 label 方差更低、极端 top-decile 仅约 5% —— “非法样本主导极值”的强假设**不成立**；本卡是预声明合法性对照，**不能**把过滤说成已知解决噪声。
### 结果（按 segment × cost 分组）
- control_all_state development_walk_forward @10bp：200.46% / MaxDD -29.03% / CVaR -3.06%
- control_all_state development_walk_forward @25bp：160.83% / MaxDD -30.18% / CVaR -3.08%
- control_all_state outer_reused_diagnostic @10bp：362.93% / MaxDD -26.48% / CVaR -4.77%
- control_all_state outer_reused_diagnostic @25bp：324.74% / MaxDD -26.85% / CVaR -4.69%
- candidate_feasible development_walk_forward @10bp：213.48% / MaxDD -29.79% / CVaR -3.35%
- candidate_feasible development_walk_forward @25bp：300.49% / MaxDD -29.48% / CVaR -3.51%
- candidate_feasible outer_reused_diagnostic @10bp：163.17% / MaxDD -26.26% / CVaR -4.45%
- candidate_feasible outer_reused_diagnostic @25bp：256.31% / MaxDD -26.65% / CVaR -4.67%
- active_hold_baseline development_walk_forward @10bp：114.59% / MaxDD -30.08% / CVaR -3.49%
- no_hold_reference development_walk_forward @10bp：118.19% / MaxDD -29.93% / CVaR -3.47%
- cash_reference development_walk_forward @10bp：0.00% / MaxDD 0.00% / CVaR 0.00%
- active_hold_baseline development_walk_forward @25bp：96.72% / MaxDD -30.09% / CVaR -3.59%
- no_hold_reference development_walk_forward @25bp：102.23% / MaxDD -30.13% / CVaR -3.58%
- cash_reference development_walk_forward @25bp：0.00% / MaxDD 0.00% / CVaR 0.00%
- active_hold_baseline outer_reused_diagnostic @10bp：219.49% / MaxDD -26.92% / CVaR -4.80%
- no_hold_reference outer_reused_diagnostic @10bp：220.43% / MaxDD -26.92% / CVaR -4.81%
- cash_reference outer_reused_diagnostic @10bp：0.00% / MaxDD 0.00% / CVaR 0.00%
- active_hold_baseline outer_reused_diagnostic @25bp：75.14% / MaxDD -32.38% / CVaR -4.42%
- no_hold_reference outer_reused_diagnostic @25bp：66.12% / MaxDD -36.44% / CVaR -4.40%
- cash_reference outer_reused_diagnostic @25bp：0.00% / MaxDD 0.00% / CVaR 0.00%
### SOXX buy-hold（真实成本，无终值假设卖出）
- development_walk_forward：gross 320.42% / net10 320.00% / net25 319.37%
- outer_reused_diagnostic：gross 398.59% / net10 398.09% / net25 397.34%
### 50:50 实际再平衡费用对照
- development_walk_forward @10bp：net 581.38%
- development_walk_forward @25bp：net 555.26%
- outer_reused_diagnostic @10bp：net 1017.13%
- outer_reused_diagnostic @25bp：net 988.73%
- native：status=`passed`，boundary=`2018-12-31`；target convention：{'control_all_state': 'post_fee_desired', 'candidate_feasible': 'post_fee_desired', 'active_hold_baseline': 'pre_fee_account', 'no_hold_reference': 'pre_fee_account', 'cash_reference': 'trivial_never_trades'}；commission/1：{10: 0.001, 25: 0.0025}。control/candidate 默认 postFee 完整对账；active/no_hold 为 pre_fee_account，待根接口 `target_convention` 就绪后完整复跑，现标 blocked 并保留精确原因（非不可验证）。
- 报告纪律：未超过 gross SOXX 不宣称稳定超额；失败项如实保留。
- 子 Recorder：e4d888a42c914bf69660ab78a35ba6e7；保存全部 annual models/scaler/legality flag/maturity/predictions/labels/native reports/positions。