# SOXL 3x状态因子实验

检验有方向路径效率、保持度期限曲率、SOXL自身跟踪误差波动、VIX与实现波动发散和冲击集中度。候选选择只使用2010–2022开发期；2023–2026只作已查看的诊断。

In [1]:
from pathlib import Path
import sys

import pandas as pd
import qlib
from qlib.config import REG_US
from qlib.data import D
from qlib.data.dataset import DatasetH
from qlib.workflow import R
from IPython.display import Markdown, display

repo_root = Path.cwd().resolve().parents[1]
sys.path.insert(0, str(repo_root))
from src.workflow.soxl_3x_state_factor_lab import run_soxl_3x_state_factor_lab_card

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

In [2]:
provider_uri = repo_root / 'data' / 'qlib' / 'soxl'
qlib.init(provider_uri=str(provider_uri), region=REG_US, kernels=1)
calendar = D.calendar(freq='day')
source_check = D.features(
    ['SOXL', 'SOXX'],
    ['$close', '$vix'],
    start_time='2010-03-11',
    end_time=str(pd.Timestamp(calendar[-1]).date()),
    freq='day',
)
{'calendar_rows': len(calendar), 'feature_rows': len(source_check)}

[98256:MainThread](2026-07-29 21:45:46,738) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[98256:MainThread](2026-07-29 21:45:46,739) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[98256:MainThread](2026-07-29 21:45:46,740) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

{'calendar_rows': 4120, 'feature_rows': 8240}

In [3]:
summary = run_soxl_3x_state_factor_lab_card(root=repo_root)
card = repo_root / 'research' / summary['experiment']
display(pd.read_csv(card / 'model_selection.csv'))
display(pd.read_csv(card / 'outer_diagnostic.csv'))
{
    'decision': summary['decision'],
    'promotion': summary['promotion'],
    'recorder_id': summary['recorder_id'],
}

[98256:MainThread](2026-07-29 21:45:46,756) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[98256:MainThread](2026-07-29 21:45:46,757) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[98256:MainThread](2026-07-29 21:45:46,757) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[98256:MainThread](2026-07-29 21:45:46,760) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[98256:MainThread](2026-07-29 21:45:46,761) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[98256:MainThread](2026-07-29 21:45:46,761) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[98256:MainThread](2026-07-29 21:45:46,786) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[98256:MainThread](2026-07-29 21:45:46,786) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[98256:MainThread](2026-07-29 21:45:46,786) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[98256:MainThread](2026-07-29 21:45:47,051) INFO - qlib.workflow - [exp.py:258] - Experiment 599514091110635178 starts running ...

[98256:MainThread](2026-07-29 21:45:47,115) INFO - qlib.workflow - [recorder.py:345] - Recorder 0de3486744d5407586c91e88dd8a568d starts running under Experiment 599514091110635178 ...

[98256:MainThread](2026-07-29 21:45:47,197) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

,candidate,role,target,mean_candidate_overlap_spearman,mean_candidate_nonoverlap_spearman,mean_incremental_overlap_spearman,mean_incremental_nonoverlap_spearman,positive_candidate_overlap_folds,positive_candidate_nonoverlap_folds,positive_overlap_folds,positive_nonoverlap_folds,total_folds,development_gate_pass,promotion
0,signed_path_efficiency_21,alpha,future_relative_excess_21,0.022180,0.006536,0.042751,0.052615,1,1,3,3,3,False,blocked_not_stable_incremental
1,retention_curve_curvature_5_21_63,alpha,future_relative_excess_21,-0.029969,-0.030570,-0.009398,0.015509,1,1,2,2,3,False,blocked_not_stable_incremental
2,retention_slope_5,alpha,future_relative_excess_21,-0.032861,-0.057533,-0.012290,-0.011454,1,1,1,0,3,False,blocked_not_stable_incremental
3,soxl_tracking_error_vol_21,retention_guardrail,future_actual_3x_residual_log_21,0.475731,0.517133,-0.016106,-0.003951,3,3,1,2,3,False,blocked_not_stable_incremental
4,vix_rvol_divergence_21,risk,future_soxl_worst_return_21,-0.030328,-0.037163,-0.023570,0.022326,2,2,2,3,3,False,blocked_not_stable_incremental
5,shock_concentration_21,risk,future_soxl_worst_return_21,0.026636,0.059332,0.033394,0.118820,2,2,2,2,3,False,blocked_not_stable_incremental

,candidate,role,target,selection_uses_outer,sample,rows,baseline_spearman,candidate_spearman,incremental_spearman
0,signed_path_efficiency_21,alpha,future_relative_excess_21,False,overlap,873,0.013540,-0.121050,-0.134590
1,signed_path_efficiency_21,alpha,future_relative_excess_21,False,nonoverlap,42,0.249818,0.121951,-0.127866
2,retention_curve_curvature_5_21_63,alpha,future_relative_excess_21,False,overlap,873,0.013540,0.018248,0.004708
3,retention_curve_curvature_5_21_63,alpha,future_relative_excess_21,False,nonoverlap,42,0.249818,0.212057,-0.037760
4,retention_slope_5,alpha,future_relative_excess_21,False,overlap,873,0.013540,0.007229,-0.006311
5,retention_slope_5,alpha,future_relative_excess_21,False,nonoverlap,42,0.249818,0.245766,-0.004052
6,soxl_tracking_error_vol_21,retention_guardrail,future_actual_3x_residual_log_21,False,overlap,873,0.415827,0.442770,0.026943
7,soxl_tracking_error_vol_21,retention_guardrail,future_actual_3x_residual_log_21,False,nonoverlap,42,0.579126,0.591119,0.011993
8,vix_rvol_divergence_21,risk,future_soxl_worst_return_21,False,overlap,873,0.098925,0.229028,0.130103
9,vix_rvol_divergence_21,risk,future_soxl_worst_return_21,False,nonoverlap,42,0.065878,0.120817,0.054939
10,shock_concentration_21,risk,future_soxl_worst_return_21,False,overlap,873,0.098925,0.148921,0.049996
11,shock_concentration_21,risk,future_soxl_worst_return_21,False,nonoverlap,42,0.065878,0.333928,0.268050

{'decision': 'no_stable_incremental_candidate',
 'promotion': 'blocked_pending_new_forward_paper',
 'recorder_id': '0de3486744d5407586c91e88dd8a568d'}

In [4]:
display(Markdown((card / 'conclusion.md').read_text(encoding='utf-8')))

# 中文结论

- 做了什么：使用qlib SOXL/SOXX/VIX日线、DatasetH、DataHandlerLP和Recorder，检验有方向路径效率、3x保持度曲率、保持度斜率、SOXL自身跟踪误差波动、VIX与实现波动发散、单日冲击集中度六个预先定义候选。
- 时间纪律：候选选择只使用2010–2022开发期；三个扩展时间折的训练端各剔除最后21个交易日，主指标使用互不重叠的21日样本。2023–2026只作已查看的诊断，不参与选择。
- 开发期通过候选：无。通过只代表可以进入前向paper，不代表可以修改生产仓位。
- 有方向路径效率：对未来21日SOXL相对SOXX超额的平均增量Spearman为0.043（重叠）和0.053（非重叠），非重叠正增益时间折为3/3；但候选模型本身的非重叠平均Spearman仅0.007，只有1/3个时间折为正，且2023–2026诊断区间增量为-0.128，因此不通过。
- 3x保持度曲率：非重叠平均增量为0.016，正增益时间折为2/3；未满足完整门槛时只保留研究价值。
- SOXL自身跟踪误差波动：对未来3x保持度的非重叠平均增量为-0.004。2023–2026诊断增量为0.012。它的单变量关系会被VIX和SOXX实现波动基线吸收，保留为产品异常监控，不作为alpha。
- VIX与实现波动发散：对未来SOXL最差21日路径的非重叠平均增量为0.022；冲击集中度为0.119。若重叠与非重叠或时间折不一致，则只允许风险paper观察。
- 当前状态：有方向路径效率为-0.267，21日保持度Z分数为-1.912，VIX与实现波动发散为-1.246。当前不是干净的正向杠杆路径，且VIX相对SOXX已实现波动偏低；这只是状态描述，不是交易信号。
- 决策：no_stable_incremental_candidate；生产晋升为blocked_pending_new_forward_paper。现有Stage1和模拟盘逻辑不变。
- qlib recorder：0de3486744d5407586c91e88dd8a568d。
- 风险：outer已被反复查看，不是clean holdout；候选较多存在多重检验风险；Spearman改善不等于扣除成本后的组合收益；未来风险目标越高表示回撤越轻。
- 下一步：从2026-07-29开始只做观察性前向记录，不把任何候选接入仓位；至少积累多个互不重叠21日窗口后，重新检查有方向路径效率的符号反转和跟踪误差波动的增量价值。
- 不构成买卖建议。