# multi_3x_etf_normalized_lgb_xgb_nested_wf_v1

Hypothesis: if SOXL-only history is too small, train pooled LGB/XGB models on normalized 3x ETF data, reject manual regime templates, and validate SOXL with nested outer-year walk-forward.

In [1]:
from pathlib import Path
import json
import sys

import pandas as pd
import qlib
from qlib.data import D
from qlib.workflow import R

ROOT_CANDIDATES = [Path.cwd().resolve(), Path("/Users/rziiiii/dev/workspace")]
ROOT = next(
    path
    for path in ROOT_CANDIDATES
    if (path / "AGENTS.md").exists() and (path / "SPEC.md").exists()
)
if ROOT.as_posix() not in sys.path:
    sys.path.insert(0, ROOT.as_posix())

from src.workflow.multi_3x_etf_normalized_nested_wf import (
    Multi3xEtfNormalizedNestedWfSpec,
    run_multi_3x_etf_normalized_nested_wf_card,
)

spec = Multi3xEtfNormalizedNestedWfSpec(root=ROOT)
summary = run_multi_3x_etf_normalized_nested_wf_card(root=ROOT)
summary["promotion_decision"], summary["overfit_audit"]["overfit_risk_status"]

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[14063:MainThread](2026-07-06 10:55:42,793) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[14063:MainThread](2026-07-06 10:55:42,794) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[14063:MainThread](2026-07-06 10:55:42,795) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[14063:MainThread](2026-07-06 10:55:42,799) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[14063:MainThread](2026-07-06 10:55:42,800) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[14063:MainThread](2026-07-06 10:55:42,800) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[14063:MainThread](2026-07-06 10:55:42,822) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[14063:MainThread](2026-07-06 10:55:42,822) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[14063:MainThread](2026-07-06 10:55:42,822) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/tqqq')}

[14063:MainThread](2026-07-06 10:55:42,826) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[14063:MainThread](2026-07-06 10:55:42,827) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[14063:MainThread](2026-07-06 10:55:42,827) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/tqqq')}

[14063:MainThread](2026-07-06 10:55:42,842) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[14063:MainThread](2026-07-06 10:55:42,843) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[14063:MainThread](2026-07-06 10:55:42,843) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/upro')}

[14063:MainThread](2026-07-06 10:55:42,846) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[14063:MainThread](2026-07-06 10:55:42,847) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[14063:MainThread](2026-07-06 10:55:42,847) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/upro')}

[14063:MainThread](2026-07-06 10:55:42,863) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[14063:MainThread](2026-07-06 10:55:42,863) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[14063:MainThread](2026-07-06 10:55:42,863) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/spxl')}

[14063:MainThread](2026-07-06 10:55:42,867) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[14063:MainThread](2026-07-06 10:55:42,868) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[14063:MainThread](2026-07-06 10:55:42,868) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/spxl')}

[14063:MainThread](2026-07-06 10:55:42,882) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[14063:MainThread](2026-07-06 10:55:42,883) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[14063:MainThread](2026-07-06 10:55:42,883) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/tecl')}

[14063:MainThread](2026-07-06 10:55:42,887) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[14063:MainThread](2026-07-06 10:55:42,887) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[14063:MainThread](2026-07-06 10:55:42,888) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/tecl')}

[14063:MainThread](2026-07-06 10:56:06,535) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[14063:MainThread](2026-07-06 10:56:06,536) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[14063:MainThread](2026-07-06 10:56:06,536) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/multi_3x_etf_normalized_lgb_xgb_nested_wf_v1')}

[14063:MainThread](2026-07-06 10:56:06,622) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[14063:MainThread](2026-07-06 10:56:06,623) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[14063:MainThread](2026-07-06 10:56:06,623) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/multi_3x_etf_normalized_lgb_xgb_nested_wf_v1')}

[14063:MainThread](2026-07-06 10:56:06,626) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[14063:MainThread](2026-07-06 10:56:06,627) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[14063:MainThread](2026-07-06 10:56:06,627) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/multi_3x_etf_normalized_lgb_xgb_nested_wf_v1')}

[14063:MainThread](2026-07-06 10:56:06,728) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[14063:MainThread](2026-07-06 10:56:06,728) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[14063:MainThread](2026-07-06 10:56:06,729) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/multi_3x_etf_normalized_lgb_xgb_nested_wf_v1')}

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[14063:MainThread](2026-07-06 10:56:43,622) INFO - qlib.workflow - [exp.py:258] - Experiment 131586310185865379 starts running ...

[14063:MainThread](2026-07-06 10:56:43,680) INFO - qlib.workflow - [recorder.py:345] - Recorder 3f73ff5d9e2447fabec5c9bbe3968eb3 starts running under Experiment 131586310185865379 ...

[14063:MainThread](2026-07-06 10:56:43,776) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

('not_promoted_multi_3x_nested_wf_goal_or_overfit_audit_failed', 'mitigated')

In [2]:
qlib.init(
    provider_uri=summary["provider_uri"],
    region="us",
    expression_cache=None,
    dataset_cache=None,
)
calendar = D.calendar(start_time=spec.train_start, end_time=summary["common_data_end"], freq="day")
feature_sample = D.features(
    ["SOXL", "TQQQ", "UPRO", "SPXL", "TECL"],
    ["$open_to_open_return", "$ret_20_z20", "$drawdown_60_pctile60", "$tracking_error_20_z60"],
    start_time="2026-01-02",
    end_time=summary["common_data_end"],
    freq="day",
)
len(calendar), calendar[0], calendar[-1], feature_sample.tail()

[14063:MainThread](2026-07-06 10:56:43,784) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[14063:MainThread](2026-07-06 10:56:43,785) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[14063:MainThread](2026-07-06 10:56:43,785) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/multi_3x_etf_normalized_lgb_xgb_nested_wf_v1')}

(3841,
 Timestamp('2011-01-03 00:00:00'),
 Timestamp('2026-04-13 00:00:00'),
                        $open_to_open_return  $ret_20_z20  \
 instrument datetime
 UPRO       2026-04-07             -0.006624     0.752794
            2026-04-08              0.027971     2.063833
            2026-04-09             -0.017389     2.122570
            2026-04-10                   NaN     2.329863
            2026-04-13                   NaN     2.198812

                        $drawdown_60_pctile60  $tracking_error_20_z60
 instrument datetime
 UPRO       2026-04-07               0.200000               -0.485676
            2026-04-08               0.333333               -0.172448
            2026-04-09               0.400000               -0.532927
            2026-04-10               0.383333               -1.980624
            2026-04-13               0.433333                0.192530  )

In [3]:
card = spec.card_dir
annual = pd.read_csv(card / summary["sidecars"]["annual_walk_forward"])
inner = pd.read_csv(card / summary["sidecars"]["inner_selection"])
risk = pd.read_csv(card / summary["sidecars"]["risk_analysis"])
display(annual[[
    "outer_test_year",
    "candidate",
    "test_return_pct",
    "test_max_drawdown_pct",
    "test_avg_abs_position",
    "buyhold_return_pct",
    "buyhold_max_drawdown_pct",
    "test_passes_target",
]])
display(inner.groupby(["outer_test_year", "candidate"])["selection_return_pct"].mean().unstack())
display(risk)

,outer_test_year,candidate,test_return_pct,test_max_drawdown_pct,test_avg_abs_position,buyhold_return_pct,buyhold_max_drawdown_pct,test_passes_target
0,2023,xgb_opp_tail_p55_t45,2.615809,-8.824312,0.059675,169.129684,-48.910748,False
1,2024,xgb_opp_tail_p55_t45,1.919770,-7.442838,0.061894,6.506205,-66.404808,False
2,2025,xgb_opp_tail_p55_t45,12.087154,-10.305059,0.073393,77.789459,-77.447060,False
3,2026,lgbm_opp_tail_p55_t45,11.663990,-1.728966,0.063814,50.129116,-39.631111,False

candidate,consensus_opp_tail_p55_t45,lgbm_opp_tail_p55_t45,xgb_opp_tail_p55_t45
outer_test_year,,,
2023,6.125642,6.944703,4.760808
2024,2.286404,2.699278,1.538852
2025,5.419878,5.352845,5.534596
2026,5.605877,5.880414,5.225595

,check,status,detail
0,overfit_audit,mitigated,"{""blocking_reasons"": [""ok""], ""experiment"": ""mu..."
1,annual_goal,fail,"{""blocking_reasons"": [""annual_target_gate_fail..."
2,prior_template_v2,fail,"{""blocking_reasons"": [""manual_template_selecti..."

## 中文结论

- 本轮不再选择人工模板；SOXL/TQQQ/UPRO/SPXL/TECL 先转成每个资产自己的 rolling z-score/percentile 特征，再 pooled 训练 LGB/XGB/consensus。
- 外层 SOXL 年份只用于最终报告，内层用 multi-asset leave-one-asset-out 选择候选；`selection_uses_outer_test=false`，`overfit_audit=mitigated`。
- 结果没有晋升：2023-2026 没有任何一年同时超过 SOXL buy-and-hold open-to-open 且回撤大于 -20%。失败主因不是回撤，而是模型把外层 SOXL 仓位压到约 6%-7%，收益显著低于 buy-and-hold。
- 这说明“补其他 3x ETF + 归一化 pooled LGB/XGB”是更正确的验证方向，但当前候选空间还没有达到目标，不能当作实盘模型。
- 下一步应预注册更多 3x ETF、扩大但固定候选仓位映射/风险预算，并继续 nested walk-forward；不能回到按年份挑模板。
- 不构成买卖建议。