# 稳定超额研究：基准风险预算与信息增量

这是同一未完成目标的下一阶段。上一批高收益伴随更高市场风险，本次把基准风险预算放入训练和推理，并加入无市场信号对照。失败的一轮不会被记作目标完成。选择计划在本轮结果前冻结。

In [1]:
import os,sys
from pathlib import Path
os.environ["MLFLOW_ALLOW_FILE_STORE"]="true"
os.environ["MLFLOW_DISABLE_AGENT_HINT"]="1"
root=Path.cwd().resolve()
while not (root/"AGENTS.md").exists(): root=root.parent
sys.path.insert(0,str(root))
import qlib
from qlib.data import D
from qlib.workflow import R
qlib.init(provider_uri=str(root/"data/qlib/stable_excess_integration_20261002"),region="us",kernels=1)
print("Frozen Qlib calendar:",D.calendar(freq="day")[-1])

[63613:MainThread](2026-10-02 18:43:14,468) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[63613:MainThread](2026-10-02 18:43:14,470) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[63613:MainThread](2026-10-02 18:43:14,470) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/benchmark-risk-excess-20261002/data/qlib/stable_excess_integration_20261002')}

Frozen Qlib calendar: 2026-09-25 00:00:00

In [2]:
from src.workflow.benchmark_risk_excess import run_experiment
summary=run_experiment(root=root)
summary

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[63613:MainThread](2026-10-02 18:43:15,784) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[63613:MainThread](2026-10-02 18:43:15,785) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[63613:MainThread](2026-10-02 18:43:15,785) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/benchmark-risk-excess-20261002/data/qlib/stable_excess_integration_20261002')}

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[63613:MainThread](2026-10-02 18:43:15,852) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:15,852) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:15,852) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:15,858) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:15,858) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:15,858) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,013) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,014) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,014) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,022) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,022) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,022) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,030) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,031) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,031) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,039) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,039) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,039) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,047) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,047) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,048) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,056) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,056) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,056) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,064) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,064) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,065) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,073) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,074) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,074) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,082) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,082) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,082) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,090) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,090) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,091) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,099) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,099) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,099) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,107) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,107) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,107) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,115) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,115) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,116) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,123) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,124) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,124) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,132) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,132) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,132) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,158) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,159) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,159) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,184) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,184) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,184) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,209) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,209) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,209) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,233) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,234) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,234) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,260) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,260) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,260) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,286) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,286) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,286) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,312) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,312) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,313) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,320) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,321) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,321) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,329) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,329) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,329) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,337) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,337) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,337) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,345) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,345) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,346) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,353) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,354) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,354) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:43:16,361) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:43:16,362) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:43:16,362) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

Risk-budget fit constant_budget seed=41 year=2016 seconds=3.9
Risk-budget fit constant_budget seed=71 year=2016 seconds=3.9
Risk-budget fit constant_budget seed=17 year=2016 seconds=3.9

Risk-budget fit constant_budget seed=41 year=2017 seconds=3.6
Risk-budget fit constant_budget seed=71 year=2017 seconds=3.6
Risk-budget fit constant_budget seed=17 year=2017 seconds=3.6

Risk-budget fit constant_budget seed=41 year=2018 seconds=3.6
Risk-budget fit constant_budget seed=71 year=2018 seconds=3.6
Risk-budget fit constant_budget seed=17 year=2018 seconds=3.6

Risk-budget fit constant_budget seed=41 year=2019 seconds=3.6
Risk-budget fit constant_budget seed=71 year=2019 seconds=3.6
Risk-budget fit constant_budget seed=17 year=2019 seconds=3.6

Risk-budget fit constant_budget seed=71 year=2020 seconds=3.6
Risk-budget fit constant_budget seed=41 year=2020 seconds=3.6
Risk-budget fit constant_budget seed=17 year=2020 seconds=3.6

Risk-budget fit constant_budget seed=71 year=2021 seconds=3.5
Risk-budget fit constant_budget seed=41 year=2021 seconds=3.5
Risk-budget fit constant_budget seed=17 year=2021 seconds=3.5

Risk-budget fit constant_budget seed=41 year=2022 seconds=3.6
Risk-budget fit constant_budget seed=17 year=2022 seconds=3.6
Risk-budget fit constant_budget seed=71 year=2022 seconds=3.6

Risk-budget fit base_budget seed=71 year=2016 seconds=3.7
Risk-budget fit base_budget seed=17 year=2016 seconds=3.7
Risk-budget fit base_budget seed=41 year=2016 seconds=3.8

Risk-budget fit base_budget seed=71 year=2017 seconds=3.7
Risk-budget fit base_budget seed=17 year=2017 seconds=3.7
Risk-budget fit base_budget seed=41 year=2017 seconds=3.7

Risk-budget fit base_budget seed=71 year=2018 seconds=3.6
Risk-budget fit base_budget seed=17 year=2018 seconds=3.6
Risk-budget fit base_budget seed=41 year=2018 seconds=3.6

Risk-budget fit base_budget seed=41 year=2019 seconds=3.7
Risk-budget fit base_budget seed=71 year=2019 seconds=3.7
Risk-budget fit base_budget seed=17 year=2019 seconds=3.7

Risk-budget fit base_budget seed=41 year=2020 seconds=3.7
Risk-budget fit base_budget seed=71 year=2020 seconds=3.7
Risk-budget fit base_budget seed=17 year=2020 seconds=3.7

Risk-budget fit base_budget seed=41 year=2021 seconds=3.7
Risk-budget fit base_budget seed=71 year=2021 seconds=3.7
Risk-budget fit base_budget seed=17 year=2021 seconds=3.7

Risk-budget fit base_budget seed=41 year=2022 seconds=3.7
Risk-budget fit base_budget seed=71 year=2022 seconds=3.7
Risk-budget fit base_budget seed=17 year=2022 seconds=3.7

Risk-budget fit pit_budget seed=17 year=2016 seconds=3.5
Risk-budget fit pit_budget seed=41 year=2016 seconds=3.6
Risk-budget fit pit_budget seed=71 year=2016 seconds=3.6

Risk-budget fit pit_budget seed=17 year=2017 seconds=3.7
Risk-budget fit pit_budget seed=41 year=2017 seconds=3.7
Risk-budget fit pit_budget seed=71 year=2017 seconds=3.7

Risk-budget fit pit_budget seed=17 year=2018 seconds=3.7
Risk-budget fit pit_budget seed=71 year=2018 seconds=3.7
Risk-budget fit pit_budget seed=41 year=2018 seconds=3.7

Risk-budget fit pit_budget seed=17 year=2019 seconds=3.7
Risk-budget fit pit_budget seed=41 year=2019 seconds=3.7
Risk-budget fit pit_budget seed=71 year=2019 seconds=3.7

Risk-budget fit pit_budget seed=17 year=2020 seconds=3.6
Risk-budget fit pit_budget seed=71 year=2020 seconds=3.6
Risk-budget fit pit_budget seed=41 year=2020 seconds=3.6

Risk-budget fit pit_budget seed=17 year=2021 seconds=3.8
Risk-budget fit pit_budget seed=71 year=2021 seconds=3.8
Risk-budget fit pit_budget seed=41 year=2021 seconds=3.8

Risk-budget fit pit_budget seed=17 year=2022 seconds=3.9
Risk-budget fit pit_budget seed=41 year=2022 seconds=3.9
Risk-budget fit pit_budget seed=71 year=2022 seconds=3.9

Risk-budget fit forecast_budget seed=17 year=2016 seconds=3.6
Risk-budget fit forecast_budget seed=41 year=2016 seconds=3.6
Risk-budget fit forecast_budget seed=71 year=2016 seconds=3.7

Risk-budget fit forecast_budget seed=17 year=2017 seconds=3.6
Risk-budget fit forecast_budget seed=41 year=2017 seconds=3.7
Risk-budget fit forecast_budget seed=71 year=2017 seconds=3.7

Risk-budget fit forecast_budget seed=17 year=2018 seconds=3.6
Risk-budget fit forecast_budget seed=41 year=2018 seconds=3.6

Risk-budget fit forecast_budget seed=71 year=2018 seconds=3.6

Risk-budget fit forecast_budget seed=17 year=2019 seconds=3.8
Risk-budget fit forecast_budget seed=41 year=2019 seconds=3.8

Risk-budget fit forecast_budget seed=71 year=2019 seconds=3.8

Risk-budget fit forecast_budget seed=17 year=2020 seconds=3.7
Risk-budget fit forecast_budget seed=41 year=2020 seconds=3.7

Risk-budget fit forecast_budget seed=71 year=2020 seconds=3.7

Risk-budget fit forecast_budget seed=17 year=2021 seconds=3.7

Risk-budget fit forecast_budget seed=41 year=2021 seconds=3.7
Risk-budget fit forecast_budget seed=71 year=2021 seconds=3.7

Risk-budget fit forecast_budget seed=17 year=2022 seconds=3.6
Risk-budget fit forecast_budget seed=41 year=2022 seconds=3.6

Risk-budget fit forecast_budget seed=71 year=2022 seconds=3.6

Phase2 development sealed: {'variant': 'constant_budget', 'historical_qualification_pass': False, 'passed_gates': 4, 'worst_annualized_lower_bound': -0.0497090247786306, 'worst_relative_wealth': 0.8261005376710694, 'positive_years_10bps': 1}

[63613:MainThread](2026-10-02 18:45:25,679) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:45:25,680) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:45:25,680) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:45:25,689) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:45:25,690) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:45:25,690) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:45:25,699) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:45:25,699) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:45:25,699) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[63613:MainThread](2026-10-02 18:45:25,708) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[63613:MainThread](2026-10-02 18:45:25,708) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[63613:MainThread](2026-10-02 18:45:25,709) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

Risk-budget fit constant_budget seed=41 year=2023 seconds=4.2
Risk-budget fit constant_budget seed=17 year=2023 seconds=4.2
Risk-budget fit constant_budget seed=71 year=2023 seconds=4.2

Risk-budget fit constant_budget seed=41 year=2024 seconds=3.5
Risk-budget fit constant_budget seed=17 year=2024 seconds=3.6
Risk-budget fit constant_budget seed=71 year=2024 seconds=3.6

Risk-budget fit constant_budget seed=41 year=2025 seconds=3.6
Risk-budget fit constant_budget seed=17 year=2025 seconds=3.6
Risk-budget fit constant_budget seed=71 year=2025 seconds=3.7

Risk-budget fit constant_budget seed=41 year=2026 seconds=3.6
Risk-budget fit constant_budget seed=17 year=2026 seconds=3.6

Risk-budget fit constant_budget seed=71 year=2026 seconds=3.7

[63613:MainThread](2026-10-02 18:45:46,248) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[63613:MainThread](2026-10-02 18:45:46,249) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[63613:MainThread](2026-10-02 18:45:46,249) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/benchmark-risk-excess-20261002/data/qlib/stable_excess_integration_20261002')}

[63613:MainThread](2026-10-02 18:45:46,261) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[63613:MainThread](2026-10-02 18:45:46,265) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[63613:MainThread](2026-10-02 18:45:46,272) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[63613:MainThread](2026-10-02 18:45:46,273) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[63613:MainThread](2026-10-02 18:45:46,276) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x1248e3aa0>

backtest loop:   0%|          | 0/1762 [00:00<?, ?it/s]

[63613:MainThread](2026-10-02 18:45:47,512) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[63613:MainThread](2026-10-02 18:45:47,512) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[63613:MainThread](2026-10-02 18:45:47,513) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/benchmark-risk-excess-20261002/data/qlib/stable_excess_integration_20261002')}

[63613:MainThread](2026-10-02 18:45:47,524) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[63613:MainThread](2026-10-02 18:45:47,529) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[63613:MainThread](2026-10-02 18:45:47,536) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[63613:MainThread](2026-10-02 18:45:47,537) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[63613:MainThread](2026-10-02 18:45:47,539) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x1249b1d30>

backtest loop:   0%|          | 0/1762 [00:00<?, ?it/s]

[63613:MainThread](2026-10-02 18:45:48,686) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[63613:MainThread](2026-10-02 18:45:48,687) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[63613:MainThread](2026-10-02 18:45:48,687) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/benchmark-risk-excess-20261002/data/qlib/stable_excess_integration_20261002')}

[63613:MainThread](2026-10-02 18:45:48,689) INFO - qlib.workflow - [exp.py:258] - Experiment 950261578068573590 starts running ...

[63613:MainThread](2026-10-02 18:45:48,769) INFO - qlib.workflow - [recorder.py:345] - Recorder bba55e94a1d04b4a9c68dca562766159 starts running under Experiment 950261578068573590 ...

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[63613:MainThread](2026-10-02 18:45:49,407) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

{'experiment': 'benchmark_risk_excess_20261002',
 'campaign_status': 'active_research',
 'objective_achieved': False,
 'decision': 'continue_research_no_historical_qualification',
 'selected': {'variant': 'constant_budget',
  'historical_qualification_pass': False,
  'passed_gates': 4,
  'worst_annualized_lower_bound': -0.0497090247786306,
  'worst_relative_wealth': 0.8261005376710694,
  'positive_years_10bps': 1},
 'plan_sha256': '81c0776c87661011b3dc7ab2c3e985257805ea5c9215758318833bc423d52716',
 'source_as_of': '2026-09-25',
 'source_recorder_id': 'b94059c2e0754b0ab102e4f62534eefb',
 'provider_uri': 'data/qlib/stable_excess_integration_20261002',
 'region': 'us',
 'market': 'all',
 'covariance_audit': {'estimator': 'expanding sample covariance ddof1',
  'price_mark': 'open',
  'last_observation': 'signal-day open, before signal close and next-open decision',
  'window_search': False,
  'future_return_labels_used': False,
  'roundoff_psd_repairs': 0,
  'source_price_sha256': '20b083cef05941c1cf698d15339ce084de8f64a7aea96cf164338682314b28de'},
 'source_sha256': {'src/model/benchmark_risk_allocation.py': '4f75ee19b3066fcfb23e139881c5caef009c90b0da92f109661371704243ace3',
  'src/workflow/benchmark_risk_excess.py': '26fcd325ca5cd20ed37eec9e8296b477eedc907e4c815af802d448236b5cdbcd',
  'src/model/integrated_allocation.py': '946f20b41afa528fef19562f696ccda81343a78dbade018d3371e18698d23f30',
  'src/data/integrated_allocation.py': '73f2495f6a9860860a76a5a8c2f679c42f5a76f089c10fb7d347ce66acc36e9c',
  'src/analysis/integrated_allocation.py': '534072ad69fb7c8f903afc6339f581d66d25e047102d05452b55490647985b56',
  'src/workflow/stable_excess_integration.py': '7753c5bc16dddda5758d6fe5609fa7be915c6484f05e1881989a67afdf17771c'},
 'historical_qualification_pass': False,
 'new_forward_qualified': False,
 'selection_uses_diagnostic_signal_years': False,
 'development_last_exit': '2023-01-04',
 'recorder_id': 'bba55e94a1d04b4a9c68dca562766159',
 'recorder_uri': '/Users/rziiiii/dev/workspace/research/benchmark_risk_excess_20261002/qlib_recorder',
 'recorder_local_dir': '/Users/rziiiii/dev/workspace/research/benchmark_risk_excess_20261002/qlib_recorder/950261578068573590/bba55e94a1d04b4a9c68dca562766159',
 'recorder_relative_dir': 'qlib_recorder/950261578068573590/bba55e94a1d04b4a9c68dca562766159',
 'native_qlib_audit': {'10': {'status': 'passed',
   'sessions': 1762,
   'start': '2016-01-05',
   'end': '2023-01-03',
   'provider_uri': '/Users/rziiiii/dev/workspace-worktrees/benchmark-risk-excess-20261002/data/qlib/stable_excess_integration_20261002',
   'cost_bps': 10.0,
   'initial_cash': 100000.0,
   'maximum_session_return_error': 3.2127325244601934e-08,
   'tolerance': 1e-07,
   'native_api': 'qlib.backtest.backtest + SimulatorExecutor + Exchange + Position',
   'schedule_strategy': 'DirectTargetWeightStrategy subclass with observed-open sizing and fee-affordable targets',
   'report_mark': 'native daily same-day close; next-open reconciliation uses native positions and Qlib D.features',
   'scope': 'complete prescribed daily target/HOLD schedule; actual Qlib Exchange, Position, report and next-open accounting',
   'execution_limitation': 'Observed historical opens and continuous adjusted shares; no claim of spread/impact/partial-fill evidence.',
   'policy_scope': 'continuous_three_asset_targets_without_legacy_allocation_caps',
   'legacy_controller_executed': False,
   'risk_annualization_sessions': 252,
   'native_close_anchored_max_drawdown_pct': -44.55187557495589,
   'native_open_to_open_anchored_max_drawdown_pct': -46.47357762843433,
   'risk_table_mark_convention': 'risk_analysis uses native close marks; risk_analysis_open_to_open uses native positions marked at the following open'},
  '25': {'status': 'passed',
   'sessions': 1762,
   'start': '2016-01-05',
   'end': '2023-01-03',
   'provider_uri': '/Users/rziiiii/dev/workspace-worktrees/benchmark-risk-excess-20261002/data/qlib/stable_excess_integration_20261002',
   'cost_bps': 25.0,
   'initial_cash': 100000.0,
   'maximum_session_return_error': 3.2119268578156834e-08,
   'tolerance': 1e-07,
   'native_api': 'qlib.backtest.backtest + SimulatorExecutor + Exchange + Position',
   'schedule_strategy': 'DirectTargetWeightStrategy subclass with observed-open sizing and fee-affordable targets',
   'report_mark': 'native daily same-day close; next-open reconciliation uses native positions and Qlib D.features',
   'scope': 'complete prescribed daily target/HOLD schedule; actual Qlib Exchange, Position, report and next-open accounting',
   'execution_limitation': 'Observed historical opens and continuous adjusted shares; no claim of spread/impact/partial-fill evidence.',
   'policy_scope': 'continuous_three_asset_targets_without_legacy_allocation_caps',
   'legacy_controller_executed': False,
   'risk_annualization_sessions': 252,
   'native_close_anchored_max_drawdown_pct': -44.703861437493906,
   'native_open_to_open_anchored_max_drawdown_pct': -46.61582999421998,
   'risk_table_mark_convention': 'risk_analysis uses native close marks; risk_analysis_open_to_open uses native positions marked at the following open'}},
 'production_change': False,
 'real_broker_orders': False,
 'artifact_policy': {'policy': 'slim_card_recorder_first',
  'workflow_config': 'workflow.yaml',
  'recorder_only_artifacts': ['inputs/*.pkl',
   'models/*.pkl',
   'analysis/portfolio_replays.pkl',
   'portfolio_analysis/*.pkl']},
 'limitations': ['Risk budget is an estimated variance ceiling; it does not guarantee realized drawdown/CVaR.',
  'All historical windows have been reviewed; adaptive research and seed repetition do not create new independent evidence.',
  'Covariance uses expanding prior observed opens, not futurelabels; its regime lag remains a model assumption.',
  'A failed batch leaves the overall stable-excess objective active.']}

In [3]:
import pandas as pd
card=root/"research/benchmark_risk_excess_20261002"
display(pd.read_csv(card/"model_selection.csv"))
display(pd.read_csv(card/"backtest_benchmark_comparison.csv"))
display(pd.read_csv(card/"development_gates.csv"))

,variant,historical_qualification_pass,passed_gates,worst_annualized_lower_bound,worst_relative_wealth,positive_years_10bps
0,constant_budget,False,4,-0.049709,0.826101,1
1,forecast_budget,False,3,-0.107149,0.783767,3
2,base_budget,False,3,-0.149019,0.703088,2
3,pit_budget,False,2,-0.153880,0.672791,2

,cost_bps,sessions,start_signal,last_exit,terminal_wealth,return_pct,cagr_pct,annualized_log_volatility_pct,max_drawdown_pct,qlib_max_drawdown_without_initial_mark_pct,...,annualized_log_excess,annualized_relative_return_pct,relative_max_drawdown_pct,up_day_conditional_relative_return_pct,down_day_conditional_relative_return_pct,conditional_returns_are_noncontiguous_statistics,risk_policy,annualization_sessions,variant,segment
0,10.0,1762,2016-01-04,2023-01-04,3.585363,258.536255,20.035286,29.149861,-46.473580,-46.473580,...,-0.025021,-2.471032,-17.678797,-49.587632,66.526957,True,reported against benchmark; no implicit fixed ...,252,constant_budget,development
1,25.0,1762,2016-01-04,2023-01-04,3.522849,252.284904,19.733699,29.150444,-46.615832,-46.615832,...,-0.027322,-2.695236,-18.729078,-50.059886,65.418231,True,reported against benchmark; no implicit fixed ...,252,constant_budget,development
2,10.0,1762,2016-01-04,2023-01-04,3.854359,285.435928,21.283709,24.468645,-47.258985,-47.258985,...,-0.014674,-1.456685,-30.845810,-95.923416,2113.830533,True,reported against benchmark; no implicit fixed ...,252,base_budget,development
3,25.0,1762,2016-01-04,2023-01-04,2.998270,199.826962,17.004270,24.474245,-49.250894,-49.250894,...,-0.050382,-4.913379,-44.419274,-96.435566,1872.508696,True,reported against benchmark; no implicit fixed ...,252,base_budget,development
4,10.0,1762,2016-01-04,2023-01-04,3.686714,268.671419,20.514798,24.301699,-47.922474,-47.922474,...,-0.021034,-2.081427,-33.481851,-96.246704,2199.932941,True,reported against benchmark; no implicit fixed ...,252,pit_budget,development
5,25.0,1762,2016-01-04,2023-01-04,2.869071,186.907063,16.269507,24.304588,-49.789938,-49.789938,...,-0.056682,-5.510504,-46.515816,-96.717710,1949.760429,True,reported against benchmark; no implicit fixed ...,252,pit_budget,development
6,10.0,1762,2016-01-04,2023-01-04,4.043245,304.324481,22.116431,26.561283,-47.052286,-47.052286,...,-0.007832,-0.780096,-20.510271,-87.796108,675.747251,True,reported against benchmark; no implicit fixed ...,252,forecast_budget,development
7,25.0,1762,2016-01-04,2023-01-04,3.342321,234.232108,18.836267,26.571123,-48.453025,-48.453025,...,-0.034846,-3.424558,-32.304627,-88.953077,609.489072,True,reported against benchmark; no implicit fixed ...,252,forecast_budget,development
8,10.0,934,2023-01-03,2026-09-25,4.193379,319.337882,47.221869,35.339019,-42.752231,-42.752231,...,-0.046254,-4.520036,-15.910896,-40.581001,41.782439,True,reported against benchmark; no implicit fixed ...,252,constant_budget_annual_refit,reused_diagnostic
9,10.0,934,2023-01-03,2026-09-25,4.185926,318.592561,47.151223,35.271327,-42.669678,-42.669678,...,-0.046734,-4.565853,-16.060565,-41.431326,43.585237,True,reported against benchmark; no implicit fixed ...,252,constant_budget_frozen2022,reused_diagnostic
10,25.0,934,2023-01-03,2026-09-25,4.149104,314.910368,46.800848,35.339477,-42.859960,-42.859960,...,-0.048714,-4.754615,-16.723311,-40.903130,41.418934,True,reported against benchmark; no implicit fixed ...,252,constant_budget_annual_refit,reused_diagnostic
11,25.0,934,2023-01-03,2026-09-25,4.141887,314.188732,46.731916,35.271838,-42.775931,-42.775931,...,-0.049183,-4.799338,-16.868359,-41.747173,43.216272,True,reported against benchmark; no implicit fixed ...,252,constant_budget_frozen2022,reused_diagnostic

,cost_bps,aggregate_positive_net_log_excess,minimum_positive_signal_years,median_annual_log_excess_positive,leave_any_one_year_out_log_excess_positive,anchored_max_drawdown_not_worse_than_soxx,cvar5_not_worse_than_soxx,minimum_positive_seeds_at_both_costs,stationary_block_20_lower_bound_positive,stationary_block_60_lower_bound_positive,all_pass,positive_years,years,positive_seeds_at_this_cost,seeds_positive_at_both_costs,seed_evidence_complete,largest_positive_year_share,minimum_leave_one_year_out_log_excess,variant
0,10.0,False,False,False,False,True,True,False,False,False,False,1,7,0,0,True,1.000000,-0.185365,constant_budget
1,25.0,False,False,False,False,True,True,False,False,False,False,1,7,0,0,True,1.000000,-0.197998,constant_budget
2,10.0,False,False,False,False,True,True,False,False,False,False,2,7,0,0,True,0.542689,-0.142445,base_budget
3,25.0,False,False,False,False,False,True,False,False,False,False,1,7,0,0,True,1.000000,-0.353373,base_budget
4,10.0,False,False,False,False,False,True,False,False,False,False,2,7,0,0,True,0.672612,-0.186914,pit_budget
5,25.0,False,False,False,False,False,True,False,False,False,False,1,7,0,0,True,1.000000,-0.397420,pit_budget
6,10.0,False,False,False,False,True,True,False,False,False,False,3,7,0,0,True,0.832255,-0.094683,forecast_budget
7,25.0,False,False,False,False,False,True,False,False,False,False,1,7,0,0,True,1.000000,-0.247758,forecast_budget

In [4]:
from IPython.display import Markdown,display
display(Markdown((card/"conclusion.md").read_text()))

# 基准风险预算实验结论

这是稳定超额目标的继续研究；本轮完成4个版本、3个种子，历史资格通过=False，总体目标尚未完成。

使用截至信号日已观察开盘收益的扩展协方差；模型学习风险预算使用比例与SOXL/SOXX组成，三维协方差只进入可行权重映射，不进入神经输入。训练与推理采用同一映射和净费结算。

开发期2016–2022信号年、10bp：
- constant_budget：收益258.54%，相对SOXX终值0.8395，MaxDD-46.47%，CVaR5-4.19%。
- base_budget：收益285.44%，相对SOXX终值0.9025，MaxDD-47.26%，CVaR5-3.66%。
- pit_budget：收益268.67%，相对SOXX终值0.8632，MaxDD-47.92%，CVaR5-3.64%。
- forecast_budget：收益304.32%，相对SOXX终值0.9467，MaxDD-47.05%，CVaR5-3.89%。

无市场信号对照、年度表现、两档费用、全部种子及失败门均已保留。开发期末次结算2023-01-04开盘；之后outer信号未参与排名。实际波动、尾部和稳定性门不因预测风险满足预算而豁免。

本轮决定：continue_research_no_historical_qualification。没有切换原SIM或提交委托；下一步由本轮结果及独立预测信息检验决定，不把单轮结束视为总体目标完成。
QLib recorder：bba55e94a1d04b4a9c68dca562766159。

# 基准风险预算实验结论

这是稳定超额目标的继续研究；本轮完成4个版本、3个种子，历史资格通过=False，总体目标尚未完成。

使用截至信号日已观察开盘收益的扩展协方差；模型学习风险预算使用比例与SOXL/SOXX组成，三维协方差只进入可行权重映射，不进入神经输入。训练与推理采用同一映射和净费结算。

开发期2016–2022信号年、10bp：
- constant_budget：收益258.54%，相对SOXX终值0.8395，MaxDD-46.47%，CVaR5-4.19%。
- base_budget：收益285.44%，相对SOXX终值0.9025，MaxDD-47.26%，CVaR5-3.66%。
- pit_budget：收益268.67%，相对SOXX终值0.8632，MaxDD-47.92%，CVaR5-3.64%。
- forecast_budget：收益304.32%，相对SOXX终值0.9467，MaxDD-47.05%，CVaR5-3.89%。

无市场信号对照、年度表现、两档费用、全部种子及失败门均已保留。开发期末次结算2023-01-04开盘；之后outer信号未参与排名。实际波动、尾部和稳定性门不因预测风险满足预算而豁免。

本轮决定：continue_research_no_historical_qualification。没有切换原SIM或提交委托；下一步由本轮结果及独立预测信息检验决定，不把单轮结束视为总体目标完成。
QLib recorder：bba55e94a1d04b4a9c68dca562766159。

训练侧继续诊断发现：21个无信号对照年度/种子模型，在全部成熟训练块上的目标损失为0.00459–0.01735；同目标下精确SOXX约为0.000001。现有有限softmax参数不能表达精确SOXX边界，参数衰减也不是向基准收缩，且固定120步尚未匹配可行的零超额对照。因此不能把本轮未通过全部归因于缺少预测信息。下一阶段改用包含明确基准候选的凸配置求解，先验证已知可行方案的目标值支配性，并使用五日预测期限避免把入场成本只压在一个会话。此项新假设将在结果前单独登记。

总体目标状态仍为active_research；本轮失败不是任务完成。原部署和账户保持不变。