> 2026-09-28 时序审计：本卡旧晋升结论已失效，当前状态为 `blocked_pending_causal_revalidation`。09:31执行路由曾读取未来10:31恢复标记；年度训练亦未排除测试开盘后才成熟的标签。两项代码问题已修复并通过反事实/边界测试，但原冻结模型与recorder明细丢失，尚不能重验原收益。以下数字与旧结论仅为历史记录，不是修复后的验证结果。按用户授权，重新训练将使用新的card/recorder身份及原参数和门槛。详见 `recovery_validation.json`。

# Stage1 开盘执行 Action Value

假设：保持 confidence-veto Stage1 的 shadow 目标和恢复状态不变，只学习小幅、非去风险开盘调仓的 execute/hold 净价值，可以同时提高成本后收益并减少交易。开发期为2016–2022；2023–2026只做复用诊断。

In [1]:
from pathlib import Path
import sys
root = Path.cwd().resolve()
while root != root.parent and not (root / 'AGENTS.md').exists():
    root = root.parent
if not (root / 'AGENTS.md').exists():
    raise RuntimeError('blocked: repository root not found')
sys.path.insert(0, root.as_posix())
import pandas as pd
import qlib
from qlib.config import REG_US
from qlib.data import D
from qlib.data.dataset import DatasetH
from qlib.data.dataset.handler import DataHandlerLP
from qlib.data.dataset.loader import StaticDataLoader
from qlib.workflow import R
from src.workflow.stage1_open_action_value import run_stage1_open_action_value_card

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

In [2]:
provider_uri = root / 'data' / 'qlib' / 'soxl_soxx_soxs'
qlib.init(provider_uri=provider_uri.as_posix(), region=REG_US, kernels=1)
calendar = D.calendar(start_time='2016-01-01', end_time='2026-12-31', freq='day')
{'provider_uri': provider_uri.as_posix(), 'calendar_rows': len(calendar), 'qlib_api': ['qlib.init', 'D.calendar', 'DatasetH', 'DataHandlerLP', 'StaticDataLoader', 'R.start']}

[18916:MainThread](2026-08-10 17:03:29,086) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[18916:MainThread](2026-08-10 17:03:29,093) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[18916:MainThread](2026-08-10 17:03:29,094) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

{'provider_uri': '/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs',
 'calendar_rows': 2664,
 'qlib_api': ['qlib.init',
  'D.calendar',
  'DatasetH',
  'DataHandlerLP',
  'StaticDataLoader',
  'R.start']}

In [3]:
summary = run_stage1_open_action_value_card(root=root)
{'decision': summary['decision'], 'baseline': summary['development_baseline'], 'candidate': summary['development_candidate'], 'frequency': summary['frequency_change'], 'recorder_id': summary['recorder_id']}

[18916:MainThread](2026-08-10 17:03:29,133) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[18916:MainThread](2026-08-10 17:03:29,137) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[18916:MainThread](2026-08-10 17:03:29,139) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[18916:MainThread](2026-08-10 17:03:29,176) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[18916:MainThread](2026-08-10 17:03:29,178) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[18916:MainThread](2026-08-10 17:03:29,179) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[18916:MainThread](2026-08-10 17:03:29,592) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[18916:MainThread](2026-08-10 17:03:29,597) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[18916:MainThread](2026-08-10 17:03:29,599) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

[18916:MainThread](2026-08-10 17:03:29,808) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[18916:MainThread](2026-08-10 17:03:29,811) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[18916:MainThread](2026-08-10 17:03:29,814) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[18916:MainThread](2026-08-10 17:03:29,908) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[18916:MainThread](2026-08-10 17:03:29,912) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[18916:MainThread](2026-08-10 17:03:29,914) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

[18916:MainThread](2026-08-10 17:03:31,701) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[18916:MainThread](2026-08-10 17:03:31,702) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[18916:MainThread](2026-08-10 17:03:31,703) INFO - qlib.timer - [log.py:127] - Time cost: 0.002s | Init data Done

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[18916:MainThread](2026-08-10 17:03:36,775) INFO - qlib.workflow - [exp.py:258] - Experiment 742969412867128395 starts running ...

[18916:MainThread](2026-08-10 17:03:36,876) INFO - qlib.workflow - [recorder.py:345] - Recorder 77f2ae6c0ea143c0a765366abae71aaf starts running under Experiment 742969412867128395 ...

[18916:MainThread](2026-08-10 17:03:37,811) INFO - qlib.timer - [log.py:127] - Time cost: 0.002s | waiting `async_log` Done

{'decision': 'validated_research_candidate_for_clean_forward_shadow',
 'baseline': {'terminal_wealth': 5.2495603589607,
  'return_pct': 424.95603589607003,
  'max_drawdown_pct': -26.728104402254584,
  'worst_day_pct': -7.847090792027754,
  'cvar5_pct': -4.104527243347027,
  'worst_rolling_5d_pct': -10.701044280515337,
  'total_turnover': 129.06286300007162,
  'open_trade_days': 1762.0,
  'recovery_action_count': 19.0,
  'avg_cash_weight_pct': 43.37510289012771},
 'candidate': {'terminal_wealth': 5.264929936854607,
  'return_pct': 426.49299368546065,
  'max_drawdown_pct': -26.72338991398454,
  'worst_day_pct': -7.847090792027754,
  'cvar5_pct': -4.091771097340451,
  'worst_rolling_5d_pct': -10.701044280515337,
  'total_turnover': 126.96102966714339,
  'open_trade_days': 1556.0,
  'recovery_action_count': 19.0,
  'avg_cash_weight_pct': 43.51384575749535},
 'frequency': {'open_trade_day_reduction_pct': 11.69125993189557,
  'turnover_reduction_pct': 1.628534563755224,
  'development_skipped_open_targets': 206,
  'outer_skipped_open_targets': 136},
 'recorder_id': '77f2ae6c0ea143c0a765366abae71aaf'}

In [4]:
card = root / 'research' / 'stage1_open_action_value_v1'
display(pd.read_csv(card / 'backtest_benchmark_comparison.csv'))
display(pd.read_csv(card / 'annual_metrics.csv'))
summary['development_gates']

,variant,segment,cost_bps,terminal_wealth,return_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,worst_rolling_5d_pct,total_turnover,open_trade_days,recovery_action_count,avg_cash_weight_pct
0,confidence_veto_baseline,development_walk_forward,10.0,5.249560,424.956036,-26.728104,-7.847091,-4.104527,-10.701044,129.062863,1762,19,43.375103
1,open_action_value_candidate,development_walk_forward,10.0,5.264930,426.492994,-26.723390,-7.847091,-4.091771,-10.701044,126.961030,1556,19,43.513846
2,confidence_veto_baseline,development_walk_forward,25.0,4.327105,332.710532,-28.827922,-7.848745,-4.115629,-10.879211,129.062863,1762,19,43.375103
3,open_action_value_candidate,development_walk_forward,25.0,4.353517,335.351712,-28.801084,-7.848745,-4.102670,-10.879211,126.961030,1556,19,43.513846
4,confidence_veto_baseline,outer_reused_diagnostic,10.0,4.802061,380.206146,-27.494922,-8.667006,-5.072032,-14.408875,58.611506,900,0,39.043288
5,open_action_value_candidate,outer_reused_diagnostic,10.0,4.888195,388.819528,-26.998395,-8.667006,-5.043097,-14.289537,57.560527,764,0,39.185506
6,confidence_veto_baseline,outer_reused_diagnostic,25.0,4.398545,339.854468,-28.409823,-8.668154,-5.078863,-14.506204,58.611506,900,0,39.043288
7,open_action_value_candidate,outer_reused_diagnostic,25.0,4.484509,348.450880,-27.887971,-8.668154,-5.049603,-14.386306,57.560527,764,0,39.185506

,segment,year,variant,terminal_wealth,return_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,worst_rolling_5d_pct,total_turnover,open_trade_days,wealth_ratio_vs_baseline
0,development_walk_forward,2016,confidence_veto_baseline,1.327158,32.715827,-15.610855,-4.710273,-3.393630,-10.701044,22.414244,252,1.000000
1,development_walk_forward,2016,open_action_value_candidate,1.327158,32.715827,-15.610855,-4.710273,-3.393630,-10.701044,22.414244,252,1.000000
2,development_walk_forward,2017,confidence_veto_baseline,1.211745,21.174469,-14.546505,-7.847091,-3.128071,-8.826932,13.818539,251,1.000000
3,development_walk_forward,2017,open_action_value_candidate,1.211802,21.180233,-14.546505,-7.847091,-3.113245,-8.826932,13.438786,209,1.000048
4,development_walk_forward,2018,confidence_veto_baseline,0.990494,-0.950560,-20.525359,-7.060733,-3.590597,-8.280248,18.274012,251,1.000000
5,development_walk_forward,2018,open_action_value_candidate,0.993379,-0.662139,-20.405162,-7.060733,-3.590597,-8.280248,18.155026,240,1.002912
6,development_walk_forward,2019,confidence_veto_baseline,1.774306,77.430628,-15.053963,-4.924076,-3.698492,-8.777179,13.257322,252,1.000000
7,development_walk_forward,2019,open_action_value_candidate,1.779857,77.985677,-15.022535,-4.673800,-3.646369,-8.661184,12.739540,197,1.003128
8,development_walk_forward,2020,confidence_veto_baseline,1.646419,64.641872,-24.732551,-6.429245,-4.792664,-10.620429,23.530547,253,1.000000
9,development_walk_forward,2020,open_action_value_candidate,1.641338,64.133848,-24.663886,-6.429245,-4.789942,-10.577509,22.811788,206,0.996914
10,development_walk_forward,2021,confidence_veto_baseline,1.480441,48.044130,-19.240349,-6.142088,-4.467593,-9.984896,15.699159,252,1.000000
11,development_walk_forward,2021,open_action_value_candidate,1.480250,48.025029,-19.147075,-6.142088,-4.458560,-9.984896,15.543483,226,0.999871
12,development_walk_forward,2022,confidence_veto_baseline,0.762039,-23.796137,-24.831559,-5.938653,-4.356848,-10.292131,22.069039,251,1.000000
13,development_walk_forward,2022,open_action_value_candidate,0.762088,-23.791234,-24.826723,-5.938653,-4.348322,-10.292131,21.858163,226,1.000064
14,outer_reused_diagnostic,2023,confidence_veto_baseline,1.418036,41.803593,-22.032330,-5.322966,-4.261943,-8.146536,18.468717,250,1.000000
15,outer_reused_diagnostic,2023,open_action_value_candidate,1.418443,41.844261,-21.920216,-5.322966,-4.249602,-8.140772,18.195947,211,1.000287
16,outer_reused_diagnostic,2024,confidence_veto_baseline,1.426218,42.621784,-17.021096,-7.392277,-4.591252,-10.096548,17.248089,252,1.000000
17,outer_reused_diagnostic,2024,open_action_value_candidate,1.433788,43.378775,-16.649793,-7.392277,-4.580566,-10.021441,17.011352,210,1.005308
18,outer_reused_diagnostic,2025,confidence_veto_baseline,1.396078,39.607832,-22.303247,-7.185976,-4.711314,-9.592239,13.321502,250,1.000000
19,outer_reused_diagnostic,2025,open_action_value_candidate,1.405357,40.535735,-21.673589,-7.185976,-4.689384,-9.592239,12.929822,212,1.006647
20,outer_reused_diagnostic,2026,confidence_veto_baseline,1.700767,70.076705,-26.382847,-8.667006,-6.402819,-14.408875,9.573198,148,1.000000
21,outer_reused_diagnostic,2026,open_action_value_candidate,1.710272,71.027183,-25.835557,-8.667006,-6.390826,-14.289537,9.423407,131,1.005589

{'development_return_above_baseline': True,
 'stress_25bps_return_above_baseline': True,
 'max_drawdown_not_worse': True,
 'worst_day_not_worse': True,
 'cvar5_not_worse': True,
 'worst_5d_not_worse': True,
 'open_trade_days_reduced_8pct': True,
 'turnover_not_increased': True,
 'annual_wealth_floor_pass': True,
 'baseline_fallback_identity': True,
 'outer_not_used_for_selection': True}

## 中文结论

> 2026-09-28 时序审计：本卡旧晋升结论已失效，当前状态为 `blocked_pending_causal_revalidation`。09:31执行路由曾读取未来10:31恢复标记；年度训练亦未排除测试开盘后才成熟的标签。两项代码问题已修复并通过反事实/边界测试，但原冻结模型与recorder明细丢失，尚不能重验原收益。以下数字与旧结论仅为历史记录，不是修复后的验证结果。按用户授权，重新训练将使用新的card/recorder身份及原参数和门槛。详见 `recovery_validation.json`。

以下保留原始执行输出；当前验证状态以 `summary.json.verification_status` 和 `recovery_validation.json` 为准。

In [5]:
print((card / 'conclusion.md').read_text(encoding='utf-8'))

> 2026-09-28 时序审计：本卡旧晋升结论已失效，当前状态为 `blocked_pending_causal_revalidation`。09:31执行路由曾读取未来10:31恢复标记；年度训练亦未排除测试开盘后才成熟的标签。两项代码问题已修复并通过反事实/边界测试，但原冻结模型与recorder明细丢失，尚不能重验原收益。以下数字与旧结论仅为历史记录，不是修复后的验证结果。按用户授权，重新训练将使用新的card/recorder身份及原参数和门槛。详见 `recovery_validation.json`。

# 中文结论

- 做了什么：在当前 Stage1 confidence-veto 上新增开盘 action-value 执行路由。Stage1 继续用独立 shadow 状态产生原目标；执行层只对不超过5% L1 turnover、且不是去风险的交易判断 execute/hold，所有 beta 下降和10:31恢复日都强制执行。
- 标签：用当日执行与继续持有的实现收益差，扣除25bp当日及下一日复位成本；Logistic 按年度扩展训练，2023-2026模型冻结在2022年末。
- 开发期10bp：baseline return=424.9560%、candidate=426.4930%；MaxDD从 -26.7281% 改善到 -26.7234%，worst5保持 -10.7010%。
- 成本压力：candidate 25bp return=335.3517%，仍高于 baseline 25bp=332.7105%。正式对比见 backtest_benchmark_comparison.csv。
- 频率：开盘交易日减少 11.69%，turnover减少 1.63%，10:31恢复语义没有被固定带宽误删。
- 年度稳定性：开发期逐年财富下限门=True；完整年度比值见 annual_metrics.csv。
- outer复用诊断：baseline=380.2061%、candidate=388.8195%；不参与选择，也不是clean holdout。
- 决策：validated_research_candidate_for_clean_forward_shadow。这已经超过当前研究基线，但生产替换仍 blocked，必须先做独立shadow状态账本和新的连续前向验证。
- qlib：DatasetH/DataHandlerLP 承载年度扩展训练，预测、标签、训练帧、模型和portfolio replay均进入 recorder 77f2ae6c0ea143c0a765366abae71aaf。
- 不构成买卖建议。