# Cost-aware asymmetric target tracking v1

假设：当前 Stage1 的开盘换手成本偏高。冻结原模型、特征和 10:30 恢复动作，仅把加风险改成分步靠近目标；降风险仍立即执行。开发期选择，2023–2026 outer 只做 reused diagnostic。

In [1]:
from pathlib import Path
import sys
import pandas as pd
import qlib
from qlib.constant import REG_US
from qlib.data import D
from qlib.workflow import R
from IPython.display import Markdown, display

HERE = Path.cwd().resolve()
ROOT = next(
    candidate
    for candidate in (HERE, *HERE.parents)
    if (candidate / 'AGENTS.md').exists() and (candidate / 'SPEC.md').exists()
)
if ROOT.as_posix() not in sys.path:
    sys.path.insert(0, ROOT.as_posix())

from src.workflow.cost_aware_target_tracking import (
    EXPERIMENT,
    run_cost_aware_target_tracking_card,
)

PROVIDER_URI = ROOT / 'data' / 'qlib' / 'soxl_intraday_15min'
qlib.init(provider_uri=PROVIDER_URI.as_posix(), region=REG_US, kernels=1)
calendar = D.calendar(
    start_time='2019-01-02 09:45:00',
    end_time='2026-12-31 16:00:00',
    freq='15min',
)
qlib_feature_audit = D.features(
    ['SOXL', 'SOXX'],
    ['$close', '$volume'],
    start_time='2026-07-20 09:45:00',
    end_time='2026-07-23 16:00:00',
    freq='15min',
)
CARD = ROOT / 'research' / EXPERIMENT
display({'provider_uri': PROVIDER_URI.as_posix(), 'calendar_rows': len(calendar), 'feature_rows': len(qlib_feature_audit)})

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[26930:MainThread](2026-07-24 23:33:38,671) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[26930:MainThread](2026-07-24 23:33:38,673) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[26930:MainThread](2026-07-24 23:33:38,673) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

{'provider_uri': '/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min',
 'calendar_rows': 49194,
 'feature_rows': 208}

In [2]:
summary = run_cost_aware_target_tracking_card(root=ROOT)
display({
    'decision': summary['decision'],
    'selected_execution': summary['selected_execution'],
    'baseline_reproduction': summary['baseline']['reproduction_pass'],
    'outer_metrics_10bps': summary['outer_diagnostic_metrics_10bps'],
    'outer_effect': summary['outer_effect'],
    'recorder_id': summary['recorder_id'],
})

[26930:MainThread](2026-07-24 23:33:38,730) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[26930:MainThread](2026-07-24 23:33:38,731) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[26930:MainThread](2026-07-24 23:33:38,731) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[26930:MainThread](2026-07-24 23:33:38,753) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[26930:MainThread](2026-07-24 23:33:38,754) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[26930:MainThread](2026-07-24 23:33:38,754) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[26930:MainThread](2026-07-24 23:33:39,016) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[26930:MainThread](2026-07-24 23:33:39,016) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[26930:MainThread](2026-07-24 23:33:39,017) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

[26930:MainThread](2026-07-24 23:33:39,214) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[26930:MainThread](2026-07-24 23:33:39,215) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[26930:MainThread](2026-07-24 23:33:39,215) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[26930:MainThread](2026-07-24 23:33:39,254) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[26930:MainThread](2026-07-24 23:33:39,255) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[26930:MainThread](2026-07-24 23:33:39,256) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[26930:MainThread](2026-07-24 23:33:42,352) INFO - qlib.workflow - [exp.py:258] - Experiment 294210145628705484 starts running ...

[26930:MainThread](2026-07-24 23:33:42,405) INFO - qlib.workflow - [recorder.py:345] - Recorder 84c4385ae7a54736901e67c3646af0ab starts running under Experiment 294210145628705484 ...

[26930:MainThread](2026-07-24 23:33:42,491) INFO - qlib.timer - [log.py:127] - Time cost: 0.004s | waiting `async_log` Done

{'decision': 'retain_current_stage1_baseline_cost_aware_variant_not_promoted',
 'selected_execution': {'variant': 'current_stage1_full_target_baseline',
  'risk_up_fraction': 1.0,
  'aim_momentum_multiplier': 0.0,
  'selected_from_segment': 'development_walk_forward',
  'selection_open_cost_bps': 25.0,
  'selection_intraday_cost_bps': 10.0},
 'baseline_reproduction': True,
 'outer_metrics_10bps': {'terminal_wealth': 6.433420180351397,
  'return_pct': 543.3420180351396,
  'max_drawdown_pct': -28.10510967554787,
  'worst_day_pct': -9.383714522786345,
  'cvar5_pct': -5.233616441404358,
  'worst_rolling_5d_pct': -11.602809404682068},
 'outer_effect': {'return_change_vs_baseline_10bps_pct_points': 0.0,
  'return_change_vs_baseline_expected_cost_pct_points': 0.0,
  'turnover_reduction_pct': 0.0,
  'open_turnover_reduction_pct': 0.0,
  'avg_cash_weight_pct': 36.09952042229019,
  'avg_effective_beta': 1.0194671611565331,
  'recovery_action_count': 32},
 'recorder_id': '84c4385ae7a54736901e67c3646af0ab'}

In [3]:
for name in (
    'model_selection.csv',
    'model_comparison.csv',
    'turnover_analysis.csv',
    'cost_sensitivity.csv',
    'annual_metrics.csv',
):
    display(Markdown(f'## {name}'))
    display(pd.read_csv(CARD / name))

## model_selection.csv

,variant,segment,selection_uses_outer_test,risk_up_fraction,aim_momentum_multiplier,expected_cost_open_bps,expected_cost_intraday_bps,expected_cost_terminal_wealth,expected_cost_return_pct,expected_cost_max_drawdown_pct,...,expected_cost_relative_ratio_p25,expected_cost_relative_ratio_median,open_turnover,intraday_turnover,total_turnover,open_turnover_share_pct,open_active_day_count,open_material_day_count,intraday_action_count,development_gate_pass
0,current_stage1_full_target_baseline,development_walk_forward,False,1.000000,0.0,25.0,10.0,1.664257,66.425709,-36.899249,...,0.689691,0.756753,132.458669,43.490428,175.949097,75.282381,923,914,139,True
1,asymmetric_risk_up_0.5,development_walk_forward,False,0.500000,0.0,25.0,10.0,1.663396,66.339610,-36.769924,...,0.680711,0.753614,120.860324,36.465636,157.325959,76.821603,1377,985,119,False
2,asymmetric_risk_up_0.3333,development_walk_forward,False,0.333333,0.0,25.0,10.0,1.386627,38.662712,-36.652808,...,0.617188,0.747158,116.432832,37.147829,153.580661,75.812170,1360,987,119,False
3,aim_ahead_risk_up_0.5,development_walk_forward,False,0.500000,1.0,25.0,10.0,1.646196,64.619559,-35.267016,...,0.710752,0.798100,129.517946,39.127827,168.645773,76.798809,1364,1050,123,False
4,aim_ahead_risk_up_0.3333,development_walk_forward,False,0.333333,2.0,25.0,10.0,1.252131,25.213139,-36.585475,...,0.628318,0.721922,138.874980,48.127347,187.002327,74.263771,1351,1083,150,False

## model_comparison.csv

,variant,segment,selection_uses_outer_test,risk_up_fraction,aim_momentum_multiplier,open_cost_bps,intraday_cost_bps,terminal_wealth,return_pct,max_drawdown_pct,...,terminal_wealth_ratio_vs_soxx,avg_cash_weight_pct,avg_effective_beta,open_turnover,intraday_turnover,total_turnover,open_turnover_share_pct,open_active_day_count,open_material_day_count,intraday_action_count
0,current_stage1_full_target_baseline,outer_diagnostic_reused,False,1.000000,0.0,10.0,10.0,6.433420,543.342018,-28.105110,...,1.347956,36.099520,1.019467,61.873906,9.871728,71.745634,86.240657,404,403,32
1,asymmetric_risk_up_0.5,outer_diagnostic_reused,False,0.500000,0.0,10.0,10.0,4.175844,317.584442,-29.140038,...,0.874940,39.875219,0.921897,55.662577,12.389029,68.051605,81.794656,707,425,40
2,asymmetric_risk_up_0.3333,outer_diagnostic_reused,False,0.333333,0.0,10.0,10.0,4.345381,334.538118,-25.033484,...,0.910462,41.576195,0.884697,51.131707,9.592320,60.724027,84.203419,713,457,29
3,aim_ahead_risk_up_0.5,outer_diagnostic_reused,False,0.500000,1.0,10.0,10.0,3.762092,276.209249,-27.657489,...,0.788249,40.515568,0.890573,63.190172,13.030076,76.220248,82.904705,695,489,42
4,aim_ahead_risk_up_0.3333,outer_diagnostic_reused,False,0.333333,2.0,10.0,10.0,3.499407,249.940654,-25.076822,...,0.733210,42.117096,0.862413,56.973468,9.431096,66.404563,85.797519,725,506,28

## turnover_analysis.csv

,variant,risk_up_fraction,aim_momentum_multiplier,open_turnover,intraday_turnover,total_turnover,open_turnover_share_pct,open_active_day_count,open_material_day_count,intraday_action_count,avg_cash_weight_pct,avg_effective_beta
0,current_stage1_full_target_baseline,1.000000,0.0,61.873906,9.871728,71.745634,86.240657,404,403,32,36.099520,1.019467
1,asymmetric_risk_up_0.5,0.500000,0.0,55.662577,12.389029,68.051605,81.794656,707,425,40,39.875219,0.921897
2,asymmetric_risk_up_0.3333,0.333333,0.0,51.131707,9.592320,60.724027,84.203419,713,457,29,41.576195,0.884697
3,aim_ahead_risk_up_0.5,0.500000,1.0,63.190172,13.030076,76.220248,82.904705,695,489,42,40.515568,0.890573
4,aim_ahead_risk_up_0.3333,0.333333,2.0,56.973468,9.431096,66.404563,85.797519,725,506,28,42.117096,0.862413

## cost_sensitivity.csv

,variant,scenario,decision_path,open_cost_bps,intraday_cost_bps,terminal_wealth,return_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,worst_rolling_5d_pct
0,current_stage1_full_target_baseline,current_10_open_10_intraday,fixed_from_10bp_open_10bp_intraday,10.0,10.0,6.433420,543.342018,-28.105110,-9.383715,-5.233616,-11.602809
1,current_stage1_full_target_baseline,open_heavy_25_open_10_intraday,fixed_from_10bp_open_10bp_intraday,25.0,10.0,5.864030,486.403011,-29.046035,-9.383715,-5.241589,-11.725467
2,current_stage1_full_target_baseline,stress_25_open_25_intraday,fixed_from_10bp_open_10bp_intraday,25.0,25.0,5.778015,477.801494,-29.088719,-9.383715,-5.244785,-11.780256
3,current_stage1_full_target_baseline,tail_50_open_25_intraday,fixed_from_10bp_open_10bp_intraday,50.0,25.0,4.950597,395.059658,-31.647203,-9.383715,-5.258073,-11.984421
4,asymmetric_risk_up_0.5,current_10_open_10_intraday,fixed_from_10bp_open_10bp_intraday,10.0,10.0,4.175844,317.584442,-29.140038,-9.346414,-5.138683,-11.328590
5,asymmetric_risk_up_0.5,open_heavy_25_open_10_intraday,fixed_from_10bp_open_10bp_intraday,25.0,10.0,3.841679,284.167912,-30.204855,-9.347017,-5.144666,-11.390910
6,asymmetric_risk_up_0.5,stress_25_open_25_intraday,fixed_from_10bp_open_10bp_intraday,25.0,25.0,3.771115,277.111497,-30.370443,-9.347017,-5.148279,-11.406880
7,asymmetric_risk_up_0.5,tail_50_open_25_intraday,fixed_from_10bp_open_10bp_intraday,50.0,25.0,3.281415,228.141495,-32.106237,-9.348021,-5.158251,-11.659241
8,asymmetric_risk_up_0.3333,current_10_open_10_intraday,fixed_from_10bp_open_10bp_intraday,10.0,10.0,4.345381,334.538118,-25.033484,-9.093683,-4.905635,-11.232458
9,asymmetric_risk_up_0.3333,open_heavy_25_open_10_intraday,fixed_from_10bp_open_10bp_intraday,25.0,10.0,4.024825,302.482489,-27.309381,-9.095843,-4.912398,-11.296271
10,asymmetric_risk_up_0.3333,stress_25_open_25_intraday,fixed_from_10bp_open_10bp_intraday,25.0,25.0,3.967587,296.758658,-27.613125,-9.095843,-4.915201,-11.296271
11,asymmetric_risk_up_0.3333,tail_50_open_25_intraday,fixed_from_10bp_open_10bp_intraday,50.0,25.0,3.491618,249.161830,-31.240771,-9.099445,-4.926474,-11.402619
12,aim_ahead_risk_up_0.5,current_10_open_10_intraday,fixed_from_10bp_open_10bp_intraday,10.0,10.0,3.762092,276.209249,-27.657489,-9.341678,-5.045147,-11.322773
13,aim_ahead_risk_up_0.5,open_heavy_25_open_10_intraday,fixed_from_10bp_open_10bp_intraday,25.0,10.0,3.422141,242.214144,-28.986900,-9.342359,-5.051895,-11.385186
14,aim_ahead_risk_up_0.5,stress_25_open_25_intraday,fixed_from_10bp_open_10bp_intraday,25.0,25.0,3.356043,235.604311,-29.123612,-9.342359,-5.055508,-11.385186
15,aim_ahead_risk_up_0.5,tail_50_open_25_intraday,fixed_from_10bp_open_10bp_intraday,50.0,25.0,2.865723,186.572283,-31.281922,-9.343493,-5.067347,-11.641916
16,aim_ahead_risk_up_0.3333,current_10_open_10_intraday,fixed_from_10bp_open_10bp_intraday,10.0,10.0,3.499407,249.940654,-25.076822,-9.066753,-4.883383,-11.210901
17,aim_ahead_risk_up_0.3333,open_heavy_25_open_10_intraday,fixed_from_10bp_open_10bp_intraday,25.0,10.0,3.213100,221.310016,-27.455072,-9.068964,-4.890676,-11.274467
18,aim_ahead_risk_up_0.3333,stress_25_open_25_intraday,fixed_from_10bp_open_10bp_intraday,25.0,25.0,3.168169,216.816888,-27.796869,-9.068964,-4.893479,-11.274467
19,aim_ahead_risk_up_0.3333,tail_50_open_25_intraday,fixed_from_10bp_open_10bp_intraday,50.0,25.0,2.747831,174.783148,-33.497857,-9.072650,-4.905634,-11.380405

## annual_metrics.csv

,year,terminal_wealth,return_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,worst_rolling_5d_pct,terminal_wealth_ratio_vs_soxx,avg_cash_weight_pct,recovery_action_count
0,2023,1.417018,41.701820,-21.654737,-5.401288,-4.267416,-8.145412,0.903588,33.607854,3
1,2024,1.393222,39.322160,-18.027343,-7.390741,-4.679966,-10.092327,1.153524,41.863089,8
2,2025,1.619374,61.937445,-22.933951,-7.185336,-4.954944,-10.535412,1.094333,36.770167,14
3,2026,2.012329,101.232911,-21.716439,-9.383715,-7.133178,-11.602809,1.181760,28.820950,7

## 最终中文结论

In [4]:
display(Markdown((CARD / 'conclusion.md').read_text(encoding='utf-8')))

# 中文结论

- 做了什么：冻结当前 Stage1 的原模型、21 个特征、回撤状态机、10:30 恢复模型和参数，只比较目标仓位执行速度。降风险仍一次完成；加风险和同 beta 轮换比较 100%、50%、33% 直接靠近目标，以及按动态交易论文思路用目标变化趋势构造 aim-ahead 后再执行 50%/33%。
- 基准：intraday_on_policy_staged_validation_v1，recorder=f6b09330175e41719886d58ee2d11bec，Stage2 继续关闭。新实现对基准的 return 差=0.0000000000 个百分点，复现门=True。
- 选择：先要求当前 10/10 成本下通过 2019–2022 完整开发门，再按开盘 25bp、盘中 10bp 收益排序；2023–2026 outer 没有参与速度选择。选中 current_stage1_full_target_baseline，risk_up_fraction=1.000000，aim multiplier=0.00；至少一个候选通过完整开发门=True。
- outer 10/10：选中方案 return=543.3420%，MaxDD=-28.1051%，worst day=-9.3837%，CVaR5=-5.2336%，worst 5d=-11.6028%。
- 相对当前基准：10/10 收益变化=0.0000 个百分点；开盘 25bp/盘中 10bp 的动态成本回放收益变化=0.0000 个百分点；总换手下降=0.0000%，开盘换手下降=0.0000%。
- 正式压力：冻结 10/10 决策后按开盘/盘中各 25bp 重估，return=477.8015%，MaxDD=-29.0887%，worst 5d=-11.7803%。额外尾部诊断按开盘 50bp、盘中 25bp 重估，但不作为晋升门。
- 现金与动作：平均现金=36.0995%，平均有效 beta=1.0195，10:30 恢复动作=32 次。
- 是否替换：retain_current_stage1_baseline_cost_aware_variant_not_promoted。只有非基准速度同时提高 10/10 与主成本收益、换手至少下降 10% 且通过风险/年度/相对 SOXX 门，才替换当前基准。
- 风险：outer 已被前序研究反复查看，因此这里只是 reused diagnostic，不是新的未见样本；成本仍是线性 bps，尚未覆盖开盘价差、冲击、排队和成交不足。
- qlib recorder：84c4385ae7a54736901e67c3646af0ab
- 不构成买卖建议。