# Multitask classification direct allocation

同时比较标签、快速变化特征、tabular/GRU编码器；最终权重始终由模型直接连续输出。

In [1]:
from pathlib import Path
import sys
import qlib
from qlib.data import D
from qlib.workflow import R
repo_root = Path.cwd().parents[1]
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))
qlib.init(provider_uri=str(repo_root / 'data/qlib/soxl'), region='us', kernels=1, skip_if_reg=False)
calendar = D.calendar(start_time='2011-01-03', end_time='2026-12-31', freq='day')
from src.workflow.multitask_classification_allocation import run_multitask_classification_allocation_card
summary = run_multitask_classification_allocation_card(root=repo_root)
summary['promotion_decision']

[32059:MainThread](2026-07-23 20:52:12,542) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[32059:MainThread](2026-07-23 20:52:12,543) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[32059:MainThread](2026-07-23 20:52:12,544) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[32059:MainThread](2026-07-23 20:52:13,999) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[32059:MainThread](2026-07-23 20:52:14,000) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[32059:MainThread](2026-07-23 20:52:14,000) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[32059:MainThread](2026-07-23 20:52:14,024) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[32059:MainThread](2026-07-23 20:52:14,025) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[32059:MainThread](2026-07-23 20:52:14,026) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[32059:MainThread](2026-07-23 20:52:14,288) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[32059:MainThread](2026-07-23 20:52:14,288) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[32059:MainThread](2026-07-23 20:52:14,289) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

[32059:MainThread](2026-07-23 20:52:14,435) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[32059:MainThread](2026-07-23 20:52:14,436) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[32059:MainThread](2026-07-23 20:52:14,436) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[32059:MainThread](2026-07-23 20:53:35,658) INFO - qlib.workflow - [exp.py:258] - Experiment 803570159196343465 starts running ...

[32059:MainThread](2026-07-23 20:53:35,734) INFO - qlib.workflow - [recorder.py:345] - Recorder 156583dcadef480f9a1f354171ee526d starts running under Experiment 803570159196343465 ...

[32059:MainThread](2026-07-23 20:53:35,888) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

'not_promoted_multitask_classification_or_risk_gates_failed'

In [2]:
import pandas as pd
card = Path.cwd()
pd.read_csv(card / 'model_selection.csv')

,segment,candidate,cost_bps,selection_uses_outer_test,return_pct,cagr_pct,annualized_vol_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,...,cvar_gate,worst_5d_gate,cash_gate,activity_gate,learnability_gate,gate_count,all_gate,selection_score,diagnostic_selected,selection_policy
0,development_walk_forward,tabular_base_allocation_only,10,False,185.287043,16.175384,37.655343,-50.573657,-14.483766,-5.673019,...,True,False,False,True,False,2,False,-0.655799,False,diagnostic_only_maximum_gate_count_then_score
1,development_walk_forward,tabular_base_multitask,10,False,273.472416,20.738010,36.215746,-43.293303,-10.129028,-5.377789,...,True,False,True,True,False,4,False,-0.085000,True,diagnostic_only_maximum_gate_count_then_score
2,development_walk_forward,tabular_fast_multitask,10,False,9.817826,1.348424,35.560320,-64.898491,-11.936688,-5.649170,...,True,False,False,True,False,3,False,-2.243341,False,diagnostic_only_maximum_gate_count_then_score
3,development_walk_forward,gru_fast_multitask,10,False,304.437023,22.121292,36.080000,-52.323937,-12.389868,-5.533773,...,True,False,False,True,False,3,False,-0.227362,False,diagnostic_only_maximum_gate_count_then_score

In [3]:
pd.read_csv(card / 'classification_summary.csv')

,candidate,task,mean_roc_auc,mean_average_precision,mean_brier,mean_positive_rate,years_auc_above_055,summary_segment
0,gru_fast_multitask,recovery_label,0.569275,0.315257,0.252648,0.221329,4,development_walk_forward
1,gru_fast_multitask,relative_alpha_label,0.613166,0.625949,0.385102,0.498099,6,development_walk_forward
2,gru_fast_multitask,tail_1d_label,0.504251,0.097849,0.124501,0.077758,2,development_walk_forward
3,gru_fast_multitask,tail_3d_label,0.486796,0.132004,0.182362,0.118086,2,development_walk_forward
4,gru_fast_multitask,tail_5d_label,0.513932,0.225767,0.272727,0.188472,2,development_walk_forward
5,tabular_base_allocation_only,recovery_label,0.542857,0.348041,0.234238,0.221329,4,development_walk_forward
6,tabular_base_allocation_only,relative_alpha_label,0.488950,0.494712,0.256715,0.498099,2,development_walk_forward
7,tabular_base_allocation_only,tail_1d_label,0.489336,0.106871,0.260698,0.077758,2,development_walk_forward
8,tabular_base_allocation_only,tail_3d_label,0.616590,0.210764,0.259282,0.118086,4,development_walk_forward
9,tabular_base_allocation_only,tail_5d_label,0.460188,0.201355,0.248256,0.188472,2,development_walk_forward
10,tabular_base_multitask,recovery_label,0.627493,0.403421,0.314496,0.221329,6,development_walk_forward
11,tabular_base_multitask,relative_alpha_label,0.596825,0.600750,0.311523,0.498099,4,development_walk_forward
12,tabular_base_multitask,tail_1d_label,0.507638,0.093990,0.171284,0.077758,2,development_walk_forward
13,tabular_base_multitask,tail_3d_label,0.519383,0.150601,0.207043,0.118086,4,development_walk_forward
14,tabular_base_multitask,tail_5d_label,0.517558,0.226362,0.278699,0.188472,3,development_walk_forward
15,tabular_fast_multitask,recovery_label,0.572790,0.303925,0.306422,0.221329,4,development_walk_forward
16,tabular_fast_multitask,relative_alpha_label,0.555306,0.562440,0.372280,0.498099,4,development_walk_forward
17,tabular_fast_multitask,tail_1d_label,0.498032,0.084664,0.142470,0.077758,3,development_walk_forward
18,tabular_fast_multitask,tail_3d_label,0.416028,0.114648,0.196020,0.118086,0,development_walk_forward
19,tabular_fast_multitask,tail_5d_label,0.438407,0.188942,0.278722,0.188472,0,development_walk_forward
20,gru_fast_multitask,recovery_label,0.571240,0.366962,0.275510,0.245116,3,outer_diagnostic
21,gru_fast_multitask,relative_alpha_label,0.542092,0.607424,0.414060,0.557295,2,outer_diagnostic
22,gru_fast_multitask,tail_1d_label,0.544981,0.138522,0.237499,0.098569,2,outer_diagnostic
23,gru_fast_multitask,tail_3d_label,0.574964,0.179223,0.265424,0.135183,2,outer_diagnostic
24,gru_fast_multitask,tail_5d_label,0.539394,0.273937,0.359058,0.221318,1,outer_diagnostic
25,tabular_base_allocation_only,recovery_label,0.380170,0.206217,0.255829,0.245116,0,outer_diagnostic
26,tabular_base_allocation_only,relative_alpha_label,0.447076,0.528722,0.249466,0.557295,0,outer_diagnostic
27,tabular_base_allocation_only,tail_1d_label,0.442833,0.109705,0.277966,0.098569,0,outer_diagnostic
28,tabular_base_allocation_only,tail_3d_label,0.499745,0.143219,0.205474,0.135183,1,outer_diagnostic
29,tabular_base_allocation_only,tail_5d_label,0.467693,0.213186,0.282525,0.221318,0,outer_diagnostic
30,tabular_base_multitask,recovery_label,0.490216,0.297696,0.366779,0.245116,0,outer_diagnostic
31,tabular_base_multitask,relative_alpha_label,0.499600,0.576281,0.306672,0.557295,1,outer_diagnostic
32,tabular_base_multitask,tail_1d_label,0.523045,0.122483,0.253001,0.098569,1,outer_diagnostic
33,tabular_base_multitask,tail_3d_label,0.517087,0.177995,0.280605,0.135183,1,outer_diagnostic
34,tabular_base_multitask,tail_5d_label,0.499003,0.270943,0.348966,0.221318,1,outer_diagnostic
35,tabular_fast_multitask,recovery_label,0.449569,0.253088,0.393199,0.245116,0,outer_diagnostic
36,tabular_fast_multitask,relative_alpha_label,0.554325,0.612271,0.321925,0.557295,1,outer_diagnostic
37,tabular_fast_multitask,tail_1d_label,0.475098,0.111640,0.221230,0.098569,0,outer_diagnostic
38,tabular_fast_multitask,tail_3d_label,0.498770,0.144527,0.279640,0.135183,0,outer_diagnostic
39,tabular_fast_multitask,tail_5d_label,0.525303,0.244244,0.358419,0.221318,1,outer_diagnostic

In [4]:
pd.read_csv(card / 'backtest_benchmark_comparison.csv')

,segment,candidate,cost_bps,selection_uses_outer_test,return_pct,cagr_pct,annualized_vol_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,...,avg_soxl_weight_pct,avg_soxx_weight_pct,longest_underwater_days,max_drawdown_recovery_days,soxx_max_drawdown_pct,soxx_longest_underwater_days,soxx_max_drawdown_recovery_days,downside_avg_cash_weight_pct,downside_min_cash_weight_pct,turnover
0,development_walk_forward,tabular_base_allocation_only,10,False,185.287043,16.175384,37.655343,-50.573657,-14.483766,-5.673019,...,14.510413,67.056037,482,56,-47.374011,257,56,14.884075,0.085559,234.987303
1,development_walk_forward,tabular_base_allocation_only,25,False,100.478377,10.459097,37.671416,-52.897055,-14.491765,-5.692209,...,14.510413,67.056037,558,56,-47.374011,257,56,14.884075,0.085559,234.987303
2,development_walk_forward,tabular_base_multitask,10,False,273.472416,20.738010,36.215746,-43.293303,-10.129028,-5.377789,...,14.888968,66.370969,281,56,-47.374011,257,56,18.886784,0.719886,243.087791
3,development_walk_forward,tabular_base_multitask,25,False,159.351140,14.602474,36.224078,-45.876064,-10.129974,-5.396724,...,14.888968,66.370969,355,56,-47.374011,257,56,18.886784,0.719886,243.087791
4,development_walk_forward,tabular_fast_multitask,10,False,9.817826,1.348424,35.560320,-64.898491,-11.936688,-5.649170,...,13.657433,66.543249,501,56,-47.374011,257,56,19.677223,1.635746,338.223820
5,development_walk_forward,tabular_fast_multitask,25,False,-33.893248,-5.747759,35.563858,-67.414407,-11.946726,-5.671188,...,13.657433,66.543249,965,56,-47.374011,257,56,19.677223,1.635746,338.223820
6,development_walk_forward,gru_fast_multitask,10,False,304.437023,22.121292,36.080000,-52.323937,-12.389868,-5.533773,...,12.850522,65.572354,410,56,-47.374011,257,56,14.738667,0.960784,144.049258
7,development_walk_forward,gru_fast_multitask,25,False,225.876812,18.406773,36.081367,-53.487739,-12.395708,-5.543565,...,12.850522,65.572354,442,56,-47.374011,257,56,14.738667,0.960784,144.049258
8,outer_diagnostic,tabular_base_allocation_only,10,False,444.915946,64.537394,37.801502,-38.025870,-11.941321,-5.177079,...,11.751624,60.100550,272,88,-42.790391,297,113,32.151042,0.505149,118.174575
9,outer_diagnostic,tabular_base_allocation_only,25,False,356.412384,56.191510,37.823540,-41.076010,-11.953964,-5.194068,...,11.751624,60.100550,297,113,-42.790391,297,113,32.151042,0.505149,118.174575
10,outer_diagnostic,tabular_base_multitask,10,False,288.697703,48.995361,38.174785,-54.921545,-13.882775,-5.676078,...,12.200990,59.525373,383,199,-42.790391,297,113,31.890841,0.691569,137.238234
11,outer_diagnostic,tabular_base_multitask,25,False,216.469719,40.265448,38.172874,-57.121941,-13.883324,-5.695584,...,12.200990,59.525373,398,214,-42.790391,297,113,31.890841,0.691569,137.238234
12,outer_diagnostic,tabular_fast_multitask,10,False,244.474951,43.802548,37.756415,-60.271109,-12.375978,-5.641516,...,11.581835,59.389989,406,222,-42.790391,297,113,29.587194,2.847064,205.660976
13,outer_diagnostic,tabular_fast_multitask,25,False,153.029696,31.345139,37.785626,-63.210735,-12.379836,-5.666960,...,11.581835,59.389989,448,264,-42.790391,297,113,29.587194,2.847064,205.660976
14,outer_diagnostic,gru_fast_multitask,10,False,328.571662,53.330752,37.014595,-46.559256,-14.309281,-5.379677,...,10.941722,57.575709,309,125,-42.790391,297,113,21.049007,1.041957,85.767133
15,outer_diagnostic,gru_fast_multitask,25,False,276.878686,47.650197,37.021209,-48.089201,-14.310849,-5.390674,...,10.941722,57.575709,323,139,-42.790391,297,113,21.049007,1.041957,85.767133

In [5]:
pd.read_csv(card / 'objective_gate_audit.csv')

,gate,required,passed,evidence
0,no_base_or_prior,True,True,none
1,no_candidate_weight_grid,True,True,none
2,outer_not_used_for_selection,True,True,development_2016_2022_only
3,development_return_gate,True,False,False
4,development_cost_gate,True,False,False
5,development_year_gate,True,False,False
6,development_maxdd_gate,True,False,False
7,development_worst_day_gate,True,True,True
8,development_cvar_gate,True,True,True
9,development_worst_5d_gate,True,False,False
10,development_cash_gate,True,True,True
11,development_activity_gate,True,True,True
12,development_learnability_gate,True,False,False
13,outer_ratio_above_soxx_report_only,False,False,0.7808842335418088
14,outer_maxdd_minus_20_report_only,False,False,-54.921545147239456

# 多任务分类直接连续配置结论

- 跑了什么：比较 allocation-only、tabular 多任务、快速变化特征多任务和20日GRU多任务；所有候选直接输出连续SOXL/SOXX/cash权重。
- 开发期诊断优胜：tabular_base_multitask；10bp财富/SOXX=0.8745，25bp=0.6082，MaxDD=-43.29%。
- 分类：tail1 AUC=0.5076，relative alpha AUC=0.5968，recovery AUC=0.6275。
- Outer仅诊断：10bp财富/SOXX=0.7809，MaxDD=-54.92%。
- 晋升决定：not_promoted_multitask_classification_or_risk_gates_failed。
- 风险：分类标签若跨年份不可学习，继续更换网络没有意义；outer不得用于选择标签、特征或模型。
- 下一步：只根据开发期分类与风险门决定是继续优化现有特征，还是转向新的PIT盘前/期权/成分股实时信息。