# Stage1 controller-aware distillation v1

假设：冻结现有 Stage1 安全控制器，只在 10:30 后学习连续安全 beta，能够在不突破 SOXL 30% 上限和现金下限的前提下，提高开发窗收益并减少换手。模型选择仅使用 2016–2022 开发窗；2023–2026 外层窗口只做冻结诊断。

In [1]:
from pathlib import Path
import sys

root = Path.cwd().resolve()
while root != root.parent and not (root / "SPEC.md").exists():
    root = root.parent
if str(root) not in sys.path:
    sys.path.insert(0, str(root))
root

PosixPath('/Users/rziiiii/dev/workspace')

In [2]:
import qlib
from qlib.data import D
from qlib.workflow import R

provider_uri = root / "data" / "qlib" / "soxl_soxx_soxs"
qlib.init(provider_uri=str(provider_uri), region="us")
calendar = D.calendar(start_time="2016-01-01", end_time="2026-12-31", freq="day")
{
    "provider_uri": str(provider_uri),
    "calendar_start": str(calendar[0]),
    "calendar_end": str(calendar[-1]),
    "calendar_sessions": len(calendar),
    "recorder_api": R.__class__.__name__,
}

[50263:MainThread](2026-07-27 17:56:46,392) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[50263:MainThread](2026-07-27 17:56:46,393) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[50263:MainThread](2026-07-27 17:56:46,394) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

{'provider_uri': '/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs',
 'calendar_start': '2016-01-04 00:00:00',
 'calendar_end': '2026-07-24 00:00:00',
 'calendar_sessions': 2654,
 'recorder_api': 'RecorderWrapper'}

In [3]:
from src.workflow.stage1_controller_aware_distillation import (
    run_stage1_controller_aware_distillation_card,
)

result = run_stage1_controller_aware_distillation_card(root=root)
result

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[50263:MainThread](2026-07-27 17:56:47,853) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[50263:MainThread](2026-07-27 17:56:47,854) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[50263:MainThread](2026-07-27 17:56:47,854) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[50263:MainThread](2026-07-27 17:56:47,878) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[50263:MainThread](2026-07-27 17:56:47,878) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[50263:MainThread](2026-07-27 17:56:47,879) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[50263:MainThread](2026-07-27 17:56:48,137) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[50263:MainThread](2026-07-27 17:56:48,138) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[50263:MainThread](2026-07-27 17:56:48,138) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

[50263:MainThread](2026-07-27 17:56:48,236) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[50263:MainThread](2026-07-27 17:56:48,237) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[50263:MainThread](2026-07-27 17:56:48,237) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[50263:MainThread](2026-07-27 17:56:48,277) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[50263:MainThread](2026-07-27 17:56:48,278) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[50263:MainThread](2026-07-27 17:56:48,278) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

[50263:MainThread](2026-07-27 17:56:48,505) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[50263:MainThread](2026-07-27 17:56:48,505) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[50263:MainThread](2026-07-27 17:56:48,505) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[50263:MainThread](2026-07-27 17:56:50,075) INFO - qlib.workflow - [exp.py:258] - Experiment 569983900966433436 starts running ...

[50263:MainThread](2026-07-27 17:56:50,124) INFO - qlib.workflow - [recorder.py:345] - Recorder c4c5082fa9eb4be3a6789deb7b80538a starts running under Experiment 569983900966433436 ...

[50263:MainThread](2026-07-27 17:56:50,203) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

{'experiment': 'stage1_controller_aware_distillation_v1',
 'card_type': 'stage1_controller_aware_distillation_research_card',
 'primary_notebook': 'stage1_controller_aware_distillation_v1.ipynb',
 'system_of_record': 'qlib',
 'provider_uri': '/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs',
 'intraday_provider_uri': '/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min',
 'as_of': '2026-07-24',
 'market': 'US',
 'region': 'us',
 'source_stage1': {'experiment': 'intraday_on_policy_staged_validation_v1',
  'recorder_id': 'f6b09330175e41719886d58ee2d11bec',
  'training_end': '2022-12-30',
  'stage2_enabled': False,
  'frozen': True},
 'hypothesis': 'A regularized continuous recovery-beta teacher can align the Stage1 safety controller with its 10:30 execution path without relaxing the 30% SOXL cap.',
 'method': {'teacher': 'development-only hindsight best legal beta on the fixed 0.4/0.6/0.8/1.0/1.2 grid after the first four 15m bars',
  'features': ['portfolio_drawdown',
   'current_beta_cap',
   'raw_effective_beta',
   'risk_state',
   'early_ret_soxl',
   'early_ret_soxx',
   'early_dislocation',
   'early_range_soxl',
   'early_range_soxx',
   'early_from_low_soxl',
   'early_from_low_soxx',
   'log_volume_soxl',
   'log_volume_soxx',
   'raw_soxl_weight',
   'raw_soxx_weight',
   'raw_cash_weight',
   'tail_probability',
   'alpha_probability',
   'portfolio_ret_1d',
   'portfolio_ret_3d',
   'portfolio_ret_5d'],
  'model': 'qlib DatasetH plus regularized Ridge',
  'development': 'walk-forward annual fits through 2022',
  'outer': 'all challenger rows in 2023-2026 use one model trained only through 2022; outer is diagnostic and never selection input',
  'incumbent_baseline': 'the source Stage1 keeps its prescribed annual walk-forward prior-year teacher updates; challenger selection never reads the resulting outer comparison',
  'hard_constraints': {'maximum_soxl_weight': 0.3,
   'minimum_cash_weight': 0.15,
   'maximum_recovery_beta': 1.2}},
 'dataset_audit': {'dataset_class': 'qlib.data.dataset.DatasetH',
  'handler_class': 'qlib.data.dataset.handler.DataHandlerLP',
  'loader_class': 'qlib.data.dataset.loader.StaticDataLoader',
  'features': ['portfolio_drawdown',
   'current_beta_cap',
   'raw_effective_beta',
   'risk_state',
   'early_ret_soxl',
   'early_ret_soxx',
   'early_dislocation',
   'early_range_soxl',
   'early_range_soxx',
   'early_from_low_soxl',
   'early_from_low_soxx',
   'log_volume_soxl',
   'log_volume_soxx',
   'raw_soxl_weight',
   'raw_soxx_weight',
   'raw_cash_weight',
   'tail_probability',
   'alpha_probability',
   'portfolio_ret_1d',
   'portfolio_ret_3d',
   'portfolio_ret_5d'],
  'labels': ['teacher_target_beta',
   'teacher_target_uplift',
   'teacher_best_return',
   'teacher_current_beta_cap',
   'teacher_raw_effective_beta'],
  'segments': {'all': ['2019-01-02', '2022-12-30'],
   'train_outer': ['2019-01-01', '2022-12-31'],
   'train_2020': ['2019-01-01', '2019-12-31'],
   'train_2021': ['2019-01-01', '2020-12-31'],
   'train_2022': ['2019-01-01', '2021-12-31'],
   'train_2023': ['2019-01-01', '2022-12-31']},
  'segment_rows': {'all': 288,
   'train_outer': 288,
   'train_2020': 23,
   'train_2021': 73,
   'train_2022': 103,
   'train_2023': 288}},
 'teacher_audit': {'rows': 288,
  'positive_uplift_rows': 138,
  'development_target_end': '2022-12-31'},
 'candidate_count': 5,
 'selected_model': {'name': 'ridge_a100_s025_u015',
  'ridge_alpha': 100.0,
  'shrinkage': 0.25,
  'minimum_predicted_uplift': 0.15,
  'maximum_recovery_beta': 1.2},
 'development_baseline_metrics_10bps': {'variant': 'stage1_baseline',
  'segment': 'development_walk_forward',
  'selection_uses_outer_test': False,
  'ridge_alpha': None,
  'shrinkage': None,
  'minimum_predicted_uplift': None,
  'maximum_recovery_beta': 0.6,
  'terminal_wealth': 5.172720536123832,
  'return_pct': 417.2720536123832,
  'max_drawdown_pct': -27.488582391581463,
  'worst_day_pct': -7.845988052345539,
  'cvar5_pct': -4.11984370114141,
  'worst_rolling_5d_pct': -11.858940216431579,
  'stress_25bps_return_pct': 315.65524510845,
  'stress_25bps_max_drawdown_pct': -30.509145252993587,
  'stress_25bps_worst_rolling_5d_pct': -12.180752211372958,
  'risk_window_pass_count': 7.0,
  'positive_relative_window_count': 7.0,
  'relative_ratio_min': 1.010417055454772,
  'relative_ratio_p25': 1.0539843226104262,
  'relative_ratio_median': 1.0699057774851397,
  'turnover': 145.939551326174,
  'turnover_reduction_vs_stage1': 0.0,
  'action_count': 51,
  'return_delta_vs_stage1_pct_points': 0.0,
  'max_drawdown_delta_vs_stage1_pct_points': 0.0,
  'worst_5d_delta_vs_stage1_pct_points': 0.0,
  'selected': False},
 'development_selected_metrics_10bps': {'variant': 'ridge_a100_s025_u015',
  'segment': 'development_walk_forward',
  'selection_uses_outer_test': False,
  'ridge_alpha': 100.0,
  'shrinkage': 0.25,
  'minimum_predicted_uplift': 0.15,
  'maximum_recovery_beta': 1.2,
  'terminal_wealth': 5.613195826539506,
  'return_pct': 461.31958265395065,
  'max_drawdown_pct': -26.52791336142051,
  'worst_day_pct': -7.845988052345539,
  'cvar5_pct': -4.143565641165957,
  'worst_rolling_5d_pct': -11.819416791793003,
  'stress_25bps_return_pct': 353.0277993290898,
  'stress_25bps_max_drawdown_pct': -29.802191957387926,
  'stress_25bps_worst_rolling_5d_pct': -11.990882909424572,
  'risk_window_pass_count': 7.0,
  'positive_relative_window_count': 7.0,
  'relative_ratio_min': 1.0031900497845496,
  'relative_ratio_p25': 1.0504043075919949,
  'relative_ratio_median': 1.0699057774851397,
  'turnover': 143.02935915507945,
  'turnover_reduction_vs_stage1': 0.019941079334897416,
  'action_count': 226,
  'return_delta_vs_stage1_pct_points': 44.04752904156743,
  'max_drawdown_delta_vs_stage1_pct_points': 0.960669030160954,
  'worst_5d_delta_vs_stage1_pct_points': 0.03952342463857583,
  'selected': True},
 'outer_diagnostic_selected_metrics_10bps': {'variant': 'ridge_a100_s025_u015',
  'segment': 'outer_diagnostic',
  'selection_uses_outer_test': False,
  'ridge_alpha': 100.0,
  'shrinkage': 0.25,
  'minimum_predicted_uplift': 0.15,
  'maximum_recovery_beta': 1.2,
  'terminal_wealth': 6.141860783807477,
  'return_pct': 514.1860783807477,
  'max_drawdown_pct': -28.80671450820075,
  'worst_day_pct': -9.383714522840133,
  'cvar5_pct': -5.195224461216374,
  'worst_rolling_5d_pct': -11.682821674959442,
  'stress_25bps_return_pct': 443.40088666243093,
  'stress_25bps_max_drawdown_pct': -30.028312109983602,
  'stress_25bps_worst_rolling_5d_pct': -11.759201947438347,
  'risk_window_pass_count': None,
  'positive_relative_window_count': None,
  'relative_ratio_min': None,
  'relative_ratio_p25': None,
  'relative_ratio_median': None,
  'turnover': 81.79289272689766,
  'turnover_reduction_vs_stage1': -0.13781232010812472,
  'action_count': 211,
  'return_delta_vs_stage1_pct_points': -27.602871240471018,
  'max_drawdown_delta_vs_stage1_pct_points': -0.7016022734185228,
  'worst_5d_delta_vs_stage1_pct_points': -0.0800122702773507,
  'selected': True},
 'promotion_gates': {'risk_gate_pass': True,
  'relative_window_gate_pass': True,
  'stage1_return_gate_pass': True,
  'neighbor_gate_pass': True,
  'neighbor_count': 3,
  'neighbor_min_wealth_ratio': 0.9280767457280722,
  'turnover_gate_pass': False,
  'required_turnover_reduction': 0.2,
  'development_return_delta_pct_points': 44.04752904156743,
  'development_turnover_reduction': 0.019941079334897416,
  'clean_unseen_holdout_available': False,
  'outer_used_for_selection': False},
 'selection_uses_outer_test': False,
 'outer_status': 'reused_diagnostic_not_clean_unseen_holdout',
 'decision': 'not_promoted_turnover_or_robustness_gate_failed',
 'promotion': 'blocked',
 'qlib_api': ['qlib.init',
  'qlib.data.D.calendar',
  'DatasetH',
  'DataHandlerLP',
  'qlib.workflow.R',
  'qlib.contrib.evaluate.risk_analysis'],
 'qlib_docs_reference': ['https://qlib.readthedocs.io/en/latest/component/model.html',
  'https://qlib.readthedocs.io/en/latest/component/recorder.html',
  'https://qlib.readthedocs.io/en/latest/reference/api.html'],
 'recorder_id': 'c4c5082fa9eb4be3a6789deb7b80538a',
 'recorder_uri': '/Users/rziiiii/dev/workspace/research/stage1_controller_aware_distillation_v1/qlib_recorder',
 'recorder_local_dir': '/Users/rziiiii/dev/workspace/research/stage1_controller_aware_distillation_v1/qlib_recorder/569983900966433436/c4c5082fa9eb4be3a6789deb7b80538a',
 'sidecars': {'selected_model': 'selected_model.json',
  'model_selection': 'model_selection.csv',
  'backtest_benchmark_comparison': 'backtest_benchmark_comparison.csv',
  'annual_metrics': 'annual_metrics.csv',
  'risk_analysis': 'risk_analysis.csv',
  'training_summary': 'training_summary.csv',
  'analysis_summary': 'analysis_summary.json',
  'failure_modes': 'failure_modes.md',
  'conclusion': 'conclusion.md',
  'workflow_config': 'workflow.yaml'},
 'artifact_policy': {'policy': 'slim_card_recorder_first',
  'workflow_config': 'workflow.yaml',
  'recorder_only_artifacts': ['artifacts/stage1_controller_aware_distillation_v1/teacher_training_frame.csv',
   'artifacts/stage1_controller_aware_distillation_v1/model_selection_full.csv',
   'artifacts/stage1_controller_aware_distillation_v1/portfolio_report.csv',
   'artifacts/stage1_controller_aware_distillation_v1/models/ridge_a100_s025_u015.pkl']}}

In [4]:
import json
import pandas as pd
from IPython.display import display

card = root / "research" / "stage1_controller_aware_distillation_v1"
summary = json.loads((card / "summary.json").read_text())
headline = {
    "decision": summary["decision"],
    "promotion": summary["promotion"],
    "development_return_pct": summary["development_selected_metrics_10bps"]["return_pct"],
    "development_delta_pct_points": summary["promotion_gates"]["development_return_delta_pct_points"],
    "development_turnover_reduction": summary["promotion_gates"]["development_turnover_reduction"],
    "outer_delta_pct_points": summary["outer_diagnostic_selected_metrics_10bps"]["return_delta_vs_stage1_pct_points"],
}
display(pd.DataFrame(headline, index=[0]).T.rename(columns={0: "value"}))
display(pd.read_csv(card / "model_selection.csv"))
display(pd.read_csv(card / "annual_metrics.csv"))

                                                                          value
decision                        not_promoted_turnover_or_robustness_gate_failed
promotion                                                               blocked
development_return_pct                                               461.319583
development_delta_pct_points                                          44.047529
development_turnover_reduction                                         0.019941
outer_delta_pct_points                                               -27.602871

,variant,segment,selection_uses_outer_test,ridge_alpha,shrinkage,minimum_predicted_uplift,maximum_recovery_beta,terminal_wealth,return_pct,max_drawdown_pct,...,relative_ratio_min,relative_ratio_p25,relative_ratio_median,turnover,turnover_reduction_vs_stage1,action_count,return_delta_vs_stage1_pct_points,max_drawdown_delta_vs_stage1_pct_points,worst_5d_delta_vs_stage1_pct_points,selected
0,stage1_baseline,development_walk_forward,False,NaN,NaN,NaN,0.6,5.172721,417.272054,-27.488582,...,1.010417,1.053984,1.069906,145.939551,0.000000,51,0.000000,0.000000,0.000000,False
1,stage1_baseline,outer_diagnostic,False,NaN,NaN,NaN,0.6,6.417889,541.788950,-28.105112,...,NaN,NaN,NaN,71.886102,0.000000,32,0.000000,0.000000,0.000000,False
2,ridge_a010_s025_u015,development_walk_forward,False,10.0,0.25,0.15,1.2,4.287798,328.779778,-34.367688,...,0.948053,0.975628,1.014328,170.919560,-0.171167,282,-88.492275,-6.879105,-1.745961,False
3,ridge_a010_s025_u015,outer_diagnostic,False,10.0,0.25,0.15,1.2,6.098605,509.860534,-28.676821,...,NaN,NaN,NaN,80.336329,-0.117550,192,-31.928416,-0.571709,-0.060120,False
4,ridge_a100_s025_u010,development_walk_forward,False,100.0,0.25,0.10,1.2,5.223707,422.370746,-25.733614,...,1.003190,1.051805,1.069906,144.302689,0.011216,235,5.098692,1.754969,0.039523,False
5,ridge_a100_s025_u010,outer_diagnostic,False,100.0,0.25,0.10,1.2,6.137595,513.759478,-28.843683,...,NaN,NaN,NaN,82.273865,-0.144503,227,-28.029471,-0.738570,-0.080012,False
6,ridge_a100_s025_u015,development_walk_forward,False,100.0,0.25,0.15,1.2,5.613196,461.319583,-26.527913,...,1.003190,1.050404,1.069906,143.029359,0.019941,226,44.047529,0.960669,0.039523,True
7,ridge_a100_s025_u015,outer_diagnostic,False,100.0,0.25,0.15,1.2,6.141861,514.186078,-28.806715,...,NaN,NaN,NaN,81.792893,-0.137812,211,-27.602871,-0.701602,-0.080012,True
8,ridge_a100_s025_u020,development_walk_forward,False,100.0,0.25,0.20,1.2,5.209477,420.947652,-25.547713,...,1.002329,1.055416,1.069906,143.178304,0.018920,200,3.675598,1.940869,0.039450,False
9,ridge_a100_s025_u020,outer_diagnostic,False,100.0,0.25,0.20,1.2,5.864759,486.475919,-28.899864,...,NaN,NaN,NaN,81.754813,-0.137283,200,-55.313031,-0.794752,-0.080012,False
10,ridge_a100_s050_u015,development_walk_forward,False,100.0,0.50,0.15,1.2,3.406593,240.659255,-41.507376,...,0.836624,0.867662,0.997930,225.394530,-0.544438,339,-176.612799,-14.018794,-1.541997,False
11,ridge_a100_s050_u015,outer_diagnostic,False,100.0,0.50,0.15,1.2,5.134742,413.474240,-30.162153,...,NaN,NaN,NaN,115.964365,-0.613168,216,-128.314709,-2.057041,-2.632434,False

,variant,year,cost_bps,terminal_wealth,return_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,worst_rolling_5d_pct,terminal_wealth_ratio_vs_soxx,turnover,action_count
0,stage1_baseline,2016,10.0,1.327675,32.767458,-15.605285,-4.708363,-3.393254,-10.697877,0.945697,22.027732,0
1,stage1_baseline,2017,10.0,1.212173,21.217311,-14.541327,-7.845988,-3.127795,-8.828303,0.843843,13.466204,0
2,stage1_baseline,2018,10.0,0.990730,-0.927044,-20.517515,-7.058978,-3.590496,-8.276475,1.112528,18.038320,0
3,stage1_baseline,2019,10.0,1.775601,77.560067,-15.045798,-4.923779,-3.698022,-8.775760,1.069906,12.528899,0
4,stage1_baseline,2020,10.0,1.585464,58.546423,-25.902932,-6.427972,-4.816103,-11.858940,1.048523,28.066263,24
5,stage1_baseline,2021,10.0,1.498924,49.892375,-18.002728,-6.141190,-4.432787,-9.585455,1.010417,16.670786,3
6,stage1_baseline,2022,10.0,0.768823,-23.117709,-25.613083,-5.937838,-4.503759,-11.547009,1.202335,35.141347,24
7,ridge_a100_s025_u015,2016,10.0,1.327675,32.767458,-15.605285,-4.708363,-3.393254,-10.697877,0.945697,22.027732,0
8,ridge_a100_s025_u015,2017,10.0,1.212173,21.217311,-14.541327,-7.845988,-3.127795,-8.828303,0.843843,13.466204,0
9,ridge_a100_s025_u015,2018,10.0,0.990730,-0.927044,-20.517515,-7.058978,-3.590496,-8.276475,1.112528,18.038320,0
10,ridge_a100_s025_u015,2019,10.0,1.775601,77.560067,-15.045798,-4.923779,-3.698022,-8.775760,1.069906,12.528899,0
11,ridge_a100_s025_u015,2020,10.0,1.585779,58.577949,-24.556859,-7.108419,-4.784167,-11.819417,1.048732,19.559110,45
12,ridge_a100_s025_u015,2021,10.0,1.488203,48.820270,-18.139863,-6.141190,-4.432408,-9.652706,1.003190,17.141340,28
13,ridge_a100_s025_u015,2022,10.0,0.840134,-15.986593,-24.627566,-5.937838,-4.574165,-11.597436,1.313856,40.267753,153
14,stage1_baseline,2023,10.0,1.417018,41.701833,-21.654740,-5.401303,-4.267415,-8.145392,0.903588,19.202598,3
15,stage1_baseline,2024,10.0,1.393222,39.322183,-18.027351,-7.390741,-4.679968,-10.092342,1.153523,19.982692,8
16,stage1_baseline,2025,10.0,1.619374,61.937432,-22.933953,-7.185349,-4.954944,-10.535418,1.094333,20.447131,14
17,stage1_baseline,2026,10.0,2.007471,100.747085,-21.716439,-9.383715,-7.133179,-11.602809,1.181377,12.253682,7
18,ridge_a100_s025_u015,2023,10.0,1.445595,44.559484,-22.157049,-5.401303,-4.267415,-8.116991,0.921810,23.374896,62
19,ridge_a100_s025_u015,2024,10.0,1.407444,40.744379,-18.173219,-7.390741,-4.604788,-10.262418,1.165298,21.362885,47
20,ridge_a100_s025_u015,2025,10.0,1.467454,46.745422,-23.644217,-7.185349,-4.820096,-9.709117,0.991669,21.999180,65
21,ridge_a100_s025_u015,2026,10.0,2.057111,105.711114,-21.391382,-9.383715,-7.133179,-11.682822,1.210589,15.055932,37

## 中文结论

以下结论由同一轮 qlib recorder 证据和 slim-card sidecars 生成。

In [5]:
from IPython.display import Markdown

display(Markdown((card / "conclusion.md").read_text()))

# 中文结论

- 做了什么：冻结现有 Stage1、Stage2 关闭和 30% SOXL 上限，使用 qlib DatasetH 将 10:30 后合法 beta 网格的最优增量蒸馏为连续 Ridge 目标；开发期逐年 walk-forward，2023–2026 共用截至 2022 年的冻结候选模型；对照组保留现有 Stage1 的逐年更新语义。
- 开发期：候选 `ridge_a100_s025_u015` 10bp return=461.3196%，相对 Stage1 增量=44.0475 个百分点，MaxDD=-26.5279%，worst-5d=-11.8194%。
- 换手：开发期 turnover reduction=1.99%，要求=20.00%，gate=False。
- outer 复用诊断：return=514.1861%，相对 Stage1 增量=-27.6029 个百分点；该区间不参与选择，也不是 clean holdout。
- 决策：`not_promoted_turnover_or_robustness_gate_failed`；生产 Stage1 不变，真实资金晋升 blocked。
- 风险：失败门=['turnover_gate_pass']；连续模型明显增加动作频率，历史开发期改善不足以替代新的连续前向模拟。
- 下一步：保持本卡为失败边界证据；若继续，只能预登记更强的换手/动作稀疏惩罚并等待 clean-forward，不用 outer 调阈值。
- qlib recorder：`c4c5082fa9eb4be3a6789deb7b80538a`。
- 不构成买卖建议。