# 固定 S/Z 监督：负结果已独评接受并完成一次归因

正式exec85921与只读归因exec6809均exit0。固定C closed_not_promoted；6fits/6native+15refs及原15CI不重跑、不改写。主阶段88artifact/NAS已由owner唯一冷读验证。

[完整结果](summary.json) · [独立评估](independent_evaluation.json) · [冷读](readback_verification.json) · [一次归因](attribution_conclusion.md) · [中文结论](conclusion.md)

## 原生 Qlib 入口与分阶段对象边界

获准的预检会执行 `qlib.init` → 在无全局写入 Recorder 时 `R.get_recorder`/`Recorder.load_object` 只读已核验白名单 → `DatasetH.prepare(col_set=DataHandler.CS_RAW)` → 严格日期/原始8字段证明后 `DataHandlerLP.from_df`/`DatasetH`（85→87列）→ `config(dump_all=True,recursive=True)` → `with R.start` 保存与直接 prepare 读回。禁止 `setup_data` 回载和先加载全时期对象再裁剪。

原PG instrument是SOXL_SOXX_CASH；C来源是SOXL_SOXX。严格验证完整3014日期顺序与原目标后才按位置赋值，不做inner join。C Recorder artifact `labels/fixed_H5_components_S_Z` 的实际列组是 `original`(8) 和 `fixed_day_night_label`(11)，只取后者S/Z。

正式运行先封存六模型SHA，才读取原946行评价Dataset和944个账户区间；预测不要求监督列。关闭全局R.start后，以同一明确Recorder低层start_run/end_run包裹评价与原生回放，避免source reader/qlib.init冲突。

In [1]:
import os, json
from pathlib import Path
from IPython.display import Markdown, display

ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "AGENTS.md").exists())
CARD = ROOT / "research/stage1_day_night_supervision_20261018"
plan = json.loads((CARD / "plan.json").read_text())
api_chain = ["qlib.init", "R.get_recorder / Recorder.load_object(exact verified whitelist)", "DatasetH.prepare(DataHandler.CS_RAW)", "DataHandlerLP.from_df -> DatasetH.config(dump_all=True, recursive=True)", "R.start / Recorder.save_objects / direct prepare roundtrip"]
prefit = os.environ.get("DAY_NIGHT_SUPERVISION_PREFLIGHT") == "1"
execute = os.environ.get("DAY_NIGHT_SUPERVISION_EXECUTE") == "1"
if prefit and execute:
    raise RuntimeError("Preflight and fit stages must be separately approved")
if prefit or execute:
    from src.workflow.day_night_supervision import prepare, run
    display({"approved_workflow_API_chain": api_chain, "phase": "preflight" if prefit else "fit_then_accounts"})
    result = (prepare if prefit else run)(root=ROOT, card=CARD)
    display({k: result.get(k) for k in ["decision", "recorder_id", "new_fits", "new_native_accounts", "gates", "nas_evidence"]})
else:
    display({"status": "implementation_only", "future_authorized_API_chain": api_chain, "real_source_objects_loaded": 0, "fits": 0, "accounts": 0})

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

{'approved_workflow_API_chain': ['qlib.init',
  'R.get_recorder / Recorder.load_object(exact verified whitelist)',
  'DatasetH.prepare(DataHandler.CS_RAW)',
  'DataHandlerLP.from_df -> DatasetH.config(dump_all=True, recursive=True)',
  'R.start / Recorder.save_objects / direct prepare roundtrip'],
 'phase': 'fit_then_accounts'}

2026/10/18 20:09:46 INFO mlflow.agent.hint: Load the `instrumenting-with-mlflow-tracing` skill at /Users/rziiiii/dev/workspace/qlib_venv/lib/python3.12/site-packages/mlflow/assistant/skills/instrumenting-with-mlflow-tracing/SKILL.md before writing any tracing code; it ships with this MLflow install. Set MLFLOW_DISABLE_AGENT_HINT=1 to silence this.

[43297:MainThread](2026-10-18 20:09:46,594) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[43297:MainThread](2026-10-18 20:09:46,596) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[43297:MainThread](2026-10-18 20:09:46,596) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/minute_information_pit_allocator_20261012/daily_prices')}

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[43297:MainThread](2026-10-18 20:09:46,691) WARNING - qlib.workflow - [expm.py:231] - No valid experiment found. Create a new experiment with name stage1_day_night_supervision_20261018.

[43297:MainThread](2026-10-18 20:09:46,693) INFO - qlib.workflow - [exp.py:258] - Experiment 146240142478072451 starts running ...

[43297:MainThread](2026-10-18 20:09:46,779) INFO - qlib.workflow - [recorder.py:345] - Recorder fd026924cf24465b918ec4ebd04ca639 starts running under Experiment 146240142478072451 ...

completed fit B_day_night_total_71

completed fit C_day_night_contrast_71

completed fit B_day_night_total_172

completed fit C_day_night_contrast_172

completed fit B_day_night_total_273

completed fit C_day_night_contrast_273

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[43297:MainThread](2026-10-18 20:09:53,501) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

[43297:MainThread](2026-10-18 20:09:53,504) INFO - qlib.workflow - [recorder.py:345] - Recorder fd026924cf24465b918ec4ebd04ca639 starts running under Experiment 146240142478072451 ...

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[43297:MainThread](2026-10-18 20:10:03,205) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[43297:MainThread](2026-10-18 20:10:03,207) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[43297:MainThread](2026-10-18 20:10:03,207) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_day_night_supervision_20261018_execution')}

[43297:MainThread](2026-10-18 20:10:03,215) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[43297:MainThread](2026-10-18 20:10:03,216) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[43297:MainThread](2026-10-18 20:10:03,217) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_day_night_supervision_20261018_execution')}

[43297:MainThread](2026-10-18 20:10:03,221) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[43297:MainThread](2026-10-18 20:10:03,222) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[43297:MainThread](2026-10-18 20:10:03,222) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_day_night_supervision_20261018_execution')}

[43297:MainThread](2026-10-18 20:10:03,238) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[43297:MainThread](2026-10-18 20:10:03,239) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[43297:MainThread](2026-10-18 20:10:03,239) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_day_night_supervision_20261018_execution')}

[43297:MainThread](2026-10-18 20:10:05,528) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[43297:MainThread](2026-10-18 20:10:05,529) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[43297:MainThread](2026-10-18 20:10:05,530) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_day_night_supervision_20261018_execution')}

[43297:MainThread](2026-10-18 20:10:05,546) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[43297:MainThread](2026-10-18 20:10:05,561) WARNING - qlib.data - [data.py:665] - load calendar error: freq=1min, future=True; return current calendar!

[43297:MainThread](2026-10-18 20:10:05,561) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[43297:MainThread](2026-10-18 20:10:05,564) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x154e71af0>

backtest loop:   0%|          | 0/3778 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
[Identical warning occurred 946 times in this output block; repetition collapsed only for slim-card display. The full original executed notebook SHA is recorded in execution_receipt.json.]

completed native B_day_night_total_0

[43297:MainThread](2026-10-18 20:10:08,802) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[43297:MainThread](2026-10-18 20:10:08,803) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[43297:MainThread](2026-10-18 20:10:08,803) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_day_night_supervision_20261018_execution')}

[43297:MainThread](2026-10-18 20:10:08,819) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[43297:MainThread](2026-10-18 20:10:08,833) WARNING - qlib.data - [data.py:665] - load calendar error: freq=1min, future=True; return current calendar!

[43297:MainThread](2026-10-18 20:10:08,833) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[43297:MainThread](2026-10-18 20:10:08,836) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x16710cf80>

backtest loop:   0%|          | 0/3778 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
[Identical warning occurred 946 times in this output block; repetition collapsed only for slim-card display. The full original executed notebook SHA is recorded in execution_receipt.json.]

completed native B_day_night_total_2

[43297:MainThread](2026-10-18 20:10:12,101) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[43297:MainThread](2026-10-18 20:10:12,102) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[43297:MainThread](2026-10-18 20:10:12,102) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_day_night_supervision_20261018_execution')}

[43297:MainThread](2026-10-18 20:10:12,119) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[43297:MainThread](2026-10-18 20:10:12,132) WARNING - qlib.data - [data.py:665] - load calendar error: freq=1min, future=True; return current calendar!

[43297:MainThread](2026-10-18 20:10:12,133) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[43297:MainThread](2026-10-18 20:10:12,135) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x1766d47a0>

backtest loop:   0%|          | 0/3778 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
[Identical warning occurred 946 times in this output block; repetition collapsed only for slim-card display. The full original executed notebook SHA is recorded in execution_receipt.json.]

completed native B_day_night_total_5

[43297:MainThread](2026-10-18 20:10:16,789) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[43297:MainThread](2026-10-18 20:10:16,790) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[43297:MainThread](2026-10-18 20:10:16,791) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_day_night_supervision_20261018_execution')}

[43297:MainThread](2026-10-18 20:10:16,807) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[43297:MainThread](2026-10-18 20:10:16,821) WARNING - qlib.data - [data.py:665] - load calendar error: freq=1min, future=True; return current calendar!

[43297:MainThread](2026-10-18 20:10:16,821) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[43297:MainThread](2026-10-18 20:10:16,824) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x17d26ed50>

backtest loop:   0%|          | 0/3778 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
[Identical warning occurred 946 times in this output block; repetition collapsed only for slim-card display. The full original executed notebook SHA is recorded in execution_receipt.json.]

completed native C_day_night_contrast_0

[43297:MainThread](2026-10-18 20:10:20,075) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[43297:MainThread](2026-10-18 20:10:20,076) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[43297:MainThread](2026-10-18 20:10:20,077) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_day_night_supervision_20261018_execution')}

[43297:MainThread](2026-10-18 20:10:20,094) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[43297:MainThread](2026-10-18 20:10:20,107) WARNING - qlib.data - [data.py:665] - load calendar error: freq=1min, future=True; return current calendar!

[43297:MainThread](2026-10-18 20:10:20,107) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[43297:MainThread](2026-10-18 20:10:20,110) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x15c3894f0>

backtest loop:   0%|          | 0/3778 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
[Identical warning occurred 946 times in this output block; repetition collapsed only for slim-card display. The full original executed notebook SHA is recorded in execution_receipt.json.]

completed native C_day_night_contrast_2

[43297:MainThread](2026-10-18 20:10:23,451) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[43297:MainThread](2026-10-18 20:10:23,452) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[43297:MainThread](2026-10-18 20:10:23,453) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_day_night_supervision_20261018_execution')}

[43297:MainThread](2026-10-18 20:10:23,471) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[43297:MainThread](2026-10-18 20:10:23,486) WARNING - qlib.data - [data.py:665] - load calendar error: freq=1min, future=True; return current calendar!

[43297:MainThread](2026-10-18 20:10:23,486) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[43297:MainThread](2026-10-18 20:10:23,489) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x17a96e2d0>

backtest loop:   0%|          | 0/3778 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
[Identical warning occurred 946 times in this output block; repetition collapsed only for slim-card display. The full original executed notebook SHA is recorded in execution_receipt.json.]

completed native C_day_night_contrast_5

[43297:MainThread](2026-10-18 20:10:31,177) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | waiting `async_log` Done

{'decision': 'not_promoted_fixed_day_night_supervision',
 'recorder_id': 'fd026924cf24465b918ec4ebd04ca639',
 'new_fits': 6,
 'new_native_accounts': 6,
 'gates': {'net_relative_wealth_all_costs': False,
  'sampled_drawdown_30pct': True,
  'cvar_no_worse_soxx': True,
  'minimum_complete_years': True,
  'complete_annual_70pct': False,
  'rolling126_70pct': False,
  'paired_block_lower_positive': False,
  'fresh_fullminute_risk_qualified': False,
  'qualified_independent_forward': False},
 'nas_evidence': {'sha256': 'c992d899300006d90a90080b1fcefd183e85d55913a92bb2d615590326f056f7',
  'size_bytes': 24565252,
  'media_type': 'application/gzip',
  'storage_uri': 'sha256/c9/92/c992d899300006d90a90080b1fcefd183e85d55913a92bb2d615590326f056f7',
  'uploaded_by': 'soxl-minute-research',
  'created_at': '2026-10-18 20:10:38.190242+08',
  'duplicate': False,
  'nas_path': '/volume1/docker/yanxuan/registry/research-artifacts/c9/92/c992d899300006d90a90080b1fcefd183e85d55913a92bb2d615590326f056f7',
  'recorder_id': 'fd026924cf24465b918ec4ebd04ca639',
  'experiment_id': '146240142478072451',
  'archive_root': 'qlib_recorder'}}

## 配对、费用与证据含义

两套目标只在获准训练域预检中各拟合一次float64均值/sample std(ddof=1)，标准化后仅一次float32转换；六fit复用同一冻结常数，不做clip/epsilon救援。原combined loss后才加0.02×half-MSE；仍一次combined backward、全982参数global clip2、AdamW。零head首步直接encoder梯度为0，但head梯度可经globalclip改变private更新，不能将结果归于单纯encoder语义。

原目标还是H1 open→next-open allocation、H5 tail/alpha/cash与原共同成熟筛选。S/Z来自已独评接受的July24分配调整研究价格平面，不是现金股利账本、原daily-reset alpha或实际09:47成交标签。

账户预算为2个等权ensemble×3个费用=6条独立自身状态政策路径/6新native，另复用15本参考，共21比较与15预先固定CI。所有成本/seed保留，MSE/AUC不是账户执行门。0新市场来源查询不等于完全不读账户价格：六模型屏障后获准解码固定raw_points/market，并生成/读取本卡Qlib execution provider；不构造S/Z评价标签。

In [2]:
display(Markdown((CARD / "conclusion.md").read_text()))

# 固定 H5 日夜监督：配对实验

完成B(S)/C(Z)各3seed固定300epoch，全部6模型封存后才读取评价对象。原3014/20741、39/16输入及H1/H5目标保留；新监督仅追加87列Dataset的独立S/Z组，推理不需新标签。原973参数后加同9参数零head，保留单次全局clip及AdamW，整体监督/优化路径为处理。

两固定等权ensemble各自0/2/5费用与内生状态，6独立政策路径/6新native及15旧references；不按训练MSE、分类分数或seed表现选择账户。

| 费用bp | C累计收益% | 匹配B累计收益% | SOXX累计收益% | C收盘最大回撤% |
|---:|---:|---:|---:|---:|
| 0 | 259.741 | 287.017 | 380.588 | -26.925 |
| 2 | 255.435 | 354.279 | 380.568 | -26.951 |
| 5 | 191.199 | 190.485 | 380.538 | -27.181 |

结论：`not_promoted_fixed_day_night_supervision`。全部年度/季度及126期滚动和15CI保留；训练MSE仅是不同目标的训练诊断，不是alpha或晋升证据。

历史已复用，PIT、独立前向及新fullminute风险资格仍未满足；不自动晋升、不救援head/权重/seed/阈值。下一步为独立结果验收，任何失败归因须另定有界范围。

# 固定 S/Z 监督：完整实验未晋升

一次正式 notebook `85921` exit 0。按预定交错顺序完成 B(S)/C(Z) 各3seed、各300epoch，共6个模型；六个最终model SHA全部封存后才读取评价对象。随后完成2个固定等权ensemble×0/2/5bp的6条独立自身状态政策路径/6新native，复用15本参考，共21组账户和全部15个预登记配对CI。每本944区间/3778价格点，全部seed和费用保留，没有中途分数筛选或重训。

原3014/20741、39/16输入、全部H1/H5目标与时钟不变。新9参数零回归头只用于训练监督；B学S、C学Z，推理忽略新头。两套尺度在预检一次冻结。原combined loss后追加0.02×half-MSE，全982参数仍单次global clip2和AdamW；整体监督/优化路径是处理，不能归于被单独证明的encoder因果。

| 费用bp | C累计净收益% | 匹配B累计净收益% | 原B累计净收益% | A同源重放累计净收益% | SOXX累计净收益% | strong9097累计净收益% |
|---:|---:|---:|---:|---:|---:|---:|
| 0 | 259.741 | 287.017 | 280.383 | 229.686 | 380.588 | 441.681 |
| 2 | 255.435 | 354.279 | 270.223 | 280.650 | 380.568 | 434.269 |
| 5 | 191.199 | 190.485 | 265.858 | 41.521 | 380.538 | 423.730 |

C三费用的收盘及现有采样点回撤均小于30%，CVaR也不劣于SOXX；但完整财富门、年度70%、126区间滚动70%与配对CI门均失败，**15/15 CI下界未严格大于0**。2bp C收盘DD为−26.951%、采样点DD为−27.512%，CVaR5为−4.301%；风险门通过不能替代稳定超额。

| 费用bp | C相对SOXX：2023 partial% | 2024完整% | 2025完整% | 2026 partial% | 819个滚动窗口正超额比例% |
|---:|---:|---:|---:|---:|---:|
| 0 | -14.865 | 17.970 | -16.565 | -10.671 | 31.136 |
| 2 | -15.141 | 17.615 | -16.853 | -10.875 | 30.403 |
| 5 | -15.464 | 9.147 | -26.367 | -10.806 | 24.664 |

两完整年度中各成本均仅2024胜SOXX、2025落后，即1/2，未达到70%。全部年度/季度小表及原生authority月度、完整滚动表均保留，无挑选窗口。B2bp收益高于B0bp来自各成本独立内生状态路径，不能当作简单费用扣减或控制器单因果结论；本次没有另做失败归因或账户重放。

固定版本决定：`not_promoted_fixed_day_night_supervision`。匹配B不是可在结果后替换的候选，C5bp仅略胜B不构成成功；不改head、权重、符号、seed、窗口或控制器救援。独立评估已接受负结果并关闭固定版本；owner唯一冷读通过，执行者没有签署promotion。

0新市场来源HTTP、0新S/Z评价标签，现役release未改；屏障后对已冻结raw_points/market与本卡派生Qlib execution provider的真实读取属于账户证据，不假称完全没有价格读取。历史已复用，三seed不等于独立市场样本，PIT/独立前向/fullminute资格仍未满足。

Recorder `fd026924cf24465b918ec4ebd04ca639`；88个artifacts，NAS `c992d899300006d90a90080b1fcefd183e85d55913a92bb2d615590326f056f7`。见 [完整结果](summary.json)、[身份清单](verification_manifest.json)、[执行收据](execution_receipt.json)、[候选元数据](selected_model.json)、[15个CI](uncertainty.csv)。大模型/optimizer/1800条loss trace、预测、原生账户、月度与滚动结果全部在Recorder。封存的88个对象和NAS不因文字同步重算或重封。

独立结果验收与owner唯一冷读均已完成。另行获准的一次Recorder-only归因见下文；没有重训、重放或参数救援。固定版本关闭，整体稳定跑赢SOXX目标尚未实现。

## 另一次已批准的只读归因
以下cell来自独立临时kernel的一次exec6809，execution_count=1是该kernel真实计数；主训练/账户cell没有重跑。首正式结果已在Git9ff0868a保留。

In [1]:
import os
from pathlib import Path
from IPython.display import display
from src.analysis.day_night_supervision_attribution import run
ROOT = Path("/Users/rziiiii/dev/workspace")
CARD = ROOT / "research/stage1_day_night_supervision_20261018"
if os.environ.get("DAY_NIGHT_ATTRIBUTION") == "1":
    attribution = run(root=ROOT, card=CARD)
    display(attribution["path_summary"])
    display(attribution["rolling_summary"])
    display(attribution["training_sampling"])
else:
    display({"status": "attribution_requires_explicit_env; see frozen attribution_scope.json"})

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[47292:MainThread](2026-10-18 20:30:52,797) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

2026/10/18 20:30:53 INFO mlflow.agent.hint: Load the `instrumenting-with-mlflow-tracing` skill at /Users/rziiiii/dev/workspace/qlib_venv/lib/python3.12/site-packages/mlflow/assistant/skills/instrumenting-with-mlflow-tracing/SKILL.md before writing any tracing code; it ships with this MLflow install. Set MLFLOW_DISABLE_AGENT_HINT=1 to silence this.

[47292:MainThread](2026-10-18 20:30:53,277) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[47292:MainThread](2026-10-18 20:30:53,278) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_day_night_supervision_20261018_execution')}

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

,family,slippage_bps,sessions,net_return_pct,raw_mean_nominal_beta,raw_mean_cash_weight,smoothed_mean_nominal_beta,smoothed_mean_cash_weight,actual_mean_ending_nominal_beta,actual_mean_ending_soxl_weight,actual_mean_ending_soxx_weight,actual_mean_ending_cash_like_weight,actual_mean_spendable_cash_usd,zero_SOXL_sessions,zero_SOXL_fraction,nonzero_risk_state_sessions,open_execute_sessions,firsthour_recovery_sessions,risk_state_counts,risk_clock_counts
0,B_day_night_total,0,944,287.017381,1.068083,0.381913,1.068398,0.382010,0.858151,0.159335,0.380147,0.460518,97669.300036,213,0.225636,353,802,0,"{""0"": 591, ""1"": 60, ""2"": 150, ""3"": 143}","{""0"": 621, ""1"": 45, ""2"": 45, ""3"": 44, ""4"": 44,..."
1,B_day_night_total,2,944,354.279263,1.068083,0.381913,1.068398,0.382010,0.870049,0.162739,0.381832,0.455429,105625.863250,199,0.210805,329,803,0,"{""0"": 615, ""1"": 56, ""2"": 140, ""3"": 133}","{""0"": 643, ""1"": 42, ""2"": 42, ""3"": 41, ""4"": 41,..."
2,B_day_night_total,5,944,190.485314,1.068083,0.381913,1.068398,0.382010,0.819349,0.147863,0.375760,0.476377,87327.137322,253,0.268008,425,805,0,"{""0"": 519, ""1"": 72, ""2"": 180, ""3"": 173}","{""0"": 555, ""1"": 54, ""2"": 54, ""3"": 53, ""4"": 53,..."
3,C_day_night_contrast,0,944,259.741039,1.073730,0.378407,1.074081,0.378481,0.856155,0.157746,0.382916,0.459338,93897.018954,233,0.246822,353,799,0,"{""0"": 591, ""1"": 60, ""2"": 150, ""3"": 143}","{""0"": 621, ""1"": 45, ""2"": 45, ""3"": 44, ""4"": 44,..."
4,C_day_night_contrast,2,944,255.434539,1.073730,0.378407,1.074081,0.378481,0.856170,0.157742,0.382945,0.459313,93184.520719,233,0.246822,353,803,0,"{""0"": 591, ""1"": 60, ""2"": 150, ""3"": 143}","{""0"": 621, ""1"": 45, ""2"": 45, ""3"": 44, ""4"": 44,..."
5,C_day_night_contrast,5,944,191.199230,1.073730,0.378407,1.074081,0.378481,0.811982,0.144930,0.377191,0.477879,85367.423351,270,0.286017,449,799,0,"{""0"": 495, ""1"": 76, ""2"": 190, ""3"": 183}","{""0"": 533, ""1"": 57, ""2"": 57, ""3"": 56, ""4"": 56,..."

,slippage_bps,comparator,windows,first_window_trade,last_window_exit,positive_windows,positive_fraction,minimum_relative_log,maximum_relative_log,mean_relative_log,overlapping_not_independent,method
0,0,B_day_night_total,819,2023-01-04 00:00:00,2026-10-09 00:00:00,264,0.322344,-0.109917,0.077285,-0.009934,True,Subtract the two stored SOXX-relative log wind...
1,0,SOXX,819,2023-01-04 00:00:00,2026-10-09 00:00:00,255,0.311355,-0.213839,0.147055,-0.031524,True,Subtract the two stored SOXX-relative log wind...
2,2,B_day_night_total,819,2023-01-04 00:00:00,2026-10-09 00:00:00,266,0.324786,-0.286921,0.077600,-0.036429,True,Subtract the two stored SOXX-relative log wind...
3,2,SOXX,819,2023-01-04 00:00:00,2026-10-09 00:00:00,249,0.304029,-0.215391,0.145644,-0.033180,True,Subtract the two stored SOXX-relative log wind...
4,5,B_day_night_total,819,2023-01-04 00:00:00,2026-10-09 00:00:00,312,0.380952,-0.121558,0.151397,0.001015,True,Subtract the two stored SOXX-relative log wind...
5,5,SOXX,819,2023-01-04 00:00:00,2026-10-09 00:00:00,202,0.246642,-0.334074,0.143160,-0.064239,True,Subtract the two stored SOXX-relative log wind...

,seed,paired_epochs,sampling_hash_equal_epochs,sampling_hash_all_equal,first_sampling_difference_epoch,sampling_hash_check_only,allocation_loss_last_C_minus_B,allocation_loss_all_step_MAE,primary_bce_last_C_minus_B,primary_bce_all_step_MAE,auxiliary_bce_last_C_minus_B,auxiliary_bce_all_step_MAE,original_loss_last_C_minus_B,original_loss_all_step_MAE,loss_last_C_minus_B,loss_all_step_MAE
0,71,300,300,True,None,Recorded hashes compared; no RNG resampling or...,-2.089073e-07,0.000003,-0.000961,0.001000,0.000425,0.000346,0.000002,0.000020,0.000056,0.000034
1,172,300,300,True,None,Recorded hashes compared; no RNG resampling or...,4.245259e-06,0.000008,-0.001456,0.000942,0.000583,0.000490,0.000004,0.000036,0.000166,0.000115
2,273,300,300,True,None,Recorded hashes compared; no RNG resampling or...,3.809715e-05,0.000009,0.000037,0.000432,0.000653,0.000474,0.000071,0.000030,0.000221,0.000104

# 一次 Recorder-only 失败归因

事前范围见 [attribution_scope.json](attribution_scope.json)。唯一归因执行 `6809` exit0，只读取同一个已封存 fd0269 Recorder 的27个白名单对象，生成4张小表：396条完整期间比较、6条路径汇总、54条状态/持仓差异、6条训练汇总。全部年度/季度/月度以及每费用819滚动窗口保留；0fit/forward/gradient/optimizer/replay/native/CI重抽/新数据/NAS下载。

同seed的300步aux采样hash逐步相等，共900/900配对一致。六条trace均完整300步；新增监督各自训练误差下降，但S与Z是不同目标，不能把两种MSE大小解读为alpha排名或评价预测性。C在三个seed的末步原combined训练loss均略高于B（约1.80e−6、4.26e−6、7.15e−5）；这只是训练目标路径描述。所有1800步最大preclip norm约0.03704，远低于2，实际没有触发裁剪；不能把设计中可能的globalclip耦合当成本轮已经发生的原因。

原始提议的平均名义β（3×SOXL+SOXX）C1.073730、B1.068083，平均现金C37.8407%、B38.1913%。C−B的现金MAE为2.0172个百分点、β MAE0.040136；保存的平滑后现金MAE为1.8288个百分点、β MAE0.036743。学习改变已经传入提议，不能称为“完全没有干预”。下表为全部费用的实际期末持仓均值，cash-like包括应收款，名义β不是回归估计的市场β。

| 费用bp | B实际名义β | C实际名义β | B现金like% | C现金like% | B零SOXL日 | C零SOXL日 | B非零risk日 | C非零risk日 |
|---:|---:|---:|---:|---:|---:|---:|---:|---:|
| 0 | 0.858151 | 0.856155 | 46.0518 | 45.9338 | 213 | 233 | 353 | 353 |
| 2 | 0.870049 | 0.856170 | 45.5429 | 45.9313 | 199 | 233 | 329 | 353 |
| 5 | 0.819349 | 0.811982 | 47.6377 | 47.7879 | 253 | 270 | 425 | 449 |

2bp下，C/B的risk_state有51日不同、risk_clock有124日不同，首个分歧均为2023-04-25；open execute有80日不同、首日2023-02-15。六个账户的first-hour recovery均0。C提议β更高而实际β更低、cash-like更高，显示提议到账户的内生传递发生变化；均值/计数不能识别单一控制器或费用的因果贡献。

成本路径确有分叉：B的0/2、0/5、2/5bp risk_state分别有32、135、142日不同；C的0/2bp risk_state与clock完全相同，但open execute仍有8日不同，C的0/5和2/5bp risk_state各有96日不同（首日2024-01-04）。因此不能把各成本收益看作统一持仓路径的线性扣费。全部首差日期与动作/暴露MAE保留在 [状态差异表](attribution_state_differences.csv)。

| 费用bp | C胜B完整年 | C胜SOXX完整年 | C胜B全部季度 | C胜SOXX全部季度 | C胜B全部月份 | C胜SOXX全部月份 | rolling C>B% | rolling C>SOXX% |
|---:|---:|---:|---:|---:|---:|---:|---:|---:|
| 0 | 1/2 | 1/2 | 7/16 | 8/16 | 19/46 | 19/46 | 32.234 | 31.136 |
| 2 | 1/2 | 1/2 | 7/16 | 8/16 | 19/46 | 18/46 | 32.479 | 30.403 |
| 5 | 2/2 | 1/2 | 8/16 | 7/16 | 20/46 | 16/46 | 38.095 | 24.664 |

年度完整2024/2025，2023/2026为partial；全部16季度包含14完整与2partial，全部46月份包含44完整与2partial，完整/partial各自计数在JSON和396条期间表中全部保留。5bp C对匹配B的局部年度优势未转化为对SOXX或全成本稳定超额，也不能将B改选成候选。滚动窗口重叠，不是819个独立样本。

已有原H5分类中，ensemble tail AUC B0.601414→C0.603673，alpha AUC B0.492664→C0.493242；描述性变化很小，alpha区分度仍接近随机。全部seed与ensemble原分类指标保留在 [归因JSON](failure_attribution.json)，未创建S/Z评价标签或计算其IC/MSE，不能据此断言Z本身普遍不可预测。

结论：固定监督确实改变了学习/提议/实际持仓和内生状态，但完整经济证据仍不足：全部15CI失败、年度及rolling门未过。独立评估已接受负结果并关闭版本，owner唯一冷读通过。禁止以这些诊断调整λ/head/seed/窗口/方向或做控制器救援。

计算来源均是已保存的原生authority、原提议/平滑提议、现有期间/滚动表、300步训练trace和原分类summary；主阶段88对象/manifest/NAS保持不变。未进行反事实、消融、重采样或新的账户计算。