# ETF迁移失败归因：固定历史账户
只读保存的Qlib实际持仓与账户，无拟合、无新账户、无晋升。按冻结计划分解均值暴露和协变贡献，二者是会计描述而非可交易反事实。

In [1]:
import os
os.environ['MLFLOW_ALLOW_FILE_STORE']='true'
from pathlib import Path
import sys
root = Path.cwd()
while not (root / 'SPEC.md').exists(): root = root.parent
sys.path.insert(0, str(root))
import qlib
from qlib.data import D
from qlib.workflow import R
qlib.init(provider_uri=str(root/'data/qlib/frozen_policy_raw_cashbook_20261015'), region='us', kernels=1)
from src.analysis.etf_transfer_attribution import run
summary = run(root)
summary

2026/10/16 11:19:07 INFO mlflow.agent.hint: Load the `instrumenting-with-mlflow-tracing` skill at /Users/rziiiii/dev/workspace/qlib_venv/lib/python3.12/site-packages/mlflow/assistant/skills/instrumenting-with-mlflow-tracing/SKILL.md before writing any tracing code; it ships with this MLflow install. Set MLFLOW_DISABLE_AGENT_HINT=1 to silence this.

[72627:MainThread](2026-10-16 11:19:07,923) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[72627:MainThread](2026-10-16 11:19:07,925) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[72627:MainThread](2026-10-16 11:19:07,925) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/frozen_policy_raw_cashbook_20261015')}

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[72627:MainThread](2026-10-16 11:19:09,767) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[72627:MainThread](2026-10-16 11:19:09,768) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[72627:MainThread](2026-10-16 11:19:09,769) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[72627:MainThread](2026-10-16 11:19:09,775) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[72627:MainThread](2026-10-16 11:19:09,775) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[72627:MainThread](2026-10-16 11:19:09,776) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/frozen_policy_raw_cashbook_20261015')}

[72627:MainThread](2026-10-16 11:19:42,898) WARNING - qlib.workflow - [expm.py:231] - No valid experiment found. Create a new experiment with name etf_transfer_attribution_20261016.

[72627:MainThread](2026-10-16 11:19:42,900) INFO - qlib.workflow - [exp.py:258] - Experiment 480520621315149975 starts running ...

[72627:MainThread](2026-10-16 11:19:42,981) INFO - qlib.workflow - [recorder.py:345] - Recorder 1a3e5cd71d6e4887b87adc01fee7ebb9 starts running under Experiment 480520621315149975 ...

[72627:MainThread](2026-10-16 11:19:47,209) INFO - qlib.timer - [log.py:127] - Time cost: 0.002s | waiting `async_log` Done

{'experiment': 'etf_transfer_attribution_20261016',
 'plan_sha256': '6c0c30a1ecc34fc4421bd34e1f96ba431ddafb27c5115146bae48925f63b097f',
 'decision': 'descriptive_diagnosis_only_parent_routes_remain_not_promoted',
 'objective_achieved': False,
 'new_fits': 0,
 'new_inference': 0,
 'new_policy_accounts': 0,
 'daily_books': 12,
 'max_daily_return_closure_error': 5.030698080332741e-16,
 'calendar_rows_per_book': 944,
 'rolling_windows_per_book': 819,
 'provider_uri': '/Users/rziiiii/dev/workspace/data/qlib/frozen_policy_raw_cashbook_20261015',
 'region': 'us',
 'as_of': '2026-10-09',
 'qlib_docs': 'https://qlib.readthedocs.io/en/latest/component/workflow.html',
 'recorder_id': '1a3e5cd71d6e4887b87adc01fee7ebb9',
 'experiment_id': '480520621315149975',
 'recorder_uri': '/Users/rziiiii/dev/workspace/research/etf_transfer_attribution_20261016/qlib_recorder',
 'recorder_local_dir': '/Users/rziiiii/dev/workspace/research/etf_transfer_attribution_20261016/qlib_recorder/480520621315149975/1a3e5cd71d6e4887b87adc01fee7ebb9',
 'artifact_policy': {'policy': 'slim_card_recorder_first',
  'workflow_config': 'workflow.yaml',
  'recorder_only_artifacts': ['inputs/*',
   'analysis/daily',
   'analysis/segments',
   'analysis/rolling*',
   'sources/*']},
 'limitations': ['Historical development diagnosis, not independent evidence',
  'Mean exposure and covariance are additive arithmetic return contributions, not tradable counterfactual or compounded allocation alpha',
  'Controller target differences include legal projection, smoothing and endogenous risk path; no controller-off account',
  'Inherited raw cash corporate convention and sampled risk coverage remain unqualified for promotion'],
 'nas_evidence': {'sha256': 'f85d46716ace35dab54d6c4ce89d9edc623c187507c3a328e55f9337b73933ab',
  'size_bytes': 18845227,
  'media_type': 'application/gzip',
  'storage_uri': 'sha256/f8/5d/f85d46716ace35dab54d6c4ce89d9edc623c187507c3a328e55f9337b73933ab',
  'uploaded_by': 'soxl-minute-research',
  'created_at': '2026-10-16 11:19:52.145499+08',
  'duplicate': False,
  'nas_path': '/volume1/docker/yanxuan/registry/research-artifacts/f8/5d/f85d46716ace35dab54d6c4ce89d9edc623c187507c3a328e55f9337b73933ab',
  'recorder_id': '1a3e5cd71d6e4887b87adc01fee7ebb9',
  'experiment_id': '480520621315149975',
  'archive_root': 'qlib_recorder'}}

In [2]:
import pandas as pd
card=root/'research/etf_transfer_attribution_20261016'
period=pd.read_csv(card/'period_summary.csv')
components=pd.read_csv(card/'paired_components.csv')
display(period[(period.kind=='all') & (period.slippage_bps==2)])
display(components[(components.kind=='all') & (components.slippage_bps==2)])

,parent,arm,slippage_bps,kind,period,partial_boundary_period,sessions,first_trade,last_exit,compounded_return,SOXL_contribution,SOXX_contribution,fee_contribution,max_closure_error,soxl_raw_minus_controlled_mean,soxx_raw_minus_controlled_mean,cash_raw_minus_controlled_mean
42,generic_index_risk_transfer_20261015,control,2,all,all,False,944,2023-01-04,2026-10-09,3.920362,0.412012,1.409576,-0.020430,4.076600e-16,0.171902,-0.258697,0.086795
63,generic_index_risk_transfer_20261015,candidate,2,all,all,False,944,2023-01-04,2026-10-09,4.185515,0.398586,1.467903,-0.020102,3.920475e-16,0.179790,-0.275002,0.095212
168,family_balanced_direct_utility_training_20261015,control,2,all,all,False,944,2023-01-04,2026-10-09,1.991385,0.096449,1.175153,-0.023990,3.434752e-16,0.147330,-0.199158,0.051827
189,family_balanced_direct_utility_training_20261015,candidate,2,all,all,False,944,2023-01-04,2026-10-09,2.382594,0.124064,1.233818,-0.015847,3.608225e-16,0.136310,-0.136381,0.000071

,parent,slippage_bps,kind,period,asset,slot,mean_exposure_contribution_delta,covariance_contribution_delta,total_contribution_delta,mean_weight_delta
168,generic_index_risk_transfer_20261015,2,all,all,SOXL,0,5.113845e-05,-0.002892,-0.002841,-0.003957
169,generic_index_risk_transfer_20261015,2,all,all,SOXL,1,-4.678733e-03,-0.011638,-0.016317,-0.003960
170,generic_index_risk_transfer_20261015,2,all,all,SOXL,2,-1.405888e-02,0.021748,0.007689,-0.003977
171,generic_index_risk_transfer_20261015,2,all,all,SOXL,3,-8.361069e-04,-0.001121,-0.001957,-0.003969
172,generic_index_risk_transfer_20261015,2,all,all,SOXX,0,-7.669143e-07,-0.007369,-0.007370,-0.001767
173,generic_index_risk_transfer_20261015,2,all,all,SOXX,1,-7.723044e-04,0.034453,0.033681,-0.001774
174,generic_index_risk_transfer_20261015,2,all,all,SOXX,2,-2.309629e-03,0.037444,0.035135,-0.001739
175,generic_index_risk_transfer_20261015,2,all,all,SOXX,3,-1.303801e-04,-0.002988,-0.003118,-0.001700
672,family_balanced_direct_utility_training_20261015,2,all,all,SOXL,0,1.830092e-04,-0.001977,-0.001794,-0.014160
673,family_balanced_direct_utility_training_20261015,2,all,all,SOXL,1,-1.673330e-02,0.037231,0.020498,-0.014162
674,family_balanced_direct_utility_training_20261015,2,all,all,SOXL,2,-4.998573e-02,0.069073,0.019087,-0.014140
675,family_balanced_direct_utility_training_20261015,2,all,all,SOXL,3,-2.974703e-03,-0.007201,-0.010175,-0.014120
676,family_balanced_direct_utility_training_20261015,2,all,all,SOXX,0,-2.390327e-05,-0.044395,-0.044419,-0.055060
677,family_balanced_direct_utility_training_20261015,2,all,all,SOXX,1,-2.398583e-02,0.025968,0.001982,-0.055107
678,family_balanced_direct_utility_training_20261015,2,all,all,SOXX,2,-7.320043e-02,0.201536,0.128336,-0.055105
679,family_balanced_direct_utility_training_20261015,2,all,all,SOXX,3,-4.215059e-03,-0.023019,-0.027234,-0.054967

# 固定迁移实验归因结论

读取两张父卡的12个Qlib实际账户（各control/candidate×0/2/5bp），没有重新拟合、推理或回测。每账户944日；全部年度、季度以及819个连续126日窗口均保留。实际持仓四段收益、拆股/除息与原始费用重建日收益，最大误差5.03e-16；支付日仅转移应收款，不重复记收益。2bp为主分析，0/5bp为完整保留核对。

2bp结果：通用指数尾部迁移候选累计418.55%，配对对照392.04%。算术日收益加总差异中，平均暴露项−2.274个百分点，暴露与资产回报协变项+6.764个百分点，费用差异+0.033个百分点。家族混合训练候选累计238.26%，对照199.14%；平均暴露项−17.094个百分点、协变项+25.722个百分点、费用差异+0.814个百分点。前两项是在每种资产与持有时段内的population covariance恒等分解；这些数字不是累计收益百分点、不是恒定仓位反事实，也不证明可预测性。

收益差异明显依赖区间。指数迁移在2023部分年和2024分别落后配对对照约0.80和0.75个百分点，2025和2026部分年分别领先5.15和5.46个百分点；家族混合在2023部分年与2024落后约26.58和13.05个百分点，2025与2026部分年领先33.24和24.21个百分点。2023起点不完整，2026尚未结束；完整年按Qlib交易日覆盖核对，仅2024、2025。全部季度和126日窗口保留，不挑选胜出区间。先验趋势状态与内生账户风险状态分别汇总，不把事后胜负作为特征。

原始目标与实际开盘目标差异很大。例如指数候选原始SOXL目标平均比受控目标高17.98个百分点，原始SOXX低27.50个百分点；家族候选分别高13.63与低13.64个百分点。差异包含合法投影和账户风险路径，未运行控制器消融，不能归因于某一控制器组件。

复用原尾部评分Recorder：940个成熟标签、4个未知；候选logloss0.434972差于对照0.343716，Brier0.133975差于0.098389。候选预测均值27.47%，事件频率11.17%。因此“最终财富提高”不支持“风险预测更准确”；正协变项也不解决滚动稳定性、校准和独立验证问题。

不晋升；两张父卡保持封闭。所有历史均为已使用诊断数据，historical PIT、完整分钟风险和独立前向资格仍未取得。所有SOXX与强参考、父门禁和父滚动比较已保留在Recorder的analysis/parent_reference。下一步是新的ETF估值/盈利周期信息机制资格检验，不重开本次迁移参数搜索，也不因单支线等待前向而结束研究目标。

证据入口：plan.json、design_review.json、summary.json、period_summary.csv、component_summary.csv、paired_components.csv、state_summary.csv、readback.json；大日表、持有段表和全部滚动分解留在Recorder/NAS。

Qlib Recorder：`1a3e5cd71d6e4887b87adc01fee7ebb9`；NAS SHA256：`f85d46716ace35dab54d6c4ce89d9edc623c187507c3a328e55f9337b73933ab`。