# Intraday recovery direct SOXL/SOXX/cash allocation

假设：日频模型的主要问题不是缺少趋势 alpha，而是回撤期用全天 cash 防守，导致恢复过慢。前四根 15 分钟 bar 只在 10:30 后使用，模型直接输出合法三资产仓位。

In [1]:
from pathlib import Path
import json
import sys
import pandas as pd
from IPython.display import Markdown, display

ROOT = Path.cwd().resolve()
while not (ROOT / 'AGENTS.md').exists():
    ROOT = ROOT.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from src.workflow.intraday_recovery_direct_allocation import run_intraday_recovery_direct_allocation_card

summary = run_intraday_recovery_direct_allocation_card(root=ROOT)
summary['decision']

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[7335:MainThread](2026-07-24 22:06:26,961) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[7335:MainThread](2026-07-24 22:06:27,396) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[7335:MainThread](2026-07-24 22:06:27,397) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[7335:MainThread](2026-07-24 22:06:27,418) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[7335:MainThread](2026-07-24 22:06:27,419) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[7335:MainThread](2026-07-24 22:06:27,419) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[7335:MainThread](2026-07-24 22:06:27,701) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[7335:MainThread](2026-07-24 22:06:27,702) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[7335:MainThread](2026-07-24 22:06:27,702) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

[7335:MainThread](2026-07-24 22:06:27,805) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[7335:MainThread](2026-07-24 22:06:27,806) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[7335:MainThread](2026-07-24 22:06:27,807) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[7335:MainThread](2026-07-24 22:06:27,850) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[7335:MainThread](2026-07-24 22:06:27,852) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[7335:MainThread](2026-07-24 22:06:27,852) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[7335:MainThread](2026-07-24 22:06:46,548) INFO - qlib.workflow - [exp.py:258] - Experiment 903361124573160811 starts running ...

[7335:MainThread](2026-07-24 22:06:46,604) INFO - qlib.workflow - [recorder.py:345] - Recorder 3a2f919b802c48f08198fc9a93ec0a8b starts running under Experiment 903361124573160811 ...

[7335:MainThread](2026-07-24 22:06:47,253) INFO - qlib.timer - [log.py:127] - Time cost: 0.004s | waiting `async_log` Done

'promoted_research_candidate_intraday_recovery_direct_allocation'

In [2]:
CARD = ROOT / 'research' / 'intraday_recovery_direct_allocation_v1'
display(pd.read_csv(CARD / 'risk_analysis.csv'))
display(pd.read_csv(CARD / 'annual_metrics.csv'))
display(pd.read_csv(CARD / 'cost_sensitivity.csv'))

,variant,segment,cost_bps,terminal_wealth,return_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,worst_rolling_5d_pct,avg_cash_weight_pct
0,daily_risk_controller,outer_diagnostic,10.0,5.837056,483.705563,-27.445156,-9.383715,-5.177782,-11.332000,38.045939
1,selected_direct_intraday_recovery,outer_diagnostic,10.0,6.433420,543.342018,-28.105110,-9.383715,-5.233616,-11.602809,36.099520
2,selected_direct_intraday_recovery_fixed_decisions,outer_diagnostic,25.0,5.778015,477.801494,-29.088719,-9.383715,-5.244785,-11.780256,36.099520

,year,terminal_wealth,return_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,worst_rolling_5d_pct,terminal_wealth_ratio_vs_soxx,avg_cash_weight_pct,recovery_action_count
0,2023,1.417018,41.701820,-21.654737,-5.401288,-4.267416,-8.145412,0.903588,33.607854,3
1,2024,1.393222,39.322160,-18.027343,-7.390741,-4.679966,-10.092327,1.153524,41.863089,8
2,2025,1.619374,61.937445,-22.933951,-7.185336,-4.954944,-10.535412,1.094333,36.770167,14
3,2026,2.012329,101.232911,-21.716439,-9.383715,-7.133178,-11.602809,1.181760,28.820950,7

,variant,segment,cost_bps,terminal_wealth,return_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,worst_rolling_5d_pct,avg_cash_weight_pct
0,selected_direct_intraday_recovery,outer_diagnostic,10.0,6.433420,543.342018,-28.105110,-9.383715,-5.233616,-11.602809,36.09952
1,selected_direct_intraday_recovery_fixed_decisions,outer_diagnostic,25.0,5.778015,477.801494,-29.088719,-9.383715,-5.244785,-11.780256,36.09952

## 中文结论

In [3]:
display(Markdown((CARD / 'conclusion.md').read_text(encoding='utf-8')))

# 中文结论

- 做了什么：把原模型的 SOXL/SOXX/cash 合法仓位、alpha/tail 概率、组合自身回撤状态与开盘后前四根 15 分钟路径合并；模型在 10:30 直接重新输出三资产仓位，不再使用底仓加 overlay。
- 为什么之前现金过多：日频回撤状态机只能按整天降风险，错过反弹后又重复进入防守；收益损失来自现金时点，而不只是平均现金比例。
- 训练结构：教师标签判断“恢复到 1.2 beta 是否有正增量”，实际执行只恢复到 0.6 beta，用不对称 teacher-student 校准限制误判杠杆。
- 选择规则：只使用 2019-2022 开发期年度/两年窗口；2023-2026 outer 完全不参与模型、阈值或动作 beta 选择。
- 外层 10bp：return=543.3420%，MaxDD=-28.1051%，worst day=-9.3837%，CVaR5=-5.2336%，worst 5d=-11.6028%。
- 现金与收益：日频控制器 outer return=483.7056%，新模型提高 59.6365 个百分点；平均现金减少 1.9464 个百分点。
- 25bp 冻结决策压力：return=477.8015%，MaxDD=-29.0887%；只重算成本，不允许成本改变仓位路径。
- 效率门：return/MaxDD=19.3325，同平均风险 SOXL=11.8911，matched-beta=8.8808，均通过。旧版 SOXL upside capture=34.1178% 仍未过 60% 门；该旧门不属于当前“超过 SOXX 且保留现金”目标。
- 原模型差距：原模型 outer return=582.7327%，新模型仍少 39.3907 个百分点；尚未做到完全保持原收益。
- 是否晋升：promoted_research_candidate_intraday_recovery_direct_allocation。这是研究候选晋级，不是生产或实盘成交证明；仍缺 bid/ask、排队、延迟和 10:30 真实成交 replay。
- qlib recorder：3a2f919b802c48f08198fc9a93ec0a8b
- 不构成买卖建议。