# 旧 SOXL 规则修复与重新研究

假设：旧规则在保留默认阈值、整数下单与 LIFO 账本后，修复未来信息、重复状态变更、收盘信号同日成交、现金/费用记账，仍可在成本后稳定超过 SOXX。

先审计再固定一次实验，不搜索参数。价格使用已认证原生 Qlib SOXL/SOXX；VIX 使用另行冻结、原生读回的历史收盘序列。17:00 纽约时间做决策，下一交易日开盘执行。VIX 历史发布时间未逐日验证，此截止时间属于研究假设。

2016-01-04 起连续持仓至样本末；开发期 2016–2022 和 2023 年后复用诊断仅切片，不年度重置。另设 2026-08-03 现金启动诊断，使用完整前史做指标热身与前一收盘初始信号。每侧成本 0/10/25 bp；主门禁 10/25 bp。

直接比较同成本 SOXX/SOXL 买入持有，以及每日固定 50%/90% SOXL 配置。这两个固定配置是暴露参照，并非精确风险匹配。稳定门禁：开发期至少 6/7 年正超额、配对 stationary bootstrap 平均块长 20/60 的2.5% 分位下界大于零、回撤与 CVaR5 均不差于 SOXX。所有历史均已被研究过，不称新样本。

In [1]:
from pathlib import Path
import sys, json
root = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "SPEC.md").exists())
sys.path.insert(0, str(root))
card = root / "research/legacy_soxl_repair_20261005"
plan = json.loads((card / "plan.json").read_text())
import qlib
from qlib.data import D
from qlib.workflow import R
from src.workflow.legacy_soxl_repair import load_legacy_inputs, run_legacy_repair
frame, source_audit = load_legacy_inputs(root, plan)
qlib.init(provider_uri=str(root / plan["execution_provider_uri"]), region="us", kernels=1)
assert len(D.calendar(freq="day")) == len(frame)
print({"native_sessions": len(frame), "first": str(frame.date.min().date()), "last": str(frame.date.max().date()), "source": source_audit})

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[47088:MainThread](2026-10-05 09:45:01,328) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[47088:MainThread](2026-10-05 09:45:01,330) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[47088:MainThread](2026-10-05 09:45:01,331) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/data/qlib/published_futu_affine_20260925_v1')}

[47088:MainThread](2026-10-05 09:45:01,341) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[47088:MainThread](2026-10-05 09:45:01,342) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[47088:MainThread](2026-10-05 09:45:01,342) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/data/qlib/legacy_vix_20260925_v1')}

[47088:MainThread](2026-10-05 09:45:01,358) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[47088:MainThread](2026-10-05 09:45:01,359) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[47088:MainThread](2026-10-05 09:45:01,359) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/data/qlib/published_futu_affine_20260925_v1')}

[47088:MainThread](2026-10-05 09:45:01,381) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[47088:MainThread](2026-10-05 09:45:01,381) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[47088:MainThread](2026-10-05 09:45:01,382) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/data/qlib/published_futu_affine_20260925_v1')}

[47088:MainThread](2026-10-05 09:45:01,394) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[47088:MainThread](2026-10-05 09:45:01,395) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[47088:MainThread](2026-10-05 09:45:01,395) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/data/qlib/legacy_soxl_execution_20260925_v1')}

[47088:MainThread](2026-10-05 09:45:01,413) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[47088:MainThread](2026-10-05 09:45:01,414) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[47088:MainThread](2026-10-05 09:45:01,414) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/data/qlib/legacy_soxl_execution_20260925_v1')}

{'native_sessions': 4162, 'first': '2010-03-11', 'last': '2026-09-25', 'source': {'price': {'native_frame_sha256': 'b7a59f39feed5aed6e61fec2b4239092c474e453c91d4d133c73f9dcc571a03f', 'native_rows': 8324, 'calendar_sessions': 4162, 'provider_manifest_sha256': 'cbbdeeca2e1c7dc0bce0f9cdf3495f50d3219bddd992e1b893f8362a5e51bc65', 'provider_marker_canonical_sha256': 'f1953da3c171072f29fc1c6e96d17155d4099ffcacad5d835718ee6d26477e3d', 'provider_uri': 'data/qlib/published_futu_affine_20260925_v1'}, 'vix': {'provider_uri': 'data/qlib/legacy_vix_20260925_v1', 'snapshot_manifest': 'data/snapshots/legacy_vix_20260925_v1/manifest.json', 'snapshot_manifest_sha256': 'af685d0e8bfa556569a52b83d72e42c2785bfac1232455b1a5f5bb78825530fe', 'source_raw_sha256': '30b05f9249d00ce0068ca02c8905e4eb7508c3acacc6ed7a129b72805ce3c780', 'source_url': 'https://query1.finance.yahoo.com/v8/finance/chart/%5EVIX?period1=1268265600&period2=1790380800&interval=1d&includeAdjustedClose=false', 'retrieved_at': '2026-10-05T01:25:09.924700+00:00', 'as_of': '2026-09-25', 'reference_calendar': {'provider_uri': 'data/qlib/published_futu_affine_20260925_v1', 'manifest_sha256': 'b57e3d31e0dfc3042c254f30f0b78739800b2994bcb3af076a5820741a5e21bb', 'calendar_sha256': '2fc4d059b1c36c49cfe6a4617852106da96b12b3d5109a152b42acbf5b1fdc8a', 'calendar_rows': 4162, 'calendar_start': '2010-03-11', 'calendar_end': '2026-09-25', 'source_api': 'qlib.data.D.calendar'}, 'qualification': {'adjustment_policy': 'raw quote.close; no adjusted-close input, split adjustment, normalization, or missing-value filling', 'canonical_rows': 4162, 'excluded_noncanonical_dates': ['2010-04-02', '2010-05-31', '2010-07-05', '2010-09-06', '2010-11-25', '2010-12-24', '2011-01-17', '2011-02-21', '2011-04-22', '2011-05-30', '2011-07-04', '2011-09-05', '2011-11-24', '2011-12-26', '2012-01-02', '2012-01-16', '2012-02-20', '2012-04-06', '2012-05-28', '2012-07-04', '2012-09-03', '2012-10-29', '2012-10-30', '2012-11-22', '2012-12-25', '2013-01-01', '2013-01-21', '2013-02-18', '2013-03-29', '2013-05-27', '2013-07-04', '2013-09-02', '2013-11-28', '2013-12-25', '2014-01-01', '2014-01-20', '2014-02-17', '2014-04-18', '2014-05-26', '2014-07-04', '2014-09-01', '2014-11-27', '2014-12-25', '2015-01-01', '2015-01-19', '2015-02-16', '2015-04-03', '2015-05-25', '2015-07-03', '2015-09-07', '2015-11-26', '2015-12-25', '2016-01-01', '2016-01-18', '2016-02-15', '2016-03-25', '2016-05-30', '2016-07-04', '2016-09-05', '2016-11-24', '2016-12-26', '2017-01-02', '2017-01-16', '2017-02-20', '2017-04-14', '2017-05-29', '2017-07-04', '2017-09-04', '2017-11-23', '2017-12-25', '2018-01-01', '2018-01-15', '2018-02-19', '2018-03-30', '2018-05-28', '2018-07-04', '2018-09-03', '2018-11-22', '2018-12-05', '2018-12-25', '2019-01-01', '2019-01-21', '2019-02-18', '2019-04-19', '2019-05-27', '2019-07-04', '2019-09-02', '2019-11-28', '2019-12-25', '2020-01-01', '2020-01-20', '2020-02-17', '2020-04-10', '2020-05-25', '2020-07-03', '2020-09-07', '2020-11-26', '2020-12-25', '2021-01-01', '2021-01-18', '2021-02-15', '2021-04-02', '2021-05-31', '2021-07-05', '2021-09-06', '2021-11-25', '2021-12-24', '2022-01-17', '2022-02-21', '2022-04-15', '2022-05-30', '2022-06-20', '2022-07-04', '2022-09-05', '2022-11-24', '2022-12-26', '2023-01-02', '2023-01-16', '2023-02-20', '2023-04-07', '2023-05-29', '2023-06-19', '2023-07-04', '2023-09-04', '2023-11-23', '2023-12-25', '2024-01-01', '2024-01-15', '2024-02-19', '2024-03-29', '2024-05-27', '2024-06-19', '2024-07-04', '2024-09-02', '2024-11-28', '2024-12-25', '2025-01-01', '2025-01-09', '2025-01-20', '2025-02-17', '2025-04-18', '2025-05-26', '2025-06-19', '2025-07-04', '2025-09-01', '2025-11-27', '2025-12-25', '2026-01-01', '2026-01-19', '2026-02-16', '2026-04-03', '2026-05-25', '2026-06-19', '2026-07-03', '2026-09-07'], 'excluded_noncanonical_null_closes': 153, 'ignored_fields': 'All summary metadata and OHLCV fields other than historical close; metadata may postdate as_of.', 'missing_canonical_sessions': 0, 'source_rows': 4317, 'source_timezone': 'America/Chicago', 'used_fields': ['timestamp', 'indicators.quote[0].close']}, 'availability': {'assumed_available_local_time': '17:00', 'execution_eligibility': 'next canonical session open only', 'historical_publication_vintage_verified': False, 'limitation': 'As-retrieved Yahoo historical closes; historical revisions/publication vintages not verified.', 'timezone': 'America/New_York'}, 'native_readback': {'status': 'passed', 'rows': 4162, 'readback_sha256': 'e3675a984178e96cc1b6f4f746022a0e3da86fda3eecf048dd8e2f6f58dd86e9', 'storage_dtype': 'float32', 'source_api': ['qlib.init', 'qlib.data.D.calendar', 'qlib.data.D.instruments', 'qlib.data.D.list_instruments', 'qlib.data.D.features']}}, 'execution': {'provider_uri': 'data/qlib/legacy_soxl_execution_20260925_v1', 'execution_manifest_sha256': '97a346885d766e91571cd4193a0b8d6519bd3f5399eeeae23923c1cab82df169', 'manifest_path': 'data/qlib/legacy_soxl_execution_20260925_v1/execution_boundary_manifest.json', 'native_frame_sha256': 'b7a59f39feed5aed6e61fec2b4239092c474e453c91d4d133c73f9dcc571a03f', 'native_rows': 8324, 'observed_calendar_rows': 4162, 'future_calendar_rows': 4163, 'boundary_date': '2026-09-28', 'scope': 'One Qlib right interval boundary only; no new observed date, price, return, or execution session.', 'parent_file_sha256': {'calendars/day.txt': 'd3381b900795126d9b67efdc85780345b7a85c298a1f6d02fbe86e50ee3f96eb', 'features/soxl/close.day.bin': '5c24c8ecaf3c7a16e10b54d6fa2797d58082fecf70406ff19ae42c156456a970', 'features/soxl/high.day.bin': '0ed44ae8679231f425fc117ad48eb001a885b9c5db0c25195b95fcc1d69aa63b', 'features/soxl/low.day.bin': '54a9436a3c1dd9137f105d6b841bb564ca1ebc6b98d8b3de6ff33a94e543ab54', 'features/soxl/open.day.bin': 'f133c0ddceb6c94a9a3fc68e7d67da4b83a51496d83b3e76a071d02deab10195', 'features/soxl/volume.day.bin': 'cfc3c13ce7d9dc8a7932e331554769ca5504e0f08a2bc3085a0722dfacc8c441', 'features/soxx/close.day.bin': '10795d93e629b42b6951cc972877b70e0e1e48ad471777a262d1a9fe85a0e647', 'features/soxx/high.day.bin': '0039b6a0543e44f2fc841f29823c427b11325e83554381fa3cf63af70e311135', 'features/soxx/low.day.bin': '411d2c3ec7b082f293d57237130e856218d39c9a67959530fc48316d767dff4f', 'features/soxx/open.day.bin': '4ec7e322c7df8837d1ca76678de33dddac6c1dd3c48585618c44bb933fbe9711', 'features/soxx/volume.day.bin': '22e4344473649f6d63d2a509469b6b9f9e27d9d5c13351014a34632f6ad903a3', 'instruments/all.txt': 'cf10f6dc8dfcb4136e8bd305c48a87967441d326850c4237dd841234626de9df', 'price_basis_manifest.json': 'cbbdeeca2e1c7dc0bce0f9cdf3495f50d3219bddd992e1b893f8362a5e51bc65', 'price_basis_status.json': '3066a4796155684d4ed8c17beb707de7c67bc78c5fdaa7a1f6edc5bd282ccd5c', 'qlib.yaml': '2fb4a57dfdeeb4b75b899fa7304d2b73f83c92470ee01fd9b4472c4f3b9ecfd4', 'qlib_store_manifest.json': 'b57e3d31e0dfc3042c254f30f0b78739800b2994bcb3af076a5820741a5e21bb'}, 'future_calendar_sha256': '955363514c4d1c2e9a0a72579dd7661e18511dccc2f5514232913b17c62b6d33'}, 'decision_cutoff': '17:00 America/New_York, historical VIX availability assumed', 'source_api': 'qlib.data.D.calendar + D.instruments + D.features', 'warmup_start': '2010-03-11', 'as_of': '2026-09-25'}}

## 固定规则、原生回测和独立对账

旧规则引擎生成冻结指令与独立现金/持仓账本。原生 Qlib Backtest、Exchange、Account、Position 按整数复权价格单位执行这些指令，并逐日核对账户、现金、持仓、费用及净收益；Qlib 报告为指标主证据。数量并不等于历史券商原始股数。规则引擎的因果性由另行的合成测试验证，不能用记账一致性替代规则验证。

完整指令、账本、报告和持仓只写入 Qlib Recorder；根目录保留小型年度、窗口、风险、成本和门禁汇总。相同已完成实验只读取匹配 Recorder，失败或身份改变禁止静默重跑。

In [2]:
summary = run_legacy_repair(root=root, card_dir=card,
    provider_uri=root / plan["execution_provider_uri"], frame=frame,
    source_audit=source_audit, plan=plan)
print({"recorder_id": summary["recorder_id"], "historical_stable_excess_pass": summary["historical_stable_excess_pass"], "promotion_decision": summary["promotion_decision"]})

[47088:MainThread](2026-10-05 09:45:01,564) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[47088:MainThread](2026-10-05 09:45:01,564) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[47088:MainThread](2026-10-05 09:45:01,565) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/data/qlib/legacy_soxl_execution_20260925_v1')}

[47088:MainThread](2026-10-05 09:45:01,572) WARNING - qlib.workflow - [expm.py:231] - No valid experiment found. Create a new experiment with name legacy_soxl_repair_20261005.

[47088:MainThread](2026-10-05 09:45:01,573) INFO - qlib.workflow - [exp.py:258] - Experiment 645863221565255266 starts running ...

[47088:MainThread](2026-10-05 09:45:01,653) INFO - qlib.workflow - [recorder.py:345] - Recorder a899b1df50274e769ec1d7fead8676ed starts running under Experiment 645863221565255266 ...

[47088:MainThread](2026-10-05 09:45:02,171) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:02,177) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:02,190) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x1245faea0>

backtest loop:   0%|          | 0/2698 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)

[47088:MainThread](2026-10-05 09:45:03,704) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:03,709) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:03,719) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x12560cd70>

backtest loop:   0%|          | 0/2698 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)

[47088:MainThread](2026-10-05 09:45:04,407) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:04,412) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:04,422) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x1262bb290>

backtest loop:   0%|          | 0/2698 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)

[47088:MainThread](2026-10-05 09:45:05,237) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:05,242) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:05,253) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x127b46a80>

backtest loop:   0%|          | 0/2698 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)

[47088:MainThread](2026-10-05 09:45:06,128) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:06,133) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:06,144) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x12843f8f0>

backtest loop:   0%|          | 0/2698 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)

Native legacy comparison complete: continuous, 0 bp, 2698 sessions

[47088:MainThread](2026-10-05 09:45:08,400) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:08,405) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:08,415) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x129a183e0>

backtest loop:   0%|          | 0/2698 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)

[47088:MainThread](2026-10-05 09:45:10,095) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:10,100) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:10,112) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x12ba2af00>

backtest loop:   0%|          | 0/2698 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)

[47088:MainThread](2026-10-05 09:45:10,802) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:10,807) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:10,817) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x12c6754c0>

backtest loop:   0%|          | 0/2698 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)

[47088:MainThread](2026-10-05 09:45:11,506) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:11,511) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:11,521) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x13c989790>

backtest loop:   0%|          | 0/2698 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)

[47088:MainThread](2026-10-05 09:45:12,719) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:12,725) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:12,735) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x13d88d8e0>

backtest loop:   0%|          | 0/2698 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)

Native legacy comparison complete: continuous, 10 bp, 2698 sessions

[47088:MainThread](2026-10-05 09:45:16,452) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:16,457) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:16,470) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x14034f050>

backtest loop:   0%|          | 0/2698 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)

[47088:MainThread](2026-10-05 09:45:17,985) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:17,990) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:18,000) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x14c66af30>

backtest loop:   0%|          | 0/2698 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)

[47088:MainThread](2026-10-05 09:45:18,691) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:18,696) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:18,706) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x14ce55790>

backtest loop:   0%|          | 0/2698 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)

[47088:MainThread](2026-10-05 09:45:19,415) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:19,420) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:19,430) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x14d337440>

backtest loop:   0%|          | 0/2698 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
[47088:MainThread](2026-10-05 09:45:20,839) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:20,845) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:20,856) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x14a2ad730>

backtest loop:   0%|          | 0/2698 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)

Native legacy comparison complete: continuous, 25 bp, 2698 sessions

[47088:MainThread](2026-10-05 09:45:24,142) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:24,146) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:24,147) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x14582c4d0>

backtest loop:   0%|          | 0/39 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
[47088:MainThread](2026-10-05 09:45:24,168) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:24,170) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:24,171) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x151b41460>

backtest loop:   0%|          | 0/39 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
[47088:MainThread](2026-10-05 09:45:24,186) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:24,188) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:24,189) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x15c3f6000>

backtest loop:   0%|          | 0/39 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
[47088:MainThread](2026-10-05 09:45:24,203) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:24,204) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:24,205) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x144673800>

backtest loop:   0%|          | 0/39 [00:00<?, ?it/s]

[47088:MainThread](2026-10-05 09:45:24,223) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:24,224) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:24,225) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x141550620>

backtest loop:   0%|          | 0/39 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)

Native legacy comparison complete: recent_cash_start, 0 bp, 39 sessions

[47088:MainThread](2026-10-05 09:45:26,647) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:26,648) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:26,650) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x159578ce0>

backtest loop:   0%|          | 0/39 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
[47088:MainThread](2026-10-05 09:45:26,671) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:26,673) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:26,674) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x142dc2c60>

backtest loop:   0%|          | 0/39 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
[47088:MainThread](2026-10-05 09:45:26,689) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:26,690) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:26,691) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x15c1617f0>

backtest loop:   0%|          | 0/39 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
[47088:MainThread](2026-10-05 09:45:26,706) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:26,707) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:26,708) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x151b40fb0>

backtest loop:   0%|          | 0/39 [00:00<?, ?it/s]

[47088:MainThread](2026-10-05 09:45:26,725) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:26,727) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:26,728) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x15c8544d0>

backtest loop:   0%|          | 0/39 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)

Native legacy comparison complete: recent_cash_start, 10 bp, 39 sessions

[47088:MainThread](2026-10-05 09:45:29,225) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:29,226) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:29,227) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x15c0acbf0>

backtest loop:   0%|          | 0/39 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
[47088:MainThread](2026-10-05 09:45:29,248) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:29,250) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:29,251) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x1432ef1d0>

backtest loop:   0%|          | 0/39 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
[47088:MainThread](2026-10-05 09:45:29,266) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:29,267) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:29,268) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x15440e780>

backtest loop:   0%|          | 0/39 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
[47088:MainThread](2026-10-05 09:45:29,283) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:29,284) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:29,285) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x159579bb0>

backtest loop:   0%|          | 0/39 [00:00<?, ?it/s]

[47088:MainThread](2026-10-05 09:45:29,302) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[47088:MainThread](2026-10-05 09:45:29,304) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[47088:MainThread](2026-10-05 09:45:29,305) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x143d86750>

backtest loop:   0%|          | 0/39 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)

Native legacy comparison complete: recent_cash_start, 25 bp, 39 sessions

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[47088:MainThread](2026-10-05 09:45:35,043) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | waiting `async_log` Done

[47088:MainThread](2026-10-05 09:45:35,053) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[47088:MainThread](2026-10-05 09:45:35,054) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[47088:MainThread](2026-10-05 09:45:35,054) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/data/qlib/published_futu_affine_20260925_v1')}

[47088:MainThread](2026-10-05 09:45:35,062) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[47088:MainThread](2026-10-05 09:45:35,062) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[47088:MainThread](2026-10-05 09:45:35,063) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/data/qlib/legacy_vix_20260925_v1')}

[47088:MainThread](2026-10-05 09:45:35,074) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[47088:MainThread](2026-10-05 09:45:35,075) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[47088:MainThread](2026-10-05 09:45:35,075) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/data/qlib/published_futu_affine_20260925_v1')}

[47088:MainThread](2026-10-05 09:45:35,095) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[47088:MainThread](2026-10-05 09:45:35,096) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[47088:MainThread](2026-10-05 09:45:35,096) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/data/qlib/published_futu_affine_20260925_v1')}

[47088:MainThread](2026-10-05 09:45:35,110) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[47088:MainThread](2026-10-05 09:45:35,110) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[47088:MainThread](2026-10-05 09:45:35,111) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/legacy-soxl-repair-20261005/data/qlib/legacy_soxl_execution_20260925_v1')}

{'recorder_id': 'a899b1df50274e769ec1d7fead8676ed', 'historical_stable_excess_pass': False, 'promotion_decision': 'not_promoted'}

In [3]:
import pandas as pd
from IPython.display import display, Markdown
with R.uri_context(summary["recorder_uri"]):
    recorder = R.get_recorder(experiment_name=summary["experiment"], recorder_id=summary["recorder_id"])
    tables = recorder.load_object("analysis/tables.pkl")
display(tables["backtest_benchmark_comparison.csv"])
display(tables["development_gates.csv"])
display(tables["annual_metrics.csv"].query("window == 'development' and cost_bps == 10"))
display(Markdown((card / "conclusion.md").read_text()))

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

,window,cost_bps,variant,sessions,return_pct,cagr_pct,max_drawdown_pct,cvar5_pct,worst_day_pct,annualized_volatility_pct,mean_exposure_pct,fee_cash,turnover,terminal_account,log_excess_vs_soxx,relative_return_vs_soxx_pct
0,development,0,legacy_repaired,1762,348.165314,23.927657,-69.954949,-7.522126,-16.048831,47.228034,36.837293,0.000000,5.159471,4.481653e+05,0.048825,5.003655
1,development,0,soxx_buy_hold,1762,326.809252,23.065295,-45.752427,-4.742973,-15.227270,31.905915,99.996363,0.000000,0.999918,4.268093e+05,0.000000,0.000000
2,development,0,soxl_buy_hold,1762,517.955422,29.754412,-90.460465,-14.145695,-38.592945,94.616315,99.999882,0.000000,0.999995,6.179554e+05,0.370079,44.784917
3,development,0,soxl_fixed_50,1762,424.827737,26.758267,-63.214722,-7.183096,-20.668943,47.345685,49.987164,0.000000,19.163353,5.248277e+05,0.206733,22.965408
4,development,0,soxl_fixed_90,1762,575.504291,31.417387,-87.142209,-12.769972,-35.214337,85.155275,89.987524,0.000000,7.629446,6.755043e+05,0.459122,58.268427
5,development,10,legacy_repaired,1762,345.925771,23.838897,-69.995413,-7.524848,-16.050990,47.242629,36.849537,2140.164363,5.160188,4.459258e+05,0.044862,4.588361
6,development,10,soxx_buy_hold,1762,326.362711,23.046873,-45.752006,-4.742866,-15.226891,31.904846,99.993623,99.885717,0.998857,4.263627e+05,0.000000,0.000000
7,development,10,soxl_buy_hold,1762,517.340364,29.735934,-90.460474,-14.145707,-38.592976,94.616069,99.999987,99.900048,0.999000,6.173404e+05,0.370130,44.792297
8,development,10,soxl_fixed_50,1762,414.856968,26.411014,-63.335191,-7.184788,-20.675199,47.345599,49.987171,8431.580018,19.164239,5.148570e+05,0.188599,20.755628
9,development,10,soxl_fixed_90,1762,570.358345,31.273737,-87.157575,-12.770546,-35.216110,85.154870,89.987530,6561.059383,7.628489,6.703583e+05,0.452522,57.227245
10,development,25,legacy_repaired,1762,342.459719,23.700771,-70.066725,-7.529795,-16.053688,47.269076,36.870220,5327.674901,5.161449,4.424597e+05,0.038630,3.938616
11,development,25,soxx_buy_hold,1762,325.693297,23.019224,-45.751346,-4.742697,-15.226298,31.903278,99.989326,249.316554,0.997266,4.256933e+05,0.000000,0.000000
12,development,25,soxl_buy_hold,1762,516.414190,29.708079,-90.460464,-14.145694,-38.592943,94.615517,99.999872,249.375234,0.997501,6.164142e+05,0.370200,44.802419
13,development,25,soxl_fixed_50,1762,400.262062,25.892177,-63.515897,-7.187256,-20.683700,47.345348,49.987183,20691.981954,19.162885,5.002621e+05,0.161413,17.517016
14,development,25,soxl_fixed_90,1762,562.706907,31.058388,-87.180417,-12.771412,-35.219332,85.154294,89.987506,16275.685604,7.627806,6.627069e+05,0.442614,55.677083
15,reused_diagnostic,0,legacy_repaired,936,529.195158,64.080738,-59.050091,-7.020815,-15.381256,52.023391,49.072414,0.000000,3.024845,2.819834e+06,0.217937,24.350919
16,reused_diagnostic,0,soxx_buy_hold,936,405.983519,54.730232,-41.359510,-5.398944,-10.444278,38.005003,99.998995,0.000000,0.000000,2.159584e+06,0.000000,0.000000
17,reused_diagnostic,0,soxl_buy_hold,936,1501.687078,111.013078,-87.879264,-16.012988,-30.513891,112.099191,99.999973,0.000000,0.000000,9.897712e+06,1.152309,216.549259
18,reused_diagnostic,0,soxl_fixed_50,936,615.649564,69.868030,-59.601128,-8.129111,-16.112593,55.962045,50.002964,0.000000,12.181391,3.755927e+06,0.346687,41.437327
19,reused_diagnostic,0,soxl_fixed_90,936,1398.592298,107.267005,-84.180236,-14.452270,-27.760993,100.827523,89.990689,0.000000,4.394072,1.012306e+07,1.085777,196.174133
20,reused_diagnostic,10,legacy_repaired,936,522.392937,63.601258,-59.691334,-7.098767,-15.622295,52.455013,49.388758,4479.760286,3.019967,2.775411e+06,0.207079,23.007996
21,reused_diagnostic,10,soxx_buy_hold,936,405.977628,54.729747,-41.359251,-5.398913,-10.444249,38.004741,99.998239,0.000000,0.000000,2.157300e+06,0.000000,0.000000
22,reused_diagnostic,10,soxl_buy_hold,936,1501.688149,111.013116,-87.879272,-16.012990,-30.513892,112.099219,99.999997,0.000000,0.000000,9.887867e+06,1.152321,216.553156
23,reused_diagnostic,10,soxl_fixed_50,936,607.011125,69.313537,-59.700593,-8.131166,-16.112861,55.960568,50.002922,19195.090418,12.182661,3.640096e+06,0.334554,39.731697
24,reused_diagnostic,10,soxl_fixed_90,936,1392.038825,107.022584,-84.194535,-14.452982,-27.761311,100.826839,89.990652,16167.857715,4.394501,1.000201e+07,1.081406,194.882371
25,reused_diagnostic,25,legacy_repaired,936,520.546503,63.470444,-59.731294,-7.103970,-15.627970,52.495089,49.426062,11099.247651,3.020187,2.745668e+06,0.204126,22.645311
26,reused_diagnostic,25,soxx_buy_hold,936,405.968388,54.728986,-41.358845,-5.398865,-10.444205,38.004330,99.997051,0.000000,0.000000,2.153874e+06,0.000000,0.000000
27,reused_diagnostic,25,soxl_buy_hold,936,1501.686982,111.013075,-87.879263,-16.012987,-30.513891,112.099189,99.999971,0.000000,0.000000,9.873026e+06,1.152339,216.558706
28,reused_diagnostic,25,soxl_fixed_50,936,594.220664,68.483366,-59.848803,-8.134259,-16.114525,55.958488,50.002981,46075.769693,12.181786,3.472923e+06,0.316316,37.206331
29,reused_diagnostic,25,soxl_fixed_90,936,1382.218064,106.654833,-84.216051,-14.454116,-27.761592,100.825949,89.990670,39774.178527,4.394680,9.822761e+06,1.074821,192.946773
30,recent_cash_start,0,legacy_repaired,39,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000e+05,-0.152379,-14.133745
31,recent_cash_start,0,soxx_buy_hold,39,16.460185,167.675306,-11.018748,-5.293048,-5.618396,40.045262,99.807868,0.000000,0.997939,1.164602e+05,0.000000,0.000000
32,recent_cash_start,0,soxl_buy_hold,39,42.738593,896.724819,-33.243799,-15.911991,-16.973316,118.400672,99.937688,0.000000,0.999273,1.427386e+05,0.203465,22.564285
33,recent_cash_start,0,soxl_fixed_50,39,22.841348,277.836052,-17.259269,-8.057833,-8.556777,59.573490,50.094726,0.000000,1.067201,1.228413e+05,0.053344,5.479265
34,recent_cash_start,0,soxl_fixed_90,39,39.142051,745.204834,-30.187887,-14.367697,-15.320467,106.750220,90.026559,0.000000,1.088473,1.391421e+05,0.177946,19.476069
35,recent_cash_start,10,legacy_repaired,39,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000e+05,-0.151522,-14.060103
36,recent_cash_start,10,soxx_buy_hold,39,16.360391,166.196693,-11.028434,-5.297855,-5.623635,40.036251,99.900785,99.793853,0.997939,1.163604e+05,0.000000,0.000000
37,recent_cash_start,10,soxl_buy_hold,39,42.593402,890.191947,-33.242322,-15.911189,-16.972378,118.340707,99.932255,99.821224,0.998212,1.425934e+05,0.203305,22.544622
38,recent_cash_start,10,soxl_fixed_50,39,22.725835,275.546193,-17.284292,-8.064471,-8.567160,59.541430,50.089412,112.498017,1.067519,1.227258e+05,0.053261,5.470456
39,recent_cash_start,10,soxl_fixed_90,39,38.922869,736.638883,-30.210324,-14.375518,-15.322732,106.718193,90.031922,111.520955,1.084260,1.389229e+05,0.177227,19.390170
40,recent_cash_start,25,legacy_repaired,39,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000e+05,-0.149547,-13.890233
41,recent_cash_start,25,soxx_buy_hold,39,16.130845,162.821761,-10.994988,-5.281258,-5.605547,39.840772,99.579960,248.255645,0.993023,1.161308e+05,0.000000,0.000000
42,recent_cash_start,25,soxl_buy_hold,39,42.398565,881.482182,-33.252432,-15.916674,-16.978798,118.306182,99.969438,249.287861,0.997151,1.423986e+05,0.203912,22.619073
43,recent_cash_start,25,soxl_fixed_50,39,22.546495,272.014294,-17.294669,-8.061995,-8.564417,59.487211,50.096572,281.501532,1.069029,1.225465e+05,0.053773,5.524502
44,recent_cash_start,25,soxl_fixed_90,39,38.756844,730.199311,-30.186606,-14.362533,-15.308512,106.615006,90.019788,279.624695,1.087419,1.387568e+05,0.178006,19.483195

,window,cost_bps,positive_years,positive_net_log_excess,max_drawdown_not_worse_soxx,cvar5_not_worse_soxx,at_least_6_of_7_positive_years,median_annual_log_excess_positive,block_20_positive_lower_bound,block_60_positive_lower_bound,all_pass
0,development,10,4,True,False,False,False,True,False,False,False
1,development,25,4,True,False,False,False,True,False,False,False
2,reused_diagnostic,10,2,True,False,False,NaN,NaN,False,False,False
3,reused_diagnostic,25,2,True,False,False,NaN,NaN,False,False,False

,window,cost_bps,variant,year,sessions,return_pct,cagr_pct,max_drawdown_pct,cvar5_pct,worst_day_pct,annualized_volatility_pct,mean_exposure_pct,fee_cash,turnover,terminal_account,log_excess_vs_soxx,accounting
35,development,10,legacy_repaired,2016,252,72.361500,72.361500,-14.442947,-4.108756,-8.909696,28.156658,38.015724,203.686561,1.574680,1.723615e+05,0.200771,slice of continuous portfolio; no annual reset
36,development,10,legacy_repaired,2017,251,9.589617,9.629606,-4.258994,-1.042445,-2.275660,6.164165,11.028992,0.000000,0.000000,1.888903e+05,-0.240336,slice of continuous portfolio; no annual reset
37,development,10,legacy_repaired,2018,251,-12.005700,-12.050527,-26.235493,-3.908117,-5.977628,23.944685,26.205582,66.837026,0.382122,1.662127e+05,-0.060845,slice of continuous portfolio; no annual reset
38,development,10,legacy_repaired,2019,252,70.778763,70.778763,-7.857663,-3.052636,-7.857663,23.100533,24.220935,171.827075,0.678536,2.838560e+05,0.050212,slice of continuous portfolio; no annual reset
39,development,10,legacy_repaired,2020,253,137.384262,136.574496,-36.330567,-9.744186,-15.582381,65.844632,61.473544,160.979776,0.609804,6.738295e+05,0.441080,slice of continuous portfolio; no annual reset
40,development,10,legacy_repaired,2021,252,71.337723,71.337723,-38.334598,-9.875070,-16.050990,60.341203,39.379327,992.093214,1.098391,1.154524e+06,0.173184,slice of continuous portfolio; no annual reset
41,development,10,legacy_repaired,2022,251,-61.375793,-61.521902,-69.827044,-9.881294,-12.507738,75.294707,57.462038,544.740710,0.816655,4.459258e+05,-0.519203,slice of continuous portfolio; no annual reset
42,development,10,soxx_buy_hold,2016,252,41.008911,41.008911,-14.648809,-3.598936,-5.426453,22.350732,99.987046,99.885717,0.998857,1.410089e+05,0.000000,slice of continuous portfolio; no annual reset
43,development,10,soxx_buy_hold,2017,251,39.362542,39.546950,-10.212915,-2.767527,-4.405156,17.387422,99.991479,0.000000,0.000000,1.965136e+05,0.000000,slice of continuous portfolio; no annual reset
44,development,10,soxx_buy_hold,2018,251,-6.485422,-6.510400,-25.247689,-4.349712,-6.558765,27.891500,99.993044,0.000000,0.000000,1.837689e+05,0.000000,slice of continuous portfolio; no annual reset
45,development,10,soxx_buy_hold,2019,252,62.415411,62.415411,-18.159289,-3.554804,-5.831613,26.112109,99.993904,0.000000,0.000000,2.984690e+05,0.000000,slice of continuous portfolio; no annual reset
46,development,10,soxx_buy_hold,2020,253,52.719085,52.463703,-34.252273,-6.997239,-15.226891,45.533510,99.995558,0.000000,0.000000,4.558191e+05,0.000000,slice of continuous portfolio; no annual reset
47,development,10,soxx_buy_hold,2021,252,44.092086,44.092086,-14.600384,-4.244289,-5.695756,29.997016,99.997326,0.000000,0.000000,6.567992e+05,0.000000,slice of continuous portfolio; no annual reset
48,development,10,soxx_buy_hold,2022,251,-35.084771,-35.196424,-45.519671,-5.291018,-6.210396,43.424162,99.996998,0.000000,0.000000,4.263627e+05,0.000000,slice of continuous portfolio; no annual reset
49,development,10,soxl_buy_hold,2016,252,136.792785,136.792785,-40.371211,-10.815813,-16.878165,67.895809,99.999956,99.900048,0.999000,2.367928e+05,0.518362,slice of continuous portfolio; no annual reset
50,development,10,soxl_buy_hold,2017,251,141.706703,142.558077,-28.903469,-8.364087,-13.145115,52.384819,99.999986,0.000000,0.000000,5.723440e+05,0.550646,slice of continuous portfolio; no annual reset
51,development,10,soxl_buy_hold,2018,251,-39.069585,-39.189734,-66.513072,-13.018682,-19.775610,83.553668,99.999991,0.000000,0.000000,3.487316e+05,-0.428385,slice of continuous portfolio; no annual reset
52,development,10,soxl_buy_hold,2019,252,231.833236,231.833236,-47.161155,-10.685927,-17.771539,78.607103,99.999992,0.000000,0.000000,1.157207e+06,0.714475,slice of continuous portfolio; no annual reset
53,development,10,soxl_buy_hold,2020,253,70.039330,69.682918,-80.382229,-20.379806,-38.592976,131.310013,99.999994,0.000000,0.000000,1.967708e+06,0.107430,slice of continuous portfolio; no annual reset
54,development,10,soxl_buy_hold,2021,252,118.831072,118.831072,-40.924335,-12.701087,-17.205647,89.635583,99.999998,0.000000,0.000000,4.305956e+06,0.417847,slice of continuous portfolio; no annual reset
55,development,10,soxl_buy_hold,2022,251,-85.663104,-85.773621,-90.342718,-15.832477,-18.302226,129.728712,99.999995,0.000000,0.000000,6.173404e+05,-1.510246,slice of continuous portfolio; no annual reset
56,development,10,soxl_fixed_50,2016,252,62.782424,62.782424,-21.688714,-5.459582,-8.685910,33.978688,50.019854,288.092650,2.550477,1.627824e+05,0.143591,slice of continuous portfolio; no annual reset
57,development,10,soxl_fixed_50,2017,251,61.277127,61.584524,-14.906270,-4.192954,-6.687466,26.153710,49.993970,349.707876,1.616442,2.625308e+05,0.146045,slice of continuous portfolio; no annual reset
58,development,10,soxl_fixed_50,2018,251,-14.468250,-14.521489,-37.849454,-6.569167,-10.158058,41.845223,49.947175,685.632181,2.541832,2.245472e+05,-0.089230,slice of continuous portfolio; no annual reset
59,development,10,soxl_fixed_50,2019,252,94.612654,94.612654,-26.604404,-5.438564,-9.239254,39.306359,50.047720,728.201264,2.308749,4.369973e+05,0.180854,slice of continuous portfolio; no annual reset
60,development,10,soxl_fixed_50,2020,253,56.084007,55.809575,-52.619329,-10.500498,-20.675199,65.745509,49.965611,1424.703751,3.445720,6.820829e+05,0.021794,slice of continuous portfolio; no annual reset
61,development,10,soxl_fixed_50,2021,252,61.448004,61.448004,-22.093140,-6.427270,-8.841289,44.665818,49.998045,2167.386016,2.577310,1.101209e+06,0.113731,slice of continuous portfolio; no annual reset
62,development,10,soxl_fixed_50,2022,251,-53.246214,-53.387616,-63.142051,-8.045126,-9.415374,65.039865,49.937577,2787.856279,4.123709,5.148570e+05,-0.328187,slice of continuous portfolio; no annual reset
63,development,10,soxl_fixed_90,2016,252,121.704242,121.704242,-36.883582,-9.751823,-15.278040,61.114573,90.002901,184.720161,1.636813,2.217042e+05,0.452521,slice of continuous portfolio; no annual reset
64,development,10,soxl_fixed_90,2017,251,124.260793,124.983556,-26.185649,-7.531546,-11.856613,47.130825,89.994755,212.960100,0.583463,4.971957e+05,0.475731,slice of continuous portfolio; no annual reset
65,development,10,soxl_fixed_90,2018,251,-33.814708,-33.923445,-61.658831,-11.738062,-17.892741,75.215399,89.972788,455.918436,0.917928,3.290704e+05,-0.345659,slice of continuous portfolio; no annual reset
66,development,10,soxl_fixed_90,2019,252,201.410380,201.410380,-43.481064,-9.650997,-16.116824,70.741213,90.012704,483.623749,0.828717,9.918524e+05,0.618315,slice of continuous portfolio; no annual reset
67,development,10,soxl_fixed_90,2020,253,72.185883,71.816451,-76.291574,-18.443993,-35.216110,118.179020,89.977606,988.534172,1.240792,1.707830e+06,0.119974,slice of continuous portfolio; no annual reset
68,development,10,soxl_fixed_90,2021,252,108.871397,108.871397,-37.419315,-11.457879,-15.567109,80.604651,89.991150,2183.403134,0.929832,3.567168e+06,0.371266,slice of continuous portfolio; no annual reset
69,development,10,soxl_fixed_90,2022,251,-81.207548,-81.332294,-87.019063,-14.291874,-16.566518,116.804971,89.960710,2051.899631,1.490943,6.703583e+05,-1.239627,slice of continuous portfolio; no annual reset

# 旧 SOXL 规则修复与原生 Qlib 复核

**机械修复通过；存在累计超额，但未达到稳定超额及风险门禁，不晋升。** 保留旧参数、实际 180 日的 MA20、整数数量和 LIFO；修复首行越界、重复状态判断、仓位记账，以及收盘信号到下一开盘成交的时序和现金费用。没有训练模型或搜索参数。

2016-01-04 至 2026-09-25 是同一条 2,698 个交易日连续账本；开发期与 2023 年后的指标仅切片，年度不重置。另设 2026-08-03 起 39 日现金启动诊断，完整前史用于预热，首日意图来自前一交易日收盘。0/10/25 bp 每侧成本独立执行，主门禁为 10/25 bp。

以下突出每侧 **25 bp** 的原生 Qlib 净报告结果：

| 窗口/方案 | 累计收益 | 最大回撤 | 日收益 CVaR5 |
|---|---:|---:|---:|
| 2016–2022 修复规则 | 342.46% | -70.07% | -7.53% |
| 2016–2022 SOXX 买入持有 | 325.69% | -45.75% | -4.74% |
| 2016–2022 每日固定 50% SOXL | 400.26% | -63.52% | -7.19% |
| 2023 年后延续持仓：修复规则 | 520.55% | -59.73% | -7.10% |
| 2023 年后延续持仓：SOXX | 405.97% | -41.36% | -5.40% |
| 2023 年后延续持仓：固定 50% SOXL | 594.22% | -59.85% | -8.13% |
| 2026-08-03 现金启动：修复规则 | 0.00% | 0.00% | 0.00% |
| 2026-08-03 现金启动：SOXX | 16.13% | -10.99% | -5.28% |

开发期规则年化收益 23.70%，SOXX 为 23.02%；相对财富增加 3.94%。10/25 bp 均只有 **4/7 年正超额**，未达 6/7；20/60 日平均块长 bootstrap 的 95% 区间均跨零，回撤和 CVaR5 均更差。0 bp 仅作成本诊断，不用于放宽门禁。

窗口差异明显：2023 年后规则相对 SOXX 财富增加 22.65%，但尾部与统计门禁仍失败。近期现金启动的指标均已就绪，却没有任何订单，保持现金 39 日，错过 SOXX 的 16.13% 上涨。固定 50% SOXL 在开发期、复用期的累计收益均高于规则，开发期回撤更小、复用期回撤相近。因此本次不能证明复杂择时比固定配置增加价值；这是配置参照，**并非严格 beta 归因或精确风险匹配**，也未挑选最优比例。

全部 30 条方案×成本×账本由 Qlib 原生 Backtest/Exchange/Account/Position 执行。六条规则账本逐日独立对账：账户、现金和股数误差为 0，最大费用误差小于 1e-12，净收益误差小于 2e-16。原生风险表不含初始资本标记的回撤约定已标注；本表和门禁均包含初始资本。完整账本、订单、持仓、报告和 bootstrap draws 只在 Recorder 中。

风险：全部历史均已复用；价格含回溯公司行动调整，不是当时可获得的价格档案。VIX 假设在纽约 17:00 可用，历史发布时间与修订未逐日验证。历史开盘价格、线性费用、整数复权价格单位不代表券商真实成交、价差、冲击或原始股数。现金收益为零，所有方案均不虚构期末清仓。派生执行 store 仅增加下一日历端点，全部已观察 SOXL/SOXX 数据与 canonical 字节及原生读回一致，没有新增未来价格。

下一步：保留本次失败证据，不据此修改旧阈值后重复宣称通过；另行预登记新连续样本与真实可执行数据的验证。**本次不改变生产、调度或券商配置。**

证据：`backtest_benchmark_comparison.csv`、`annual_metrics.csv`、`development_gates.csv`、`bootstrap.csv`、`risk_analysis.csv`；Recorder `a899b1df50274e769ec1d7fead8676ed`，状态 FINISHED，16 个已登记 artifact 哈希已回读通过。首次启动只在创建 Recorder 前因 MLflow 环境开关失败，已保留 `pre_recorder_failure.json`；环境修复后仅一次金融执行。

# 旧 SOXL 规则修复与原生 Qlib 复核

**机械修复通过；存在累计超额，但未达到稳定超额及风险门禁，不晋升。** 保留旧参数、实际 180 日的 MA20、整数数量和 LIFO；修复首行越界、重复状态判断、仓位记账，以及收盘信号到下一开盘成交的时序和现金费用。没有训练模型或搜索参数。

2016-01-04 至 2026-09-25 是同一条 2,698 个交易日连续账本；开发期与 2023 年后的指标仅切片，年度不重置。另设 2026-08-03 起 39 日现金启动诊断，完整前史用于预热，首日意图来自前一交易日收盘。0/10/25 bp 每侧成本独立执行，主门禁为 10/25 bp。

以下突出每侧 **25 bp** 的原生 Qlib 净报告结果：

| 窗口/方案 | 累计收益 | 最大回撤 | 日收益 CVaR5 |
|---|---:|---:|---:|
| 2016–2022 修复规则 | 342.46% | -70.07% | -7.53% |
| 2016–2022 SOXX 买入持有 | 325.69% | -45.75% | -4.74% |
| 2016–2022 每日固定 50% SOXL | 400.26% | -63.52% | -7.19% |
| 2023 年后延续持仓：修复规则 | 520.55% | -59.73% | -7.10% |
| 2023 年后延续持仓：SOXX | 405.97% | -41.36% | -5.40% |
| 2023 年后延续持仓：固定 50% SOXL | 594.22% | -59.85% | -8.13% |
| 2026-08-03 现金启动：修复规则 | 0.00% | 0.00% | 0.00% |
| 2026-08-03 现金启动：SOXX | 16.13% | -10.99% | -5.28% |

开发期规则年化收益 23.70%，SOXX 为 23.02%；相对财富增加 3.94%。10/25 bp 均只有 **4/7 年正超额**，未达 6/7；20/60 日平均块长 bootstrap 的 95% 区间均跨零，回撤和 CVaR5 均更差。0 bp 仅作成本诊断，不用于放宽门禁。

窗口差异明显：2023 年后规则相对 SOXX 财富增加 22.65%，但尾部与统计门禁仍失败。近期现金启动的指标均已就绪，却没有任何订单，保持现金 39 日，错过 SOXX 的 16.13% 上涨。固定 50% SOXL 在开发期、复用期的累计收益均高于规则，开发期回撤更小、复用期回撤相近。因此本次不能证明复杂择时比固定配置增加价值；这是配置参照，**并非严格 beta 归因或精确风险匹配**，也未挑选最优比例。

全部 30 条方案×成本×账本由 Qlib 原生 Backtest/Exchange/Account/Position 执行。六条规则账本逐日独立对账：账户、现金和股数误差为 0，最大费用误差小于 1e-12，净收益误差小于 2e-16。原生风险表不含初始资本标记的回撤约定已标注；本表和门禁均包含初始资本。完整账本、订单、持仓、报告和 bootstrap draws 只在 Recorder 中。

风险：全部历史均已复用；价格含回溯公司行动调整，不是当时可获得的价格档案。VIX 假设在纽约 17:00 可用，历史发布时间与修订未逐日验证。历史开盘价格、线性费用、整数复权价格单位不代表券商真实成交、价差、冲击或原始股数。现金收益为零，所有方案均不虚构期末清仓。派生执行 store 仅增加下一日历端点，全部已观察 SOXL/SOXX 数据与 canonical 字节及原生读回一致，没有新增未来价格。

下一步：保留本次失败证据，不据此修改旧阈值后重复宣称通过；另行预登记新连续样本与真实可执行数据的验证。**本次不改变生产、调度或券商配置。**

证据：`backtest_benchmark_comparison.csv`、`annual_metrics.csv`、`development_gates.csv`、`bootstrap.csv`、`risk_analysis.csv`；Recorder `a899b1df50274e769ec1d7fead8676ed`，状态 FINISHED，16 个已登记 artifact 哈希已回读通过。首次启动只在创建 Recorder 前因 MLflow 环境开关失败，已保留 `pre_recorder_failure.json`；环境修复后仅一次金融执行。