# 财报预期差与现有指增：固定信息层检验

假设：NVDA/AMD/INTC历史EPS surprise能否在BASE5之外改善现金与加杠杆两个五日预测头。只允许2016–2022信号年、14次联合多输出Ridge拟合；本轮不执行组合，不改SIM或生产。

**供应商历史预期缺少当时版本，source_deployment_gate=False，无论结果如何不晋升。** 固定三家公司不代表完整历史成分；旧EPS回溯拆股复权与三位小数可能影响surprise。本次两个头的局部多重比较调整不覆盖过往研究次数。

In [1]:
from pathlib import Path
import json
import sys
ROOT = Path.cwd().resolve()
while not (ROOT / "src").is_dir():
    if ROOT == ROOT.parent:
        raise RuntimeError("repository root unavailable")
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))
import qlib
from qlib.data import D
from qlib.data.dataset import DatasetH
from qlib.workflow import R
from src.workflow.earnings_enhancement import EXPERIMENT, run_experiment, verify_registered_plan
CARD = ROOT / "research" / EXPERIMENT
plan = json.loads((CARD / "plan.json").read_text())
verify_registered_plan(plan)
qlib.init(provider_uri=str(ROOT / plan["source"]["provider_uri"]), region="us", kernels=1)
calendar = D.calendar(freq="day")
{"source": plan["source"]["provider_uri"], "first_session": str(calendar[0]), "last_session": str(calendar[-1]), "source_deployment_gate": False}

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[4165:MainThread](2026-10-05 14:18:20,967) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[4165:MainThread](2026-10-05 14:18:20,968) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[4165:MainThread](2026-10-05 14:18:20,969) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/earnings-enhancement-20261005/data/qlib/published_futu_affine_20260925_v1')}

{'source': 'data/qlib/published_futu_affine_20260925_v1',
 'first_session': '2010-03-11 00:00:00',
 'last_session': '2026-09-25 00:00:00',
 'source_deployment_gate': False}

## 冻结合同

[plan.json](plan.json)与[workflow.yaml](workflow.yaml)登记两头标签、20行剔除、成熟时间、成本与停止门。所有价格先在完整Qlib日历形成标签，再接入三列财报状态；2022末信号可使用2023初已经成熟的H5标签，但2023+信号不拟合或评价。

下面代码只在root复核源码与输入并写入run_authorization.json后执行；一次14拟合，已有完成Recorder时只读回原证据。

In [2]:
summary = run_experiment(root=ROOT)
assert summary["fit_count"] == 14
assert summary["source_deployment_gate"] is False
assert summary["no_portfolio_backtest"] is True
{"recorder_id": summary["recorder_id"], "gates": summary["gates"]}

[4165:MainThread](2026-10-05 14:18:21,547) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[4165:MainThread](2026-10-05 14:18:21,548) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[4165:MainThread](2026-10-05 14:18:21,548) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/earnings-enhancement-20261005/data/qlib/published_futu_affine_20260925_v1')}

[4165:MainThread](2026-10-05 14:18:21,581) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[4165:MainThread](2026-10-05 14:18:21,582) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[4165:MainThread](2026-10-05 14:18:21,582) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/earnings-enhancement-20261005/data/qlib/earnings_surprise_20261005_v1')}

[4165:MainThread](2026-10-05 14:18:21,590) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[4165:MainThread](2026-10-05 14:18:21,591) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[4165:MainThread](2026-10-05 14:18:21,591) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/earnings-enhancement-20261005/data/qlib/published_futu_affine_20260925_v1')}

[4165:MainThread](2026-10-05 14:18:21,594) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[4165:MainThread](2026-10-05 14:18:21,594) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[4165:MainThread](2026-10-05 14:18:21,594) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[4165:MainThread](2026-10-05 14:18:21,607) WARNING - qlib.workflow - [expm.py:231] - No valid experiment found. Create a new experiment with name earnings_enhancement_20261005.

[4165:MainThread](2026-10-05 14:18:21,610) INFO - qlib.workflow - [exp.py:258] - Experiment 763171092913407904 starts running ...

[4165:MainThread](2026-10-05 14:18:21,684) INFO - qlib.workflow - [recorder.py:345] - Recorder b3674e7f2d7c41a5b8827c99f316969a starts running under Experiment 763171092913407904 ...

[4165:MainThread](2026-10-05 14:18:24,689) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

{'recorder_id': 'b3674e7f2d7c41a5b8827c99f316969a',
 'gates': {'heads': {'cash5': {'positive_full_ic_years': 6,
    'positive_delta_ic_years': 4,
    'positive_mse_reduction_years': 3,
    'evaluated_years': 7,
    'information_pass': False,
    'incremental_pass': False,
    'economic_pass': False,
    'all_head_gates_pass': False},
   'leverage5': {'positive_full_ic_years': 6,
    'positive_delta_ic_years': 4,
    'positive_mse_reduction_years': 3,
    'evaluated_years': 7,
    'information_pass': False,
    'incremental_pass': False,
    'economic_pass': False,
    'all_head_gates_pass': False}},
  'both_heads_information_and_economic_pass': False,
  'source_deployment_gate': False,
  'promotion_decision': 'not_promoted',
  'decision': 'end_fixed_recipe_no_further_search',
  'fresh_holdout': False,
  'stable_excess_gate_evaluated': False,
  'economic_scope': 'isolated_overlapping_H5_events_not_a_portfolio'}}

In [3]:
with R.uri_context(Path(summary["recorder_uri"]).as_uri()):
    recorder = R.get_recorder(experiment_name=EXPERIMENT, recorder_id=summary["recorder_id"])
    recorded_summary = recorder.load_object("card/summary.pkl")
assert recorder.status == "FINISHED"
assert recorded_summary["native_input_sha256"] == summary["native_input_sha256"]
import pandas as pd
display(pd.read_csv(CARD / "point_metrics.csv"))
display(pd.read_csv(CARD / "event_metrics.csv"))

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

,slice,head,rows,signal_start,signal_end,trade_start,label_mature_end,base_ic,full_ic,base_ic_undefined_reason,full_ic_undefined_reason,delta_ic_full_minus_base,base_mse,full_mse,mse_reduction_base_minus_full,prior_mean_mse,mse_reduction_prior_minus_full
0,development_2016_2022,cash5,1762,2016-01-04,2022-12-30,2016-01-05,2023-01-10,0.042432,0.069832,NaN,NaN,0.027400,0.001652,0.001756,-0.000105,0.001634,-0.000122
1,development_2016_2022,leverage5,1762,2016-01-04,2022-12-30,2016-01-05,2023-01-10,0.009434,0.049621,NaN,NaN,0.040187,0.007369,0.007845,-0.000476,0.007199,-0.000646
2,year_2016,cash5,252,2016-01-04,2016-12-30,2016-01-05,2017-01-10,0.253790,0.307703,NaN,NaN,0.053913,0.000931,0.000958,-0.000027,0.000953,-0.000006
3,year_2016,leverage5,252,2016-01-04,2016-12-30,2016-01-05,2017-01-10,0.226053,0.286516,NaN,NaN,0.060463,0.003898,0.004021,-0.000123,0.003965,-0.000056
4,year_2017,cash5,251,2017-01-03,2017-12-29,2017-01-04,2018-01-09,0.096976,0.080579,NaN,NaN,-0.016397,0.000621,0.000636,-0.000015,0.000590,-0.000046
5,year_2017,leverage5,251,2017-01-03,2017-12-29,2017-01-04,2018-01-09,0.083042,0.078949,NaN,NaN,-0.004093,0.002574,0.002643,-0.000069,0.002465,-0.000178
6,year_2018,cash5,251,2018-01-02,2018-12-31,2018-01-03,2019-01-09,0.174002,0.115570,NaN,NaN,-0.058431,0.001342,0.001333,0.000009,0.001362,0.000029
7,year_2018,leverage5,251,2018-01-02,2018-12-31,2018-01-03,2019-01-09,0.135030,0.068759,NaN,NaN,-0.066271,0.005722,0.005671,0.000051,0.005742,0.000071
8,year_2019,cash5,252,2019-01-02,2019-12-31,2019-01-03,2020-01-09,0.148607,0.172794,NaN,NaN,0.024187,0.001153,0.001147,0.000006,0.001177,0.000030
9,year_2019,leverage5,252,2019-01-02,2019-12-31,2019-01-03,2020-01-09,0.114296,0.145339,NaN,NaN,0.031043,0.004606,0.004584,0.000022,0.004674,0.000090
10,year_2020,cash5,253,2020-01-02,2020-12-31,2020-01-03,2021-01-11,0.195588,0.224863,NaN,NaN,0.029275,0.002743,0.002721,0.000022,0.002810,0.000089
11,year_2020,leverage5,253,2020-01-02,2020-12-31,2020-01-03,2021-01-11,0.131119,0.174632,NaN,NaN,0.043512,0.015466,0.015449,0.000017,0.014647,-0.000802
12,year_2021,cash5,252,2021-01-04,2021-12-31,2021-01-05,2022-01-10,0.078439,0.102780,NaN,NaN,0.024342,0.001288,0.001376,-0.000088,0.001301,-0.000075
13,year_2021,leverage5,252,2021-01-04,2021-12-31,2021-01-05,2022-01-10,0.040415,0.079638,NaN,NaN,0.039223,0.005367,0.005821,-0.000453,0.005371,-0.000450
14,year_2022,cash5,251,2022-01-03,2022-12-30,2022-01-04,2023-01-10,0.053111,-0.040892,NaN,NaN,-0.094003,0.003481,0.004123,-0.000642,0.003243,-0.000881
15,year_2022,leverage5,251,2022-01-03,2022-12-30,2022-01-04,2023-01-10,0.064886,-0.030125,NaN,NaN,-0.095010,0.013919,0.016700,-0.002781,0.013499,-0.003201

,slice,family,head,cost_bps,log_hurdle,event_count,coverage,mean_event_gross_log_bp,mean_event_net_log_bp,conditional_mean_undefined_reason,event_scope
0,development_2016_2022,base,cash5,10,0.002,204,0.115778,12.612950,-7.387057,NaN,isolated_overlapping_H5_SOXX_roundtrip_not_por...
1,development_2016_2022,base,cash5,25,0.005,58,0.032917,13.226156,-36.773948,NaN,isolated_overlapping_H5_SOXX_roundtrip_not_por...
2,development_2016_2022,base_plus_earnings,cash5,10,0.002,451,0.255959,-9.026818,-29.026825,NaN,isolated_overlapping_H5_SOXX_roundtrip_not_por...
3,development_2016_2022,base_plus_earnings,cash5,25,0.005,238,0.135074,4.611494,-45.388610,NaN,isolated_overlapping_H5_SOXX_roundtrip_not_por...
4,development_2016_2022,prior_mean,cash5,10,0.002,0,0.000000,NaN,NaN,no_events,isolated_overlapping_H5_SOXX_roundtrip_not_por...
...,...,...,...,...,...,...,...,...,...,...,...
91,year_2022,base,leverage5,25,0.010,121,0.482072,-221.642080,-321.642289,NaN,isolated_overlapping_H5_SOXX_roundtrip_not_por...
92,year_2022,base_plus_earnings,leverage5,10,0.004,190,0.756972,-318.017974,-358.017988,NaN,isolated_overlapping_H5_SOXX_roundtrip_not_por...
93,year_2022,base_plus_earnings,leverage5,25,0.010,169,0.673307,-321.132027,-421.132235,NaN,isolated_overlapping_H5_SOXX_roundtrip_not_por...
94,year_2022,prior_mean,leverage5,10,0.004,0,0.000000,NaN,NaN,no_events,isolated_overlapping_H5_SOXX_roundtrip_not_por...
95,year_2022,prior_mean,leverage5,25,0.010,0,0.000000,NaN,NaN,no_events,isolated_overlapping_H5_SOXX_roundtrip_not_por...

# 财报预期差：SOXX/SOXL/cash 指增信息层诊断

本轮仅检验财报信息是否增加现有指增预测能力，没有运行仓位策略或真实订单。固定 NVDA/AMD/INTC 三个历史 EPS surprise 特征，与同样本 BASE5 对照；每年两次双输出 StandardScaler + Ridge(alpha=10)，共14次拟合。训练自2011年起，评价2016–2022七年，20行剔除与真实H5成熟时间门。2023及以后信号日未产生预测或评价；2022末信号的H5结果允许在2023年初成熟，完整保留。

**数据源不满足部署门：历史供应商 EPS/一致预期快照缺少当时版本归档，可能有事后修订。保守延迟报告可见时间不能消除这个缺口。三家公司也是固定代理，不代表完整历史半导体成分。NVDA早期EPS约0.004–0.007且仅三位小数，回溯拆股调整与舍入可能改变surprise；本轮保留登记值与公式，不修数或换公司。无论下列指标如何，本轮不晋升。**

- cash5：1762个开发期观察，BASE5/加财报 IC=0.042432/0.069832，ΔIC=0.027400，MSE改善(base-full)=-0.000105。全特征IC正/IC增量正/MSE改善年数为6/4/3（各7年）；信息/增量/费用事件门=False/False/False。
- leverage5：1762个开发期观察，BASE5/加财报 IC=0.009434/0.049621，ΔIC=0.040187，MSE改善(base-full)=-0.000476。全特征IC正/IC增量正/MSE改善年数为6/4/3（各7年）；信息/增量/费用事件门=False/False/False。

cash5预测SOXX转现金的五日相对对数收益；leverage5预测SOXL对SOXX的五日相对对数收益。两头使用同一组20/60日期块、各2000次配对抽样；两头调整后的下1.25%界用于门禁，未定义抽样直接失败；该调整仅覆盖本次两个固定头，不覆盖此前全部研究次数。全部市场历史均已查看，不是新的留出样本。逐年差异见point_metrics.csv。季度状态持续多日，日数不是独立财报事件数，bootstrap亦不能消除历史复用和供应商修订风险。

费用事件从已经持有SOXX出发，cash5门槛为h=log((1+c)/(1-c))；leverage5四条股票交易腿为2h。10/25bp均计算base/full/prior。事件互相重叠，只作独立五日费用诊断，不复利、不年化，不是投资组合或稳定超额证明。

结论：`end_fixed_recipe_no_further_search`。source_deployment_gate=False，稳定超额目标未达成。下一步只允许先取得可信的历史时点预期版本，再另立验证；本轮不换符号、期限、特征或门槛继续筛选。即使信息门通过，也须另行接入精确费用结算、SOXX和同平均仓位静态对照及风险门，不能直接部署。

Qlib Recorder：`b3674e7f2d7c41a5b8827c99f316969a`。大型预测、模型和抽样仅存Recorder；本卡保留审计入口。