# NQ overnight 18:00→10:00 → 10:31 之后收益（0 模型诊断）

决策 10:31 ET；信号由 60min Qlib store 读取；session_close 由官方 receipt（WHOLE/MORNING）决定；
long-only（SOXL/SOXX/cash）日内 cash→持仓→session close→cash；20-session 移动块 CI；缺时钟 needs_data。

In [1]:
import sys, json, hashlib
from pathlib import Path

ROOT = Path.cwd()
while not (ROOT/'AGENTS.md').exists():
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))
CARD = ROOT/'research'/'stage1_nq_overnight_after1031_20261010'
print('plan sha256:', hashlib.sha256((CARD/'plan.json').read_bytes()).hexdigest())

plan sha256: df4d8c9d012a39aff420e80cdc4ced0ec17d44fdb33fbe7ce6b8f448dbfb8e91

In [2]:
from src.workflow import nq_overnight_after1031 as workflow
summary = workflow.run_nq_overnight_after1031(root=ROOT, card_dir=CARD)
print('decision:', summary['decision'], '|', summary['reason'])
print('coverage:', {k: summary[k] for k in ['official_days_in_range','sessions','dropped_needs_data','morning_days_in_range','missing_nq_signal_days']})
print('execution proxy:', summary['execution_proxy'])
print('recorder:', summary['recorder_id'])

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[78169:MainThread](2026-10-10 01:31:49,806) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

2026/10/10 01:31:50 INFO mlflow.agent.hint: Load the `instrumenting-with-mlflow-tracing` skill at /Users/rziiiii/dev/workspace/qlib_venv/lib/python3.12/site-packages/mlflow/assistant/skills/instrumenting-with-mlflow-tracing/SKILL.md before writing any tracing code; it ships with this MLflow install. Set MLFLOW_DISABLE_AGENT_HINT=1 to silence this.

[78169:MainThread](2026-10-10 01:31:50,202) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[78169:MainThread](2026-10-10 01:31:50,203) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/nq_futures_60min_20261010_v1')}

[78169:MainThread](2026-10-10 01:32:49,262) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[78169:MainThread](2026-10-10 01:32:49,263) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[78169:MainThread](2026-10-10 01:32:49,263) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_intraday_20261009')}

[78169:MainThread](2026-10-10 01:33:00,758) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[78169:MainThread](2026-10-10 01:33:00,759) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[78169:MainThread](2026-10-10 01:33:00,759) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[78169:MainThread](2026-10-10 01:33:00,791) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[78169:MainThread](2026-10-10 01:33:00,792) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[78169:MainThread](2026-10-10 01:33:00,792) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_intraday_20261009')}

[78169:MainThread](2026-10-10 01:33:00,797) WARNING - qlib.workflow - [expm.py:231] - No valid experiment found. Create a new experiment with name stage1_nq_overnight_after1031_20261010.

[78169:MainThread](2026-10-10 01:33:00,798) INFO - qlib.workflow - [exp.py:258] - Experiment 972630437874833678 starts running ...

[78169:MainThread](2026-10-10 01:33:00,854) INFO - qlib.workflow - [recorder.py:345] - Recorder 846542c84829474d9f8c409f670b3829 starts running under Experiment 972630437874833678 ...

[78169:MainThread](2026-10-10 01:33:01,194) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

decision: end_route_no_further_search | no long-only NQ>0->SOXL rule edge with a positive CI at the 25bp roundtrip stress
coverage: {'official_days_in_range': 492, 'sessions': 469, 'dropped_needs_data': 23, 'morning_days_in_range': 5, 'missing_nq_signal_days': 22}
execution proxy: entry mark is the predeclared historical 10:30 close; decision is 10:31 ET; NOT verified real 10:31 fills
recorder: 846542c84829474d9f8c409f670b3829

In [3]:
import pandas as pd
print('=== spread IC primary ==='); display(pd.read_csv(CARD/'spread_ic_primary.csv').round(4))
print('=== individual IC (descriptive) ==='); display(pd.read_csv(CARD/'individual_ic.csv').round(4))
print('=== economic long-only (bps/day) ==='); display(pd.read_csv(CARD/'economic_long_only.csv').round(2))
print('=== SOXX buyhold account ==='); print(summary['soxx_buyhold_account'])

=== spread IC primary ===

    point  ci_low  ci_high  blocks status
0  0.0386 -0.0449   0.1139     473     ok

=== individual IC (descriptive) ===

           Unnamed: 0   point  ci_low  ci_high  blocks status
0  soxl_session_close  0.0457 -0.0395   0.1227     473     ok
1  soxx_session_close  0.0597 -0.0266   0.1394     473     ok
2     soxl_close_1300  0.0831 -0.0161   0.1677     473     ok
3     soxx_close_1300  0.0900 -0.0113   0.1750     473     ok

=== economic long-only (bps/day) ===

,book,cost_bps,mean_net_bps,ci_low_bps,ci_high_bps,ci_status,legs
0,rule_NQpos_SOXL_else_SOXX,10.0,0.85,-29.07,32.66,ok,"cash->target at 10:30, target->cash at session..."
1,rule_NQpos_SOXL_else_SOXX,25.0,-29.11,-58.94,2.60,ok,"cash->target at 10:30, target->cash at session..."
2,soxl_only,10.0,-12.09,-46.68,27.84,ok,"cash->target at 10:30, target->cash at session..."
3,soxl_only,25.0,-42.01,-76.50,-2.20,ok,"cash->target at 10:30, target->cash at session..."
4,soxx_only,10.0,-17.31,-29.10,-3.82,ok,"cash->target at 10:30, target->cash at session..."
5,soxx_only,25.0,-47.21,-58.97,-33.76,ok,"cash->target at 10:30, target->cash at session..."

=== SOXX buyhold account ===
{10: {'return_pct': 147.7823416553354, 'sessions': 490, 'status': 'ok', 'missing_marks': []}, 25: {'return_pct': 147.41159500946173, 'sessions': 490, 'status': 'ok', 'missing_marks': []}}

## 中文结论

In [4]:
from IPython.display import Markdown, display
display(Markdown((CARD/'conclusion.md').read_text()))

# NQ overnight 18:00→10:00 → 10:31 之后收益（0 模型诊断）
- 0 新模型；固定决策 10:31 ET；固定单一信号 NQ overnight 18:00→10:00（由 60min Qlib store 读取，09:00 bar close=10:00，早于决策）。
- 官方交易日 receipt digest 校验通过（sha `d7f5577b2730`）；session_close 由 receipt 的 WHOLE/MORNING 决定（16:00/13:00）。
- 覆盖：official_days_in_range=492，sessions=469，needs_data=23，morning_days=5（有效 0），missing_nq_signal_days=22。
- 执行口径：entry mark is the predeclared historical 10:30 close; decision is 10:31 ET; NOT verified real 10:31 fills；the NQ sign is a directional description; economics are long-only, no short portfolio。
### 主预测目标：SOXL−SOXX 价差 IC（20-session 移动块 CI）
- spread IC +0.0386 CI [-0.0449, +0.1139]
### long-only 日内经济净优势（bps/日，cash→持仓→cash，两腿费用）
- rule_NQpos_SOXL_else_SOXX @10bp：+0.85 CI [-29.07, +32.66]
- rule_NQpos_SOXL_else_SOXX @25bp：-29.11 CI [-58.94, +2.60]
- soxl_only @10bp：-12.09 CI [-46.68, +27.84]
- soxl_only @25bp：-42.01 CI [-76.50, -2.20]
- soxx_only @10bp：-17.31 CI [-29.10, -3.82]
- soxx_only @25bp：-47.21 CI [-58.97, -33.76]
### SOXX 真正 buyhold（跨夜连续账户，独立于 10:30 入场）
- @10bp：147.78%（490 sessions）
- @25bp：147.41%（490 sessions）
### 相对描述：rule − same-window SOXX（同费用完整 roundtrip，非 signed short spread）
- @10bp：+18.16 bps CI [-1.14, +38.29]（仅描述，相对正不能掩盖绝对亏损）
- @25bp：+18.10 bps CI [-1.14, +38.18]（仅描述，相对正不能掩盖绝对亏损）
### 三账户 absolute/net 风险与财富
- rule_NQpos_SOXL_else_SOXX @10bp：cum -24.71% / MaxDD -56.89% / worst -23.05% / CVaR5 -7.84%
- soxl_only @10bp：cum -66.36% / MaxDD -76.69% / worst -23.05% / CVaR5 -11.70%
- soxx_only @10bp：cum -58.23% / MaxDD -60.44% / worst -8.54% / CVaR5 -4.02%
- rule_NQpos_SOXL_else_SOXX @25bp：cum -81.56% / MaxDD -84.56% / worst -23.28% / CVaR5 -8.11%
- soxl_only @25bp：cum -91.76% / MaxDD -93.01% / worst -23.28% / CVaR5 -11.97%
- soxx_only @25bp：cum -89.77% / MaxDD -90.12% / worst -8.81% / CVaR5 -4.31%
- **决定：`end_route_no_further_search`** — no long-only NQ>0->SOXL rule edge with a positive CI at the 25bp roundtrip stress。
- native：full_strategy_native=`needs_data`（root helper covers opening/recovery slots; the 10:30 entry->session_close two-leg roundtrip is not directly adaptable）；已记录 real settle_target_session fee/cash/weight paths per day (normalized account)；不借用之前 control native PASS。
- 本固定机制未获得足够证据（预测 IC 跨 0、25bp 绝对为负）；不反号/改 horizon/阈值，仅停止本路，不宣称“信息不存在”或“模型永无救”。
- NQ=F 为 Yahoo 前月连续序列，roll/调整不构成独立证据。
- 子 Recorder：846542c84829474d9f8c409f670b3829；保存 panel/audit/IC/economic。