# Stage1 action 边际信息诊断（修正版）

现役 action logistic 模型的**真 OOS 条件信息**（每年用该年已保存 pipeline 预测）+ **分段×成本**净贡献
+ 同成交同费用的 SOXX 参照。

In [1]:
import sys, json, hashlib
from pathlib import Path

ROOT = Path.cwd()
while not (ROOT/'AGENTS.md').exists():
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))
CARD = ROOT/'research'/'stage1_action_marginal_diagnosis_20261009'
print('plan sha256:', hashlib.sha256((CARD/'plan.json').read_bytes()).hexdigest())

plan sha256: 5ad101dda557eb3737eb1471f1682593fb678e5d814ee947dd6080d19a1d31fb

In [2]:
from src.workflow import action_marginal_diagnosis as workflow
summary = workflow.run_action_marginal_diagnosis(root=ROOT, card_dir=CARD)
print('decision:', summary['decision'])
print('recorder_id:', summary['recorder_id'])
print('conditional_information:', json.dumps(summary['conditional_information'], ensure_ascii=False, default=str)[:400])

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

2026/10/09 22:07:17 INFO mlflow.agent.hint: Load the `instrumenting-with-mlflow-tracing` skill at /Users/rziiiii/dev/workspace/qlib_venv/lib/python3.12/site-packages/mlflow/assistant/skills/instrumenting-with-mlflow-tracing/SKILL.md before writing any tracing code; it ships with this MLflow install. Set MLFLOW_DISABLE_AGENT_HINT=1 to silence this.

[67543:MainThread](2026-10-09 22:07:17,940) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67543:MainThread](2026-10-09 22:07:17,941) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67543:MainThread](2026-10-09 22:07:17,942) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[67543:MainThread](2026-10-09 22:07:19,281) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67543:MainThread](2026-10-09 22:07:19,282) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67543:MainThread](2026-10-09 22:07:19,282) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[67543:MainThread](2026-10-09 22:07:19,351) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67543:MainThread](2026-10-09 22:07:19,352) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67543:MainThread](2026-10-09 22:07:19,352) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[67543:MainThread](2026-10-09 22:07:19,364) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67543:MainThread](2026-10-09 22:07:19,364) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67543:MainThread](2026-10-09 22:07:19,365) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[67543:MainThread](2026-10-09 22:07:19,374) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[67543:MainThread](2026-10-09 22:07:19,379) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[67543:MainThread](2026-10-09 22:07:19,386) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[67543:MainThread](2026-10-09 22:07:19,386) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[67543:MainThread](2026-10-09 22:07:19,388) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x12125bc20>

backtest loop:   0%|          | 0/1756 [00:00<?, ?it/s]

[67543:MainThread](2026-10-09 22:07:20,569) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67543:MainThread](2026-10-09 22:07:20,570) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67543:MainThread](2026-10-09 22:07:20,570) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[67543:MainThread](2026-10-09 22:07:20,583) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67543:MainThread](2026-10-09 22:07:20,583) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67543:MainThread](2026-10-09 22:07:20,584) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[67543:MainThread](2026-10-09 22:07:20,594) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[67543:MainThread](2026-10-09 22:07:20,599) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[67543:MainThread](2026-10-09 22:07:20,605) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[67543:MainThread](2026-10-09 22:07:20,606) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[67543:MainThread](2026-10-09 22:07:20,608) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x1221e3890>

backtest loop:   0%|          | 0/1756 [00:00<?, ?it/s]

[67543:MainThread](2026-10-09 22:07:21,706) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67543:MainThread](2026-10-09 22:07:21,707) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67543:MainThread](2026-10-09 22:07:21,708) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[67543:MainThread](2026-10-09 22:07:21,774) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67543:MainThread](2026-10-09 22:07:21,775) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67543:MainThread](2026-10-09 22:07:21,775) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[67543:MainThread](2026-10-09 22:07:21,787) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67543:MainThread](2026-10-09 22:07:21,788) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67543:MainThread](2026-10-09 22:07:21,788) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[67543:MainThread](2026-10-09 22:07:21,798) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[67543:MainThread](2026-10-09 22:07:21,802) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[67543:MainThread](2026-10-09 22:07:21,809) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[67543:MainThread](2026-10-09 22:07:21,809) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[67543:MainThread](2026-10-09 22:07:21,812) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x121e66a50>

backtest loop:   0%|          | 0/1756 [00:00<?, ?it/s]

[67543:MainThread](2026-10-09 22:07:22,798) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67543:MainThread](2026-10-09 22:07:22,799) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67543:MainThread](2026-10-09 22:07:22,799) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[67543:MainThread](2026-10-09 22:07:22,812) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67543:MainThread](2026-10-09 22:07:22,813) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67543:MainThread](2026-10-09 22:07:22,813) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[67543:MainThread](2026-10-09 22:07:22,824) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[67543:MainThread](2026-10-09 22:07:22,828) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[67543:MainThread](2026-10-09 22:07:22,835) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[67543:MainThread](2026-10-09 22:07:22,835) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[67543:MainThread](2026-10-09 22:07:22,838) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x123226870>

backtest loop:   0%|          | 0/1756 [00:00<?, ?it/s]

[67543:MainThread](2026-10-09 22:07:23,851) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67543:MainThread](2026-10-09 22:07:23,852) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67543:MainThread](2026-10-09 22:07:23,852) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[67543:MainThread](2026-10-09 22:07:23,854) WARNING - qlib.workflow - [expm.py:231] - No valid experiment found. Create a new experiment with name stage1_action_marginal_diagnosis_20261009.

[67543:MainThread](2026-10-09 22:07:23,856) INFO - qlib.workflow - [exp.py:258] - Experiment 980599116697540100 starts running ...

[67543:MainThread](2026-10-09 22:07:24,034) INFO - qlib.workflow - [recorder.py:345] - Recorder 16b6769b3fc848a2b3004dbb126aaf2a starts running under Experiment 980599116697540100 ...

[67543:MainThread](2026-10-09 22:07:24,112) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

decision: diagnostic_reported_no_strategy
recorder_id: 16b6769b3fc848a2b3004dbb126aaf2a
conditional_information: {"status": "ok", "label_source": "active_model_own_execute_advantage", "scope": "active_model_own_oos_label", "decidable_rule": "not mandatory_derisk and not large_transition and finite probability", "decidable_sessions": 410, "full_oos_sessions": 1503, "positive_advantage_rate": 0.5146341463414634, "mean_advantage": -1.6395794863109965e-05, "mean_predicted_probability": 0.51067716834179, "rank_ic

In [3]:
import pandas as pd
print('=== 分段×成本 净贡献 ===')
display(pd.read_csv(CARD/'contribution_comparison.csv').round(3))
print('=== SOXX 参照（同成交同费用）===')
display(pd.read_csv(CARD/'reference_comparison.csv').round(3))
print('=== 概率分组校准 ===')
display(pd.read_csv(CARD/'probability_calibration.csv').round(5))

=== 分段×成本 净贡献 ===

,segment,cost_bps,variant,sessions,gaps,return_pct,no_hold_return_pct,net_contribution_pct,max_drawdown_pct,cvar5_pct,sharpe
0,development,10.0,active,1756,0,170.745,115.036,55.709,-30.083,-3.539,0.762
1,development,10.0,no_hold,1756,0,115.036,115.036,0.000,-29.931,-3.485,0.623
2,development,10.0,rules_only,1756,0,171.492,115.036,56.456,-29.674,-3.524,0.770
3,development,10.0,own_state_frozen,1756,0,200.489,115.036,85.453,-29.028,-3.056,0.931
4,development,10.0,own_state_expanding,1756,0,200.489,115.036,85.453,-29.028,-3.056,0.931
5,development,25.0,active,1756,0,96.761,151.270,-54.510,-30.078,-3.585,0.548
6,development,25.0,no_hold,1756,0,151.270,151.270,0.000,-30.000,-3.643,0.694
7,development,25.0,rules_only,1756,0,98.975,151.270,-52.295,-30.100,-3.563,0.560
8,development,25.0,own_state_frozen,1756,0,160.852,151.270,9.581,-30.179,-3.078,0.834
9,development,25.0,own_state_expanding,1756,0,160.852,151.270,9.581,-30.179,-3.078,0.834
10,outer_reused_diagnostic,10.0,active,934,0,219.426,220.367,-0.941,-26.922,-4.795,1.134
11,outer_reused_diagnostic,10.0,no_hold,934,0,220.367,220.367,0.000,-26.922,-4.812,1.134
12,outer_reused_diagnostic,10.0,rules_only,934,0,220.818,220.367,0.450,-26.920,-4.797,1.137
13,outer_reused_diagnostic,10.0,own_state_frozen,934,0,362.837,220.367,142.470,-26.482,-4.766,1.438
14,outer_reused_diagnostic,10.0,own_state_expanding,934,0,187.589,220.367,-32.778,-26.804,-4.609,1.096
15,outer_reused_diagnostic,25.0,active,934,0,75.109,66.087,9.022,-32.381,-4.421,0.686
16,outer_reused_diagnostic,25.0,no_hold,934,0,66.087,66.087,0.000,-36.442,-4.403,0.639
17,outer_reused_diagnostic,25.0,rules_only,934,0,74.796,66.087,8.709,-32.888,-4.425,0.684
18,outer_reused_diagnostic,25.0,own_state_frozen,934,0,324.649,66.087,258.562,-26.851,-4.694,1.382
19,outer_reused_diagnostic,25.0,own_state_expanding,934,0,260.902,66.087,194.815,-27.194,-4.737,1.248

=== SOXX 参照（同成交同费用）===

,reference,cost_bps,sessions,return_pct,max_drawdown_pct,cvar5_pct,sharpe,native_status
0,soxx_buy_hold,10.0,1756,320.284,-47.374,-4.418,0.828,passed
1,soxx_cash_50_50,10.0,1756,121.043,-26.239,-2.209,0.822,passed
2,soxx_buy_hold,25.0,1756,319.655,-47.374,-4.419,0.827,passed
3,soxx_cash_50_50,25.0,1756,118.835,-26.356,-2.211,0.813,passed

=== 概率分组校准 ===

   bucket  count  mean_probability  mean_advantage
0       0     82           0.41842        -0.00002
1       1     82           0.47378        -0.00004
2       2     82           0.50819        -0.00013
3       3     82           0.54304         0.00003
4       4     82           0.60996         0.00008

## 中文结论

In [4]:
from IPython.display import Markdown, display
display(Markdown((CARD/'conclusion.md').read_text()))

# Stage1 action 边际信息诊断（中文结论）
- 主对象：**现役 action logistic 模型**；预测为该年**已保存 pipeline**（仅用更早数据拟合）的输出，标签为**同一基线域**的真实 `execute_advantage`，严格成熟。
- 源证据（只读、对象 sha256 绑定，plan sha `5ad101dda557`）：recorder `17f81fbf27ee46859816ec1ac52151f6`；窗口 dev ['2016-01-04', '2022-12-21']，outer ['2023-01-03', '2026-09-23']（分段 reset，不拼接）。
- 撤回：跨账户 active−no_hold 当标签的旧做法作废；旧 AUC 0.321 / 2438 样本结果无效。
- 模型成熟度：逐年断言 label_available_at_max < test_decision_at（源 dataset_audit/training_diagnostics）。
- native 边界：SOXX/cash 参照仅经 open-only 原生对账；无完整 intraday 原生账本（2016-18 无 15min）。
- 真 OOS 条件信息（decidable n=410 / full 1503）：AUC 0.5168 CI [0.467,0.575] null=0.5；rank IC +0.0729 CI [-0.015,+0.171] null=0.0；标签均值 CI [-0.824,0.325] bp。
- 显著性声明：仅报上述 CI；若 rankIC/AUC/均值 CI 均含各自 null，则不声称存在条件信息，也不声称反号可用。
- 分段×成本净贡献（各自 reset，不跨段相乘）：
  - development @ 10bp active：收益 170.7%，净贡献 +55.7pp，MaxDD -30.08%，gap 0。
  - development @ 10bp no_hold：收益 115.0%，净贡献 +0.0pp，MaxDD -29.93%，gap 0。
  - development @ 10bp rules_only：收益 171.5%，净贡献 +56.5pp，MaxDD -29.67%，gap 0。
  - development @ 10bp own_state_frozen：收益 200.5%，净贡献 +85.5pp，MaxDD -29.03%，gap 0。
  - development @ 10bp own_state_expanding：收益 200.5%，净贡献 +85.5pp，MaxDD -29.03%，gap 0。
  - development @ 25bp active：收益 96.8%，净贡献 -54.5pp，MaxDD -30.08%，gap 0。
  - development @ 25bp no_hold：收益 151.3%，净贡献 +0.0pp，MaxDD -30.00%，gap 0。
  - development @ 25bp rules_only：收益 99.0%，净贡献 -52.3pp，MaxDD -30.10%，gap 0。
  - development @ 25bp own_state_frozen：收益 160.9%，净贡献 +9.6pp，MaxDD -30.18%，gap 0。
  - development @ 25bp own_state_expanding：收益 160.9%，净贡献 +9.6pp，MaxDD -30.18%，gap 0。
  - outer_reused_diagnostic @ 10bp active：收益 219.4%，净贡献 -0.9pp，MaxDD -26.92%，gap 0。
  - outer_reused_diagnostic @ 10bp no_hold：收益 220.4%，净贡献 +0.0pp，MaxDD -26.92%，gap 0。
  - outer_reused_diagnostic @ 10bp rules_only：收益 220.8%，净贡献 +0.5pp，MaxDD -26.92%，gap 0。
  - outer_reused_diagnostic @ 10bp own_state_frozen：收益 362.8%，净贡献 +142.5pp，MaxDD -26.48%，gap 0。
  - outer_reused_diagnostic @ 10bp own_state_expanding：收益 187.6%，净贡献 -32.8pp，MaxDD -26.80%，gap 0。
  - outer_reused_diagnostic @ 25bp active：收益 75.1%，净贡献 +9.0pp，MaxDD -32.38%，gap 0。
  - outer_reused_diagnostic @ 25bp no_hold：收益 66.1%，净贡献 +0.0pp，MaxDD -36.44%，gap 0。
  - outer_reused_diagnostic @ 25bp rules_only：收益 74.8%，净贡献 +8.7pp，MaxDD -32.89%，gap 0。
  - outer_reused_diagnostic @ 25bp own_state_frozen：收益 324.6%，净贡献 +258.6pp，MaxDD -26.85%，gap 0。
  - outer_reused_diagnostic @ 25bp own_state_expanding：收益 260.9%，净贡献 +194.8pp，MaxDD -27.19%，gap 0。
- SOXX 参照（同成交、同成本、含费用）：
  - soxx_buy_hold @ 10bp：收益 320.3%，MaxDD -47.37%
  - soxx_cash_50_50 @ 10bp：收益 121.0%，MaxDD -26.24%
  - soxx_buy_hold @ 25bp：收益 319.7%，MaxDD -47.37%
  - soxx_cash_50_50 @ 25bp：收益 118.8%，MaxDD -26.36%
- 下一步：只在 OOS 条件信息与分段归因给出证据后才选具体修正实验；本卡不导向叠加风险 cap。
- 子 Recorder：16b6769b3fc848a2b3004dbb126aaf2a；父只读不改。