# Auxiliary 3x training-data allocation

其他3x ETF只进入训练行；所有开发期和outer测试均为SOXL。

In [1]:
from pathlib import Path
import sys
import qlib
from qlib.data import D
from qlib.data.dataset import DatasetH
from qlib.workflow import R
repo_root = Path.cwd().parents[1]
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))
qlib.init(provider_uri=str(repo_root / 'data/qlib/soxl'), region='us', kernels=1, skip_if_reg=False)
calendar = D.calendar(start_time='2011-01-03', end_time='2026-07-02', freq='day')
from src.workflow.auxiliary_3x_training_data_allocation import run_auxiliary_3x_training_data_allocation_card
summary = run_auxiliary_3x_training_data_allocation_card(root=repo_root)
summary['promotion_decision']

[67077:MainThread](2026-07-24 00:30:50,595) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67077:MainThread](2026-07-24 00:30:50,596) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67077:MainThread](2026-07-24 00:30:50,596) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[67077:MainThread](2026-07-24 00:30:51,889) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67077:MainThread](2026-07-24 00:30:51,889) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67077:MainThread](2026-07-24 00:30:51,890) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[67077:MainThread](2026-07-24 00:30:51,894) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67077:MainThread](2026-07-24 00:30:51,895) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67077:MainThread](2026-07-24 00:30:51,895) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[67077:MainThread](2026-07-24 00:30:51,913) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67077:MainThread](2026-07-24 00:30:51,913) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67077:MainThread](2026-07-24 00:30:51,914) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/tqqq')}

[67077:MainThread](2026-07-24 00:30:51,917) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67077:MainThread](2026-07-24 00:30:51,918) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67077:MainThread](2026-07-24 00:30:51,918) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/tqqq')}

[67077:MainThread](2026-07-24 00:30:51,933) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67077:MainThread](2026-07-24 00:30:51,934) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67077:MainThread](2026-07-24 00:30:51,934) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/upro')}

[67077:MainThread](2026-07-24 00:30:51,937) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67077:MainThread](2026-07-24 00:30:51,938) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67077:MainThread](2026-07-24 00:30:51,938) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/upro')}

[67077:MainThread](2026-07-24 00:30:51,953) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67077:MainThread](2026-07-24 00:30:51,954) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67077:MainThread](2026-07-24 00:30:51,954) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/spxl')}

[67077:MainThread](2026-07-24 00:30:51,958) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67077:MainThread](2026-07-24 00:30:51,959) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67077:MainThread](2026-07-24 00:30:51,959) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/spxl')}

[67077:MainThread](2026-07-24 00:30:51,974) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67077:MainThread](2026-07-24 00:30:51,975) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67077:MainThread](2026-07-24 00:30:51,975) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/tecl')}

[67077:MainThread](2026-07-24 00:30:51,979) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67077:MainThread](2026-07-24 00:30:51,980) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67077:MainThread](2026-07-24 00:30:51,980) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/tecl')}

[67077:MainThread](2026-07-24 00:31:16,553) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[67077:MainThread](2026-07-24 00:31:16,554) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[67077:MainThread](2026-07-24 00:31:16,554) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[67077:MainThread](2026-07-24 00:31:16,558) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67077:MainThread](2026-07-24 00:31:16,558) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67077:MainThread](2026-07-24 00:31:16,559) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[67077:MainThread](2026-07-24 00:31:16,578) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67077:MainThread](2026-07-24 00:31:16,579) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67077:MainThread](2026-07-24 00:31:16,579) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[67077:MainThread](2026-07-24 00:31:16,936) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[67077:MainThread](2026-07-24 00:31:16,937) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[67077:MainThread](2026-07-24 00:31:16,938) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[67077:MainThread](2026-07-24 00:31:22,542) INFO - qlib.workflow - [exp.py:258] - Experiment 743878911069380708 starts running ...

[67077:MainThread](2026-07-24 00:31:22,606) INFO - qlib.workflow - [recorder.py:345] - Recorder d0d1e39b74fc4203ac28a25386edff3a starts running under Experiment 743878911069380708 ...

[67077:MainThread](2026-07-24 00:31:22,746) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

'not_promoted_auxiliary_training_data_risk_gates_failed'

In [2]:
import pandas as pd
card = Path.cwd()
pd.read_csv(card / 'model_selection.csv')

,segment,candidate,cost_bps,selection_uses_outer_test,return_pct,cagr_pct,annualized_vol_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,...,worst_day_gate,cvar_gate,worst_5d_gate,cash_gate,capture_gate,gate_count,all_gate,selection_score,diagnostic_selected,selection_policy
0,development_walk_forward,soxl_only_common_features,10,False,300.135641,21.934683,33.373793,-52.715976,-11.047537,-4.826001,...,True,True,False,True,False,4,False,-0.297977,False,development_only_gate_count_then_score
1,development_walk_forward,spxl_aux_half_weight,10,False,319.196859,22.748950,33.831583,-53.197829,-11.372130,-4.861293,...,True,True,False,True,False,4,False,-0.150857,False,development_only_gate_count_then_score
2,development_walk_forward,tech_spxl_aux_weighted,10,False,317.915056,22.695200,33.648281,-52.543122,-10.899468,-4.825892,...,True,True,False,True,False,4,False,-0.143957,True,development_only_gate_count_then_score

In [3]:
pd.read_csv(card / 'training_data_audit.csv')

,candidate,segment,fold_year,train_end,training_assets,test_assets,selection_uses_outer_test,loss,allocation_loss,cash_floor_loss,best_loss,train_rows,test_rows,auxiliary_train_share
0,soxl_only_common_features,development_walk_forward,2016,2015-12-02,SOXL,SOXL,False,0.014974,0.014974,0.000000e+00,0.014974,1159.0,252.0,0.00
1,soxl_only_common_features,development_walk_forward,2017,2016-12-01,SOXL,SOXL,False,0.015420,0.015420,0.000000e+00,0.015420,1411.0,251.0,0.00
2,soxl_only_common_features,development_walk_forward,2018,2017-11-30,SOXL,SOXL,False,0.016998,0.016998,0.000000e+00,0.016998,1662.0,251.0,0.00
3,soxl_only_common_features,development_walk_forward,2019,2018-11-29,SOXL,SOXL,False,0.017159,0.017159,0.000000e+00,0.017159,1913.0,252.0,0.00
4,soxl_only_common_features,development_walk_forward,2020,2019-12-02,SOXL,SOXL,False,0.019350,0.019350,0.000000e+00,0.019350,2165.0,253.0,0.00
5,soxl_only_common_features,development_walk_forward,2021,2020-12-02,SOXL,SOXL,False,0.021863,0.021863,0.000000e+00,0.021863,2418.0,252.0,0.00
6,soxl_only_common_features,development_walk_forward,2022,2021-12-02,SOXL,SOXL,False,0.022636,0.022636,0.000000e+00,0.022636,2670.0,251.0,0.00
7,soxl_only_common_features,outer_diagnostic,outer_refit,2022-12-30,SOXL,SOXL,False,0.026352,0.026352,0.000000e+00,0.026352,2941.0,877.0,0.00
8,spxl_aux_half_weight,development_walk_forward,2016,2015-12-02,"SOXL,SPXL",SOXL,False,0.017878,0.017867,5.254868e-06,0.017878,2318.0,252.0,0.50
9,spxl_aux_half_weight,development_walk_forward,2017,2016-12-01,"SOXL,SPXL",SOXL,False,0.018267,0.018262,2.535398e-06,0.018267,2822.0,251.0,0.50
10,spxl_aux_half_weight,development_walk_forward,2018,2017-11-30,"SOXL,SPXL",SOXL,False,0.018072,0.018024,2.443161e-05,0.018072,3324.0,251.0,0.50
11,spxl_aux_half_weight,development_walk_forward,2019,2018-11-29,"SOXL,SPXL",SOXL,False,0.018875,0.018855,1.000388e-05,0.018875,3826.0,252.0,0.50
12,spxl_aux_half_weight,development_walk_forward,2020,2019-12-02,"SOXL,SPXL",SOXL,False,0.020823,0.020807,8.035904e-06,0.020823,4330.0,253.0,0.50
13,spxl_aux_half_weight,development_walk_forward,2021,2020-12-02,"SOXL,SPXL",SOXL,False,0.023110,0.023110,2.817900e-07,0.023110,4836.0,252.0,0.50
14,spxl_aux_half_weight,development_walk_forward,2022,2021-12-02,"SOXL,SPXL",SOXL,False,0.023415,0.023414,4.564807e-07,0.023415,5340.0,251.0,0.50
15,spxl_aux_half_weight,outer_diagnostic,outer_refit,2022-12-30,"SOXL,SPXL",SOXL,False,0.027310,0.027310,0.000000e+00,0.027310,5882.0,877.0,0.50
16,tech_spxl_aux_weighted,development_walk_forward,2016,2015-12-02,"SOXL,SPXL,TECL,TQQQ",SOXL,False,0.018439,0.018396,2.165214e-05,0.018439,4636.0,252.0,0.75
17,tech_spxl_aux_weighted,development_walk_forward,2017,2016-12-01,"SOXL,SPXL,TECL,TQQQ",SOXL,False,0.019073,0.019047,1.320502e-05,0.019073,5644.0,251.0,0.75
18,tech_spxl_aux_weighted,development_walk_forward,2018,2017-11-30,"SOXL,SPXL,TECL,TQQQ",SOXL,False,0.019284,0.019187,4.849540e-05,0.019284,6648.0,251.0,0.75
19,tech_spxl_aux_weighted,development_walk_forward,2019,2018-11-29,"SOXL,SPXL,TECL,TQQQ",SOXL,False,0.020287,0.020235,2.553370e-05,0.020287,7652.0,252.0,0.75
20,tech_spxl_aux_weighted,development_walk_forward,2020,2019-12-02,"SOXL,SPXL,TECL,TQQQ",SOXL,False,0.021577,0.021538,1.943127e-05,0.021577,8660.0,253.0,0.75
21,tech_spxl_aux_weighted,development_walk_forward,2021,2020-12-02,"SOXL,SPXL,TECL,TQQQ",SOXL,False,0.024190,0.024181,4.705070e-06,0.024190,9672.0,252.0,0.75
22,tech_spxl_aux_weighted,development_walk_forward,2022,2021-12-02,"SOXL,SPXL,TECL,TQQQ",SOXL,False,0.024079,0.024066,6.492958e-06,0.024079,10680.0,251.0,0.75
23,tech_spxl_aux_weighted,outer_diagnostic,outer_refit,2022-12-30,"SOXL,SPXL,TECL,TQQQ",SOXL,False,0.027983,0.027983,0.000000e+00,0.027983,11764.0,877.0,0.75

In [4]:
pd.read_csv(card / 'window_metrics.csv')

,window,start,end,rows,terminal_wealth_ratio_vs_soxx,avg_cash_weight_pct,avg_soxl_weight_pct,turnover
0,2020_pre_crash,2020-01-02,2020-02-19,33,1.008576,12.842117,11.033119,1.159716
1,2020_crash,2020-02-20,2020-03-23,23,0.923294,16.115661,13.252720,0.998740
2,2020_recovery_early,2020-03-24,2020-05-29,47,1.021524,18.623831,13.899753,2.413350
3,2020_recovery_late,2020-06-01,2020-08-31,65,1.027226,10.661080,11.716797,2.280618
4,2022_bear,2022-01-03,2022-12-30,251,0.904710,17.771205,14.041125,12.397263

In [5]:
pd.read_csv(card / 'objective_gate_audit.csv')

,gate,required,passed,detail
0,auxiliary_assets_training_only,True,True,all development and outer test rows are SOXL
1,outer_not_used_for_selection,True,True,candidate selection uses 2016-2022 SOXL only
2,development_return_10bps,True,False,ratio=0.9786
3,development_return_25bps,True,False,ratio=0.8629
4,development_all_risk_gates,True,False,gate_count=4/9
5,outer_year_robustness,True,False,passing_outer_years=1/4
6,outer_maxdd,True,False,maxdd=-45.94%

# 结论

- 已完成“其他3x只作为训练数据”的严格对照；测试集始终只有SOXL。
- 开发期选择：`tech_spxl_aux_weighted`；10bp相对SOXX=0.9786，25bp=0.8629，正超额年份=6/7，MaxDD=-52.54%。
- Outer仅报告：10bp相对SOXX=1.1578，MaxDD=-45.94%。
- 晋升：`not_promoted_auxiliary_training_data_risk_gates_failed`。
- 失败门：development_return_10bps, development_return_25bps, development_all_risk_gates, outer_year_robustness, outer_maxdd。
- 解释：辅助行改善了部分年度稳定性，但共同归一化特征丢失了SOXL专属alpha，且换手成本抵消了收益；不能替代原有特征模型。
- 下一步：保留该结果作为数据增强边界，不继续扩大pooled权重；若再用其他3x，只允许训练辅助风险头并要求明显超过SOXL-only对照。
- Qlib recorder：`9e569c681c644f34a8c3ad48dca69a7d`。