# 连续配置整合：稳定净超额的受控检验

复用连续配置、PIT训练与真实持仓会计，移除手工交易状态机。三个同结构候选、三个种子、年度成熟标签、10/25bp独立持仓回放。selection_plan.json在模型训练结果之前固定。所有2023–2026均为已看过的复用诊断，不冒充新的未见测试。

In [1]:
import os
from pathlib import Path
os.environ["MLFLOW_ALLOW_FILE_STORE"]="true"
os.environ["MLFLOW_DISABLE_AGENT_HINT"]="1"
root=Path.cwd().resolve()
while not (root / "AGENTS.md").exists(): root=root.parent
import sys
sys.path.insert(0,str(root))
import qlib
from qlib.data import D
from qlib.workflow import R
provider=root / "data/qlib/stable_excess_integration_20261002"
if not provider.exists(): provider=root / "data/qlib/soxl_soxx_soxs"
qlib.init(provider_uri=str(provider),region="us",kernels=1)
print("Frozen calendar:",D.calendar(freq="day")[-1])

[19224:MainThread](2026-10-02 10:13:51,750) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[19224:MainThread](2026-10-02 10:13:51,751) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[19224:MainThread](2026-10-02 10:13:51,752) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/stable-excess-integration-20261002/data/qlib/stable_excess_integration_20261002')}

Frozen calendar: 2026-09-25 00:00:00

In [2]:
from src.workflow.stable_excess_integration import run_experiment
summary=run_experiment(root=root)
summary

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[19224:MainThread](2026-10-02 10:13:53,082) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[19224:MainThread](2026-10-02 10:13:53,082) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[19224:MainThread](2026-10-02 10:13:53,083) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/stable-excess-integration-20261002/data/qlib/stable_excess_integration_20261002')}

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[19224:MainThread](2026-10-02 10:13:53,143) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:13:53,143) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:13:53,143) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:13:53,148) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[19224:MainThread](2026-10-02 10:13:53,149) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[19224:MainThread](2026-10-02 10:13:53,149) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/stable-excess-integration-20261002/data/qlib/stable_excess_integration_20261002')}

[19224:MainThread](2026-10-02 10:13:53,162) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:13:53,162) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:13:53,162) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

Frozen data 3956 primary rows; cache identity 1461dcfe4fd344af99109631d9cb3484a7575fdff0623c00912333a819172e35

[19224:MainThread](2026-10-02 10:13:53,310) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:13:53,310) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:13:53,310) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:13:53,318) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:13:53,318) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:13:53,318) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:13:53,326) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:13:53,326) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:13:53,326) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:13:53,334) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:13:53,334) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:13:53,335) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:13:53,342) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:13:53,342) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:13:53,343) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:13:53,350) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:13:53,351) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:13:53,351) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:13:53,358) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:13:53,359) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:13:53,359) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:13:53,367) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:13:53,368) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:13:53,368) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:13:53,394) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:13:53,394) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:13:53,395) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:13:53,419) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:13:53,419) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:13:53,419) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:13:53,444) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:13:53,444) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:13:53,444) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:13:53,468) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:13:53,469) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:13:53,469) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:13:53,494) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:13:53,494) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:13:53,495) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:13:53,520) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:13:53,520) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:13:53,521) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:13:53,546) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:13:53,547) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:13:53,547) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:13:53,555) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:13:53,555) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:13:53,555) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:13:53,563) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:13:53,563) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:13:53,563) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:13:53,571) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:13:53,571) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:13:53,571) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:13:53,578) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:13:53,579) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:13:53,579) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:13:53,587) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:13:53,587) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:13:53,587) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:13:53,594) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:13:53,595) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:13:53,595) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

Fit complete base seed=17 year=2016 rows=1256 seconds=2.4
Fit complete base seed=41 year=2016 rows=1256 seconds=2.4
Fit complete base seed=71 year=2016 rows=1256 seconds=2.4

Fit complete base seed=17 year=2017 rows=1508 seconds=2.0
Fit complete base seed=41 year=2017 rows=1508 seconds=2.0
Fit complete base seed=71 year=2017 rows=1508 seconds=2.1

Fit complete base seed=17 year=2018 rows=1759 seconds=2.3
Fit complete base seed=41 year=2018 rows=1759 seconds=2.3
Fit complete base seed=71 year=2018 rows=1759 seconds=2.3

Fit complete base seed=17 year=2019 rows=2010 seconds=2.4

Fit complete base seed=71 year=2019 rows=2010 seconds=2.5
Fit complete base seed=41 year=2019 rows=2010 seconds=2.5

Fit complete base seed=17 year=2020 rows=2262 seconds=2.4

Fit complete base seed=71 year=2020 rows=2262 seconds=2.5
Fit complete base seed=41 year=2020 rows=2262 seconds=2.5

Fit complete base seed=17 year=2021 rows=2515 seconds=2.3

Fit complete base seed=71 year=2021 rows=2515 seconds=2.3
Fit complete base seed=41 year=2021 rows=2515 seconds=2.3

Fit complete base seed=17 year=2022 rows=2767 seconds=2.4

Fit complete base seed=71 year=2022 rows=2767 seconds=2.4
Fit complete base seed=41 year=2022 rows=2767 seconds=2.4

Fit complete pit_auxiliary seed=17 year=2016 rows=1256 seconds=2.1

Fit complete pit_auxiliary seed=41 year=2016 rows=1256 seconds=2.1
Fit complete pit_auxiliary seed=71 year=2016 rows=1256 seconds=2.1

Fit complete pit_auxiliary seed=17 year=2017 rows=1508 seconds=2.1

Fit complete pit_auxiliary seed=41 year=2017 rows=1508 seconds=2.1
Fit complete pit_auxiliary seed=71 year=2017 rows=1508 seconds=2.1

Fit complete pit_auxiliary seed=17 year=2018 rows=1759 seconds=2.1

Fit complete pit_auxiliary seed=41 year=2018 rows=1759 seconds=2.2
Fit complete pit_auxiliary seed=71 year=2018 rows=1759 seconds=2.2

Fit complete pit_auxiliary seed=17 year=2019 rows=2010 seconds=2.1

Fit complete pit_auxiliary seed=41 year=2019 rows=2010 seconds=2.1
Fit complete pit_auxiliary seed=71 year=2019 rows=2010 seconds=2.2

Fit complete pit_auxiliary seed=17 year=2020 rows=2262 seconds=2.2

Fit complete pit_auxiliary seed=41 year=2020 rows=2262 seconds=2.2
Fit complete pit_auxiliary seed=71 year=2020 rows=2262 seconds=2.2

Fit complete pit_auxiliary seed=17 year=2021 rows=2515 seconds=2.2

Fit complete pit_auxiliary seed=41 year=2021 rows=2515 seconds=2.2
Fit complete pit_auxiliary seed=71 year=2021 rows=2515 seconds=2.2

Fit complete pit_auxiliary seed=17 year=2022 rows=2767 seconds=2.3

Fit complete pit_auxiliary seed=41 year=2022 rows=2767 seconds=2.3
Fit complete pit_auxiliary seed=71 year=2022 rows=2767 seconds=2.4

Fit complete cash_vol_forecasts seed=17 year=2016 rows=1256 seconds=2.1

Fit complete cash_vol_forecasts seed=41 year=2016 rows=1256 seconds=2.1
Fit complete cash_vol_forecasts seed=71 year=2016 rows=1256 seconds=2.1

Fit complete cash_vol_forecasts seed=17 year=2017 rows=1508 seconds=2.1

Fit complete cash_vol_forecasts seed=41 year=2017 rows=1508 seconds=2.1
Fit complete cash_vol_forecasts seed=71 year=2017 rows=1508 seconds=2.1

Fit complete cash_vol_forecasts seed=17 year=2018 rows=1759 seconds=2.1

Fit complete cash_vol_forecasts seed=41 year=2018 rows=1759 seconds=2.1
Fit complete cash_vol_forecasts seed=71 year=2018 rows=1759 seconds=2.1

Fit complete cash_vol_forecasts seed=17 year=2019 rows=2010 seconds=2.2

Fit complete cash_vol_forecasts seed=41 year=2019 rows=2010 seconds=2.2
Fit complete cash_vol_forecasts seed=71 year=2019 rows=2010 seconds=2.2

Fit complete cash_vol_forecasts seed=17 year=2020 rows=2262 seconds=2.1

Fit complete cash_vol_forecasts seed=41 year=2020 rows=2262 seconds=2.1
Fit complete cash_vol_forecasts seed=71 year=2020 rows=2262 seconds=2.1

Fit complete cash_vol_forecasts seed=17 year=2021 rows=2515 seconds=2.1

Fit complete cash_vol_forecasts seed=41 year=2021 rows=2515 seconds=2.1
Fit complete cash_vol_forecasts seed=71 year=2021 rows=2515 seconds=2.2

Fit complete cash_vol_forecasts seed=17 year=2022 rows=2767 seconds=2.1

Fit complete cash_vol_forecasts seed=41 year=2022 rows=2767 seconds=2.1
Fit complete cash_vol_forecasts seed=71 year=2022 rows=2767 seconds=2.1

Development selection sealed: {'variant': 'cash_vol_forecasts', 'historical_qualification_pass': False, 'passed_gates': 9, 'worst_annualized_lower_bound': -0.26519249630566816, 'worst_relative_wealth': 1.7186507206139465, 'positive_years_10bps': 5}

[19224:MainThread](2026-10-02 10:14:55,897) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:14:55,897) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:14:55,898) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:14:55,907) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:14:55,907) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:14:55,907) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:14:55,916) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:14:55,916) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:14:55,916) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[19224:MainThread](2026-10-02 10:14:55,925) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[19224:MainThread](2026-10-02 10:14:55,925) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[19224:MainThread](2026-10-02 10:14:55,925) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

Fit complete cash_vol_forecasts seed=17 year=2023 rows=3018 seconds=2.6
Fit complete cash_vol_forecasts seed=41 year=2023 rows=3018 seconds=2.6
Fit complete cash_vol_forecasts seed=71 year=2023 rows=3018 seconds=2.6

Fit complete cash_vol_forecasts seed=17 year=2024 rows=3268 seconds=2.0
Fit complete cash_vol_forecasts seed=41 year=2024 rows=3268 seconds=2.1
Fit complete cash_vol_forecasts seed=71 year=2024 rows=3268 seconds=2.1

Fit complete cash_vol_forecasts seed=17 year=2025 rows=3520 seconds=2.1
Fit complete cash_vol_forecasts seed=41 year=2025 rows=3520 seconds=2.1
Fit complete cash_vol_forecasts seed=71 year=2025 rows=3520 seconds=2.1

Fit complete cash_vol_forecasts seed=17 year=2026 rows=3770 seconds=2.1
Fit complete cash_vol_forecasts seed=41 year=2026 rows=3770 seconds=2.0
Fit complete cash_vol_forecasts seed=71 year=2026 rows=3770 seconds=2.1

[19224:MainThread](2026-10-02 10:15:10,068) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[19224:MainThread](2026-10-02 10:15:10,069) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[19224:MainThread](2026-10-02 10:15:10,070) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/stable-excess-integration-20261002/data/qlib/stable_excess_integration_20261002')}

[19224:MainThread](2026-10-02 10:15:10,081) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[19224:MainThread](2026-10-02 10:15:10,086) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[19224:MainThread](2026-10-02 10:15:10,093) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[19224:MainThread](2026-10-02 10:15:10,093) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[19224:MainThread](2026-10-02 10:15:10,096) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x11f8f9dc0>

backtest loop:   0%|          | 0/1762 [00:00<?, ?it/s]

[19224:MainThread](2026-10-02 10:15:11,338) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[19224:MainThread](2026-10-02 10:15:11,339) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[19224:MainThread](2026-10-02 10:15:11,339) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/stable-excess-integration-20261002/data/qlib/stable_excess_integration_20261002')}

[19224:MainThread](2026-10-02 10:15:11,351) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[19224:MainThread](2026-10-02 10:15:11,355) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[19224:MainThread](2026-10-02 10:15:11,362) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[19224:MainThread](2026-10-02 10:15:11,363) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[19224:MainThread](2026-10-02 10:15:11,365) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x120dd8080>

backtest loop:   0%|          | 0/1762 [00:00<?, ?it/s]

[19224:MainThread](2026-10-02 10:15:12,507) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[19224:MainThread](2026-10-02 10:15:12,508) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[19224:MainThread](2026-10-02 10:15:12,508) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/stable-excess-integration-20261002/data/qlib/stable_excess_integration_20261002')}

[19224:MainThread](2026-10-02 10:15:12,510) INFO - qlib.workflow - [exp.py:258] - Experiment 861915197973611996 starts running ...

[19224:MainThread](2026-10-02 10:15:12,562) INFO - qlib.workflow - [recorder.py:345] - Recorder b94059c2e0754b0ab102e4f62534eefb starts running under Experiment 861915197973611996 ...

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[19224:MainThread](2026-10-02 10:15:12,972) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

{'experiment': 'stable_excess_integration_20261002',
 'decision': 'not_promoted_no_stable_excess_evidence',
 'selected': {'variant': 'cash_vol_forecasts',
  'historical_qualification_pass': False,
  'passed_gates': 9,
  'worst_annualized_lower_bound': -0.26519249630566816,
  'worst_relative_wealth': 1.7186507206139465,
  'positive_years_10bps': 5},
 'plan_sha256': '6d2836d363045da5629c6264edbbc0106d19f09fbc0c4890fd3b3ed07c7143c6',
 'source_as_of': '2026-09-25',
 'provider_uri': 'data/qlib/stable_excess_integration_20261002',
 'execution_snapshot_manifest': {'as_of': '2026-09-25',
  'audit_snapshot_hash': '93e9b4b80f47047d',
  'calendar_end': '2026-09-25',
  'calendar_start': '2010-03-11',
  'feature_file_count': 4,
  'fields': ['$open', '$close'],
  'freq': 'day',
  'hash': '9a7fb81a25bbf255',
  'instruments': ['SOXL', 'SOXX'],
  'market': 'all',
  'max_datetime': '2026-09-25',
  'operation': 'qlib_store_build',
  'provider_uri': '/Users/rziiiii/dev/workspace-worktrees/stable-excess-integration-20261002/data/qlib/stable_excess_integration_20261002',
  'region': 'us',
  'row_count': 8324,
  'source': 'Qlib frozen execution frame fe78c5dcadac986e757d8b5d30cbbf0dc3b667b1d32e1377ee313a6ae66ba12a',
  'source_api': ['qlib.init',
   'qlib.data.storage.file_storage.FileFeatureStorage',
   'qlib.data.D.calendar',
   'qlib.data.D.instruments',
   'qlib.data.D.features'],
  'status': 'ok'},
 'region': 'us',
 'market': 'all',
 'data_audit': {'as_of': '2026-09-25',
  'train_start': '2011-01-03',
  'source_api': ['qlib.data.D.features',
   'qlib.data.D.calendar',
   'qlib.data.dataset.DatasetH',
   'qlib.data.dataset.handler.DataHandlerLP',
   'qlib.data.dataset.loader.StaticDataLoader'],
  'primary': {'provider_uri': '/Users/rziiiii/dev/workspace-worktrees/stable-excess-integration-20261002/data/qlib/soxl',
   'manifest_sha256': '26aa3b85a2ed8cddad7b47b6c6e30997448c0f92a360b47a0020e2e953d5ae0d',
   'provider_as_of': '2026-09-25',
   'calendar_start': '2010-03-11',
   'calendar_end': '2026-09-25',
   'fields': ['$open', '$high', '$low', '$close', '$volume'],
   'instruments': ['SOXL', 'SOXX'],
   'readback_sha256': '160c19426a3df368e875b47a1bd784815e0fed18182d6cfed3166e330e892ac8',
   'source_api': ['qlib.data.D.features', 'qlib.data.D.calendar']},
  'execution': {'provider_uri': '/Users/rziiiii/dev/workspace-worktrees/stable-excess-integration-20261002/data/qlib/soxl_soxx_soxs',
   'manifest_sha256': '9dec4b4dea3d7ff918d46645b9d8716238a0b007399969969fcd039d045c228d',
   'provider_as_of': '2026-09-25',
   'calendar_start': '2010-03-11',
   'calendar_end': '2026-09-25',
   'fields': ['$open', '$close'],
   'instruments': ['SOXL', 'SOXX'],
   'readback_sha256': '0e293b872a308c5577c64540ff13ccb482649d9aa94c5f4f7afacaf73ec52b11',
   'source_api': ['qlib.data.D.features', 'qlib.data.D.calendar']},
  'auxiliary': {'provider_uri': '/Users/rziiiii/dev/workspace-worktrees/stable-excess-integration-20261002/data/qlib/soxx_pit_leveraged_training_v1',
   'manifest_sha256': '65267558677904f78d2e44056361c5af3e795fe405483483a02a7b23099c560d',
   'provider_as_of': '2026-07-02',
   'calendar_start': '2007-02-01',
   'calendar_end': '2026-07-02',
   'fields': ['$open',
    '$high',
    '$low',
    '$close',
    '$adj_close',
    '$volume',
    '$pit_weight_pct',
    '$pit_available',
    '$pit_member',
    '$instrument_type',
    '$leverage_multiple',
    '$is_actual_2x'],
   'instruments': ['ACLS',
    'ADI',
    'ALAB',
    'AMAT',
    'AMD',
    'AMDL',
    'ARM',
    'ASML',
    'ASX',
    'AVGO',
    'CRDO',
    'CRUS',
    'ENTG',
    'INTC',
    'INTW',
    'KLAC',
    'LRCX',
    'LSCC',
    'MCHP',
    'MKSI',
    'MPWR',
    'MRVL',
    'MTSI',
    'MU',
    'MULL',
    'MVLL',
    'NVDA',
    'NVDL',
    'NVMI',
    'NXPI',
    'OLED',
    'ON',
    'ONTO',
    'QCOM',
    'QRVO',
    'RMBS',
    'SLAB',
    'SMTC',
    'STM',
    'SWKS',
    'SYNA',
    'TER',
    'TSM',
    'TXN',
    'UMC',
    'USD'],
   'readback_sha256': '1ef63a2901c773594e04b48e8a4112143ddf0714bbff1157cba830c3762ffd00',
   'source_api': ['qlib.data.D.features', 'qlib.data.D.calendar']},
  'primary_frame_sha256': 'e29390b697b176f2dd6a9731cdcef34c019e000ecbf6f3c4aa494764bfd93246',
  'execution_prices_sha256': 'fe78c5dcadac986e757d8b5d30cbbf0dc3b667b1d32e1377ee313a6ae66ba12a',
  'auxiliary_frame_sha256': '59d72504ee28130cf9b16fdbc5f3dcb7c2e4021aca9d8fbecb8ba238053d6e2f',
  'primary_rows': 3956,
  'auxiliary_rows': 46688,
  'primary_feature_end': '2026-09-25',
  'primary_return_label_end': '2026-09-23',
  'primary_forecast_label_end': '2026-09-17',
  'auxiliary_first_signal': '2019-11-26',
  'auxiliary_last_signal': '2026-07-02',
  'common_feature_indices': [0,
   1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15],
  'feature_columns': ['soxx_ret1',
   'soxx_mom5',
   'soxx_mom20',
   'soxx_mom60',
   'soxx_reversal1',
   'soxx_vol10',
   'soxx_vol20',
   'soxx_downside_vol20',
   'soxx_skew20',
   'soxx_kurt60',
   'soxx_drawdown20',
   'soxx_drawdown60',
   'soxx_gap1',
   'soxx_intraday1',
   'soxx_volume_z20',
   'soxx_range_pct',
   'soxl_gap1',
   'soxl_intraday1',
   'soxl_volume_z20',
   'soxl_range_pct',
   'relative_log_return_1d',
   'relative_log_return_5d',
   'relative_log_return_20d',
   'relative_volatility_20',
   'soxx_efficiency_20',
   'cash_advantage_prediction',
   'future_vol_prediction',
   'forecast_available'],
  'auxiliary_features': ['ret1',
   'mom5',
   'mom20',
   'mom60',
   'reversal1',
   'vol10',
   'vol20',
   'downside_vol20',
   'skew20',
   'kurt60',
   'drawdown20',
   'drawdown60',
   'gap1',
   'intraday1',
   'volume_z20',
   'range_pct'],
  'auxiliary_targets': ['underlying_return_5d', 'underlying_vol_5d'],
  'pit_membership': "previous Qlib session's filing-date-derived published membership; no same-day filing-time assumption",
  'pre_pit_union_backfill_used': False,
  'actual_2x_rows_used': False,
  'auxiliary_target_basis': 'five future adjusted close returns; continuous return and sample standard deviation',
  'forecast_target_basis': 'cash advantage is negative next-open log return; vol is sample std of five next-open returns',
  'unavailable_forecast_features': 'explicit neutral zero plus forecast_available=0; not invented predictions',
  'label_timing': 'signal close < next-open decision < label observation; incomplete tail labels remain missing',
  'qlib_docs_reference': 'https://qlib.readthedocs.io/en/latest/component/data.html'},
 'recorder_id': 'b94059c2e0754b0ab102e4f62534eefb',
 'recorder_uri': '/Users/rziiiii/dev/workspace/research/stable_excess_integration_20261002/qlib_recorder',
 'recorder_local_dir': '/Users/rziiiii/dev/workspace/research/stable_excess_integration_20261002/qlib_recorder/861915197973611996/b94059c2e0754b0ab102e4f62534eefb',
 'recorder_relative_dir': 'qlib_recorder/861915197973611996/b94059c2e0754b0ab102e4f62534eefb',
 'source_sha256': {'src/model/integrated_allocation.py': '946f20b41afa528fef19562f696ccda81343a78dbade018d3371e18698d23f30',
  'src/data/integrated_allocation.py': '73f2495f6a9860860a76a5a8c2f679c42f5a76f089c10fb7d347ce66acc36e9c',
  'src/analysis/integrated_allocation.py': '534072ad69fb7c8f903afc6339f581d66d25e047102d05452b55490647985b56',
  'src/workflow/stable_excess_integration.py': '7753c5bc16dddda5758d6fe5609fa7be915c6484f05e1881989a67afdf17771c'},
 'seeds': [17, 41, 71],
 'model_selection_uses_outer_test': False,
 'research_adaptive_history': True,
 'development_period': {'first_signal': '2016-01-04',
  'last_signal': '2022-12-30',
  'last_exit': '2023-01-04',
  'annual_basis': 'signal_year'},
 'diagnostic_frozen_system': 'allocator and any cash/volatility forecast heads both fixed at their2023fit with pre2023mature training labels',
 'historical_qualification_pass': False,
 'new_forward_qualified': False,
 'production_change': False,
 'native_qlib_audit': {'10': {'status': 'passed',
   'sessions': 1762,
   'start': '2016-01-05',
   'end': '2023-01-03',
   'provider_uri': '/Users/rziiiii/dev/workspace-worktrees/stable-excess-integration-20261002/data/qlib/stable_excess_integration_20261002',
   'cost_bps': 10.0,
   'initial_cash': 100000.0,
   'maximum_session_return_error': 5.899210564486168e-08,
   'tolerance': 1e-07,
   'native_api': 'qlib.backtest.backtest + SimulatorExecutor + Exchange + Position',
   'schedule_strategy': 'DirectTargetWeightStrategy subclass with observed-open sizing and fee-affordable targets',
   'report_mark': 'native daily same-day close; next-open reconciliation uses native positions and Qlib D.features',
   'scope': 'complete prescribed daily target/HOLD schedule; actual Qlib Exchange, Position, report and next-open accounting',
   'execution_limitation': 'Observed historical opens and continuous adjusted shares; no claim of spread/impact/partial-fill evidence.',
   'policy_scope': 'continuous_three_asset_targets_without_legacy_allocation_caps',
   'legacy_controller_executed': False,
   'risk_annualization_sessions': 252,
   'native_close_anchored_max_drawdown_pct': -81.19948347412331,
   'native_open_to_open_anchored_max_drawdown_pct': -83.15638848087619,
   'risk_table_mark_convention': 'risk_analysis uses native close marks; risk_analysis_open_to_open uses native positions marked at the following open'},
  '25': {'status': 'passed',
   'sessions': 1762,
   'start': '2016-01-05',
   'end': '2023-01-03',
   'provider_uri': '/Users/rziiiii/dev/workspace-worktrees/stable-excess-integration-20261002/data/qlib/stable_excess_integration_20261002',
   'cost_bps': 25.0,
   'initial_cash': 100000.0,
   'maximum_session_return_error': 5.899045274482262e-08,
   'tolerance': 1e-07,
   'native_api': 'qlib.backtest.backtest + SimulatorExecutor + Exchange + Position',
   'schedule_strategy': 'DirectTargetWeightStrategy subclass with observed-open sizing and fee-affordable targets',
   'report_mark': 'native daily same-day close; next-open reconciliation uses native positions and Qlib D.features',
   'scope': 'complete prescribed daily target/HOLD schedule; actual Qlib Exchange, Position, report and next-open accounting',
   'execution_limitation': 'Observed historical opens and continuous adjusted shares; no claim of spread/impact/partial-fill evidence.',
   'policy_scope': 'continuous_three_asset_targets_without_legacy_allocation_caps',
   'legacy_controller_executed': False,
   'risk_annualization_sessions': 252,
   'native_close_anchored_max_drawdown_pct': -82.58006033664857,
   'native_open_to_open_anchored_max_drawdown_pct': -84.3932640907914,
   'risk_table_mark_convention': 'risk_analysis uses native close marks; risk_analysis_open_to_open uses native positions marked at the following open'}},
 'artifact_policy': {'policy': 'slim_card_recorder_first',
  'workflow_config': 'workflow.yaml',
  'recorder_only_artifacts': ['inputs/*.pkl',
   'models/*.pkl',
   'analysis/portfolio_replays.pkl',
   'portfolio_analysis/native_reconciliation.pkl']},
 'limitations': ['All2016-2026 history has participated in earlier research; repeated historical qualification is not new forward evidence.',
  'Block bootstrap does not include all previous model/feature search uncertainty; family adjustment covers only this registered family.',
  'Training uses initially-cash chronological84-session blocks with21warmup; evaluation uses continuous own holdings.',
  'PIT auxiliary starts2019; earlier folds intentionally receive no auxiliary data.',
  'Historical open execution is not verified09:31 fills; no real orders or existingSIM replacement.',
  'Cash returns assumed zero; no promise of future stable excess.'],
 'qlib_docs_reference': ['https://qlib.readthedocs.io/en/latest/component/data.html',
  'https://qlib.readthedocs.io/en/latest/component/workflow.html',
  'https://qlib.readthedocs.io/en/latest/component/strategy.html']}

In [3]:
import pandas as pd
card=root/"research/stable_excess_integration_20261002"
display(pd.read_csv(card/"model_selection.csv"))
display(pd.read_csv(card/"annual_metrics.csv"))
display(pd.read_csv(card/"backtest_benchmark_comparison.csv"))

,variant,historical_qualification_pass,passed_gates,worst_annualized_lower_bound,worst_relative_wealth,positive_years_10bps
0,cash_vol_forecasts,False,9,-0.265192,1.718651,5
1,base,False,8,-0.243632,1.384646,5
2,pit_auxiliary,False,8,-0.267850,1.264801,5

,year,year_basis,sessions,start_signal,last_exit,terminal_wealth,return_pct,cagr_pct,annualized_log_volatility_pct,max_drawdown_pct,...,annualized_relative_return_pct,relative_max_drawdown_pct,up_day_conditional_relative_return_pct,down_day_conditional_relative_return_pct,conditional_returns_are_noncontiguous_statistics,risk_policy,annualization_sessions,cost_bps,variant,segment
0,2016,signal_year_fold_attribution,252,2016-01-04,2017-01-04,2.090147,109.014739,109.014739,32.880863,-13.226900,...,49.028976,-14.381941,32.061806,12.847901,True,reported against benchmark; no implicit fixed ...,252,10.0,base,development
1,2017,signal_year_fold_attribution,251,2017-01-03,2018-01-03,1.473355,47.335452,47.563112,38.815974,-27.934972,...,2.576429,-23.225895,84.855055,-44.515407,True,reported against benchmark; no implicit fixed ...,252,10.0,base,development
2,2018,signal_year_fold_attribution,251,2018-01-02,2019-01-03,0.726974,-27.302639,-27.394933,65.921369,-48.237244,...,-18.431267,-32.328206,417.909770,-84.237659,True,reported against benchmark; no implicit fixed ...,252,10.0,base,development
3,2019,signal_year_fold_attribution,252,2019-01-02,2020-01-03,2.903551,190.355050,190.355050,45.897207,-23.121463,...,74.956206,-10.246421,227.575683,-46.590600,True,reported against benchmark; no implicit fixed ...,252,10.0,base,development
4,2020,signal_year_fold_attribution,253,2020-01-02,2021-01-05,2.222633,122.263337,121.562783,83.679116,-64.620119,...,46.766851,-46.020835,998.522774,-86.619260,True,reported against benchmark; no implicit fixed ...,252,10.0,base,development
5,2021,signal_year_fold_attribution,252,2021-01-04,2022-01-04,1.748808,74.880788,74.880788,56.608646,-25.692368,...,17.886378,-23.851686,259.905953,-67.245227,True,reported against benchmark; no implicit fixed ...,252,10.0,base,development
6,2022,signal_year_fold_attribution,251,2022-01-03,2023-01-04,0.431191,-56.880919,-57.025187,91.905377,-73.163971,...,-32.673358,-52.881822,635.016780,-90.825730,True,reported against benchmark; no implicit fixed ...,252,10.0,base,development
7,2016,signal_year_fold_attribution,252,2016-01-04,2017-01-04,1.942406,94.240602,94.240602,32.909498,-14.206227,...,38.702448,-16.234353,27.569457,8.727004,True,reported against benchmark; no implicit fixed ...,252,25.0,base,development
8,2017,signal_year_fold_attribution,251,2017-01-03,2018-01-03,1.389499,38.949883,39.132100,38.817778,-27.993995,...,-3.284271,-25.312975,78.380251,-45.773960,True,reported against benchmark; no implicit fixed ...,252,25.0,base,development
9,2018,signal_year_fold_attribution,251,2018-01-02,2019-01-03,0.672279,-32.772086,-32.878356,65.925548,-51.324724,...,-24.591662,-36.329268,398.633311,-84.860047,True,reported against benchmark; no implicit fixed ...,252,25.0,base,development
10,2019,signal_year_fold_attribution,252,2019-01-02,2020-01-03,2.635025,163.502520,163.502520,45.894078,-23.770905,...,58.775957,-10.895285,209.133409,-48.638370,True,reported against benchmark; no implicit fixed ...,252,25.0,base,development
11,2020,signal_year_fold_attribution,253,2020-01-02,2021-01-05,2.055696,105.569607,104.984920,83.748712,-65.005216,...,35.785401,-47.108103,953.862805,-87.099807,True,reported against benchmark; no implicit fixed ...,252,25.0,base,development
12,2021,signal_year_fold_attribution,252,2021-01-04,2022-01-04,1.560820,56.082002,56.082002,56.594801,-27.995828,...,5.214199,-26.279957,237.720273,-68.845756,True,reported against benchmark; no implicit fixed ...,252,25.0,base,development
13,2022,signal_year_fold_attribution,251,2022-01-03,2023-01-04,0.384907,-61.509320,-61.655453,91.883592,-75.398880,...,-39.927380,-56.649043,597.295341,-91.367470,True,reported against benchmark; no implicit fixed ...,252,25.0,base,development
14,2016,signal_year_fold_attribution,252,2016-01-04,2017-01-04,2.090147,109.014739,109.014739,32.880863,-13.226900,...,49.028976,-14.381941,32.061806,12.847901,True,reported against benchmark; no implicit fixed ...,252,10.0,pit_auxiliary,development
15,2017,signal_year_fold_attribution,251,2017-01-03,2018-01-03,1.473355,47.335452,47.563112,38.815974,-27.934972,...,2.576429,-23.225895,84.855055,-44.515407,True,reported against benchmark; no implicit fixed ...,252,10.0,pit_auxiliary,development
16,2018,signal_year_fold_attribution,251,2018-01-02,2019-01-03,0.726974,-27.302639,-27.394933,65.921369,-48.237244,...,-18.431267,-32.328206,417.909770,-84.237659,True,reported against benchmark; no implicit fixed ...,252,10.0,pit_auxiliary,development
17,2019,signal_year_fold_attribution,252,2019-01-02,2020-01-03,2.903551,190.355050,190.355050,45.897207,-23.121463,...,74.956206,-10.246421,227.575683,-46.590600,True,reported against benchmark; no implicit fixed ...,252,10.0,pit_auxiliary,development
18,2020,signal_year_fold_attribution,253,2020-01-02,2021-01-05,2.034238,103.423758,102.853588,84.426579,-67.317802,...,34.373571,-49.696849,1026.553973,-88.058166,True,reported against benchmark; no implicit fixed ...,252,10.0,pit_auxiliary,development
19,2021,signal_year_fold_attribution,252,2021-01-04,2022-01-04,1.665587,66.558658,66.558658,55.103021,-26.547302,...,12.276467,-24.720494,224.392600,-65.388709,True,reported against benchmark; no implicit fixed ...,252,10.0,pit_auxiliary,development
20,2022,signal_year_fold_attribution,251,2022-01-03,2023-01-04,0.448654,-55.134625,-55.277662,89.242988,-72.037163,...,-29.935592,-51.440449,534.433766,-88.940786,True,reported against benchmark; no implicit fixed ...,252,10.0,pit_auxiliary,development
21,2016,signal_year_fold_attribution,252,2016-01-04,2017-01-04,1.942406,94.240602,94.240602,32.909498,-14.206227,...,38.702448,-16.234353,27.569457,8.727004,True,reported against benchmark; no implicit fixed ...,252,25.0,pit_auxiliary,development
22,2017,signal_year_fold_attribution,251,2017-01-03,2018-01-03,1.389499,38.949883,39.132100,38.817778,-27.993995,...,-3.284271,-25.312975,78.380251,-45.773960,True,reported against benchmark; no implicit fixed ...,252,25.0,pit_auxiliary,development
23,2018,signal_year_fold_attribution,251,2018-01-02,2019-01-03,0.672279,-32.772086,-32.878356,65.925548,-51.324724,...,-24.591662,-36.329268,398.633311,-84.860047,True,reported against benchmark; no implicit fixed ...,252,25.0,pit_auxiliary,development
24,2019,signal_year_fold_attribution,252,2019-01-02,2020-01-03,2.635025,163.502520,163.502520,45.894078,-23.770905,...,58.775957,-10.895285,209.133409,-48.638370,True,reported against benchmark; no implicit fixed ...,252,25.0,pit_auxiliary,development
25,2020,signal_year_fold_attribution,253,2020-01-02,2021-01-05,1.890124,89.012426,88.537398,84.487178,-67.619785,...,24.890291,-50.559599,982.481908,-88.452417,True,reported against benchmark; no implicit fixed ...,252,25.0,pit_auxiliary,development
26,2021,signal_year_fold_attribution,252,2021-01-04,2022-01-04,1.486168,48.616776,48.616776,55.079585,-28.803097,...,0.181922,-27.341983,204.069324,-67.052934,True,reported against benchmark; no implicit fixed ...,252,25.0,pit_auxiliary,development
27,2022,signal_year_fold_attribution,251,2022-01-03,2023-01-04,0.401599,-59.840097,-59.985800,89.224181,-74.297824,...,-37.311613,-55.224855,502.543449,-89.576741,True,reported against benchmark; no implicit fixed ...,252,25.0,pit_auxiliary,development
28,2016,signal_year_fold_attribution,252,2016-01-04,2017-01-04,2.361254,136.125400,136.125400,45.359149,-25.364739,...,68.359068,-16.029108,249.208379,-51.788365,True,reported against benchmark; no implicit fixed ...,252,10.0,cash_vol_forecasts,development
29,2017,signal_year_fold_attribution,251,2017-01-03,2018-01-03,1.793218,79.321783,79.739504,38.900033,-20.863696,...,24.943397,-15.626766,150.751112,-50.216359,True,reported against benchmark; no implicit fixed ...,252,10.0,cash_vol_forecasts,development
30,2018,signal_year_fold_attribution,251,2018-01-02,2019-01-03,0.657629,-34.237137,-34.346855,76.405121,-55.971789,...,-26.241458,-42.076635,964.260540,-93.061127,True,reported against benchmark; no implicit fixed ...,252,10.0,cash_vol_forecasts,development
31,2019,signal_year_fold_attribution,252,2019-01-02,2020-01-03,3.576977,257.697657,257.697657,52.000324,-23.535252,...,115.534136,-10.078793,491.552667,-63.564675,True,reported against benchmark; no implicit fixed ...,252,10.0,cash_vol_forecasts,development
32,2020,signal_year_fold_attribution,253,2020-01-02,2021-01-05,2.180201,118.020147,117.349525,90.027541,-69.162566,...,43.975920,-52.426424,1702.287496,-91.999927,True,reported against benchmark; no implicit fixed ...,252,10.0,cash_vol_forecasts,development
33,2021,signal_year_fold_attribution,252,2021-01-04,2022-01-04,1.931494,93.149380,93.149380,63.129473,-29.697784,...,30.201156,-19.392385,518.838546,-78.960400,True,reported against benchmark; no implicit fixed ...,252,10.0,cash_vol_forecasts,development
34,2022,signal_year_fold_attribution,251,2022-01-03,2023-01-04,0.298574,-70.142646,-70.286084,104.314279,-83.156395,...,-53.448589,-68.136262,1874.654088,-97.635390,True,reported against benchmark; no implicit fixed ...,252,10.0,cash_vol_forecasts,development
35,2016,signal_year_fold_attribution,252,2016-01-04,2017-01-04,2.189593,118.959269,118.959269,45.437631,-26.053174,...,56.353441,-16.641484,237.525233,-53.676518,True,reported against benchmark; no implicit fixed ...,252,25.0,cash_vol_forecasts,development
36,2017,signal_year_fold_attribution,251,2017-01-03,2018-01-03,1.710443,71.044272,71.410434,38.905634,-21.081747,...,19.153561,-16.229198,143.419841,-51.084214,True,reported against benchmark; no implicit fixed ...,252,25.0,cash_vol_forecasts,development
37,2018,signal_year_fold_attribution,251,2018-01-02,2019-01-03,0.620799,-37.920130,-38.037933,76.407805,-57.938139,...,-30.388229,-44.633684,934.071545,-93.258503,True,reported against benchmark; no implicit fixed ...,252,25.0,cash_vol_forecasts,development
38,2019,signal_year_fold_attribution,252,2019-01-02,2020-01-03,3.247479,224.747922,224.747922,52.005091,-24.263920,...,95.679959,-10.377943,458.051341,-64.935133,True,reported against benchmark; no implicit fixed ...,252,25.0,cash_vol_forecasts,development
39,2020,signal_year_fold_attribution,253,2020-01-02,2021-01-05,2.044908,104.490830,103.913453,90.120746,-69.512167,...,35.075643,-52.965761,1646.398676,-92.256241,True,reported against benchmark; no implicit fixed ...,252,25.0,cash_vol_forecasts,development
40,2021,signal_year_fold_attribution,252,2021-01-04,2022-01-04,1.755278,75.527768,75.527768,63.116704,-30.517683,...,18.322505,-20.902743,486.626488,-79.830010,True,reported against benchmark; no implicit fixed ...,252,25.0,cash_vol_forecasts,development
41,2022,signal_year_fold_attribution,251,2022-01-03,2023-01-04,0.270433,-72.956678,-73.097209,104.310920,-84.393270,...,-57.852648,-70.476109,1785.741022,-97.757269,True,reported against benchmark; no implicit fixed ...,252,25.0,cash_vol_forecasts,development
42,2023,signal_year_fold_attribution,250,2023-01-03,2024-01-03,1.459210,45.920959,46.362769,42.875559,-39.444067,...,-6.910725,-27.328486,51.584848,-38.554415,True,reported against benchmark; no implicit fixed ...,252,10.0,cash_vol_forecasts_annual_refit,reused_diagnostic
43,2024,signal_year_fold_attribution,252,2024-01-02,2025-01-03,0.990674,-0.932629,-0.932629,57.941235,-46.358595,...,-17.976801,-28.870164,174.127848,-70.078487,True,reported against benchmark; no implicit fixed ...,252,10.0,cash_vol_forecasts_annual_refit,reused_diagnostic
44,2025,signal_year_fold_attribution,250,2025-01-02,2026-01-05,2.414492,141.449166,143.157862,87.375282,-67.401675,...,63.805566,-50.319060,1134.578149,-86.783726,True,reported against benchmark; no implicit fixed ...,252,10.0,cash_vol_forecasts_annual_refit,reused_diagnostic
45,2026,signal_year_fold_attribution,182,2026-01-02,2026-09-25,1.914714,91.471414,145.813347,70.992747,-31.629487,...,10.829404,-21.975112,65.887775,-35.071339,True,reported against benchmark; no implicit fixed ...,252,10.0,cash_vol_forecasts_annual_refit,reused_diagnostic
46,2023,signal_year_fold_attribution,250,2023-01-03,2024-01-03,1.459210,45.920959,46.362769,42.875559,-39.444067,...,-6.910725,-27.328486,51.584848,-38.554415,True,reported against benchmark; no implicit fixed ...,252,10.0,cash_vol_forecasts_frozen2022,reused_diagnostic
47,2024,signal_year_fold_attribution,252,2024-01-02,2025-01-03,0.856541,-14.345935,-14.345935,54.233606,-49.049548,...,-29.082398,-38.501508,89.703121,-62.616534,True,reported against benchmark; no implicit fixed ...,252,10.0,cash_vol_forecasts_frozen2022,reused_diagnostic
48,2025,signal_year_fold_attribution,250,2025-01-02,2026-01-05,2.391493,139.149309,140.823289,90.325749,-70.143353,...,62.232859,-54.497469,1247.112527,-88.003151,True,reported against benchmark; no implicit fixed ...,252,10.0,cash_vol_forecasts_frozen2022,reused_diagnostic
49,2026,signal_year_fold_attribution,182,2026-01-02,2026-09-25,1.722171,72.217079,112.263228,63.341455,-27.322247,...,-4.297276,-31.322617,4.515346,-7.307831,True,reported against benchmark; no implicit fixed ...,252,10.0,cash_vol_forecasts_frozen2022,reused_diagnostic
50,2023,signal_year_fold_attribution,250,2023-01-03,2024-01-03,1.352036,35.203560,35.530186,42.855050,-40.630521,...,-13.670233,-28.672567,45.644885,-40.656659,True,reported against benchmark; no implicit fixed ...,252,25.0,cash_vol_forecasts_annual_refit,reused_diagnostic
51,2024,signal_year_fold_attribution,252,2024-01-02,2025-01-03,0.917044,-8.295623,-8.295623,57.993210,-46.679956,...,-24.073019,-31.446253,161.656304,-70.853221,True,reported against benchmark; no implicit fixed ...,252,25.0,cash_vol_forecasts_annual_refit,reused_diagnostic
52,2025,signal_year_fold_attribution,250,2025-01-02,2026-01-05,2.272937,127.293732,128.791644,87.359056,-67.597197,...,54.127629,-50.617043,1091.980295,-87.113935,True,reported against benchmark; no implicit fixed ...,252,25.0,cash_vol_forecasts_annual_refit,reused_diagnostic
53,2026,signal_year_fold_attribution,182,2026-01-02,2026-09-25,1.811501,81.150056,127.658588,70.956706,-32.191455,...,2.644001,-23.187183,60.446255,-36.488002,True,reported against benchmark; no implicit fixed ...,252,25.0,cash_vol_forecasts_annual_refit,reused_diagnostic
54,2023,signal_year_fold_attribution,250,2023-01-03,2024-01-03,1.352036,35.203560,35.530186,42.855050,-40.630521,...,-13.670233,-28.672567,45.644885,-40.656659,True,reported against benchmark; no implicit fixed ...,252,25.0,cash_vol_forecasts_frozen2022,reused_diagnostic
55,2024,signal_year_fold_attribution,252,2024-01-02,2025-01-03,0.796094,-20.390599,-20.390599,54.234170,-49.650729,...,-34.087100,-41.335051,81.251039,-63.461756,True,reported against benchmark; no implicit fixed ...,252,25.0,cash_vol_forecasts_frozen2022,reused_diagnostic
56,2025,signal_year_fold_attribution,250,2025-01-02,2026-01-05,2.240894,124.089361,125.540536,90.324643,-70.304756,...,51.937489,-54.743453,1199.339824,-88.345318,True,reported against benchmark; no implicit fixed ...,252,25.0,cash_vol_forecasts_frozen2022,reused_diagnostic
57,2026,signal_year_fold_attribution,182,2026-01-02,2026-09-25,1.635568,63.556772,97.628118,63.305088,-27.762893,...,-10.895780,-32.625623,1.200852,-9.085899,True,reported against benchmark; no implicit fixed ...,252,25.0,cash_vol_forecasts_frozen2022,reused_diagnostic

,cost_bps,sessions,start_signal,last_exit,terminal_wealth,return_pct,cagr_pct,annualized_log_volatility_pct,max_drawdown_pct,qlib_max_drawdown_without_initial_mark_pct,...,annualized_log_excess,annualized_relative_return_pct,relative_max_drawdown_pct,up_day_conditional_relative_return_pct,down_day_conditional_relative_return_pct,conditional_returns_are_noncontiguous_statistics,risk_policy,annualization_sessions,variant,segment
0,10.0,1762,2016-01-04,2023-01-04,10.894609,989.460859,40.715286,62.919160,-73.163971,-73.163971,...,0.133932,14.331520,-52.881822,1.203465e+06,-99.978805,True,reported against benchmark; no implicit fixed ...,252,base,development
1,25.0,1762,2016-01-04,2023-01-04,5.904728,490.472840,28.912927,62.931009,-75.398880,-75.398880,...,0.046545,4.764507,-56.649043,8.704199e+05,-99.984094,True,reported against benchmark; no implicit fixed ...,252,base,development
2,10.0,1762,2016-01-04,2023-01-04,9.881262,888.126153,38.764178,62.316191,-72.037163,-72.037163,...,0.119969,12.746240,-52.897438,9.601483e+05,-99.975906,True,reported against benchmark; no implicit fixed ...,252,pit_auxiliary,development
3,25.0,1762,2016-01-04,2023-01-04,5.393659,439.365857,27.254590,62.325918,-74.297824,-74.297824,...,0.033597,3.416816,-56.204775,6.955685e+05,-99.981819,True,reported against benchmark; no implicit fixed ...,252,pit_auxiliary,development
4,10.0,1762,2016-01-04,2023-01-04,12.523157,1152.315705,43.547046,70.854028,-83.156395,-83.156395,...,0.153856,16.632332,-68.136262,1.214118e+08,-99.999758,True,reported against benchmark; no implicit fixed ...,252,cash_vol_forecasts,development
5,25.0,1762,2016-01-04,2023-01-04,7.329068,632.906804,32.959283,70.878045,-84.393270,-84.393270,...,0.077451,8.052885,-70.476109,9.159539e+07,-99.999812,True,reported against benchmark; no implicit fixed ...,252,cash_vol_forecasts,development
6,10.0,934,2023-01-03,2026-09-25,6.683100,568.310012,66.949477,66.443759,-72.252795,-72.252795,...,0.079497,8.274200,-59.584912,8.410242e+03,-98.422317,True,reported against benchmark; no implicit fixed ...,252,cash_vol_forecasts_annual_refit,reused_diagnostic
7,10.0,934,2023-01-03,2026-09-25,5.147674,414.767360,55.595785,65.148163,-75.304195,-75.304195,...,0.009067,0.910823,-67.199407,3.948687e+03,-97.445650,True,reported against benchmark; no implicit fixed ...,252,cash_vol_forecasts_frozen2022,reused_diagnostic
8,25.0,934,2023-01-03,2026-09-25,5.105098,410.509849,55.247519,66.440277,-73.653347,-73.653347,...,0.007230,0.725642,-64.214995,7.188281e+03,-98.584406,True,reported against benchmark; no implicit fixed ...,252,cash_vol_forecasts_annual_refit,reused_diagnostic
9,25.0,934,2023-01-03,2026-09-25,3.944957,294.495681,44.815997,65.138071,-76.437390,-76.437390,...,-0.062327,-6.042400,-70.804360,3.371224e+03,-97.702522,True,reported against benchmark; no implicit fixed ...,252,cash_vol_forecasts_frozen2022,reused_diagnostic
10,10.0,1762,2016-01-04,2023-01-04,1.818319,81.831853,8.927570,15.816623,-32.745738,-32.745738,...,-0.122123,-11.496078,-68.209137,-9.988757e+01,37769.947759,True,reported against benchmark; no implicit fixed ...,252,SOXX_cash_initial_0.25,development
11,10.0,1762,2016-01-04,2023-01-04,2.636228,163.622811,14.870547,22.852519,-41.233961,-41.233961,...,-0.069001,-6.667395,-47.384308,-9.732677e+01,2209.060042,True,reported against benchmark; no implicit fixed ...,252,SOXX_cash_initial_0.5,development
12,10.0,1762,2016-01-04,2023-01-04,3.453729,245.372904,19.394854,27.300788,-45.133761,-45.133761,...,-0.030370,-2.991384,-24.731811,-7.856341e+01,277.242965,True,reported against benchmark; no implicit fixed ...,252,SOXX_cash_initial_0.75,development
13,10.0,1762,2016-01-04,2023-01-04,4.270822,327.082162,23.076546,30.550724,-47.374015,-47.374015,...,0.000000,0.000000,0.000000,0.000000e+00,0.000000,True,reported against benchmark; no implicit fixed ...,252,SOXX_cash_initial_1,development
14,10.0,934,2023-01-03,2026-09-25,1.995135,99.513509,20.485480,16.882899,-18.611340,-18.611340,...,-0.246665,-21.859779,-61.987964,-9.941700e+01,6775.233283,True,reported against benchmark; no implicit fixed ...,252,SOXX_cash_initial_0.25,reused_diagnostic
15,10.0,934,2023-01-03,2026-09-25,2.989773,198.977286,34.378766,25.940304,-29.859611,-29.859611,...,-0.137532,-12.849362,-41.360081,-9.435680e+01,964.378807,True,reported against benchmark; no implicit fixed ...,252,SOXX_cash_initial_0.5,reused_diagnostic
16,10.0,934,2023-01-03,2026-09-25,3.983914,298.391369,45.200458,32.344377,-37.392713,-37.392713,...,-0.060079,-5.831011,-20.697456,-7.142766e+01,180.122336,True,reported against benchmark; no implicit fixed ...,252,SOXX_cash_initial_0.75,reused_diagnostic
17,10.0,934,2023-01-03,2026-09-25,4.977558,397.755794,54.191374,37.338748,-42.790376,-42.790376,...,0.000000,0.000000,0.000000,0.000000e+00,0.000000,True,reported against benchmark; no implicit fixed ...,252,SOXX_cash_initial_1,reused_diagnostic
18,25.0,1762,2016-01-04,2023-01-04,1.817637,81.763709,8.921731,15.816927,-32.745738,-32.745738,...,-0.121963,-11.481868,-68.209137,-9.988757e+01,37812.482305,True,reported against benchmark; no implicit fixed ...,252,SOXX_cash_initial_0.25,development
19,25.0,1762,2016-01-04,2023-01-04,2.634253,163.425341,14.858237,22.853357,-41.233961,-41.233961,...,-0.068894,-6.657409,-47.384308,-9.732677e+01,2210.787947,True,reported against benchmark; no implicit fixed ...,252,SOXX_cash_initial_0.5,development
20,25.0,1762,2016-01-04,2023-01-04,3.449851,244.985086,19.375670,27.302364,-45.133761,-45.133761,...,-0.030317,-2.986197,-24.731811,-7.856341e+01,277.384026,True,reported against benchmark; no implicit fixed ...,252,SOXX_cash_initial_0.75,development
21,25.0,1762,2016-01-04,2023-01-04,4.264431,326.443137,23.050192,30.553228,-47.374015,-47.374015,...,0.000000,0.000000,0.000000,0.000000e+00,0.000000,True,reported against benchmark; no implicit fixed ...,252,SOXX_cash_initial_1,development
22,25.0,934,2023-01-03,2026-09-25,1.994387,99.438738,20.473296,16.883020,-18.611340,-18.611340,...,-0.246362,-21.836109,-61.987964,-9.941700e+01,6782.955367,True,reported against benchmark; no implicit fixed ...,252,SOXX_cash_initial_0.25,reused_diagnostic
23,25.0,934,2023-01-03,2026-09-25,2.987533,198.753333,34.351600,25.940595,-29.859611,-29.859611,...,-0.137330,-12.831771,-41.360081,-9.435680e+01,965.175298,True,reported against benchmark; no implicit fixed ...,252,SOXX_cash_initial_0.5,reused_diagnostic
24,25.0,934,2023-01-03,2026-09-25,3.979440,297.944018,45.156450,32.344876,-37.392713,-37.392713,...,-0.059978,-5.821512,-20.697456,-7.142766e+01,180.227081,True,reported against benchmark; no implicit fixed ...,252,SOXX_cash_initial_0.75,reused_diagnostic
25,25.0,934,2023-01-03,2026-09-25,4.970110,397.011023,54.129093,37.339488,-42.790376,-42.790376,...,0.000000,0.000000,0.000000,0.000000e+00,0.000000,True,reported against benchmark; no implicit fixed ...,252,SOXX_cash_initial_1,reused_diagnostic

In [4]:
from IPython.display import Markdown,display
display(Markdown((card/"conclusion.md").read_text()))

# 稳定净超额整合实验结论

完成3个同结构候选、每个3个种子的年度成熟标签训练；无旧止损计时器、现金下限、SOXL上限、EMA或HOLD开关。选中cash_vol_forecasts；历史稳定性门全部通过=False。

开发期2016–2022，各模型为同一真实持仓上平均三个种子目标的组合，以下为10bp：
- base：净收益989.46%，相对SOXX终值比2.5509，MaxDD-73.16%，CVaR5-9.54%。
- pit_auxiliary：净收益888.13%，相对SOXX终值比2.3137，MaxDD-72.04%，CVaR5-9.48%。
- cash_vol_forecasts：净收益1152.32%，相对SOXX终值比2.9323，MaxDD-83.16%，CVaR5-10.42%。

年度相对财富见annual_metrics.csv；20/60交易日相关块、三候选调整后的区间见bootstrap_analysis.csv；所有种子和失败门均保留。25bp重新计算各自费用、持仓与后续决策。

开发期按2016–2022信号年划分，末次收益结算到2023-01-04开盘；此后outer持有区间未参与本次排名。2023–2026信号仅作已查看历史的复用诊断，不能用于追加候选或选择种子。冻结2022对照同时冻结配置器和现金/波动预测头。原生Qlib回测按两档成本核对完整开发期目标与现金结算。

决定：not_promoted_no_stable_excess_evidence。本次没有更换原SIM或提交委托；没有把软件验证或历史拟合当成稳定前向超额。

下一步：若历史门通过，冻结模型收集全新同价独立前向证据；否则保留失败结果，依据失败来源评估是否有新的独立信息，而不继续未登记调参。
QLib recorder：b94059c2e0754b0ab102e4f62534eefb。

# 稳定净超额整合实验结论

完成3个同结构候选、每个3个种子的年度成熟标签训练；无旧止损计时器、现金下限、SOXL上限、EMA或HOLD开关。选中cash_vol_forecasts；历史稳定性门全部通过=False。

开发期2016–2022，各模型为同一真实持仓上平均三个种子目标的组合，以下为10bp：
- base：净收益989.46%，相对SOXX终值比2.5509，MaxDD-73.16%，CVaR5-9.54%。
- pit_auxiliary：净收益888.13%，相对SOXX终值比2.3137，MaxDD-72.04%，CVaR5-9.48%。
- cash_vol_forecasts：净收益1152.32%，相对SOXX终值比2.9323，MaxDD-83.16%，CVaR5-10.42%。

年度相对财富见annual_metrics.csv；20/60交易日相关块、三候选调整后的区间见bootstrap_analysis.csv；所有种子和失败门均保留。25bp重新计算各自费用、持仓与后续决策。

开发期按2016–2022信号年划分，末次收益结算到2023-01-04开盘；此后outer持有区间未参与本次排名。2023–2026信号仅作已查看历史的复用诊断，不能用于追加候选或选择种子。冻结2022对照同时冻结配置器和现金/波动预测头。原生Qlib回测按两档成本核对完整开发期目标与现金结算。

决定：not_promoted_no_stable_excess_evidence。本次没有更换原SIM或提交委托；没有把软件验证或历史拟合当成稳定前向超额。

下一步：若历史门通过，冻结模型收集全新同价独立前向证据；否则保留失败结果，依据失败来源评估是否有新的独立信息，而不继续未登记调参。
QLib recorder：b94059c2e0754b0ab102e4f62534eefb。

结果解释：开发期平均SOXL仓位约48.90%／48.43%／62.30%，名义风险敞口约1.59／1.58／1.97。最高收益的现金/波动预测版本年化对数波动70.85%，明显高于同窗SOXX的30.55%；2022信号年收益-70.14%，SOXX为-36.06%。高累计收益不能解释为稳定alpha。PIT辅助训练未改善主干净终值，所有相关块下界均未高于零。

复现与验证：原始及修正运行的全部开发期比较行逐项完全一致；冻结2022对照已同时冻结配置与预测头，原生风险表明确按252交易日年化。37项新路径测试通过；完整测试725通过、139失败，失败ID与保存的未修改main基线完全相同。原有策略和观察任务不变。