# 冻结配置、风险投影与动作层诊断

完整raw目标使用parent17已保存的冻结模型推理快照，原f696预测作为重叠对照。五层独立账户，两窗口两成本；Qlib原生账户对账后分析风险状态与HOLD/恢复交互。零拟合，诊断不晋升。

In [1]:
import sys, json, hashlib
from pathlib import Path

ROOT = Path.cwd()
while not (ROOT/'AGENTS.md').exists():
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))
CARD = ROOT/'research'/'stage1_uniform_layer_attribution_20261010'
print('plan sha256:', hashlib.sha256((CARD/'preregister_plan.json').read_bytes()).hexdigest())

plan sha256: c883792bfaa5526ff871f448e16356bf0037efb3aec40641411d2181ad953730

In [2]:
# Explicit Qlib DataAPI readback of the uniform price provider.
import qlib
from qlib.data import D
qlib.init(provider_uri=str((ROOT/'data/qlib/stage1_uniform_daily_marks_20261009').resolve()), region='us', kernels=1)
cal = D.calendar(freq='day')
print('uniform daily calendar:', cal[0], '->', cal[-1], '| n', len(cal))

[8839:MainThread](2026-10-10 14:03:20,040) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

2026/10/10 14:03:20 INFO mlflow.agent.hint: Load the `instrumenting-with-mlflow-tracing` skill at /Users/rziiiii/dev/workspace/qlib_venv/lib/python3.12/site-packages/mlflow/assistant/skills/instrumenting-with-mlflow-tracing/SKILL.md before writing any tracing code; it ships with this MLflow install. Set MLFLOW_DISABLE_AGENT_HINT=1 to silence this.

[8839:MainThread](2026-10-10 14:03:20,517) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:03:20,518) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

uniform daily calendar: 2016-01-04 00:00:00 -> 2026-09-25 00:00:00 | n 2698

In [3]:
from src.workflow import uniform_layer_attribution as workflow
summary = workflow.run_layer_attribution(root=ROOT, card_dir=CARD)
print('decision:', summary['decision'], '| models_trained:', summary['models_trained'])
print('full parity vs e4 active_hold:', summary['full_parity_vs_e4_active_hold'])
print('raw convention:', summary['raw_convention'], '| legacy convention:', summary['legacy_convention'])
print('recorder:', summary['recorder_id'])

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[8839:MainThread](2026-10-10 14:03:21,808) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:03:21,809) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:03:21,809) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:03:21,945) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:03:21,945) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:03:21,946) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:03:21,962) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:03:21,963) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:03:21,963) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:03:21,973) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:03:21,974) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:03:21,974) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_intraday_20261009')}

[8839:MainThread](2026-10-10 14:03:22,255) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:03:22,256) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:03:22,257) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:03:30,749) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:03:30,750) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:03:30,750) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:03:30,763) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:03:30,764) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:03:30,764) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:03:30,771) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:03:30,771) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:03:30,772) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:03:30,776) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:03:30,780) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:03:30,783) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:03:30,783) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:03:30,785) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x11f7b71a0>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:03:31,343) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:03:31,344) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:03:31,344) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:03:31,510) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:03:31,511) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:03:31,511) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:03:31,554) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:03:31,586) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:03:31,674) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:03:31,674) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:03:31,702) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x11f0a57c0>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:03:42,242) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:03:42,243) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:03:42,243) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:03:42,259) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:03:42,260) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:03:42,260) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:03:42,270) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:03:42,270) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:03:42,271) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:03:42,275) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:03:42,281) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:03:42,285) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:03:42,285) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:03:42,287) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x138bcffe0>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:03:42,847) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:03:42,848) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:03:42,848) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:03:42,922) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:03:42,923) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:03:42,923) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:03:42,965) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:03:42,996) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:03:43,085) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:03:43,085) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:03:43,113) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x11ef957c0>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:03:54,088) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:03:54,089) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:03:54,089) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:03:54,105) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:03:54,106) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:03:54,106) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:03:54,181) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:03:54,182) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:03:54,182) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:03:54,225) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:03:54,256) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:03:54,338) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:03:54,338) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:03:54,366) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x124bdcc80>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:04:04,816) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:04,817) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:04,817) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:04,833) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:04,834) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:04,834) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:04,908) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:04,909) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:04,909) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:05,421) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:04:05,450) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:04:05,534) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:04:05,534) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:04:05,565) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x1388790a0>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:04:15,843) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:15,844) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:15,844) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:15,861) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:15,862) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:15,862) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:15,872) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:15,872) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:15,873) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:15,877) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:04:15,882) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:04:15,886) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:04:15,886) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:04:15,888) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x13c6aacc0>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:04:16,360) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:16,361) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:16,361) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:16,438) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:16,439) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:16,440) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:16,483) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:04:16,516) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:04:16,604) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:04:16,605) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:04:16,633) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x1393d57c0>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:04:27,053) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:27,054) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:27,055) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:27,071) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:27,072) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:27,072) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:27,081) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:27,082) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:27,082) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:27,086) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:04:27,092) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:04:27,096) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:04:27,096) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:04:27,098) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x1373074d0>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:04:27,573) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:27,574) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:27,574) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:27,652) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:27,653) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:27,654) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:27,698) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:04:27,730) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:04:27,819) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:04:27,819) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:04:27,847) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x1396157c0>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:04:38,325) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:38,326) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:38,326) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:38,343) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:38,344) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:38,344) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:38,420) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:38,421) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:38,421) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:38,466) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:04:38,496) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:04:38,580) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:04:38,581) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:04:38,608) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x125d75190>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:04:48,678) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:48,679) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:48,679) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:48,695) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:48,696) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:48,696) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:48,774) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:48,775) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:48,775) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:48,821) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:04:48,851) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:04:48,937) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:04:48,937) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:04:49,653) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x12708f5c0>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:04:59,096) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:59,097) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:59,097) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:59,114) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:59,115) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:59,115) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:59,125) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:59,126) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:59,126) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:59,131) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:04:59,137) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:04:59,144) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:04:59,144) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:04:59,146) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x1268201d0>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:04:59,620) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:59,621) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:59,621) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:59,698) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:04:59,699) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:04:59,699) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:04:59,743) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:04:59,776) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:04:59,868) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:04:59,868) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:04:59,899) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x121f9c3e0>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:05:10,165) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:05:10,167) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:05:10,167) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:05:10,183) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:05:10,184) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:05:10,184) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:05:10,194) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:05:10,195) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:05:10,195) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:05:10,199) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:05:10,204) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:05:10,208) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:05:10,209) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:05:10,210) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x12953ad80>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:05:10,683) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:05:10,684) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:05:10,684) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:05:10,763) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:05:10,764) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:05:10,764) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:05:11,580) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:05:11,612) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:05:11,706) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:05:11,706) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:05:11,737) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x12381dcd0>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:05:21,854) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:05:21,855) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:05:21,856) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:05:21,873) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:05:21,873) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:05:21,874) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:05:21,953) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:05:21,954) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:05:21,954) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:05:22,001) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:05:22,032) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:05:22,116) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:05:22,116) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:05:22,145) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x126e48710>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:05:32,441) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:05:32,442) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:05:32,442) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:05:32,459) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:05:32,460) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:05:32,460) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:05:32,537) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:05:32,538) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:05:32,539) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:05:32,583) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:05:32,613) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:05:32,699) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:05:32,699) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:05:32,727) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x121382d80>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:05:42,594) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:05:42,595) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:05:42,595) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:05:42,612) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:05:42,613) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:05:42,613) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:05:42,623) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:05:42,623) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:05:42,624) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:05:42,628) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:05:42,633) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:05:42,638) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:05:42,638) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:05:42,640) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x1281c81d0>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:05:43,112) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:05:43,113) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:05:43,113) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:05:43,191) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:05:43,192) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:05:43,192) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:05:43,238) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:05:43,270) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:05:43,362) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:05:43,362) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:05:43,392) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x126725490>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:05:53,817) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:05:53,818) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:05:53,818) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:05:53,835) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:05:53,836) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:05:53,836) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:05:53,845) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:05:53,846) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:05:53,846) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:05:53,850) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:05:53,855) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:05:53,859) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:05:53,860) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:05:53,862) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x144221c10>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:05:54,338) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:05:54,338) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:05:54,339) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:05:54,416) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:05:54,417) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:05:54,418) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:05:54,462) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:05:54,495) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:05:54,589) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:05:54,590) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:05:54,618) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x127818080>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:06:05,424) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:06:05,425) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:06:05,426) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:06:05,442) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:06:05,443) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:06:05,443) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:06:05,520) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:06:05,521) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:06:05,521) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:06:05,566) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:06:05,595) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:06:05,680) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:06:05,681) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:06:05,708) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x12757ae70>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:06:16,240) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:06:16,241) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:06:16,241) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:06:16,258) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:06:16,259) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:06:16,259) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:06:16,337) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:06:16,338) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:06:16,338) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:06:16,384) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:06:16,414) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:06:16,499) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:06:16,500) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:06:16,528) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x14b6743e0>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:06:25,897) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:06:25,898) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:06:25,899) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:06:25,916) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:06:25,917) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:06:25,917) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:06:25,927) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:06:25,928) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:06:25,928) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:06:25,932) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:06:25,938) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:06:25,942) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:06:25,942) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:06:25,944) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x141d9e7e0>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:06:26,425) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:06:26,426) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:06:26,427) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:06:26,508) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:06:26,509) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:06:26,509) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:06:26,557) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:06:26,589) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:06:26,685) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:06:26,686) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:06:26,714) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x123247ce0>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:06:37,426) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:06:37,428) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:06:37,428) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:06:37,444) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:06:37,445) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:06:37,445) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:06:37,455) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:06:37,456) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:06:37,456) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:06:37,460) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:06:37,465) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:06:37,469) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:06:37,470) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:06:37,472) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x1241f8c50>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:06:37,950) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:06:37,951) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:06:37,951) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:06:38,032) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:06:38,033) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:06:38,033) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:06:38,080) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:06:38,114) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:06:38,206) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:06:38,206) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:06:38,234) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x14476d7c0>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:06:49,223) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:06:49,224) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:06:49,224) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:06:49,244) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:06:49,245) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:06:49,245) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:06:49,324) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:06:49,325) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:06:49,325) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:06:49,370) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:06:49,401) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:06:49,488) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:06:49,488) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:06:49,516) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x14286c3e0>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:06:59,557) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:06:59,558) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:06:59,558) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_daily_marks_20261009')}

[8839:MainThread](2026-10-10 14:06:59,575) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:06:59,576) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:06:59,576) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:06:59,657) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:06:59,658) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:06:59,658) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_uniform_execution_marks_20261009')}

[8839:MainThread](2026-10-10 14:06:59,706) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[8839:MainThread](2026-10-10 14:06:59,737) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[8839:MainThread](2026-10-10 14:06:59,820) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[8839:MainThread](2026-10-10 14:06:59,820) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[8839:MainThread](2026-10-10 14:06:59,848) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x155523410>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[8839:MainThread](2026-10-10 14:07:13,261) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[8839:MainThread](2026-10-10 14:07:13,262) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[8839:MainThread](2026-10-10 14:07:13,262) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[8839:MainThread](2026-10-10 14:07:13,265) INFO - qlib.workflow - [exp.py:258] - Experiment 978444292326671251 starts running ...

[8839:MainThread](2026-10-10 14:07:13,343) INFO - qlib.workflow - [recorder.py:345] - Recorder 6c6fac4f2d974545a4ca8ed8b149a17c starts running under Experiment 978444292326671251 ...

[8839:MainThread](2026-10-10 14:07:16,511) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

decision: layer_attribution_reported_diagnostic_only | models_trained: 0
full parity vs e4 active_hold: {'development_walk_forward::10': True, 'development_walk_forward::25': True, 'outer_reused_diagnostic::10': True, 'outer_reused_diagnostic::25': True}
raw convention: post_fee_desired | legacy convention: pre_fee_account
recorder: 6c6fac4f2d974545a4ca8ed8b149a17c

In [4]:
import pandas as pd
for name in ("layer_metrics", "soxx_benchmark", "fee_ledger", "risk_report", "annual_metrics", "risk_mechanism"):
    print(name)
    display(pd.read_csv(CARD / (name + ".csv")).round(4))

layer_metrics

,layer,segment,cost_bps,sessions,return_pct,max_drawdown_pct,cvar5_pct,worst_day_pct,worst_rolling_5d_pct,sharpe,total_turnover,avg_ending_cash_weight_pct
0,raw_allocator_only,development_walk_forward,10.0,1756,404.2586,-51.7050,-5.3264,-12.4900,-27.8650,0.8154,74.8258,36.8550
1,raw_allocator_only,development_walk_forward,25.0,1756,350.7194,-52.2826,-5.3321,-12.4900,-27.8862,0.7716,74.8194,36.8550
2,raw_allocator_only,outer_reused_diagnostic,10.0,934,305.6385,-45.6060,-6.1680,-11.1942,-20.1285,1.1004,33.3574,40.4209
3,raw_allocator_only,outer_reused_diagnostic,25.0,934,285.8404,-46.3546,-6.1718,-11.1986,-20.1532,1.0687,33.3551,40.4209
4,open_risk_projection_nohold_no_recovery,development_walk_forward,10.0,1756,171.6717,-29.9306,-3.5083,-7.1138,-10.8237,0.7683,102.7964,53.4170
5,open_risk_projection_nohold_no_recovery,development_walk_forward,25.0,1756,99.1370,-30.2146,-3.5812,-7.1160,-11.8891,0.5600,107.9545,53.5385
6,open_risk_projection_nohold_no_recovery,outer_reused_diagnostic,10.0,934,220.4298,-26.9218,-4.8117,-8.7040,-14.5534,1.1337,59.5363,48.1781
7,open_risk_projection_nohold_no_recovery,outer_reused_diagnostic,25.0,934,66.1206,-36.4415,-4.4034,-11.1995,-14.6356,0.6391,46.9275,59.2094
8,open_risk_projection_withhold_no_recovery,development_walk_forward,10.0,1756,115.4607,-30.0833,-3.4585,-7.1138,-10.8237,0.6282,100.2954,54.6730
9,open_risk_projection_withhold_no_recovery,development_walk_forward,25.0,1756,96.7455,-30.1774,-3.5840,-7.1160,-11.8891,0.5497,110.9123,53.2402
10,open_risk_projection_withhold_no_recovery,outer_reused_diagnostic,10.0,934,219.4883,-26.9218,-4.7955,-8.7040,-14.5534,1.1345,57.4342,48.3534
11,open_risk_projection_withhold_no_recovery,outer_reused_diagnostic,25.0,934,75.1443,-32.3806,-4.4206,-11.1995,-14.6356,0.6857,50.6146,58.5131
12,full_withhold_and_recovery,development_walk_forward,10.0,1756,114.5893,-30.0833,-3.4857,-7.1138,-10.8237,0.6231,102.8714,54.6380
13,full_withhold_and_recovery,development_walk_forward,25.0,1756,96.7171,-30.0921,-3.5852,-7.1160,-11.8891,0.5482,114.4234,53.0930
14,full_withhold_and_recovery,outer_reused_diagnostic,10.0,934,219.4883,-26.9218,-4.7955,-8.7040,-14.5534,1.1345,57.4342,48.3534
15,full_withhold_and_recovery,outer_reused_diagnostic,25.0,934,75.1443,-32.3806,-4.4206,-11.1995,-14.6356,0.6857,50.6146,58.5131
16,nohold_with_recovery_reference,development_walk_forward,10.0,1756,118.1875,-29.9306,-3.4715,-7.1138,-10.8237,0.6332,107.6229,54.0702
17,nohold_with_recovery_reference,development_walk_forward,25.0,1756,102.2302,-30.1293,-3.5824,-7.1160,-11.8891,0.5685,112.0321,53.3330
18,nohold_with_recovery_reference,outer_reused_diagnostic,10.0,934,220.4298,-26.9218,-4.8117,-8.7040,-14.5534,1.1337,59.5363,48.1781
19,nohold_with_recovery_reference,outer_reused_diagnostic,25.0,934,66.1206,-36.4415,-4.4034,-11.1995,-14.6356,0.6391,46.9275,59.2094

soxx_benchmark

                    segment  cost_bps  return_pct  max_drawdown_pct
0  development_walk_forward      10.0    320.0028          -47.3741
1   outer_reused_diagnostic      10.0    398.0879          -42.7903
2  development_walk_forward      25.0    319.3744          -47.3741
3   outer_reused_diagnostic      25.0    397.3426          -42.7903

fee_ledger

,layer,segment,cost_bps,status,convention,return_pct,fee_fraction_of_nav_sum,fee_currency_of_startcash,fee_unit,base_10bp_day_parity
0,raw_allocator_only,development_walk_forward,0.0,ok,post_fee_desired,443.4399,0.0000,0.0000,fee_fraction_of_nav_sum is unitless NAV fracti...,True
1,raw_allocator_only,development_walk_forward,25.0,ok,post_fee_desired,350.7194,0.1870,0.5285,fee_fraction_of_nav_sum is unitless NAV fracti...,True
2,raw_allocator_only,outer_reused_diagnostic,0.0,ok,post_fee_desired,319.3984,0.0000,0.0000,fee_fraction_of_nav_sum is unitless NAV fracti...,True
3,raw_allocator_only,outer_reused_diagnostic,25.0,ok,post_fee_desired,285.8404,0.0834,0.1500,fee_fraction_of_nav_sum is unitless NAV fracti...,True
4,open_risk_projection_nohold_no_recovery,development_walk_forward,0.0,ok,pre_fee_account,201.0739,0.0000,0.0000,fee_fraction_of_nav_sum is unitless NAV fracti...,True
5,open_risk_projection_nohold_no_recovery,development_walk_forward,25.0,ok,pre_fee_account,132.8462,0.2570,0.4145,fee_fraction_of_nav_sum is unitless NAV fracti...,True
6,open_risk_projection_nohold_no_recovery,outer_reused_diagnostic,0.0,ok,pre_fee_account,240.0451,0.0000,0.0000,fee_fraction_of_nav_sum is unitless NAV fracti...,True
7,open_risk_projection_nohold_no_recovery,outer_reused_diagnostic,25.0,ok,pre_fee_account,193.0903,0.1489,0.2392,fee_fraction_of_nav_sum is unitless NAV fracti...,True
8,open_risk_projection_withhold_no_recovery,development_walk_forward,0.0,ok,pre_fee_account,138.1931,0.0000,0.0000,fee_fraction_of_nav_sum is unitless NAV fracti...,True
9,open_risk_projection_withhold_no_recovery,development_walk_forward,25.0,ok,pre_fee_account,85.3484,0.2508,0.3696,fee_fraction_of_nav_sum is unitless NAV fracti...,True
10,open_risk_projection_withhold_no_recovery,outer_reused_diagnostic,0.0,ok,pre_fee_account,238.3403,0.0000,0.0000,fee_fraction_of_nav_sum is unitless NAV fracti...,True
11,open_risk_projection_withhold_no_recovery,outer_reused_diagnostic,25.0,ok,pre_fee_account,193.1438,0.1436,0.2320,fee_fraction_of_nav_sum is unitless NAV fracti...,True
12,full_withhold_and_recovery,development_walk_forward,0.0,ok,pre_fee_account,137.8412,0.0000,0.0000,fee_fraction_of_nav_sum is unitless NAV fracti...,True
13,full_withhold_and_recovery,development_walk_forward,25.0,ok,pre_fee_account,83.8868,0.2572,0.3764,fee_fraction_of_nav_sum is unitless NAV fracti...,True
14,full_withhold_and_recovery,outer_reused_diagnostic,0.0,ok,pre_fee_account,238.3403,0.0000,0.0000,fee_fraction_of_nav_sum is unitless NAV fracti...,True
15,full_withhold_and_recovery,outer_reused_diagnostic,25.0,ok,pre_fee_account,193.1438,0.1436,0.2320,fee_fraction_of_nav_sum is unitless NAV fracti...,True
16,nohold_with_recovery_reference,development_walk_forward,0.0,ok,pre_fee_account,142.9746,0.0000,0.0000,fee_fraction_of_nav_sum is unitless NAV fracti...,True
17,nohold_with_recovery_reference,development_walk_forward,25.0,ok,pre_fee_account,85.6504,0.2691,0.3936,fee_fraction_of_nav_sum is unitless NAV fracti...,True
18,nohold_with_recovery_reference,outer_reused_diagnostic,0.0,ok,pre_fee_account,240.0451,0.0000,0.0000,fee_fraction_of_nav_sum is unitless NAV fracti...,True
19,nohold_with_recovery_reference,outer_reused_diagnostic,25.0,ok,pre_fee_account,193.0903,0.1489,0.2392,fee_fraction_of_nav_sum is unitless NAV fracti...,True

risk_report

,layer,segment,cost_bps,sessions,mean,std,annualized_return,information_ratio,max_drawdown,beta_vs_soxx,relative_wealth_vs_soxx
0,raw_allocator_only,development_walk_forward,10.0,1756,0.0009,0.0231,0.2452,0.6146,-0.5171,1.1557,1.2006
1,raw_allocator_only,development_walk_forward,25.0,1756,0.0009,0.0231,0.2264,0.5719,-0.5228,1.1555,1.0747
2,raw_allocator_only,outer_reused_diagnostic,10.0,934,0.0015,0.0268,0.4288,0.8644,-0.4561,1.0927,0.8144
3,raw_allocator_only,outer_reused_diagnostic,25.0,934,0.0014,0.0268,0.4107,0.8335,-0.4635,1.0927,0.7758
4,open_risk_projection_nohold_no_recovery,development_walk_forward,10.0,1756,0.0006,0.0137,0.1451,0.6390,-0.2993,0.5658,0.6468
5,open_risk_projection_nohold_no_recovery,development_walk_forward,25.0,1756,0.0004,0.0139,0.0979,0.4364,-0.3021,0.5730,0.4748
6,open_risk_projection_nohold_no_recovery,outer_reused_diagnostic,10.0,934,0.0012,0.0204,0.3455,0.9457,-0.2692,0.7270,0.6433
7,open_risk_projection_nohold_no_recovery,outer_reused_diagnostic,25.0,934,0.0005,0.0172,0.1381,0.4872,-0.3644,0.5840,0.3340
8,open_risk_projection_withhold_no_recovery,development_walk_forward,10.0,1756,0.0004,0.0133,0.1096,0.5062,-0.3008,0.5453,0.5130
9,open_risk_projection_withhold_no_recovery,development_walk_forward,25.0,1756,0.0004,0.0140,0.0961,0.4259,-0.3018,0.5785,0.4691
10,open_risk_projection_withhold_no_recovery,outer_reused_diagnostic,10.0,934,0.0012,0.0203,0.3444,0.9470,-0.2692,0.7242,0.6414
11,open_risk_projection_withhold_no_recovery,outer_reused_diagnostic,25.0,934,0.0006,0.0175,0.1535,0.5306,-0.3238,0.5950,0.3522
12,full_withhold_and_recovery,development_walk_forward,10.0,1756,0.0004,0.0134,0.1090,0.5006,-0.3008,0.5505,0.5109
13,full_withhold_and_recovery,development_walk_forward,25.0,1756,0.0004,0.0140,0.0960,0.4240,-0.3009,0.5837,0.4691
14,full_withhold_and_recovery,outer_reused_diagnostic,10.0,934,0.0012,0.0203,0.3444,0.9470,-0.2692,0.7242,0.6414
15,full_withhold_and_recovery,outer_reused_diagnostic,25.0,934,0.0006,0.0175,0.1535,0.5306,-0.3238,0.5950,0.3522
16,nohold_with_recovery_reference,development_walk_forward,10.0,1756,0.0004,0.0134,0.1115,0.5102,-0.2993,0.5531,0.5195
17,nohold_with_recovery_reference,development_walk_forward,25.0,1756,0.0004,0.0139,0.1002,0.4443,-0.3013,0.5781,0.4822
18,nohold_with_recovery_reference,outer_reused_diagnostic,10.0,934,0.0012,0.0204,0.3455,0.9457,-0.2692,0.7270,0.6433
19,nohold_with_recovery_reference,outer_reused_diagnostic,25.0,934,0.0005,0.0172,0.1381,0.4872,-0.3644,0.5840,0.3340

annual_metrics

,layer,segment,cost_bps,year,sessions,strategy_return_pct,soxx_return_pct,relative_wealth_vs_soxx
0,raw_allocator_only,development_walk_forward,10.0,2016,251,46.3222,40.0351,1.0449
1,raw_allocator_only,development_walk_forward,10.0,2017,251,27.9664,40.0641,0.9136
2,raw_allocator_only,development_walk_forward,10.0,2018,251,-8.9386,-8.9555,1.0002
3,raw_allocator_only,development_walk_forward,10.0,2019,252,78.3374,67.8956,1.0622
4,raw_allocator_only,development_walk_forward,10.0,2020,253,77.3811,51.7975,1.1685
...,...,...,...,...,...,...,...,...
105,nohold_with_recovery_reference,outer_reused_diagnostic,10.0,2026,183,85.7821,84.8826,1.0049
106,nohold_with_recovery_reference,outer_reused_diagnostic,25.0,2023,249,29.1052,62.4004,0.7950
107,nohold_with_recovery_reference,outer_reused_diagnostic,25.0,2024,252,-19.7396,16.0372,0.6917
108,nohold_with_recovery_reference,outer_reused_diagnostic,25.0,2025,250,8.8302,42.7497,0.7624
109,nohold_with_recovery_reference,outer_reused_diagnostic,25.0,2026,183,47.3090,84.8826,0.7968

risk_mechanism

,case,layer,segment,cost_bps,status,sessions,stop_events,emergency_entries,emergency_longest_consecutive_days,state_share,binding_share,mean_drawdown_before,mean_beta,phases,mean_strategy_return,mean_soxx_return,mean_ending_cash_weight,paired_vs_raw
0,full_withhold_and_recovery::development_walk_f...,full_withhold_and_recovery,development_walk_forward,10,ok,1756,44,18,136,"{'0': 0.4060364464692483, '2': 0.2488610478359...","{'clock_cap_binding': 0.3439635535307517, 'eme...",0.1319,0.6784,"{'stop_entered': {'days': 44, 'share': 0.02505...",0.0005,0.001,0.5464,"{'status': 'ok', 'paired_log_wealth_diff': -0...."
1,full_withhold_and_recovery::development_walk_f...,full_withhold_and_recovery,development_walk_forward,25,ok,1756,44,21,120,"{'0': 0.4060364464692483, '2': 0.2488610478359...","{'clock_cap_binding': 0.3439635535307517, 'eme...",0.1290,0.7069,"{'stop_entered': {'days': 44, 'share': 0.02505...",0.0005,0.001,0.5309,"{'status': 'ok', 'paired_log_wealth_diff': -0...."
2,full_withhold_and_recovery::outer_reused_diagn...,full_withhold_and_recovery,outer_reused_diagnostic,10,ok,934,20,4,42,"{'0': 0.5053533190578159, '2': 0.2055674518201...","{'clock_cap_binding': 0.2751605995717345, 'eme...",0.0962,0.8173,"{'stop_entered': {'days': 20, 'share': 0.02141...",0.0014,0.002,0.4835,"{'status': 'ok', 'paired_log_wealth_diff': -0...."
3,full_withhold_and_recovery::outer_reused_diagn...,full_withhold_and_recovery,outer_reused_diagnostic,25,ok,934,30,8,268,"{'2': 0.31263383297644537, '3': 0.310492505353...","{'clock_cap_binding': 0.43147751605995716, 'em...",0.1701,0.5906,"{'stop_entered': {'days': 30, 'share': 0.03211...",0.0008,0.002,0.5851,"{'status': 'ok', 'paired_log_wealth_diff': -0...."
4,nohold_with_recovery_reference::development_wa...,nohold_with_recovery_reference,development_walk_forward,10,ok,1756,44,21,96,"{'0': 0.4060364464692483, '2': 0.2488610478359...","{'clock_cap_binding': 0.3439635535307517, 'eme...",0.1304,0.6880,"{'stop_entered': {'days': 44, 'share': 0.02505...",0.0005,0.001,0.5407,"{'status': 'ok', 'paired_log_wealth_diff': -0...."
5,nohold_with_recovery_reference::development_wa...,nohold_with_recovery_reference,development_walk_forward,25,ok,1756,44,19,134,"{'0': 0.4060364464692483, '2': 0.2488610478359...","{'clock_cap_binding': 0.3439635535307517, 'eme...",0.1308,0.7016,"{'stop_entered': {'days': 44, 'share': 0.02505...",0.0005,0.001,0.5333,"{'status': 'ok', 'paired_log_wealth_diff': -0...."
6,nohold_with_recovery_reference::outer_reused_d...,nohold_with_recovery_reference,outer_reused_diagnostic,10,ok,934,20,4,42,"{'0': 0.5053533190578159, '2': 0.2055674518201...","{'clock_cap_binding': 0.2751605995717345, 'eme...",0.0973,0.8211,"{'stop_entered': {'days': 20, 'share': 0.02141...",0.0015,0.002,0.4818,"{'status': 'ok', 'paired_log_wealth_diff': -0...."
7,nohold_with_recovery_reference::outer_reused_d...,nohold_with_recovery_reference,outer_reused_diagnostic,25,ok,934,30,11,358,"{'2': 0.31263383297644537, '3': 0.310492505353...","{'clock_cap_binding': 0.43147751605995716, 'em...",0.1898,0.5777,"{'stop_entered': {'days': 30, 'share': 0.03211...",0.0007,0.002,0.5921,"{'status': 'ok', 'paired_log_wealth_diff': -0...."
8,open_risk_projection_nohold_no_recovery::devel...,open_risk_projection_nohold_no_recovery,development_walk_forward,10,ok,1756,41,17,96,"{'0': 0.44703872437357633, '2': 0.231776765375...","{'clock_cap_binding': 0.3200455580865604, 'eme...",0.1263,0.7038,"{'stop_entered': {'days': 41, 'share': 0.02334...",0.0007,0.001,0.5342,"{'status': 'ok', 'paired_log_wealth_diff': -0...."
9,open_risk_projection_nohold_no_recovery::devel...,open_risk_projection_nohold_no_recovery,development_walk_forward,25,ok,1756,44,17,134,"{'0': 0.4060364464692483, '2': 0.2488610478359...","{'clock_cap_binding': 0.3439635535307517, 'eme...",0.1320,0.6983,"{'stop_entered': {'days': 44, 'share': 0.02505...",0.0005,0.001,0.5354,"{'status': 'ok', 'paired_log_wealth_diff': -0...."
10,open_risk_projection_nohold_no_recovery::outer...,open_risk_projection_nohold_no_recovery,outer_reused_diagnostic,10,ok,934,20,4,42,"{'0': 0.5053533190578159, '2': 0.2055674518201...","{'clock_cap_binding': 0.2751605995717345, 'eme...",0.0973,0.8211,"{'stop_entered': {'days': 20, 'share': 0.02141...",0.0015,0.002,0.4818,"{'status': 'ok', 'paired_log_wealth_diff': -0...."
11,open_risk_projection_nohold_no_recovery::outer...,open_risk_projection_nohold_no_recovery,outer_reused_diagnostic,25,ok,934,30,11,358,"{'2': 0.31263383297644537, '3': 0.310492505353...","{'clock_cap_binding': 0.43147751605995716, 'em...",0.1898,0.5777,"{'stop_entered': {'days': 30, 'share': 0.03211...",0.0007,0.002,0.5921,"{'status': 'ok', 'paired_log_wealth_diff': -0...."
12,open_risk_projection_withhold_no_recovery::dev...,open_risk_projection_withhold_no_recovery,development_walk_forward,10,ok,1756,44,19,136,"{'0': 0.4060364464692483, '2': 0.2488610478359...","{'clock_cap_binding': 0.3439635535307517, 'eme...",0.1317,0.6785,"{'stop_entered': {'days': 44, 'share': 0.02505...",0.0005,0.001,0.5467,"{'status': 'ok', 'paired_log_wealth_diff': -0...."
13,open_risk_projection_withhold_no_recovery::dev...,open_risk_projection_withhold_no_recovery,development_walk_forward,25,ok,1756,44,19,120,"{'0': 0.4060364464692483, '2': 0.2488610478359...","{'clock_cap_binding': 0.3439635535307517, 'eme...",0.1294,0.7046,"{'stop_entered': {'days': 44, 'share': 0.02505...",0.0005,0.001,0.5324,"{'status': 'ok', 'paired_log_wealth_diff': -0...."
14,open_risk_projection_withhold_no_recovery::out...,open_risk_projection_withhold_no_recovery,outer_reused_diagnostic,10,ok,934,20,4,42,"{'0': 0.5053533190578159, '2': 0.2055674518201...","{'clock_cap_binding': 0.2751605995717345, 'eme...",0.0962,0.8173,"{'stop_entered': {'days': 20, 'share': 0.02141...",0.0014,0.002,0.4835,"{'status': 'ok', 'paired_log_wealth_diff': -0...."
15,open_risk_projection_withhold_no_recovery::out...,open_risk_projection_withhold_no_recovery,outer_reused_diagnostic,25,ok,934,30,8,268,"{'2': 0.31263383297644537, '3': 0.310492505353...","{'clock_cap_binding': 0.43147751605995716, 'em...",0.1701,0.5906,"{'stop_entered': {'days': 30, 'share': 0.03211...",0.0008,0.002,0.5851,"{'status': 'ok', 'paired_log_wealth_diff': -0...."
16,raw_allocator_only::development_walk_forward::10,raw_allocator_only,development_walk_forward,10,ok,1756,0,0,0,{'0': 1.0},"{'clock_cap_binding': 0.0, 'emergency_cap_bind...",0.0969,1.0896,"{'stop_entered': {'days': 0, 'share': 0.0}, 'e...",0.0012,0.001,0.3685,{'status': 'self_raw_reference'}
17,raw_allocator_only::development_walk_forward::25,raw_allocator_only,development_walk_forward,25,ok,1756,0,0,0,{'0': 1.0},"{'clock_cap_binding': 0.0, 'emergency_cap_bind...",0.0995,1.0896,"{'stop_entered': {'days': 0, 'share': 0.0}, 'e...",0.0011,0.001,0.3685,{'status': 'self_raw_reference'}
18,raw_allocator_only::outer_reused_diagnostic::10,raw_allocator_only,outer_reused_diagnostic,10,ok,934,0,0,0,{'0': 1.0},"{'clock_cap_binding': 0.0, 'emergency_cap_bind...",0.1127,1.0296,"{'stop_entered': {'days': 0, 'share': 0.0}, 'e...",0.0019,0.002,0.4042,{'status': 'self_raw_reference'}
19,raw_allocator_only::outer_reused_diagnostic::25,raw_allocator_only,outer_reused_diagnostic,25,ok,934,0,0,0,{'0': 1.0},"{'clock_cap_binding': 0.0, 'emergency_cap_bind...",0.1164,1.0296,"{'stop_entered': {'days': 0, 'share': 0.0}, 'e...",0.0018,0.002,0.4042,{'status': 'self_raw_reference'}

## 中文结论

In [5]:
from IPython.display import Markdown, display
display(Markdown((CARD/'conclusion.md').read_text()))

# 冻结配置、风险投影与动作层诊断

使用同一价格版本、五层独立账户、两窗口与10/25bp费用；零拟合、零新候选。

完整目标读取已哈希parent17冻结推理快照；原f696预测2686行逐行对照，末尾四日来自已保存的冻结模型推理延展。未重新推理、未静默HOLD。

Qlib原生账户对账：20/20；完整动作层与父e4逐日收益、三权重和动作一致。

| 窗口/费用 | 层 | 收益% | 最大回撤% | CVaR5% | 相对SOXX财富 |
|---|---|---:|---:|---:|---:|
| development_walk_forward / 10bp | raw_allocator_only | 404.26 | -51.71 | -5.33 | 1.2006 |
| development_walk_forward / 25bp | raw_allocator_only | 350.72 | -52.28 | -5.33 | 1.0747 |
| outer_reused_diagnostic / 10bp | raw_allocator_only | 305.64 | -45.61 | -6.17 | 0.8144 |
| outer_reused_diagnostic / 25bp | raw_allocator_only | 285.84 | -46.35 | -6.17 | 0.7758 |
| development_walk_forward / 10bp | open_risk_projection_nohold_no_recovery | 171.67 | -29.93 | -3.51 | 0.6468 |
| development_walk_forward / 25bp | open_risk_projection_nohold_no_recovery | 99.14 | -30.21 | -3.58 | 0.4748 |
| outer_reused_diagnostic / 10bp | open_risk_projection_nohold_no_recovery | 220.43 | -26.92 | -4.81 | 0.6433 |
| outer_reused_diagnostic / 25bp | open_risk_projection_nohold_no_recovery | 66.12 | -36.44 | -4.40 | 0.3340 |
| development_walk_forward / 10bp | open_risk_projection_withhold_no_recovery | 115.46 | -30.08 | -3.46 | 0.5130 |
| development_walk_forward / 25bp | open_risk_projection_withhold_no_recovery | 96.75 | -30.18 | -3.58 | 0.4691 |
| outer_reused_diagnostic / 10bp | open_risk_projection_withhold_no_recovery | 219.49 | -26.92 | -4.80 | 0.6414 |
| outer_reused_diagnostic / 25bp | open_risk_projection_withhold_no_recovery | 75.14 | -32.38 | -4.42 | 0.3522 |
| development_walk_forward / 10bp | full_withhold_and_recovery | 114.59 | -30.08 | -3.49 | 0.5109 |
| development_walk_forward / 25bp | full_withhold_and_recovery | 96.72 | -30.09 | -3.59 | 0.4691 |
| outer_reused_diagnostic / 10bp | full_withhold_and_recovery | 219.49 | -26.92 | -4.80 | 0.6414 |
| outer_reused_diagnostic / 25bp | full_withhold_and_recovery | 75.14 | -32.38 | -4.42 | 0.3522 |
| development_walk_forward / 10bp | nohold_with_recovery_reference | 118.19 | -29.93 | -3.47 | 0.5195 |
| development_walk_forward / 25bp | nohold_with_recovery_reference | 102.23 | -30.13 | -3.58 | 0.4822 |
| outer_reused_diagnostic / 10bp | nohold_with_recovery_reference | 220.43 | -26.92 | -4.81 | 0.6433 |
| outer_reused_diagnostic / 25bp | nohold_with_recovery_reference | 66.12 | -36.44 | -4.40 | 0.3340 |

HOLD与恢复动作的交互（收益百分点，只是有序路径对照）：

- development_walk_forward / 10bp：无HOLD时加入恢复 -53.48pp；有HOLD时加入恢复 -0.87pp。
- development_walk_forward / 25bp：无HOLD时加入恢复 +3.09pp；有HOLD时加入恢复 -0.03pp。
- outer_reused_diagnostic / 10bp：无HOLD时加入恢复 +0.00pp；有HOLD时加入恢复 +0.00pp。
- outer_reused_diagnostic / 25bp：无HOLD时加入恢复 +0.00pp；有HOLD时加入恢复 +0.00pp。

风险循环的实际账户统计：

- development_walk_forward / 10bp：stop事件 41 次；emergency最长连续 96 日。详情、状态占比和分组配对log财富差见risk_mechanism.csv及Recorder。
- development_walk_forward / 25bp：stop事件 44 次；emergency最长连续 134 日。详情、状态占比和分组配对log财富差见risk_mechanism.csv及Recorder。
- outer_reused_diagnostic / 10bp：stop事件 20 次；emergency最长连续 42 日。详情、状态占比和分组配对log财富差见risk_mechanism.csv及Recorder。
- outer_reused_diagnostic / 25bp：stop事件 30 次；emergency最长连续 358 日。详情、状态占比和分组配对log财富差见risk_mechanism.csv及Recorder。

年度、beta及Qlib product模式风险统计见annual_metrics.csv、risk_report.csv。费用归因从10bp实际目标路径重新结算0/25bp，10bp自复现检查真执行；不是从净收益再次减费。

风险投影减少回撤也牺牲上涨暴露；该比较不能证明约束过度，不能靠删除风控达成上线。raw使用post_fee_desired，旧动作层使用pre_fee_account，差异及账户反馈均包含在路径比较中。这些层不是唯一可加的因果贡献，条件分组不是可交易子策略。

外窗已被反复查看，只是复用历史诊断，不是新鲜样本外。收益、尾部风险、年度稳定性和独立前向证据仍需分别达标。

晋升决定：不晋升；本卡只定位机制。下一步依据冻结状态统计制定一个明确机制增量，再单独冻结验证；不得继续搜索失败的信息路线、改符号或放宽门槛。