# 条件波动信息与稳定净超额

在已验收的统一Qlib行情上，固定同一年度风险预算、H5先前均值和费用结算，对比扩展方差、开盘20日、收盘20日及OOF预测四种风险估计。先固定selection_plan.json，再拟合和回放；旧历史不当作新样本外。

In [1]:
from pathlib import Path
import os,sys,json
ROOT=Path.cwd().resolve()
while not (ROOT/'src').is_dir():
    if ROOT.parent==ROOT: raise RuntimeError('Run within workspace')
    ROOT=ROOT.parent
sys.path.insert(0,str(ROOT))
os.environ['MLFLOW_ALLOW_FILE_STORE']='true'
os.environ['MLFLOW_DISABLE_AGENT_HINT']='1'
import qlib
qlib.init(provider_uri=str(ROOT/'data/qlib/published_futu_affine_20260925_v1'),region='us',kernels=1)
from src.workflow.conditional_variance import run_experiment
summary=run_experiment(root=ROOT)
summary

[87531:MainThread](2026-10-02 22:28:46,142) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[87531:MainThread](2026-10-02 22:28:46,516) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[87531:MainThread](2026-10-02 22:28:46,516) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/conditional-variance-20261002/data/qlib/published_futu_affine_20260925_v1')}

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[87531:MainThread](2026-10-02 22:28:47,836) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[87531:MainThread](2026-10-02 22:28:47,836) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[87531:MainThread](2026-10-02 22:28:47,837) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/conditional-variance-20261002/data/qlib/published_futu_affine_20260925_v1')}

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[87531:MainThread](2026-10-02 22:28:47,864) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[87531:MainThread](2026-10-02 22:28:47,865) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[87531:MainThread](2026-10-02 22:28:47,865) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/conditional-variance-20261002/data/qlib/published_futu_affine_20260925_v1')}

[87531:MainThread](2026-10-02 22:28:48,050) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[87531:MainThread](2026-10-02 22:28:48,050) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[87531:MainThread](2026-10-02 22:28:48,051) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[87531:MainThread](2026-10-02 22:28:48,275) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[87531:MainThread](2026-10-02 22:28:48,275) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[87531:MainThread](2026-10-02 22:28:48,275) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

Variance repeat=1 expanding_variance_control cost=10 verified=True estimator_fallbacks=0

Variance repeat=1 expanding_variance_control cost=25 verified=True estimator_fallbacks=0

Variance repeat=1 observed_open20 cost=10 verified=True estimator_fallbacks=0

Variance repeat=1 observed_open20 cost=25 verified=True estimator_fallbacks=0

Variance repeat=1 observed_close20 cost=10 verified=True estimator_fallbacks=0

Variance repeat=1 observed_close20 cost=25 verified=True estimator_fallbacks=0

Variance repeat=1 learned_vol5 cost=10 verified=True estimator_fallbacks=0

Variance repeat=1 learned_vol5 cost=25 verified=True estimator_fallbacks=0

[87531:MainThread](2026-10-02 22:29:04,280) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[87531:MainThread](2026-10-02 22:29:04,280) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[87531:MainThread](2026-10-02 22:29:04,280) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[87531:MainThread](2026-10-02 22:29:04,606) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[87531:MainThread](2026-10-02 22:29:04,607) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[87531:MainThread](2026-10-02 22:29:04,607) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

Variance repeat=2 expanding_variance_control cost=10 verified=True estimator_fallbacks=0

Variance repeat=2 expanding_variance_control cost=25 verified=True estimator_fallbacks=0

Variance repeat=2 observed_open20 cost=10 verified=True estimator_fallbacks=0

Variance repeat=2 observed_open20 cost=25 verified=True estimator_fallbacks=0

Variance repeat=2 observed_close20 cost=10 verified=True estimator_fallbacks=0

Variance repeat=2 observed_close20 cost=25 verified=True estimator_fallbacks=0

Variance repeat=2 learned_vol5 cost=10 verified=True estimator_fallbacks=0

Variance repeat=2 learned_vol5 cost=25 verified=True estimator_fallbacks=0

[87531:MainThread](2026-10-02 22:29:19,511) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[87531:MainThread](2026-10-02 22:29:19,512) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[87531:MainThread](2026-10-02 22:29:19,512) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[87531:MainThread](2026-10-02 22:29:19,741) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[87531:MainThread](2026-10-02 22:29:19,742) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[87531:MainThread](2026-10-02 22:29:19,742) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

Variance repeat=3 expanding_variance_control cost=10 verified=True estimator_fallbacks=0

Variance repeat=3 expanding_variance_control cost=25 verified=True estimator_fallbacks=0

Variance repeat=3 observed_open20 cost=10 verified=True estimator_fallbacks=0

Variance repeat=3 observed_open20 cost=25 verified=True estimator_fallbacks=0

Variance repeat=3 observed_close20 cost=10 verified=True estimator_fallbacks=0

Variance repeat=3 observed_close20 cost=25 verified=True estimator_fallbacks=0

Variance repeat=3 learned_vol5 cost=10 verified=True estimator_fallbacks=0

Variance repeat=3 learned_vol5 cost=25 verified=True estimator_fallbacks=0

Variance development sealed: {'variant': 'expanding_variance_control', 'historical_qualification_pass': False, 'passed_gates': 12, 'worst_annualized_lower_bound': -0.075001288222862, 'worst_relative_wealth': 0.8038691954700189, 'positive_years_10bps': 2}

Variance diagnostic repeat=1 annual_refit cost=10

Variance diagnostic repeat=1 annual_refit cost=25

Variance diagnostic repeat=1 frozen2022_calibration cost=10

Variance diagnostic repeat=1 frozen2022_calibration cost=25

Variance diagnostic repeat=2 annual_refit cost=10

Variance diagnostic repeat=2 annual_refit cost=25

Variance diagnostic repeat=2 frozen2022_calibration cost=10

Variance diagnostic repeat=2 frozen2022_calibration cost=25

Variance diagnostic repeat=3 annual_refit cost=10

Variance diagnostic repeat=3 annual_refit cost=25

Variance diagnostic repeat=3 frozen2022_calibration cost=10

Variance diagnostic repeat=3 frozen2022_calibration cost=25

[87531:MainThread](2026-10-02 22:29:47,815) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[87531:MainThread](2026-10-02 22:29:47,815) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[87531:MainThread](2026-10-02 22:29:47,816) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/conditional-variance-20261002/data/qlib/published_futu_affine_20260925_v1')}

[87531:MainThread](2026-10-02 22:29:47,827) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[87531:MainThread](2026-10-02 22:29:47,832) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[87531:MainThread](2026-10-02 22:29:47,839) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[87531:MainThread](2026-10-02 22:29:47,839) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[87531:MainThread](2026-10-02 22:29:47,842) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x1383f6540>

backtest loop:   0%|          | 0/1762 [00:00<?, ?it/s]

[87531:MainThread](2026-10-02 22:29:48,943) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[87531:MainThread](2026-10-02 22:29:48,944) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[87531:MainThread](2026-10-02 22:29:48,945) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/conditional-variance-20261002/data/qlib/published_futu_affine_20260925_v1')}

[87531:MainThread](2026-10-02 22:29:48,955) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[87531:MainThread](2026-10-02 22:29:48,959) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[87531:MainThread](2026-10-02 22:29:48,966) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[87531:MainThread](2026-10-02 22:29:48,966) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[87531:MainThread](2026-10-02 22:29:48,969) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x1392f48f0>

backtest loop:   0%|          | 0/1762 [00:00<?, ?it/s]

[87531:MainThread](2026-10-02 22:29:50,302) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[87531:MainThread](2026-10-02 22:29:50,303) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[87531:MainThread](2026-10-02 22:29:50,303) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/conditional-variance-20261002/data/qlib/published_futu_affine_20260925_v1')}

[87531:MainThread](2026-10-02 22:29:50,304) WARNING - qlib.workflow - [expm.py:231] - No valid experiment found. Create a new experiment with name conditional_variance_20261002.

[87531:MainThread](2026-10-02 22:29:50,305) INFO - qlib.workflow - [exp.py:258] - Experiment 607243708770492389 starts running ...

[87531:MainThread](2026-10-02 22:29:50,382) INFO - qlib.workflow - [recorder.py:345] - Recorder 9a447c33dc934baeb1d4c3f2b9bf2122 starts running under Experiment 607243708770492389 ...

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[87531:MainThread](2026-10-02 22:29:51,015) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

{'experiment': 'conditional_variance_20261002',
 'campaign_status': 'active_research',
 'objective_achieved': False,
 'decision': 'continue_research_no_historical_qualification',
 'selected': {'variant': 'expanding_variance_control',
  'historical_qualification_pass': False,
  'passed_gates': 12,
  'worst_annualized_lower_bound': -0.075001288222862,
  'worst_relative_wealth': 0.8038691954700189,
  'positive_years_10bps': 2},
 'historical_qualification_pass': False,
 'learned_increment_over_both_observed_controls_at_both_costs': False,
 'learned_attribution_integrity_eligible': False,
 'learned_increment_scope': 'descriptive net path differences; neither fallback policy nor positive point estimates alone establish learned alpha',
 'new_forward_qualified': False,
 'source_sensitivity_completed': False,
 'source': {'experiment': 'canonical_price_basis_20261002',
  'recorder_id': 'bd754e6362b241f194351a1e7aebff6f',
  'provider_uri': 'data/qlib/published_futu_affine_20260925_v1',
  'as_of': '2026-09-25',
  'model_signal_start': '2011-01-03',
  'history_start': '2010-03-11',
  'basis': 'published_futu_affine_v1',
  'secondary_bars': 16,
  'limitations': 'Published affine basis differs slightly from serverQFQ; Jan2012 secondary quote uncertainty remains. Rebuilt history is not fresh out-of-sample evidence.'},
 'source_audit': {'parent_recorder_id': 'bd754e6362b241f194351a1e7aebff6f',
  'parent_summary_sha256': '0e444d39dd4e09e5bdcac2d44dd77fa3db356ce735ecdfc80b8f937cf0bf362f',
  'provider_uri': '/Users/rziiiii/dev/workspace-worktrees/conditional-variance-20261002/data/qlib/published_futu_affine_20260925_v1',
  'provider_manifest_sha256': 'cbbdeeca2e1c7dc0bce0f9cdf3495f50d3219bddd992e1b893f8362a5e51bc65',
  'native_frame_sha256': 'b7a59f39feed5aed6e61fec2b4239092c474e453c91d4d133c73f9dcc571a03f',
  'as_of': '2026-09-25',
  'features': {'primary_frame_sha256': 'bf5586573a4c51feb348c8e1a661ccf0f334f3a7d83b9ce9558629bfd16cf02b',
   'feature_columns': ['soxx_ret1',
    'soxx_mom5',
    'soxx_mom20',
    'soxx_mom60',
    'soxx_reversal1',
    'soxx_vol10',
    'soxx_vol20',
    'soxx_downside_vol20',
    'soxx_skew20',
    'soxx_kurt60',
    'soxx_drawdown20',
    'soxx_drawdown60',
    'soxx_gap1',
    'soxx_intraday1',
    'soxx_volume_z20',
    'soxx_range_pct',
    'soxl_gap1',
    'soxl_intraday1',
    'soxl_volume_z20',
    'soxl_range_pct',
    'relative_log_return_1d',
    'relative_log_return_5d',
    'relative_log_return_20d',
    'relative_volatility_20',
    'soxx_efficiency_20',
    'cash_advantage_prediction',
    'future_vol_prediction',
    'forecast_available'],
   'price_basis': 'published_futu_affine_v1',
   'volume_z20': '(log(volume)-rolling20_mean)/(rolling20_std_ddof0+1e-8); min_periods10',
   'volume_feature_change': 'log1p replaced by log before any new fitting; no other feature recipe change',
   'horizon': {'horizon_sessions': 5,
    'formula': 'open[t+6]/open[t+1]-1',
    'signal': 'close[t]',
    'entry': 'open[t+1]',
    'outcome_available': 'open[t+6],09:30 America/New_York',
    'feature_columns': ['soxx_ret1',
     'soxx_mom5',
     'soxx_mom20',
     'soxx_mom60',
     'soxx_reversal1',
     'soxx_vol10',
     'soxx_vol20',
     'soxx_downside_vol20',
     'soxx_skew20',
     'soxx_kurt60',
     'soxx_drawdown20',
     'soxx_drawdown60',
     'soxx_gap1',
     'soxx_intraday1',
     'soxx_volume_z20',
     'soxx_range_pct',
     'soxl_gap1',
     'soxl_intraday1',
     'soxl_volume_z20',
     'soxl_range_pct',
     'relative_log_return_1d',
     'relative_log_return_5d',
     'relative_log_return_20d',
     'relative_volatility_20',
     'soxx_efficiency_20'],
    'label_columns': ['soxl_return_h5', 'soxx_return_h5'],
    'primary_input_sha256': '5e8bad935deaa8782acb9799cbf3dc52c85d9f28bbb9eeb2ac824572f2d33bf3',
    'execution_prices_sha256': '25d1e2486924c3e21f0aa6e1a004c7a8b02cb8acc5c279713f18f5aae0fdba9a',
    'horizon_frame_sha256': 'bf5586573a4c51feb348c8e1a661ccf0f334f3a7d83b9ce9558629bfd16cf02b',
    'rows': 3956,
    'complete_labels': 3950,
    'last_feature_date': '2026-09-25',
    'last_complete_label_signal': '2026-09-17',
    'last_complete_label_available_at': '2026-09-25T09:30:00-04:00',
    'daily_returns_preserved': True,
    'mean_covariance_units': 'five_session_simple_return_squared',
    'daily_risk_covariance_units': 'one_session_simple_return_squared',
    'qlib_docs_reference': 'https://qlib.readthedocs.io/en/latest/component/data.html'}},
  'source_api': ['qlib.workflow.R.get_recorder',
   'qlib.data.D.calendar',
   'qlib.data.D.instruments',
   'qlib.data.D.features']},
 'source_sha256': {'src/data/conditional_variance.py': '818cfe475f6631cb231e66f6f11fca4b150b55fbca81bc32986d1612c81d19e6',
  'src/model/convex_allocation.py': '28228f8db1a8d6acf42dcffebd5e7edbaef857146ee7cd3bc067970a702eb86c',
  'src/workflow/conditional_variance.py': '5b2ae71b45d308db376166a29b015b35ec8c38499d51b0426d066222eaa7a2b5',
  'src/data/integrated_allocation.py': '73f2495f6a9860860a76a5a8c2f679c42f5a76f089c10fb7d347ce66acc36e9c',
  'src/data/convex_allocation.py': '915c7eae8da16d69221d660e040b26ad5ba16e37fd607afd01ae0842e0fba82f',
  'src/analysis/integrated_allocation.py': '63a04045c59e8266efc2642a4db3d080845bdefbad6c2ac914a2194d26c17fc4',
  'src/workflow/convex_excess.py': 'dee0b77983fee5268c3f76360c11b1cb145aca3cffec1e5e4e89afa28c0fa698',
  'src/analysis/convex_qlib.py': '7bb60f7a3365cc36623785f25aa62c2f585211eb85483c0a3891caa53d7fd9e9',
  'src/backtest/qlib_continuous_position.py': 'f06bb596b6d3d3f875e9b6c59490080684d13fbe9f6763bd039d1b2afa4c5721',
  'src/workflow/benchmark_risk_excess.py': '26fcd325ca5cd20ed37eec9e8296b477eedc907e4c815af802d448236b5cdbcd',
  'src/workflow/stable_excess_integration.py': '7753c5bc16dddda5758d6fe5609fa7be915c6484f05e1881989a67afdf17771c',
  'src/backtest/position_accounting.py': '070a42a631f4ddc5aaa251791c9c8e43b263d34e9ae70d7e0a66a486f6b4fdde',
  'src/workflow/stage1_economic_action.py': '17a580e1a0fdf1e991fdfd150d59e80f272f199a9f0bd45a99d325d155cd5fe7',
  'src/data/qlib_native.py': 'ad0bd14a95347bc2e7513f71654abdc7ec12553730472dea2f8e668e25f9054b',
  'src/data/price_basis.py': '8e73d8267c474afd589e10df67d7391b8b938160d1fa13016aff7c717e80382e',
  'src/factor/soxx_pit_tail_factors.py': '46adf9dc728225657273cd220993630c6beba504c430d80f955c025454f19976',
  'src/workflow/pit_constituent_auxiliary_training_allocation.py': '1120abca4fdc1257c3a2ed9b42cd8b515356eeea0f5ef9e79622f3b38ceff85d'},
 'plan_sha256': '0aa019ede34351b2831c19daf8bbea24f843e1d20102008c0f5d9f5d9af2bfbe',
 'provider_uri': 'data/qlib/published_futu_affine_20260925_v1',
 'region': 'us',
 'market': 'all',
 'recorder_id': '9a447c33dc934baeb1d4c3f2b9bf2122',
 'recorder_uri': '/Users/rziiiii/dev/workspace/research/conditional_variance_20261002/qlib_recorder',
 'recorder_local_dir': '/Users/rziiiii/dev/workspace/research/conditional_variance_20261002/qlib_recorder/607243708770492389/9a447c33dc934baeb1d4c3f2b9bf2122',
 'recorder_relative_dir': 'qlib_recorder/607243708770492389/9a447c33dc934baeb1d4c3f2b9bf2122',
 'development_last_exit': '2023-01-04',
 'selection_uses_diagnostic_signal_years': False,
 'native_qlib_audit': {'10': {'status': 'passed',
   'sessions': 1762,
   'start': '2016-01-05',
   'end': '2023-01-03',
   'provider_uri': '/Users/rziiiii/dev/workspace-worktrees/conditional-variance-20261002/data/qlib/published_futu_affine_20260925_v1',
   'cost_bps': 10.0,
   'initial_cash': 100000.0,
   'maximum_session_return_error': 2.0771470099489875e-08,
   'tolerance': 1e-07,
   'native_api': 'qlib.backtest.backtest + SimulatorExecutor + Exchange + Account + Position',
   'position_type': 'src.backtest.qlib_continuous_position.QlibContinuousPosition',
   'position_precision_fix': 'Every positive fractional-sale residual remains owned; no relative isclose liquidation.',
   'report_mark': 'native same-day close; next-open reconciliation marks native positions through Qlib D.features',
   'sealed_stage1_code_changed': False,
   'qlib_api_reference': 'https://qlib.readthedocs.io/en/latest/reference/api.html#qlib.backtest.backtest',
   'policy_scope': 'continuous_three_asset_targets_without_legacy_allocation_caps',
   'legacy_controller_executed': False,
   'scope': 'complete prescribed daily target/HOLD schedule; actual Qlib Exchange, Position, report and next-open accounting',
   'risk_annualization_sessions': 252,
   'native_close_anchored_max_drawdown_pct': -43.34695302241284,
   'native_open_to_open_anchored_max_drawdown_pct': -45.428553061634204,
   'risk_table_mark_convention': 'risk_analysis uses native close marks; risk_analysis_open_to_open uses native positions marked at the following open',
   'execution_limitation': 'Observed historical opens and continuous adjusted shares; no claim of spread/impact/partial-fill evidence.'},
  '25': {'status': 'passed',
   'sessions': 1762,
   'start': '2016-01-05',
   'end': '2023-01-03',
   'provider_uri': '/Users/rziiiii/dev/workspace-worktrees/conditional-variance-20261002/data/qlib/published_futu_affine_20260925_v1',
   'cost_bps': 25.0,
   'initial_cash': 100000.0,
   'maximum_session_return_error': 2.0786287135976522e-08,
   'tolerance': 1e-07,
   'native_api': 'qlib.backtest.backtest + SimulatorExecutor + Exchange + Account + Position',
   'position_type': 'src.backtest.qlib_continuous_position.QlibContinuousPosition',
   'position_precision_fix': 'Every positive fractional-sale residual remains owned; no relative isclose liquidation.',
   'report_mark': 'native same-day close; next-open reconciliation marks native positions through Qlib D.features',
   'sealed_stage1_code_changed': False,
   'qlib_api_reference': 'https://qlib.readthedocs.io/en/latest/reference/api.html#qlib.backtest.backtest',
   'policy_scope': 'continuous_three_asset_targets_without_legacy_allocation_caps',
   'legacy_controller_executed': False,
   'scope': 'complete prescribed daily target/HOLD schedule; actual Qlib Exchange, Position, report and next-open accounting',
   'risk_annualization_sessions': 252,
   'native_close_anchored_max_drawdown_pct': -43.582519870744264,
   'native_open_to_open_anchored_max_drawdown_pct': -45.64840572555558,
   'risk_table_mark_convention': 'risk_analysis uses native close marks; risk_analysis_open_to_open uses native positions marked at the following open',
   'execution_limitation': 'Observed historical opens and continuous adjusted shares; no claim of spread/impact/partial-fill evidence.'}},
 'deterministic_reproduction': {'fresh_runs': 3,
  'all_match': True,
  'tolerance': 1e-08,
  'independent_statistical_observations': False},
 'production_change': False,
 'real_broker_orders': False,
 'sidecars': ['model_selection.csv',
  'backtest_benchmark_comparison.csv',
  'annual_metrics.csv',
  'development_gates.csv',
  'bootstrap_analysis.csv',
  'repeated_metrics.csv',
  'reproduction_audit.csv',
  'risk_solver_audit.csv',
  'control_comparison.csv',
  'beta_alpha_attribution.csv',
  'forecast_metrics.csv',
  'forecast_annual_metrics.csv',
  'forecast_loss_bootstrap.csv',
  'forecast_training_audit.csv'],
 'qlib_docs_reference': ['https://qlib.readthedocs.io/en/latest/component/data.html',
  'https://qlib.readthedocs.io/en/latest/component/workflow.html'],
 'artifact_policy': {'policy': 'slim_card_recorder_first',
  'workflow_config': 'workflow.yaml',
  'recorder_only_artifacts': ['inputs/*.pkl',
   'models/*.pkl',
   'policy/*.pkl',
   'analysis/portfolio_replays.pkl',
   'analysis/daily_solver_audits.pkl',
   'portfolio_analysis/*.pkl']},
 'limitations': ['Reviewed historical data is not new forward evidence; family14does not correct all adaptive research.',
  'Annual B scale cancels with common moment calibration; conditional time-varying variance ratios remain. This is normalized variance timing.',
  'Prior-centered squared returns are a conditional second-moment proxy, not observed true conditional variance.',
  'H5planning ignores future trades; actual daily costs, realized risk and qualification gates remain binding.',
  'Published-affine price basis and16secondary quotes retain documented source uncertainty.']}

In [2]:
import pandas as pd
from IPython.display import display,Markdown
CARD=ROOT/'research/conditional_variance_20261002'
display(pd.read_csv(CARD/'backtest_benchmark_comparison.csv'))
display(pd.read_csv(CARD/'development_gates.csv'))
display(Markdown((CARD/'conclusion.md').read_text()))

,cost_bps,sessions,start_signal,last_exit,terminal_wealth,return_pct,cagr_pct,annualized_log_volatility_pct,max_drawdown_pct,qlib_max_drawdown_without_initial_mark_pct,...,annualized_log_excess,annualized_relative_return_pct,relative_max_drawdown_pct,up_day_conditional_relative_return_pct,down_day_conditional_relative_return_pct,conditional_returns_are_noncontiguous_statistics,risk_policy,annualization_sessions,variant,segment
0,10.0,1762,2016-01-04,2023-01-04,3.504039,250.403889,19.642055,29.504918,-45.428550,-45.428550,...,-0.027854,-2.747005,-20.353299,-39.901816,36.943196,True,reported against benchmark; no implicit fixed ...,252,expanding_variance_control,development
1,25.0,1762,2016-01-04,2023-01-04,3.417331,241.733143,19.214081,29.504757,-45.648403,-45.648403,...,-0.031224,-3.074136,-21.489363,-40.722369,35.607704,True,reported against benchmark; no implicit fixed ...,252,expanding_variance_control,development
2,10.0,1762,2016-01-04,2023-01-04,3.031187,203.118732,17.187131,24.434365,-36.287533,-36.287533,...,-0.048587,-4.742530,-38.712491,-91.828503,771.260593,True,reported against benchmark; no implicit fixed ...,252,observed_open20,development
3,25.0,1762,2016-01-04,2023-01-04,2.904201,190.420130,16.472060,24.433544,-36.562458,-36.562458,...,-0.054493,-5.303510,-40.841540,-92.026668,756.797187,True,reported against benchmark; no implicit fixed ...,252,observed_open20,development
4,10.0,1762,2016-01-04,2023-01-04,2.783358,178.335831,15.766249,24.518776,-34.898199,-34.898199,...,-0.060786,-5.897517,-46.737636,-91.577292,676.162634,True,reported against benchmark; no implicit fixed ...,252,observed_close20,development
5,25.0,1762,2016-01-04,2023-01-04,2.667406,166.740564,15.063865,24.520157,-35.165334,-35.165334,...,-0.066657,-6.448429,-48.537718,-91.773350,662.702719,True,reported against benchmark; no implicit fixed ...,252,observed_close20,development
6,10.0,1762,2016-01-04,2023-01-04,2.809568,180.956831,15.921534,23.856906,-36.265317,-36.265317,...,-0.059445,-5.771291,-42.903172,-92.315223,758.694579,True,reported against benchmark; no implicit fixed ...,252,learned_vol5,development
7,25.0,1762,2016-01-04,2023-01-04,2.627836,162.783606,14.818177,23.857742,-36.583918,-36.583918,...,-0.068795,-6.648183,-46.065385,-92.598219,735.112886,True,reported against benchmark; no implicit fixed ...,252,learned_vol5,development
8,10.0,934,2023-01-03,2026-09-25,3.527292,252.729209,40.508851,32.428512,-41.623691,-41.623691,...,-0.093123,-8.891859,-29.890733,-70.993338,144.122076,True,reported against benchmark; no implicit fixed ...,252,expanding_variance_control_annual_refit,reused_diagnostic
9,25.0,934,2023-01-03,2026-09-25,3.473103,247.310345,39.923151,32.428942,-41.791734,-41.791734,...,-0.096896,-9.234974,-30.823504,-71.235611,143.187784,True,reported against benchmark; no implicit fixed ...,252,expanding_variance_control_annual_refit,reused_diagnostic
10,10.0,934,2023-01-03,2026-09-25,3.455478,245.547774,39.731206,31.767983,-40.988196,-40.988196,...,-0.098673,-9.396096,-31.680618,-74.785833,175.122972,True,reported against benchmark; no implicit fixed ...,252,expanding_variance_control_frozen2022_calibration,reused_diagnostic
11,25.0,934,2023-01-03,2026-09-25,3.402972,240.297250,39.155148,31.768425,-41.156334,-41.156334,...,-0.102400,-9.733160,-32.580477,-74.994004,174.084279,True,reported against benchmark; no implicit fixed ...,252,expanding_variance_control_frozen2022_calibration,reused_diagnostic

,cost_bps,aggregate_positive_net_log_excess,minimum_positive_signal_years,median_annual_log_excess_positive,leave_any_one_year_out_log_excess_positive,anchored_max_drawdown_not_worse_than_soxx,cvar5_not_worse_than_soxx,all_repeats_positive_at_both_costs,stationary_block_20_lower_bound_positive,stationary_block_60_lower_bound_positive,...,positive_repeats_at_this_cost,repeats_positive_at_both_costs,repeat_evidence_complete,largest_positive_year_share,minimum_leave_one_year_out_log_excess,all_three_fresh_runs_match,all_convex_solutions_verified,measurable_log_excess_above_numerical_tolerance,no_invalid_estimator_fallbacks,variant
0,10.0,False,False,False,False,True,True,False,False,False,...,0,0,True,0.745839,-0.215157,True,True,False,True,expanding_variance_control
1,25.0,False,False,False,False,True,True,False,False,False,...,0,0,True,0.760898,-0.233479,True,True,False,True,expanding_variance_control
2,10.0,False,False,False,False,True,True,False,False,False,...,0,0,True,0.511882,-0.451600,True,True,False,True,observed_open20
3,25.0,False,False,False,False,True,True,False,False,False,...,0,0,True,0.506886,-0.485654,True,True,False,True,observed_open20
4,10.0,False,False,False,False,True,True,False,False,False,...,0,0,True,0.656451,-0.572824,True,True,False,True,observed_close20
5,25.0,False,False,False,False,True,True,False,False,False,...,0,0,True,0.667965,-0.608554,True,True,False,True,observed_close20
6,10.0,False,False,False,False,True,True,False,False,False,...,0,0,True,1.000000,-0.506359,True,True,False,True,learned_vol5
7,25.0,False,False,False,False,True,True,False,False,False,...,0,0,True,1.000000,-0.565162,True,True,False,True,learned_vol5

# 条件波动比较结论

完成4组对照、3次独立重拟合/重算及10/25bp实际费用路径。历史资格通过=False；稳定超额目标仍在进行。

统一使用合格Qlib价格口径、同一H5先前均值、共同成熟日期及风险形状。学习预测与开盘/收盘20日对照分开，检验条件波动信息而不是调高风险预算。

开发期2016–2022信号年，10bp：
- expanding_variance_control：收益250.40%，相对SOXX终值0.8230，MaxDD-45.43%，CVaR5-4.21%。
- observed_open20：收益203.12%，相对SOXX终值0.7120，MaxDD-36.29%，CVaR5-3.62%。
- observed_close20：收益178.34%，相对SOXX终值0.6538，MaxDD-34.90%，CVaR5-3.63%。
- learned_vol5：收益180.96%，相对SOXX终值0.6599，MaxDD-36.27%，CVaR5-3.46%。

学习版本记账路径相对两个20日观察对照、两档费用均有正增量=False；估计与求解完整性通过=True。正点估计或回退路径本身不能证明学到了alpha。预测损失、各年差异及费用压力分别保留，三次复现不增加统计样本。

推广决定：continue_research_no_historical_qualification。2023以后已看过的诊断期未参与排名；数据敏感性及新的前向证据尚未完成。

风险包括波动预测误差、归一化校准的跨年变化、H5规划与日重配差异、交易成本及报价来源不确定性。下一步依据失败门和相对对照的信息增量继续研究；没有切换原SIM或提交真实委托。
Qlib Recorder：9a447c33dc934baeb1d4c3f2b9bf2122。

# 条件波动比较结论

完成4组对照、3次独立重拟合/重算及10/25bp实际费用路径。历史资格通过=False；稳定超额目标仍在进行。

统一使用合格Qlib价格口径、同一H5先前均值、共同成熟日期及风险形状。学习预测与开盘/收盘20日对照分开，检验条件波动信息而不是调高风险预算。

开发期2016–2022信号年，10bp：
- expanding_variance_control：收益250.40%，相对SOXX终值0.8230，MaxDD-45.43%，CVaR5-4.21%。
- observed_open20：收益203.12%，相对SOXX终值0.7120，MaxDD-36.29%，CVaR5-3.62%。
- observed_close20：收益178.34%，相对SOXX终值0.6538，MaxDD-34.90%，CVaR5-3.63%。
- learned_vol5：收益180.96%，相对SOXX终值0.6599，MaxDD-36.27%，CVaR5-3.46%。

学习版本记账路径相对两个20日观察对照、两档费用均有正增量=False；估计与求解完整性通过=True。正点估计或回退路径本身不能证明学到了alpha。预测损失、各年差异及费用压力分别保留，三次复现不增加统计样本。

推广决定：continue_research_no_historical_qualification。2023以后已看过的诊断期未参与排名；数据敏感性及新的前向证据尚未完成。

风险包括波动预测误差、归一化校准的跨年变化、H5规划与日重配差异、交易成本及报价来源不确定性。下一步依据失败门和相对对照的信息增量继续研究；没有切换原SIM或提交真实委托。
Qlib Recorder：9a447c33dc934baeb1d4c3f2b9bf2122。

经独立审计，36条费用/复现路径、53,496次决策均通过数值、费用与风险验证，无回退；原生两档费用对账通过。93项针对性测试通过；全套910通过、139个原有失败，失败集合未增加。

本轮学习波动版本10/25bp相对SOXX终值为0.6599/0.6182，只有1/7开发年份正超额。平均约30.35%SOXL、69.65%现金，SOXX几乎未使用；实际回归beta约0.728。QLIKE相对open20改善有正区间下界，相对同样看到收盘的close20区间仍跨零。相对open20，费前目标路径本身更弱且换手更高，不能把失败全部归咎于费用。

独立均值诊断不支持“H5均值把SOXL排到SOXX前面”的解释：2016–2023全部8个cutoff，H5、5倍日均值及日均值复合，单位估计风险的毛收益均以SOXX更高。58个固定决策点的费用诊断进一步表明：同输入的毛收益最优权重虽更高，但按原换仓费重新评价，五日净目标全部不如原选择。2016初次入场10bp案例，原约34.15%SOXL的预期五日毛增长25.507bp、费用3.414bp；全SOXX毛增长26.367bp、费用9.990bp。短规划窗口偏好较低入场费并延续已有仓位，是可核验机制；它不证明任何较长期限就会改善实际收益。

下一步单独登记能精确保留SOXX基准、以连续持仓后完整净收益训练的方案，验证成本时序与可行基准问题；不搜索一个看起来更漂亮的固定规划天数。整体稳定超额目标继续，当前没有候选达到部署资格。