# Hierarchical SOXX excess with explicit prior

`base_constrained_ref` 是显式仓位先验和独立基准，不进入模型特征矩阵。

In [1]:
from pathlib import Path
import sys
repo_root = Path.cwd().parents[1]
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))
from src.workflow.hierarchical_soxx_excess_prior_overlay import run_hierarchical_soxx_excess_prior_overlay_card
summary = run_hierarchical_soxx_excess_prior_overlay_card(root=repo_root)
summary['promotion_decision']

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[86142:MainThread](2026-07-23 16:16:51,041) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[86142:MainThread](2026-07-23 16:16:51,440) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[86142:MainThread](2026-07-23 16:16:51,441) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[86142:MainThread](2026-07-23 16:16:51,461) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[86142:MainThread](2026-07-23 16:16:51,462) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[86142:MainThread](2026-07-23 16:16:51,462) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[86142:MainThread](2026-07-23 16:16:51,720) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[86142:MainThread](2026-07-23 16:16:51,721) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[86142:MainThread](2026-07-23 16:16:51,722) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

[86142:MainThread](2026-07-23 16:16:51,821) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[86142:MainThread](2026-07-23 16:16:51,822) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[86142:MainThread](2026-07-23 16:16:51,823) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[86142:MainThread](2026-07-23 16:16:52,437) INFO - qlib.workflow - [exp.py:258] - Experiment 480760990960530270 starts running ...

[86142:MainThread](2026-07-23 16:16:52,486) INFO - qlib.workflow - [recorder.py:345] - Recorder f1754867293b4f57a5bbe4a68fe1f459 starts running under Experiment 480760990960530270 ...

[86142:MainThread](2026-07-23 16:16:52,606) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

'validated_research_goal_passed_explicit_prior_overlay'

In [2]:
import pandas as pd
card = Path.cwd()
pd.read_csv(card / 'backtest_benchmark_comparison.csv')

,segment,candidate,cost_bps,selection_uses_outer_test,return_pct,cagr_pct,annualized_vol_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,...,max_drawdown_recovery_days,soxx_max_drawdown_pct,soxx_longest_underwater_days,soxx_max_drawdown_recovery_days,downside_avg_cash_weight_pct,downside_min_cash_weight_pct,hazard_days,cash_entry_days,prior_active_days,turnover
0,development_walk_forward,prior_balanced,10,False,448.380520,27.556616,36.792657,-46.978766,-11.659827,-5.275922,...,56,-47.374011,257,56,11.514851,10.0,126,30,1314,84.460567
1,development_walk_forward,prior_balanced,25,False,383.160444,25.267459,36.793227,-47.870663,-11.659827,-5.282785,...,56,-47.374011,257,56,11.514851,10.0,126,30,1314,84.460567
2,outer_diagnostic,prior_balanced,10,False,769.307126,86.681617,40.746172,-42.256310,-11.241603,-5.514757,...,63,-42.790391,297,113,15.625000,10.0,94,35,768,50.182200
3,outer_diagnostic,prior_balanced,25,False,706.297057,82.670611,40.755546,-43.334952,-11.241603,-5.523046,...,67,-42.790391,297,113,15.625000,10.0,94,35,768,50.182200

In [3]:
pd.read_csv(card / 'prior_incremental_attribution.csv')

,segment,variant,base_constrained_ref_hidden_feature,selection_uses_outer_test,return_pct,cagr_pct,annualized_vol_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,...,max_drawdown_recovery_days,soxx_max_drawdown_pct,soxx_longest_underwater_days,soxx_max_drawdown_recovery_days,downside_avg_cash_weight_pct,downside_min_cash_weight_pct,hazard_days,cash_entry_days,prior_active_days,turnover
0,development_walk_forward,selected_model_plus_explicit_prior,False,False,448.380520,27.556616,36.792657,-46.978766,-11.659827,-5.275922,...,56,-47.374011,257,56,11.514851,10.0,126,30,1314,84.460567
1,development_walk_forward,model_only_same_cash_gate,False,False,379.049429,25.114463,34.864150,-45.345962,-11.659827,-5.017104,...,56,-47.374011,257,56,11.514851,10.0,126,30,1314,63.720000
2,development_walk_forward,explicit_prior_only_same_cash_gate,False,False,335.152858,23.406520,29.301114,-43.472983,-9.203057,-4.240101,...,56,-47.374011,257,56,11.514851,10.0,126,30,1314,42.928492
3,development_walk_forward,model_plus_prior_no_extra_cash,False,False,447.931019,27.541657,37.139908,-48.379724,-11.659827,-5.337730,...,56,-47.374011,257,56,10.000000,10.0,126,0,1314,67.000905
4,outer_diagnostic,selected_model_plus_explicit_prior,False,False,769.307126,86.681617,40.746172,-42.256310,-11.241603,-5.514757,...,63,-42.790391,297,113,15.625000,10.0,94,35,768,50.182200
5,outer_diagnostic,model_only_same_cash_gate,False,False,513.884741,68.845303,36.428811,-40.471162,-11.241603,-5.018119,...,60,-42.790391,297,113,15.625000,10.0,94,35,768,38.250000
6,outer_diagnostic,explicit_prior_only_same_cash_gate,False,False,565.276988,72.809547,36.359469,-36.638148,-7.926008,-5.041856,...,109,-42.790391,297,113,15.625000,10.0,94,35,768,30.113899
7,outer_diagnostic,model_plus_prior_no_extra_cash,False,False,742.234355,84.984477,41.576873,-47.737789,-11.887501,-5.685124,...,111,-42.790391,297,113,10.000000,10.0,94,0,768,36.153517

In [4]:
pd.read_csv(card / 'regime_metrics.csv')

,regime,rows,return_pct,soxx_return_pct,terminal_wealth_ratio_vs_soxx,avg_soxl_weight_pct,avg_cash_weight_pct
0,all,2635,4667.110932,2204.640579,2.068483,14.008710,11.110057
1,downtrend,753,448.103841,273.498487,1.467486,11.571261,12.868526
2,prior_active,2082,4377.581638,2217.268181,1.932267,14.435616,10.497118
3,hazard_active,220,186.441817,156.452656,1.116938,9.824528,23.295455

# 显式先验 SOXX 超额策略结论

- 跑了什么：从 hierarchical_soxx_excess_walk_forward_v1 的 qlib recorder 读取年度 OOS 三头预测，把旧 base_constrained_ref 作为独立加法先验，而不是模型特征；仅用 2016–2022 选择五个预定义 profile。
- 开发期：10bp 终值/SOXX=1.2841，25bp=1.1331；MaxDD=-46.98% vs SOXX -47.37%；最长水下 252 vs 257 天。
- Outer 诊断：10bp 终值/SOXX=1.6142；MaxDD=-42.26% vs -42.79%；最长水下 247 vs 297 天；回撤恢复 63 vs 113 天。
- 下跌区间现金：outer 平均 15.63%，最低 10.00%。
- 决定：validated_research_goal_passed_explicit_prior_overlay；这是研究目标通过，不等同于未观察数据上的生产晋升。
- 风险：增量同时依赖模型收益头与显式规则先验；必须持续分别报告 model-only、prior-only 和 blend，不能重新把先验塞回特征矩阵。
- 下一步：进入 paper target-position 观察期，只允许新到数据做前向验证，不再用 2023+ 历史选择参数。