# PIT constituent auxiliary training allocation

成分股与2x标签只参与训练；推理仍只依赖SOXL/SOXX。

In [1]:
from pathlib import Path
import sys
import qlib
from qlib.data import D
from qlib.data.dataset import DatasetH
from qlib.workflow import R
repo_root = Path.cwd().parents[1]
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))
qlib.init(provider_uri=str(repo_root / 'data/qlib/soxl'), region='us', kernels=1, skip_if_reg=False)
calendar = D.calendar(start_time='2011-01-03', end_time='2026-07-02', freq='day')
from src.workflow import run_pit_constituent_auxiliary_training_allocation_card
summary = run_pit_constituent_auxiliary_training_allocation_card(root=repo_root)
summary['promotion_decision']

[73364:MainThread](2026-07-24 09:43:49,586) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[73364:MainThread](2026-07-24 09:43:49,587) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[73364:MainThread](2026-07-24 09:43:49,587) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[73364:MainThread](2026-07-24 09:43:50,932) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[73364:MainThread](2026-07-24 09:43:50,933) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[73364:MainThread](2026-07-24 09:43:50,933) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[73364:MainThread](2026-07-24 09:43:50,956) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[73364:MainThread](2026-07-24 09:43:50,957) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[73364:MainThread](2026-07-24 09:43:50,957) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[73364:MainThread](2026-07-24 09:43:51,219) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[73364:MainThread](2026-07-24 09:43:51,220) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[73364:MainThread](2026-07-24 09:43:51,220) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

[73364:MainThread](2026-07-24 09:43:51,316) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[73364:MainThread](2026-07-24 09:43:51,316) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[73364:MainThread](2026-07-24 09:43:51,316) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[73364:MainThread](2026-07-24 09:43:51,321) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[73364:MainThread](2026-07-24 09:43:51,322) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[73364:MainThread](2026-07-24 09:43:51,323) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[73364:MainThread](2026-07-24 09:43:51,341) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[73364:MainThread](2026-07-24 09:43:51,342) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[73364:MainThread](2026-07-24 09:43:51,343) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxx_pit_leveraged_training_v1')}

[73364:MainThread](2026-07-24 09:43:52,021) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[73364:MainThread](2026-07-24 09:43:52,021) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[73364:MainThread](2026-07-24 09:43:52,021) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[73364:MainThread](2026-07-24 09:44:10,551) INFO - qlib.workflow - [exp.py:258] - Experiment 157306831391018414 starts running ...

[73364:MainThread](2026-07-24 09:44:10,734) INFO - qlib.workflow - [recorder.py:345] - Recorder 3144ec23c3ee4478b6b1e699fb8203d3 starts running under Experiment 157306831391018414 ...

[73364:MainThread](2026-07-24 09:44:10,850) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

'not_promoted_pit_auxiliary_training_gates_failed'

In [2]:
import pandas as pd
card = Path.cwd()
pd.read_csv(card / 'model_selection.csv')

,segment,candidate,cost_bps,selection_uses_outer_test,return_pct,cagr_pct,annualized_vol_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,...,worst_5d_gate,cash_gate,capture_gate,relative_gate_count,risk_gate_count,relative_objective_pass,all_gate,selection_score,selected,selection_policy
0,development_walk_forward,primary_only,10,False,391.477056,25.573589,37.129835,-48.554616,-12.395221,-5.338706,...,False,True,False,2,2,False,False,0.391811,False,diagnostic_fallback_relative_gate_count_then_s...
1,development_walk_forward,pit_only_aux_005,10,False,446.497300,27.493875,36.468944,-48.370613,-12.424681,-5.224798,...,False,True,False,4,2,True,False,0.536500,True,development_relative_gates_then_score
2,development_walk_forward,pit_plus_union_aux_003,10,False,384.594369,25.320561,36.505201,-51.033137,-12.469202,-5.321641,...,False,True,False,1,2,False,False,0.334331,False,diagnostic_fallback_relative_gate_count_then_s...
3,development_walk_forward,pit_plus_union_aux_005,10,False,402.948784,25.988654,36.835385,-49.180020,-12.245893,-5.312810,...,False,True,False,2,2,False,False,0.345809,False,diagnostic_fallback_relative_gate_count_then_s...
4,development_walk_forward,pit_plus_union_aux_008,10,False,438.308567,27.218884,36.928045,-49.852529,-12.471060,-5.328803,...,False,True,False,4,2,True,False,0.479784,False,development_relative_gates_then_score

In [3]:
pd.read_csv(card / 'actual_2x_calibration.csv')

,product,underlying,observations,start_date,end_date,daily_rank_correlation,tracking_residual_mean_bps,tracking_residual_rmse_bps
0,NVDL,NVDA,614,2024-01-22,2026-07-02,0.999408,-5.087769,19.299169
1,AMDL,AMD,574,2024-03-19,2026-07-02,0.999563,-4.575493,18.814573
2,MULL,MU,408,2024-11-13,2026-07-02,0.998917,-6.334652,30.954779
3,INTW,INTC,346,2025-02-14,2026-07-02,0.999302,-4.486147,25.434938
4,MVLL,MRVL,331,2025-03-10,2026-07-02,0.998614,-6.593127,32.215322

In [4]:
pd.read_csv(card / 'backtest_walk_forward_metrics.csv')

,fold_year,segment,candidate,cost_bps,selection_uses_outer_test,return_pct,cagr_pct,annualized_vol_pct,max_drawdown_pct,worst_day_pct,...,terminal_wealth,terminal_wealth_ratio_vs_soxx,soxx_terminal_wealth,soxx_return_pct,avg_cash_weight_pct,min_cash_weight_pct,max_cash_weight_pct,zero_cash_days,avg_soxl_weight_pct,avg_soxx_weight_pct
0,2016,development_walk_forward,primary_only,10,False,46.077544,46.077544,23.946900,-14.602559,-4.708363,...,1.460775,1.041581,1.402460,40.246030,46.144384,19.875743,90.751251,0,21.177438,32.678177
1,2017,development_walk_forward,primary_only,10,False,33.208544,33.360810,20.099908,-13.810387,-7.845988,...,1.332085,0.927318,1.436492,43.649187,50.028198,16.037642,97.597320,0,19.462823,30.508979
2,2018,development_walk_forward,primary_only,10,False,-8.683203,-8.716245,31.827566,-27.017078,-7.058978,...,0.913168,1.025431,0.890521,-10.947863,34.897142,15.742432,92.701359,0,21.672917,43.429942
3,2019,development_walk_forward,primary_only,10,False,71.005145,71.005145,30.272548,-21.208793,-4.923678,...,1.710051,1.030408,1.659586,65.958602,26.275641,16.947384,90.442846,0,24.909535,48.814824
4,2020,development_walk_forward,primary_only,10,False,60.529360,60.229326,49.577542,-45.378711,-12.395221,...,1.605294,1.061637,1.512093,51.209284,28.783092,17.945771,79.123077,0,23.717371,47.499537
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,2026,outer_diagnostic,pit_only_aux_005,10,False,136.964733,503.021821,64.108042,-19.386798,-9.382462,...,2.369647,1.232034,1.923363,92.336260,20.655170,15.985473,29.573934,0,29.589323,49.755507
74,2023,outer_diagnostic,pit_only_aux_005,25,False,62.335076,62.965498,39.044063,-24.498806,-6.307653,...,1.623351,1.037762,1.564280,56.427971,23.801615,17.425291,62.997819,0,28.018627,48.179757
75,2024,outer_diagnostic,pit_only_aux_005,25,False,30.968366,30.968366,37.929275,-32.997891,-11.218521,...,1.309684,1.084357,1.207797,20.779705,36.798773,18.277438,91.675095,0,22.777646,40.423581
76,2025,outer_diagnostic,pit_only_aux_005,25,False,56.241189,56.799943,47.495246,-38.039182,-10.821911,...,1.562412,1.055839,1.479783,47.978263,31.343546,17.372419,93.361209,0,24.874464,43.781990
77,2026,outer_diagnostic,pit_only_aux_005,25,False,136.722466,501.738548,64.105316,-19.416907,-9.382462,...,2.367225,1.230774,1.923363,92.336260,20.655170,15.985473,29.573934,0,29.589323,49.755507

In [5]:
pd.read_csv(card / 'objective_gate_audit.csv')

,gate,required,passed,evidence
0,development_20pct_excess_10bps,True,True,1.2796526213704555
1,development_25bps_cost_stress,True,True,1.1596419358822558
2,development_positive_relative_years,True,True,6
3,outer_20pct_excess_10bps,True,True,1.4995829768963345
4,outer_25bps_cost_stress,True,True,1.4623331422583015
5,outer_three_of_four_positive_years,True,True,4
6,max_drawdown_minus_20pct,True,False,-48.26408101776889
7,worst_day_minus_12pct,True,True,-11.21852149805987
8,cvar5_minus_8pct,True,True,-6.291979286111673
9,worst_rolling_5d_minus_12pct,True,False,-19.909771746154213
10,average_cash_15pct,True,True,29.277040792273546
11,upside_capture_60pct,True,False,41.83386386857026
12,outer_not_used_for_selection,True,True,development_2016_2022_only

# 结论

- what_ran: 成分股与合成2x标签只进入训练辅助头；开发期和outer推理均只使用原有SOXL/SOXX数据，仓位由一个网络直接输出。
- key_metrics: 开发期选择 `pit_only_aux_005`，10bp相对SOXX=1.2797，25bp=1.1596，正超额年份=6/7；outer 10bp=1.4996，MaxDD=-48.26%。
- regime_window: SEC filing_date 后使用PIT成员；更早历史并非PIT，只在单独候选中以0.25权重作为预训练样本。
- promotion_decision: `not_promoted_pit_auxiliary_training_gates_failed`；相对目标通过=True，完整风险门=False。
- risks: 失败门为 max_drawdown_minus_20pct, worst_rolling_5d_minus_12pct, upside_capture_60pct；实际单股2x历史太短，只用于校准合成标签，不伪造早期可交易历史。
- next_action: 若20%相对门通过但风险门失败，应保留辅助训练头，把研究目标转为可预测的现金风险期限；不再扩大pooled权重。
- recorder: `b1a3761aa6b8412a9547712a6e17059c`。