# Cash-Floor Benchmark-Relative Walk-Forward v1

冻结结构：SOXS 仅作特征；风险仓固定 30% SOXL / 70% SOXX；两个 Ridge 头分别预测五日现金优势与未来波动，模型只控制 10%–60% 现金。2016–2022 为逐年开发 walk-forward，2023–2026 outer 只诊断。

In [1]:
from pathlib import Path
import json
import sys
repo = Path.cwd().resolve()
if repo.name == 'cash_floor_benchmark_relative_walk_forward_v1':
    repo = repo.parents[1]
sys.path.insert(0, repo.as_posix())
import pandas as pd
import qlib
from qlib.data import D
from qlib.data.dataset import DatasetH
from qlib.data.dataset.handler import DataHandlerLP
from qlib.workflow import R
from src.workflow.cash_floor_benchmark_relative_wf import run_cash_floor_benchmark_relative_card

provider = repo / 'data' / 'qlib' / 'soxl_soxx_soxs'
qlib.init(provider_uri=provider.as_posix(), region='us', kernels=1)
calendar = D.calendar(start_time='2011-01-03', end_time='2026-07-21', freq='day')
summary = run_cash_floor_benchmark_relative_card(root=repo)
recorder = R.get_recorder(recorder_id=summary['recorder_id'], experiment_name=summary['experiment'])
{'calendar_rows': len(calendar), 'recorder_id': recorder.id, 'decision': summary['promotion_decision']}

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[57005:MainThread](2026-07-22 21:11:06,253) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[57005:MainThread](2026-07-22 21:11:06,255) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[57005:MainThread](2026-07-22 21:11:06,255) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[57005:MainThread](2026-07-22 21:11:06,261) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[57005:MainThread](2026-07-22 21:11:06,262) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[57005:MainThread](2026-07-22 21:11:06,262) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[57005:MainThread](2026-07-22 21:11:06,291) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[57005:MainThread](2026-07-22 21:11:06,292) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[57005:MainThread](2026-07-22 21:11:06,292) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[57005:MainThread](2026-07-22 21:11:06,876) INFO - qlib.workflow - [exp.py:258] - Experiment 496757848563496074 starts running ...

[57005:MainThread](2026-07-22 21:11:06,945) INFO - qlib.workflow - [recorder.py:345] - Recorder 17dafd78c96048aa9d9861a527b714c4 starts running under Experiment 496757848563496074 ...

[57005:MainThread](2026-07-22 21:11:07,078) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

{'calendar_rows': 3909,
 'recorder_id': '17dafd78c96048aa9d9861a527b714c4',
 'decision': 'needs_iteration_relative_wealth'}

In [2]:
card = repo / 'research' / summary['experiment']
selection = pd.read_csv(card / 'model_selection.csv')
comparison = pd.read_csv(card / 'backtest_benchmark_comparison.csv')
display(selection)
display(comparison[['segment', 'strategy', 'cost_bps', 'return_pct', 'terminal_wealth_ratio_vs_soxx', 'max_drawdown_pct', 'worst_rolling_5d_pct', 'avg_cash_weight_pct']])

,model,selected,selection_policy,all_development_gates_pass,passed_gate_count,total_gate_count,promotion_decision,selection_uses_outer_test
0,two_head_fixed_ridge,True,fixed_by_requirements_no_candidate_search,False,9,15,needs_iteration_relative_wealth,False

,segment,strategy,cost_bps,return_pct,terminal_wealth_ratio_vs_soxx,max_drawdown_pct,worst_rolling_5d_pct,avg_cash_weight_pct
0,development_walk_forward,dynamic_cash_floor,10,268.103697,0.861934,-37.394429,-14.981995,38.522826
1,development_walk_forward,soxx_buyhold,10,327.066917,1.000000,-47.374011,-17.254933,0.000000
2,development_walk_forward,matched_static,10,278.549274,0.886393,-47.560399,-20.028295,38.522826
3,development_walk_forward,no_cash_30soxl_70soxx,10,531.108826,1.477775,-67.378441,-31.128007,0.000000
4,development_walk_forward,cash_only,10,0.000000,0.234155,0.000000,0.000000,100.000000
5,development_walk_forward,dynamic_cash_floor,25,212.795552,0.733566,-37.937744,-15.046905,38.522826
6,development_walk_forward,soxx_buyhold,25,326.404047,1.000000,-47.374011,-17.254933,0.000000
7,development_walk_forward,matched_static,25,278.189024,0.886926,-47.560399,-20.028295,38.522826
8,development_walk_forward,no_cash_30soxl_70soxx,25,530.111895,1.477734,-67.378441,-31.128007,0.000000
9,development_walk_forward,cash_only,25,0.000000,0.234519,0.000000,0.000000,100.000000
10,outer_diagnostic,dynamic_cash_floor,10,297.115227,0.806167,-40.726366,-12.708500,43.900795
11,outer_diagnostic,soxx_buyhold,10,392.596534,1.000000,-42.790391,-17.688154,0.000000
12,outer_diagnostic,matched_static,10,292.783094,0.797373,-40.673884,-16.093932,43.900795
13,outer_diagnostic,no_cash_30soxl_70soxx,10,783.674055,1.793910,-62.953848,-27.539506,0.000000
14,outer_diagnostic,cash_only,10,0.000000,0.203006,0.000000,0.000000,100.000000
15,outer_diagnostic,dynamic_cash_floor,25,263.777237,0.739603,-41.603737,-12.784501,43.900795
16,outer_diagnostic,soxx_buyhold,25,391.854403,1.000000,-42.790391,-17.688154,0.000000
17,outer_diagnostic,matched_static,25,292.451496,0.797902,-40.673884,-16.093932,43.900795
18,outer_diagnostic,no_cash_30soxl_70soxx,25,782.340836,1.793907,-62.953848,-27.539506,0.000000
19,outer_diagnostic,cash_only,25,0.000000,0.203312,0.000000,0.000000,100.000000

In [3]:
folds = pd.read_csv(card / 'backtest_walk_forward_metrics.csv')
development = folds.query("segment == 'development_walk_forward' and strategy == 'dynamic_cash_floor' and cost_bps == 10")
display(development[['fold_year', 'return_pct', 'soxx_return_pct', 'terminal_wealth_ratio_vs_soxx', 'max_drawdown_pct', 'avg_cash_weight_pct']])
display(pd.Series(summary['gate_evaluation']['gates'], name='pass'))

,fold_year,return_pct,soxx_return_pct,terminal_wealth_ratio_vs_soxx,max_drawdown_pct,avg_cash_weight_pct
0,2016,41.728741,40.246030,1.010572,-13.214330,33.447573
1,2017,58.692217,43.649187,1.104721,-11.772923,26.585127
2,2018,-22.826611,-10.947863,0.866609,-32.249487,32.542994
3,2019,61.254099,65.958602,0.971653,-14.726177,36.643501
4,2020,48.590691,51.209284,0.982682,-30.212645,45.577490
5,2021,25.946272,48.347037,0.848998,-15.706524,37.796391
6,2022,-29.724917,-36.055863,1.099007,-36.172148,57.041097

relative_wealth_10bps                   False
relative_wealth_25bps                   False
positive_fold_count                     False
median_fold_ratio                       False
bootstrap_outperformance_probability    False
minimum_daily_cash                       True
average_cash                             True
zero_cash_days                           True
timing_value_vs_matched_static          False
maxdd_vs_soxx                            True
worst5_vs_soxx                           True
maxdd_vs_matched_static                  True
worst5_vs_matched_static                 True
maxdd_improvement_vs_no_cash             True
worst5_improvement_vs_no_cash            True
Name: pass, dtype: bool

## 最终中文结论

- 做了什么：通过 qlib DatasetH/DataHandlerLP、两个固定 Ridge 头和 recorder，完成 2016–2022 年度 expanding walk-forward 与 10/25bp 回测。
- 核心指标：以执行输出、`backtest_benchmark_comparison.csv`、`backtest_walk_forward_metrics.csv` 和 recorder 明细为准。
- Regime/区间差异：2016–2022 是开发 OOS 拼接；2023–2026 是已观察 outer，仅报告、不选型。
- 是否晋升：必须由 `summary.json.promotion_decision` 决定；本研究卡不能直接晋升 production。
- 风险：双头最大值映射可能导致长期高现金和高换手；现金按零收益处理；SOXS 只作特征。
- 下一步：若相对收益失败，只能在开发期内部重构现金聚合/平滑，禁止使用 outer 回调。