# Holdings-aware PIT allocation

成分股与2x标签只参与训练；推理仍只依赖SOXL/SOXX。

In [1]:
from pathlib import Path
import sys
import qlib
from qlib.data import D
from qlib.data.dataset import DatasetH
from qlib.workflow import R
repo_root = Path.cwd().parents[1]
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))
qlib.init(provider_uri=str(repo_root / 'data/qlib/soxl'), region='us', kernels=1, skip_if_reg=False)
calendar = D.calendar(start_time='2011-01-03', end_time='2026-08-05', freq='day')
from src.workflow import run_holdings_aware_pit_allocation_card
summary = run_holdings_aware_pit_allocation_card(root=repo_root)
summary['promotion_decision']

[90569:MainThread](2026-08-10 12:59:11,201) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[90569:MainThread](2026-08-10 12:59:11,203) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[90569:MainThread](2026-08-10 12:59:11,204) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[90569:MainThread](2026-08-10 12:59:13,531) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[90569:MainThread](2026-08-10 12:59:13,534) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[90569:MainThread](2026-08-10 12:59:13,534) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[90569:MainThread](2026-08-10 12:59:13,568) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[90569:MainThread](2026-08-10 12:59:13,570) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[90569:MainThread](2026-08-10 12:59:13,571) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[90569:MainThread](2026-08-10 12:59:13,906) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[90569:MainThread](2026-08-10 12:59:13,908) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[90569:MainThread](2026-08-10 12:59:13,909) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

[90569:MainThread](2026-08-10 12:59:14,082) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[90569:MainThread](2026-08-10 12:59:14,083) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[90569:MainThread](2026-08-10 12:59:14,084) INFO - qlib.timer - [log.py:127] - Time cost: 0.002s | Init data Done

[90569:MainThread](2026-08-10 12:59:14,093) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[90569:MainThread](2026-08-10 12:59:14,095) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[90569:MainThread](2026-08-10 12:59:14,096) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[90569:MainThread](2026-08-10 12:59:14,125) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[90569:MainThread](2026-08-10 12:59:14,127) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[90569:MainThread](2026-08-10 12:59:14,128) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxx_pit_leveraged_training_v1')}

[90569:MainThread](2026-08-10 12:59:15,396) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[90569:MainThread](2026-08-10 12:59:15,397) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[90569:MainThread](2026-08-10 12:59:15,397) INFO - qlib.timer - [log.py:127] - Time cost: 0.002s | Init data Done

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[90569:MainThread](2026-08-10 12:59:46,185) INFO - qlib.workflow - [exp.py:258] - Experiment 272897056299425375 starts running ...

[90569:MainThread](2026-08-10 12:59:46,315) INFO - qlib.workflow - [recorder.py:345] - Recorder 77a5c2bb26f34fe0bf6e19d45f15a2a5 starts running under Experiment 272897056299425375 ...

[90569:MainThread](2026-08-10 12:59:47,546) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

[90569:MainThread](2026-08-10 12:59:47,600) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[90569:MainThread](2026-08-10 12:59:47,610) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[90569:MainThread](2026-08-10 12:59:47,611) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[90569:MainThread](2026-08-10 12:59:47,646) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[90569:MainThread](2026-08-10 12:59:47,649) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[90569:MainThread](2026-08-10 12:59:47,651) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[90569:MainThread](2026-08-10 12:59:48,233) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[90569:MainThread](2026-08-10 12:59:48,236) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[90569:MainThread](2026-08-10 12:59:48,237) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

[90569:MainThread](2026-08-10 12:59:48,375) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[90569:MainThread](2026-08-10 12:59:48,378) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[90569:MainThread](2026-08-10 12:59:48,379) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[90569:MainThread](2026-08-10 12:59:48,454) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[90569:MainThread](2026-08-10 12:59:48,458) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[90569:MainThread](2026-08-10 12:59:48,459) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

'not_promoted_pit_auxiliary_training_gates_failed'

In [2]:
import pandas as pd
card = Path.cwd()
pd.read_csv(card / 'model_selection.csv')

,segment,candidate,cost_bps,selection_uses_outer_test,return_pct,cagr_pct,annualized_vol_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,...,relative_objective_pass,all_gate,research_maxdd_gate,research_worst_5d_gate,research_relative_preservation_gate,research_gate_count,research_target_pass,selection_score,selected,selection_policy
0,development_walk_forward,primary_only,10,False,348.734018,23.950136,36.698848,-50.930585,-12.152373,-5.316740,...,False,False,True,False,False,1,False,0.154918,False,diagnostic_fallback_relative_gate_count_then_s...
1,development_walk_forward,pit_holdings_event_0000,10,False,413.418916,26.360457,36.746773,-51.705944,-12.489969,-5.309456,...,False,False,True,False,True,2,False,0.372680,False,diagnostic_fallback_relative_gate_count_then_s...
2,development_walk_forward,pit_holdings_event_0005,10,False,410.650227,26.262775,39.756808,-57.694836,-13.011411,-5.683528,...,False,False,True,False,True,2,False,0.523079,True,diagnostic_fallback_relative_gate_count_then_s...
3,development_walk_forward,pit_holdings_event_0015,10,False,329.060759,23.157934,36.947373,-55.345054,-11.901134,-5.307771,...,False,False,True,False,True,2,False,0.313513,False,diagnostic_fallback_relative_gate_count_then_s...

In [3]:
pd.read_csv(card / 'actual_2x_calibration.csv')

,product,underlying,observations,start_date,end_date,daily_rank_correlation,tracking_residual_mean_bps,tracking_residual_rmse_bps
0,NVDL,NVDA,614,2024-01-22,2026-07-02,0.999408,-5.087769,19.299169
1,AMDL,AMD,574,2024-03-19,2026-07-02,0.999563,-4.575493,18.814573
2,MULL,MU,408,2024-11-13,2026-07-02,0.998917,-6.334652,30.954779
3,INTW,INTC,346,2025-02-14,2026-07-02,0.999302,-4.486147,25.434938
4,MVLL,MRVL,331,2025-03-10,2026-07-02,0.998614,-6.593127,32.215322

In [4]:
pd.read_csv(card / 'backtest_walk_forward_metrics.csv')

,fold_year,segment,candidate,cost_bps,selection_uses_outer_test,return_pct,cagr_pct,annualized_vol_pct,max_drawdown_pct,worst_day_pct,...,terminal_wealth,terminal_wealth_ratio_vs_soxx,soxx_terminal_wealth,soxx_return_pct,avg_cash_weight_pct,min_cash_weight_pct,max_cash_weight_pct,zero_cash_days,avg_soxl_weight_pct,avg_soxx_weight_pct
0,2016,development_walk_forward,primary_only,10,False,46.032622,46.032622,25.358418,-16.260684,-4.996509,...,1.460326,1.041259,1.402462,40.246203,40.889081,17.549864,87.442875,0,22.874304,36.236614
1,2017,development_walk_forward,primary_only,10,False,32.588792,32.737883,17.858702,-11.655147,-5.285143,...,1.325888,0.923003,1.436493,43.649303,54.102961,19.335251,97.976424,0,17.101923,28.795116
2,2018,development_walk_forward,primary_only,10,False,-11.194122,-11.236115,33.087797,-30.165723,-7.185274,...,0.888059,0.997236,0.890520,-10.947968,37.836701,14.854819,95.712266,0,22.622747,39.540552
3,2019,development_walk_forward,primary_only,10,False,75.103944,75.103944,31.456310,-23.272475,-4.933211,...,1.751039,1.055106,1.659587,65.958703,24.967863,16.120978,85.810121,0,26.262051,48.770087
4,2020,development_walk_forward,primary_only,10,False,63.194018,62.878404,48.401664,-43.369070,-12.152373,...,1.631940,1.079259,1.512093,51.209344,31.646709,17.863896,85.748855,0,24.033157,44.320133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,2026,outer_diagnostic,pit_holdings_event_0005,10,False,68.232781,148.509842,67.346787,-32.665082,-9.139154,...,1.682328,1.095573,1.535569,53.556854,25.635616,21.459282,35.368440,0,29.970940,44.393444
60,2023,outer_diagnostic,pit_holdings_event_0005,25,False,66.514005,67.194648,38.457405,-23.366434,-6.359356,...,1.665140,1.064477,1.564280,56.428007,25.868101,21.692533,46.577840,0,28.441799,45.690100
61,2024,outer_diagnostic,pit_holdings_event_0005,25,False,26.777669,26.777669,38.041727,-32.040222,-10.297055,...,1.267777,1.049660,1.207797,20.779696,32.482621,22.446409,64.914455,0,23.794560,43.722819
62,2025,outer_diagnostic,pit_holdings_event_0005,25,False,57.626063,58.200937,47.608823,-39.507877,-9.530396,...,1.576261,1.065197,1.479783,47.978315,29.589879,22.045737,61.860758,0,26.002516,44.407606
63,2026,outer_diagnostic,pit_holdings_event_0005,25,False,67.704861,147.146741,67.348451,-32.730373,-9.145192,...,1.677049,1.092135,1.535569,53.556854,25.635616,21.459282,35.368440,0,29.970940,44.393444

In [5]:
pd.read_csv(card / 'objective_gate_audit.csv')

,gate,required,passed,evidence
0,development_20pct_excess_10bps,True,False,1.1957136277277522
1,development_25bps_cost_stress,True,True,1.1571080999075267
2,development_positive_relative_years,True,True,5
3,outer_20pct_excess_10bps,True,True,1.3237225690008554
4,outer_25bps_cost_stress,True,True,1.2998447296974318
5,outer_three_of_four_positive_years,True,True,4
6,max_drawdown_minus_20pct,True,False,-48.70714222168644
7,worst_day_minus_12pct,True,True,-10.293576877072649
8,cvar5_minus_8pct,True,True,-6.5441848718283095
9,worst_rolling_5d_minus_12pct,True,False,-18.67806929133594
10,average_cash_15pct,True,True,28.729513496044806
11,upside_capture_60pct,True,False,42.156579036843326
12,outer_not_used_for_selection,True,True,development_2016_2022_only
13,development_research_maxdrawdown_target,False,True,-57.694835808080704
14,outer_research_maxdrawdown_target,False,True,-48.70714222168644
15,outer_research_worst_5d_target,False,False,-18.67806929133594
16,outer_research_relative_preservation,False,True,1.3237225690008554
17,development_trade_day_reduction,True,True,0.4667847652790079
18,development_terminal_wealth_retention,True,True,1.1379797533732954

# 结论

- what_ran: 修正训练、平滑与回测的换手口径，统一按实际盘前持仓计真实订单，并以 qlib DatasetH 年度 walk-forward 比较 4 个预注册候选。
- key_metrics: `pit_holdings_event_0005` 裸模型开发期交易日 602/1762，减少 46.68%，终值为同批基线 113.80%；但 MaxDD=-57.69%、worst-5d=-28.34%。
- controller_integration: 接回冻结 Stage1 后交易日减少 35.70%，但终值仅保留 38.27%，MaxDD 恶化至 -39.61%，不能替换当前策略。
- regime_window: 2016–2022 用于选择；2023–2026 只做复用诊断，不参与选参。
- promotion_decision: `not_promoted_pit_auxiliary_training_gates_failed`；生产 Stage1、Futu SIMULATE 和当前调度均不切换。
- risks: 裸模型风险过高，Stage1 集成后的收益保留与风险门失败；outer 不用于调参。
- next_action: 保留冻结预测器，单独训练 `HOLD / REBALANCE / DE-RISK` 动作层；降风险立即，加风险需新信号与冷却确认。
- recorder: `77a5c2bb26f34fe0bf6e19d45f15a2a5`。