# Taleb fragility feature allocation

固定同一tabular多任务直接仓位模型，仅消融经验尾部、隐含尾部和结构脆弱度特征。

In [1]:
from pathlib import Path
import sys
import qlib
from qlib.data import D
from qlib.workflow import R
repo_root = Path.cwd().parents[1]
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))
qlib.init(provider_uri=str(repo_root / 'data/qlib/soxl'), region='us', kernels=1, skip_if_reg=False)
calendar = D.calendar(start_time='2011-01-03', end_time='2026-07-02', freq='day')
from src.workflow.taleb_fragility_allocation import run_taleb_fragility_allocation_card
summary = run_taleb_fragility_allocation_card(root=repo_root)
summary['promotion_decision']

[40599:MainThread](2026-07-23 22:00:37,171) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[40599:MainThread](2026-07-23 22:00:37,172) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[40599:MainThread](2026-07-23 22:00:37,172) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[40599:MainThread](2026-07-23 22:00:38,423) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[40599:MainThread](2026-07-23 22:00:38,424) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[40599:MainThread](2026-07-23 22:00:38,424) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[40599:MainThread](2026-07-23 22:00:38,447) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[40599:MainThread](2026-07-23 22:00:38,448) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[40599:MainThread](2026-07-23 22:00:38,449) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[40599:MainThread](2026-07-23 22:00:38,714) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[40599:MainThread](2026-07-23 22:00:38,715) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[40599:MainThread](2026-07-23 22:00:38,715) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

[40599:MainThread](2026-07-23 22:00:38,815) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[40599:MainThread](2026-07-23 22:00:38,815) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[40599:MainThread](2026-07-23 22:00:38,816) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[40599:MainThread](2026-07-23 22:00:39,171) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[40599:MainThread](2026-07-23 22:00:39,171) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[40599:MainThread](2026-07-23 22:00:39,172) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/taleb_fragility_v1')}

[40599:MainThread](2026-07-23 22:00:39,178) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[40599:MainThread](2026-07-23 22:00:39,178) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[40599:MainThread](2026-07-23 22:00:39,179) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/taleb_fragility_v1')}

[40599:MainThread](2026-07-23 22:00:39,182) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[40599:MainThread](2026-07-23 22:00:39,183) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[40599:MainThread](2026-07-23 22:00:39,183) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/taleb_fragility_v1')}

[40599:MainThread](2026-07-23 22:00:39,214) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[40599:MainThread](2026-07-23 22:00:39,214) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[40599:MainThread](2026-07-23 22:00:39,215) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/taleb_fragility_v1')}

[40599:MainThread](2026-07-23 22:00:39,246) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[40599:MainThread](2026-07-23 22:00:39,247) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[40599:MainThread](2026-07-23 22:00:39,247) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[40599:MainThread](2026-07-23 22:01:14,997) INFO - qlib.workflow - [exp.py:258] - Experiment 744895744531263738 starts running ...

[40599:MainThread](2026-07-23 22:01:15,053) INFO - qlib.workflow - [recorder.py:345] - Recorder 7c974fdde16d46bfb024b9d4afa8a711 starts running under Experiment 744895744531263738 ...

[40599:MainThread](2026-07-23 22:01:15,201) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

'not_promoted_taleb_features_or_risk_gates_failed'

In [2]:
import pandas as pd
card = Path.cwd()
pd.read_csv(card / 'model_selection.csv')

,segment,candidate,cost_bps,selection_uses_outer_test,return_pct,cagr_pct,annualized_vol_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,...,cvar_gate,worst_5d_gate,cash_gate,activity_gate,learnability_gate,gate_count,all_gate,selection_score,diagnostic_selected,selection_policy
0,development_walk_forward,tabular_base_multitask,10,False,273.472416,20.738010,36.215746,-43.293303,-10.129028,-5.377789,...,True,False,True,True,False,4,False,-0.085000,True,diagnostic_only_maximum_gate_count_then_score
1,development_walk_forward,tabular_base_empirical_tail,10,False,177.578838,15.721167,35.098783,-48.269227,-11.644136,-5.393480,...,True,False,False,True,False,3,False,-0.587626,False,diagnostic_only_maximum_gate_count_then_score
2,development_walk_forward,tabular_base_implied_tail,10,False,229.861498,18.612764,36.684204,-46.528935,-12.266817,-5.509148,...,True,False,True,True,False,3,False,-0.340255,False,diagnostic_only_maximum_gate_count_then_score
3,development_walk_forward,tabular_base_structural_fragility,10,False,144.572680,13.644869,36.137654,-52.427528,-14.113644,-5.479275,...,True,False,False,True,False,2,False,-0.866735,False,diagnostic_only_maximum_gate_count_then_score
4,development_walk_forward,tabular_base_all_taleb,10,False,258.825503,20.049131,35.517242,-51.070629,-13.944363,-5.389290,...,True,False,False,True,False,2,False,-0.362737,False,diagnostic_only_maximum_gate_count_then_score

In [3]:
pd.read_csv(card / 'classification_summary.csv')

,candidate,task,mean_roc_auc,mean_average_precision,mean_brier,mean_positive_rate,years_auc_above_055,summary_segment
0,tabular_base_all_taleb,recovery_label,0.627040,0.340981,0.294121,0.221329,5,development_walk_forward
1,tabular_base_all_taleb,relative_alpha_label,0.577367,0.598544,0.373103,0.498099,3,development_walk_forward
2,tabular_base_all_taleb,tail_1d_label,0.521119,0.107097,0.185399,0.077758,4,development_walk_forward
3,tabular_base_all_taleb,tail_3d_label,0.488697,0.167836,0.235081,0.118086,1,development_walk_forward
4,tabular_base_all_taleb,tail_5d_label,0.502099,0.230065,0.314536,0.188472,2,development_walk_forward
5,tabular_base_empirical_tail,recovery_label,0.583906,0.350412,0.321376,0.221329,6,development_walk_forward
6,tabular_base_empirical_tail,relative_alpha_label,0.566136,0.581277,0.368880,0.498099,5,development_walk_forward
7,tabular_base_empirical_tail,tail_1d_label,0.538388,0.111839,0.217908,0.077758,4,development_walk_forward
8,tabular_base_empirical_tail,tail_3d_label,0.507611,0.154229,0.247419,0.118086,3,development_walk_forward
9,tabular_base_empirical_tail,tail_5d_label,0.462410,0.210433,0.327344,0.188472,3,development_walk_forward
10,tabular_base_implied_tail,recovery_label,0.565837,0.315666,0.338826,0.221329,5,development_walk_forward
11,tabular_base_implied_tail,relative_alpha_label,0.558523,0.574545,0.336583,0.498099,2,development_walk_forward
12,tabular_base_implied_tail,tail_1d_label,0.506504,0.091882,0.174560,0.077758,1,development_walk_forward
13,tabular_base_implied_tail,tail_3d_label,0.499439,0.130238,0.193294,0.118086,2,development_walk_forward
14,tabular_base_implied_tail,tail_5d_label,0.502142,0.214005,0.269996,0.188472,2,development_walk_forward
15,tabular_base_multitask,recovery_label,0.627493,0.403421,0.314496,0.221329,6,development_walk_forward
16,tabular_base_multitask,relative_alpha_label,0.596825,0.600750,0.311523,0.498099,4,development_walk_forward
17,tabular_base_multitask,tail_1d_label,0.507638,0.093990,0.171284,0.077758,2,development_walk_forward
18,tabular_base_multitask,tail_3d_label,0.519383,0.150601,0.207043,0.118086,4,development_walk_forward
19,tabular_base_multitask,tail_5d_label,0.517558,0.226362,0.278699,0.188472,3,development_walk_forward
20,tabular_base_structural_fragility,recovery_label,0.516458,0.270623,0.365497,0.221329,4,development_walk_forward
21,tabular_base_structural_fragility,relative_alpha_label,0.545367,0.548527,0.363909,0.498099,4,development_walk_forward
22,tabular_base_structural_fragility,tail_1d_label,0.539446,0.110620,0.164997,0.077758,2,development_walk_forward
23,tabular_base_structural_fragility,tail_3d_label,0.498563,0.135639,0.217133,0.118086,1,development_walk_forward
24,tabular_base_structural_fragility,tail_5d_label,0.481236,0.199903,0.300769,0.188472,1,development_walk_forward
25,tabular_base_all_taleb,recovery_label,0.534380,0.384809,0.337876,0.245116,2,outer_diagnostic
26,tabular_base_all_taleb,relative_alpha_label,0.558082,0.612934,0.344593,0.557295,3,outer_diagnostic
27,tabular_base_all_taleb,tail_1d_label,0.489799,0.120404,0.311332,0.098569,1,outer_diagnostic
28,tabular_base_all_taleb,tail_3d_label,0.479338,0.156857,0.334187,0.135183,0,outer_diagnostic
29,tabular_base_all_taleb,tail_5d_label,0.484855,0.245722,0.419553,0.221318,0,outer_diagnostic
30,tabular_base_empirical_tail,recovery_label,0.517210,0.304793,0.338746,0.245116,1,outer_diagnostic
31,tabular_base_empirical_tail,relative_alpha_label,0.513253,0.589389,0.356598,0.557295,2,outer_diagnostic
32,tabular_base_empirical_tail,tail_1d_label,0.488680,0.107136,0.284516,0.098569,1,outer_diagnostic
33,tabular_base_empirical_tail,tail_3d_label,0.525966,0.168581,0.295035,0.135183,2,outer_diagnostic
34,tabular_base_empirical_tail,tail_5d_label,0.524829,0.259098,0.357094,0.221318,1,outer_diagnostic
35,tabular_base_implied_tail,recovery_label,0.544120,0.330651,0.287079,0.245116,3,outer_diagnostic
36,tabular_base_implied_tail,relative_alpha_label,0.524039,0.594343,0.334117,0.557295,2,outer_diagnostic
37,tabular_base_implied_tail,tail_1d_label,0.540267,0.142494,0.284797,0.098569,1,outer_diagnostic
38,tabular_base_implied_tail,tail_3d_label,0.547868,0.178126,0.297708,0.135183,3,outer_diagnostic
39,tabular_base_implied_tail,tail_5d_label,0.552786,0.275738,0.349804,0.221318,3,outer_diagnostic
40,tabular_base_multitask,recovery_label,0.490216,0.297696,0.366779,0.245116,0,outer_diagnostic
41,tabular_base_multitask,relative_alpha_label,0.499600,0.576281,0.306672,0.557295,1,outer_diagnostic
42,tabular_base_multitask,tail_1d_label,0.523045,0.122483,0.253001,0.098569,1,outer_diagnostic
43,tabular_base_multitask,tail_3d_label,0.517087,0.177995,0.280605,0.135183,1,outer_diagnostic
44,tabular_base_multitask,tail_5d_label,0.499003,0.270943,0.348966,0.221318,1,outer_diagnostic
45,tabular_base_structural_fragility,recovery_label,0.499393,0.291906,0.321392,0.245116,1,outer_diagnostic
46,tabular_base_structural_fragility,relative_alpha_label,0.447743,0.544687,0.404168,0.557295,0,outer_diagnostic
47,tabular_base_structural_fragility,tail_1d_label,0.543741,0.121353,0.323800,0.098569,2,outer_diagnostic
48,tabular_base_structural_fragility,tail_3d_label,0.540052,0.157497,0.360465,0.135183,2,outer_diagnostic
49,tabular_base_structural_fragility,tail_5d_label,0.545114,0.245188,0.400235,0.221318,2,outer_diagnostic

In [4]:
pd.read_csv(card / 'continuous_tail_summary.csv')

,candidate,feature_set,target,mean_pinball_skill,median_pinball_skill,positive_skill_years,mean_spearman,mean_predicted_tail_actual
0,tabular_base_all_taleb,base_all_taleb,soxl_future_adverse_5d,-0.066000,-0.131961,2,0.014921,-0.047056
1,tabular_base_all_taleb,base_all_taleb,soxx_future_adverse_5d,-0.069313,-0.132589,3,-0.002486,-0.014818
2,tabular_base_empirical_tail,base_empirical,soxl_future_adverse_5d,-0.049117,-0.071281,2,0.011727,-0.061062
3,tabular_base_empirical_tail,base_empirical,soxx_future_adverse_5d,-0.048415,-0.100607,3,0.013846,-0.017189
4,tabular_base_implied_tail,base_implied,soxl_future_adverse_5d,-0.045446,-0.093223,3,0.019344,-0.051567
5,tabular_base_implied_tail,base_implied,soxx_future_adverse_5d,-0.055217,-0.084482,2,0.018523,-0.016105
6,tabular_base_multitask,base,soxl_future_adverse_5d,-0.057715,-0.085400,2,-0.003442,-0.049273
7,tabular_base_multitask,base,soxx_future_adverse_5d,-0.070761,-0.107302,2,0.019624,-0.016834
8,tabular_base_structural_fragility,base_structural,soxl_future_adverse_5d,-0.079535,-0.122706,2,0.003876,-0.052781
9,tabular_base_structural_fragility,base_structural,soxx_future_adverse_5d,-0.075194,-0.102300,2,0.005708,-0.016815

In [5]:
pd.read_csv(card / 'backtest_benchmark_comparison.csv')

,segment,candidate,cost_bps,selection_uses_outer_test,return_pct,cagr_pct,annualized_vol_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,...,avg_soxl_weight_pct,avg_soxx_weight_pct,longest_underwater_days,max_drawdown_recovery_days,soxx_max_drawdown_pct,soxx_longest_underwater_days,soxx_max_drawdown_recovery_days,downside_avg_cash_weight_pct,downside_min_cash_weight_pct,turnover
0,development_walk_forward,tabular_base_multitask,10,False,273.472416,20.738010,36.215746,-43.293303,-10.129028,-5.377789,...,14.888968,66.370969,281,56,-47.374011,257,56,18.886784,0.719886,243.087791
1,development_walk_forward,tabular_base_multitask,25,False,159.351140,14.602474,36.224078,-45.876064,-10.129974,-5.396724,...,14.888968,66.370969,355,56,-47.374011,257,56,18.886784,0.719886,243.087791
2,development_walk_forward,tabular_base_empirical_tail,10,False,177.578838,15.721167,35.098783,-48.269227,-11.644136,-5.393480,...,13.633686,62.974232,275,56,-47.374011,257,56,23.006970,0.528945,233.938915
3,development_walk_forward,tabular_base_empirical_tail,25,False,95.402659,10.054719,35.109191,-50.909673,-11.650065,-5.408011,...,13.633686,62.974232,335,56,-47.374011,257,56,23.006970,0.528945,233.938915
4,development_walk_forward,tabular_base_implied_tail,10,False,229.861498,18.612764,36.684204,-46.528935,-12.266817,-5.509148,...,13.942728,67.245991,275,56,-47.374011,257,56,19.630336,0.308552,240.850497
5,development_walk_forward,tabular_base_implied_tail,25,False,129.845878,12.639944,36.688869,-49.188389,-12.353547,-5.524897,...,13.942728,67.245991,289,56,-47.374011,257,56,19.630336,0.308552,240.850497
6,development_walk_forward,tabular_base_structural_fragility,10,False,144.572680,13.644869,36.137654,-52.427528,-14.113644,-5.479275,...,14.507078,65.755025,450,56,-47.374011,257,56,16.358660,0.611912,225.952667
7,development_walk_forward,tabular_base_structural_fragility,25,False,74.314647,8.271811,36.130287,-54.754803,-14.115085,-5.491784,...,14.507078,65.755025,687,56,-47.374011,257,56,16.358660,0.611912,225.952667
8,development_walk_forward,tabular_base_all_taleb,10,False,258.825503,20.049131,35.517242,-51.070629,-13.944363,-5.389290,...,12.934384,63.786661,256,56,-47.374011,257,56,18.959293,0.633570,226.106107
9,development_walk_forward,tabular_base_all_taleb,25,False,155.598747,14.363848,35.527306,-52.850448,-13.962212,-5.401955,...,12.934384,63.786661,256,56,-47.374011,257,56,18.959293,0.633570,226.106107
10,outer_diagnostic,tabular_base_multitask,10,False,288.697703,48.995361,38.174785,-54.921545,-13.882775,-5.676078,...,12.200990,59.525373,383,199,-42.790391,297,113,31.890841,0.691569,137.238234
11,outer_diagnostic,tabular_base_multitask,25,False,216.469719,40.265448,38.172874,-57.121941,-13.883324,-5.695584,...,12.200990,59.525373,398,214,-42.790391,297,113,31.890841,0.691569,137.238234
12,outer_diagnostic,tabular_base_empirical_tail,10,False,247.091689,44.122527,37.684055,-44.323865,-10.440201,-5.539344,...,11.295720,58.595773,304,120,-42.790391,297,113,31.577936,0.477831,141.567399
13,outer_diagnostic,tabular_base_empirical_tail,25,False,180.740551,35.416019,37.687735,-47.056694,-10.486437,-5.561682,...,11.295720,58.595773,379,195,-42.790391,297,113,31.577936,0.477831,141.567399
14,outer_diagnostic,tabular_base_implied_tail,10,False,422.164862,62.489246,36.815214,-39.313396,-13.001253,-5.231970,...,12.116245,59.068615,172,55,-42.790391,297,113,28.389817,0.431472,144.767761
15,outer_diagnostic,tabular_base_implied_tail,25,False,320.404382,52.466697,36.811192,-41.869974,-13.011859,-5.250824,...,12.116245,59.068615,251,67,-42.790391,297,113,28.389817,0.431472,144.767761
16,outer_diagnostic,tabular_base_structural_fragility,10,False,209.688550,39.375939,33.700254,-45.051484,-11.117068,-4.710747,...,10.649756,54.757517,372,188,-42.790391,297,113,30.371285,0.466052,157.745175
17,outer_diagnostic,tabular_base_structural_fragility,25,False,144.488259,30.027083,33.702568,-47.815270,-11.131645,-4.734423,...,10.649756,54.757517,383,199,-42.790391,297,113,30.371285,0.466052,157.745175
18,outer_diagnostic,tabular_base_all_taleb,10,False,290.178392,49.161838,37.649343,-53.475735,-13.309883,-5.754809,...,10.280921,54.859115,393,195,-42.790391,297,113,28.165580,0.509811,155.475797
19,outer_diagnostic,tabular_base_all_taleb,25,False,208.990727,39.283625,37.679963,-56.449929,-13.318342,-5.773231,...,10.280921,54.859115,449,251,-42.790391,297,113,28.165580,0.509811,155.475797

In [6]:
pd.read_csv(card / 'objective_gate_audit.csv')

,gate,required,passed,evidence
0,no_base_or_prior,True,True,none
1,no_candidate_weight_grid,True,True,none
2,outer_not_used_for_selection,True,True,development_2016_2022_only
3,development_return_gate,True,False,False
4,development_cost_gate,True,False,False
5,development_year_gate,True,False,False
6,development_maxdd_gate,True,False,False
7,development_worst_day_gate,True,True,True
8,development_cvar_gate,True,True,True
9,development_worst_5d_gate,True,False,False
10,development_cash_gate,True,True,True
11,development_activity_gate,True,True,True
12,development_learnability_gate,True,False,False
13,outer_ratio_above_soxx_report_only,False,False,0.7808842335418088
14,outer_maxdd_minus_20_report_only,False,False,-54.921545147239456

# Taleb肥尾与脆弱度特征结论

- 跑了什么：固定同一tabular多任务直接连续仓位模型，分别加入经验尾部、期权隐含尾部、结构脆弱度和全部Taleb特征；没有底仓、先验或仓位网格。
- 基准特征：开发期10bp财富/SOXX=0.8745，MaxDD=-43.29%，tail1 AUC=0.5076。
- 开发期诊断优胜：tabular_base_multitask；10bp财富/SOXX=0.8745，25bp=0.6082，MaxDD=-43.29%，tail1 AUC=0.5076。
- 连续尾部诊断最佳：tabular_base_implied_tail / soxl_future_adverse_5d，平均pinball skill=-0.0454，正skill年份=3/7。
- Outer仅诊断：10bp财富/SOXX=0.7809，MaxDD=-54.92%。
- 晋升决定：not_promoted_taleb_features_or_risk_gates_failed。
- 风险：Hill/ES等滚动尾部估计仍有参数不确定性；成分股回填和2024年才开始的外部15分钟数据均未参与选择；outer没有参与特征或模型选择。
- 下一步：只有开发期标签可学习性和风险收益同时改善，才保留对应特征族；否则停止日线尾部工程并转向真正PIT盘前或更长历史的期权截面。