# Stage1 coherent 价格重放（增量 1）

旧冻结 base forecast/selection 与 control 模型身份不变，仅换 coherent 价格 panel 重放（价格效应）；
再在同一 panel 训练费用一致候选（训练效应）。两效应分开报告，不合并。
首小时全部 EARLY_FIELDS 从 repaired 源统一重建；native prefix/suffix 连账并保存真实 reports/positions。

In [1]:
import sys, json, hashlib
from pathlib import Path

ROOT = Path.cwd()
while not (ROOT/'AGENTS.md').exists():
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))
CARD = ROOT/'research'/'stage1_coherent_price_replay_20261009'
print('plan sha256:', hashlib.sha256((CARD/'plan.json').read_bytes()).hexdigest())

plan sha256: 2e1026a0ff70387641e49b48bf21304fd0256cbc88b43d030f0b61d99225911f

In [2]:
from src.workflow import coherent_price_replay_experiment as workflow
summary = workflow.run_coherent_price_replay(root=ROOT, card_dir=CARD)
print('decision:', summary['decision'])
print('native status:', summary['native_reconciliation']['status'], 'boundary:', summary['native_reconciliation'].get('boundary'))
print('early repair:', summary.get('early_field_repair'))
print('recorder:', summary.get('recorder_id'), 'saved:', summary.get('saved_objects'))

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

2026/10/10 00:45:04 INFO mlflow.agent.hint: Load the `instrumenting-with-mlflow-tracing` skill at /Users/rziiiii/dev/workspace/qlib_venv/lib/python3.12/site-packages/mlflow/assistant/skills/instrumenting-with-mlflow-tracing/SKILL.md before writing any tracing code; it ships with this MLflow install. Set MLFLOW_DISABLE_AGENT_HINT=1 to silence this.

[76054:MainThread](2026-10-10 00:45:04,278) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:45:04,280) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:45:04,280) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[76054:MainThread](2026-10-10 00:45:04,336) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:45:04,337) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:45:04,338) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_coherent_daily_marks_20261009')}

[76054:MainThread](2026-10-10 00:45:04,349) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:45:04,349) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:45:04,350) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_repaired_intraday_20261009')}

[76054:MainThread](2026-10-10 00:45:08,811) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[76054:MainThread](2026-10-10 00:45:08,812) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[76054:MainThread](2026-10-10 00:45:08,812) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[76054:MainThread](2026-10-10 00:45:09,243) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[76054:MainThread](2026-10-10 00:45:09,244) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[76054:MainThread](2026-10-10 00:45:09,244) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[76054:MainThread](2026-10-10 00:45:09,670) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[76054:MainThread](2026-10-10 00:45:09,670) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[76054:MainThread](2026-10-10 00:45:09,671) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[76054:MainThread](2026-10-10 00:45:10,105) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[76054:MainThread](2026-10-10 00:45:10,105) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[76054:MainThread](2026-10-10 00:45:10,106) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[76054:MainThread](2026-10-10 00:45:10,679) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[76054:MainThread](2026-10-10 00:45:10,679) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[76054:MainThread](2026-10-10 00:45:10,679) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[76054:MainThread](2026-10-10 00:45:11,232) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[76054:MainThread](2026-10-10 00:45:11,232) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[76054:MainThread](2026-10-10 00:45:11,233) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[76054:MainThread](2026-10-10 00:45:12,011) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[76054:MainThread](2026-10-10 00:45:12,011) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[76054:MainThread](2026-10-10 00:45:12,012) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[76054:MainThread](2026-10-10 00:45:14,575) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[76054:MainThread](2026-10-10 00:45:14,576) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[76054:MainThread](2026-10-10 00:45:14,576) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[76054:MainThread](2026-10-10 00:45:15,004) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[76054:MainThread](2026-10-10 00:45:15,004) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[76054:MainThread](2026-10-10 00:45:15,004) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[76054:MainThread](2026-10-10 00:45:15,429) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[76054:MainThread](2026-10-10 00:45:15,430) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[76054:MainThread](2026-10-10 00:45:15,430) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[76054:MainThread](2026-10-10 00:45:15,868) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[76054:MainThread](2026-10-10 00:45:15,868) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[76054:MainThread](2026-10-10 00:45:15,868) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[76054:MainThread](2026-10-10 00:45:16,304) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[76054:MainThread](2026-10-10 00:45:16,304) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[76054:MainThread](2026-10-10 00:45:16,305) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[76054:MainThread](2026-10-10 00:45:16,863) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[76054:MainThread](2026-10-10 00:45:16,863) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[76054:MainThread](2026-10-10 00:45:16,863) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[76054:MainThread](2026-10-10 00:45:17,625) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[76054:MainThread](2026-10-10 00:45:17,626) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[76054:MainThread](2026-10-10 00:45:17,626) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

[76054:MainThread](2026-10-10 00:45:27,898) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:45:27,899) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:45:27,899) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_coherent_daily_marks_20261009')}

[76054:MainThread](2026-10-10 00:45:27,912) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:45:27,913) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:45:27,913) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_coherent_daily_marks_20261009')}

[76054:MainThread](2026-10-10 00:45:27,920) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:45:27,921) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:45:27,921) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_coherent_daily_marks_20261009')}

[76054:MainThread](2026-10-10 00:45:27,925) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[76054:MainThread](2026-10-10 00:45:27,929) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[76054:MainThread](2026-10-10 00:45:27,933) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[76054:MainThread](2026-10-10 00:45:27,933) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[76054:MainThread](2026-10-10 00:45:27,935) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x1233848c0>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[76054:MainThread](2026-10-10 00:45:28,363) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:45:28,364) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:45:28,364) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_execution_marks_20261009')}

[76054:MainThread](2026-10-10 00:45:28,439) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:45:28,440) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:45:28,440) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_execution_marks_20261009')}

[76054:MainThread](2026-10-10 00:45:28,483) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[76054:MainThread](2026-10-10 00:45:28,517) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[76054:MainThread](2026-10-10 00:45:28,693) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[76054:MainThread](2026-10-10 00:45:28,694) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[76054:MainThread](2026-10-10 00:45:28,722) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x1247ef110>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[76054:MainThread](2026-10-10 00:45:38,807) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:45:38,808) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:45:38,808) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_coherent_daily_marks_20261009')}

[76054:MainThread](2026-10-10 00:45:38,818) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:45:38,819) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:45:38,819) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_coherent_daily_marks_20261009')}

[76054:MainThread](2026-10-10 00:45:38,823) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[76054:MainThread](2026-10-10 00:45:38,830) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[76054:MainThread](2026-10-10 00:45:38,834) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[76054:MainThread](2026-10-10 00:45:38,834) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[76054:MainThread](2026-10-10 00:45:38,836) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x13de25c10>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[76054:MainThread](2026-10-10 00:45:39,291) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:45:39,292) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:45:39,292) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_execution_marks_20261009')}

[76054:MainThread](2026-10-10 00:45:39,368) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:45:39,369) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:45:39,369) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_execution_marks_20261009')}

[76054:MainThread](2026-10-10 00:45:39,412) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[76054:MainThread](2026-10-10 00:45:39,443) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[76054:MainThread](2026-10-10 00:45:39,531) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[76054:MainThread](2026-10-10 00:45:39,531) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[76054:MainThread](2026-10-10 00:45:39,560) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x123bdaba0>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[76054:MainThread](2026-10-10 00:45:49,424) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:45:49,425) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:45:49,425) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_coherent_daily_marks_20261009')}

[76054:MainThread](2026-10-10 00:45:49,435) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:45:49,436) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:45:49,436) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_coherent_daily_marks_20261009')}

[76054:MainThread](2026-10-10 00:45:49,440) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[76054:MainThread](2026-10-10 00:45:49,446) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[76054:MainThread](2026-10-10 00:45:49,451) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[76054:MainThread](2026-10-10 00:45:49,451) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[76054:MainThread](2026-10-10 00:45:49,453) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x149159e20>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[76054:MainThread](2026-10-10 00:45:49,889) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:45:49,890) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:45:49,890) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_execution_marks_20261009')}

[76054:MainThread](2026-10-10 00:45:49,969) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:45:49,970) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:45:49,970) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_execution_marks_20261009')}

[76054:MainThread](2026-10-10 00:45:50,347) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[76054:MainThread](2026-10-10 00:45:50,379) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[76054:MainThread](2026-10-10 00:45:50,472) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[76054:MainThread](2026-10-10 00:45:50,472) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[76054:MainThread](2026-10-10 00:45:50,503) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x140a7b2f0>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[76054:MainThread](2026-10-10 00:46:00,644) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:46:00,645) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:46:00,646) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_coherent_daily_marks_20261009')}

[76054:MainThread](2026-10-10 00:46:00,656) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:46:00,657) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:46:00,657) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_coherent_daily_marks_20261009')}

[76054:MainThread](2026-10-10 00:46:00,661) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[76054:MainThread](2026-10-10 00:46:00,667) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[76054:MainThread](2026-10-10 00:46:00,671) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[76054:MainThread](2026-10-10 00:46:00,672) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[76054:MainThread](2026-10-10 00:46:00,673) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x14ade2ba0>

backtest loop:   0%|          | 0/752 [00:00<?, ?it/s]

[76054:MainThread](2026-10-10 00:46:01,108) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:46:01,109) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:46:01,110) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_execution_marks_20261009')}

[76054:MainThread](2026-10-10 00:46:01,190) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:46:01,191) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:46:01,191) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_execution_marks_20261009')}

[76054:MainThread](2026-10-10 00:46:01,236) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[76054:MainThread](2026-10-10 00:46:01,268) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[76054:MainThread](2026-10-10 00:46:01,357) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[76054:MainThread](2026-10-10 00:46:01,357) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[76054:MainThread](2026-10-10 00:46:01,387) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x127aac3e0>

backtest loop:   0%|          | 0/26020 [00:00<?, ?it/s]

[76054:MainThread](2026-10-10 00:46:11,883) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:46:11,884) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:46:11,884) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_execution_marks_20261009')}

[76054:MainThread](2026-10-10 00:46:11,963) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:46:11,964) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:46:11,964) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_execution_marks_20261009')}

[76054:MainThread](2026-10-10 00:46:12,009) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[76054:MainThread](2026-10-10 00:46:12,041) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[76054:MainThread](2026-10-10 00:46:12,124) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[76054:MainThread](2026-10-10 00:46:12,124) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[76054:MainThread](2026-10-10 00:46:12,155) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x141295ac0>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[76054:MainThread](2026-10-10 00:46:22,302) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:46:22,303) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:46:22,303) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_execution_marks_20261009')}

[76054:MainThread](2026-10-10 00:46:22,382) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:46:22,383) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:46:22,383) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_execution_marks_20261009')}

[76054:MainThread](2026-10-10 00:46:22,429) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[76054:MainThread](2026-10-10 00:46:22,459) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[76054:MainThread](2026-10-10 00:46:22,544) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[76054:MainThread](2026-10-10 00:46:22,545) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[76054:MainThread](2026-10-10 00:46:22,575) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x12c04dd60>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[76054:MainThread](2026-10-10 00:46:31,992) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:46:31,993) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:46:31,993) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_execution_marks_20261009')}

[76054:MainThread](2026-10-10 00:46:32,587) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:46:32,588) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:46:32,588) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_execution_marks_20261009')}

[76054:MainThread](2026-10-10 00:46:32,634) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[76054:MainThread](2026-10-10 00:46:32,663) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[76054:MainThread](2026-10-10 00:46:32,749) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[76054:MainThread](2026-10-10 00:46:32,749) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[76054:MainThread](2026-10-10 00:46:32,779) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x142b8cfb0>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[76054:MainThread](2026-10-10 00:46:42,272) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:46:42,273) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:46:42,273) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_execution_marks_20261009')}

[76054:MainThread](2026-10-10 00:46:42,922) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:46:42,922) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:46:42,923) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/stage1_execution_marks_20261009')}

[76054:MainThread](2026-10-10 00:46:42,969) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[76054:MainThread](2026-10-10 00:46:42,998) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[76054:MainThread](2026-10-10 00:46:43,082) WARNING - qlib.data - [data.py:665] - load calendar error: freq=15min, future=True; return current calendar!

[76054:MainThread](2026-10-10 00:46:43,082) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[76054:MainThread](2026-10-10 00:46:43,112) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x12afaf350>

backtest loop:   0%|          | 0/24188 [00:00<?, ?it/s]

[76054:MainThread](2026-10-10 00:46:52,731) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[76054:MainThread](2026-10-10 00:46:52,732) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[76054:MainThread](2026-10-10 00:46:52,732) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[76054:MainThread](2026-10-10 00:46:52,734) WARNING - qlib.workflow - [expm.py:231] - No valid experiment found. Create a new experiment with name stage1_coherent_price_replay_20261009.

[76054:MainThread](2026-10-10 00:46:52,736) INFO - qlib.workflow - [exp.py:258] - Experiment 108283454878980817 starts running ...

[76054:MainThread](2026-10-10 00:46:52,811) INFO - qlib.workflow - [recorder.py:345] - Recorder 9775b262dfab496e947a433a18ab6c88 starts running under Experiment 108283454878980817 ...

[76054:MainThread](2026-10-10 00:46:54,248) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

decision: coherent_price_replay_reported
native status: passed boundary: 2018-12-31
early repair: {'source': '/Users/rziiiii/dev/workspace/data/qlib/stage1_repaired_intraday_20261009', 'repaired_sessions': 1944, 'repaired_from': '2018-12-31', 'prior_vintage_prefix_sessions': 752, 'fields': ['early_ret', 'early_range', 'early_from_low', 'early_volume', 'early_bar_count'], 'symbols': ['SOXL', 'SOXX'], 'note': 'all first-hour fields are rebuilt together from one repaired source in the covered region; the unmatched prefix carries no recovery'}
recorder: 9775b262dfab496e947a433a18ab6c88 saved: ['native', 'replays']

In [3]:
import pandas as pd
display(pd.read_csv(CARD/'coherent_replay_comparison.csv').round(3))
print('=== 价格效应 vs old daily ===')
display(pd.read_csv(CARD/'price_effect_delta.csv').round(3))
print('=== SOXX 基准 ===')
display(pd.read_csv(CARD/'soxx_benchmark.csv').round(3))
print('=== 门 ===')
display(pd.read_csv(CARD/'gate_results.csv'))

,family,segment,cost_bps,sessions,terminal_wealth,return_pct,max_drawdown_pct,cvar5_pct,worst_day_pct,worst_rolling_5d_pct,sharpe,total_turnover,open_trade_days
0,price_effect_control,development_walk_forward,10.0,1756,3.005,200.486,-29.028,-3.056,-7.461,-10.821,0.931,46.647,638
1,training_effect_candidate,development_walk_forward,10.0,1756,2.149,114.860,-30.866,-3.513,-9.495,-14.422,0.631,61.787,748
2,price_effect_control,development_walk_forward,25.0,1756,2.608,160.849,-30.179,-3.078,-8.259,-10.993,0.834,49.021,649
3,training_effect_candidate,development_walk_forward,25.0,1756,2.677,167.664,-30.009,-3.160,-7.528,-10.993,0.826,50.457,628
4,price_effect_control,outer_reused_diagnostic,10.0,934,4.628,362.793,-26.498,-4.765,-8.684,-14.553,1.438,44.805,559
5,training_effect_candidate,outer_reused_diagnostic,10.0,934,2.739,173.871,-31.274,-4.563,-9.625,-12.084,1.057,48.733,660
6,price_effect_control,outer_reused_diagnostic,25.0,934,4.246,324.612,-26.867,-4.693,-8.738,-14.634,1.382,41.689,538
7,training_effect_candidate,outer_reused_diagnostic,25.0,934,2.424,142.365,-28.004,-4.604,-8.678,-14.634,0.941,46.635,543

=== 价格效应 vs old daily ===

,segment,cost_bps,coherent_return_pct,old_daily_return_pct,return_delta_pct,coherent_max_drawdown_pct,old_daily_max_drawdown_pct,max_drawdown_delta_pct,coherent_cvar5_pct,old_daily_cvar5_pct,old_control_variant
0,development_walk_forward,10.0,200.486,200.489,-0.004,-29.028,-29.028,-0.000,-3.056,-3.056,own_state_net_value_frozen_2022
1,development_walk_forward,25.0,160.849,160.852,-0.003,-30.179,-30.179,-0.000,-3.078,-3.078,own_state_net_value_frozen_2022
2,outer_reused_diagnostic,10.0,362.793,362.837,-0.045,-26.498,-26.482,-0.016,-4.765,-4.766,own_state_net_value_frozen_2022
3,outer_reused_diagnostic,25.0,324.612,324.649,-0.037,-26.867,-26.851,-0.015,-4.693,-4.694,own_state_net_value_frozen_2022

=== SOXX 基准 ===

,benchmark,segment,sessions,gross_return_pct,gross_max_drawdown_pct,cost_model,net10_return_pct,net25_return_pct
0,SOXX_buy_hold_open_to_open,development_walk_forward,1756,320.698,-47.374,buy at first open and sell at last exit open; ...,319.857,318.597
1,SOXX_buy_hold_open_to_open,outer_reused_diagnostic,934,398.260,-42.790,buy at first open and sell at last exit open; ...,397.264,395.772

=== 门 ===

,candidate,segment,cost_bps,reference,return_above_control,max_drawdown_not_worse,worst_day_not_worse,cvar5_not_worse,worst_5d_not_worse,all_pass
0,training_effect_candidate,development_walk_forward,10.0,price_effect_control,False,False,False,False,False,False
1,training_effect_candidate,development_walk_forward,25.0,price_effect_control,True,True,True,False,True,False
2,training_effect_candidate,outer_reused_diagnostic,10.0,price_effect_control,False,False,False,True,True,False
3,training_effect_candidate,outer_reused_diagnostic,25.0,price_effect_control,False,False,True,True,True,False

In [4]:
for k, e in summary['native_reconciliation']['results'].items():
    pf = e.get('prefix') or {}
    sf = e.get('suffix') or {}
    print(f"{k:44s} prefix={pf.get('status')} suffix={sf.get('status')} inherited={e['prefix_inherited']}")

control_price::development_walk_forward::10  prefix=passed suffix=passed inherited=True
candidate_training::development_walk_forward::10 prefix=passed suffix=passed inherited=True
control_price::development_walk_forward::25  prefix=passed suffix=passed inherited=True
candidate_training::development_walk_forward::25 prefix=passed suffix=passed inherited=True
control_price::outer_reused_diagnostic::10   prefix=None suffix=passed inherited=False
candidate_training::outer_reused_diagnostic::10 prefix=None suffix=passed inherited=False
control_price::outer_reused_diagnostic::25   prefix=None suffix=passed inherited=False
candidate_training::outer_reused_diagnostic::25 prefix=None suffix=passed inherited=False

## 中文结论

In [5]:
from IPython.display import Markdown, display
display(Markdown((CARD/'conclusion.md').read_text()))

# Stage1 coherent 价格重放（增量 1，中文结论）
- 做了什么：冻结 base forecast/selection 与 control 动作模型（身份不变），仅在新 coherent 价格 panel 上重放（价格效应）；再在同一 panel 上训练费用一致候选（训练效应）；两者分开报告，不合并。
- coherent provider：`data/qlib/stage1_coherent_daily_marks_20261009`；intraday provider：`data/qlib/stage1_repaired_intraday_20261009`；execution mark provider：`data/qlib/stage1_execution_marks_20261009`。
- 首小时输入修复：全部 EARLY_FIELDS（ret/range/from-low/volume/bar_count × SOXL/SOXX）统一从 repaired 源重建；{'source': '/Users/rziiiii/dev/workspace/data/qlib/stage1_repaired_intraday_20261009', 'repaired_sessions': 1944, 'repaired_from': '2018-12-31', 'prior_vintage_prefix_sessions': 752, 'fields': ['early_ret', 'early_range', 'early_from_low', 'early_volume', 'early_bar_count'], 'symbols': ['SOXL', 'SOXX'], 'note': 'all first-hour fields are rebuilt together from one repaired source in the covered region; the unmatched prefix carries no recovery'}。
- price control 来源：`analysis/training_results.pkl` key=2022 的年度 models，直接读回不 refit；control parity=`passed`。
- 决定：`coherent_price_replay_reported`。
### 价格效应（同冻结模型、仅换价格；旧值为父 Recorder 精确对象指标）
- development_walk_forward @10bp：coherent 200.4859% vs old daily 200.4894%（Δ -0.0035pp），MaxDD -29.0278% vs -29.0277%（Δ -0.0001pp）
- development_walk_forward @25bp：coherent 160.8489% vs old daily 160.8518%（Δ -0.0029pp），MaxDD -30.1793% vs -30.1792%（Δ -0.0000pp）
- outer_reused_diagnostic @10bp：coherent 362.7927% vs old daily 362.8372%（Δ -0.0445pp），MaxDD -26.4977% vs -26.4822%（Δ -0.0155pp）
- outer_reused_diagnostic @25bp：coherent 324.6125% vs old daily 324.6494%（Δ -0.0369pp），MaxDD -26.8667% vs -26.8513%（Δ -0.0154pp）
（以上仅为这些已测路径上的影响幅度，不是普适结论。）
- 注意：本卡价格效应只测 economic control 路径；legacy/rules-only 的 state feedback 路径可能对 source vintage 明显更敏感，需单独核验。
### 训练效应（同 coherent panel 新候选项）
- development_walk_forward @10bp：114.86% / MaxDD -30.87%
- development_walk_forward @25bp：167.66% / MaxDD -30.01%
- outer_reused_diagnostic @10bp：173.87% / MaxDD -31.27%
- outer_reused_diagnostic @25bp：142.36% / MaxDD -28.00%
- native 对账：status=`passed`，boundary=`2018-12-31`；2016 prefix open-only、2018-12-31+ intraday 承接 prefix 末现金/股数；prefix 选择被承接但不重新验证。
- 门：候选须超过同价冻结 control；[{'candidate': 'training_effect_candidate', 'segment': 'development_walk_forward', 'cost_bps': 10.0, 'reference': 'price_effect_control', 'return_above_control': False, 'max_drawdown_not_worse': False, 'worst_day_not_worse': False, 'cvar5_not_worse': False, 'worst_5d_not_worse': False, 'all_pass': False}, {'candidate': 'training_effect_candidate', 'segment': 'development_walk_forward', 'cost_bps': 25.0, 'reference': 'price_effect_control', 'return_above_control': True, 'max_drawdown_not_worse': True, 'worst_day_not_worse': True, 'cvar5_not_worse': False, 'worst_5d_not_worse': True, 'all_pass': False}, {'candidate': 'training_effect_candidate', 'segment': 'outer_reused_diagnostic', 'cost_bps': 10.0, 'reference': 'price_effect_control', 'return_above_control': False, 'max_drawdown_not_worse': False, 'worst_day_not_worse': False, 'cvar5_not_worse': True, 'worst_5d_not_worse': True, 'all_pass': False}, {'candidate': 'training_effect_candidate', 'segment': 'outer_reused_diagnostic', 'cost_bps': 25.0, 'reference': 'price_effect_control', 'return_above_control': False, 'max_drawdown_not_worse': False, 'worst_day_not_worse': True, 'cvar5_not_worse': True, 'worst_5d_not_worse': True, 'all_pass': False}]
- 仅历史 opening/10:30 close 代理，不证明真实 09:31/10:31 成交；候选 not_promoted 直到独立 forward。
- 子 Recorder：9775b262dfab496e947a433a18ab6c88；保存真实 reports/positions/reconciliation/replays。