# Stage1 feature recovery ablation v2

假设：只给原 Stage1 recovery head 恢复绝对风险与滞后行业宽度，能否在不改合法仓位、控制器和 outer 边界的前提下提高超额并降低换手。

In [1]:
from pathlib import Path
import sys
root = Path.cwd().resolve()
while root != root.parent and not ((root / 'AGENTS.md').exists() and (root / 'SPEC.md').exists()):
    root = root.parent
sys.path.insert(0, str(root))
import qlib
from qlib.config import REG_US
from qlib.data import D
from qlib.data.dataset import DatasetH
from qlib.workflow import R
provider_uri = root / 'data' / 'qlib' / 'dynamic_soxx_soxl_cash_allocation_wf_v1'
qlib.init(provider_uri=str(provider_uri), region=REG_US, kernels=1)
calendar = D.calendar(freq='day')
from src.workflow.stage1_feature_recovery_ablation import run_stage1_feature_recovery_ablation_card
summary = run_stage1_feature_recovery_ablation_card(root=root)
{'calendar_end': str(calendar[-1]), 'recorder_id': summary['recorder_id'], 'decision': summary['decision']}

[44723:MainThread](2026-07-25 14:29:21,487) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[44723:MainThread](2026-07-25 14:29:21,488) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[44723:MainThread](2026-07-25 14:29:21,488) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[44723:MainThread](2026-07-25 14:29:22,933) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[44723:MainThread](2026-07-25 14:29:22,934) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[44723:MainThread](2026-07-25 14:29:22,935) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[44723:MainThread](2026-07-25 14:29:22,960) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[44723:MainThread](2026-07-25 14:29:22,960) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[44723:MainThread](2026-07-25 14:29:22,961) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[44723:MainThread](2026-07-25 14:29:23,231) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[44723:MainThread](2026-07-25 14:29:23,232) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[44723:MainThread](2026-07-25 14:29:23,232) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

[44723:MainThread](2026-07-25 14:29:23,337) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[44723:MainThread](2026-07-25 14:29:23,338) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[44723:MainThread](2026-07-25 14:29:23,338) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[44723:MainThread](2026-07-25 14:29:23,381) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[44723:MainThread](2026-07-25 14:29:23,382) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[44723:MainThread](2026-07-25 14:29:23,382) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

[44723:MainThread](2026-07-25 14:29:23,589) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[44723:MainThread](2026-07-25 14:29:23,590) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[44723:MainThread](2026-07-25 14:29:23,590) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

[44723:MainThread](2026-07-25 14:29:23,630) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[44723:MainThread](2026-07-25 14:29:23,631) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[44723:MainThread](2026-07-25 14:29:23,631) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[44723:MainThread](2026-07-25 14:30:07,815) INFO - qlib.workflow - [exp.py:258] - Experiment 281331975052886530 starts running ...

[44723:MainThread](2026-07-25 14:30:07,895) INFO - qlib.workflow - [recorder.py:345] - Recorder a76504862a15490982f4f80faea334e9 starts running under Experiment 281331975052886530 ...

[44723:MainThread](2026-07-25 14:30:08,037) INFO - qlib.timer - [log.py:127] - Time cost: 0.004s | waiting `async_log` Done

{'calendar_end': '2026-07-24 00:00:00',
 'recorder_id': 'a76504862a15490982f4f80faea334e9',
 'decision': 'rejected_feature_recovery_outer_generalization_failed'}

In [2]:
import pandas as pd
card = root / 'research' / 'stage1_feature_recovery_ablation_v2'
pd.read_csv(card / 'feature_ablation.csv')

,segment,selection_uses_outer_test,feature_set,feature_count,logistic_c,probability_threshold,action_beta,terminal_wealth,return_pct,max_drawdown_pct,...,open_turnover,intraday_turnover,recovery_action_count,avg_cash_weight_pct,development_gate_pass,neighbor_count,neighbor_min_wealth_ratio,neighbor_median_terminal_wealth,selection_eligible,selected
0,development_walk_forward,False,absolute_plus_breadth,32,0.10,0.7125,0.6,5.324489,432.448857,-28.868443,...,122.445326,8.377871,25,43.278769,True,5,0.988164,5.295000,True,True
1,development_walk_forward,False,absolute_risk,29,0.03,0.7375,0.8,5.225993,422.599264,-26.637898,...,117.358184,2.365970,6,43.625462,True,4,0.947914,5.131753,False,False
2,development_walk_forward,False,absolute_plus_normalized,33,0.10,0.7250,0.6,5.207466,420.746597,-26.885246,...,123.579699,9.039801,31,42.909924,True,5,0.926756,4.997097,False,False
3,development_walk_forward,False,baseline_stage1,21,0.03,0.5500,0.6,5.172721,417.272054,-27.488582,...,130.061349,15.878202,51,42.567010,True,1,1.000000,5.172721,False,False

In [3]:
pd.read_csv(card / 'risk_analysis.csv')

,variant,segment,cost_bps,terminal_wealth,return_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,worst_rolling_5d_pct,total_turnover,avg_cash_weight_pct
0,baseline_stage1,development_walk_forward,10.0,5.172721,417.272054,-27.488582,-7.845988,-4.119844,-11.858940,145.939551,42.567010
1,selected_feature_recovery,development_walk_forward,10.0,5.324489,432.448857,-28.868443,-7.845988,-4.071250,-11.965807,130.823197,43.278769
2,baseline_stage1,outer_diagnostic_reused,10.0,6.417889,541.788950,-28.105112,-9.383715,-5.233616,-11.602809,71.886102,36.080906
3,selected_feature_recovery,outer_diagnostic_reused,10.0,5.684878,468.487810,-27.445155,-9.383715,-5.203088,-11.436088,59.189806,37.742570
4,selected_feature_recovery_fixed_decisions,outer_diagnostic_reused,25.0,5.202666,420.266569,-28.743251,-9.383715,-5.212176,-11.667294,59.189806,37.742570

# 中文结论

- 做了什么：保持原 Stage1 合法 SOXL/SOXX/cash 输出、回撤状态机、第一小时执行时点和教师标签不变，只对 recovery head 做四组特征消融；训练通过 qlib DatasetH，证据写入 qlib Recorder。
- 开发期选择：`absolute_plus_breadth`，Logistic C=0.10，阈值=0.71，动作 beta=0.6。
- 开发期效果：新候选 return=432.4489%，原 Stage1=417.2721%，财富提升=2.9340%；总换手变化=-10.3580%。
- 特征结论：绝对风险单独和“绝对风险+标准化状态”均未形成可选增益；只有绝对 VIX/波动/回撤/相对动量与滞后一日 SOXX 宽度共同进入 recovery head 后，在开发期形成通过五点阈值邻域的候选。这仍是自适应开发期搜索证据，不等同于新的样本外证明。
- outer 10bp 冻结诊断：新候选 return=468.4878%，原 Stage1=541.7889%，MaxDD=-27.4452%，worst 5d=-11.4361%。
- 25bp 固定决策压力：return=420.2666%，MaxDD=-28.7433%，worst 5d=-11.6673%。
- 稳健性：选中阈值邻域数量=5，邻域最差财富比例=0.9882；outer 不参与任何候选、阈值或 beta 选择。
- 是否晋升：`rejected_feature_recovery_outer_generalization_failed`。开发期候选被冻结 outer 泛化门否决，不进入 paper challenger，production Stage1 保持不变。
- 下一步：停止继续调概率阈值；下一轮改成带交易成本和五日尾部惩罚的连续 advantage 目标，并用独立 tail-veto head 约束恢复动作。
- 不构成买卖建议。