# 可行父模型上的33坐标稀疏持仓搜索

本Notebook已完成登记的合成增益预检、开发期搜索、已查看历史外层诊断及原生Qlib对账。三个信息组均未通过历史资格，不晋升，稳定净超额目标未完成。完整定义见[selection_plan.json](selection_plan.json)和[design.md](design.md)；最终经济解释见末尾中文结论及[economic_review.md](economic_review.md)。重跑默认只核对已封存证据，不启动新的拟合活动。

In [1]:
from pathlib import Path
import sys, json, hashlib, qlib
ROOT=next(p for p in (Path.cwd(),*Path.cwd().parents) if (p/'SPEC.md').exists())
sys.path.insert(0,str(ROOT))
CARD=ROOT/'research/feasible_parent_sparse_search_20261003'
PLAN=json.loads((CARD/'selection_plan.json').read_text())
assert PLAN['registration_status']=='registered_before_implementation_or_new_fits', 'blocked: plan not registered'
assert PLAN['architecture']['trainable_search_coordinates']==33
assert PLAN['search']['unique_whole_two_cost_path_evaluation_cap']==2000
qlib.init(provider_uri=str(ROOT/PLAN['source']['provider_uri']),region='us')
from qlib.data import D
from qlib.workflow import R
print({'calendar_sessions':len(D.calendar(freq='day')),'as_of':PLAN['source']['as_of'],'plan_sha256':hashlib.sha256((CARD/'selection_plan.json').read_bytes()).hexdigest(),'objective_achieved':False})

[39290:MainThread](2026-10-03 06:46:39,835) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[39290:MainThread](2026-10-03 06:46:40,197) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[39290:MainThread](2026-10-03 06:46:40,197) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/data/qlib/published_futu_affine_20260925_v1')}

{'calendar_sessions': 4162, 'as_of': '2026-09-25', 'plan_sha256': 'c7818045478368cd472b4f37c54a19ffcad014478e36d558f4af31af6e5f40b7', 'objective_achieved': False}

所有行情、成熟行和scaler由原生Qlib DatasetH重建并对照冻结父来源。来源读取、旧父模型的必要重建、合成证据、每次搜索与回测均由下一单元格的薄工作流写入Qlib Recorder。完整合成结果首次生成后封存，Notebook重跑只核对该证据；没有通过增益门就输出失败诊断，市场拟合数量必须为0。不得用试验失败作为修改预算的理由。

In [2]:
import os
from src.workflow.feasible_parent_sparse_search import run
ALLOW_MARKET = os.environ.get('SOXL_ALLOW_MARKET_FITS','0') == '1'
summary=run(ROOT,CARD,allow_market_fits=ALLOW_MARKET)
print(json.dumps({k:summary.get(k) for k in ('recorder_id','decision','preflight','market_model_fits','objective_achieved')},ensure_ascii=False,indent=2))

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[39290:MainThread](2026-10-03 06:46:41,488) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[39290:MainThread](2026-10-03 06:46:41,489) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[39290:MainThread](2026-10-03 06:46:41,489) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/data/qlib/published_futu_affine_20260925_v1')}

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[39290:MainThread](2026-10-03 06:46:41,594) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[39290:MainThread](2026-10-03 06:46:41,595) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[39290:MainThread](2026-10-03 06:46:41,595) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/data/qlib/published_futu_affine_20260925_v1')}

[39290:MainThread](2026-10-03 06:46:41,674) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[39290:MainThread](2026-10-03 06:46:41,674) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[39290:MainThread](2026-10-03 06:46:41,674) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[39290:MainThread](2026-10-03 06:46:46,116) INFO - qlib.workflow - [exp.py:258] - Experiment 730964976368316455 starts running ...

[39290:MainThread](2026-10-03 06:46:46,168) INFO - qlib.workflow - [recorder.py:345] - Recorder 8696cd2152df4ffbbb5ac6692b139ef9 starts running under Experiment 730964976368316455 ...

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

Parent search holdings_only/2016/41:origin=search F=0.0001796878 unique=848

Parent search holdings_only/2016/17:origin=search F=0.0001796878 unique=848

Parent search holdings_only/2016/71:origin=search F=0.0001796878 unique=848

Parent search holdings_only/2017/17:origin=search F=0.00015135695 unique=879

Parent search holdings_only/2017/71:origin=search F=0.00015135695 unique=879

Parent search holdings_only/2017/41:origin=search F=0.00015135695 unique=879

Parent search holdings_only/2018/17:origin=search F=0.00011626776 unique=581

Parent search holdings_only/2018/41:origin=search F=0.00011626776 unique=581

Parent search holdings_only/2018/71:origin=search F=0.00011626776 unique=581

Parent search holdings_only/2019/17:origin=search F=0.00012122665 unique=426

Parent search holdings_only/2019/41:origin=search F=0.00012122665 unique=426

Parent search holdings_only/2019/71:origin=search F=0.00012122665 unique=426

Parent search holdings_only/2020/17:origin=search F=0.00010134485 unique=656

Parent search holdings_only/2020/41:origin=search F=0.00010134485 unique=656

Parent search holdings_only/2020/71:origin=search F=0.00010134485 unique=656

Parent search holdings_only/2021/17:origin=search F=8.812253e-05 unique=1567

Parent search holdings_only/2021/41:origin=search F=8.812253e-05 unique=1567

Parent search holdings_only/2021/71:origin=search F=8.812253e-05 unique=1567

Parent search holdings_only/2022/17:origin=search F=7.8186358e-05 unique=832

Parent search holdings_only/2022/41:origin=search F=7.8186358e-05 unique=832

Parent search holdings_only/2022/71:origin=search F=7.8186358e-05 unique=832

Parent search price_holdings/2016/17:origin=search F=0.058443428 unique=729

Parent search price_holdings/2016/71:origin=search F=0.080019746 unique=2000

Parent search price_holdings/2016/41:origin=search F=0.073028087 unique=2000

Parent search price_holdings/2017/17:origin=search F=0.081722775 unique=2000

Parent search price_holdings/2017/41:origin=search F=0.099747761 unique=2000

Parent search price_holdings/2017/71:origin=search F=0.072264563 unique=2000

Parent search price_holdings/2018/17:origin=search F=0.026498667 unique=2000

Parent search price_holdings/2018/41:origin=search F=0.037515065 unique=2000

Parent search price_holdings/2018/71:origin=search F=0.036310132 unique=2000

Parent search price_holdings/2019/17:origin=search F=0.041442884 unique=2000

Parent search price_holdings/2019/41:origin=search F=0.047163301 unique=2000

Parent search price_holdings/2019/71:origin=search F=0.050262551 unique=2000

Parent search price_holdings/2020/17:origin=search F=0.032597638 unique=2000

Parent search price_holdings/2020/41:origin=search F=0.034880857 unique=2000

Parent search price_holdings/2020/71:origin=search F=0.039564899 unique=2000

Parent search price_holdings/2021/17:origin=search F=0.038078037 unique=1632

Parent search price_holdings/2021/41:origin=search F=0.042698517 unique=2000

Parent search price_holdings/2021/71:origin=search F=0.052875318 unique=2000

Parent search price_holdings/2022/17:origin=search F=0.039703356 unique=2000

Parent search price_holdings/2022/41:origin=search F=0.050814258 unique=2000

Parent search price_holdings/2022/71:origin=search F=0.057340138 unique=2000

Parent search price_vol_holdings/2016/17:origin=search F=0.072131982 unique=2000

Parent search price_vol_holdings/2016/41:origin=search F=0.071050111 unique=2000

Parent search price_vol_holdings/2016/71:origin=search F=0.078554691 unique=2000

Parent search price_vol_holdings/2017/17:origin=search F=0.082048437 unique=2000

Parent search price_vol_holdings/2017/41:origin=search F=0.086428519 unique=2000

Parent search price_vol_holdings/2017/71:origin=search F=0.072622571 unique=2000

Parent search price_vol_holdings/2018/17:origin=search F=0.041195327 unique=2000

Parent search price_vol_holdings/2018/41:origin=search F=0.028591031 unique=2000

Parent search price_vol_holdings/2018/71:origin=search F=0.050575167 unique=2000

Parent search price_vol_holdings/2019/17:origin=search F=0.04219816 unique=2000

Parent search price_vol_holdings/2019/41:origin=search F=0.05095712 unique=2000

Parent search price_vol_holdings/2019/71:origin=search F=0.044656992 unique=2000

Parent search price_vol_holdings/2020/17:origin=search F=0.036672562 unique=1591

Parent search price_vol_holdings/2020/41:origin=search F=0.037123394 unique=2000

Parent search price_vol_holdings/2020/71:origin=search F=0.046753754 unique=2000

Parent search price_vol_holdings/2021/17:origin=search F=0.03808334 unique=2000

Parent search price_vol_holdings/2021/71:origin=search F=0.058159187 unique=1149

Parent search price_vol_holdings/2022/17:origin=search F=0.029010487 unique=539

Parent search price_vol_holdings/2021/41:origin=search F=0.051732394 unique=2000

Parent search price_vol_holdings/2022/41:origin=search F=0.035335722 unique=2000

Parent search price_vol_holdings/2022/71:origin=search F=0.052235584 unique=2000

Feasible parent search development sealed: {'variant': 'holdings_only', 'historical_qualification_pass': False, 'passed_gates': 12, 'worst_annualized_lower_bound': -0.00014838837770166335, 'worst_relative_wealth': 1.0147424163131835, 'positive_years_10bps': 1}

[39290:MainThread](2026-10-03 07:17:29,268) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | waiting `async_log` Done

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[39290:MainThread](2026-10-03 07:17:29,397) INFO - qlib.workflow - [exp.py:258] - Experiment 730964976368316455 starts running ...

[39290:MainThread](2026-10-03 07:17:29,401) INFO - qlib.workflow - [recorder.py:345] - Recorder 8696cd2152df4ffbbb5ac6692b139ef9 starts running under Experiment 730964976368316455 ...

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

Parent search holdings_only/2023/17:origin=search F=4.4777234e-05 unique=2000

Parent search holdings_only/2023/71:origin=search F=4.4777234e-05 unique=2000

Parent search holdings_only/2023/41:origin=search F=4.4777234e-05 unique=2000

Parent search holdings_only/2024/41:origin=search F=3.7208627e-05 unique=530

Parent search holdings_only/2024/17:origin=search F=3.7208627e-05 unique=530

Parent search holdings_only/2024/71:origin=search F=3.7208627e-05 unique=530

Parent search holdings_only/2025/17:origin=search F=6.2146506e-05 unique=966

Parent search holdings_only/2025/41:origin=search F=6.2146506e-05 unique=966

Parent search holdings_only/2025/71:origin=search F=6.2146506e-05 unique=966

Parent search holdings_only/2026/41:origin=search F=5.5999081e-05 unique=525

Parent search holdings_only/2026/17:origin=search F=5.5999081e-05 unique=525

Parent search holdings_only/2026/71:origin=search F=5.5999081e-05 unique=525

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

[39290:MainThread](2026-10-03 07:23:55,199) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

[39290:MainThread](2026-10-03 07:23:55,213) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[39290:MainThread](2026-10-03 07:23:55,214) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[39290:MainThread](2026-10-03 07:23:55,215) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/data/qlib/published_futu_affine_20260925_v1')}

[39290:MainThread](2026-10-03 07:23:55,227) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[39290:MainThread](2026-10-03 07:23:55,232) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[39290:MainThread](2026-10-03 07:23:55,239) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[39290:MainThread](2026-10-03 07:23:55,240) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[39290:MainThread](2026-10-03 07:23:55,242) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x11f553f50>

backtest loop:   0%|          | 0/1762 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)

/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)

[39290:MainThread](2026-10-03 07:23:56,899) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[39290:MainThread](2026-10-03 07:23:56,900) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[39290:MainThread](2026-10-03 07:23:56,900) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/data/qlib/published_futu_affine_20260925_v1')}

[39290:MainThread](2026-10-03 07:23:56,910) INFO - qlib.backtest caller - [__init__.py:93] - Create new exchange

[39290:MainThread](2026-10-03 07:23:56,914) WARNING - qlib.online operator - [exchange.py:226] - factor.day.bin file not exists or factor contains `nan`. Order using adjusted_price.

[39290:MainThread](2026-10-03 07:23:56,922) WARNING - qlib.data - [data.py:665] - load calendar error: freq=day, future=True; return current calendar!

[39290:MainThread](2026-10-03 07:23:56,922) WARNING - qlib.data - [data.py:668] - You can get future calendar by referring to the following document: https://github.com/microsoft/qlib/blob/main/scripts/data_collector/contrib/README.md

[39290:MainThread](2026-10-03 07:23:56,925) WARNING - qlib.BaseExecutor - [executor.py:121] - `common_infra` is not set for <qlib.backtest.executor.SimulatorExecutor object at 0x15f890c50>

backtest loop:   0%|          | 0/1762 [00:00<?, ?it/s]

/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)
/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/qlib_venv/lib/python3.12/site-packages/qlib/utils/index_data.py:492: RuntimeWarning: Mean of empty slice
  return np.nanmean(self.data)

[39290:MainThread](2026-10-03 07:23:57,754) INFO - qlib.workflow - [exp.py:258] - Experiment 730964976368316455 starts running ...

[39290:MainThread](2026-10-03 07:23:57,757) INFO - qlib.workflow - [recorder.py:345] - Recorder 8696cd2152df4ffbbb5ac6692b139ef9 starts running under Experiment 730964976368316455 ...

[39290:MainThread](2026-10-03 07:23:58,380) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

{
  "recorder_id": "8696cd2152df4ffbbb5ac6692b139ef9",
  "decision": "continue_research_no_historical_qualification",
  "preflight": null,
  "market_model_fits": null,
  "objective_achieved": false
}

以下只展示Recorder导出的瘦摘要。若合成增益门失败，显示三个种子与集合的父F、新F、差值及原始风险差；不产生虚假的市场比较。若通过，开发期选择必须先封存，再生成两种外层诊断和同成本原生Qlib对账。

In [3]:
import pandas as pd
from IPython.display import display
for filename in ['preflight_seed_summary.csv','model_selection.csv','backtest_benchmark_comparison.csv','risk_analysis.csv','window_metrics.csv']:
    path=CARD/filename
    if path.exists():
        print(filename)
        display(pd.read_csv(path))
print(json.dumps(summary.get('native_qlib_audit',{}),ensure_ascii=False,indent=2))

preflight_seed_summary.csv

,seed,parent_F,parent_stage_passed,search_ran,retained_origin,search_F,F_delta,incremental_seed_gate_passed,unique_evaluations,search_failure
0,17,0.015864,True,True,search,0.650048,0.634184,True,225,NaN
1,41,0.030139,True,True,search,0.650048,0.619909,True,190,NaN
2,71,0.005151,True,True,search,0.650048,0.644897,True,225,NaN

model_selection.csv

,variant,historical_qualification_pass,passed_gates,worst_annualized_lower_bound,worst_relative_wealth,positive_years_10bps
0,holdings_only,False,12,-0.000148,1.014742,1
1,price_vol_holdings,False,9,-0.296372,1.114310,3
2,price_holdings,False,8,-0.217042,1.036266,3

backtest_benchmark_comparison.csv

,cost_bps,sessions,start_signal,last_exit,terminal_wealth,return_pct,cagr_pct,annualized_log_volatility_pct,max_drawdown_pct,qlib_max_drawdown_without_initial_mark_pct,...,annualized_log_excess,annualized_relative_return_pct,relative_max_drawdown_pct,up_day_conditional_relative_return_pct,down_day_conditional_relative_return_pct,conditional_returns_are_noncontiguous_statistics,risk_policy,annualization_sessions,variant,segment
0,10.0,1762,2016-01-04,2023-01-04,4.320293,332.029286,23.279439,30.533249,-47.373291,-47.373291,...,0.002095,0.209702,-0.037289,-4.098210e-12,1.475493,True,reported against benchmark; no implicit fixed ...,252,holdings_only,development
1,25.0,1762,2016-01-04,2023-01-04,4.313775,331.377539,23.252823,30.535125,-47.373291,-47.373291,...,0.002093,0.209525,-0.103700,0.000000e+00,1.474242,True,reported against benchmark; no implicit fixed ...,252,holdings_only,development
2,10.0,1762,2016-01-04,2023-01-04,5.898861,489.886107,28.894599,39.236410,-49.033193,-49.033193,...,0.046636,4.774077,-38.554633,-7.689482e+01,499.665436,True,reported against benchmark; no implicit fixed ...,252,price_holdings,development
3,25.0,1762,2016-01-04,2023-01-04,4.405274,340.527432,23.623365,39.236952,-49.432100,-49.432100,...,0.005095,0.510790,-45.197186,-8.026425e+01,425.082991,True,reported against benchmark; no implicit fixed ...,252,price_holdings,development
4,10.0,1762,2016-01-04,2023-01-04,6.627177,562.717668,31.058693,44.896553,-64.262477,-64.262477,...,0.063286,6.533195,-53.342981,3.520195e+01,15.132968,True,reported against benchmark; no implicit fixed ...,252,price_vol_holdings,development
5,25.0,1762,2016-01-04,2023-01-04,4.737046,373.704558,24.913856,44.905429,-64.569751,-64.569751,...,0.015480,1.560012,-54.229125,1.328093e+01,-1.628052,True,reported against benchmark; no implicit fixed ...,252,price_vol_holdings,development
6,10.0,934,2023-01-03,2026-09-25,4.985306,398.530577,54.256093,37.340960,-42.789194,-42.789194,...,0.000221,0.022068,-0.064684,-6.458812e-02,0.146500,True,reported against benchmark; no implicit fixed ...,252,holdings_only_annual_refit,reused_diagnostic
7,25.0,934,2023-01-03,2026-09-25,4.977843,397.784310,54.193757,37.340999,-42.789194,-42.789194,...,0.000220,0.022050,-0.114855,-1.146078e-01,0.196583,True,reported against benchmark; no implicit fixed ...,252,holdings_only_annual_refit,reused_diagnostic
8,10.0,934,2023-01-03,2026-09-25,4.985306,398.530577,54.256093,37.340960,-42.789194,-42.789194,...,0.000221,0.022068,-0.064684,-6.458812e-02,0.146500,True,reported against benchmark; no implicit fixed ...,252,holdings_only_frozen2022_parameters,reused_diagnostic
9,25.0,934,2023-01-03,2026-09-25,4.977843,397.784310,54.193757,37.340999,-42.789194,-42.789194,...,0.000220,0.022050,-0.114855,-1.146078e-01,0.196583,True,reported against benchmark; no implicit fixed ...,252,holdings_only_frozen2022_parameters,reused_diagnostic

window_metrics.csv

,variant,cost_bps,window,start_position,sessions,start_signal,last_exit,terminal_wealth,return_pct,cagr_pct,...,relative_wealth,relative_return_pct,annualized_log_excess,annualized_relative_return_pct,relative_max_drawdown_pct,up_day_conditional_relative_return_pct,down_day_conditional_relative_return_pct,conditional_returns_are_noncontiguous_statistics,risk_policy,annualization_sessions
0,holdings_only_annual_refit,10,trade_date>=2026-08-03; through2026-09-25open,carried from diagnostic2023start,38,2026-07-31,2026-09-25,1.158432,15.843223,165.193660,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True,reported against benchmark; no implicit fixed ...,252
1,holdings_only_annual_refit,10,trade_date>=2026-08-03; through2026-09-25open,CASH at first window trade,38,2026-07-31,2026-09-25,1.125412,12.541230,118.915904,...,0.972468,-2.753248,-0.185144,-16.901574,-2.753282,-2.749972,-0.003369,True,reported against benchmark; no implicit fixed ...,252
2,holdings_only_annual_refit,25,trade_date>=2026-08-03; through2026-09-25open,carried from diagnostic2023start,38,2026-07-31,2026-09-25,1.158432,15.843223,165.193660,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True,reported against benchmark; no implicit fixed ...,252
3,holdings_only_annual_refit,25,trade_date>=2026-08-03; through2026-09-25open,CASH at first window trade,38,2026-07-31,2026-09-25,1.123728,12.372775,116.752000,...,0.972467,-2.753304,-0.185148,-16.901892,-2.753304,-2.747541,-0.005926,True,reported against benchmark; no implicit fixed ...,252
4,holdings_only_frozen2022_parameters,10,trade_date>=2026-08-03; through2026-09-25open,carried from diagnostic2023start,38,2026-07-31,2026-09-25,1.158432,15.843223,165.193660,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True,reported against benchmark; no implicit fixed ...,252
5,holdings_only_frozen2022_parameters,10,trade_date>=2026-08-03; through2026-09-25open,CASH at first window trade,38,2026-07-31,2026-09-25,1.129357,12.935655,124.054390,...,0.975876,-2.412426,-0.161943,-14.951053,-2.412426,-2.411319,-0.001135,True,reported against benchmark; no implicit fixed ...,252
6,holdings_only_frozen2022_parameters,25,trade_date>=2026-08-03; through2026-09-25open,carried from diagnostic2023start,38,2026-07-31,2026-09-25,1.158432,15.843223,165.193660,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,True,reported against benchmark; no implicit fixed ...,252
7,holdings_only_frozen2022_parameters,25,trade_date>=2026-08-03; through2026-09-25open,CASH at first window trade,38,2026-07-31,2026-09-25,1.127695,12.769471,121.877031,...,0.975900,-2.410005,-0.161779,-14.937064,-2.410005,-2.403692,-0.006469,True,reported against benchmark; no implicit fixed ...,252

{
  "10": {
    "status": "passed",
    "sessions": 1762,
    "start": "2016-01-05",
    "end": "2023-01-03",
    "provider_uri": "/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/data/qlib/published_futu_affine_20260925_v1",
    "cost_bps": 10.0,
    "initial_cash": 100000.0,
    "maximum_session_return_error": 5.9503293403651014e-08,
    "tolerance": 1e-07,
    "native_api": "qlib.backtest.backtest + SimulatorExecutor + Exchange + Account + Position",
    "position_type": "src.backtest.qlib_continuous_position.QlibContinuousPosition",
    "position_precision_fix": "Every positive fractional-sale residual remains owned; no relative isclose liquidation.",
    "report_mark": "native same-day close; next-open reconciliation marks native positions through Qlib D.features",
    "sealed_stage1_code_changed": false,
    "qlib_api_reference": "https://qlib.readthedocs.io/en/latest/reference/api.html#qlib.backtest.backtest",
    "policy_scope": "continuous_three_asset_targets_without_legacy_allocation_caps",
    "legacy_controller_executed": false,
    "scope": "complete prescribed daily target/HOLD schedule; actual Qlib Exchange, Position, report and next-open accounting",
    "risk_annualization_sessions": 252,
    "native_close_anchored_max_drawdown_pct": -45.7529855035116,
    "native_open_to_open_anchored_max_drawdown_pct": -47.37329003636821,
    "risk_table_mark_convention": "risk_analysis uses native close marks; risk_analysis_open_to_open uses native positions marked at the following open",
    "execution_limitation": "Observed historical opens and continuous adjusted shares; no claim of spread/impact/partial-fill evidence."
  },
  "25": {
    "status": "passed",
    "sessions": 1762,
    "start": "2016-01-05",
    "end": "2023-01-03",
    "provider_uri": "/Users/rziiiii/dev/workspace-worktrees/feasible-parent-sparse-search-20261003/data/qlib/published_futu_affine_20260925_v1",
    "cost_bps": 25.0,
    "initial_cash": 100000.0,
    "maximum_session_return_error": 5.9503293403651014e-08,
    "tolerance": 1e-07,
    "native_api": "qlib.backtest.backtest + SimulatorExecutor + Exchange + Account + Position",
    "position_type": "src.backtest.qlib_continuous_position.QlibContinuousPosition",
    "position_precision_fix": "Every positive fractional-sale residual remains owned; no relative isclose liquidation.",
    "report_mark": "native same-day close; next-open reconciliation marks native positions through Qlib D.features",
    "sealed_stage1_code_changed": false,
    "qlib_api_reference": "https://qlib.readthedocs.io/en/latest/reference/api.html#qlib.backtest.backtest",
    "policy_scope": "continuous_three_asset_targets_without_legacy_allocation_caps",
    "legacy_controller_executed": false,
    "scope": "complete prescribed daily target/HOLD schedule; actual Qlib Exchange, Position, report and next-open accounting",
    "risk_annualization_sessions": 252,
    "native_close_anchored_max_drawdown_pct": -45.75298550351157,
    "native_open_to_open_anchored_max_drawdown_pct": -47.37329003636815,
    "risk_table_mark_convention": "risk_analysis uses native close marks; risk_analysis_open_to_open uses native positions marked at the following open",
    "execution_limitation": "Observed historical opens and continuous adjusted shares; no claim of spread/impact/partial-fill evidence."
  }
}

# 可行父模型上的稀疏搜索：三个组均未通过历史资格

本轮完成登记的固定父编码器、33坐标COBYLA搜索。合成预检通过，实际市场开发期搜索、两种外层诊断与原生Qlib对账均完成，但**三个组全部未通过原定历史门槛，不晋升；稳定净超额目标仍未完成**。`holdings_only`只是失败候选中的诊断排序第一，不能称为合格策略。

开发期为2016–2022信号年，1,762个区间，首交易2016-01-05，最后于2023-01-04开盘结算。冻结行情截至2026-09-25，来自原生Qlib provider `data/qlib/published_futu_affine_20260925_v1`，源Recorder为`bd754e6362b241f194351a1e7aebff6f`。2023以后是已查看历史诊断，不能当作新留出样本。

|组|相对SOXX终值10/25bp|正超额年份10/25bp|MaxDD 25bp|CVaR5 25bp|
|---|---:|---:|---:|---:|
|持仓状态 `holdings_only`|1.014755 / 1.014742|1/7、1/7|−47.373%|−4.416%|
|价格 `price_holdings`|1.385531 / 1.036266|3/7、3/7|−49.432%|−5.771%|
|价格与波动预测 `price_vol_holdings`|1.556598 / 1.114310|3/7、3/7|−64.570%|−6.605%|

同窗SOXX25bp的MaxDD为−47.373%，CVaR5为−4.418%。两个条件组在两档成本下均失败于年度稳定性、回撤、尾部及bootstrap门。价格与波动组的10bp删一年门通过，但25bp失败。持仓状态组虽保住风险门，其余六年25bp超额精确为0；10bp微小负残差未虚增正年份。三个组的bootstrap下界均未通过，原门槛与排序未被修改。

持仓状态组25bp整段净对数超额0.0146348，第一天贡献却为+0.0156723，其余全部观察合计−0.00103754：开始只持56.40%SOXX，第三天达到纯SOXX，之后1,759天逐日收益与基准相同。它不是持续的择时信号。11个已保存集合训练账本也都从2011-01-04现金起步，相对父模型的改进只发生在开头2–10行，之后逐日相同。三种子结果相同，不能作为三个独立市场证据。2023以后诊断的微小正增量同样由首次入场贡献。

两个条件组25bp相对父模型终值分别改善2.49%和7.89%，说明本轮确实搜索出了新训练可行状态；但交易天数从父模型1,762天下降至1,455/1,541天的同时，总换手从54.61/59.23倍上升至194.58/223.76倍，为父模型约3.56/3.78倍。保存账本的年化对数费用前贡献为7.433%/9.516%，费用项为−6.924%/−7.968%，净贡献仅0.509%/1.548%。这些是同一持仓路径的恒等分解，不是零成本新策略，也不证明未来毛收益优势。25bp最差单日恶化至−21.59%/−27.35%；平均现金多仍未保护危机日。两组HAC alpha区间跨零，未形成可靠信息优势证据。

三个集合开发路径都没有单独HOLD专家触发的日期。精确零订单日分别为1,759、307、188，不能把已经持有资产顶点时的零订单归因于学会HOLD。价格与波动组另有33天微小订单低于原报告阈值，仍不属于精确零订单。

用户“8月3日以来”按实际交易日定义为2026-08-03至09-25开盘，共38区间，首信号07-31。仅对开发期选出的持仓状态组作下列已登记诊断：

|起点/模式|10bp策略 / SOXX|25bp策略 / SOXX|交易天数|
|---|---:|---:|---:|
|持续持仓，年更或冻结|15.843% / 15.843%|15.843% / 15.843%|0|
|8/3现金起步，年更|12.541% / 15.727%|12.373% / 15.554%|7|
|8/3现金起步，冻结|12.936% / 15.727%|12.769% / 15.554%|8|

持续持仓已是纯SOXX，没有超额；现金起步落后约2.8–3.2个百分点。各窗口MaxDD约−10.984%，与SOXX相同。这不是用户真实账户，也不能与截至09-30收盘的旧窗口混比。

本轮实际工作量为75个新市场搜索、25个集合审计、109,070次唯一双成本评估，复用63个开发父模型，另按原协议重建12个缺失外层父模型（1,440步旧Adam）。合成预检另有3个父模型重建及3个搜索。COBYLA评估次数和旧Adam步数不可作为等计算预算。原生Qlib两档成本对账均通过，最大逐期误差约5.95e−8；工程正确不等于金融资格通过。

未解决的是跨时间泛化、费用和下一年尾部。下一方向尚未登记或运行：先核实已有输入的可复用信息，再设计诚实的训练内部时间验证，防止固定现金起点冒充持续能力；不再把优化器可找到训练改进等同于存在稳定超额。既有有限搜索不保证全局最优，父模型保留原梯度/截断近似；数据含16条次来源观察、复权差异，历史开盘连续份额亦不代表真实点差、冲击或部分成交。

没有新前向合格证据，没有生产/SIM切换，没有实盘订单。完整经济解释见[economic_review.md](economic_review.md)，年度、费用、父模型增量和起点贡献见对应小表。市场Recorder：`8696cd2152df4ffbbb5ac6692b139ef9`；合成预检Recorder：`a0cbd66785b44ccc8ab2080b36026195`，其合成F约0.650不能读作市场收益。