# Cash-Floor Relative-Target Feature Reintegration v1

把历史日频特征按新的现金保护相对财富目标重新审计。比较当前 10 特征、精简 reintegrated 特征和全量特征；2016–2022 为 expanding walk-forward，2023 起 outer 仅诊断。

In [1]:
from pathlib import Path
import sys
repo = Path.cwd().resolve()
if repo.name == 'cash_floor_relative_target_feature_reintegration_v1':
    repo = repo.parents[1]
sys.path.insert(0, repo.as_posix())
import pandas as pd
import qlib
from qlib.data import D
from qlib.data.dataset import DatasetH
from qlib.data.dataset.handler import DataHandlerLP
from qlib.workflow import R
from src.workflow.cash_floor_relative_feature_reintegration import run_cash_floor_relative_feature_reintegration_card

provider = repo / 'data' / 'qlib' / 'soxl_soxx_soxs'
qlib.init(provider_uri=provider.as_posix(), region='us', kernels=1)
calendar = D.calendar(start_time='2011-01-03', end_time='2026-07-21', freq='day')
summary = run_cash_floor_relative_feature_reintegration_card(root=repo)
recorder = R.get_recorder(recorder_id=summary['recorder_id'], experiment_name=summary['experiment'])
{'calendar_rows': len(calendar), 'recorder_id': recorder.id, 'decision': summary['promotion_decision']}

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[70033:MainThread](2026-07-23 15:07:45,600) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[70033:MainThread](2026-07-23 15:07:45,601) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[70033:MainThread](2026-07-23 15:07:45,602) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[70033:MainThread](2026-07-23 15:07:45,606) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[70033:MainThread](2026-07-23 15:07:45,607) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[70033:MainThread](2026-07-23 15:07:45,607) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[70033:MainThread](2026-07-23 15:07:45,629) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[70033:MainThread](2026-07-23 15:07:45,630) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[70033:MainThread](2026-07-23 15:07:45,630) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[70033:MainThread](2026-07-23 15:07:45,883) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[70033:MainThread](2026-07-23 15:07:45,884) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[70033:MainThread](2026-07-23 15:07:45,884) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

[70033:MainThread](2026-07-23 15:07:45,981) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | Loading data Done

[70033:MainThread](2026-07-23 15:07:45,981) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | fit & process data Done

[70033:MainThread](2026-07-23 15:07:45,982) INFO - qlib.timer - [log.py:127] - Time cost: 0.001s | Init data Done

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[70033:MainThread](2026-07-23 15:08:01,218) WARNING - qlib.workflow - [expm.py:231] - No valid experiment found. Create a new experiment with name cash_floor_relative_target_feature_reintegration_v1.

[70033:MainThread](2026-07-23 15:08:01,219) INFO - qlib.workflow - [exp.py:258] - Experiment 445309417058052209 starts running ...

[70033:MainThread](2026-07-23 15:08:01,275) INFO - qlib.workflow - [recorder.py:345] - Recorder 58d8f39c04a740ac85945d064b98a5de starts running under Experiment 445309417058052209 ...

[70033:MainThread](2026-07-23 15:08:01,388) INFO - qlib.timer - [log.py:127] - Time cost: 0.000s | waiting `async_log` Done

{'calendar_rows': 3909,
 'recorder_id': '58d8f39c04a740ac85945d064b98a5de',
 'decision': 'needs_iteration_tail_risk_after_feature_reintegration'}

In [2]:
card = repo / 'research' / summary['experiment']
audit = pd.read_csv(card / 'feature_oos_audit.csv')
selection = pd.read_csv(card / 'model_selection.csv')
display(audit.sort_values(['target', 'pooled_spearman'], ascending=[True, False]))
display(selection.loc[selection['selected']])

,feature_set,model_family,target,pooled_spearman,median_fold_spearman,positive_fold_count,fold_count,prediction_q4_minus_q1_actual,selection_uses_outer_test
2,compact_reintegrated,ridge,cash_protection_5d,0.059469,0.100917,7,7,0.004322,False
0,compact_reintegrated,extra_trees,cash_protection_5d,0.047485,0.077611,7,7,-0.000110,False
10,full_reintegrated,ridge,cash_protection_5d,0.046886,0.102566,6,7,0.002229,False
6,current10,ridge,cash_protection_5d,0.046507,0.129046,7,7,-0.000025,False
4,current10,extra_trees,cash_protection_5d,0.016834,0.113597,6,7,-0.000832,False
8,full_reintegrated,extra_trees,cash_protection_5d,-0.006386,0.077293,5,7,-0.004241,False
3,compact_reintegrated,ridge,future_vol_5d,0.611492,0.284880,6,7,0.014898,False
9,full_reintegrated,extra_trees,future_vol_5d,0.608035,0.317595,6,7,0.015311,False
1,compact_reintegrated,extra_trees,future_vol_5d,0.599347,0.325915,6,7,0.015049,False
5,current10,extra_trees,future_vol_5d,0.594929,0.253365,7,7,0.014616,False
7,current10,ridge,future_vol_5d,0.580379,0.248114,7,7,0.014619,False
11,full_reintegrated,ridge,future_vol_5d,0.572554,0.268969,6,7,0.013820,False

,candidate,feature_set,model_family,volatility_weight,router,cost_bps,return_pct,cagr_pct,annualized_vol_pct,max_drawdown_pct,...,avg_soxx_weight_pct,ratio_25bps,positive_years,median_year_ratio,relative_gate,risk_gate,all_gate,risk_violation_score,selection_score,selected
4,current10__ridge__volw_0.75__none,current10,ridge,0.75,none,10,364.232874,24.553546,31.43232,-42.339176,...,50.250812,1.062578,4,1.020688,True,False,False,1.64863,-1.534836,True

In [3]:
comparison = pd.read_csv(card / 'backtest_benchmark_comparison.csv')
folds = pd.read_csv(card / 'backtest_walk_forward_metrics.csv')
display(comparison[['segment', 'candidate', 'cost_bps', 'return_pct', 'terminal_wealth_ratio_vs_soxx', 'max_drawdown_pct', 'worst_rolling_5d_pct', 'avg_cash_weight_pct']])
display(folds.query("segment == 'development_walk_forward' and cost_bps == 10")[["fold_year", "terminal_wealth_ratio_vs_soxx", "max_drawdown_pct", "avg_cash_weight_pct"]])

,segment,candidate,cost_bps,return_pct,terminal_wealth_ratio_vs_soxx,max_drawdown_pct,worst_rolling_5d_pct,avg_cash_weight_pct
0,development_walk_forward,current10__ridge__volw_0.75__none,10,364.232874,1.087026,-42.339176,-18.380059,28.213126
1,development_walk_forward,current10__ridge__volw_0.75__none,25,353.087520,1.062578,-42.467242,-18.413151,28.213126
2,outer_diagnostic,current10__ridge__volw_0.75__none,10,341.063999,0.914294,-46.285145,-15.146836,33.256247
3,outer_diagnostic,current10__ridge__volw_0.75__none,25,334.492409,0.902030,-46.453914,-15.146836,33.256247

,fold_year,terminal_wealth_ratio_vs_soxx,max_drawdown_pct,avg_cash_weight_pct
0,2016,1.020688,-14.836671,22.271194
1,2017,1.101119,-12.940372,18.020865
2,2018,0.906920,-31.887213,26.568293
3,2019,1.060446,-19.310308,26.485038
4,2020,0.971759,-36.748222,32.198987
5,2021,0.997052,-16.289423,25.054619
6,2022,1.037955,-41.235019,46.904266

## 最终中文结论

- 做了什么：通过 qlib Data API、DatasetH/DataHandlerLP 和 recorder，把历史价格、波动、杠杆路径和跨资产扩散特征迁移到现金保护相对财富目标。
- 核心指标：以执行后的 `summary.json`、`feature_oos_audit.csv`、`model_selection.csv` 和 recorder 明细为准。
- Regime/区间差异：2016–2022 是开发 OOS 拼接；2023 起为已观察 outer，仅报告，不参与特征或参数选择。
- 是否晋升：由 `summary.json.promotion_decision` 决定；相对财富通过不等于尾部风险通过。
- 风险：更多日频特征可能加剧共线性和 regime 漂移；非 PIT 成分股历史及 2019 后才覆盖的数据未进入主模型。
- 下一步：如果严格尾部门仍失败，不继续扩张同类价格特征，转向真正领先的 PIT 风险数据或重新评估目标可行边界。