# Intraday on-policy staged validation v1

假设：旧二段恢复模型的高收益可能来自 teacher-state 与实际 inference-state 不一致。这里仅在年度 walk-forward 第一段模型真实触发的日子生成二段标签，并用开发期参数邻域稳定性选择模型。2023–2026 outer 只做冻结诊断。

In [1]:
from pathlib import Path
import json
import sys
import pandas as pd
import qlib
from qlib.constant import REG_US
from qlib.workflow import R
from IPython.display import Markdown, display

HERE = Path.cwd().resolve()
ROOT = next(
    candidate
    for candidate in (HERE, *HERE.parents)
    if (candidate / 'AGENTS.md').exists() and (candidate / 'SPEC.md').exists()
)
if ROOT.as_posix() not in sys.path:
    sys.path.insert(0, ROOT.as_posix())

from src.workflow.intraday_on_policy_staged_validation import (
    EXPERIMENT,
    run_intraday_on_policy_staged_validation_card,
)

qlib.init(
    provider_uri=(ROOT / 'data' / 'qlib' / 'soxl_intraday_15min').as_posix(),
    region=REG_US,
)
CARD = ROOT / 'research' / EXPERIMENT

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[7437:MainThread](2026-07-24 22:06:56,975) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[7437:MainThread](2026-07-24 22:06:56,977) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[7437:MainThread](2026-07-24 22:06:56,977) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

In [2]:
summary = run_intraday_on_policy_staged_validation_card(root=ROOT)
display({
    'decision': summary['decision'],
    'selected_model': summary['selected_model'],
    'selection_gates': summary['selection_gates'],
    'training_sample_audit': summary['training_sample_audit'],
    'outer_metrics_10bps': summary['outer_diagnostic_metrics_10bps'],
    'stress_metrics_25bps': summary['fixed_decision_stress_metrics_25bps'],
    'recorder_id': summary['recorder_id'],
})

[7437:MainThread](2026-07-24 22:06:56,993) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[7437:MainThread](2026-07-24 22:06:56,994) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[7437:MainThread](2026-07-24 22:06:56,994) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_soxx_soxs')}

[7437:MainThread](2026-07-24 22:06:57,016) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[7437:MainThread](2026-07-24 22:06:57,017) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[7437:MainThread](2026-07-24 22:06:57,017) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[7437:MainThread](2026-07-24 22:06:57,289) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[7437:MainThread](2026-07-24 22:06:57,290) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[7437:MainThread](2026-07-24 22:06:57,290) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/dynamic_soxx_soxl_cash_allocation_wf_v1')}

[7437:MainThread](2026-07-24 22:06:57,390) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[7437:MainThread](2026-07-24 22:06:57,391) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[7437:MainThread](2026-07-24 22:06:57,391) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl')}

[7437:MainThread](2026-07-24 22:06:57,432) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[7437:MainThread](2026-07-24 22:06:57,433) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[7437:MainThread](2026-07-24 22:06:57,433) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

[7437:MainThread](2026-07-24 22:06:57,565) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[7437:MainThread](2026-07-24 22:06:57,566) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[7437:MainThread](2026-07-24 22:06:57,566) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

[7437:MainThread](2026-07-24 22:07:03,930) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[7437:MainThread](2026-07-24 22:07:03,931) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[7437:MainThread](2026-07-24 22:07:03,931) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

[7437:MainThread](2026-07-24 22:07:10,141) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[7437:MainThread](2026-07-24 22:07:10,142) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[7437:MainThread](2026-07-24 22:07:10,142) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

[7437:MainThread](2026-07-24 22:07:16,747) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[7437:MainThread](2026-07-24 22:07:16,748) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[7437:MainThread](2026-07-24 22:07:16,748) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

[7437:MainThread](2026-07-24 22:07:23,080) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[7437:MainThread](2026-07-24 22:07:23,081) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[7437:MainThread](2026-07-24 22:07:23,081) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

[7437:MainThread](2026-07-24 22:07:29,674) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[7437:MainThread](2026-07-24 22:07:29,675) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[7437:MainThread](2026-07-24 22:07:29,676) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

[7437:MainThread](2026-07-24 22:07:36,029) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[7437:MainThread](2026-07-24 22:07:36,030) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[7437:MainThread](2026-07-24 22:07:36,030) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

[7437:MainThread](2026-07-24 22:07:42,691) INFO - qlib.Initialization - [config.py:452] - default_conf: client.

[7437:MainThread](2026-07-24 22:07:42,692) INFO - qlib.Initialization - [__init__.py:75] - qlib successfully initialized based on client settings.

[7437:MainThread](2026-07-24 22:07:42,693) INFO - qlib.Initialization - [__init__.py:77] - data_path={'__DEFAULT_FREQ': PosixPath('/Users/rziiiii/dev/workspace/data/qlib/soxl_intraday_15min')}

/Users/rziiiii/dev/workspace/qlib_venv/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
[7437:MainThread](2026-07-24 22:07:49,458) INFO - qlib.workflow - [exp.py:258] - Experiment 300782104043818423 starts running ...

[7437:MainThread](2026-07-24 22:07:49,515) INFO - qlib.workflow - [recorder.py:345] - Recorder f6b09330175e41719886d58ee2d11bec starts running under Experiment 300782104043818423 ...

[7437:MainThread](2026-07-24 22:07:50,183) INFO - qlib.timer - [log.py:127] - Time cost: 0.005s | waiting `async_log` Done

{'decision': 'promoted_research_candidate_stage1_direct_allocation_stage2_gated',
 'selected_model': {'teacher_recovery_beta': 1.2,
  'action_beta': 0.6,
  'logistic_c': 0.03,
  'probability_threshold': 0.55,
  'open_no_trade_band': 0.0,
  'second_cut_bars': 8,
  'second_cut_time': '11:30',
  'stage2_logistic_c': 0.3,
  'stage2_probability_threshold': 0.6,
  'stage2_action_beta': 0.8,
  'stage2_teacher_beta': 1.2,
  'stage2_enabled': False},
 'selection_gates': {'minimum_development_stage2_actions': 20,
  'minimum_neighbor_count': 3,
  'minimum_neighbor_wealth_ratio': 0.9,
  'near_best_neighbor_wealth_tolerance': 0.005,
  'selected_neighbor_count': 3,
  'selected_neighbor_min_wealth_ratio': 1.0,
  'selected_development_stage2_actions': 28,
  'robust_gate_pass': True,
  'stage2_calibration_gate_pass': False,
  'benchmark_gate_pass': True,
  'raw_return_preservation_gate_pass': False},
 'training_sample_audit': {'development_on_policy_stage2_samples': 51,
  'outer_prior_year_update_samples': 32,
  'development_samples_by_year': {'2020': 24, '2021': 3, '2022': 24},
  'outer_samples_by_year': {'2023': 3, '2024': 8, '2025': 14, '2026': 7}},
 'outer_metrics_10bps': {'terminal_wealth': 6.433420180351397,
  'return_pct': 543.3420180351396,
  'max_drawdown_pct': -28.10510967554787,
  'worst_day_pct': -9.383714522786345,
  'cvar5_pct': -5.233616441404358,
  'worst_rolling_5d_pct': -11.602809404682068},
 'stress_metrics_25bps': {'terminal_wealth': 5.778014938322686,
  'return_pct': 477.8014938322686,
  'max_drawdown_pct': -29.088719044447874,
  'worst_day_pct': -9.383714522786345,
  'cvar5_pct': -5.244785499544563,
  'worst_rolling_5d_pct': -11.78025619472718},
 'recorder_id': 'f6b09330175e41719886d58ee2d11bec'}

In [3]:
for name in (
    'risk_analysis.csv',
    'annual_metrics.csv',
    'calibration_metrics.csv',
    'no_trade_band_diagnostics.csv',
):
    display(Markdown(f'## {name}'))
    display(pd.read_csv(CARD / name))

## risk_analysis.csv

,variant,segment,cost_bps,terminal_wealth,return_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,worst_rolling_5d_pct
0,raw_direct_allocation,outer_diagnostic_reused,10.0,6.827327,582.732743,-48.264075,-11.218519,-6.462858,-19.909757
1,stage1_10_30_recovery,outer_diagnostic_reused,10.0,6.433420,543.342018,-28.105110,-9.383715,-5.233616,-11.602809
2,prior_off_policy_staged,outer_diagnostic_reused,10.0,8.127392,712.739209,-28.105120,-9.382462,-5.253781,-11.301752
3,selected_on_policy_staged,outer_diagnostic_reused,10.0,6.433420,543.342018,-28.105110,-9.383715,-5.233616,-11.602809
4,selected_on_policy_staged_fixed_decisions,outer_diagnostic_reused,25.0,5.778015,477.801494,-29.088719,-9.383715,-5.244785,-11.780256

## annual_metrics.csv

,year,terminal_wealth,return_pct,max_drawdown_pct,worst_day_pct,cvar5_pct,worst_rolling_5d_pct,terminal_wealth_ratio_vs_soxx,avg_cash_weight_pct,recovery_action_count,stage2_action_count
0,2023,1.417018,41.701820,-21.654737,-5.401288,-4.267416,-8.145412,0.903588,33.607854,3,0
1,2024,1.393222,39.322160,-18.027343,-7.390741,-4.679966,-10.092327,1.153524,41.863089,8,0
2,2025,1.619374,61.937445,-22.933951,-7.185336,-4.954944,-10.535412,1.094333,36.770167,14,0
3,2026,2.012329,101.232911,-21.716439,-9.383715,-7.133178,-11.602809,1.181760,28.820950,7,0

## calibration_metrics.csv

,year,sample_count,status,label_rate,auc,brier,predicted_action_rate
0,2020,24,insufficient_prior_training_samples,0.583333,NaN,NaN,NaN
1,2021,3,scored,0.666667,1.000000,0.256053,1.000000
2,2022,24,scored,0.500000,0.493056,0.437587,0.958333
3,2023,3,scored,0.666667,0.000000,0.432643,0.000000
4,2024,8,scored,0.125000,0.000000,0.419387,0.500000
5,2025,14,scored,0.500000,0.877551,0.183853,0.071429
6,2026,7,scored,0.285714,0.500000,0.209024,0.000000

## no_trade_band_diagnostics.csv

,segment,selection_uses_outer_test,open_no_trade_band,second_cut_bars,second_cut_time,stage2_logistic_c,stage2_probability_threshold,stage2_action_beta,terminal_wealth,return_pct,...,relative_ratio_median,base_development_gate,stage1_action_count,stage2_action_count,total_turnover,open_no_trade_count,avg_cash_weight_pct,neighbor_count,neighbor_min_wealth_ratio,neighbor_median_terminal_wealth
0,development_walk_forward,False,0.000,8,11:30,0.3,0.6,0.8,5.110048,411.004841,...,1.069906,True,53,28,156.118209,0,42.458671,3,1.0,5.110048
1,development_walk_forward,False,0.005,8,11:30,0.3,0.6,0.8,5.111343,411.134340,...,1.069901,True,53,28,156.118184,4,42.458999,3,1.0,5.111343
2,development_walk_forward,False,0.010,8,11:30,0.3,0.6,0.8,5.110561,411.056136,...,1.069901,True,53,28,156.118184,5,42.459437,3,1.0,5.110561
3,development_walk_forward,False,0.020,8,11:30,0.3,0.6,0.8,5.107993,410.799263,...,1.069901,True,53,28,156.118184,12,42.463226,3,1.0,5.107993

## 最终中文结论

In [4]:
display(Markdown((CARD / 'conclusion.md').read_text(encoding='utf-8')))

# 中文结论

- 做了什么：把第二段模型改成真正的 on-policy 训练。第二段标签只在年度 walk-forward 第一段模型实际触发的交易日生成，不再拿“老师假设触发”的日子冒充模型会遇到的状态。
- 开发期样本：第二段共有 51 条真实动作状态；年度分布为 {'2020': 24, '2021': 3, '2022': 24}。这比旧 off-policy 训练集小得多，因此本卡同时要求至少 20 次开发期动作、连续三个相邻阈值成立，并限制相邻参数最差终值比例。
- 选中参数：第二切点 11:30，Logistic C=0.30，阈值=0.60，临时 beta=0.8，开盘 no-trade band=0.000。
- 开发期 10bp：return=417.2721%，MaxDD=-27.4886%，worst 5d=-11.8589%。参数邻域门已通过，但它证明的是局部稳定性，不是 outer 泛化。
- 外层诊断 10bp：return=543.3420%，MaxDD=-28.1051%，worst day=-9.3837%，CVaR5=-5.2336%，worst 5d=-11.6028%。
- 收益复盘：相对第一段模型增加 0.0000 个百分点，但相对旧 off-policy 二段模型减少 169.3972 个百分点；相对原始直接配置模型仍少 39.3907 个百分点。outer 二段实际仅触发 0 次，证据仍稀疏。
- 25bp 冻结决策压力：return=477.8015%，MaxDD=-29.0887%，worst 5d=-11.7803%。
- no-trade 结论：开发期近优候选最终选择 0 band。0.5%-2% 小带宽不能实质减少换手，3%-5% 大带宽在可行性检查中破坏回撤或相对收益窗口，所以不应把“保持现金”写成独立手工规则；现金仍由模型合法权重直接决定。
- 是否晋升：promoted_research_candidate_stage1_direct_allocation_stage2_gated。Stage 2 开发期校准闸门=False；本次因此自动退回 Stage 1 直接合法权重。原始直接配置收益不是硬晋升目标，真正验收是超过 SOXX、超过 matched-beta 基准并通过风险和成本压力门。
- 数据边界：2023-2026 已被前序实验多次查看，本卡只把它们标记为 reused diagnostic，不能声称是全新未见测试。下一轮应冻结本卡结构，等待新数据或改用跨品种训练后再做一次真正未见验证。
- qlib recorder：f6b09330175e41719886d58ee2d11bec
- 不构成买卖建议。